### ISSUE TITLE
Remove VerKV deadcode

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#10002]
## Feature Request

This is proposing to revert the versioned kv [RFC](https://github.com/tikv/rfcs/pull/44) and the already implemented codes. This feature has not been pushed forward since April 2020, and after deeper consideration, I think it can not achieve the goals described in the RFC. Further, coprocessor plugin, a better solution to the problems verkv trying to solve is working on master.

To remove the code, we may revert these PRs:

- <https://github.com/tikv/tikv/pull/7607>
- <https://github.com/tikv/tikv/pull/7449>
- <https://github.com/pingcap/kvproto/pull/591>

**Comment by andylokandy** [comment]
cc @BusyJay @zhangjinpeng1987 @Connor1996 @overvenus

**Comment by hbina** [comment]
There's a pattern matching in here that causes an error if the changes are reverted because we are iterating over enums provided by kvproto.

Do you want to handle it here (adding unimplemented or wrapper enum that maps A => A') or by removing those enums over there?

**Comment by andylokandy** [comment]
@hbina where is the code you mentioned?

**Comment by hbina** [comment]
This one https://github.com/tikv/tikv/blob/master/src/server/service/kv.rs#L1161

**Comment by hbina** [comment]
I've noticed that a _lot_ of components are using `kvproto`. I assume they all have to be the same version. Shouldn't there be a `kvproto` component that simply reexports the same version? This way its easier to test it because you only need to change this one place instead of coordinating everything.

**Comment by andylokandy** [comment]
ASICS, I think the pattern match you mentions will not be a problem since the VerKV interface is never used. And for your concern on `kvproto`, I don't really mean to `git revert` it but to manually remove the item those PRs added.

**Comment by andylokandy** [comment]
@fredchenbj What do you think?

**Comment by andylokandy** [comment]
@BusyJay So... Let's move on?
