### ISSUE TITLE
Remove report batch split since it only validates the split regions

### ISSUE THREAD

**Issue by rleungx** [tikv/tikv#10021]
### Is your feature request related to a problem? Please describe:

Currently, PD only does a check when handling ReportSplitRequest. See
https://github.com/tikv/pd/blob/36973389887515f19434217fc101e906d86c4f13/server/cluster/cluster_worker.go#L162-L178

### Describe the feature you'd like:
This check can be directly done by TiKV itself and there is no need to use RPC to do it.

**Comment by JayiceZ** [comment]
Can I try it?

**Comment by JayiceZ** [comment]
What do you think of replacing RPC with local check here？：https://github.com/tikv/tikv/blob/e6681ac0c0eeeb0059a14da32471bd7da56ff80e/components/pd_client/src/client.rs#L716
There are two reasons
- Good tests compatibility.  We don't need to modify too much tests codes. Because the behavior is still in pd_client
- If its behavior changes in the future (RPC becomes necessary), it can also be easily migrated

**Comment by BusyJay** [comment]
It was used for analyzing split history and generated fancy animation based on PD split logs. It may not be used any more. I suggest to remove it completely if no one claims to need this. Let's wait for a week.

**Comment by JmPotato** [comment]
> What do you think of replacing RPC with local check here？：
> 
> https://github.com/tikv/tikv/blob/e6681ac0c0eeeb0059a14da32471bd7da56ff80e/components/pd_client/src/client.rs#L716
> 
> 
> There are two reasons
> * Good tests compatibility.  We don't need to modify too much tests codes. Because the behavior is still in pd_client
> * If its behavior changes in the future (RPC becomes necessary), it can also be easily migrated

@JayiceZ I don't think it's a good place to do something other than implementing the PD gRPC calling logic.

Instead, we only call `report_batch_split()` once the worker of the `raftstore` receive a `PdTask::ReportBatchSplit` task. You can check the use of `handle_report_batch_split`.

https://github.com/tikv/tikv/blob/444edc05a88e38231ce2f29de1d08f7b983a96c0/components/raftstore/src/store/worker/pd.rs#L1134-L1142

So, a proper way is to replace the scheduling of the `PdTask::ReportBatchSplit` task inside the `on_ready_split_region` function. We can directly do the check here.

https://github.com/tikv/tikv/blob/444edc05a88e38231ce2f29de1d08f7b983a96c0/components/raftstore/src/store/fsm/peer.rs#L2656-L2666

Then, the old gRPC method code could be safely removed.

**Comment by JmPotato** [comment]
We should not remove this method since PD plans to use the RPC to handle the region split instead of the region heartbeat. See https://github.com/tikv/pd/pull/4230.

**Comment by rleungx** [comment]
According to @JmPotato 's comment, seem we need this interface to do some other things. I'm going to close this issue. @JayiceZ Maybe you can pick up another issue if you want.
