### ISSUE TITLE
CDC old value cache does not work effectively for caching pessimistic txn write

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#10032]
## Bug Report

0% old value cache hit for pessimistic transaction write.

This issue may relate to https://github.com/tikv/tikv/issues/9996 and https://github.com/tikv/tikv/issues/9981.

The left is optimistic transaction writes and the right is pessimistic transaction writes.
![image](https://user-images.githubusercontent.com/2150711/115109723-13c70980-9faa-11eb-851b-424e45a75223.png)
![image](https://user-images.githubusercontent.com/2150711/115109787-66a0c100-9faa-11eb-9df0-8a616b73192d.png)

### What version of TiKV are you using?

master and v5.0.0

### Steps to reproduce

```
# create a changefeed with old value feature.
sysbench --db-driver=mysql --mysql-host=172.16.5.33 --mysql-port=47904 --mysql-user=root --time=15000 --report-interval=10 --threads=64 --mysql-db=test --tables=1 --table-size=6000000 oltp_write_only prepare
sleep 60 && sysbench --db-driver=mysql --mysql-host=172.16.5.33 --mysql-port=47904 --mysql-user=root --time=15000 --report-interval=10 --threads=64 --mysql-db=test --tables=1 --table-size=6000000 oltp_write_only run
```

### What did you expect?

Old value cache works effectively.

**Comment by 5kbpers** [comment]
The pessimistic txn write reads the previous write when acquiring the pessimistic lock so the old value cache will be always missing.
IMO the block cache could be good enough to relieve this situation, because in most cases if an old value is not in the block cache, then a great chance it was evicted from the old value cache.
