### ISSUE TITLE
Proposal - Apply GitHub Discussion for tikv project

### ISSUE THREAD

**Issue by tisonkun** [tikv/tikv#10044]
GitHub provides [GitHub Discussion](https://docs.github.com/en/discussions) for open-ended discussion, it could be used as a communication tool for general discussions, question and answers, and pre-RFCs discussion.

Since we have AskTUG for user facing discussion, we might narrow the scope of GH Discussion as internal discussion, i.e., design and implementation of TiKV functionality only.

According to a previous discussion(https://github.com/tikv/sig-transaction/issues/108) we notice that the discussion for sig-transaction especially pre-RFCs discussion can leverage the power of GH Discussion. And with offline discussion with wider range of sig members, the entry of GH Discussion is better to be set under this repo, i.e., https://github.com/tikv/tikv/.

The benefits are as below.

1. The reason why we create https://github.com/tikv/sig-transaction is we don't have an open-ended discussion way yet. GH Discussion is a good candidate and sig-transaction members are willing to maintain it. We can reduce the burden maintaining a separated repository.
2. So far, as the pre RFCs discussion under sig-transaction repo, it is conventional to just put the RFCs under the same repo, which diverges from https://github.com/tikv/rfcs. We'd better be clear a GH Discussion for pre-RFCs discussion while the formal RFCs are under our rfcs repo so that information can be found together.
3. The pre-RFCs discussion would gain more visibility by having an entry from this repo.

The expected changes are as below.

1. Apply GitHub Discussion for tikv project, with categories:
    1. Transaction // transaction grouped topics, including pre-RFCs and implementation designs
    2. [optional] Coprocessor // maybe more grouped topics.
2. Moving discussion in sig-transaction under GH Discussion, formalizing async-commit RFCs to https://github.com/tikv/rfcs or if it is still unstable, discuss further under GH Discussion.

I think the structure is quite clear and without real discussion we cannot and need not setup a pinned topic to elaborate. 

What do you think?

cc @siddontang @zhangjinpeng1987 @zz-jason @nrc @andylokandy @sticnarf

**Comment by zz-jason** [comment]
what questions are supposed to be asked in this form? what's the expected response time for these discussions?

**Comment by tisonkun** [comment]
> what questions are supposed to be asked in this form? what's the expected response time for these discussions?

@zz-jason I think we can move questions under issue template to this form. the expected response time is NOT PROMISED as now but our committers / contributors will take care of it I think. We don't narrow question scope but only about tikv.

**Comment by andylokandy** [comment]
LGTM. My last concern is not being able to comment on lines of meeting records. But we can figure it out while moving on.

**Comment by tisonkun** [comment]
> LGTM. My last concern is not being able to comment on lines of meeting records. But we can figure it out while moving on.

Quote reply works almost.

**Comment by nrc** [comment]
I think it is worth considering the scenarios for using discussion vs an issue vs a PR (which ends up begin committed).

It's not clear to me at the moment exactly when something should be a discussion vs an issue. The key difference seems to be that issues can be closed, so issues are better suited for things which can be completed or dismissed, whereas discussions are suited for things that remain relevant indefintely. So, Q&A seems much better in discussions than in issues. But design discussion feels like it should be in an issue since at some point the feature is implemented and we want to indicate that.

I believe that for meeting records, they should end up being committed so there is an indexed, permanent record. For meeting records, we want to edit the record to reflect the meeting then freeze that record and preserve it. Committing is ideal for this. If people want to discuss a meeting post hoc, then we can use discussions, but I don't think that is what usually happens.

I'd also like to point out that choosing a venue for discussion is a big decision for a project, this is not simply activating a feature. How discussions take place and are moderated is really important to the culture of a community, and moving venues is painful. We need to decided if we are using GH discussions as well as Slack/Feishu/Discuss or instead of one of them. We need to be sure that discussions fulfill our use cases for the thing being replaced, or if nothing is replaced, then we are willing to accommodate the overhead of an additional venue. I'd personally like to see if GH discussions get widespread use in the world before we commit to using them, but some experimentation in the meantime would be good.

**Comment by tisonkun** [comment]
> It's not clear to me at the moment exactly when something should be a discussion vs an issue.

An issue is for a determinate bug or develop task, while discussion is for questions and open-ended discussion, such as pre-RFC discussion. We use issue for answering question because we don't have discussion before.

> The key difference seems to be that issues can be closed, so issues are better suited for things which can be completed or dismissed, whereas discussions are suited for things that remain relevant indefinitely. So, Q&A seems much better in discussions than in issues. But design discussion feels like it should be in an issue since at some point the feature is implemented and we want to indicate that.

Functionally, you can lock the conversation. On the scenario, it is not the whole lifetime of design discussion. The reason why you have sig-transaction and not just create a pull request to tikv/rfcs from my information source is that transaction design requires more pre discussion so that we don't rush into a formal design which is possibly proven totally in a wrong way soon. Discussion is for "PRE"-RFC, and if you'd like to use mailing list for that or a separated repository for that, it is the same. @andylokandy doesn't like mailing list although [we actually have one](https://lists.tidb.io/g/contributors) and I think the important thing is you guys to talk about the code and the design regardless of the place, but not a separated repository because it is hard to explain to potential contributors SIG or something else up front. Just go to the tikv community or the discussion forum of tikv.

Frankly, I think it is something the same as [Rust Internals](https://internals.rust-lang.org/) but we don't have such a forum yet. A SaaS service like GH Discussion is a fast way to have one.

> I believe that for meeting records, they should end up being committed so there is an indexed, permanent record. For meeting records, we want to edit the record to reflect the meeting then freeze that record and preserve it. Committing is ideal for this. If people want to discuss a meeting post hoc, then we can use discussions, but I don't think that is what usually happens.

If only you use the pattern `[MEETING] YYYY-MM-DD` as the title or topic, you have the same result to be indexed, permanent record and is able to edit the record to reflect the meeting then freeze that record and preserve it. It is the way how community uses mailing list or forum to record their meeting minutes.

But if you have a strong feeling on commit, what if you call for other sigs to use a tikv/meetings repo, which would be similar as tikv/rfcs. If it is a good practice, I think it will be accepted widely.

> I'd also like to point out that choosing a venue for discussion is a big decision for a project, this is not simply activating a feature. How discussions take place and are moderated is really important to the culture of a community, and moving venues is painful. We need to decided if we are using GH discussions as well as Slack/Feishu/Discuss or instead of one of them.

So here is the issue for discussion instead of notifying you the decision, it is the decision making progress itself.

Generally speaking, if under tikv project, every sig has its own preference and does the same thing in different way, our contributor will go crazy to understand so huge tribal knowledge before talking on anything. I'm not a fan of GH Discussion but if talks happen here, contributors gather here. So far, we don't have an active, open communication tool for communicating with contributors outside the sig, but all personal connections. Slack/Feishu is IM tools closed or hard to be found by contributors. They have the same and more overhead than maintaining a mailing list or forum. Though I do think a tikv@lists.tidb.io mailing list should work but GH Discussion works also, the same as a separated repository, but not SIG-A in the way A, SIG-B in the way B because people know tikv as a whole project and have less interest to know the sig things.

> We need to be sure that discussions fulfill our use cases for the thing being replaced, or if nothing is replaced, then we are willing to accommodate the overhead of an additional venue. I'd personally like to see if GH discussions get widespread use in the world before we commit to using them, but some experimentation in the meantime would be good.

And this is a proposal and experimentation because @andylokandy & @sticnarf show their willing to discuss in GH Discussion. We don't have an active, open communication way and we do need to have one.

**Comment by tisonkun** [comment]
@nrc or what if this statement.

> Since we have AskTUG for user facing discussion, we might narrow the scope of GH Discussion as internal discussion, i.e., design and implementation of TiKV functionality only.

**Comment by dragonly** [comment]
LGTM

**Comment by tisonkun** [comment]
> @nrc or what if this statement.
> 
> > Since we have AskTUG for user facing discussion, we might narrow the scope of GH Discussion as internal discussion, i.e., design and implementation of TiKV functionality only.

@nrc and if so, weekly has its own lifecycle and we don't take care of it in this domain.

> what questions are supposed to be asked in this form? what's the expected response time for these discussions?

@zz-jason then questions is only valid if it is about tikv internals, no user questions. We will close discussion and guide it to AskTUG.

**Comment by tisonkun** [comment]
Now we have [a forum](https://internals.tidb.io/) as proposed before, I would suggest to use a universe forum so that we don't have to choose one of our repository hold all discussions, which is possibly confusing.
