### ISSUE TITLE
Incorrect Titan blob files size metrics

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#10052]
### What version of TiKV are you using?
v4.0.x

### Steps to reproduce
Run TiKV with Titan enabled and insert some data. The "Titan - kv -> blob file size" metrics in Grafana is way smaller than the actual `titandb` directory size.

**Comment by zhangjinpeng1987** [comment]
@yiwu-arbug Would you mind to provide the concrete step to reproduce this issue? We follow the step you provided but didn't reproduce the issue. Was there other operations you have did for this cluster?

**Comment by tonyxuqqi** [comment]
Same as https://github.com/tikv/tikv/issues/15971
Fixed.
