### ISSUE TITLE
Write-only variables `info_log_level`s in config

### ISSUE THREAD

**Issue by zhongzc** [tikv/tikv#10070]
## Bug Report

Here are two configs that seem to be write-only/unused.

https://github.com/tikv/tikv/blob/e87b52edfebc787cf6217ebb0a76e563d70b3e1e/src/config.rs#L952

https://github.com/tikv/tikv/blob/e87b52edfebc787cf6217ebb0a76e563d70b3e1e/src/config.rs#L1296

### What version of TiKV are you using?
https://github.com/tikv/tikv/commit/e87b52edfebc787cf6217ebb0a76e563d70b3e1e

### What did you expect?

Cleaner code & fewer useless configs.

**Comment by zhongzc** [comment]
Should we whether make them work, or remove them then use existing unified log level config as it is? @BusyJay

**Comment by BusyJay** [comment]
Isn't it used Rocksdb Option?

**Comment by zhongzc** [comment]
> Isn't it used Rocksdb Option?

orz. I made a stupid mistake. They're write-only on rust level but read on cpp.
