### ISSUE TITLE
<jemalloc>: Malformed conf string in tikv_stderr.log

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#10130]
### What version of TiKV are you using?

$ ./tikv-server --version
TiKV
Release Version:   5.0.0-rc.x
Edition:           Community
Git Commit Hash:   a52d25a2b4c53706046346c522b4dd653d9befc4
Git Commit Branch: master
UTC Build Time:    2021-05-06 08:07:15
Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?

$ cat /proc/cpuinfo | more
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
stepping	: 4
microcode	: 0x2006906
cpu MHz		: 2999.992
cache size	: 25344 KB
physical id	: 0
siblings	: 16
core id		: 0

### Steps to reproduce

deploy a tidb cluster with nightly version, check the tikv_stderr.log

$ cat tikv_stderr.log
<jemalloc>: Malformed conf string
<jemalloc>: Malformed conf string
### What did happened?
If the jemalloc error message can be ignored, it should not be logged into the tikv_stderr.log.

**Comment by YangKeao** [comment]
I wonder why `mem-profiling` is opened by default?

**Comment by BusyJay** [comment]
Probably related to #10150.

**Comment by BusyJay** [comment]
Close as it was a bug of tiup and fixed.
