### ISSUE TITLE
CDC some info level logs are very verbose

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#10255]
## Bug Report

After pausing a changefeed, there are lots of following logs:

```
[2021/05/27 17:49:23.388 +08:00] [INFO] [apply.rs:392] ["region is no longer observerd"] [region_id=10106]
```

### What version of TiKV are you using?

TiKV v4.0.13

### Steps to reproduce

```sh
cdc cli changefeed pause -c "cf"
```

### What did you expect?

No verbose logs

**Comment by ben1009** [comment]
I will take this one

**Comment by SuperSupeng** [comment]
update: I will take this one

**Comment by hi-rustin** [comment]
I tested it locally with the latest tikv (master) and it no longer has this problem.

1. build tikv
2. tiup playground  --tiflash 0 --kv.binpath  ./target/debug/tikv-server
3. build cdc
4. ./cdc server
5. ./cdc cli changefeed create --sink-uri="blackhole://" --changefeed-id="test"
6. create a table
7. insert some data
8. grep "apply.rs" tikv.log
9. no more this log
