### ISSUE TITLE
CDC incremental scan pollutes rocksdb block cache

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#10267]
## Bug Report

CDC incremental scanner sets fill caches (the default behavior of a scanner), it pollutes block cache, and slows down online read services.

https://github.com/tikv/tikv/blob/06c3e76eab84482d49a36d634fb2a6c05995f54b/components/cdc/src/endpoint.rs#L1094-L1097

### What version of TiKV are you using?

4.0.13 and 5.0.2

### Steps to reproduce

Run TiCDC

### What did you expect?

Do not add blocks to block cache.

**Comment by xuhui-lu** [comment]
hey @overvenus , is this issue unassigned? If so, I can help to fix it.

**Comment by lonng** [comment]
@xuhui-lu Yes, this issue have not been assigned to somebody, you can pick this issue. Thanks 👍

**Comment by hi-rustin** [comment]
> hey @overvenus , is this issue unassigned? If so, I can help to fix it.

Try `/assign`. The bot will assign this issue to you.

**Comment by overvenus** [comment]
@xuhui-lu Hi, do you have time to fix this issue in tomorrow? We plan to release its fix in the next release, and tomorrow we will freeze the code.

**Comment by xuhui-lu** [comment]
yea, I will do that tomorrow.
