### ISSUE TITLE
 gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong

### ISSUE THREAD

**Issue by zqchinaone** [tikv/tikv#10293]
## Bug Report

刚克隆的tikv 编译仍然报错。
error: failed to run custom build command for `grpcio-sys v0.9.0+1.38.0`

  --- stderr
  CMake Warning at cmake/protobuf.cmake:51 (message):
    gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
  Call Stack (most recent call first):
    CMakeLists.txt:255 (include)

  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS

### What operating system and CPU are you using?

CentOS Linux release 7.9.2009 (Core)  64位
[root@localhost tikv]# rustc --version
rustc 1.53.0-nightly (16bf626a3 2021-04-14)
[root@localhost tikv]# rustup --version
rustup 1.24.2 (755e2b07e 2021-05-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.53.0-nightly (16bf626a3 2021-04-14)`
[root@localhost tikv]# cargo --version
cargo 1.53.0-nightly (65d57e6f3 2021-04-04)
[root@localhost tikv]# gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
配置为：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
线程模型：posix
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
[root@localhost tikv]# cmake -version
cmake version 3.14.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by zqchinaone** [comment]
参考的https://www.modb.pro/db/54842

**Comment by BusyJay** [comment]
Since TiKV 5.0, g++ 8 is required.

**Comment by zqchinaone** [comment]
> 从 TiKV 5.0 开始，需要 g++8。

谢谢，使用 gcc 8.3 构建成功
