### ISSUE TITLE
TiKV Hiberate Peers metric has negative numbers

### ISSUE THREAD

**Issue by Tammyxia** [tikv/tikv#10330]
### What version of TiKV are you using?
5.0.2

### What operating system and CPU are you using?
Internal big cluster

### Steps to reproduce

- Now 5.0.2 enable hiberate-region and  cdc.hibernate-regions-compatible, check grafana-> TiKV-details-> Server -> Hibernate Peers, there's negative numbers for awaken region count, such as -3.0K

![JE237tRBtU](https://user-images.githubusercontent.com/78345569/121285524-1e01e600-c911-11eb-8f12-bff731fef343.png)

- The second issue is "show config;" list has not hiberate-region config, but only has tikv. cdc.hibernate-regions-compatible.

### What did you expect?

- How can I enable or disable hiberate-region since "show config" has not this config.
- TiKV Hiberate peers has correct statistical information.

**Comment by yiwu-arbug** [comment]
Didn't reproduce on a 1 node cluster (tpcc 5K, 8 hours). Would probably try a larger cluster or try to eyeball what's wrong from the code.
