### ISSUE TITLE
v4.0.11 - Does tikv-client.copr-cache take effect in tikv-server?

### ISSUE THREAD

**Issue by glkappe** [tikv/tikv#10346]
Uesed TiUP-Reload -R tikv

![image](https://user-images.githubusercontent.com/21033020/121625166-871a6280-caa5-11eb-9dec-dd532f58c3f4.png)

![image](https://user-images.githubusercontent.com/21033020/121625034-43bff400-caa5-11eb-90da-36ad57a80140.png)

Please try

**Comment by breeswish** [comment]
Hi, [as the document describes](https://docs.pingcap.com/tidb/stable/tidb-configuration-file#tikv-clientcopr-cache-new-in-v400), copr-cache is a TiDB configuration, so that you need to put it under the `tidb: ...` config item.

**Comment by glkappe** [comment]
i know，but it under the tikv: ... config, it's ok

**Comment by breeswish** [comment]
> i know，but it under the tikv: ... config, it's ok
> 

Under tikv it will not take effect. For example, unknown configurations may be just ignored.

**Comment by glkappe** [comment]
We have plans to do `check config for tikv`, is necessary in any `db`

**Comment by breeswish** [comment]
I think you can go ahead. There is nothing special with TiKV's configuration, since this configuration item just doesn't exist. If you have plans to check configurations, then it will not be a blocking stone.

**Comment by glkappe** [comment]
It's a weird idea. If I don't check the configuration item, it won't take effect. Users may think that this is an invalid optimization. What are the benefits of this to the product.

**Comment by breeswish** [comment]
Sorry I could not get your ideas. What kind of problem are you suggesting? If you think it is unreasonable *not* to check configurations, then you can raise a standalone issue for this behavior. This is unrelated to copr-cache though, since for a "invalid configurations" you can write anything, and you will receive nothing, for example, what you are doing is the same as:

```yaml
tikv:
    enable-super-optimization: true
```
