### ISSUE TITLE
response from raftstore is not deterministic

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#10353]
### What version of TiKV are you using?
v4.0.11, but every version after v3.0.0 is affected.

### What operating system and CPU are you using?
Doesn't matter.

### Steps to reproduce
Produce highly conflict requests and slow down the shutdown process

### What did you expect?
It shutdown successfully, and ACID is still hold.

### What did happened?
Transaction is corrupted by either missing data from default CF or some part of transaction are rollback.

When a node is shutdown without evicting leader, then leader can't know whether a log is committed or not, so to clear callback, it will respond with a stale response to hint the client to retry. StaleCommand error doesn't mean the request will fail eventually or not, it just mean the leader can't handle the request at the moment.

But latch assumes all responses from raftstore are deterministic that if an error is returned, then the write should never be written unless retry. Hence during shutdown, if there are more than two requests in latch queue, then the first two requests will be processed one by one. If the first request is to commit a transaction and the second is to rollback, then the key can be both committed and rollback. If data is large enough to be stored in default cf, error like `DefaultNotFound` will be reported; in all conditions, ACID is broken.

`StaleCommand` can also be called when a peer is about to be destroyed. But we don't allow to remove leader eagerly, so when the error is reported, the leader should either be removed by leader at last term and it won't process any read before being destroy. If the leader is paused, and then being destroyed by a new leader, all following commands won't be committed as it's not leader anymore.

So to fix the problem, we can either make raftstore's response deterministic or make latch to handle undeterministic error.

For the former, an easy fix is to stop invoking any callbacks during shutdown, this can have the side effects raw kv may not know the requests are stopped, instead, it may timeout before next try.

For the latter, latch should not release slot when an undeterministic error is returned. I think it is also necessary after implementing timeout inside raftstore.

There is a similar discussion in #9113, which is discussing deterministic of transaction.

**Comment by BusyJay** [comment]
For existing versions, the get around is always waiting for evicting leaders before restarting a node or use kill -9 to stop tikv service.

**Comment by siddontang** [comment]
oh, I am so surprised that how do we find this bug...

**Comment by BusyJay** [comment]
@lucklove Is it possible to change tiup to turn off TiKV by `kill -9` when transfer leader is not finished?

**Comment by NingLin-P** [comment]
A more easy fix would be to ensure the txn layer (namely the `TxnScheduler` thread group) stopped before `raftstore`, so that invoking the callback when `raftstore` shutdown will become a no-op, it is also more elegant to stop from the outer layer to inner layer. But this can't help the rawkv though, which bypass the txn layer and may still get non-deterministic
 response.

**Comment by BusyJay** [comment]
Deterministic is the fundamental problem of raftstore's callback handling. Even it's fixed for txn, it can still cause problem for any future design. Correctness should not rely on the shutdown order.
