### ISSUE TITLE
upgrade from v4.0.3 to v5.1.0 fail for tikv timeout,report critical config check failed: can't enable ttl on a non-ttl instance

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#10367]
## Bug Report

use tiup to upgrade, init config has been passed, but report "critical config check failed: can't enable ttl on a non-ttl instance" during UpgradeCluster

+ [ Serial ] - InitConfig: cluster=218, user=tidb, host=172.16.6.218, path=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache/alertmanager-9093.service, deploy_dir=/home/tidb/deploy/alertmanager-9093, data_dir=[/home/tidb/deploy/alertmanager-9093/data], log_dir=/home/tidb/deploy/alertmanager-9093/log, cache_dir=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache
+ [ Serial ] - InitConfig: cluster=218, user=tidb, host=172.16.6.218, path=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache/pd-2379.service, deploy_dir=/home/tidb/deploy/pd-2379, data_dir=[/home/tidb/deploy/pd-2379/data], log_dir=/home/tidb/deploy/pd-2379/log, cache_dir=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache
+ [ Serial ] - InitConfig: cluster=218, user=tidb, host=172.16.6.218, path=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache/prometheus-9090.service, deploy_dir=/home/tidb/deploy/prometheus-9090, data_dir=[/home/tidb/deploy/prometheus-9090/data], log_dir=/home/tidb/deploy/prometheus-9090/log, cache_dir=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache
+ [ Serial ] - InitConfig: cluster=218, user=tidb, host=172.16.6.218, path=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache/tidb-4000.service, deploy_dir=/home/tidb/deploy/tidb-4000, data_dir=[], log_dir=/home/tidb/deploy/tidb-4000/log, cache_dir=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache
+ [ Serial ] - InitConfig: cluster=218, user=tidb, host=172.16.6.218, path=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache/grafana-3000.service, deploy_dir=/home/tidb/deploy/grafana-3000, data_dir=[], log_dir=/home/tidb/deploy/grafana-3000/log, cache_dir=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache
+ [ Serial ] - InitConfig: cluster=218, user=tidb, host=172.16.6.218, path=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache/tikv-20160.service, deploy_dir=/home/tidb/deploy/tikv-20160, data_dir=[/home/tidb/deploy/tikv-20160/data], log_dir=/home/tidb/deploy/tikv-20160/log, cache_dir=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache
+ [ Serial ] - InitConfig: cluster=218, user=tidb, host=172.16.6.218, path=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache/tiflash-9000.service, deploy_dir=/home/tidb/deploy/tiflash-9000, data_dir=[/home/tidb/deploy/tiflash-9000/data], log_dir=/home/tidb/deploy/tiflash-9000/log, cache_dir=/home/tidb/.tiup/storage/cluster/clusters/218/config-cache
+ [ Serial ] - UpgradeCluster
Upgrading component tiflash
	Restarting instance 172.16.6.218
	Restart 172.16.6.218 success
Upgrading component pd
	Restarting instance 172.16.6.218
	Restart 172.16.6.218 success
Upgrading component tikv
	Restarting instance 172.16.6.218

Error: failed to restart: tikv 172.16.6.218:20160, please check the instance's log(/home/tidb/deploy/tikv-20160/log) for more detail.: timed out waiting for port 20160 to be started after 2m0s

Verbose debug logs has been written to /home/tidb/.tiup/logs/tiup-cluster-debug-2021-06-16-11-38-17.log.
Error: run `/home/tidb/.tiup/components/cluster/v1.4.0/tiup-cluster` (wd:/home/tidb/.tiup/data/SaSuHva) failed: exit status 1
[2021/06/16 11:50:09.328 +08:00] [WARN] [config.rs:2669] ["deprecated configuration, rocksdb.auto_tuned is no longer used and ignored, please use rocksdb.rate_limiter_auto_tuned."]
[2021/06/16 11:50:09.329 +08:00] [INFO] [config.rs:1953] ["readpool.storage.use-unified-pool is not set, set to true by default"]
[2021/06/16 11:50:09.329 +08:00] [INFO] [config.rs:1976] ["readpool.coprocessor.use-unified-pool is not set, set to true by default"]
[2021/06/16 11:50:09.345 +08:00] [WARN] [config.rs:2663] ["deprecated configuration, raft_store.clean_stale_peer_delay is no longer used and ignored."]
[2021/06/16 11:50:09.345 +08:00] [WARN] [config.rs:2669] ["deprecated configuration, rocksdb.auto_tuned is no longer used and ignored, please use rocksdb.rate_limiter_auto_tuned."]
[2021/06/16 11:50:09.346 +08:00] [FATAL] [setup.rs:282] ["critical config check failed: can't enable ttl on a non-ttl instance"]

**Comment by seiya-annie** [comment]
tikv:
    rocksdb.auto-tuned: false
    rocksdb.raftcf.titan.level-merge: true
    rocksdb.rate-bytes-per-sec: 0KiB
    storage.enable-ttl: true
  pd:

**Comment by BusyJay** [comment]
@Connor1996 PTAL

**Comment by Connor1996** [comment]
It's expected, you shouldn't set the `enable-ttl` field for a existing cluster @seiya-annie

**Comment by BusyJay** [comment]
Close as it's expected, feel free to reopen if have any questions.
