### ISSUE TITLE
Channel full metric needs to be updated

### ISSUE THREAD

**Issue by gengliqi** [tikv/tikv#10377]
### What version of TiKV are you using?
\>= v3.0.0

### What operating system and CPU are you using?
doesn't matter

### Steps to reproduce
Just see the channel full metric

### What did you expect?
The channel full metric should be updated when some channels are full.

### What did happened?
The channel full metric is always empty even when some peer's channel are full.

![image](https://user-images.githubusercontent.com/21253569/122333307-85034880-cf6a-11eb-8f36-5a7ace670efb.png)
I find the `tikv_channel_full` metric has been removed for a long time since v3.0.0. It should be updated.

**Comment by rleungx** [comment]
This metrics has been removed by https://github.com/tikv/tikv/pull/4232.

**Comment by rleungx** [comment]
@BusyJay PTAL, thanks.
