### ISSUE TITLE
Rewrite the descriptions of some monitors

### ISSUE THREAD

**Issue by rleungx** [tikv/tikv#10381]
## Development Task
There are some descriptions of monitors written in Chinese and perhaps we should change it to English. e.g.

<img width="983" alt="Screen Shot 2021-06-17 at 5 55 35 PM" src="https://user-images.githubusercontent.com/35896542/122374973-65cde080-cf95-11eb-87fb-4521eb94d8f0.png">

**Comment by jackwener** [comment]
I am willing to take this task up.
