### ISSUE TITLE
QPS drop a lot when a tikv is killed

### ISSUE THREAD

**Issue by cosven** [tikv/tikv#10408]
### What version of TiKV are you using?
v5.0.2

### What operating system and CPU are you using?
tidbcloud T3.standard

### Steps to reproduce
1. deploy a 2db 6kv(3 zone) cluster on tidbcloud staging environment
2. go-tpc prepare 1000 warehouses 
3. run `go-tpc tpcc --warehouses 1000 run -T 100`
4. kill and start one tikv
5. wait till the tps and duration is stable
6. kill two tikv in one zone

### What did you expect?
1. ~QPS drops not much(about 1/6 in ideal condition) when a tikv is killed.~
2. ~QPS drops not much(about 1/3 in ideal condition) when two tikvs are killed.~
3. The QPS drops less when a tikv is killed than when two tikvs are killed. (FAILED)
4. The QPS should recover in one or two minutes. (PASS)
5. After the killed tikv restart, there should be no jitter in QPS. (FAILED)

### What did happened?
1. QPS drops significantly when a tikv is killed 
![image](https://user-images.githubusercontent.com/4962134/122586325-1bc92580-d08f-11eb-9919-628af29013e8.png)
![image](https://user-images.githubusercontent.com/4962134/122586403-37ccc700-d08f-11eb-9d29-193748d06629.png)

2. When a tikv is killed, the QPS drops more than when two tikvs are killed.
![image](https://user-images.githubusercontent.com/4962134/122586459-4a470080-d08f-11eb-8488-9fc39b68d64a.png)

**Comment by cosven** [comment]
/type bug
/severity critical

Since the QPS drops much more than expected, I give it the `critical` severity.

**Comment by cosven** [comment]
/remove-severity critical
/severity major
/assign @rleungx 

After some investigation and discussion with @rleungx , we change the expectation. Changes are saved in issue body.

**Comment by Connor1996** [comment]
The jitter after TiKV is restarted is probably due to the same reason of https://github.com/tikv/tikv/issues/11320 that
