### ISSUE TITLE
Online changing `resolved-ts.advance-ts-interval` can't take effect immediately

### ISSUE THREAD

**Issue by NingLin-P** [tikv/tikv#10426]
### What version of TiKV are you using?

Master

### What operating system and CPU are you using?

No Matter

### Steps to reproduce

Run following sql
```
set config tikv `resolved-ts.advance-ts-interval`='1h';
set config tikv `resolved-ts.advance-ts-interval`='1s';
```

### What did you expect?

`advance-ts-interval` becomes `1s` after the second sql run

### What did happened?

`advance-ts-interval` becomes `1s` after `1h`, namely after the previous config interval timeout.

**Comment by nolouch** [comment]
Does `set config tikv `resolved-ts`.`advance-ts-interval`='1s';` works?

**Comment by NingLin-P** [comment]
> Does
> 
> ```
> set config tikv `resolved-ts`.`advance-ts-interval`='1s';
> ```
> 
> works?

Yes, it works. It just needs to wait for the previously configured interval timeout to take effect.

For example, the interval was set to `10s`, and we change it to `1s`, the interval will become `1s` after 10s

**Comment by zhongzc** [comment]
I can say `RunnableWithTimer` have the same problem. It also has to first come timeout then take the new interval effect. Maybe some interrupt mechanisms are needed.
