### ISSUE TITLE
Very high kv_get ops on leader node when read stale via 'set transaction ... as of...'

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#10423]
## Bug Report
Env:
   1. Evict leader in 10 and 24, so all leader is in 23.
   2. label the only tidb to dc1, same as tikv-1(.10), so all stale read should be sent to node 10.
 Workload:
      Simulate 500 client to run stale read using following two ways:
set transaction read only as of timestamp now()-interval $stale_second second;
begin;
select * from test3.$table_name;
commit;

set transaction read only as of timestamp now()-interval $stale_second second;
select * from test3.$table_name;

Check monitor found that there is unexpected high kv_get ops in leader node.
![image](https://user-images.githubusercontent.com/9443637/122874762-f45faa80-d365-11eb-8ca2-b44499f1041d.png)

### What version of TiKV are you using?

[root@3e76ac64fb05 bin]# ./tikv-server --version
TiKV
Release Version:   5.1.0
Edition:           Community
Git Commit Hash:   3bbe9da7623dcf1dcb95e8ae18aad9e07fd40163
Git Commit Branch: heads/refs/tags/v5.1.0
UTC Build Time:    2021-06-18 13:51:10
Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What did you expect?
Shouldn't triage the high kv_get in leader, it should be will low.

**Comment by Yisaer** [comment]
root casue: https://github.com/tikv/tikv/issues/10423

**Comment by BusyJay** [comment]
Closed as unrelated to TiKV.
