### ISSUE TITLE
rocksdb: add sst_ingestion_write_global_seqno option and set it to false by default

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#10430]
## Development Task
Older versions of RocksDB write global seqno (the sequence number of the ingested SST file) in the ingested SST file, which incur an IO while holding db_mutex (per RocksDB instance global mutex), which could cause latency jitter for RocksDB writes. Newer versions of RocksDB provide the `write_global_seqno` (see https://github.com/tikv/rocksdb/blob/6.4.tikv/include/rocksdb/options.h#L1500) as an option and allow disabling it. When disabled, RocksDB instead write the global seqno into manifest file, which is without holding db_mutex. We need to add the corresponding option in rust-rocksdb (see https://github.com/tikv/rust-rocksdb/blob/master/src/rocksdb_options.rs#L2029) then in TiKV (to the `DbConfig` struct, see https://github.com/tikv/tikv/blob/master/src/config.rs#L889). Let's name this option `sst_ingestion_write_global_seqno` and default it to false. Related interfaces in engine trait (components/engine_traits) also need to be updated. Then whenever ingest SST is called, set the corresponding option to RocksDB.

We need to provide it as an option instead of just hard-code the option value to false. This is to provide some backward compatibility. TiKV < v3.0 (e.g. v2.1) was on RocksDB v5.15, which does not support this option and wouldn't be able to read the DB after using this option. But the need to downgrade to v2.1 should be rare.

**Comment by yiwu-arbug** [comment]
@v01dstar

**Comment by hicqu** [comment]
After it's introduced, `reset_global_seq` is not necessary?
![图片](https://user-images.githubusercontent.com/8407317/124266755-f3025f00-db69-11eb-8ace-1b806e76719a.png)

It's in `components/sst_importer/src/sst_importer.rs:669`.

**Comment by yiwu-arbug** [comment]
> After it's introduced, `reset_global_seq` is not necessary?
> ![图片](https://user-images.githubusercontent.com/8407317/124266755-f3025f00-db69-11eb-8ace-1b806e76719a.png)
> 
> It's in `components/sst_importer/src/sst_importer.rs:669`.

yes, `reset_global_seq` would not be necessary with `write_global_seqno=false`. However to keep backward compatibility let's keep the logic. @v01dstar can you add the following comments around `reset_global_seq` call in your PR?
```
When ingest with `write_global_seqno=true` and the ingestion fail, to allow us retry the ingestion with the same file, we need to reset global seqno to 0. If we later only allow to use `write_global_seqno=false`, we can remove the `reset_global_seq` call.
```
