### ISSUE TITLE
TiKV OOM under high pressure

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10492]
### What version of TiKV are you using?
[root@centos76_vm tikv-20160]# ./bin/tikv-server -V
TiKV 
Release Version:   5.0.3
Edition:           Community
Git Commit Hash:   63b63edfbb9bbf8aeb875aad28c59f082eeb55d4
Git Commit Branch: heads/refs/tags/v5.0.3
UTC Build Time:    2021-06-28 10:06:29
Rust Version:      rustc 1.51.0-nightly (bc39d4d9c 2021-01-15)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
4 core、8G mem for per node
top as follow
[topology.txt](https://github.com/tikv/tikv/files/6739984/topology.txt)

### Steps to reproduce
1. run workload（3PD、3KV、1TiDB）
- sysbench --config-file=config oltp_point_select --tables=32 --table-size=10000000 --auto_inc=yes prepare
   threads=8
- /root/.tiup/components/bench/v1.5.1/tiup-bench tpcc -H 172.16.6.161 -P 4000 -D tpcc --warehouses 1000 -T 32 prepare

### What did you expect?
all node keep health always

### What did happened?
two TiKV OOM
<img width="728" alt="oom" src="https://user-images.githubusercontent.com/84712107/123943026-4a6bc800-d9ce-11eb-8057-a2c6a4a7f1ac.png">
<img width="1070" alt="oom1" src="https://user-images.githubusercontent.com/84712107/123943374-adf5f580-d9ce-11eb-9304-d855af315dbc.png">

**Comment by hicqu** [comment]
Closed by #10860.
