### ISSUE TITLE
statistics: write qps in query stats is inconsistent with Prometheus

### ISSUE THREAD

**Issue by lhy1024** [tikv/tikv#10507]
### What version of TiKV are you using?
master

### Steps to reproduce
sysbench test

### What did you expect?

consistent

### What did happened?
![image](https://user-images.githubusercontent.com/19542290/124239976-da378080-db4c-11eb-9f86-75cdac90a2f1.png)

**Comment by nolouch** [comment]
How about CPUs？

**Comment by nolouch** [comment]
It's strange about apply CPU.
![image](https://user-images.githubusercontent.com/6428910/124374444-c404fe00-dccd-11eb-8ada-5f6337406e80.png)
