### ISSUE TITLE
Remove all request snapshot code

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#10526]
### Is your feature request related to a problem? Please describe:
Request snapshot is used to request a snapshot explicitly from follower to fix problems like corruption. But the API has never been used or tested. Technically, it's an unreleased feature. I propose to remove all related code for now to make code base clean.

**Comment by BusyJay** [comment]
`grep request_snapshot` should find all occurrences.

/cc @overvenus

**Comment by overvenus** [comment]
LGTM!

**Comment by jiangyuzhao** [comment]
Could I participate in this task?

**Comment by BusyJay** [comment]
Sure!
