### ISSUE TITLE
destroy uninitialized peer can make it possible to recreate old peer

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#10533]
### What version of TiKV are you using?
v5.0.3

### What operating system and CPU are you using?
Linux

### Steps to reproduce
Supposing there are 4 stores 1, 2, 3, 4. And we schedule a region to add peer a, b, c on store 1, 2, 3 respectively. Since then a is isolated, b is leader. b decides to remove c and add d on store 4. It can succeed as quorum remains connected during the whole time. After that, 2 adds a new learner e on store 3, but remove it immediately before sending any snapshot to it. So e is uninitialized. After 2 hours, e will ask PD and find itself deleted, so will mark itself as tombstone with an **empty region**. If a is recovered and send vote requests to c, the messages can pass the peer id check and epoch check as region is uninitialized. So c will be recreated as an uninitialized peer and vote for a. Then a will become leader. There will be two leaders a and b for the region.

### What did you expect?
Only one leader at a term and the cluster work correctly.

### What did happened?
Correctness is broken.

**Comment by BusyJay** [comment]
One possible solution is adding the current peer into peer list when writing tombstone. So the peer id check will not pass. Note epoch should remain unchanged, which should be 0, to avoid wrong mapping between epoch and peer lists.

The long term solution is introducing a new uninitialized state explicitly instead of relying on the peer lists. Introducing uninitialized state should also solve other problems caused by uninitialized peer like #9579, #3572.

**Comment by NingLin-P** [comment]
Perhaps a more easy solution for this case would be don't mark an uninitialized peer as tombstone when it is destroyed, just like how we don't persist any data for an uninitialized peer when it is not destroyed.

Since the region is empty, having and haven't the tombstone state is the same for the epoch check and the peer id check, 
 except that having the tombstone state has the damage of overwriting the previous peer state. 

But we do need a long term solution to fix #9579 and #3572 though.

**Comment by PatrickNicholas** [comment]
Our previous experience is that after deleting a peer, we need to save its ID. When trying to create a peer, we need to check whether it has been deleted before. Can we adopt this solution?
@BusyJay @NingLin-P

**Comment by BusyJay** [comment]
> ...we need to save its ID.

It's already saved, the problem is an empty region state corrupts the record.

> Since the region is empty, having and haven't the tombstone state is the same for the epoch check and the peer id check

It's not true, an uninitialized peer can also vote, not persisting tombstone state doesn't solve the problem.

@PatrickNicholas do you want to have a try on this? "adding the current peer into peer list when writing tombstone" should solve the problem.

**Comment by PatrickNicholas** [comment]
> @PatrickNicholas do you want to have a try on this? "adding the current peer into peer list when writing tombstone" should solve the problem.

Ok, I will try to fix this problem.

**Comment by PatrickNicholas** [comment]
> It's already saved, the problem is an empty region state corrupts the record.

Maybe I didn't make it clear, once a peer is deleted(data is erased), it should never be added back. The most intuitive way is to save the tombstone state with peer's id rather than region id.
