### ISSUE TITLE
Unstable test `raftstore::test_stale_peer::test_stale_learner`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#10547]
## Bug Report

In ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3925/pipeline

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
