### ISSUE TITLE
Unstable test `raftstore::test_replica_read::test_read_index_out_of_order`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#10550]
## Bug Report
in ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3951/pipeline

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
