### ISSUE TITLE
Tikv node oom happened while dm job working

### ISSUE THREAD

**Issue by XuJianxu** [tikv/tikv#10580]
### What version of TiKV are you using?

4.0.10
### What operating system and CPU are you using?

Linux - Intel Core Processor (Haswell, IBRS)
### Steps to reproduce

create 200mysql upstream, 200dm-worker 100*tasks to migrate data to downstream tidb.
### What did you expect?
No error happened, tidb can work properly.
### What did happened?
DM: v5.0.0-nightly-20210715

Refer to TiKV and DM-worker logs below:
[dm-worker.log](https://github.com/tikv/tikv/files/6829153/dm-worker.log)
[tikv.log](https://github.com/tikv/tikv/files/6829154/tikv.log)

**Comment by XuJianxu** [comment]
reproduce this Scenario
![image](https://user-images.githubusercontent.com/23207893/126298173-ba900382-6284-4a94-b46b-cb6c1be2a3a7.png)

**Comment by fubinzh** [comment]
TiKV OOM issue seen again while using DM to sync upstream ( 2 MariaDB) to TiDB.

[Thu Jul 22 17:04:56 2021]  [<ffffffffa35c2cc6>] out_of_memory+0x4b6/0x4f0
[Thu Jul 22 17:04:56 2021] Out of memory: Kill process 31235 (tikv-server) score 507 or sacrifice child
[Fri Jul 23 00:02:22 2021]  [<ffffffffa35c2cc6>] out_of_memory+0x4b6/0x4f0
[Fri Jul 23 00:02:22 2021] Out of memory: Kill process 31015 (tikv-server) score 496 or sacrifice child

<img width="923" alt="tikvoom" src="https://user-images.githubusercontent.com/7403864/126729482-b8443c98-dd1e-43eb-a449-d4b854718931.png">

[tikv.log.1.log](https://github.com/tikv/tikv/files/6866216/tikv.log.1.log)

[tikv.log.2.log](https://github.com/tikv/tikv/files/6866218/tikv.log.2.log)

[dm-worker-1.log](https://github.com/tikv/tikv/files/6866219/dm-worker-1.log)

[dm-worker-2.log](https://github.com/tikv/tikv/files/6866220/dm-worker-2.log)

**Comment by hicqu** [comment]
The reason is deploying 2 TiKV instance on 1 machine but block-cache is not adjusted correctly.
