### ISSUE TITLE
Checks before starting TiKV

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#1059]
Before starting TiKV with existing RocksDB, we should do some checks, including:
1. Is the db created by a newer version of TiKV?
2. Is the dynamic linked RocksDB library supported?
3. Does the db need to be modified or cleaned up before providing service?

**Comment by Ishiihara** [comment]
@siddontang I am interested in learning more about TiKV, can you assign this to me?

**Comment by siddontang** [comment]
Thanks @Ishiihara 

But we have not figured out a way to handle this issue yet. :sob: 

Maybe we can check dynamic linked RocksDB version first,  we can get the minimum version from rust-rocksdb, then check with current RocksDB. 

/cc @BusyJay

**Comment by Hoverbear** [comment]
This is closable since we use our own RocksDB now.
