### ISSUE TITLE
Speed up evict leader scheduler

### ISSUE THREAD

**Issue by NingLin-P** [tikv/tikv#10602]
### Is your feature request related to a problem? Please describe:

When restart/offline a TiKV instance, PD need to evict leader from that instance in case the region is unavailable until the new  leader elected. Evict leaders could take a long time if there are a large number of leaders in the store and hence slow down the restart/offline process.

### Describe the feature you'd like:

When transfer leadership, after some checks passed, the follower needs to append all lagging logs before start election by `MsgTimeoutNow`, although the number of lagging logs is limited by `raftstore.leader-transfer-max-log-lag`, it can still cost time. And since PD just randomly pick the transferee for the evict leader scheduler, we can let TiKV decide to transfer leadership to the peer that has the least lagging logs to speed up the process.

So PD sends the `TransferLeader` command with the store/peer list (to filter some store that we can't transfer because violate restraints like placement rules) that TiKV can choose to transfer, and TiKV decide to transfer leadership based on the store/peer list and the lagging logs.

**Comment by MrCroxx** [comment]
May I try to do this?

**Comment by NingLin-P** [comment]
> May I try to do this?

Sure!

**Comment by MrCroxx** [comment]
@NingLin-P Should I replace the `peer` field in the proto file with repeated `peers` filed, or add a new field? I found both kinds of modification in proto history.

**Comment by MrCroxx** [comment]
> @NingLin-P Should I replace the `peer` field in the proto file with repeated `peers` filed, or add a new field? I found both kinds of modification in proto history.

I found the answer [here](https://github.com/pingcap/kvproto/pull/806#issuecomment-914194641). Seems replacing the unrepeatable filed `peer` with repeatable `peers` is fine.

**Comment by MrCroxx** [comment]
With the prototype, PD will pass a valid leader candidate list to the origin leader store to handle evict-leader operation. The origin leader store (TiKV instance) will use its local Raft `ProgressTracker` to decide which candidate has the largest `matched` index, and transfer leadership to it (with `pre_transferleader`).

The prototype can reduce ~50% time that `TransferLeader` needed before under heavy workload.

I benched the prototype with 130k+ 512KB regions, 3 TiKV nodes. First I ran 800 threads 500 warehouse tpcc workload (before 23:31) and set an evict-leader-scheduler on one store. In the following metrics we can see that `TransferLeaderV2` takes 50% less time to finish (P99) than `TransferLeader` (`TransferLeaderV2` comes from evict-leader, `TransferLeader` comes from balance-leader). At 23:31, I terminated tpcc workload, and the P99 finish duration of the both dropped to the same level.

![image](https://user-images.githubusercontent.com/22407295/136896692-004827db-4bbf-42cd-b1d6-15732d4a3cd7.png)

**Comment by MrCroxx** [comment]
> @NingLin-P : Cloud you also comparing `TransferLeader` and `TransferLeaderV2` that both come from the `evict-leader` scheduler, to see more clearly about the improvement of `evict-leader`

The previous benchmark is not accurate, for `TransferLeader` operation step is caused not only by `evict-leader`, but `balance-leader` as well, and those from `balance-leader` is much slower. I ran a new benchmark to better compare the new transfer leader implementation.

The new benchmark uses uniform YCSB on raw TiKV as the workload to better distribute the load across regions. All other schedulers are removed during evicting leaders to reduce noises. The operation order in the following metrics is: `evict-leader-v1 (with YCSB) => balance-leader (no workloads, stands for transfer leader v1 under no workload) => evict-leader-v2 (with YCSB)`

Summary:

1. evict-leader-v2 is about 2x faster than v1 (under uniform request distribution).
2. P80 TransferLeaderV2 is 2~3x faster than v1, and is competitive with v1 under no workload (about 500ms).
3. TransferLeaderV2 tail latency (>P80) is worse than V1.

![image](https://user-images.githubusercontent.com/22407295/137265451-9ce3ed01-6d92-4f41-bd6c-e33081307205.png)

![image](https://user-images.githubusercontent.com/22407295/137267110-19d7de9f-4b00-4fe5-81c7-7ad2e295ece8.png)
