### ISSUE TITLE
Support changing CDC related configs dynamically 

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#10645]
### Is your feature request related to a problem? Please describe:

Support changing CDC configs dynamically via SQL. https://docs.pingcap.com/tidb/stable/dynamic-config

Example: 
https://github.com/tikv/tikv/blob/3f0c72a389b4987c27b3dc42d8931a7ecaff9638/components/server/src/server.rs#L759-L762

TiCDC also need a config manager to update its config.

**Comment by overvenus** [comment]
PTAL @hi-rustin

**Comment by hi-rustin** [comment]
/assign 

I will take a look.
