### ISSUE TITLE
After upgrading from 5.1.0 to the 5.2.0 master, run sysbench insert and query，some tikv crash repeatedly

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10694]
### What version of TiKV are you using?
| Release Version: v5.2.0-alpha-545-g30cf15a59
Edition: Community
Git Commit Hash: 30cf15a59db11c34ffe05fc926152a43327eaa61
Git Branch: HEAD
UTC Build Time: 2021-08-08 18:30:45
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

### What operating system and CPU are you using?
2 tidb，3 pd，4 tikv
k8s环境
tikv：8G、4 cores

### Steps to reproduce
case：TiKVWorkloadStress003
1、upgrading from 5.1.0 to the 5.2.0 master
2、run sysbench insert and query
tabNum：512
tableSize：1000000000
threads：512
3、query
select * from sbtest1 limit 1,100

### What did you expect?
tikv is normal

### What did happened?
some tikv crash（oom） repeatedly
<img width="576" alt="stress003" src="https://user-images.githubusercontent.com/84712107/128792645-0272d099-e9c4-43b6-9fcd-7c219309290f.png">
<img width="576" alt="stress003_mem" src="https://user-images.githubusercontent.com/84712107/128793556-87b9aa57-db15-4877-aa69-0f2e3d7a8753.png">

**Comment by hicqu** [comment]
Seems `block-cache-size` is not configured correctly:
![图片](https://user-images.githubusercontent.com/8407317/128808430-e39ee1bc-5d05-4ae9-8c3a-06ce988096e0.png)

**Comment by hicqu** [comment]
@Lily2025 thanks for your report! It's a bug. I will fix it later.
