### ISSUE TITLE
After the disk is full, create table、drop table、truncate table operators are all stuck，and no any prompt message

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10708]
### What version of TiKV are you using?
[root@centos76_vm bin]# ./tikv-server -V
TiKV
Release Version: 5.1.0-alpha
Edition: Community
Git Commit Hash: d78394c
Git Commit Branch: heads/refs/tags/v5.2.0
UTC Build Time: 2021-08-09 12:08:07
Rust Version: rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features: jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile: dist_release

### What operating system and CPU are you using?
tiup部署
1 tidb，1pd，3 tikv
tikv：8G、4 cores

### Steps to reproduce
1、run sysbench insert
threads=512
tableNum = 512
tableSize = 10000000000

### What did you expect?
after disk is full：
1、the space statistics are normal
2、create table fail，and there is correct prompt message
3、drop table、truncate table can success

### What did happened?
logs：
[2021/08/11 17:57:08.933 +08:00] [ERROR] [region_request.go:955] ["tikv reports `DiskFull` not retry"] [diskFull="store_id:4 reason:\"propose failed: disk full\" "] [ctx="region ID: 6969, meta: id:6969 start_key:\"t\\200\\000\\000\\000\\000\\000\\000\\031_r\\200\\000\\000\\000\\000\\004N\\333\" end_key:\"t\\200\\000\\000\\000\\000\\000\\003x\" region_epoch:<conf_ver:5 version:394 > peers:<id:6970 store_id:1 > peers:<id:6971 store_id:4 > peers:<id:6972 store_id:5 > , peer: id:6971 store_id:4 , addr: 172.16.6.194:20160, idx: 0, reqStoreType: TiKvOnly, runStoreType: tikv"] 
after disk is full：
1、the space statistics are abnormal
<img width="912" alt="空间" src="https://user-images.githubusercontent.com/84712107/129135750-8adf375a-2198-497c-8a2f-1b7ee28a9609.png">
2、create table fail，and there is correct prompt message
<img width="489" alt="create tab" src="https://user-images.githubusercontent.com/84712107/129135769-c82fd646-7af5-486e-9f85-682948270f6c.png">
3、drop table、truncate table can not success
<img width="224" alt="drop tab" src="https://user-images.githubusercontent.com/84712107/129135801-bc694d6a-41e6-4c7e-8072-92be8f9a749a.png">
<img width="243" alt="truncate tab" src="https://user-images.githubusercontent.com/84712107/129135938-e9a378b1-a7e8-4ee5-a9c8-19053195b209.png">

**Comment by tier-cap** [comment]
The latest version will failed to drop table when tikv is disk full.
It has already been fixed, and pr is reviewing. https://github.com/tikv/tikv/pull/10693

**Comment by tisonkun** [comment]
@Lily2025 @tier-cap is this bug related to https://github.com/tikv/tikv/issues/10537?

**Comment by zhangjinpeng1987** [comment]
@tier-cap Please make sure this issue is updated since it is a critical bug. If this bug will not trigger in master please lower it serverity, I remember that this new feature is close by default now and the user has no way to open it.

**Comment by tier-cap** [comment]
can close it by https://github.com/tikv/tikv/pull/10833 and https://github.com/pingcap/tidb/pull/27685

**Comment by VelocityLight** [comment]
solved at 11240
