### ISSUE TITLE
TiKV oom when inject bandwidth limit

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10728]
### What version of TiKV are you using?
[root@copy-of-vm-ee-centos76-v1 bin]# ./tikv-server -V
TiKV
Release Version:   5.1.0-alpha
Edition:           Community
Git Commit Hash:   d78394cb8dcc3e55a53d34378253a0888d26b438
Git Commit Branch: heads/refs/tags/v5.2.0
UTC Build Time:    2021-08-09 12:08:07
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
tiup ：
1PD
1TiDB
3TiKV
all node：500G NVME、4 cores、8G mem

### Steps to reproduce
1、run sysbench oltp_point_select prepare
    tableNum = 512
    tableSize = 10000000000
    threads=128
2、inject bandwidth limit （mybe too low）
echo "8:0 20971520" > /sys/fs/cgroup/blkio/g1/blkio.throttle.write_bps_device
echo $(pgrep tikv-server) > /sys/fs/cgroup/blkio/g1/cgroup.procs

### What did you expect?
tikv is normal

### What did happened?
TiKV oom
<img width="456" alt="oom " src="https://user-images.githubusercontent.com/84712107/129331328-62f6cdf9-42d9-40b9-8d1f-dbf0b3922ed7.png">
![log](https://user-images.githubusercontent.com/84712107/129331350-c17c904e-d0b4-4479-aeee-9d3091a50fa0.png)

**Comment by hicqu** [comment]
Similar as #10927 . Can't do anything without heap profiling.
