### ISSUE TITLE
After a slow node appears, the alarm that prompts the user to open the slow node processing is not generated

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10737]
### What version of TiKV are you using?
TiKV
Release Version: 5.1.0-alpha
Edition: Community
Git Commit Hash: d78394c
Git Commit Branch: heads/refs/tags/v5.2.0
UTC Build Time: 2021-08-09 12:08:07
Rust Version: rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features: jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile: dist_release

### What operating system and CPU are you using?
tiup ：
1PD
1TiDB
3TiKV
all node：500G NVME、4 cores、8G mem

### Steps to reproduce
1、run sysbench prepare
tableNum = 512
tableSize = 10000000000
threads=128
sysbench --config-file=/root/config oltp_point_select --tables=512 --table-size=10000000000 --auto_inc=true prepare
2、inject bandwidth limit
echo "8:0 104857600" > /sys/fs/cgroup/blkio/g1/blkio.throttle.write_bps_device
echo $(pgrep tikv-server) > /sys/fs/cgroup/blkio/g1/cgroup.procs

### What did you expect?
After a slow node appears, the alarm that prompts the user to open the slow node processing is not generated

### What did happened?
the alarm that prompts the user to open the slow node processing is generated and show how to open the way

**Comment by 5kbpers** [comment]
Should be fixed by https://github.com/tikv/pd/pull/3978

**Comment by 5kbpers** [comment]
Close fixed issue.
