### ISSUE TITLE
region cannot be INTEGRITY_OVER_LABEL in dr-auto-sync

### ISSUE THREAD

**Issue by nolouch** [tikv/tikv#10772]
### What version of TiKV are you using?
5.2 release branch

### Steps to reproduce
 
manually PD leader transfer during async, and then recover the network.
### What did you expect?
async-> sync-recover -> sync

### What did happened?
async-> sync-recover(blocking)
and found some regions blocking with SIMPLE_MAJORITY. such as :
```
{
  "id": 18412,
  "start_key": "7480000000000000FF795F698000000000FF0000010380000000FF0007A50503800000FF00004F93B6000000FC",
  "end_key": "7480000000000000FF795F698000000000FF0000010380000000FF0007A8F703800000FF000036319E000000FC",
  "epoch": {
    "conf_ver": 68,
    "version": 55
  },
  "peers": [
    {
      "id": 18413,
      "store_id": 82,
      "role_name": "Voter"
    },
    {
      "id": 18414,
      "store_id": 5,
      "role_name": "Voter"
    },
    {
      "id": 18415,
      "store_id": 81,
      "role_name": "Voter"
    }
  ],
  "leader": {
    "id": 18415,
    "store_id": 81,
    "role_name": "Voter"
  },
  "written_bytes": 0,
  "read_bytes": 0,
  "written_keys": 0,
  "read_keys": 0,
  "approximate_size": 64,
  "approximate_keys": 1016577,
  "replication_status": {
    "state": "SIMPLE_MAJORITY",
    "state_id": 20243
  }
}
```

```
{
  "replication-mode": "dr-auto-sync",
  "dr-auto-sync": {
    "label-key": "zone",
    "primary": "cn-west-1",
    "dr": "cn-east-1",
    "primary-replicas": 2,
    "dr-replicas": 1,
    "wait-store-timeout": "1m0s",
    "wait-sync-timeout": "1m0s",
    "wait-async-timeout": "2m0s"
  }
}

{
  "mode": "dr-auto-sync",
  "dr-auto-sync": {
    "label_key": "zone",
    "state": "sync_recover",
    "state_id": 20243,
    "total_regions": 566,
    "synced_regions": 36,
    "recover_progress": 0.9858657
  }
}

```
details log about this region: 
[store81_18412.log](https://github.com/tikv/tikv/files/7008643/store81_18412.log)
[stores.log](https://github.com/tikv/tikv/files/7008658/stores.log)

**Comment by mayjiang0203** [comment]
Some of region stay in SIMPLE_MAJORITY even pd work in sync mode.
[2021/08/19 14:04:51.975 +08:00] [INFO] [pdutil.go:254] ["No need to wait to recover to sync,cur stat:sync"]
[2021/08/19 14:04:52.154 +08:00] [WARN] [pdutil.go:364] ["There are 7 regions not in expected status."]
[2021/08/19 14:04:52.154 +08:00] [WARN] [pdutil.go:365] ["Regions stay not in expected status:NTEGRITY_OVER_LABEL|UNKOWN v%!(NOVERB)%!(EXTRA map[int]string=map[188:SIMPLE_MAJORITY 224:SIMPLE_MAJORITY 228:SIMPLE_MAJORITY 232:SIMPLE_MAJORITY 252:SIMPLE_MAJORITY 307:SIMPLE_MAJORITY 319:SIMPLE_MAJORITY])"]
