### ISSUE TITLE
how a secondary index works

### ISSUE THREAD

**Issue by dzwinning** [tikv/tikv#10788]
## Question

let's say we have a table like:uid,phone, uid is primary key, and phone is secondary index, so we have key-value pairs like:
uid->phone
phone->uid

a row is inserted into the table:
insert into table values (20, 180123)；

let's assume that the row is writed to memtable, but not sstable yet

at the same time, there is a query like:
select * from table where phone=180123;

question:
how the select query get data with the secondary index "phone"? (in orther words: how the select works in memtable or immutable?)

thanks

**Comment by zz-jason** [comment]
The "index" concept is on the TiDB side. An index is also stored in key-value pairs in TiDB. You can take [TiDB encoding rules](https://docs.pingcap.com/tidb/stable/troubleshoot-hot-spot-issues#tidb-encoding-rules) for details.

To utilize the secondary index, TiDB firstly scans the index key-value pairs, then looks up the table key-value pairs based on the result of the index key-value pairs.

**Comment by dzwinning** [comment]
> The "index" concept is on the TiDB side. An index is also stored in key-value pairs in TiDB. You can take [TiDB encoding rules](https://docs.pingcap.com/tidb/stable/troubleshoot-hot-spot-issues#tidb-encoding-rules) for details.
> 
> To utilize the secondary index, TiDB firstly scans the index key-value pairs, then looks up the table key-value pairs based on the result of the index key-value pairs.

“An index is also stored in key-value pairs in TiDB.”very helpful！！thank you so much！
