### ISSUE TITLE
*: Expansion fails when TiKV diskusage is already full

### ISSUE THREAD

**Issue by tier-cap** [tikv/tikv#10868]
### What version of TiKV are you using?

$./tikv-server --version
TiKV 
Release Version:   5.1.0-alpha
Edition:           Community
Git Commit Hash:   73f5375ebb8c0585fe47206920e39188bb4af95a
Git Commit Branch: feature-diskcap-cloud-fix
UTC Build Time:    2021-08-26 08:28:08
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           release
FYI: TiKV disk full feature has been closed in v5.2, so you should remove the mock code to use this feature.

### What operating system and CPU are you using?

N/A
### Steps to reproduce

1. Tiup cluster deploys 3 nodes.
2. Put data until TiKV disk full happens.
3. When some other user data add in this disk, which leads to diskusage very nervous
4. Exec expansion, add another TiKV, but there are no data migrated.
### What did you expect?
1. Can expand successfully, space can reclaim.

### What did happened?
1. No expansion, no data migration, no space reclaim.
![image](https://user-images.githubusercontent.com/80742231/131463743-96995475-56bc-4015-9ca9-3c893a709b1e.png)
![image](https://user-images.githubusercontent.com/80742231/131463789-444a50ce-0743-4eb2-bdd0-c8e3304e2e61.png)

**Comment by tisonkun** [comment]
@tier-cap I think this is part of #10537 ?
