### ISSUE TITLE
tikv panicking on startup

### ISSUE THREAD

**Issue by Adam-Kulju** [tikv/tikv#10897]
### What version of TiKV are you using?

5.2.0

### What operating system and CPU are you using?

Linux Subsystem for Windows, Ubuntu 20.0.4 LTS
As for the CPU info, I have 4 processors each with these specs:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 61
model name      : Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
stepping        : 4
microcode       : 0xffffffff
cpu MHz         : 2594.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap intel_pt ibrs ibpb stibp ssbd
bogomips        : 5188.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

### Steps to reproduce

I'm not sure what has gone wrong, running "tiup playground" used to work just fine but since a couple days ago whenever I run it TiKV crashes. I have tiup updated to the newest version as well.

### What did you expect?
I expect the instance to start normally, like it used to when I first downloaded TiUP and run "tiup playground"
### What did happened?
Now whenever I try to run it here's what happens:

adam@DESKTOP-N3M2KTC:~$ tiup playground
Starting component `playground`: /home/adam/.tiup/components/playground/v1.5.6/tiup-playground
Using the version v5.2.0 for version constraint "".

If you'd like to use a TiDB version other than v5.2.0, cancel and retry with the following arguments:
    Specify version manually:   tiup playground <version>
    Specify version range:      tiup playground ^5
    The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance
Start tikv instance
Start tidb instance
tikv quit: exit status 101
thread 'main' panicked at 'assertion failed: ret.contains_key(*controller)', components/tikv_util/src/sys/cgroup.rs:184:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...
check detail log from: /home/adam/.tiup/data/ShtcUUR/tikv-0/tikv.log
Waiting for tidb instances ready
127.0.0.1:4000 ... ⠴

Run with RUST_BACKTRACE=full:
adam@DESKTOP-N3M2KTC:~$ RUST_BACKTRACE=full tiup playground
Starting component `playground`: /home/adam/.tiup/components/playground/v1.5.6/tiup-playground
Using the version v5.2.0 for version constraint "".

If you'd like to use a TiDB version other than v5.2.0, cancel and retry with the following arguments:
    Specify version manually:   tiup playground <version>
    Specify version range:      tiup playground ^5
    The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance
Start tikv instance
Start tidb instance
Waiting for tidb instances ready
127.0.0.1:4000 ... ⠏
tikv quit: exit status 101
  45:     0x7fb64e00110a - tikv_server::main::h64f2cb4cacd69b59
                               at /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tikv/cmd/tikv-server/src/main.rs:159:22
  46:     0x7fb64dfea373 - core::ops::function::FnOnce::call_once::he841198ab39dc2ae
                               at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
  47:     0x7fb64dfea373 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8774cf5834ef8cd1
                               at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/sys_common/backtrace.rs:125:18
  48:     0x7fb64e003824 - main
  49:     0x7fb64d7070b3 - __libc_start_main
  50:     0x7fb64dfe9487 - <unknown>
  51:                0x0 - <unknown>
Waiting for tidb instances ready
127.0.0.1:4000 ... Error
To view the dashboard: http://127.0.0.1:2379/dashboard
PD client endpoints: [127.0.0.1:2379]
To view the Prometheus: http://127.0.0.1:9090
To view the Grafana: http://127.0.0.1:3000

I am guessing that this is a problem with something on my machine rather than a bug in the code itself, but I'm not sure what it is. I've tried uninstalling and reinstalling tiup, but it still won't work. I'm confused because it worked as recently as a few days ago, and then stopped working, but I don't know of anything out of the ordinary that could have made it start crashing. Can anyone help me out?

**Comment by youjiali1995** [comment]
@hicqu PTAL. It panicked at cgroup.rs.

**Comment by Adam-Kulju** [comment]
Specifically, it panicked at the "cgroup_mountinfos_v1" function, which leads me to believe I somehow messed up how my disk is mounted.

**Comment by hicqu** [comment]
@Adam-Kulju sorry for that. I'm trying to locate the problem now.

**Comment by Adam-Kulju** [comment]
After a bit more digging, I found it's crashing because it can't get my mount info properly.
Here's what it looks like when I run "mount":
rootfs on / type wslfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)

Is there anything wrong with this?

**Comment by hicqu** [comment]
@Adam-Kulju can you show `cat /proc/self/mountinfo`?

**Comment by Adam-Kulju** [comment]
cat /proc/self/mountinfo:

2 2 0:2 / / rw,noatime - wslfs rootfs rw
3 2 0:3 / /dev rw,noatime - tmpfs none rw,mode=755
4 2 0:4 / /sys rw,nosuid,nodev,noexec,noatime - sysfs sysfs rw
5 2 0:5 / /proc rw,nosuid,nodev,noexec,noatime - proc proc rw
6 3 0:6 / /dev/pts rw,nosuid,noexec,noatime - devpts devpts rw,gid=5,mode=620
7 2 0:7 / /run rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
8 7 0:8 / /run/lock rw,nosuid,nodev,noexec,noatime - tmpfs none rw
9 7 0:9 / /run/shm rw,nosuid,nodev,noatime - tmpfs none rw
10 7 0:10 / /run/user rw,nosuid,nodev,noexec,noatime - tmpfs none rw,mode=755
11 5 0:11 / /proc/sys/fs/binfmt_misc rw,relatime - binfmt_misc binfmt_misc rw
12 4 0:12 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,mode=755
13 12 0:13 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
14 2 0:14 / /mnt/c rw,noatime - drvfs C:\134 rw,uid=1000,gid=1000,case=off

**Comment by sergeyshaykhullin** [comment]
@hicqu WSL 2

```
tiup playground --mode tikv-slim
Starting component `playground`: /home/sergeyshaykhullin/.tiup/components/playground/v1.5.6/tiup-playground --mode tikv-slim
Using the version v5.2.1 for version constraint "".

If you'd like to use a TiDB version other than v5.2.1, cancel and retry with the following arguments:
    Specify version manually:   tiup playground <version>
    Specify version range:      tiup playground ^5
    The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance
Start tikv instance
PD client endpoints: [127.0.0.1:2379]
To view the Prometheus: http://127.0.0.1:9090
tikv quit: exit status 101
thread 'main' panicked at 'assertion failed: ret.contains_key(*controller)', components/tikv_util/src/sys/cgroup.rs:184:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...
check detail log from: /home/sergeyshaykhullin/.tiup/data/SjGBh1Y/tikv-0/tikv.log
To view the Grafana: http://127.0.0.1:3000
```

```
cat /proc/self/mountinfo
2 2 0:2 / / rw,noatime - lxfs rootfs rw
3 2 0:3 / /dev rw,noatime - tmpfs none rw,mode=755
4 2 0:4 / /sys rw,nosuid,nodev,noexec,noatime - sysfs sysfs rw
5 2 0:5 / /proc rw,nosuid,nodev,noexec,noatime - proc proc rw
6 3 0:6 / /dev/pts rw,nosuid,noexec,noatime - devpts devpts rw,gid=5,mode=620
7 2 0:7 / /run rw,nosuid,noexec,noatime - tmpfs none rw,mode=755
8 7 0:8 / /run/lock rw,nosuid,nodev,noexec,noatime - tmpfs none rw
9 7 0:9 / /run/shm rw,nosuid,nodev,noatime - tmpfs none rw
10 7 0:10 / /run/user rw,nosuid,nodev,noexec,noatime - tmpfs none rw,mode=755
11 5 0:11 / /proc/sys/fs/binfmt_misc rw,relatime - binfmt_misc binfmt_misc rw
12 4 0:12 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,mode=755
13 12 0:13 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
14 2 0:14 / /mnt/c rw,noatime - drvfs C:\134 rw,uid=1000,gid=1000,case=off
15 2 0:15 / /mnt/d rw,noatime - drvfs D:\134 rw,uid=1000,gid=1000,case=off
```

**Comment by Adam-Kulju** [comment]
@sergeyshaykhullin I notice your /dev mount info is the same as mine (none as the root source), what I want to know is whether the problem is with the mount info or a bug in the code?
