### ISSUE TITLE
DWARF info of dist_release binary is incorrect

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#10906]
### What version of TiKV are you using?

Not really related. It affects at least TiKV 4.0 ~ 5.2.

### What operating system and CPU are you using?

I can confirm the problem on Linux x86-64 and Linux aarch64.

### Steps to reproduce

Run `make dist_release`. And use `dwz` on the binary, it reports:

```
$ objcopy --decompress-debug-sections bin/tikv-server
$ dwz bin/tikv-server
dwz: bin/tikv-server: Couldn't find DIE at [d4bb7] referenced by DW_AT_abstract_origin from DIE at [17c2a3]
```

[dwarf-validate](https://github.com/gimli-rs/gimli/blob/master/examples/dwarf-validate.rs) also reports dwarf errors:

```
DWARF error in bin/tikv-server: Invalid intra-unit reference in unit 0xb4181 from DIE 0xc8122 to 0x20a36
DWARF error in bin/tikv-server: Invalid intra-unit reference in unit 0xb4181 from DIE 0xc813f to 0x208ea
DWARF error in bin/tikv-server: Invalid intra-unit reference in unit 0xb4181 from DIE 0xc8156 to 0x208c0
DWARF error in bin/tikv-server: Invalid intra-unit reference in unit 0xb4181 from DIE 0xc81b9 to 0x59c
...
```

### What did you expect?

There should not be dwarf errors.

### What did happened?

Dwarf tools report errors.

**Comment by sticnarf** [comment]
This issue only happens if **full LTO** is used. The dwarf errors disappear if only using thin LTO.

Some upstream bug reports:

https://github.com/rust-lang/rust/issues/66118

Malformed dwarf information may cause some trouble to debuggers. GDB sometimes gets stuck or crashes when it encounters these incorrect dwarf info.

**Comment by BusyJay** [comment]
Is it still an issue?

**Comment by sticnarf** [comment]
Yes, until we upgrade the toolchain. (Although the new toolchain will produce a bit incomplete debug info.)

**Comment by sticnarf** [comment]
Closed by https://github.com/tikv/tikv/pull/11875
