### ISSUE TITLE
CDC may hold snapshots for a long time when eventfeed is flowcontrolled

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#10900]
## Bug Report

CDC holds snapshot for a long time due to flowcontrol. See more: https://github.com/pingcap/ticdc/pull/2699#issue-724007913

![image](https://user-images.githubusercontent.com/2150711/131610531-f40fcbb2-cf2b-4fd4-a4c6-bfd203853859.png)

### What version of TiKV are you using?

v4.0.13

### Steps to reproduce

Pause TiCDC process, eg., `kill -SIGSTOP <CDC_PID>` .

### What did you expect?

Snapshots should be released within a specified time period., eg 10mins. 

### What did happened?

Snapshots may be hold arbitrary long.

**Comment by zhangjinpeng1987** [comment]
Any proposal to fix it? Like, add a timeout for holding snapshot?

**Comment by overvenus** [comment]
> Any proposal to fix it? Like, add a timeout for holding snapshot?

A timeout should be good enough for most cases.

Also, we need to consider another variant of this case: a TiCDC straggler, flow control can always make progress, but extremely slow. It may hold snapshot for a long time too.

**Comment by overvenus** [comment]
This issue has been mitigated by #10135
