### ISSUE TITLE
the status of two store are abnormal and some tikv oom while run sysbench

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#10927]
### What version of TiKV are you using?
v5.2.1

### What operating system and CPU are you using?
k8s 3PD、2TiDB、4TiKV
8 Core 16G mem

### Steps to reproduce
case:TiKVWorkloadStress005（do not scale TiKV）
run sysbench prepare
threads=64
tables=512

### What did you expect?
all store are normal

### What did happened?
the status of two store are abnormal while run sysbench
<img width="422" alt="无标题" src="https://user-images.githubusercontent.com/84712107/132711755-7e135d82-bf16-4296-a3e7-af2028269812.png">
some tikv oom
<img width="447" alt="oom" src="https://user-images.githubusercontent.com/84712107/132712129-444ca573-c586-4040-9a18-17d9a9b9232b.png">

**Comment by hicqu** [comment]
It can't be continued until we improve TiKV heap profiling. So let's close it now.
