### ISSUE TITLE
Analyze table failed due to tikv server timeout error during lighting import

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#10924]
### What version of TiKV are you using?
/ # ./tikv-server -V
TiKV
Release Version:   5.2.0
Edition:           Community
Git Commit Hash:   556783c314a9bfca36c818256182eeef364120d7
Git Commit Branch: heads/refs/tags/v5.2.0
UTC Build Time:    2021-08-26 05:47:23
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
TiKV: 8U, 61GB

### Steps to reproduce

1, Create DBaaS Cluster in Dev Env - T5.xlarge, TiKV x 3, 8U 61GB
2, Create CSV Import job, import data from: s3://data-platform-uw2/csv_export_default_10GiB 

### What did you expect?
Lightning import succeed

### What did happened?
Lightning import failed.

  | 2021-09-09 05:59:06 | [2021/09/09 05:59:06.942 +00:00] [ERROR] [restore.go:154] [-] [table=`aaa`.`bbb`] [status=analyzed] [error="analyze table failed: Error 9002: TiKV server timeout"]
  | 2021-09-09 05:59:06 | [2021/09/09 05:59:06.942 +00:00] [ERROR] [restore.go:152] ["tables failed to be imported"] [count=1]
  | 2021-09-09 05:59:06 | [2021/09/09 05:59:06.942 +00:00] [ERROR] [restore.go:431] ["the whole procedure failed"] [takeTime=1h52m11.9212808s] [error="analyze table failed: Error 9002: TiKV server timeout"]
   | 2021-09-09 05:59:06 | [2021/09/09 05:59:06.942 +00:00] [ERROR] [restore.go:420] ["run failed"] [step=3] [error="analyze table failed: Error 9002: TiKV server timeout"]
  | 2021-09-09 05:59:06 | Error: analyze table failed: Error 9002: TiKV server timeout
  | 2021-09-09 05:59:06 | [2021/09/09 05:59:06.651 +00:00] [INFO] [restore.go:1038] ["switch to normal mode"]

Log:  https://grafana.oauth.dev.shared.aws.tidbcloud.com/explore?orgId=1&left=%5B%22now-3h%22,%22now%22,%22loki%22,%7B%22expr%22:%22%7Bcontainer%3D%5C%22tidb-lightning%5C%22,namespace%3D%5C%22tidb120007%5C%22%7D%22%7D%5D

**Comment by Little-Wallace** [comment]
TiKV will kill coprocessor request whose wait duration exceed 60s in https://github.com/tikv/tikv/pull/10189.
It causes more TiDB SQL fail because of requests to TiKV are killed.

**Comment by sticnarf** [comment]
> TiKV will kill coprocessor request whose wait duration exceed 60s in #10189.
> It causes more TiDB SQL fail because of requests to TiKV are killed.

I don't think it related. If you are using TiDB for analyzing, the timeout at TiDB is 60s:

https://github.com/pingcap/tidb/blob/v5.2.0/store/copr/coprocessor.go#L725

So any response of request running longer than 60s will not be received by TiDB and the resource is wasted.

**Comment by BusyJay** [comment]
According @winoros, it's fixed in TiDB side.
