### ISSUE TITLE
`compaction-style` setting is broken

### ISSUE THREAD

**Issue by kamijin-fanta** [tikv/tikv#11028]
### What version of TiKV are you using?

using tiup for deployment.
```
TiKV
Release Version:   5.2.1
Edition:           Community
Git Commit Hash:   2c99f317d4ba125b772a8b94a6c3c0eb9d07ac59
Git Commit Branch: heads/refs/tags/v5.2.1
UTC Build Time:    2021-09-08 02:32:36
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

### What operating system and CPU are you using?

It seems to be a machine-independent bug.

### Steps to reproduce

The server will not start if the following settings are made.

```yaml
# tiup-topology.yaml
server_configs:
  # tidb:
  tikv:
    rocksdb:
      defaultcf:
        compaction-style: universal
```

```toml
# /opt/tidb/deploy/tikv-20160/conf/tikv.toml
[rocksdb]
[rocksdb.defaultcf]
compaction-style = "universal"
```

```
Error: init config failed: 192.168.50.3:20160: executor.ssh.execute_failed: Failed to execute command over SSH for '********@********:22' {ssh_stderr: thread 'main' panicked at 'invalid auto generated configuration file /opt/tidb/deploy/tikv-20160/conf/tikv.toml, err invalid type: string "level", expected valid DBCompactionStyle for key `rocksdb.defaultcf.compaction-style` at line 10 column 20', src/config.rs:2836:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /opt/tidb/deploy/tikv-20160/bin/tikv-server --config-check --config=/opt/tidb/deploy/tikv-20160/conf/tikv.toml --pd "" --data-dir "/opt/tidb/data/tikv-20160"}, cause: Process exited with status 101: check config failed
```

### What did you expect?

The reference looks like a correct description.
https://docs.pingcap.com/tidb/stable/tikv-configuration-file#compaction-style

### What did happened?

If specify `compaction-style: 1`, it appears to start successfully.

**Comment by yuqi1129** [comment]
@tabokie I have test this configuration and it seems that only numeric is supported like `compaction-pri`. Sounds like we need to update user docs.

```rust
numeric_enum_mod! {compaction_style_serde DBCompactionStyle {
    Level = 0,
    Universal = 1,
}}
```

**Comment by tabokie** [comment]
@yuqi1129 I prefer to use descriptive words for these config items, just like `blob-run-mode`, `grpc-compression-type`, etc. So I think you should submit a code patch to make `compaction-pri` accept string literals.

As for `compaction-pri`, it is problematic too, but we probably shouldn't change it directly for backward compatibility.
