### ISSUE TITLE
Add `raw` CF

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#11026]
1. Add `raw` cf
2. When `storage.api_version == ApiVersion::V2`, enable RawKV TTL compaction filter on `raw` cf and disable RawKV TTL compaction filter on `default` cf.

**Comment by BusyJay** [comment]
I don't see this in the RFC, how come a new cf is required?

**Comment by andylokandy** [comment]
After internal discussion, we decided not to add a raw cf.
