### ISSUE TITLE
Incorrect snapshot state count if an error occurs on receiving snapshot

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#11157]
### What version of TiKV are you using?

v5.0.1. Later TiKV until at lease v5.3 should also be affected.

### What operating system and CPU are you using?

Not related.

### Steps to reproduce

Inject network abnormity to one TiKV instance in the cluster while some snapshots are sending.

### What did you expect?

The other TiKV instances with no network issues will work well.

### What did happened?

PD will not produce operators to these normal nodes because of too many "receiving" snapshot.

Here is the snapshot metrics of a node without network issues. Its snapshot count in "receiving" state is incorrect.

![image](https://user-images.githubusercontent.com/17217495/139039461-079bb8ba-c0c9-48ef-8c21-67329f52090d.png)

**Comment by sticnarf** [comment]
Should also be closed by https://github.com/tikv/tikv/pull/11342

**Comment by nolouch** [comment]
resolved by #11342
