### ISSUE TITLE
PR #10289 results in performance degradation in TPCC benchmark

### ISSUE THREAD

**Issue by Yui-Song** [tikv/tikv#11165]
## Bug Report

The pr https://github.com/tikv/tikv/pull/10289 results in performance degradation in TPCC benchmark. The performance drops 5.8%-9.0% against last pull request.

### What version of TiKV are you using?

```
TiKV 
Release Version:   5.3.0-alpha
Edition:           Community
Git Commit Hash:   58573b822c7b7f56aeb7933f8e30162a6c9b6073
Git Commit Branch: master
UTC Build Time:    2021-10-20 13:23:57
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

### What operating system and CPU are you using?

```
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018
Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
```

### Steps to reproduce

1. create a new tidb cluster
2. patch tikv to this PR (commit hash: 58573b822c7b7f56aeb7933f8e30162a6c9b6073) 
3. use go-tpc to run TPC-C 1000 warehouse benchmark.
`go-tpc -H $tidb -P9999 -D tpcc tpcc run --time 10m --warehouses 1000 --threads 64
`
### What did happened?
The performance of TPCC drops 5.8%-9.0% against last pull request.

**Comment by dbsid** [comment]
for sysbench oltp_insert workload, the performance degradation from  pr #10289 is 4.7%, compared the the previous pr.

**Comment by youjiali1995** [comment]
@Yui-Song @dbsid Latest release-5.3 has some improvements. Can you bench again?
