### ISSUE TITLE
scripts/test: fail to compile and run test due to OOM on a machine with 18G free memory

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#11181]
### What version of TiKV are you using?
Master branch or release-5.1.1

### What operating system and CPU are you using?

OS: Linux  3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, 40 cores
processor	: 39
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping	: 1
microcode	: 0xb00001f
cpu MHz		: 1257.238
cache size	: 25600 KB
physical id	: 1
siblings	: 20
core id		: 12
cpu cores	: 10
apicid		: 57
initial apicid	: 57
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bogomips	: 4399.41
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual

Memory:
free -m
                       total        used        free      shared  buff/cache   available
Mem:         128655       65582       19212        4142       43861       57775
Swap:          7167           0        7167

### Steps to reproduce

 ./scripts/test test_node_base_merge  -- --nocapture

### What did you expect?
Compile and run succeed
### What did happened?
Compile failed due to OOM. But in fact the machine has 18G memory free.
Below is the detail error:
.....
memory allocation of 16912 bytes failed
memory allocation of 278544 bytes failed
error: could not compile `engine_rocks`

Caused by:
  process didn't exit successfully: `rustc --crate-name engine_rocks --edition=2018 components/engine_rocks/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C embed-bitcode=no -C codegen-units=16 -C debuginfo=1 --test --cfg 'feature="default"' --cfg 'feature="failpoints"' --cfg 'feature="jemalloc"' --cfg 'feature="portable"' --cfg 'feature="protobuf-codec"' --cfg 'feature="sse"' -C metadata=613b2c34d7b348c2 -C extra-filename=-613b2c34d7b348c2 --out-dir /data4/qixu/tikv/target/debug/deps -C incremental=/data4/qixu/tikv/target/debug/incremental -L dependency=/data4/qixu/tikv/target/debug/deps --extern collections=/data4/qixu/tikv/target/debug/deps/libcollections-ff4b61b1e625e0bd.rlib --extern encryption=/data4/qixu/tikv/target/debug/deps/libencryption-69ef0f85f3fc9d60.rlib --extern engine_traits=/data4/qixu/tikv/target/debug/deps/libengine_traits-267baeb262e248cc.rlib --extern fail=/data4/qixu/tikv/target/debug/deps/libfail-eaf11d7a7ad661bc.rlib --extern file_system=/data4/qixu/tikv/target/debug/deps/libfile_system-4379e993838cda77.rlib --extern keys=/data4/qixu/tikv/target/debug/deps/libkeys-6bfa84ce9cfa4cfa.rlib --extern kvproto=/data4/qixu/tikv/target/debug/deps/libkvproto-3efefc3cb668066f.rlib --extern lazy_static=/data4/qixu/tikv/target/debug/deps/liblazy_static-13264be0b3c7d350.rlib --extern log_wrappers=/data4/qixu/tikv/target/debug/deps/liblog_wrappers-2913509288b11a10.rlib --extern num_cpus=/data4/qixu/tikv/target/debug/deps/libnum_cpus-c7937c3f2073a5ef.rlib --extern online_config=/data4/qixu/tikv/target/debug/deps/libonline_config-5052e65122949d2b.rlib --extern prometheus=/data4/qixu/tikv/target/debug/deps/libprometheus-27b03b9affc74dfe.rlib --extern prometheus_static_metric=/data4/qixu/tikv/target/debug/deps/libprometheus_static_metric-8d6dcda53182a6b1.so --extern protobuf=/data4/qixu/tikv/target/debug/deps/libprotobuf-170df4f6f58293fe.rlib --extern raft=/data4/qixu/tikv/target/debug/deps/libraft-0fdffff7aab487c4.rlib --extern rand=/data4/qixu/tikv/target/debug/deps/librand-392e061d78b172ab.rlib --extern rocksdb=/data4/qixu/tikv/target/debug/deps/librocksdb-8627d3fe0f2fcb7d.rlib --extern serde=/data4/qixu/tikv/target/debug/deps/libserde-fe5f502a9511000b.rlib --extern serde_derive=/data4/qixu/tikv/target/debug/deps/libserde_derive-e93cbc01a8974653.so --extern slog=/data4/qixu/tikv/target/debug/deps/libslog-eb33ee7bd2dec5cb.rlib --extern slog_global=/data4/qixu/tikv/target/debug/deps/libslog_global-148ae0e00c2035c5.rlib --extern tempfile=/data4/qixu/tikv/target/debug/deps/libtempfile-0eb2ced38807848c.rlib --extern tikv_alloc=/data4/qixu/tikv/target/debug/deps/libtikv_alloc-00e6a2bb1693062a.rlib --extern tikv_util=/data4/qixu/tikv/target/debug/deps/libtikv_util-8c12dd116dea0199.rlib --extern time=/data4/qixu/tikv/target/debug/deps/libtime-2caa5bdcdb49344c.rlib --extern toml=/data4/qixu/tikv/target/debug/deps/libtoml-ee0d1fd032cb55f7.rlib --extern txn_types=/data4/qixu/tikv/target/debug/deps/libtxn_types-3acc8795a113e150.rlib -L native=/data4/qixu/tikv/target/debug/build/tikv-jemalloc-sys-38d6572dc82de9f7/out/build/lib -L native=/data4/qixu/tikv/target/debug/build/libz-sys-bfac05ba4edd72bd/out/build -L native=/data4/qixu/tikv/target/debug/build/libz-sys-bfac05ba4edd72bd/out/lib -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/container -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/container -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/strings -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/strings -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/strings -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/strings -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/base -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/base -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/base -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/base -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/base -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/base -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/base -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/status -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/status -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/numeric -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/debugging -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/debugging -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/debugging -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/debugging -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/hash -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/hash -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/hash -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/types -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/types -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/synchronization -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/synchronization -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/time -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/time -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/abseil-cpp/absl/time -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/cares/cares/lib -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build/third_party/re2 -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out/build -L native=/data4/qixu/tikv/target/debug/build/grpcio-sys-f91f56752ed61337/out -L native=/data4/qixu/tikv/target/debug/build/libz-sys-bfac05ba4edd72bd/out/lib -L native=/data4/qixu/tikv/target/debug/build/libz-sys-bfac05ba4edd72bd/out/lib -L native=/data4/qixu/tikv/target/debug/build/openssl-sys-17028fb8541d7e55/out/openssl-build/install/lib -L native=/data4/qixu/tikv/target/debug/build/miniz-sys-3c0ec5e26bb2b217/out -L native=/data4/qixu/tikv/target/debug/build/librocksdb_sys-3518cb0375dbc1ef/out/build -L native=/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8 -L native=/data4/qixu/tikv/target/debug/build/librocksdb_sys-3518cb0375dbc1ef/out -L native=/data4/qixu/tikv/target/debug/build/bzip2-sys-8b5bc6a3e15d22ad/out/lib -L native=/data4/qixu/tikv/target/debug/build/libtitan_sys-85307656deb78f19/out/build -L native=/data4/qixu/tikv/target/debug/build/lz4-sys-0685cee1bfd10cc2/out -L native=/data4/qixu/tikv/target/debug/build/snappy-sys-3d39d36362bf8238/out/build -L native=/data4/qixu/tikv/target/debug/build/zstd-sys-72ff2863740d385e/out` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1

Other information:
Tried compact memory or free more memory, problem still exists.
However, "make release" actually works.

**Comment by BusyJay** [comment]
Close it now, feel free to reopen if above suggestion can't solve the problem.
