### ISSUE TITLE
Unstable test `test_cdc::test_cdc_stale_epoch_after_region_ready`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#11185]
### Steps to reproduce

in ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9780/pipeline

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
