### ISSUE TITLE
Update Rust toolchain to edition 2021

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#11180]
## Motivation

The most useful update edition 2021 will bring us is the [Disjoint capture in closures](https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html). In edition 2018, when we use `a.x` in a closure, it will move the entire `a` into the closure. But in edition 2021, the closure will only move the field of struct `x`.

The second useful one is implementing `IntoIterator` for arrays, which I think I don't bother the explain.

**Comment by burnerlee** [comment]
@andylokandy can I take up the issue and work on this?

**Comment by andylokandy** [comment]
@burnerlee Just to mention, maybe you need to upgrade the rust-toolchain version before switching to the 2021 edition.

**Comment by burnerlee** [comment]
@andylokandy sure, I'll get started with this. Can you please assign me this issue? Also, I am new to this project. What would be a good way to get started with the project and the issue?

**Comment by hi-rustin** [comment]
@burnerlee Have you started this upgrade? If not I'd like to try it.
