### ISSUE TITLE
Add Procedural macros to support convert identifier to string literal

### ISSUE THREAD

**Issue by yuqi1129** [tikv/tikv#11189]
## Development Task
In some macros about tikv config, we run into this situation: convert identifier to string value in compile stage. for example
the following case:

```
numeric_enum_mod {
 ($enum:ident) { 

match str_value:
   "read-only" => ReadOnly,
   "read-write" ==> ReadWrite
 }
}
```
That is, we need a templated to convert kebab case string to camel case Enum value, However input value is a came-case identifier, We have to use procedural macros to implement this conversion (ReadWrite => "read-write")

This task aim to add a procedural macros to convert camel case identifier to kebab case string, Issue #11028 depends on this task

**Comment by BusyJay** [comment]
Will hand writing match be optimized out at compile time? If it is, a procedural macros seems overkill.

**Comment by yuqi1129** [comment]
> Will hand writing match be optimized out at compile time? If it is, a procedural macros seems overkill.

@BusyJay , I'm not sure if we need this macros to solve concrete case conversion problem.  But @tabokie suggest we'd better add it for further use. @tabokie Can you make this issue more clearly here?

**Comment by tabokie** [comment]
@BusyJay The use case is to make RocksDB enum configuration supports string literals (e.g. `compaction-style = "universal"`), without breaking backward compatibility of using numbers. This is what it looks like before: https://github.com/tikv/tikv/blob/e1b198abeaa8c781794cc6d374bf8aea96cc34f8/components/engine_rocks/src/config.rs#L384-L389

Not particularly good, so I think it would be better to implement our own case conversion tools to further dedup the code.
