### ISSUE TITLE
test_resource_metering is too slow

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#11229]
test_resource_metering takes 4 minutes to finish, which is too long.

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/10151/pipeline/112#step-333-log-108

**Comment by mornyx** [comment]
Can we simply shorten this reporting interval at [tests/integrations/resource_metering/test_suite/mod.rs#L55](https://github.com/tikv/tikv/blob/f3f02d7fc6cf7e94abcf8cdb9b9ff52b110a72ba/tests/integrations/resource_metering/test_suite/mod.rs#L55)? @zhongzc

**Comment by zhongzc** [comment]
> Can we simply shorten this reporting interval at [tests/integrations/resource_metering/test_suite/mod.rs#L55](https://github.com/tikv/tikv/blob/f3f02d7fc6cf7e94abcf8cdb9b9ff52b110a72ba/tests/integrations/resource_metering/test_suite/mod.rs#L55)? @zhongzc

Can have a try.

**Comment by BusyJay** [comment]
Any updates?

**Comment by mornyx** [comment]
> Any updates?

I tried to adjust the sleep interval, but got an unexpected panic, I will take time to continue troubleshooting.

**Comment by BusyJay** [comment]
Got it. Giving that the feature is not GA, I will disable the case first, and you can enable it again once it's optimized.
