### ISSUE TITLE
Make threads of `snap-generator` pool be adjustable

### ISSUE THREAD

**Issue by nolouch** [tikv/tikv#11247]
## Background
In recover scenario,  because we want TiDB to make up the copy as soon as possible, we release all limit, including `store limit`, `scheduling limit`,  `snap-max-write-bytes-per-sec` and so on. but the IO only reach to 150MB/s for each TiKV instance. after we change the pool size of region worker from `2` to `32`, the recover speed has been effectively improved.
https://github.com/tikv/tikv/blob/14895dc46c48586946445ebff12e6380c7b561bf/components/raftstore/src/store/worker/region.rs#L631-L635

the IO speed reach to 650MB/s：
![image](https://user-images.githubusercontent.com/6428910/140308355-92056e90-ba33-48c8-8290-849cc5445460.png)

**Comment by bufferflies** [comment]
let me try

**Comment by nolouch** [comment]
FYI @andylokandy @iosmanthus

**Comment by iosmanthus** [comment]
@nolouch https://github.com/tikv/tikv/pull/11263 PTAL
