### ISSUE TITLE
test case test_update_server_config failed

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#11250]
### What version of TiKV are you using?
Doesn't matter.

### What operating system and CPU are you using?
Linux, x86_64

### Steps to reproduce
run integration tests multiple times, it will fail occasionally.

### What did you expect?
It finishes successfully.

### What did happened?
```
failures:

---- config::dynamic::snap::test_update_server_config stdout ----
thread 'config::dynamic::snap::test_update_server_config' panicked at 'assertion failed: `(left == right)`
  left: `inf`,
 right: `536870912.0`', tests/integrations/config/dynamic/snap.rs:105:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
