### ISSUE TITLE
v5.3.0 cmd-batch-concurrent-ready-max-count  can't be modify

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#11281]
### What version of TiKV are you using?
f98a247f060455632c90472cf72f9369b6d71811

### Steps to reproduce
modify raftstore.cmd-batch-concurrent-read-max-count to 2,using tiup cluster edit-config and reload;
then check in 'show config', but this value still 1.
is this expected

tiup cluster edit-config debug 
  tikv:
    raftstore.cmd-batch-concurrent-read-max-count: 2

MySQL [(none)]> show config where Type='tikv' and Name='raftstore.cmd-batch-concurrent-ready-max-count';
+------+------------------+------------------------------------------------+-------+
| Type | Instance         | Name                                           | Value |
+------+------------------+------------------------------------------------+-------+
| tikv | tikv3-peer:20360 | raftstore.cmd-batch-concurrent-ready-max-count | 1     |
| tikv | tikv2-peer:20260 | raftstore.cmd-batch-concurrent-ready-max-count | 1     |
| tikv | tikv4-peer:20460 | raftstore.cmd-batch-concurrent-ready-max-count | 1     |
| tikv | tikv-peer:20560  | raftstore.cmd-batch-concurrent-ready-max-count | 1     |
+------+------------------+------------------------------------------------+-------+
4 rows in set (0.03 sec)

### What did you expect?
value in 'show config' should be 2
### What did happened?
value in 'show config' still 1 by default

**Comment by yuqi1129** [comment]
@seiya-annie , Can't reproduce this problem on master branch and 5.3.0

**Comment by gengliqi** [comment]
I remove this config from `config-template.toml` in https://github.com/tikv/tikv/pull/11310 because it should not be changed in almost all cases.
