### ISSUE TITLE
Vote for TiKV character

### ISSUE THREAD

**Issue by gingerkidney** [tikv/tikv#11311]
We are looking for a new character for TiKV, and we need your vote!

Many of you may have read Illustrated Children’s Guide to Kubernetes. In this book, Phippy and her friends explain the core concepts of Kubernetes in simple terms. And the character Phippy, the yellow PHP application giraffe is well known after that.

As a CNCF project, TiKV is joining the adventure by donating a character to the Phippy and Friends family. The character will also be presented in Kubecon China. All we need is:

- An animal that begins with the letter T (for TiKV) - like a tiger, tapir, toucan or tortoise. 
- A name for TiKV character, also beginning with the letter T (for example, CNCF has Linky the lobster who represents Linkerd, and Hazel the hedgehog who represents Helm.) 

We have listed some animals in the comment below, you can vote thumb up for your favourite or list others you like. Also, you can help TiKV to have an easy-remember name by comment. 

We will close the vote before 8PM on November 12th (GMT+8)

Reference: 
https://www.cncf.io/phippy/ 

You can also get some inspiration from:
https://a-z-animals.com/animals/animals-that-start-with-t/
https://alphabetimals.com/animal-dictionary/animals-that-start-with-t/

**Comment by gingerkidney** [comment]
1. Tiger

**Comment by gingerkidney** [comment]
2. Tortoise

**Comment by gingerkidney** [comment]
3. Tree frog

**Comment by gingerkidney** [comment]
4. T-Rex

**Comment by gingerkidney** [comment]
5. Tropicbird

**Comment by PsiACE** [comment]
6. Tetra

**Comment by gingerkidney** [comment]
7. Toucans

**Comment by tabokie** [comment]
a. "Tycho"

Related: astronomer [Tycho Brahe](https://en.wikipedia.org/wiki/Tycho_Brahe), lunar crater [Tycho](https://en.wikipedia.org/wiki/Tycho_(lunar_crater)), fictional space station [Tycho](https://expanse.fandom.com/wiki/Tycho_Station)

**Comment by disksing** [comment]
Eddie, an elephant.

**Comment by hfxsd** [comment]
tuckoo

**Comment by gingerkidney** [comment]
> Eddie, an elephant.

It's not start with T ><

**Comment by disksing** [comment]
Tom cat

**Comment by yanguwan** [comment]
Tarpon

**Comment by ztelur** [comment]
thunderbird？

**Comment by gingerkidney** [comment]
> thunderbird？

cool!!! But already used by Mozilla for an open-source cross-platform email client 
https://www.thunderbird.net/en-US/

**Comment by buggithubs** [comment]
T-800 robot
From the Future

**Comment by kennytm** [comment]
do we vote for names in this issue or a separate issue

**Comment by unbyte** [comment]
Teng
https://en.wikipedia.org/wiki/Teng_(mythology)

**Comment by BusyJay** [comment]
Tyrannosaurus, "霸王龙" in Chinese, lived in the Late Cretaceous.

https://en.wikipedia.org/wiki/Tyrannosaurus

**Comment by winkyao** [comment]
> Tyrannosaurus, "霸王龙" in Chinese, lived in the Late Cretaceous.
> 
> https://en.wikipedia.org/wiki/Tyrannosaurus

Same as "T-Rex"?

**Comment by it2911** [comment]
Ti　鯛

![image](https://user-images.githubusercontent.com/2803470/141069742-db951bde-a93d-4df8-b640-9615c0c0c820.png)

![TiDB_koiB](https://user-images.githubusercontent.com/2803470/141069847-0a59106e-d76a-4a8e-bc01-de07a3bb35fd.png)

**Comment by gingerkidney** [comment]
> do we vote for names in this issue or a separate issue

in the same issue is fine :)

**Comment by gingerkidney** [comment]
> T-800 robot From the Future

It has to be animal ><

**Comment by nexustar** [comment]
TiKiwi (kiwi)
![Screenshot 2021-11-10 at 15-50-28 Kiwi (bird) - Wikipedia](https://user-images.githubusercontent.com/20392070/141086880-615048c8-c94f-4f18-a6e3-63970cd2096a.png)

**Comment by Mossaka** [comment]
Tapir

![image](https://user-images.githubusercontent.com/5447827/141204931-877514c5-c06b-4390-b797-9271b5891f04.png)

It's sooooo cute

**Comment by msohn** [comment]
Toco Toucan
https://en.wikipedia.org/wiki/Toco_toucan

![toco toucan](https://en.wikipedia.org/wiki/List_of_toucans#/media/File:Ramphastos_toco_Whipsnade_Zoo.jpg)

**Comment by gingerkidney** [comment]
Name：Trusty
start with T and include rust ><

**Comment by gingerkidney** [comment]
We will use Tiger as the character, thank you all!
