### ISSUE TITLE
resolved_ts may occupy a lot of memory

### ISSUE THREAD

**Issue by NingLin-P** [tikv/tikv#11339]
### What version of TiKV are you using?

v5.1.1

### What operating system and CPU are you using?

Not related

### Steps to reproduce

`resolved_ts` is used for stale read and TiCDC, it needs to keep track of all the locks data on the raft leaders to compute the correct `resolved_ts`. Before v5.1.0 it is only enabled when TiCDC is deployed, after v5.1.0 it is enabled by default for stale read use.

Although normally lock data should be small (they will be cleaned up after transaction commit ) and `resolved_ts` only keep track of the lock's key and timestamp, in some cases it is still possible that there are a lot of lock data and `resolved_ts` could occupy a lot of memory.

For example, when executing a large transaction that invokes many keys, before the transaction is committed and the lock is cleaned up the TiDB crashes and leaves a lot of lock data. If the GC lifetime is also set to a large value, these lock data wouldn't be cleaned up quickly, so that `resolved_ts` will keep occupying the memory.

**Comment by overvenus** [comment]
It has been resolved by #14864 and #15412.
