### ISSUE TITLE
tidb-cluster can not run pod of basic-tikv-0

### ISSUE THREAD

**Issue by fhj939057500** [tikv/tikv#11348]
### What version of TiKV are you using?

5.2.1
### What operating system and CPU are you using?

Linux TENCENT64.site  x86_64 x86_64 x86_64 GNU/Linux
### Steps to reproduce

1.Refer to the official website document，quickly run tidb-cluster.
2.Execute instructions：
    kubectl -n tidb-cluster apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/examples/basic/tidb-cluster.yaml
3. kubectl logs basic-tikv-0 -n tidb-cluster,find log :
    ParseIntError { kind: PosOverflow}' , components/tikv_util/src/cgroupp.rs.251:18
3. find basic

### What did you expect?
fix bug

**Comment by sticnarf** [comment]
It's because we cannot handle a limit that is larger than 2^63-1. I think we can treat `PosOverflow` error same as max.

**Comment by sticnarf** [comment]
@fhj939057500 Could you tell more about your kubernetes environment?

Are you using a managed k8s service provided by cloud, or you deployed your own k8s?

**Comment by fhj939057500** [comment]
> @fhj939057500 Could you tell more about your kubernetes environment?
> 
> Are you using a managed k8s service provided by cloud, or you deployed your own k8s?

yes,it.s run by: https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#%E8%BF%9E%E6%8E%A5-tidb-%E9%9B%86%E7%BE%A4

**Comment by sticnarf** [comment]
Closed by #11354
