### ISSUE TITLE
tikv oom when run sysbench prepare while query under stress

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#11379]
### What version of TiKV are you using?
sh-4.2# ./tikv-server -V
TiKV 
Release Version:   5.3.0-alpha
Edition:           Community
Git Commit Hash:   500ead07966474d280f652dafc4fc4856b99d9e2
Git Commit Branch: heads/refs/tags/v5.3.0
UTC Build Time:    2021-11-09 11:32:30
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
8core 16G memory

### Steps to reproduce
TiKVWorkloadStress003
run run sysbench prepare and select *

### What did you expect?
all instance are normal

### What did happened?
one tikv oom several times
![image](https://user-images.githubusercontent.com/84712107/141927213-47f91e26-7286-464d-8fc2-54a800b5ee7b.png)

![image](https://user-images.githubusercontent.com/84712107/141927365-c7ae6835-286a-403b-88c7-56c8daf2990b.png)

**Comment by tier-cap** [comment]
1. OOM has been reproduced.
2. Moreover, one of the nodes restarted after OOM, and then entered a cycle of repeated OOM, which lasted more than ten minutes
