### ISSUE TITLE
add a new builtin function to convert string to binary literal

### ISSUE THREAD

**Issue by xiongjiwei** [tikv/tikv#11386]
## Development Task
see https://github.com/pingcap/tidb/pull/29736.

the gbk character is stored as utf8 encoding, some built-in functions like `md5` should take the original bytes as the input. So that, we should convert the utf8 encoding character to gbk encoding. 

On the tidb side, `select md5(a)` will build to `select md5(to_binary(a))` if `a` is non-utf8 charset

**Comment by breeswish** [comment]
Wow. The idea of `to_binary` and `from_binary` actually looks good to me. One thing I'm considering is that, how would it affect the implementation of current charset-aware functions for the new GBK charset?

For example, there exists "lower" and "lower_utf8", which does different lowering logics. What will happen to them when we have a GBK charset?

**Comment by xiongjiwei** [comment]
> Will you introduce lower_gbk then?

@breeswish, most of the functions will not change except the `lower` and `upper`, please see https://github.com/pingcap/tidb/issues/28360#issuecomment-941905023. I think just introducing a map for the special case is enough.
