### ISSUE TITLE
Delete 16k data tables in a single pass

### ISSUE THREAD

**Issue by buggithubs** [tikv/tikv#11398]
### What version of TiKV are you using?

```
TiKV 
Release Version:   5.3.0-alpha
Edition:           Community
Git Commit Hash:   e16bf9c0f86d26fd41335f9714adbdd387862ee7
Git Commit Branch: heads/refs/tags/v5.3.0
UTC Build Time:    2021-11-11 10:05:28
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

### What operating system and CPU are you using?

```
NVME Disk 
centos 7.5 
model name      : Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz * 2
```

### What did happened?

GC continued to run for 13 hours without advancement

1. Create 16k data tables
2. Write 100w rows of data per table
3. drop database

![image](https://user-images.githubusercontent.com/11624213/142155597-024735cf-22d5-4aa3-bf38-1656aa65d573.png)
![image](https://user-images.githubusercontent.com/11624213/142155672-c838baff-f27f-4630-bf6c-ea17268557ae.png)
![image](https://user-images.githubusercontent.com/11624213/142155689-ad80ac55-995d-44e5-94a6-5c0e4c06fafe.png)

**Comment by BusyJay** [comment]
Any updates?

**Comment by buggithubs** [comment]
The next step for this question can be seen  https://github.com/pingcap/tidb/issues/29864。

**Comment by BusyJay** [comment]
Then it seems not a problem of TiKV.
