### ISSUE TITLE
raftstore: TiKV can not deleted the truncated raft log as soon as possible

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/tikv#11404]
### What version of TiKV are you using?

5.1.2
### Steps to reproduce

I have add some metrics in TiKV in PR: https://github.com/tikv/tikv/pull/11377/files
And we find that TiKV was busy with write the deleted keys to RaftDB. Because most of GC Batch is small but the number of regions which need to clean is large.
![image](https://user-images.githubusercontent.com/16376959/142194352-18790a91-8b33-492b-8901-b93a46070186.png)

### What did you expect?
I hope TiKV can consume the GC task as soon as possible,

### What did happened?
There are more and more data in RaftDB.  I got thousands  of SST files in RaftDB and it usually was small (maybe tens).

**Comment by VelocityLight** [comment]
update
