### ISSUE TITLE
QPS dropped severely many times during scale out in DBaaS

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#11424]
### What version of TiKV are you using?
5.3.0

### What operating system and CPU are you using?
Cluster Tier
T3.standard

### Steps to reproduce
run sysbench prepare
sysbench --config-file=config oltp_insert --tables=16 --table-size=100000000 prepare
threads=8
scale out tikv from 3 to 6

### What did you expect?
performance is stable

### What did happened?
![NYTJMTk7xU](https://user-images.githubusercontent.com/84712107/142590227-d2d79f89-f0b5-49a6-88dd-11d45f4d3cf7.png)
![zYRSkgmqqs](https://user-images.githubusercontent.com/84712107/142590256-24e8a7e6-c407-4552-8023-1a15b801fbee.png)

**Comment by zhangjinpeng1987** [comment]
@Connor1996 any update for this issue?

**Comment by MimeLyc** [comment]
update
