### ISSUE TITLE
Use assert_matches!() in tests

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#11435]
We usually use `assert!(xxx.is_err())`, `assert!(xxx.is_some())` in tests. But `assert!` provides too little information when failing, and we usually want to know what `xxx` is when the assertion failed.

## Development Task

 This task aims to replace all simple assertion in the form `assert!(xxx.is_{pattern}());` with `assert_matches!(xxx, {pattern});`, for example:

```rust
assert!(res.is_err());
// into
assert_matches!(res, Err(_));
```

**Comment by Jayice-zjw** [comment]
maybe I can try it
