### ISSUE TITLE
How to quickly pull up a lightweight tikv ？

### ISSUE THREAD

**Issue by zhijian-pro** [tikv/tikv#11443]
## Question

I think about using tikv as a dependent service for unit testing in GitHub travis, but the startup method using tiup is too time-consuming. Is there a more lightweight startup method?

**Comment by BusyJay** [comment]
I believe you need some customization on configurations like reserved space. Usually `tiup playground --tiflash 0 v5.2.2 --kv 1` should be lightweight enough to setup a single KV.
