### ISSUE TITLE
copr: got bug when cast invalid utf8 to real

### ISSUE THREAD

**Issue by guo-shaoge** [tikv/tikv#11466]
### What version of TiKV are you using?

4.0

### Steps to reproduce

Described in [tidb issue](https://github.com/pingcap/tidb/issues/23322)

**Comment by guo-shaoge** [comment]
This is a temporary issue because we have to use tikv issue in pr description.

**Comment by zhangjinpeng1987** [comment]
@guo-shaoge can we close it now?
