### ISSUE TITLE
Upgrade hung more than 1 hours when upgrade from 5.0.1 to 5.3.0

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11484]
### Steps to reproduce

Upgrade from 5.0.1 to 5.3.0.
Hit issue https://github.com/tikv/tikv/issues/11475, after the tikv 3 recover from panic, upgrade still hung for about 1 hours.
![image](https://user-images.githubusercontent.com/9443637/143538114-b069f0fc-07ec-423e-951c-c343c07e82d8.png)

### What did you expect?
Upgrade continue and should finished within 1 hours.

### What did happened?
Upgrade still hung after tikv 3 recover from panic.

Related logs and monitor can get from our minio buckets/test-infra-testground/browse/YXJjaGl2ZS90ZXN0YmVkLW9sdHAtaG0tNmN6MjUv

**Comment by BusyJay** [comment]
It's probably related to #9714.

**Comment by BusyJay** [comment]
I think it's verified that #9714 fixed this issue.
