### ISSUE TITLE
tikv-ctl doesn't handle missing parameters

### ISSUE THREAD

**Issue by kolbe** [tikv/tikv#11514]
### What version of TiKV are you using?

```
TiKV Control (tikv-ctl)
Release Version:   5.4.0-alpha
Edition:           Community
Git Commit Hash:   171ffa9179794f35432a3943785110c30a44665b
Git Commit Branch: master
UTC Build Time:    2021-11-29 22:08:48
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc test-engines-rocksdb cloud-aws cloud-gcp
Profile:           release
```

### What operating system and CPU are you using?

```
Darwin monebase 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

```

### Steps to reproduce

```
./tikv-ctl consistency-check -r 1
```

### What did you expect?

The `--host` parameter is missing, and `tikv-ctl` should inform the user of this rather than panicking.

### What did happened?

```
$ RUST_BACKTRACE=1 ./tikv-ctl consistency-check -r 1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cmd/tikv-ctl/src/main.rs:106:29
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: tikv_ctl::new_debug_executor
   4: tikv_ctl::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kolbe** [comment]
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cmd/tikv-ctl/src/main.rs:106:29
stack backtrace:
   0:        0x100a32750 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h868959edd43e2d09
   1:        0x100648b98 - core::fmt::write::ha504d799b94a55bf
   2:        0x100a2d600 - std::io::Write::write_fmt::hdd42eaf7cc314d21
   3:        0x100a36774 - std::panicking::default_hook::{{closure}}::ha8b5ad372d004d6e
   4:        0x100a36ff0 - std::panicking::rust_panic_with_hook::h85b111d5ada04830
   5:        0x100a368cc - std::panicking::begin_panic_handler::{{closure}}::h5276ca2c76dd598a
   6:        0x100a35780 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb97fda8df36c3ad
   7:        0x100a36864 - _rust_begin_unwind
   8:        0x1012e8b00 - core::panicking::panic_fmt::h52ed451722f61ad3
   9:        0x1012e8a84 - core::panicking::panic::h8abe614f4f5d159c
  10:        0x100ba9580 - tikv_ctl::new_debug_executor::heed979346254263d
  11:        0x100bd76b0 - tikv_ctl::main::h9b54bf4713eaece4
  12:        0x100ae9584 - std::sys_common::backtrace::__rust_begin_short_backtrace::h23f62a76a1c68d0b
  13:        0x100aeabec - std::rt::lang_start::{{closure}}::h1839f5720ca3b595
  14:        0x100a37710 - std::rt::lang_start_internal::h7de4712d9f7ef65a
  15:        0x100c0e2b4 - _main
```

**Comment by JayiceZ** [comment]
I tried other commands and seemed to get the same result.

It looks like this line  does not return the value we want
https://github.com/tikv/tikv/blob/fd24cc9e3b43f77f0dceba5bf20f7b4f9e9dae44/cmd/tikv-ctl/src/main.rs#L1818

but
`Opt { 
    pd: None,
    log_level: "info", 
    host: None, 
    ca_path: None, 
    cert_path: None,  
    key_path: None, 
    config: None, 
    data_dir: None,
  ......
`

**Comment by peng1999** [comment]
> but `Opt { pd: None, log_level: "info", host: None, ca_path: None, cert_path: None, key_path: None, config: None, data_dir: None, ......`

This is the current behavior. We cannot set a meaningful default value for these fields, so it panics (unwrapping a `None`) when using a value that is not provided. In this case, the missing value is `data_dir`.

This behavior should be improved easily by adding `require-if` attributes to the fields so a user-friendly message could be printed.

**Comment by JayiceZ** [comment]
> > but `Opt { pd: None, log_level: "info", host: None, ca_path: None, cert_path: None, key_path: None, config: None, data_dir: None, ......`
> 
> This is the current behavior. We cannot set a meaningful default value for these fields, so it panics (unwrapping a `None`) when using a value that is not provided. In this case, the missing value is `data_dir`.
> 
> This behavior should be improved easily by adding `require-if` attributes to the fields so a user-friendly message could be printed.

What do you think of using `clap::ArgGroup`? For example, `pd`, `host`, `data-dir`  will be in one group, so we must specify one of them.

**Comment by peng1999** [comment]
> What do you think of using `clap::ArgGroup`? For example, `pd`, `host`, `data-dir` will be in one group, so we must specify one of them.

Sure. `host` and `data-dir` can be in a `ArgGroup` and required by curresponding subcommands and `pd` is required by commands in [here](https://github.com/tikv/tikv/blob/master/cmd/tikv-ctl/src/main.rs#L1959).

**Comment by JayiceZ** [comment]
> > What do you think of using `clap::ArgGroup`? For example, `pd`, `host`, `data-dir` will be in one group, so we must specify one of them.
> 
> Sure. `host` and `data-dir` can be in a `ArgGroup` and required by curresponding subcommands and `pd` is required by commands in [here](https://github.com/tikv/tikv/blob/master/cmd/tikv-ctl/src/main.rs#L1959).

But it seems that clap doesn't support `an arg is required by subcommand`  because subcommand is in another namespace.

do you have any idea to implement that?🤔

**Comment by JayiceZ** [comment]
> > > What do you think of using `clap::ArgGroup`? For example, `pd`, `host`, `data-dir` will be in one group, so we must specify one of them.
> > 
> > 
> > Sure. `host` and `data-dir` can be in a `ArgGroup` and required by curresponding subcommands and `pd` is required by commands in [here](https://github.com/tikv/tikv/blob/master/cmd/tikv-ctl/src/main.rs#L1959).
> 
> But it seems that clap doesn't support `an arg is required by subcommand` because subcommand is in another namespace.
> 
> do you have any idea to implement that?🤔

see https://github.com/TeXitoi/structopt/issues/515 and https://github.com/TeXitoi/structopt/issues/464#issuecomment-920015044

**Comment by peng1999** [comment]
So currently our requirements may be too complicated for clap. 😂 
However we can still write the error handling logic manually. By using `clap::Error` in clap v3 we can write something like this:
```rust
let pd = opt.pd.unwrap_or_else(|| {
    Opt::into_app().error(
        ErrorKind::MissingRequiredArgument,
        "--pd is required for this command",
    )
    .exit();
});
```

**Comment by JayiceZ** [comment]
> So currently our requirements may be too complicated for clap. 😂 However we can still write the error handling logic manually. By using `clap::Error` in clap v3 we can write something like this:
> 
> ```rust
> let pd = opt.pd.unwrap_or_else(|| {
>     Opt::into_app().error(
>         ErrorKind::MissingRequiredArgument,
>         "--pd is required for this command",
>     )
>     .exit();
> });
> ```

Got it! Thanks for your patient reply.
I will try to fix it
