### ISSUE TITLE
Add functionalities that helps detecting potential data inconsistency

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#11542]
## Development Task

This is part of https://github.com/pingcap/tidb/issues/26833 , and there needs an issue in TiKV repo that the PRs' can refer to in the commit messages. 😕

The TiKV part is to support an assertion mechanism that, during  a prewrite request, asserts a key exists or not exists before, and when an assertion is violated, it must indicates that there's some bug.

Related PRs:

* https://github.com/tikv/tikv/pull/11516
* https://github.com/tikv/tikv/pull/11518
* https://github.com/tikv/tikv/pull/10977

**Comment by ekexium** [comment]
Can we close it?

**Comment by MyonKeminta** [comment]
> Can we close it?

I think yes.
