### ISSUE TITLE
One TiKV OOM when it exhausts memory in one numa

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11547]
### What version of TiKV are you using?

[root@IDC-172-16-6-60 bin]# ./tikv-server -V
TiKV
Release Version:   5.2.3
Edition:           Community
Git Commit Hash:   2bba8cce69b1da1cfb1181ed4630b084ad7a542b
Git Commit Branch: heads/refs/tags/v5.2.3
UTC Build Time:    2021-11-20 04:29:29
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### Steps to reproduce

Use sysbench insert, 300 thread.

### What did you expect?
Nothing error hit.

### What did happened?
One tikv oom many times.
![image](https://user-images.githubusercontent.com/9443637/144398817-d00a3506-e792-46a0-bf1e-d2663c239510.png)
[root@IDC-172-16-6-60 bin]# numastat -m

Per-node system memory usage (in MBs):
                          Node 0          Node 1           Total
                 --------------- --------------- ---------------
MemTotal                96894.21        98304.00       195198.21
MemFree                   447.65        81727.59        82175.25
MemUsed                 96446.55        16576.41       113022.96
Active                  87802.64        10575.84        98378.48
Inactive                 4768.19         2854.50         7622.69
Active(anon)            87328.89         4624.38        91953.27
Inactive(anon)           4113.32          174.57         4287.89
Active(file)              473.75         5951.46         6425.21
Inactive(file)            654.87         2679.93         3334.80
Unevictable                 0.00            0.00            0.00
Mlocked                     0.00            0.00            0.00
Dirty                       4.02            0.16            4.18
Writeback                   0.07            0.00            0.07
FilePages                1476.59         9244.65        10721.24
Mapped                     17.01          229.61          246.61
AnonPages               91100.90         4185.85        95286.75
Shmem                     277.42          597.57          874.99
KernelStack                14.69           21.23           35.92
PageTables                214.78           27.60          242.38
NFS_Unstable                0.00            0.00            0.00
Bounce                      0.00            0.00            0.00
WritebackTmp                0.00            0.00            0.00
Slab                      921.03          720.35         1641.38
SReclaimable              771.07          576.41         1347.48
SUnreclaim                149.96          143.94          293.91
AnonHugePages              36.00          180.00          216.00
HugePages_Total             0.00            0.00            0.00
HugePages_Free              0.00            0.00            0.00
HugePages_Surp              0.00            0.00            0.00

**Comment by BusyJay** [comment]
I think it's near impossible for TiKV to solve the problem. Instead we should let the system allow allocate memory across numa.

**Comment by BusyJay** [comment]
I would say it works as expected. It's an issue but not a bug.
