### ISSUE TITLE
Sysbench read and write workload hit 9007 Write conflict error

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11612]
### What version of TiKV are you using?

/ # /tikv-server -V
TiKV
Release Version:   5.3.0
Edition:           Community
Git Commit Hash:   6c1424706f3d5885faa668233f34c9f178302f36
Git Commit Branch: heads/refs/tags/v5.3.0
UTC Build Time:    2021-11-22 10:51:38
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### Steps to reproduce

run oltp test case oltp_stability_002 failed.

### What did you expect?
Case run succeeded.

### What did happened?
Hit following error.
2021-12-08T12:03:47.527+0800	INFO	oltppkg/workload.go:331	FATAL: mysql_stmt_execute() returned error 9007 (Write conflict, txnStartTS=429637298355962059, conflictStartTS=429637298355962016, conflictCommitTS=429637298382176376, key={tableID=156, indexID=1, indexValues={5025659, 5045579, }} primary={tableID=156, handle=5045579} [try again later]) for query 'COMMIT'

/var/lib/tidb/log # grep -A5 -B 5 '429637298355962016' *.log
tidb.log-[2021/12/08 04:03:47.090 +00:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=31.14879ms]
tidb.log-[2021/12/08 04:03:47.265 +00:00] [ERROR] [terror.go:307] ["encountered error"] [error=EOF] [stack="github.com/pingcap/tidb/parser/terror.Log\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:307\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:519"]
tidb.log-[2021/12/08 04:03:47.523 +00:00] [WARN] [client_batch.go:794] ["wait response is cancelled"] [to=tc-tikv-2.tc-tikv-peer.testbed-oltp-hm-k52vt.svc:20160] [cause="context canceled"]
tidb.log-[2021/12/08 04:03:47.524 +00:00] [WARN] [client_batch.go:794] ["wait response is cancelled"] [to=tc-tikv-1.tc-tikv-peer.testbed-oltp-hm-k52vt.svc:20160] [cause="context canceled"]
tidb.log-[2021/12/08 04:03:47.524 +00:00] [WARN] [client_batch.go:794] ["wait response is cancelled"] [to=tc-tikv-3.tc-tikv-peer.testbed-oltp-hm-k52vt.svc:20160] [cause="context canceled"]
tidb.log:[2021/12/08 04:03:47.524 +00:00] [WARN] [session.go:721] ["can not retry txn"] [conn=29083] [label=general] [error="[kv:9007]Write conflict, txnStartTS=429637298355962059, conflictStartTS=429637298355962016, conflictCommitTS=429637298382176376, key={tableID=156, indexID=1, indexValues={5025659, 5045579, }} primary={tableID=156, handle=5045579} [try again later]"] [IsBatchInsert=false] [IsPessimistic=true] [InRestrictedSQL=false] [tidb_retry_limit=10] [tidb_disable_txn_auto_retry=true]
tidb.log:[2021/12/08 04:03:47.524 +00:00] [WARN] [session.go:737] ["commit failed"] [conn=29083] ["finished txn"="Txn{state=invalid}"] [error="[kv:9007]Write conflict, txnStartTS=429637298355962059, conflictStartTS=429637298355962016, conflictCommitTS=429637298382176376, key={tableID=156, indexID=1, indexValues={5025659, 5045579, }} primary={tableID=156, handle=5045579} [try again later]"]
tidb.log:[2021/12/08 04:03:47.524 +00:00] [INFO] [conn.go:1069] ["command dispatched failed"] [conn=29083] [connInfo="id:29083, addr:10.233.116.131:46984 status:10, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:0, autocommit:1"] [sql=COMMIT] [txn_mode=PESSIMISTIC] [err="[kv:9007]Write conflict, txnStartTS=429637298355962059, conflictStartTS=429637298355962016, conflictCommitTS=429637298382176376, key={tableID=156, indexID=1, indexValues={5025659, 5045579, }} primary={tableID=156, handle=5045579} [try again later]\nCOMMIT"]

Logs and monitor can be get from minio via testbed testbed-oltp-hm-k52vt.

**Comment by youjiali1995** [comment]
Met the same error again:
```
"FATAL: mysql_stmt_execute() returned error 9007 (Write conflict, txnStartTS=429686608989258006, conflictStartTS=429686608989257901, conflictCommitTS=429686609054793967, key={tableID=111, indexID=1, indexValues={4768979, 1, }} primary={tableID=111, handle=7375652} [try again later]) for query 'COMMIT'\r\n"
```

The error happened on the non-unique index key which needn't be locked and check write-conflict in the pessimistic transaction, but if it's a retry request, it will check write-conflict for the safety of CDC and it's the only place that a pessimistic transaction can report a write-conflict error:
https://github.com/tikv/tikv/blob/dd7f8d89af67e72148bec7713708eeaa57fa6025/src/storage/txn/actions/prewrite.rs#L415-L425

The start_ts `429637298355962059` is around the log time([2021/12/08 04:03:47.524 +00:00]), so it's likely the pessimistic lock on the row key is lost due to pipelined pessimistic locking otherwise the other transaction can't be committed so quickly.
```pd-ctl tso 429637298355962059
system:  2021-12-08 12:03:47.249 +0800 CST
logic:  203
```

The log indicates there are some cancelled requests. I'm sure if it's related.
```
[2021/12/08 04:03:47.523 +00:00] [WARN] [client_batch.go:794] ["wait response is cancelled"] [to=tc-tikv-2.tc-tikv-peer.testbed-oltp-hm-k52vt.svc:20160] [cause="context canceled"]
[2021/12/08 04:03:47.524 +00:00] [WARN] [client_batch.go:794] ["wait response is cancelled"] [to=tc-tikv-1.tc-tikv-peer.testbed-oltp-hm-k52vt.svc:20160] [cause="context canceled"]
[2021/12/08 04:03:47.524 +00:00] [WARN] [client_batch.go:794] ["wait response is cancelled"] [to=tc-tikv-3.tc-tikv-peer.testbed-oltp-hm-k52vt.svc:20160] [cause="context canceled"]
[2021/12/08 04:03:47.524 +00:00] [WARN] [session.go:721] ["can not retry txn"] [conn=29083] [label=general] [error="[kv:9007]Write conflict, txnStartTS=429637298355962059, conflictStartTS=429637298355962016, conflictCommitTS=429637298382176376, key={tableID=156, indexID=1, indexValues={5025659, 5045579, }} primary={tableID=156, handle=5045579} [try again later]"] [IsBatchInsert=false] [IsPessimistic=true] [InRestrictedSQL=false] [tidb_retry_limit=10] [tidb_disable_txn_auto_retry=true]
```

**Comment by MimeLyc** [comment]
refresh
