### ISSUE TITLE
Deprecation of std::<primitives>::(MIN|MAX|etc)

### ISSUE THREAD

**Issue by hdost** [tikv/tikv#11678]
## Development Task
Deprecation is planned for MIN,MAX,EPSLION,INFINITY,NEG_INFINITY of
the (i|u|f)(8|16|32|64) types in standard.
 
Example seen here: https://doc.rust-lang.org/std/i64/index.html

**Comment by youjiali1995** [comment]
Closed by https://github.com/tikv/tikv/pull/11677.
