### ISSUE TITLE
TiKV may still panic when kernel patch version larger than 255 due to procfs/issues/136

### ISSUE THREAD

**Issue by NingLin-P** [tikv/tikv#11702]
### What version of TiKV are you using?

Master

### Steps to reproduce

Although https://github.com/tikv/tikv/pull/11458 had updated the prometheus dependency to `0.13.0` to avoid https://github.com/eminence/procfs/issues/136, there are still some places in TiKV using `procfs 0.9.1` that may cause panic due to https://github.com/eminence/procfs/issues/136 

https://github.com/tikv/tikv/blob/849a01d2e7498f56e61850bfa2dc8abd8fd58fd6/components/tikv_util/src/metrics/process_linux.rs#L62

https://github.com/tikv/tikv/blob/849a01d2e7498f56e61850bfa2dc8abd8fd58fd6/components/tikv_util/src/metrics/process_linux.rs#L83

**Comment by youjiali1995** [comment]
Need to update `procfs` to 0.12 and `prometheus` to 0.13 to fix it. That means, we should cherry-pick https://github.com/tikv/tikv/pull/11703 to update `procfs`, and part of https://github.com/tikv/tikv/pull/10175 and https://github.com/tikv/tikv/pull/11458 to update `prometheus`.

**Comment by NingLin-P** [comment]
> Need to update `procfs` to 0.12 and `prometheus` to 0.13 to fix it. That means, we should cherry-pick #11703 to update `procfs`, and part of #10175 and #11458 to update `prometheus`.

I found that `prometheus` only require `procfs`  if `#[cfg(all(feature = "process", target_os = "linux"))]`, the process feature is not a default feature and not enabled by TiKV too, such that we can see in `Cargo.lock` only the `tikv_util` crate depend on `procfs` but the `prometheus` crate do not.

That means we only need to cherry-pick #11703 to update `procfs` to 0.12 to fix this issue. /cc @youjiali1995 @tabokie 
For the `prometheus` analyze /cc @overvenus 

More detail code paths in `prometheus`:

The only place using `procfs` is `ProcessCollector`:
https://github.com/tikv/rust-prometheus/blob/ac86a264223c8d918a43e739ca3c48bb4aaedb90/src/process_collector.rs#L135-L141

And `ProcessCollector` only be used if `#[cfg(all(feature = "process", target_os = "linux"))]`:
https://github.com/tikv/rust-prometheus/blob/ac86a264223c8d918a43e739ca3c48bb4aaedb90/src/lib.rs#L171-L172
https://github.com/tikv/rust-prometheus/blob/ac86a264223c8d918a43e739ca3c48bb4aaedb90/src/registry.rs#L295-L308
