### ISSUE TITLE
Standalone streaming for reporting buckets flow

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#11718]
Currently, region flow is reported through region heartbeat every 60s. After introducing dynamic region, we need more timely information for region split, so buckets flow should be reported more frequently.
For more details see [0082-dynamic-size-region.md#flow-report](https://github.com/tikv/rfcs/blob/master/text/0082-dynamic-size-region.md#flow-report)

**Comment by lhy1024** [comment]
At present, TiKV report hot read statistics to PD by store heartbeat and report hot write statistic to PD by region heartbeat. I think we can unify them to store heartbeat.

**Comment by lhy1024** [comment]
So it's really two questions：
1. Do we need Standalone streaming?
2. Is the granularity of report store or region or bucket?

**Comment by nolouch** [comment]
We can use store stream to report TopN same as read flow. but change region heartbeat to store heartbeat will influence keyviz for now.

**Comment by 5kbpers** [comment]
> So it's really two questions：
> 
> 1. Do we need Standalone streaming?
> 2. Is the granularity of report store or region or bucket?

1. The benefit of standalone streaming is that we can change the duration of reporting flow individually. Reporting flow through store heartbeats seems to be more simple, so we can implement it in this way and introduce standalone streaming later if we do have needs. 
2. Will be buckets.

cc @lhy1024 @nolouch

**Comment by 5kbpers** [comment]
> We can use store stream to report TopN same as read flow. but change region heartbeat to store heartbeat will influence keyviz for now.

We can keep the flow reporting in region heartbeat.

**Comment by bufferflies** [comment]
There will be consistency problem if keeps two reporting channel.

**Comment by BusyJay** [comment]
Can this be closed?
