### ISSUE TITLE
sysbench write only run makes tikv oom

### ISSUE THREAD

**Issue by Tammyxia** [tikv/tikv#11747]
### What version of TiKV are you using?

TiKV 
Release Version:   5.0.6
Edition:           Community
Git Commit Hash:   7fcfaf4a9dd6b245fa7b6ac26740effda57b5139
Git Commit Branch: heads/refs/tags/v5.0.6
UTC Build Time:    2021-12-21 09:12:26
Rust Version:      rustc 1.51.0-nightly (bc39d4d9c 2021-01-15)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?

k8s pod, 3 tikv, each  has 8c, 16g memory

### Steps to reproduce

- Testbed: 3 tikv 16GB memory, 3 pd, 3 tidb, test-infra k8s.
- Workload: 
   1.   2021-12-28T19:32:34.888Z   INFO    host/workload.go:41     Execute command {"command": "sysbench --db-driver=mysql --mysql-host=upst
ream-tidb.cdc-testbed--tps-542872-1-247 --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=300 --table-size=50 --time=3600 --debug=true --threads=1
00 oltp_write_only prepare", "timeout": "1h10m0s", "resource name": "workload"}
  2.   2021-12-28T19:53:54.677Z   INFO    host/workload.go:41     Execute command {"command": "sysbench --db-driver=mysql --mysql-host=upst
ream-tidb.cdc-testbed--tps-542872-1-247 --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=300 --table-size=50 --time=3600 --debug=true --threads=1
00 oltp_write_only run", "timeout": "1h10m0s", "resource name": "workload"}
### What did you expect?

- TiKV can recognize cgroup memory limit (<= 70% totally memory), to avoid OOM.

### What did happened?
![image](https://user-images.githubusercontent.com/78345569/147636244-7652336b-9c9b-4716-bedc-ece93f70148e.png)
![image](https://user-images.githubusercontent.com/78345569/147636321-1644623c-5e84-431a-a618-a9d45fdc8548.png)

**Comment by ethercflow** [comment]
Not repro in 6.1 LTS.

**Comment by overvenus** [comment]
We haven't seen similar report in past two years, I believe we have fixed/mitigated this issue. 
Feel free to reopen if it occurs again.
