### ISSUE TITLE
raftstore: snapshot files may deleted while the peer state is still `PeerState::Applying`

### ISSUE THREAD

**Issue by NingLin-P** [tikv/tikv#11746]
### What version of TiKV are you using?

Matser

### What operating system and CPU are you using?

Not related

### Steps to reproduce

A peer with the peer state set to `PeerState::Applying` is started the apply snapshot process. If before it actually starts to apply snapshot data, it received a message (gc message or raft msg with larger peer id) telling it to destroy itself, the peer will try to cancel applying snapshot and submit the change of peer state (to `PeerState::Tombstone`) to the `WriteBatch`.

At the meantime, a canceled snapshot will be gc by the `StoreTick::SnapGc` tick, which will delete the snapshot files immediately and the `WriteBatch` may not persist yet. If TiKV then crashes and recover, the peer state is still `PeerState::Applying` and TiKV will panic because the snapshot does not exist.

This case can happen in scenarios like a TiKV is down while there are regions applying snapshot, and recover after a long time, by then these regions will try to continue to apply snapshot and the leader will tell them to gc themself, at this time the TiKV is crashed.

### What did you expect?

Not panic

### What did happened?

Panic because snapshot files not exist

**Comment by BusyJay** [comment]
Is it duplicated with https://github.com/tikv/tikv/issues/11618?

**Comment by NingLin-P** [comment]
> Is it duplicated with #11618?

I think it is different, the root cause of this bug is the delete of snapshot files and the persist of `PeerState::Tombstone` are not atomic.

**Comment by BusyJay** [comment]
> a canceled snapshot will be gc by the StoreTick::SnapGc tick, which will delete the snapshot files immediately

How can this happen? `StoreTick` will not delete the files unless mailbox is not found. And the mailbox is destroyed only after the tombstone state is written to disk.

**Comment by NingLin-P** [comment]
> How can this happen? `StoreTick` will not delete the files unless mailbox is not found. And the mailbox is destroyed only after the tombstone state is written to disk.

More precisely, the `StoreTick::SnapGc` will collect snapshot files that not currently applying and send them to the corresponding peer, and the peer will find it is not applying a snapshot (which had aborted by `maybe_destroy`) so delete the snapshot files immediately.

**Comment by BusyJay** [comment]
It should be major as it hardly happen.
