### ISSUE TITLE
Resolved ts exceed 1 hours for more than 30min without any fault inject

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11767]
### What version of TiKV are you using?

/ # /tikv-server -V
TiKV
Release Version:   5.4.0-alpha
Edition:           Community
Git Commit Hash:   74cd8ae2a9ff930460cba15acdf1847726eb6db8
Git Commit Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time:    2021-12-31 05:14:05
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### Steps to reproduce

run oltp_stability_002
Run sysbench read only workload, and do split region repeatly and randomly.

### What did you expect?
resolved ts should below serval minutes.

### What did happened?
![image](https://user-images.githubusercontent.com/9443637/147817972-23aac9da-a395-4088-ae31-1bb5cc4b11eb.png)

**Comment by 5kbpers** [comment]
From the log we can ensure that the region with minimal resolved ts is an orphan follower:
![image](https://user-images.githubusercontent.com/20279863/148382580-b7b43c90-16d7-421c-9cff-1766ad785822.png)

In general, the resolved ts of a follower should be synced from its leader. But in this case, the orphan follower cannot get resolved ts from any other peer, so this phenomenon is expected.

This issue exports a problem that we can not simply distinguish whether the resolved ts could not be advanced or just could not receive from leaders. This PR #11809 added more metrics to fix this problem.

**Comment by mayjiang0203** [comment]
affects-5.3
