### ISSUE TITLE
Log level for IO snooper failure is too high

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#11775]
### What version of TiKV are you using?
/ # ./tikv-server -V
TiKV
Release Version: 5.4.0-alpha
Edition: Community
Git Commit Hash: 99b3436
Git Commit Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time: 2022-01-04 01:15:55
Rust Version: rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features: jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile: dist_release

### What operating system and CPU are you using?
8core 16G

### Steps to reproduce
oltp_stability_rel_002
1、
/pd-ctl schedule add shuffle-leader-scheduler:Success!
/pd-ctl schedule add shuffle-region-scheduler:Success!
/pd-ctl schedule add random-merge-scheduler:Success!
2、
go-tpc tpcc run -D tpcc --host tc-tidb.endless-oltp--tps-543619-1-288 -P4000 --warehouses 1000 -T 512 --time 36000m --ignore-error '2013,1213,1105,1205,8022,8027,8028,9004,9007,1062‘
3、
Run chaos {"name": "network-loss", "selectors": ["endless-oltp--tps-543619-1-288/tc-tikv-2"], "experiment": {"Duration":"","Scheduler":null,"Loss":"76","Correlation":"25"}}

### What did you expect?
logs level are right for below log
[2022/01/04 07:05:58.465 +00:00] [ERROR] [server.rs:1071] ["failed to init io snooper"] [err_code=KV:Unknown] [err="\"IO snooper is not started due to not compiling with BCC\""]

### What did happened?
this log should not set to ERRPOR level
[2022/01/04 07:05:58.465 +00:00] [ERROR] [server.rs:1071] ["failed to init io snooper"] [err_code=KV:Unknown] [err="\"IO snooper is not started due to not compiling with BCC\""]

**Comment by sticnarf** [comment]
Can you please describe the phenomenon and what you expect more clearly? What do you mean "logs are right"?

**Comment by Lily2025** [comment]
> Can you please describe the phenomenon and what you expect more clearly? What do you mean "logs are right"?

Little-Wallace says the log below should not be of error level 

[2022/01/04 07:05:58.465 +00:00] [ERROR] [server.rs:1071] ["failed to init io snooper"] [err_code=KV:Unknown] [err=""IO snooper is not started due to not compiling with BCC""]
