### ISSUE TITLE
Better bounding restriction for configuring rocksdb background workers

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#11776]
### What version of TiKV are you using?
/ # ./tikv-server -V
TiKV
Release Version: 5.4.0-alpha
Edition: Community
Git Commit Hash: 99b3436
Git Commit Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time: 2022-01-04 01:15:55
Rust Version: rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features: jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile: dist_release

### What operating system and CPU are you using?
8core 16G

### Steps to reproduce
modify rocksdb.max-background-jobs from default 7 to 8

### What did you expect?
can modify rocksdb.max-background-jobs success within a reasonable range

### What did happened?
modify rocksdb.max-background-jobs from default 7 to 8， modify failed

**Comment by ethercflow** [comment]
Currently restricted by the implementation of Rocksdb, we only support scaling up. In actual usage scenarios, we almost always increase it.

If we want to support shrinking, we need to make more changes, and we have not done shrinking related tests at present.

So it is recommended that version 5.4 keep the current behavior

**Comment by tabokie** [comment]
I can't connect the bug report with the title. The "reproduce" section says you tune *up* the background jobs:
> modify rocksdb.max-background-jobs from default 7 to 8， modify failed
