### ISSUE TITLE
one tikv（recovered pod）oom repeatedly when network fault recover while run tpcc

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#11774]
### What version of TiKV are you using?
/ # ./tikv-server -V
TiKV 
Release Version:   5.4.0-alpha
Edition:           Community
Git Commit Hash:   99b34363cda1bd394ae689802655e9d9cf76d7fb
Git Commit Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time:    2022-01-04 01:15:55
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What operating system and CPU are you using?
8core 16G
NS：endless-oltp--tps-543619-1-288
https://tcms.pingcap.net/dashboard/executions/plan/543619

### Steps to reproduce
oltp_stability_rel_002
1、
/pd-ctl schedule add shuffle-leader-scheduler:Success!
/pd-ctl schedule add shuffle-region-scheduler:Success!
/pd-ctl schedule add random-merge-scheduler:Success!
2、
go-tpc tpcc run -D tpcc --host tc-tidb.endless-oltp--tps-543619-1-288 -P4000 --warehouses 1000 -T 512 --time 36000m --ignore-error '2013,1213,1105,1205,8022,8027,8028,9004,9007,1062‘
3、
Run chaos	{"name": "network-loss", "selectors": ["endless-oltp--tps-543619-1-288/tc-tikv-2"], "experiment": {"Duration":"","Scheduler":null,"Loss":"76","Correlation":"25"}}

### What did you expect?
all pods are normal

### What did happened?
one tikv oom repeatedly
![image](https://user-images.githubusercontent.com/84712107/148024655-3748ef47-cafe-4230-bd24-c5c30d8dc073.png)

![cvBiqA9NnR](https://user-images.githubusercontent.com/84712107/148024721-b556b6ed-b3b4-4c17-80e3-215baf2bc460.png)

**Comment by Little-Wallace** [comment]
This environment was inject network error, and it may cause some rpc failed

**Comment by Lily2025** [comment]
https://tcms.pingcap.net/dashboard/executions/plan/514289 similar issue 
tikv3 oom:
    State:          Running
      Started:      Mon, 10 Jan 2022 17:08:28 +0800
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Mon, 10 Jan 2022 16:31:54 +0800
      Finished:     Mon, 10 Jan 2022 17:08:27 +0800
logs：http://minio.pingcap.net:42041/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLW9sdHAtLXRwcy01MTQyODktMS00MDY=

**Comment by cfzjywxk** [comment]
Another oom issue
https://github.com/tikv/tikv/issues/11838

**Comment by cfzjywxk** [comment]
@tonyxuqqi @5kbpers 
Do we have any new memory insight method besides the memory trace panel and dumping the jemalloc profile?
It's hard to tell if it's expected for this phenomenon described by @Lily2025.

**Comment by Lily2025** [comment]
fixed
