### ISSUE TITLE
If a key and multiple values are repeatedly written to tikv and the region is not split, will tikv crash?

### ISSUE THREAD

**Issue by cargo-youth** [tikv/tikv#11797]

**Comment by tabokie** [comment]
It shouldn't.

**Comment by eulerf** [comment]
If a single region does not split to a large extent, the current threshold of 70g will not cause tikv to crash, right?

**Comment by tabokie** [comment]
I don't know about the "70G" threshold, could you point me to a source reference?
Even if there is a upper bound, a single key is unlikely to breach that. TiKV periodically GC the stale MVCC versions of your key, so the flat data size will be small. RocksDB also cleans up its internal MVCC versions via compaction, so the physical data size is manageable.

**Comment by eulerf** [comment]
This may be a misunderstanding. This threshold is the upper limit of a single region displayed as 70G in our monitoring panel data, not that region.

**Comment by eulerf** [comment]
As long as it is safe enough, there is no doubt about this problem

**Comment by eulerf** [comment]
The txnkv method of cilint-go we used to write the current single unsplit region reached 70G.

**Comment by tabokie** [comment]
Is that one of your customized panels? I only know we have an alert for approximate region size [here](https://github.com/tikv/tikv/blob/650e85a49e561921d7f6c3268d839c889535281e/metrics/alertmanager/tikv.rules.yml#L292). And that threshold is 1GB.

**Comment by eulerf** [comment]
Yes, we triggered this threshold warning. Check the region's size panel to show 70G, so what will happen if this region continues to not split?

**Comment by tabokie** [comment]
There is two possibilities here:
1. You hit a bug (#11217), stale records are not properly GC-ed, please upgrade to versions >= v5.0.5, v5.1.3, v5.2.3, v5.3.0.
2. The RocksDB compaction didn't cleanup your outdated data in time. And the physical size of your data is growing. In this case, the performance won't actually be affected and TiKV is safe to service. Of source, you can still try to speed up the progress by this command: `tikv-ctl --host <tikv-ip:port> --cf write -r <region-id> --bottommost force && tikv-ctl --host <tikv-ip:port> --cf default -r <region-id> --bottommost force`.

**Comment by eulerf** [comment]
Thank you for your reply. I have communicated with the technical teachers in the community before and got the reply: If you insert the same key repeatedly, although there are many mvcc version data in rockdb, there is only one key for tikv, so it cannot be split. I also verified on the latest version 5.3

**Comment by eulerf** [comment]
So for the same key with multiple values, can we modify the code to split it. When I talked with the technical teacher before, I did such an instruction to manually distribute the split

**Comment by tabokie** [comment]
I think it's self-evident that you can't split a single key. And since the size of such region doesn't affect online service, I don't think you should pay much attention to it.

**Comment by eulerf** [comment]
Yes, I also think that such a key cannot trigger a split. A normal region split should be the split of key a-c into key a-b and key b-c. Is it only allowed for a large region?

**Comment by tabokie** [comment]
We have a configuration for that: https://github.com/tikv/tikv/blob/650e85a49e561921d7f6c3268d839c889535281e/etc/config-template.toml#L443

**Comment by eulerf** [comment]
Yes, we also use this configuration file, but it will not affect the triggering of the split. Our online cluster environment is 3pd+3tikv. Can you wait for a while. I will find the corresponding code of the error message and discuss it with us. Do you think it is okay?

**Comment by eulerf** [comment]
This is our post on asktug https://asktug.com/t/topic/212965/12

**Comment by tabokie** [comment]
I'm a little confused, I though you were talking about the general case where region has several keys. Region with a single key will not be split, and we won't alter the current design to make it split.

**Comment by eulerf** [comment]
Okay, thank you for your Q&A. Although it does not affect the business, a large region will always occupy the disk, which is also our concern.

**Comment by tabokie** [comment]
Assuming you are only storing one key in a single TiKV, you can try tuning the RocksDB parameters to reduce space amplification. E.g. `rocksdb.defaultcf|writecf.num-levels = 3`

**Comment by eulerf** [comment]
Hi. Our business scenario is like this. Use tikv to store the value of a key at different times. When we use it frequently, we will continue to write a key (only the value has changed), so a region will increase without splitting. We are worried that he will fill up our disk. So can you give some suggestions in this situation, or that our use is wrong.

**Comment by tabokie** [comment]
Like I said, if you don't have a lot of keys in the DB, then it's safe to apply some RocksDB configurations that can reduce disk space usage.
For fresh deployment (no existing data): `rocksdb.defaultcf|writecf.num-levels = 2`
For existing cluster: `rocksdb.defaultcf|writecf.max-bytes-for-level-multiplier = 2`

**Comment by eulerf** [comment]
Ok thank you so much

**Comment by eulerf** [comment]
In addition, we have observed that when the writing stops, the region size will drop. We speculate that there is a gc mechanism after the heat drops? We want to study the design of tikv's source code. Can you recommend the directory where the relevant code is located?

**Comment by tabokie** [comment]
We have two ways of estimating region size,: 1) ask for the physical data size from RocksDB, this estimation includes deleted entries, and can be bloated. 2) scan for actual keys in the range, and summing up their value size, this estimation is accurate.

I suspect when the write flow stops, the estimation converges to a stable and accurate value.

The code for this process is here:
https://github.com/tikv/tikv/blob/15591892abafcca11e1fbbe180507e7bb4965726/components/raftstore/src/store/worker/split_check.rs#L288-L294

**Comment by eulerf** [comment]
Okay, thank you very much, and whether you can recommend routes and community information related to the contributed code

**Comment by tabokie** [comment]
Do you mean a development guide of sorts? We have a [source code reading series](https://pingcap.com/zh/blog/?tag=TiKV%20%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90).

**Comment by cargo-youth** [comment]
Thanks to the community, I learned a lot
