### ISSUE TITLE
param resource-metering.enabled  is deleted in v5.4.0, upgrade to 5.4.0 will fail if pre-upgrade version include this config

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#11836]
### What version of TiKV are you using?
v5.4.0

### Steps to reproduce
Error: init config failed: 172.16.6.77:2360: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@172.16.6.77:22' {ssh_stderr: unknown configuration options: resource-metering.enabled
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /home/tidb/deploy/tikv-2360/bin/tikv-server --config-check --config=/home/tidb/deploy/tikv-2360/conf/tikv.toml --pd "" --data-dir "/home/tidb/deploy/tikv-2360/data"}, cause: Process exited with status 1: check config failed

Verbose debug logs has been written to /home/tidb/.tiup/logs/tiup-cluster-debug-2022-01-11-11-14-29.log.
Error: run `/home/tidb/.tiup/components/cluster/v1.8.1/tiup-cluster` (wd:/home/tidb/.tiup/data/SuAsiQg) failed: exit status 1
[tidb@101 540]$ 
### What did you expect?
this config can be ignored
### What did happened?
upgrade fail

**Comment by you06** [comment]
Since `resource-metering.enabled` is not released, backward compatibility may not be guaranteed.
