### ISSUE TITLE
Change PeerTicks to a simple enum

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#11848]
`PeerTicks` is defined as bitflags:

https://github.com/tikv/tikv/blob/0743109814002b23d539379777a33c56797362fb/components/raftstore/src/store/msg.rs#L183

But `PeerTicks` doesn't need to be bitflags. Only when scheduling ticks need we check if a `PeerTick` exists in a set, but it can be achieved in other ways efficiently too.

It also makes extending the types of `PeerTick` more difficult. It is now defined as `u8` and if we need more tick types, we have to change it to u16. It also wastes space because `tick_batch` needs 2^n space where n is the type of ticks.

Therefore, I think it more appropriate to define `PeerTicks` as an enum. This will make it easier to extend more tick types.

**Comment by BusyJay** [comment]
> ...because tick_batch needs 2^n space where n is the type of ticks.

Can changing index to `BitFlags::bits().trailing_zeros()` solve the problem?

**Comment by sticnarf** [comment]
> Can changing index to `BitFlags::bits().trailing_zeros()` solve the problem?

Yes. But actually the biggest motivation is that using an enum is more _semantically_ reasonable. When using a `PeerTicks`, we never combine multiple flags, so that's not bitflags typically used for. 

If we _really_ want to save space for the `registry`, we can just use a bitset for that.

**Comment by BusyJay** [comment]
`bitset` LGTM. The reason `BitFlags` is used is for querying and updating registry quickly. Space is not in concern.

**Comment by sticnarf** [comment]
> `bitset` LGTM. The reason `BitFlags` is used is for querying and updating registry quickly. Space is not in concern.

Then, PTAL the current implementation of #11849. It's now using a bool array for registry, which seems faster than bit operations, according to microbenchmarks:

```rust
#[bench]
fn bench_bool_arr_get(b: &mut Bencher) {
    let v = [true; 16];
    b.iter(|| {
        for i in 0..1000 {
            let pos = i % 16;
            black_box(black_box(&v)[pos]);
        }
    });
}

#[bench]
fn bench_bool_arr_set(b: &mut Bencher) {
    let mut v = [false; 16];
    b.iter(|| {
        for i in 0..1000 {
            let pos = i % 16;
            black_box(&mut v)[pos] = true;
        }
    });
}

#[bench]
fn bench_bitset_get(b: &mut Bencher) {
    let v = 0xabcdu16;
    b.iter(|| {
        for i in 0..1000 {
            let pos = i % 16;
            black_box(black_box(&v) & (1 << pos) != 0);
        }
    });
}

#[bench]
fn bench_bitset_set(b: &mut Bencher) {
    let mut v = 0u16;
    b.iter(|| {
        for i in 0..1000 {
            let pos = i % 16;
            *black_box(&mut v) |= 1 << pos;
        }
    });
}
```

The result:

```
test bench_bitset_get   ... bench:         428 ns/iter (+/- 2)
test bench_bitset_set   ... bench:       1,273 ns/iter (+/- 145)
test bench_bool_arr_get ... bench:         425 ns/iter (+/- 5)
test bench_bool_arr_set ... bench:         887 ns/iter (+/- 9)
```
