### ISSUE TITLE
Implement tracing for TiKV

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#11872]
## Development Task

- [x] https://github.com/tikv/minitrace-rust/pull/67
- [x] https://github.com/tikv/minitrace-rust/pull/71
- [x] https://github.com/tikv/minitrace-rust/pull/74
- [x] https://github.com/pingcap/kvproto/pull/846
- [ ] https://github.com/tikv/tikv/pull/11824
- [ ] Allow Java client to send trace context in the request

## Useful material

- https://github.com/zhongzc/tikv/commit/db76b66a2ea3cb23e0cab4e043500e5a31c16fbc
- https://pingcap.feishu.cn/docs/doccnessOsvm9waxwPqt5h7CMXl
- https://docs.google.com/presentation/d/1Tb0amFbuB9IDNMhh5x9Sujujes2lXrg1GqdGv5HkNck/edit?usp=sharing

**Comment by Aiixalex** [comment]
Hi! I'm a senior CS student from Zhejiang University and I'm really interested in contributing to TiKV with this idea. In the process of learning distributed databases, I learned about and became interested in tikv and i'm eager to and passionate about contributing my code to this project.
Would you mind offer me some advise on how to start my journey in tikv community as well as preparing for solving this idea during GSoC 2022?

**Comment by kiibo382** [comment]
@andylokandy  (and other experts)

Hi! My name is Shota. I'm preparing to apply for the GSoC. There are a few confirmations and requests.

1. Goal of this issue
    I recognized that the goal of this issue is to be able to see TiKV trace graphs, slow query logs, etc. from the Jaeger UI and Datadog dashboard when the TiUP or TiDB Operator trace switch is turned on. To achieve it, we will implement features to send reports to Jaeger or Datadog by using minitrace-rust.
    For each query (trace id), we will collect the following information
    - Counts of parses, executions, and fetches
    - CPU time and elapsed time (latency)
    - Number of rows processed
    - Each commit and rollback
    - Summary of wait events for each SQL statement
    - Row operations showing the actual execution plan for each SQL statement
    - Number of physical reads, physical writes, and elapsed time for each row operation
    
    Please advise me if I make a mistake or have anything to add.

2. status of this issue
    I interpreted that most of the design & policy-making are finished, but implementation is not yet complete.
    (I saw [this PR](https://github.com/tikv/tikv/pull/11824) .)
    Please point out if my interpretation is wrong. Also, if you have any advice, please let me know.

3. what I need to research
    List any uncertainties as you make policy decisions and design the project.

If you have any other resources that would be helpful for implementation, please share them with me.

**Comment by andylokandy** [comment]
ping gsoc mentors @breeswish @zhongzc

**Comment by kiibo382** [comment]
Thanks!!
