### ISSUE TITLE
Spawn TiKV without 24GB intial disk space

### ISSUE THREAD

**Issue by kokizzu** [tikv/tikv#11895]
## Question

is it possible to spawn TiKV without 24GB intiial disk consumption?

I'm using this docker-compose https://github.com/kokizzu/hugedbbench/blob/master/2021/tidb/docker-compose-single.yaml to test it locally

**Comment by BusyJay** [comment]
You may check the configuration `reserve-space`: https://tikv.org/docs/dev/tasks/configure/storage/#reserve-space

**Comment by kokizzu** [comment]
oh it's newer config

ah nice it works, thanks a lot, now i can test locally without make my disk full
