### ISSUE TITLE
GC Keys tasks executes slowly due to millions of seek_tombstone

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11902]
### What version of TiKV are you using?

/ # /tikv-server -V
TiKV
Release Version:   5.4.0-alpha
Edition:           Community
Git Commit Hash:   e8718be24177a7218c317ade7d8055a3a1c4d6b5
Git Commit Branch: heads/refs/tags/v5.5.0-nightly
UTC Build Time:    2022-01-24 06:09:14
Rust Version:      rustc 1.59.0-nightly (cfa4ac66c 2022-01-06)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What did you expect?
Should be dropped during serval minutes.

### What did happened?
280G took 2 hours to drop.

From GC tasks duration, we can see that gc_keys is very slow. Since total size to be dropped only has 280G, the seek-tombstone in GC scan write detail seems abnormal.   

![image](https://user-images.githubusercontent.com/9443637/150773926-41ac7e0d-b527-4472-9b29-10be6cff21ba.png)

![image](https://user-images.githubusercontent.com/9443637/150774002-dfda6984-206a-4ae9-9885-ab5141d91c9d.png)

![image](https://user-images.githubusercontent.com/9443637/150774073-84374c15-9cf8-4e54-9fbd-c1b509336822.png)

![image](https://user-images.githubusercontent.com/9443637/150774126-b8df4c2b-7ffe-442a-9ce5-1682464cf2e4.png)

Slow gc_keys tasks may block execution of unsafe_destroy_range tasks and further blocks TiDB's GC procedure (causes #11752)

**Comment by MyonKeminta** [comment]
GC keys tasks runs too slowly. It looks to be caused by too many tombstones.

Since GC keys tasks don't set the range of the rocksdb iterator, it's possible that here are many GC keys tasks that unnecessarily scans many tombstones even they are not in the task's key range. Therefore one of the possible optimization would be setting proper bounds to the iterators in GC keys tasks. cc @Connor1996

**Comment by Connor1996** [comment]
Agree. A better solution is to avoid triggering verbose gc-keys tasks when the key is already deleted, though hard to realized.

**Comment by mayjiang0203** [comment]
logs and granfana can be get from minio by testbed-oltp-hm-rfkks.
