### ISSUE TITLE
Slow to handle Raft messages but no obvious latency source

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#11927]
### What version of TiKV are you using?

v4.0.14

The raftstore got stuck printing these logs:

```
[2022/01/27 14:20:50.487 +08:00] [WARN] [store.rs:645] ["[store 21694] handle 1 pending peers include 1 ready, 1 entries, 1 messages and 0 snapshots"] [takes=7669]
[2022/01/27 14:20:50.488 +08:00] [WARN] [store.rs:645] ["[store 21694] handle 83 pending peers include 83 ready, 1 entries, 162 messages and 0 snapshots"] [takes=7657]
```

But unlike https://github.com/tikv/tikv/issues/10210 , the time used for clearing peer meta is short. RocksDB durations all look normal.
![图片](https://user-images.githubusercontent.com/17217495/151508212-cf4b4df8-2600-497e-b065-faca355f5776.png)
![图片](https://user-images.githubusercontent.com/17217495/151508234-c4c79213-59d7-4c5c-ba98-27c8433f8a6f.png)

Related logs: [tikv.log](https://github.com/tikv/tikv/files/7956783/tikv.log)

**Comment by sticnarf** [comment]
cc @5kbpers

**Comment by 5kbpers** [comment]
![image](https://user-images.githubusercontent.com/20279863/153350008-73894dbb-be2c-4390-953a-7bc5f62c212c.png)

Through our investigation, the only related outlier is that there are some pages swapping at that time.

**Comment by Connor1996** [comment]
Encouter same problem, can you reproduce it?

**Comment by sticnarf** [comment]
> Encounter same problem, can you reproduce it?

I cannot. The issue is from some user and they only encountered the problem once.
