### ISSUE TITLE
tikv abnormally reset in 5.1.3 hotfix version

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#11923]
### What version of TiKV are you using?
/ # ./tikv-server -V
TiKV 
Release Version:   5.1.3
Edition:           Community
Git Commit Hash:   1af8392ea6a6382d7725e426cf2828ac4d70ab1a
Git Commit Branch: heads/refs/tags/v5.1.3-20220126
UTC Build Time:    2022-01-26 02:59:23
Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
8core 16G

### Steps to reproduce
run endless-oltp-sysbench-oltp-read-write-fun@v5.1.3-hotfix-20220126

### What did you expect?
all tikv are normal

### What did happened?
tikv abnormal reset for three times
test plan：https://tcms.pingcap.net/dashboard/executions/plan/631450
logs：http://minio.pingcap.net:42041/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLW9sdHAtdHBzLTYzMTQ1MC0xLTY1L3RjLXRpa3YtMi8=
![image](https://user-images.githubusercontent.com/84712107/151345737-e601e676-ab2b-4403-9238-cfe1f3f10695.png)

**Comment by sticnarf** [comment]
This is probably due to https://github.com/tikv/tikv/pull/11205. Close it because it only occurs on old versions.
