### ISSUE TITLE
Can `tikv` use libaco to get a better performance ?

### ISSUE THREAD

**Issue by loongs-zhang** [tikv/tikv#11939]
[libaco](https://github.com/hnes/libaco) is a `c lib`, the question is shown in the title.

**Comment by sticnarf** [comment]
Coroutines in TiKV are implemented with Rust async/await. I'm afraid it's not so easy to change to use a C coroutine library.

**Comment by dragon-zhang** [comment]
fine



发自我的iPhone


------------------ Original ------------------
From: Yilin Chen ***@***.***&gt;
Date: Thu,Feb 10,2022 6:03 PM
To: tikv/tikv ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [tikv/tikv] Can `tikv` use libaco to get a better performance ? (Issue #11939)





 
Coroutines in TiKV are implemented with Rust async/await. I'm afraid it's not so easy to change to use a C coroutine library.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
