### ISSUE TITLE
Stale read hit data is not ready after inject some errors to pd

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#11937]
### What version of TiKV are you using?

master

### Steps to reproduce

Run oltp plan: endless-oltp-stale-read-rel@main

Test steps:
1、Start workload sysbench read_write and stale read, read datas 5s before
2、Inject -1h time offset to pd leader, continue 5m, then delete；
3、After about 30min, hit 9005 region unavailable error which cause by data is not ready;

### What did you expect?
Should no error messages received.

### What did happened?
/var/lib/tidb/log/tidb.log:[2022/02/07 07:48:13.346 +00:00] [INFO] [conn.go:1119] ["command dispatched failed"] [conn=3555] [connInfo="id:3555, addr:10.233.111.5:43728 status:11, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:1, autocommit:1"] [sql="SELECT c FROM sbtest20 WHERE id BETWEEN ? AND ? ORDER BY c [arguments: (22795, 22894)]"] [txn_mode=PESSIMISTIC] [timestamp=431022420000768000] [err="[tikv:9005]Region is unavailable\ngithub.com/pingcap/errors.AddStack\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopResponse\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:943\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTaskOnce\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:789\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:673\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:414\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nSELECT c FROM sbtest20 WHERE id BETWEEN ? AND ? ORDER BY c [arguments: (22795, 22894)]"]

Test plan can get from tcms via plan id 602694, and logs can be from minio via testbed name endless-oltp-tps-602694-1-905.

**Comment by NingLin-P** [comment]
From the metric we can see resolved-ts fail to advance due to there are locks not cleaned up:
<img width="922" alt="截屏2022-02-08 下午6 20 44" src="https://user-images.githubusercontent.com/28501710/152967659-70b8ccf4-672a-4252-a2b6-fc205350631d.png">

causing region `12296`'s resolved-ts keep in `431021895239655218`.

**Comment by 5kbpers** [comment]
No further progress, close this issue.
