### ISSUE TITLE
Rls is missing

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#11953]
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

No related

### Steps to reproduce

```
$ rustup component add rls                                                                
error: component 'rls' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'nightly-2022-01-07'
Sometimes not all components are available in any given nightly. If you don't need the component, you can remove it with:
```

### What did you expect?
Have a rls component

**Comment by sticnarf** [comment]
Just being curious, are you still using RLS, despite it has not been in active development for a long time?

Why not use rust-analyzer instead?

**Comment by Connor1996** [comment]
> Just being curious, are you still using RLS, despite it has not been in active development for a long time?
> 
> Why not use rust-analyzer instead?

Didn't notice it before, will try

**Comment by Connor1996** [comment]
> Just being curious, are you still using RLS, despite it has not been in active development for a long time?
> 
> Why not use rust-analyzer instead?

Much better! Though still better to upgrade the toolchain if someone are using rls
