### ISSUE TITLE
sysbench oltp_write_only run failed with error: Cannot allocate memory... for query 'COMMIT'

### ISSUE THREAD

**Issue by Tammyxia** [tikv/tikv#11962]
## Bug Report

- Run sysbench oltp_write_only: "sysbench --db-driver=mysql --mysql-host=upstream-tidb.cdc-testbed-tps-603591-1-535 --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=32 --table-size=100000 --time=7200 --debug=true --threads=32 --mysql-ignore-errors=1213,1020,1205,9007,1062 oltp_write_only run"
- Workload failed with error: FATAL: mysql_stmt_execute() returned error 1105 (tikv aborts txn: Error(Txn(Error(Mvcc(Error(Engine(Error(Other(\"[components/tikv_kv/src/[raftstore_impls.rs:35](http://raftstore_impls.rs:35/)]: Storage Engine IO error: While pread offset 5646882 len 16318: /var/lib/tikv/data/db/031819.sst: Cannot allocate memory\"))))))))) for query 'COMMIT'\nFATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:409: SQL error, errno = 1105, state = 'HY000': tikv aborts txn: Error(Txn(Error(Mvcc(Error(Engine(Error(Other(\"[components/tikv_kv/src/[raftstore_impls.rs:35](http://raftstore_impls.rs:35/)]: Storage Engine IO error: While pread offset 5646882 len 16318: /var/lib/tikv/data/db/031819.sst: Cannot allocate memory\"))))))))\nDone."] ["exit code"=1]

### What version of TiKV are you using?

5.1.4

**Comment by Tammyxia** [comment]
FATAL: mysql_stmt_execute() returned error 1105 (tikv aborts txn: Error(Txn(Error(Mvcc(Error(Engine(Error(Other(\"[components/tikv_kv/src/raftstore_impls.rs:35]: Storage Engine IO error: While pread offset 4391590 len 16346: /var/lib/tikv/data/db/012713.sst: Cannot allocate memory\"))))))))) for query 'UPDATE sbtest7 SET k=k+1 WHERE id=?'\nFATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:458: SQL error, errno = 1105, state = 'HY000': tikv aborts txn: Error(Txn(Error(Mvcc(Error(Engine(Error(Other(\"[components/tikv_kv/src/raftstore_impls.rs:35]: Storage Engine IO error: While pread offset 4391590 len 16346: /var/lib/tikv/data/db/012713.sst: Cannot allocate memory\"))))))))\nDone."]

**Comment by Tammyxia** [comment]
The above errors were caused by tikv oom:
![image](https://user-images.githubusercontent.com/78345569/153822109-a4d73d4d-33ec-4ca9-9d83-c9e2f6d0e907.png)

**Comment by hicqu** [comment]
<img width="1829" alt="图片" src="https://user-images.githubusercontent.com/8407317/153835165-8be1a0da-297a-4c37-84c5-fdab04c504a1.png">

Seems lots of tasks are pending in cdc endpoint.

**Comment by hicqu** [comment]
Duplicated with https://github.com/pingcap/tiflow/issues/4589. Close it.
