### ISSUE TITLE
Collect key ranges for the read request in ResourceMeteringTag

### ISSUE THREAD

**Issue by JmPotato** [tikv/tikv#11988]
### Is your feature request related to a problem? Please describe:

For now, we have this info to collect when using a `ResourceMeteringTag`:

https://github.com/tikv/tikv/blob/560227ecfa3a217d44cbcc0eb90ebe353355c05a/components/resource_metering/src/lib.rs#L264-L274

To make the resource metering info finer, we can also collect key ranges for the read request in `ResourceMeteringTag`. For example, a `scan` request has these arguments to call:

https://github.com/tikv/tikv/blob/560227ecfa3a217d44cbcc0eb90ebe353355c05a/src/storage/mod.rs#L942-L952

We can see both `start_key` and `end_key` are easy to access here. We can easily pass them into the creation of the `resource_tag` later.

### Describe the feature you'd like:

Collect key ranges for the read request in `ResourceMeteringTag`. With this, we can make the CPU and other read stats even finer.

**Comment by JmPotato** [comment]
Load Base Split could benefit from this a lot if possible. PTAL @zhongzc @nolouch @lhy1024

**Comment by zhongzc** [comment]
LGTM
