### ISSUE TITLE
TiKV copr resp size may exceed 4GB

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#11994]
### What version of TiKV are you using?

master

### Steps to reproduce

Create a table with lots of fields of `VARCHAR`, and insert 50w records with these fields filling with null.
Then execute
```
mysql> update table set multi_tenancy_id = '1';
```

### What did you expect?
```
Query OK
```
### What did happened?
```
ERROR 1105 (HY000): other error: [src/coprocessor/dag/[mod.rs:143](http://mod.rs:143/)]: IoError(Custom { kind: Other, error: "given slice is too small to serialize the message" })
```

**Comment by Connor1996** [comment]
This error is due to the copr resp size exceeds 4GB. It's confirmed as the chunk codec(arrow codec) would reserve space for the fixed-length field even if the value is null. So when there are lots of fixed-length fields filling with null, the size of copr resp would be amplified by multiple times and exceed 4GB.

**Comment by zhangjinpeng1987** [comment]
> set `tidb_enable_chunk_rpc` to off can workaround this problem.

Is there any side effect for this change?

**Comment by Connor1996** [comment]
The situation is rare and likely impossible in a real workload. So @zanmato1984 decided not to fix it at that time.

**Comment by AndreMouche** [comment]
fixed by https://github.com/tikv/tikv/pull/10993
