### ISSUE TITLE
Some grafana expression are wrong or suboptimal

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#12007]
### What version of TiKV are you using?
v5.4.0

### What operating system and CPU are you using?
Doesn't matter

### Steps to reproduce
tiup playground

### What did you expect?
Good well defined graph.

### What did happened?
1. Pending task is wrong.
    Pending task metrics is a guage instead of a counter, its value should be used directly.
2. Hitmap in coprocessor is hard to read.
    It should use similar settings like Raft IO, which makes zero values transparent and choose more colorful scheme.

**Comment by BusyJay** [comment]
And storage panel should also show 99%, 95% and avg graph besides hitmap for both async snapshot and async write .

**Comment by BusyJay** [comment]
"Raft log speed" should be renamed to "Raft propose speed" and the unit should be changed to byte/s.

**Comment by BusyJay** [comment]
I suggest to include this into v6.0.0.

**Comment by zhangjinpeng1987** [comment]
@jiayang-zheng PTAL

**Comment by kevin-xianliu** [comment]
I will take a look at it.
