### ISSUE TITLE
The creation of ReadStats should take into account the user configuration of sample_num

### ISSUE THREAD

**Issue by JmPotato** [tikv/tikv#12014]
### What version of TiKV are you using?

https://github.com/tikv/tikv/commit/a7d1595f5486616be34e0cf2bbf372edb5f0e85a

### What did you expect?

The `sample_num` of `ReadStats` should be updated along with the user config. However, in the current implementation, TiKV uses `ReadStats::default()` to create each `ReadStats` without considering the actual `sample_num` config.

https://github.com/tikv/tikv/blob/a7d1595f5486616be34e0cf2bbf372edb5f0e85a/components/raftstore/src/store/worker/split_controller.rs#L397-L404

https://github.com/tikv/tikv/blob/a7d1595f5486616be34e0cf2bbf372edb5f0e85a/src/storage/metrics.rs#L26-L34

### What did happened?

If the user adjusts the default config and sets a large `sample_num`, the Load Base Split may not work due to the insufficient number of the sampled key range.

**Comment by JayiceZ** [comment]
can I try to fix it?

**Comment by JmPotato** [comment]
> can I try to fix it?

@JayiceZ Of course! However, I don't have any idea how to fix this currently. The problem here is that we don't have a good place to pass the config to `local_read_stats`. Maybe you can take a explore here 🤔.

**Comment by JayiceZ** [comment]
> > can I try to fix it?
> 
> @JayiceZ Of course! However, I don't have any idea how to fix this currently. The problem here is that we don't have a good place to pass the config to `local_read_stats`. Maybe you can take a explore here 🤔.

In my opinion.
SplitConfig Change happened here.https://github.com/tikv/tikv/blob/1047b51285456e702b66253da26c7f14d582ff0c/components/raftstore/src/store/worker/split_config.rs#L83

and maybe we can add a static var to replace DEFAULT_SAMPLE_NUM,like:
`
lazy_static! {
    static ref SAMPLE_NUM ......
}
`

and it will be updated when ConfigChange in dispatch() contains "sample_num"



how's that?🤔

**Comment by JmPotato** [comment]
> > > can I try to fix it?
> > 
> > 
> > @JayiceZ Of course! However, I don't have any idea how to fix this currently. The problem here is that we don't have a good place to pass the config to `local_read_stats`. Maybe you can take a explore here 🤔.
> 
> In my opinion. SplitConfig Change happened here.
> 
> https://github.com/tikv/tikv/blob/1047b51285456e702b66253da26c7f14d582ff0c/components/raftstore/src/store/worker/split_config.rs#L83
> 
> and maybe we can add a static var to replace DEFAULT_SAMPLE_NUM,like: `lazy_static! { static ref SAMPLE_NUM ...... }`
> 
> and it will be updated when ConfigChange in dispatch() contains "sample_num"
> 
> how's that?🤔

LGTM. One suggestion is that in order to keep everything tidy, you may want to make `SplitConfigManager` static rather than one of its fields and change all of its usages to the static variable.
