### ISSUE TITLE
follower Raft logs cannot be force compacted and purged by Raft Engine

### ISSUE THREAD

**Issue by glorv** [tikv/tikv#12011]
### What version of TiKV are you using?

`cb5cb230e77665e017853ce9292162c5fd250cbb`

### Steps to reproduce

1. use tiup to deploy a cluster (1tidb, 1pd, 3tikv)
2. use tidb-lightning to load 14k tpcc data into this cluster
3. run sysbench prepare for 10 * 1billion data
4. patch tikv to a newer nightly version

### What did you expect?
The rolling restart should be successful

### What did happened?
Tiup up report start tikv-server time. In the tikv-log in see it cost nearly 500s to recover raft-engine.
One of the raft-engine contains more the 4000 files and the total file size is >400Gb, the other two raft-engine file sizes are <10Gb.

**Comment by tabokie** [comment]
Workaround: Use `ctl try-purge --path /path/to/raft-engine` to get a list of region laggers. Then transfer leaders of these regions to the problematic store. Or unsafe remove them from the store.

**Comment by tabokie** [comment]
Should be fixed by https://github.com/tikv/raft-engine/pull/193.
