### ISSUE TITLE
Store read query is not converging after 30m when set strict-picking-store to false

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#12032]
### What version of TiKV are you using?

/ # /tikv-server -V
TiKV
Release Version:   5.4.0-alpha
Edition:           Community
Git Commit Hash:   a7d1595f5486616be34e0cf2bbf372edb5f0e85a
Git Commit Branch: heads/refs/tags/v5.5.0-nightly
UTC Build Time:    2022-02-24 06:10:41
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce

sysbench /go/location.lua --is_long_connection=true --queries=/go/poisource.sql --threads=500 --mysql-db=location  --mysql-host=tc-tidb.pd-scheduler-hongm-pb5jv --mysql-port=4000 --mysql-user=root --db-driver=mysql --time=0 --report-interval=10  run

### What did you expect?
Should converge with 10min as before version.

### What did happened?
![image](https://user-images.githubusercontent.com/9443637/155910685-d0c1e12f-75a1-4d18-9273-79a5b055afe8.png)

**Comment by JmPotato** [comment]
After a series of tests, we found that the test failed because the QPS did not reach the QPS threshold of the Load Base Split check due to test environmental problems, so the region could not be further split for scheduling. This issue could be closed now.

**Comment by mayjiang0203** [comment]
The reason why qps drop from 5.4 is cause by https://github.com/pingcap/tidb/issues/33422
After change the data source, now the hot region scheduler works fine. 
![image](https://user-images.githubusercontent.com/9443637/160991850-9072e2f1-ac03-4a7f-ae3d-15fa4317828f.png)
