### ISSUE TITLE
UB in TsSet conversions

### ISSUE THREAD

**Issue by dtolnay** [tikv/tikv#12070]
https://github.com/tikv/tikv/blob/8b86c063c21f111a2fb0d4fcc4a328c3df7bd6f3/components/txn_types/src/timestamp.rs#L149
https://github.com/tikv/tikv/blob/8b86c063c21f111a2fb0d4fcc4a328c3df7bd6f3/components/txn_types/src/timestamp.rs#L156

This unsafe cast is UB because Vec\<u64\> and Vec\<TimeStamp\> don't have the same layout in general. For example a Rust implementation using profile-guided optimization might put the vec's fields in a different order for the two types, due to different access patterns across all the places those 2 different instantiations are used (e.g. one might store the len first while the other might store the capacity first, because len() is called more often on one than the other).

**Comment by sticnarf** [comment]
Thanks for pointing this out.

I find `.into_iter().map().collect()` can be optimized out if they really have the same layout:

https://godbolt.org/z/an9jxa7v8

I believe we can and should use a safe way to implement it here. But as you say the behavior is actually not guaranteed. Do you have any suggestion for confirming the optimization so we won't get performance regression unexpectedly?

**Comment by BusyJay** [comment]
How about
```
let (ptr, len, cap) = ts.into_raw_parts();
let ts = { Vec::from_raw_parts(ptr as _, len, cap) };
```

**Comment by Connor1996** [comment]
Thanks! We notice that the Clippy complains about it after upgrading to recent rust nightly. So are the layout of the two types promised to be the same for the previous rust version? @dtolnay

**Comment by sticnarf** [comment]
> Thanks! We notice that the Clippy complains about it after upgrading to recent rust nightly. So are the layout of the two types promised to be the same for the previous rust version? @dtolnay

I believe not. It's never guaranteed to be the same. It's just clippy that adds the lints recently.
