### ISSUE TITLE
running BR in incompatible version of cluster

### ISSUE THREAD

**Issue by buchuitoudegou** [tikv/tikv#12112]
### What version of TiKV are you using?

latest master branch

### What operating system and CPU are you using?

macOS

### Steps to reproduce

restore table using BR: 
```shell
bin/br restore table --db test_backup \
        --table test \
        -s local:///tmp/backup_test/ \
        --pd ${myipv4}:2379 \
        --log-file restore_test.log
```
### What did you expect?
restore successfully

### What did happened?
get mismatched cluster version.
```
[2022/03/07 16:53:00.369 +08:00] [INFO] [collector.go:67] ["Table restore --db test_backup --table test failed summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0]
Error: running BR in incompatible version of cluster, if you believe it's OK, use --check-requirements=false to skip.: TiKV node 192.168.196.92:20160 version 5.4.0-alpha and BR v6.0.0-alpha-14-g0aa5f1a66-dirty major version mismatch, please use the same version of BR: [BR:Common:ErrVersionMismatch]version mismatch
```
The hinted workaround does work, but what actually attributes to this?

**Comment by glorv** [comment]
I think this is an issue related to BR rather than TiKV, so it should be transfered to pingcap/tidb repo. @kennytm @3pointer
