### ISSUE TITLE
Entry count of raft-engine seems not right

### ISSUE THREAD

**Issue by cosven** [tikv/tikv#12158]
## Bug Report

The entry count keep increasing. After the tikv is restarted, it goes down.

### What version of TiKV are you using?

e1fae9469b33ff1ec4fd66aa143a21a5f30f5aa3

### Steps to reproduce

1. Run go-tpc workload

### What did you expect?

The entry count should not increase at all time.

### What did happened?
![middle_img_v2_594c76d4-a0e7-4179-a1f5-3c723c74e03g](https://user-images.githubusercontent.com/4962134/158298883-bca5c4e2-4537-434f-8fa7-4ccf797b2ac4.png)

**Comment by tabokie** [comment]
Reopen this if another case pops up.
