### ISSUE TITLE
proposal: support getTS() from PD server

### ISSUE THREAD

**Issue by disksing** [tikv/tikv#1215]
There are at least three features may require it.
1. Switch to 1PC if a transaction's all mutations are in a single region. By creating _CommitTS_ with the latch occupied on server side, we can guarantee the isolation of transaction.
2. Push _DeleteRange_ down to tikv. Similar to 1, if we use a 2PC protocol for _DeleteRange_, we always have to trace all the related keys in client, so it will be unable to push down.
3. Backoff & retry on tikv when encounter locks. With the knowledge of global timing, we can control the process more precisely.

**Comment by huachaohuang** [comment]
Now TiKV may not connect to the PD leader directly, if we need to get TS efficiently, we should let TiKV connect to the PD leader as far as it can.

**Comment by siddontang** [comment]
Now we only use only one connection, we may use another connection for TSO specially for performance.

**Comment by ngaut** [comment]
We should discuss it after we introduced gRPC to TiKV.
