### ISSUE TITLE
v4.0.10 upgrade to v6.0.0 fail with : region split size 4194304 must >= region bucket size 100663296

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#12236]
### What version of TiKV are you using?
v6.0.0

### Steps to reproduce
install v4.0.10 with :
  tikv:
    coprocessor.region-max-size: 16MB
    coprocessor.region-split-size: 4MB
    raftstore.region-split-check-diff: 1MB
    storage.block-cache.capacity: 1GB
upgrade to v6.0.0
upgrade fail with : 
Error: init config failed: tikv1-peer:30160: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@tikv1-peer:22' {ssh_stderr: invalid configuration: [components/raftstore/src/coprocessor/config.rs:111]: region split size 4194304 must >= region bucket size 100663296
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /tiup/deploy/tikv-30160/bin/tikv-server --config-check --config=/tiup/deploy/tikv-30160/conf/tikv.toml --pd "" --data-dir "/tiup/data/tikv-30160"}, cause: Process exited with status 1: check config failed

### What did you expect?
upgrade success
### What did happened?
upgrade fail

**Comment by youjiali1995** [comment]
Fixed by https://github.com/tikv/tikv/pull/12237
