### ISSUE TITLE
v3.0.11 upgrade to v6.0.0 fail with "critical config check failed: raft engine dir have been changed, former is ''

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#12238]
### What version of TiKV are you using?
v6.0.0                                               2022-03-22T19:50:34+08:00 

### Steps to reproduce

install v3.0.11 with default config 
upgrade to v6.0.0
### What did you expect?
upgrade successfully

### What did happened?
upgrade fail with:
Error: init config failed: tikv1-peer:30160: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@tikv1-peer:22' {ssh_stderr: critical config check failed: raft engine dir have been changed, former is '', current is '/tiup/data/tikv-30160/raft-engine', please check if it is expected.
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /tiup/deploy/tikv-30160/bin/tikv-server --config-check --config=/tiup/deploy/tikv-30160/conf/tikv.toml --pd "" --data-dir "/tiup/data/tikv-30160"}, cause: Process exited with status 1: check config failed

**Comment by seiya-annie** [comment]
please help check which config item should be set for this error, and please add compatibility description in doc

**Comment by tabokie** [comment]
I cannot reproduce this issue. My steps:
```
tiup cluster deploy test v3.0.11 /home/tabokie/control/topology_singlekv.yaml --password --user tabokie
tiup cluster start test
tiup cluster upgrade test nightly
```
TiKV config in `topology_singlekv.yaml` is left empty.

**Comment by you06** [comment]
It's fine to upgrade to nightly, but failed when upgrading to v6.0.0.

**Comment by tabokie** [comment]
@you06 What's the version code for v6.0.0 alpha build? My tiup can't find "v6.0.0" with various suffix.

**Comment by you06** [comment]
> It's fine to upgrade to nightly, but failed when upgrading to v6.0.0.

@tabokie Sorry that's not accurate, the tiup's check(actually it uses `--config-check` of TiKV) failed inside k8s but work in normal tiup cluster, I'll do further investigation.

**Comment by tabokie** [comment]
Well, if it helps, my theory in #12250 is that the v3.0.11 config didn't pass the validation logic in v6.0.0. It can be verified if you copied the `data/last_tikv.toml` from a v3.0.11 cluster to `conf/tikv.toml`, then do the upgrade and check if there's any error.

**Comment by you06** [comment]
@tabokie I added some log and it shows that the config check actually failed in the following part.

In v3.0.11, `storage.scheduler-worker-pool-size` is set to 8.

https://github.com/tikv/tikv/blob/1b35044a1910043bbf60905ceb6ce34e34879a0c/src/storage/config.rs#L112-L121

After this failure, it returns with an error and skipped the init for `self.raft_engine.config.dir` in line #2692, so we get the error in the description of this issue.

https://github.com/tikv/tikv/blob/1b35044a1910043bbf60905ceb6ce34e34879a0c/src/config.rs#L2677-L2692

And you've mentioned in #12250 that we skipped the error check for `validate` of last config.

https://github.com/tikv/tikv/blob/5ee7d037d4e2e63d710410daac81baca7e9efe69/src/config.rs#L3185

-----

The reason we cannot reproduce it in our environments is that `storage.scheduler-worker-pool-size` is allowed to set up to CPU nums, so `storage.scheduler-worker-pool-size` with 8 will pass the check. In k8s test environment, both `cpu set cores` and `cpu quota` are set to 4, which fail the validation.

**Comment by you06** [comment]
The validation for configuration of storage is introduced in #12068, I think this looks OK. But when TikV v3.0.11 bootstraps, it choose `storage.scheduler-worker-pool-size` without consideration of cgroup limitations. @glorv PTAL

**Comment by tabokie** [comment]
@you06 Nice finding! I think it's because v3.0.11 doesn't have cgroup integration yet. Anyway, https://github.com/tikv/tikv/pull/12250 will fix this issue.

**Comment by glorv** [comment]
> The validation for configuration of storage is introduced in #12068, I think this looks OK. But when TikV v3.0.11 bootstraps, it choose `storage.scheduler-worker-pool-size` without consideration of cgroup limitations. @glorv PTAL

This is truely a breaking change. Since it make little sense to config  `storage.scheduler-worker-pool-size` to bigger than cpu quota limit, I think this won't be a problem in production environment.
