### ISSUE TITLE
slow score calculation is not accurate

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#12254]
### What version of TiKV are you using?
5.4.0 or older version

### What operating system and CPU are you using?
Linux/Intel

### Steps to reproduce
Code review
Two issues:
1)  in https://github.com/tikv/tikv/blob/v5.4.0/components/raftstore/src/store/worker/pd.rs#L606
"if OrderedFloat(desc) > self.value" should be "if OrderedFloat(desc) > self.value - 1". Otherwise the value could be < 1 (not [1, 100])

2) in https://github.com/tikv/tikv/blob/v5.4.0/components/raftstore/src/store/fsm/store.rs#L881
inspector.record_store_write(dur) and inspector.record_store_process(dur) (in L879) are double counting the dur. 

### What did you expect?
SlowScore calculation is accurate
### What did happened?
SlowScore calculation is inaccurate in corner cases.

**Comment by JayiceZ** [comment]
@5kbpers Hi. Have you started working on the issue? if not, can I try it?😀

**Comment by 5kbpers** [comment]
> @5kbpers Hi. Have you started working on the issue? if haven't, can I try it?😀

@JayiceZ  I've not started yet. Your contribution is welcome!

**Comment by JayiceZ** [comment]
@5kbpers  I‘ve sent two PRs to fix those two issues, PTAL if you have time~

**Comment by 5kbpers** [comment]
Fixed by #12275 and #12276
