### ISSUE TITLE
dr-autosync: After switch to backup cluster in sync mode, scan table hit 9005: Region is unavailable 

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#12307]
### What version of TiKV are you using?

sh-4.2# ./tikv-server -V
TiKV
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   f3a230996f4208948cf5e0a3d4e1583e388cdb6f
Git Commit Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time:    2022-03-26 14:55:51
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce

TCMS Test Plan:  722395
Endless Case: oltp_tiup_dr_autosync_001

STEP: Prepare TiDB Cluster
STEP: Step 1: Init cluster
STEP: Step 1: Run workload
STEP: Step 2: Down dr cluster to block write
STEP: Step 3: Read data from primary cluster
STEP: Step 4: Down primary cluster and startup dr cluster
STEP: Step 5: Restore dr cluster
STEP: Step 6: Remove fail stores
STEP: Step 7: Verify in dr cluster    << scan all tables here hit 9005 error. 
STEP: End One Test,Now delete chaos 

### What did you expect?
Should no error report.

### What did happened?
```
select count(*) from sbtest8 hit following error.
TiDB-OLTP
/home/jhm/project/endless_submit/pkg/util/dsl.go:29
  run workload
  /home/jhm/project/endless_submit/testcase/oltp/tiuptest/oltp_tiup_test.go:108
    ACID should be consistent when down primary dc and restore backup cluster #oltp_tiup_dr_autosync_001# [It]
    /home/jhm/project/endless_submit/pkg/util/dsl.go:61
    Expected success, but got an error:
        <*mysql.MySQLError | 0xc0012ffb78>: {
            Number: 9005,
            Message: "Region is unavailable",
        }
        Error 9005: Region is unavailable
    /home/jhm/project/endless_submit/testcase/oltp/tiuptest/tiuppkg/tiuputil.go:113
```

**Comment by disksing** [comment]
If the primary DC fails while a region is being scheduled and the operator contains the operation of adding peer to the primary DC node. It is possible that the new peer will be created after the recovery from dr center. That is, this region may not be able to elect a leader afterwards.
To solve this problem, we need to use online recovery (which is not GA yet). Another temporary solution is to stop the cluster and run tikv-ctl unsafe-recover again.

**Comment by cfzjywxk** [comment]
@disksing
Is this a blocking issue for release versions? v5.4.1 is being triaged.

**Comment by disksing** [comment]
Not blocking. The plan is not to fix the issue in tikv-ctl but wait for the `online-recover` feature to GA.

**Comment by Connor1996** [comment]
> Not blocking. The plan is not to fix the issue in tikv-ctl but wait for the `online-recover` feature to GA.

Online recovery is GA now

**Comment by nolouch** [comment]
So online recovery is GA,  can we close this issue?
