### ISSUE TITLE
tikv-ctl: error string match in `bad-ssts` tool

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#12329]
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

Don't care

### Steps to reproduce

just modify a normal sst file to bad file and execute `bad-ssts` to verify and cannot get info as expected because the sst file name is not recognized.

**Comment by hunterlxt** [comment]
https://github.com/tikv/tikv/pull/12049 is merged

**Comment by MimeLyc** [comment]
refresh pr relation.
