### ISSUE TITLE
too many compactions and even write stalls occur by cleaning range by ingesting SSTs

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#12367]
## Bug Report

Currently TiKV cleans up destroyed ranges for write cf and default cf by [ingesting SSTs](https://github.com/tikv/tikv/blob/45fcb0812a0437cabce2436c5223c96c9de83d5e/components/raftstore/src/store/worker/region.rs#L593).
Those ingested SSTs may introduce too many compactions on L0, make compactions on L1~Ln slower. Then the size of LSM tree grows up continuously, the space of disk may run out in some extreme cases.

**Comment by 5kbpers** [comment]
> Can we use `DeleteFileInRange` instead?

Used already, turns out still some problems with ingesting too many SST here.
https://github.com/tikv/tikv/blob/2552144c31b481f8cac04aaef960a1dd3f390496/components/engine_rocks/src/misc.rs#L53

**Comment by 5kbpers** [comment]
The purpose of the original optimization (https://github.com/tikv/tikv/pull/7794) is to reduce write amplification, but seems it's not effective when the SST is ingested to L0 and even could cause some bad effects. So I suggest putting delete through a WriteBatch if the SST can only be ingested to L0.

**Comment by 5kbpers** [comment]
Seems is duplicated with https://github.com/tikv/tikv/issues/10680 and was fixed.

**Comment by cosven** [comment]
I'm trying to reproduce the problem with the help from @5kbpers . 

Meanwhile, I found that a fix https://github.com/tikv/tikv/pull/10934 is submitted before and it is not merged.
