### ISSUE TITLE
Single table with 7000 partitioned tables，Approximate Region size exception

### ISSUE THREAD

**Issue by buggithubs** [tikv/tikv#12365]
### What version of TiKV are you using?

v6.0.0-alpha
b60271983288caf7d978f111cd1878b508861327

### What did happened?

7000 partitioned tables were created in a single table（https://github.com/pingcap/tidb/issues/34011）
region size P.99 has a statistical error

<img width="2123" alt="image" src="https://user-images.githubusercontent.com/11624213/163532069-aef071a5-9933-49d9-a922-d99b914970b8.png">
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/11624213/163532095-3bac4f9c-0dc9-48b1-8684-9ccfc1076783.png">
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/11624213/163532176-e200b0fd-27ec-4e87-ba4e-35e268235f1e.png">
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/11624213/163532510-32d43afa-33de-4f67-a410-d00057e42c44.png">
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/11624213/163532588-d9c8caca-59b4-452f-9d53-7591e01d2c96.png">

**Comment by Lily2025** [comment]
cc @tonyxuqqi

**Comment by tonyxuqqi** [comment]
It's likely due to issue #12510

**Comment by zhangjinpeng1987** [comment]
@tonyxuqqi Have we confirmed this issue is caused by https://github.com/tikv/tikv/issues/12510, and should we close this issue since https://github.com/tikv/tikv/issues/12510 is closed.
