### ISSUE TITLE
Switch to aws rust sdk

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#12371]
## Development Task

rusoto is not maintained and AWS has released its own SDK. https://github.com/awslabs/aws-sdk-rust.

Although it claims it's still not production ready, but according to https://github.com/rusoto/rusoto/issues/1651, community has started the transition. We may also give it a try.

**Comment by roguepnz** [comment]
@BusyJay Hello! I'm trying to fix this. Is it ok to completely replace rusoto with aws-sdk or it's better to keep both implementations with some kind of feature flagging?

**Comment by BusyJay** [comment]
@roguepnz Thanks, replace it with aws-sdk completely is OK as long as nothing is broken.

**Comment by BusyJay** [comment]
Hi, @roguepnz how is it going? Just want to check out if everything is OK and anything I can help.

**Comment by roguepnz** [comment]
@BusyJay Hi, still in progress (had to pause it for a while, but now i'm in progress). 
I have 2 questions:
1. aws-sdk doesn't support virtual hosts for s3. Is it ok? Storage config has option "force_path_style" and it will have no-op effect
2. How it's better to test it? I'm rewriting unit tests, but it's not enough. Are there any integration tests for aws or it will be ok to test it manually with localstack/minio and post results in PR?

**Comment by BusyJay** [comment]
> doesn't support virtual hosts for s3

That actually will be a problem as we also have support for s3-compatable object storage. But giving that aws itself is deprecating path style, I guess it should not be a long term deal breaker. I think you can still send your change but guard it with features to choose whether use aws-rust or rusoto.

> Are there any integration tests for aws or it will be ok to test it manually with localstack/minio and post results in PR?

Yes, manually test is OK. Currently we don't have integration tests for this part yet. We tested it with minio locally.

**Comment by kennytm** [comment]
[AWS SDK has now GA](https://aws.amazon.com/blogs/developer/announcing-general-availability-of-the-aws-sdk-for-rust/), there should be no reason keeping rusoto now.

**Comment by akoshchiy** [comment]
Yeah, I can try to revive PR if it's needed.
