### ISSUE TITLE
File locks for working around port conflict are sometimes inaccessible 

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#12399]
### What version of TiKV are you using?
master

### What operating system and CPU are you using?
unix

### Steps to reproduce
1. run tikv-server in root mode
2. run tikv-server in user mode

### What did you expect?
nornal startup

### What did happened?
`[FATAL] [[server.rs:894](http://server.rs:894/)] ["failed to create lock at /tmp/1001_TIKV_LOCK_FILES/0.0.0.0_20160: Permission denied (os error 13)"]`

**Comment by BusyJay** [comment]
I don't get it. If this file is created by other user, then ownership of all the files also belongs to root. How can it start normally by just making the lock file accessible to all other users? Is it even secure to do so?

**Comment by hunterlxt** [comment]
lock file need to be accessed so they can try lock that file.
