### ISSUE TITLE
The tikv component triggers the alarm type = "unreachable" when reloading

### ISSUE THREAD

**Issue by jacktd9** [tikv/tikv#12408]
### What version of TiKV are you using?

v4.0.12

### What operating system and CPU are you using?

x86
### Steps to reproduce

case1:
tiup cluster reload dba-test -R tikv  --transfer-timeout 1
![LQucGq04v9](https://user-images.githubusercontent.com/63033738/164404734-cdb12add-52a5-47ec-86da-cc64d71ec36f.jpg)
![image](https://user-images.githubusercontent.com/63033738/164404869-89a1ce46-92e4-4352-96df-ad84caf171f3.png)

case2:
tiup cluster reload dba-test -R tikv  --transfer-timeout 100000
![uU87vNq7YR](https://user-images.githubusercontent.com/63033738/164405163-866e2807-351a-405c-a199-0fe97acf0a5c.jpg)
![image](https://user-images.githubusercontent.com/63033738/164405500-3851e732-7c82-4fec-acc2-081caf54fbf2.png)

### What did you expect?
Do not trigger alarm type = "unreachable"

### What did happened?
a lot of "sum(rate(tikv_server_report_failure_msg_total{type=#unreachable#}[10m])) BY (store_id) > 10”

**Comment by BusyJay** [comment]
I think this is expected, restarting TiKV is supposed to abort connection.
