### ISSUE TITLE
TiKV Short-term memory usage continues to rise

### ISSUE THREAD

**Issue by buggithubs** [tikv/tikv#12416]
### What version of TiKV are you using?

v6.0.0
2b4f7d57af9ca3e21bc07b91a9cfc466ed87734f

### What did happened?

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/11624213/164583972-8d5e8adc-9255-4663-8e39-01949434c287.png">
<img width="1848" alt="image" src="https://user-images.githubusercontent.com/11624213/164584027-84e7eb0e-5bf6-4ac3-8590-9d06adbf206d.png">

Suspect the same problem as this one：https://github.com/tikv/tikv/issues/12229

**Comment by JmPotato** [comment]
It should be the same problem as https://github.com/tikv/tikv/issues/12229. The PR at that time did not completely fix this bug
