### ISSUE TITLE
Support batch split

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#1243]
Current split only split one region at a time. It may be very slow when sequential write is too fast. Slow split can lead to a huge region. If a snapshot is triggered, it will occupy a lot of IO and make everything slow.

**Comment by BusyJay** [comment]
This needs to update pd too. /cc @huachaohuang

**Comment by huachaohuang** [comment]
Seems `optional` is compatible with `repeated` in protobuf, we can just replace `optional` with `repeated` in the request message.

**Comment by BusyJay** [comment]
Split check is checked every 10s, assume a region write 10MB/s, then after 10 seconds, the region becomes 100MB. If scan is slow, the interval can be larger. So I think we still need this feature to support high load.

**Comment by Hoverbear** [comment]
Seems this feature is supported now!
