### ISSUE TITLE
TiKV automatic restart, non-oom

### ISSUE THREAD

**Issue by buggithubs** [tikv/tikv#12453]
### What version of TiKV are you using?

TiKV 
Release Version:   6.0.0
Edition:           Community
Git Commit Hash:   79c94ccb0b35f238665a199d9ab4c472a4de257c
Git Commit Branch: HEAD
UTC Build Time:    2022-04-30 05:33:04
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What did happened?

`20091990016 May  3 21:55 core-grpc_global_tim-85856-1651586111`

![origin_img_v2_c6f19cc1-0bf5-4478-8b68-268df22a5a2g](https://user-images.githubusercontent.com/11624213/166867869-b33b4888-0cfa-4a77-b0dc-68241aa2f4da.jpg)

**Comment by tabokie** [comment]
What's the error message? It should be "Futex operation failed with error xxx".

**Comment by buggithubs** [comment]
`CentOS Linux release 7.6.1810 (Core)`
 `3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by dbsid** [comment]
observed on ARM64, latest master version

```
[root@tikv-1-0 ~]# uname -a
Linux tikv-1-0 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```
```
[root@tikv-1-0 log]# cat tikv_stderr.log
[waiter.cc : 102] RAW: Futex operation failed with error -9
```

![image](https://user-images.githubusercontent.com/2316425/168950439-09330a4c-5c47-4847-9b42-f0e5a0bb73d8.png)

**Comment by dbsid** [comment]
should we raise the severity?

**Comment by Lily2025** [comment]
The test environment appears several times

**Comment by mornyx** [comment]
> The test environment appears several times

Hi @Lily2025, what is your TiKV branch and commit id?

**Comment by Lily2025** [comment]
> > The test environment appears several times
> 
> Hi @Lily2025, what is your TiKV branch and commit id?

cc @buggithubs

**Comment by BusyJay** [comment]
May be caused by https://github.com/tikv/pprof-rs/pull/128

**Comment by mornyx** [comment]
Should be resolved as https://github.com/tikv/pprof-rs/pull/128 , https://github.com/tikv/tikv/pull/12480 has been merged.

**Comment by zhangjinpeng1987** [comment]
@mornyx can we close this issue now?

**Comment by mornyx** [comment]
> @mornyx can we close this issue now?

Yes, can be closed.
