### ISSUE TITLE
TiKV restarts due to segfault

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12525]
### What version of TiKV are you using?
 ["Welcome to TiDB."] ["Release Version"=v6.1.0-alpha] [Edition=Community] ["Git Commit Hash"=bbfbe137eba05f828a9fb40708a6f6805a3453f0] ["Git Branch"=heads/refs/tags/v6.1.0-alpha] ["UTC Build Time"="2022-05-13 14:58:01"] 

### What operating system and CPU are you using?

Cent OS, 16 CPU
```
processor       : 39
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb00002a
cpu MHz         : 2399.938
cache size      : 25600 KB
physical id     : 1
siblings        : 20
core id         : 12
cpu cores       : 10
apicid          : 57
initial apicid  : 57
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopol
ogy nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dno
wprefetch epb cat_l3 cdp_l3 intel_pt ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total
 cqm_mbm_local dtherm ida arat pln pts spec_ctrl intel_stibp
bogomips        : 4404.48
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

```

### Steps to reproduce
1. Start a cluster and keep running workload
2. Start a log backup task, and monitor log backup status

### What did you expect?
No tikv restart

### What did happened?
there are 2 TiKV restart seen in 2 days for the same reason.

![middle_img_v2_e64b26b6-14f2-49c6-a632-2951d7d2ec4g](https://user-images.githubusercontent.com/7403864/168549466-48e26db9-a7de-4a76-a2ea-0778d5c41439.jpg)

```
[六 5月 14 20:17:14 2022] steady-timer[150605]: segfault at 2000 ip 00007f0423a260b8 sp 00007f03bf1c9410 error 4 in libgcc_s-4.8.5-20150702.so.1[7f0423a17000+15000]
[日 5月 15 00:15:14 2022] perf: interrupt took too long (6201 > 6193), lowering kernel.perf_event_max_sample_rate to 32000
[日 5月 15 10:01:54 2022] TCP: request_sock_TCP: Possible SYN flooding on port 4000. Sending cookies.  Check SNMP counters.
[一 5月 16 11:30:15 2022] steady-timer[160415]: segfault at ffffffffffffff92 ip 00007f6e742690b8 sp 00007f6deffc9410 error 5 in libgcc_s-4.8.5-20150702.so.1[7f6e7425a000+15000]
```

**Comment by fubinzh** [comment]
Another TiKV restart seen:
[Mon May 16 15:45:18 2022] steady-timer[25730]: segfault at ffffffffffffff92 ip 00007f9f6b2910b8 sp 00007f9eec749410 error 5 in libgcc_s-4.8.5-20150702.so.1[7f9f6b282000+15000]

**Comment by jiayang-zheng** [comment]
Both segfault error 4 and error 5 are about read invalid memory on user space. Could you help to confirm that the limitation of memory usage  (tikv1 + tikv2+ ... tikvN)+(tidb1 + tidb2 + ... tidbN) should be  less than the total memory of the machine?

**Comment by jiayang-zheng** [comment]
By the way, have you specified the block cache  size if you deploy multiple tikv instances in one host?

**Comment by jiayang-zheng** [comment]
Could you please turn on the [core dump](https://zhuanlan.zhihu.com/p/41153588) - then we could see more if the segfault  issue occurs again.

**Comment by jiayang-zheng** [comment]
[storage.block-cache]
## To deploy multiple TiKV nodes on a single physical machine, configure this parameter explicitly.
## Otherwise, the OOM problem might occur in TiKV.
##
## If it's not set, 45% of available system memory will be used.
# capacity = "1GB"

Please have a check that `block-cache.capacity` should be set explicitly while deploying multiple TiKV nodes on a single physical machine.

**Comment by fubinzh** [comment]
> ```toml
> [storage.block-cache]
> ## To deploy multiple TiKV nodes on a single physical machine, configure this parameter explicitly.
> ## Otherwise, the OOM problem might occur in TiKV.
> ##
> ## If it's not set, 45% of available system memory will be used.
> # capacity = "1GB"
> ```
> 
> Please have a check that `block-cache.capacity` should be set explicitly while deploying multiple TiKV nodes on a single physical machine.

OK, will update config and check whether we can reproduce it.

**Comment by jiayang-zheng** [comment]
As we look, the segfault thread got a signal and met problem in `perf_signal_handler`.
```
#0  0x00007f6ea9fe60f8 in ?? () from /lib64/libgcc_s.so.1
#1  0x00007f6ea9fe6ff9 in _Unwind_Backtrace () from /lib64/libgcc_s.so.1
#2  0x00005653cde71e17 in perf_signal_handler ()
#3  <signal handler called>
```
This may be related to ` continue profiling` feature, which has a known issue and should be fixed by the [merging pr](https://github.com/tikv/tikv/pull/12480).

**Comment by mornyx** [comment]
Should be resolved as https://github.com/tikv/tikv/pull/12480 has been merged.
