### ISSUE TITLE
HTTP status server does not automatically reload TLS certificate

### ISSUE THREAD

**Issue by LINKIWI** [tikv/tikv#12546]
## Bug Report

TLS server certificates for the HTTP status server are not automatically reloaded. The symptom is that, beyond the certificate validity period, Prometheus scrape requests will start failing with invalid certificate errors. Note that the certificates used by the gRPC server *are* properly reloaded; this bug only affects the status server.

It appears that the security configuration is only loaded once during server start: https://github.com/tikv/tikv/blob/b6220123ef333a9e7d7033a060d0c6adea6ad1b2/src/server/status_server/mod.rs#L505

There are no routines (either in `status_server/mod.rs` or in dependent libraries) to reload the server certificate for new connections.

### What version of TiKV are you using?

5.4.0

### What operating system and CPU are you using?

Linux x86_64, AWS EC2 i3.4xlarge

### Steps to reproduce

1. Create a certificate with a short validity period.
2. Start TiKV with TLS using this certificate.
3. Start Prometheus with a static HTTPS scrape target pointed to the TiKV metrics endpoint.
4. Wait until the certificate expires.
5. Replace the certificate file on disk with a newly issued, valid certificate, for both Prometheus and TiKV.
6. Notice that Prometheus scrapes now report errors for an invalid certificate due to an expired certificate.

### What did you expect?

I expect TiKV to have used the new certificate on disk for new connections, thus allowing Prometheus to continue to scrape the target without invalid certificate errors.

### What did happened?

TiKV's HTTP status server did not pick up the new certificate on disk, so it continued to terminate new TLS connections using the old certificate.

**Comment by sticnarf** [comment]
I agree it's important to have the ability to hot-reload TLS certificate without restarting TiKV.

I will try to improve this case recently.
