### ISSUE TITLE
In try_batch, we should use the latest apply's bucket_meta.

### ISSUE THREAD

**Issue by SpadeA-Tang** [tikv/tikv#12578]
## Description
Now in struct `Apply`, we have `bucket_meta` field. So we should adjust the try_bacth's code to use the latest `bucket_meta` ().

The code have not handled with `bucket_meta` which means we will use the first one's `bucket_meta`.
![image](https://user-images.githubusercontent.com/71589810/169732567-345561db-2e88-46db-95bf-e16fa4246e49.png)

**Comment by 5kbpers** [comment]
Please clarify the issue in the description.

**Comment by zhangjinpeng1987** [comment]
> Please clarify the issue in the description.

 @SpadeA-Tang

**Comment by SpadeA-Tang** [comment]
> > Please clarify the issue in the description.
> 
> @SpadeA-Tang

Em.. The words in the description now are appended after the comments. I will list the original code.
