### ISSUE TITLE
[BR] gc safepoint not set correctly when there is log backup fatal error 

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12579]
### What version of TiKV are you using?
TiKV
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   f05af56d12b93c74ac5a54a28f77d2f6dc7d6ad8
Git Commit Branch: inflight-detect
UTC Build Time:    2022-05-17 08:48:36
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           release

### What operating system and CPU are you using?
Cent OS, 16U

### Steps to reproduce
1. Start a log backup task
2. Simulate fetal errors like storage can't be access

### What did you expect?
When error happens, GC safepoint should be set appropriately to prevent GC scheduler delete logs that is not backed up.

### What did happened?
Currently we use start_ts to set the GC safepoint, which doesn't take effect actually, and will result in data loss.

**Comment by joccau** [comment]
fix by https://github.com/joccau/tikv/pull/13
