### ISSUE TITLE
[BR] log backup checkpoint_ts doesn't move forward when there is residual tidb lock

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12582]
### What version of TiKV are you using?
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   f05af56d12b93c74ac5a54a28f77d2f6dc7d6ad8
Git Commit Branch: inflight-detect
UTC Build Time:    2022-05-17 08:48:36
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           release

### What operating system and CPU are you using?
Cent OS,  16U

### Steps to reproduce
1. Start a log backup task in upstream
2. There is a transaction in upstream on-going, and for some reason, it was interrupted and leave a lock, e.g 
![middle_img_v2_e81def20-5f1b-411f-b376-15c1a9775a9g](https://user-images.githubusercontent.com/7403864/169278125-cd4cbea6-cf20-4012-b76f-06bb3a7551d0.jpg)

3. Check log backup status

### What did you expect?
The residual  lock should be handled automatically, and log backup task should not be impacted.

### What did happened?
Log backup task checkpoint_ts doesn't move forward in this case.

**Comment by joccau** [comment]
The solution to fix it: https://pingcap.feishu.cn/wiki/wikcnK2mc3wsJgKxfpAiFToY2je

**Comment by fubinzh** [comment]
This issue is seen again during 6.2 release testing, after patch TiKV. Refer to  https://github.com/pingcap/tidb/issues/36298
