### ISSUE TITLE
[BR] huge logs when PD error during log backup

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12580]
### What version of TiKV are you using?
Release Version: 6.1.0-alpha
Edition: Community
Git Commit Hash: https://github.com/tikv/tikv/commit/f05af56d12b93c74ac5a54a28f77d2f6dc7d6ad8
Git Commit Branch: inflight-detect
UTC Build Time: 2022-05-17 08:48:36
Rust Version: rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features: jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile: release

### What operating system and CPU are you using?
Cent OS, 16U

### Steps to reproduce
1. Start a log backup task
2. There is a pd error

### What did you expect?
There should be lots of logs generated

### What did happened?
huge logs generated.

**Comment by 3pointer** [comment]
close it due to https://github.com/tikv/tikv/pull/12584 merged
