### ISSUE TITLE
[Dynamic Region] Some large regions did not split as expected

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#12597]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   a23fd680807d35d60828dc298cf99eca7448faa2
Git Commit Branch: HEAD
UTC Build Time:    2022-05-19 04:37:08
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2022-05-19T18:30:12.351+0800	INFO	k8s/client.go:107	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
 Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: 85918318d7a127a845af25e208b82b153820fc0d
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:  2022-05-18 10:57:30
2022-05-19T18:30:12.527+0800	INFO	k8s/client.go:107	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./tidb-server -V
 Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: 381e870c5ca018d9b5b6e89233d2cbd9a3b41cac
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-05-18 11:04:58
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### What operating system and CPU are you using?
8core、16GB

### Steps to reproduce
update config repeatedly while run tpcc
[2022/05/19 18:42:08.656 +08:00] [INFO] [cmd.go:124] ["Start remote command"] [cmd="go-tpc tpcc run -D tpcc --host tc-tidb.glh-dynamic-regions-jw8pv -P4000 --warehouses 1000 -T 64 --time 36000m --ignore-error '2013,1213,1105,1205,8022,8027,8028,9004,9007,9001'"] [nodename=benchtoolset]

### What did you expect?
big region can split

### What did happened?
current config
    "coprocessor": {
        "split-region-on-table": false,
        "batch-split-limit": 10,
        "region-max-size": "800MiB",
        "region-split-size": "512MiB",
        "region-max-keys": 8000000,
        "region-split-keys": 4800000,
        "consistency-check-method": "mvcc",
        "enable-region-bucket": true,
        "region-bucket-size": "128MiB",
        "region-size-threshold-for-approximate": "384MiB",
        "region-bucket-merge-size-ratio": 0.33
    },

    "max-merge-region-keys": 1000000,
    "max-merge-region-size": 100,

Some large regions did not split as expected
![eGUffDgG8s](https://user-images.githubusercontent.com/84712107/169491584-fc371e8c-39af-4a56-aced-163a10b6b0d2.png)
/pd-ctl region topsize 1
![image](https://user-images.githubusercontent.com/84712107/169491682-ec88a070-96b3-42ee-b197-918993015b6c.png)

**Comment by nolouch** [comment]
duplicated with https://github.com/tikv/tikv/issues/12597.
