### ISSUE TITLE
the invisible mvcc versions are not purged by gc

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#12729]
### What version of TiKV are you using?
v5.4.0

### Steps to reproduce

This is a customer's workload which is only "read"
### What did you expect?
TiKV will clear the invisible mvcc version automatically when there are a lot of rocksdb  tombstone keys instead of waiting for compaction file GC
### What did happened?
![image](https://user-images.githubusercontent.com/85105033/171374360-5aaaeeb5-837c-4ef3-aca9-369116276666.png)
QPS is just 49.9 

![image](https://user-images.githubusercontent.com/85105033/171374582-90268ea6-43f0-4283-bb7d-1dd8ce23a263.png)
IO usage on TiKV is high, avg 571MB/s. CPU usage of TiDB/TiKV is low.

![origin_img_v2_e4e04cc5-8eb1-438a-a995-40930cc560dg](https://user-images.githubusercontent.com/85105033/171377170-0f007b4f-0f38-48ee-bfef-7579ab480062.jpg)
We can see the total_keys is almost equal to key_skipped_count. It means during the scan, coprocessor meets a lot of versions.

![origin_img_v2_0ddcfc1a-9e8c-4fe9-a6b1-c9d7753954eg](https://user-images.githubusercontent.com/85105033/171369591-641dc6d3-b3b7-4135-b8b3-50dc12c3daaf.jpg)
The iterator calls millions of next but only process tens of keys. It means there are too many invisible mvcc versions in the TiKV. From the flamegraph, the iterator is busy spinning on finding next valid key.

![origin_img_v2_9d55ad74-e539-48ad-ac7b-887d3d456ceg](https://user-images.githubusercontent.com/85105033/171371962-62baadbf-84e0-4d60-8db5-a88a78c16a1e.jpg)
From TiKV metrics, that GC rarely happens in the collected time frame. 

![origin_img_v2_b48c1f30-0b98-4237-a56f-ce0d809bf90g](https://user-images.githubusercontent.com/85105033/171372133-267b7346-5fb4-4612-8d66-7538c888e044.jpg)
There is no modifications during the time frame, so no gc is executed

All above shows there are too many delete versions that have not been compacted into tombstones which affected the performance.

**Comment by hicqu** [comment]
@shaoxiqian thanks for your report! In the current implementation, MVCC-deletions can only be handled at the bottlemost level. https://github.com/tikv/tikv/pull/10545 may be helpful for this case, we will continue on it.

**Comment by dbsid** [comment]
I think this is a critical bug for the default gc. It’s devastating that the old mvcc versions are not purged from the user perspective.

**Comment by tonyxuqqi** [comment]
@hicqu would you please move #10545 forward?

**Comment by BusyJay** [comment]
I think an easy fix is to change the function

https://github.com/tikv/tikv/blob/dcb5e2ccd2582fc2f8d3425c27f9891368658154/components/raftstore/src/store/worker/compact.rs#L177-L192

If there are too many versions, compaction should be triggered for write cf, otherwise stale versions won't be deleted.

**Comment by cfzjywxk** [comment]
Maybe it's needed to consider more about the compaction triggering strategy, before that we could abstract a simpler case to help investigate this issue.
/cc @you06

**Comment by cfzjywxk** [comment]
@tonyxuqqi 
@you06 is already working on this and doing related tests.

**Comment by you06** [comment]
@tonyxuqqi I'm currently working on this issue by triggering compaction when there are too many deletes.

**Comment by you06** [comment]
We can trigger compaction when MVCC deletes exceed the given count or ratio. But when the deletes are in memtable, [get versions](https://github.com/tikv/tikv/blob/afbacfc4a864080f958497ce9a387df854f62f0f/components/engine_traits/src/misc.rs#L93-L98) from table properties does not contain those deletes. I think the fix would be:

- Check the count of MVCC deletes in `need_compact` in `CheckAndCompact` task.
- Scan ranges at a long interval, like the old GC style, this handles the situation that `need_compact` can not read the count of deletes in memtable.

@BusyJay PTAL

**Comment by BusyJay** [comment]
> Scan ranges at a long interval

Interesting, it may also solve the issue that too many tombstone key in memtable. Note you can hint the rocksdb to only scan keys in memtable by using ReadTier.

**Comment by you06** [comment]
> Note you can hint the rocksdb to only scan keys in memtable by using ReadTier.

Thanks for the advice, I'll give a try.

**Comment by afeinberg** [comment]
another PR to address this is merged: https://github.com/tikv/tikv/pull/15995

**Comment by tonyxuqqi** [comment]
Since we already have the enhanced check_compact as well as the periodic full compaction. I think the issue can be closed for now.
