### ISSUE TITLE
TiKV panic when execute br restore point

### ISSUE THREAD

**Issue by WangLe1321** [tikv/tikv#12751]
### What version of TiKV are you using?

master
### Steps to reproduce

1. create dir of log file
2. execute br restore point command
### What did happened?
tikv pod restarted.

logs are [here](https://grafana.oauth.dev.shared.aws.tidbcloud.com/explore?orgId=1&left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22freetier%2Feks%2Fdev-us-east-1-f01%5C%22,%20namespace%3D%5C%22free-tier-nightly-ms-43523%5C%22,%20instance%3D%5C%22db30261-tikv-0%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

**Comment by joccau** [comment]
![middle_img_v2_15c6cc4c-9b26-4819-9e26-89b287a04a5g](https://user-images.githubusercontent.com/57036248/172088372-356c3a9e-9669-483f-a5ca-d84f914247df.png)
