### ISSUE TITLE
Recommend using nextest for testing

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#12769]
[Nextest](https://nexte.st/) significantly improves the speed of running tests by using a better execution model than `cargo test`. It also provides some useful features like re-running flaky tests automatically, test partitioning and reusing builds.

## CI

On the build machine, build all tests and only run proc-macro related unit tests:

```bash
cargo nextest run --workspace --platform-filter host
```

Then, archive the test files and send it to test machines:

```bash
cargo nextest archive --workspace --archive-file tests.tar.zst
# upload tests.tar.zst
```

On multiple test machines, we download the same test archive and run them by partition:

```bash
# The test machine doesn't need cargo, use cargo-nextest instead
cargo-nextest nextest run --platform-filter target --partition hash:1/5 --retries 3 --test-threads 3 --failure-output=immediate-final --archive-file tests.tar.zst
```

The flaky tests will be shown at the end of the output and can be collected and tracked easily.

## Local

Nextest can be the recommended test runner if a developer wants to run all tests locally:

```
cargo nextest run --workspace --retries 3
```

**Comment by sticnarf** [comment]
cc @purelind @BusyJay

**Comment by tabokie** [comment]
I tested it in https://github.com/tikv/tikv/pull/12799 and https://ci.pingcap.net/blue/organizations/jenkins/debug-tikv-new-test/activity. The test time is reduced from 5m to 3m, with 40% less CPU resources (from 20\*2c to 3\*8c).

**Comment by BusyJay** [comment]
Very promising! Have you check the total running test case number compared to the old way?

**Comment by BusyJay** [comment]
I would argue 20 * 2c vs 3 * 8c is not a fair comparison. As with 2c mode, pods are allocated quickly and freed quickly, so it's not occupied all the time. Perhaps should test the old way with 3 * 8c or test the nextest with 20 * 2c.

**Comment by tabokie** [comment]
@BusyJay Actually using more cores is a requirement for getting those benefits. Nextest excels at optimally parallelizing tests, so using a 2c machine can't demonstrate its execution model. On the other hand, using cargo test on 8c machine doesn't seem like a viable choice. Based on my local tests before, isolation by threads (in contrary to nextest's process isolation) is simply too weak to reliably run our test cases. And to add to the argument, running integration tests locally with (-j 8 --no-fail-fast) shows nextest is 65% faster.

Still, pod allocation is a valid concern. I'll see if I can squeeze it to 2\*8c to ease the transition.

**Comment by tabokie** [comment]
> Have you check the total running test case number compared to the old way?

163 benches out of 2865 tests are not run by nextest.
