### ISSUE TITLE
Workload Error when killing pd Leader in HA test

### ISSUE THREAD

**Issue by yongpan0709** [tikv/tikv#12794]
### What version of TiKV are you using?

6.1.0-alpha   5c6018e5711bec3d13f9cdf39d3a84ed9de27809

### Steps to reproduce

1. Deploy RawKV Cluster, API-Version =2 , storage.enable-ttl: true
2. Start Workload R-W
3. Kill PD Leader

### What did you expect?
Workload runs normally.

### What did happened?
Some R-W actions failed.

**Comment by pingyu** [comment]
### Issue Analysis

The duration of `raw_get` & `raw_compare_and_swap` is much longer than expect, up to 8s (The metrics in the following diagram is MAX message duration)
![middle_img_v2_50945c99-988e-406c-9975-63b54bae26ag](https://user-images.githubusercontent.com/1907938/173009678-7cefa157-e933-4ed6-83c9-1d9ded45017f.jpg)

We can also see that the long duration of `propose wait`:
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/1907938/173009890-8f42ba45-a11a-4441-982e-9b098643d4f3.png">


From metrics & logs, the 8s consist of:
1. 4s from PD leader killed to TSO service recovery.
pd.log:
```
Jun 6, 2022 @ 11:40:21.222	7105962764204181729	pd	pd-2.pd-peer	[node.go:331] ["raft.node: aa10f5ac15deb34e lost leader b7a58c96c777aa50 at term 2"]
Jun 6, 2022 @ 11:40:21.223	7105962764204181729	pd	pd-2.pd-peer	[node.go:325] ["raft.node: aa10f5ac15deb34e elected leader aa10f5ac15deb34e at term 3"]
Jun 6, 2022 @ 11:40:21.223	7105962764204181729	pd	pd-2.pd-peer	[raft.go:765] ["aa10f5ac15deb34e became leader at term 3"]
Jun 6, 2022 @ 11:40:25.320	7105962764204181729	pd	pd-2.pd-peer	[server.go:1410] ["PD cluster leader is ready to serve"] [pd-leader-name=pd-pd-2.pd-peer-2579]
```

2. 3s from TSO service recovery to TiKV's tso component restart & recovery.
tikv.log:
```
Jun 6, 2022 @ 11:40:22.352	tikv-7.tikv-peer	[[util.rs:447](http://util.rs:447/)] ["request failed, retry"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/[client.rs:897](http://client.rs:897/)]: get timestamp timeout\")"]
Jun 6, 2022 @ 11:40:26.357	tikv-7.tikv-peer	[[util.rs:701](http://util.rs:701/)] ["connected to PD member"] [endpoints=http://pd-2.pd-peer:2579/]
Jun 6, 2022 @ 11:40:26.358	tikv-7.tikv-peer	[[util.rs:385](http://util.rs:385/)] ["trying to update PD client done"] [spend=4.365108ms]
Jun 6, 2022 @ 11:40:26.358	tikv-7.tikv-peer	[[util.rs:258](http://util.rs:258/)] ["update pd client"] [via=] [leader=http://pd-2.pd-peer:2579/] [prev_via=] [prev_leader=http://pd-0.pd-peer:2579/]
Jun 6, 2022 @ 11:40:27.310	tikv-7.tikv-peer	[[util.rs:447](http://util.rs:447/)] ["request failed, retry"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/[client.rs:897](http://client.rs:897/)]: get timestamp timeout\")"]
Jun 6, 2022 @ 11:40:27.311	tikv-7.tikv-peer	[[tso.rs:157](http://tso.rs:157/)] ["TSO worker terminated"] [receiver_cause=None] [sender_cause=None]
Jun 6, 2022 @ 11:40:27.312	tikv-7.tikv-peer	[[util.rs:258](http://util.rs:258/)] ["update pd client"] [via=] [leader=http://pd-2.pd-peer:2579/] [prev_via=] [prev_leader=http://pd-2.pd-peer:2579/]
Jun 6, 2022 @ 11:40:28.314	tikv-7.tikv-peer	[[util.rs:385](http://util.rs:385/)] ["trying to update PD client done"] [spend=4.366822ms]
```

### Solutions
We can solve this issue from 3 aspect:
1. Shorten the recovery duration of PD's TSO service (https://github.com/tikv/pd/issues/5122).
2. Shorten the recovery duration of TiKV's tso worker.
3. Cache more TSO in [`BatchTsoProvider`](https://github.com/tikv/tikv/blob/ab968ffb5e496ea1fce4ff40ee0e562247de98dd/components/causal_ts/src/tso.rs#L128) to be more tolerable to fault of TSO service.

**Comment by Connor1996** [comment]
@pingyu can it close now?

**Comment by pingyu** [comment]
Oh yes, it can.
