### ISSUE TITLE
br log backup checkpoint lag > 1H after stop restarting tikv for 1H

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12854]
### What version of TiKV are you using?
/ # /tikv-server -V
TiKV
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   9fda7293db13eb2441a3814609d7a48b0c140cae
Git Commit Branch: 6.1.0-pitr-dev
UTC Build Time:    2022-06-13 03:03:45
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           release

### What operating system and CPU are you using?
K8S

### Steps to reproduce
1. Restart TiKV multiple times
2. Start log backup  at 11:18 
3. Restart TiKV servers multiple times (stop restarting TiKV at ~11:40)
4. Check log backup status
5
### What did you expect?
Log backup checkpoint should move forward in 20 minutes after stop TiKV restart.

### What did happened?
Log backup checkpoint doesn't move foward until ~12:44
There is a TiKV restart at ~12:33

![image](https://user-images.githubusercontent.com/7403864/174570854-9b4c4a56-b7db-4278-80d0-c4568b9db0cb.png)

![image](https://user-images.githubusercontent.com/7403864/174570529-466d2de4-0f37-477d-8384-4e715500a60c.png)

![image](https://user-images.githubusercontent.com/7403864/174573221-f17e9d08-88f1-4d50-bb43-fc80bcde9f74.png)

**Comment by YuJuncen** [comment]
The reason is probably the callback in the message 'CaptureChange' has been dropped.

**Comment by 3pointer** [comment]
after new checkpoint model implemented(https://github.com/pingcap/tidb/issues/35164), we need re-consider this kind of issue. close it
