### ISSUE TITLE
tikv should support use hostname instead of ip for status_address

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#12867]
### What version of TiKV are you using?

sh-4.2# ./tikv-server -Version
TiKV
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   c1a09b83f6da437f49758dc713150ebc0da5fcb9
Git Commit Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time:    2022-06-18 14:26:16
Rust Version:      rustc 1.62.0-nightly (7c4b47696 2022-04-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce

1、Deploy one cluster with tls enabled between all components in k8s dockers, part of topo list as following,
tikv_servers:
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tiup/deploy"
  data_dir: "/tiup/data"
  arch: "amd64"
  enable_tls: true

host: tikv1-peer
port: 20160
status_port: 20180
config:
server.labels:
dc: dc1
zone: zone1
host: host1

2、Show tikv config
show config where type='tikv';

### What did you expect?
No error report, and config can be show.

### What did happened?
MySQL [(none)]> show config where type='tikv';
Empty set, 3 warnings (0.09 sec)

MySQL [(none)]> show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                               |
+---------+------+-------------------------------------------------------------------------------------------------------+
| Warning | 1105 | Get "https://10.233.80.87:20180/config": x509: certificate is valid for 127.0.0.1, not 10.233.80.87   |
| Warning | 1105 | Get "https://10.233.98.159:20180/config": x509: certificate is valid for 127.0.0.1, not 10.233.98.159 |
| Warning | 1105 | Get "https://10.233.113.26:20180/config": x509: certificate is valid for 127.0.0.1, not 10.233.113.26 |
+---------+------+-------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)

Since in k8s, pod ip may changed, so if status_address use host will be helpful in this situation.

sh-4.2# tiup ctl:nightly pd -u https://pd1-peer:2379 --cacert /root/.tiup/storage/cluster/clusters/debug/tls/ca.crt --cert /root/.tiup/storage/cluster/clusters/debug/tls/client.crt  --key /root/.tiup/storage/cluster/clusters/debug/tls/client.pem store |grep status_address
Starting component `ctl`: /root/.tiup/components/ctl/v6.2.0-alpha-nightly-20220620/ctl /root/.tiup/components/ctl/v6.2.0-alpha-nightly-20220620/ctl pd -u https://pd1-peer:2379 --cacert /root/.tiup/storage/cluster/clusters/debug/tls/ca.crt --cert /root/.tiup/storage/cluster/clusters/debug/tls/client.crt --key /root/.tiup/storage/cluster/clusters/debug/tls/client.pem store
        "status_address": "0.0.0.0:20180",
        "status_address": "0.0.0.0:20180",
        "status_address": "0.0.0.0:20180",

**Comment by zhongzc** [comment]
https://github.com/pingcap/tiup/issues/1988#issuecomment-1187044956
> already fixed on https://github.com/pingcap/tiup/pull/1873

@mayjiang0203 the latest tiup-cluster has fixed this issue. Update tiup-cluster via `tiup update cluster` and retry to see if resolved or not.
