### ISSUE TITLE
compact-cluster using high threads  may cause oom

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#12887]
## Bug Report

From oncall-5044
### What version of TiKV are you using?

6.0.0

### Steps to reproduce

tiup ctl:v6.0.0 tikv --pd 172.16.6.130:2379 compact-cluster --threads 4 --bottommost force

### What did you expect?
succeed.

### What did happened?
Failed, and one tikv oom.

**Comment by mayjiang0203** [comment]
Clinic link:
[portal/#/orgs/39/clusters/7045148589375764408]

**Comment by tonyxuqqi** [comment]
not repro-ed so far. Close it for now.
