### ISSUE TITLE
br log backup too many small files and too many files in single folder

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12885]
### What version of TiKV are you using?
/ # /tikv-server -V
TiKV
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   9fda7293db13eb2441a3814609d7a48b0c140cae
Git Commit Branch: 6.1.0-pitr-dev
UTC Build Time:    2022-06-13 03:03:45
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)

### What operating system and CPU are you using?
K8S

### Steps to reproduce
Running log backup for about 7 days, with QPS(insert & update 8K+)

### What did you expect?
Log backup should not generate too many small file, and put too many files in a single folder.

### What did happened?
Currently log backup files are small ( tens of KB to hundred of KB mostly.), and one folder for each table, and result in log backup error if target storage is ext4.

Lots of log files flushed to minio (ext4 file system), and exceed the limit of ext4 file system, and log backup in error status
```
[二 6月 21 03:33:40 2022] EXT4-fs warning (device dm-4): ext4_dx_add_entry:2353: Directory (ino: 568113172) index full, reach max htree level :2
[二 6月 21 03:33:40 2022] EXT4-fs warning (device dm-4): ext4_dx_add_entry:2357: Large directory feature is not enabled on this filesystem
```

![image](https://user-images.githubusercontent.com/7403864/175197629-8fb21637-4365-4f83-a70d-b8be559c9afb.png)

**Comment by 3pointer** [comment]
https://github.com/tikv/tikv/pull/13018 will partition files by date/store
