### ISSUE TITLE
[BR] Duration 99 triples  when log backup and full backup are in progress

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12896]
### What version of TiKV are you using?
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   900dd036829662f4e88d31fc66fc3aada09a9924
Git Commit Branch: 6.1.0-pitr-dev

### What operating system and CPU are you using?
K8S

### Steps to reproduce
1. Start log backup, check the duration & QPS
2. Run workload, QPS ~9K, insert&update: 3K
3. Start full backup when cluster has about 4TB data, check duration & QPS again

### What did you expect?
Duration should not increased more than 10% 

### What did happened?
Duration 99 triples from ~4 ms to ~12 ms.

![origin_img_v2_3baf0e24-37f2-4e24-99b4-7c250ce50bag](https://user-images.githubusercontent.com/7403864/175288032-d0ecfe09-dd5b-4086-8acb-0656a3f03376.jpg)

**Comment by 3pointer** [comment]
close it due to the we can manually set backup.num-threads to reduce the influence of backup
