### ISSUE TITLE
PiTR log backup fails due to "failed to put object rusoto error"

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12902]
### What version of TiKV are you using?
│/ # /tikv-server -V
│TiKV
│Release Version:   6.1.0-alpha
│Edition:           Community
│Git Commit Hash:   900dd036829662f4e88d31fc66fc3aada09a9924
│Git Commit Branch: 6.1.0-pitr-dev
│UTC Build Time:    2022-06-13 03:03:45

### What operating system and CPU are you using?
K8S

### Steps to reproduce
1. Start log backup with workload running for about 10 days.

### What did you expect?
Log backup should not fail.

### What did happened?
![image](https://user-images.githubusercontent.com/7403864/175462091-867b0732-a981-40a5-8ea9-70c86bc110d4.png)

**Comment by 3pointer** [comment]
If it's the error from external storage and can not recover. I think log backup expect to fail.
