### ISSUE TITLE
BR log backup data lost if tikv restart followed by tikv network partition

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#12918]
### What version of TiKV are you using?
Release Version:   6.1.0
Edition:           Enterprise
Git Commit Hash:   f20a1195ddadf435329a0fbde7326ae9df17c245
Git Commit Branch: heads/refs/tags/v6.1.0-20220622
UTC Build Time:    2022-06-24 13:42:12

### What operating system and CPU are you using?
K8S

### Steps to reproduce
1. start log backup
2. do a full backup
3. start a workload
4. restart tikv, and start tikv network partition  (run chaos for 20 minutes for every 30 minutes, partition network between all tikvs)
![image](https://user-images.githubusercontent.com/7403864/175938220-4fc2c710-49c6-4df7-91a8-c6b9d0f5cbc4.png)
![image](https://user-images.githubusercontent.com/7403864/175938249-843533e4-ddc1-43db-a206-5f84c81de445.png)
5. do a PiTR restore and run sync_diff to check data consistency
![image](https://user-images.githubusercontent.com/7403864/175938341-a2ed2b83-339c-4ca2-9762-c78420079025.png)
 

### What did you expect?
data should be consistent.

### What did happened?
![image](https://user-images.githubusercontent.com/7403864/175938365-857584e5-ee7b-4995-8d34-7969b0cdb8d2.png)

 
![image](https://user-images.githubusercontent.com/7403864/175938452-2e541f8b-493e-468b-8905-85a63d7a5508.png)

**Comment by 3pointer** [comment]
After implement new checkpoint model this issue will be fixed. https://github.com/pingcap/tidb/issues/35164
