### ISSUE TITLE
Remove the suppport for specifying block cache for cf manually

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#12936]
## Feature Request

For historical reason, we support specifying block cache for each cf for either raft db or kv db. But since we support sharing cache between CFs and dbs (3 years ago), these settings are not practical anymore. They are hard to use and easy to make mistake. We better remove those settings and always enabling share cache for simplicity.

**Comment by BusyJay** [comment]
For those users that still use the settings (should be very few if any), it's recommended to migrate to the share cache method and set a total capacity instead.

**Comment by sunxiaoguang** [comment]
+1
