### ISSUE TITLE
tikv-server store id is invalid

### ISSUE THREAD

**Issue by Smityz** [tikv/tikv#13001]
### What version of TiKV are you using?

v5.3.0

### What operating system and CPU are you using?

centos7 / Intel CPU

### What did happened?
tikv server(x.x.84.132:20110) report store ID 1035, not found
```
[2022/07/12 11:47:02.548 +08:00] [ERROR] [util.rs:460] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 1035, not found\", details: [] }))"]
[2022/07/12 11:47:03.549 +08:00] [ERROR] [util.rs:460] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 1035, not found\", details: [] }))"]
```
But pd shows its store ID should be 1989
```
Machine        Port   Store  Status  Leaders  Regions  Capacity  Available  Labels
-------        ----   -----  ------  -------  -------  --------  ---------  ------
x.x.84.132
               20040  1989   Up      214      623      1.074TiB  902.4GiB   {host: x.x.84.132}
```

Then I check pd info, find it still have a heartbeat
```
{
  "store": {
    "id": 1989,
    "address": "x.x.84.132:20040",
    "labels": [
      {
        "key": "host",
        "value": "x.x.84.132"
      }
    ],
    "version": "5.3.0",
    "status_address": "x.x.84.132:20041",
    "git_hash": "6c1424706f3d5885faa668233f34c9f178302f36",
    "start_timestamp": 1654855114,
    "deploy_path": "x/tikv-20040/bin",
    "last_heartbeat": 1657598258981392596,
    "state_name": "Up"
  },
  "status": {
    "capacity": "1.074TiB",
    "available": "902.4GiB",
    "used_size": "128.6GiB",
    "leader_count": 214,
    "leader_weight": 1,
    "leader_score": 214,
    "leader_size": 54870,
    "region_count": 623,
    "region_weight": 1,
    "region_score": 202357.82097795728,
    "region_size": 156557,
    "slow_score": 1,
    "start_ts": "2022-06-10T17:58:34+08:00",
    "last_heartbeat_ts": "2022-07-12T11:57:38.981392596+08:00",
    "uptime": "761h59m4.981392596s"
  }
}
```

**Comment by zhangjinpeng1987** [comment]
@Smityz How many tikv instances you have?

**Comment by Smityz** [comment]
2000 instance+

**Comment by Smityz** [comment]
> @Smityz How many tikv instances you have?

2000+

After I restart one tikv instance, the error msg disapper, but others still have this error

**Comment by JmPotato** [comment]
Hi, after reading the code, the "invalid store ID" error is most likely from calling the PD's GetStore. Considering the large TiKV instance number, it may be caused by a backlog of some kinds of obsolete tasks. "1035 not found" may not be returned by query `84.132`, so would you like to provide more contextual logs to see exactly what went wrong?

**Comment by tonyxuqqi** [comment]
@Smityz 
I’m wondering if it’s possible to send us the metrics information which will give us better context on what happened. The metrics also has the history information of store Id

**Comment by Smityz** [comment]
> 

What metrics are you looking at?

**Comment by tonyxuqqi** [comment]
> What metrics are you looking at?

I think we can start with the PD’s metrics for the time duration about one hour when this issue happened.

**Comment by Smityz** [comment]
Tikv server continue printing these logs
```
[2022/07/14 10:45:52.997 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.165.72:2379]
[2022/07/14 10:45:52.997 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7fec59d7ccb0 for subchannel 0x7fed2d584cc0"]
[2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.166.70:2379]
[2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:668] ["connected to PD member"] [endpoints=http://x.x.166.70:2379]
[2022/07/14 10:45:52.999 +08:00] [INFO] [util.rs:202] ["heartbeat sender and receiver are stale, refreshing ..."]
[2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:573] ["cancel region heartbeat sender"]
[2022/07/14 10:45:52.999 +08:00] [INFO] [tso.rs:148] ["TSO worker terminated"] [receiver_cause=None] [sender_cause=None]
[2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:136] ["TSO stream is closed, reconnect to PD"]
[2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:230] ["update pd client"] [via=] [leader=http://x.x.166.70:2379] [prev_via=] [prev_leader=http://x.x.166.70:2379]
[2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:357] ["trying to update PD client done"] [spend=3.163775ms]
[2022/07/14 10:45:53.000 +08:00] [WARN] [client.rs:138] ["failed to update PD client"] [error="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
[2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:460] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 570, not found\", details: [] }))"]
[2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:469] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
```
It seems like it never stops reconnecting the non-existing store.

**Comment by Smityz** [comment]
> > What metrics are you looking at?
> 
> I think we can start with the PD’s metrics for the time duration about one hour when this issue happened.

It's too large to identify, you can give some specific metrics to check.

```
[2022/07/14 10:53:06.779 +08:00] [ERROR] [grpclog.go:75] ["transport: Got too many pings from the client, closing the connection."]
[2022/07/14 10:53:06.779 +08:00] [ERROR] [grpclog.go:75] ["transport: loopyWriter.run returning. Err: transport: Connection closing"]
[2022/07/14 10:53:06.780 +08:00] [WARN] [grpclog.go:60] ["transport: http2Server.HandleStreams failed to read frame: read tcp x.x.166.1:2379->x.x.25.146:52400: use of closed network connection"]
```

pd-server continues printing these logs

**Comment by BornChanger** [comment]
@Smityz was your large tikv cluster running well previously? or it's just established.

**Comment by tonyxuqqi** [comment]
> > > What metrics are you looking at?
> > 
> > 
> > I think we can start with the PD’s metrics for the time duration about one hour when this issue happened.
> 
> It's too large to identify, you can give some specific metrics to check.
> 
> ```
> [2022/07/14 10:53:06.779 +08:00] [ERROR] [grpclog.go:75] ["transport: Got too many pings from the client, closing the connection."]
> [2022/07/14 10:53:06.779 +08:00] [ERROR] [grpclog.go:75] ["transport: loopyWriter.run returning. Err: transport: Connection closing"]
> [2022/07/14 10:53:06.780 +08:00] [WARN] [grpclog.go:60] ["transport: http2Server.HandleStreams failed to read frame: read tcp x.x.166.1:2379->x.x.25.146:52400: use of closed network connection"]
> ```
> 
> pd-server continues printing these logs

You may use clinic to upload PD metrics. Thanks.

**Comment by tonyxuqqi** [comment]
> Thanks
For how to use clinic for troubleshooting, please refer 
https://docs.pingcap.com/tidb/dev/clinic-user-guide-for-tiup
@Smityz

**Comment by Smityz** [comment]
> 

It has run well in the past 1 month and undertaken about 600k put throughput.
Our HDD disk quality is not well, so crashes are always happening

**Comment by Smityz** [comment]
> @Smityz was your large tikv cluster running well previously? or it's just established.

It has run well in the past 1 month and undertaken about 600k put throughput.
Our HDD disk quality is not well, so crashes are always happening

**Comment by JmPotato** [comment]
> Tikv server continue printing these logs
> 
> ```
> [2022/07/14 10:45:52.997 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.165.72:2379[](http://x.x.165.72:2379)]
> [2022/07/14 10:45:52.997 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7fec59d7ccb0 for subchannel 0x7fed2d584cc0"]
> [2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.166.70:2379[](http://x.x.166.70:2379)]
> [2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:668] ["connected to PD member"] [endpoints=http://x.x.166.70:2379[](http://x.x.166.70:2379)]
> [2022/07/14 10:45:52.999 +08:00] [INFO] [util.rs:202] ["heartbeat sender and receiver are stale, refreshing ..."]
> [2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:573] ["cancel region heartbeat sender"]
> [2022/07/14 10:45:52.999 +08:00] [INFO] [tso.rs:148] ["TSO worker terminated"] [receiver_cause=None] [sender_cause=None]
> [2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:136] ["TSO stream is closed, reconnect to PD"]
> [2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:230] ["update pd client"] [via=] [leader=http://x.x.166.70:2379[](http://x.x.166.70:2379)] [prev_via=] [prev_leader=http://x.x.166.70:2379[](http://x.x.166.70:2379)]
> [2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:357] ["trying to update PD client done"] [spend=3.163775ms]
> [2022/07/14 10:45:53.000 +08:00] [WARN] [client.rs:138] ["failed to update PD client"] [error="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
> [2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:460] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 570, not found\", details: [] }))"]
> [2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:469] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
> ```
> 
> It seems like it never stops reconnecting the non-existing store.

The reconnection is more likely the result of a request failure.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/1446531/178891823-04c94a35-d7c3-45fa-bbd1-14c651a6dc54.png">

Currently, we need to figure out what kind of task triggers the `invalid store ID 570` error. As mentioned above, clinic info would be very helpful, which could provide us with more detailed metrics and logs.

**Comment by Smityz** [comment]
> https://docs.pingcap.com/tidb/dev/clinic-user-guide-for-tiup

Thanks for your suggestion~
I believe Clinic is a wonderful tool to help people diagnose TiKV problems, but for some reason, we can't upload this data.

**Comment by Smityz** [comment]
> > Tikv server continue printing these logs
> > ```
> > [2022/07/14 10:45:52.997 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.165.72:2379[](http://x.x.165.72:2379)]
> > [2022/07/14 10:45:52.997 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7fec59d7ccb0 for subchannel 0x7fed2d584cc0"]
> > [2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.166.70:2379[](http://x.x.166.70:2379)]
> > [2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:668] ["connected to PD member"] [endpoints=http://x.x.166.70:2379[](http://x.x.166.70:2379)]
> > [2022/07/14 10:45:52.999 +08:00] [INFO] [util.rs:202] ["heartbeat sender and receiver are stale, refreshing ..."]
> > [2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:573] ["cancel region heartbeat sender"]
> > [2022/07/14 10:45:52.999 +08:00] [INFO] [tso.rs:148] ["TSO worker terminated"] [receiver_cause=None] [sender_cause=None]
> > [2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:136] ["TSO stream is closed, reconnect to PD"]
> > [2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:230] ["update pd client"] [via=] [leader=http://x.x.166.70:2379[](http://x.x.166.70:2379)] [prev_via=] [prev_leader=http://x.x.166.70:2379[](http://x.x.166.70:2379)]
> > [2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:357] ["trying to update PD client done"] [spend=3.163775ms]
> > [2022/07/14 10:45:53.000 +08:00] [WARN] [client.rs:138] ["failed to update PD client"] [error="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
> > [2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:460] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 570, not found\", details: [] }))"]
> > [2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:469] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems like it never stops reconnecting the non-existing store.
> 
> The reconnection is more likely the result of a request failure.
> 
> <img alt="image" width="991" src="https://user-images.githubusercontent.com/1446531/178891823-04c94a35-d7c3-45fa-bbd1-14c651a6dc54.png">
> 
> Currently, we need to figure out what kind of task triggers the `invalid store ID 570` error. As mentioned above, clinic info would be very helpful, which could provide us with more detailed metrics and logs.

These logs appear after the scale-in operation, let's try to see if we can reproduce this problem.
Maybe we should print all stacks when meeting this error

**Comment by JmPotato** [comment]
> > > Tikv server continue printing these logs
> > > ```
> > > [2022/07/14 10:45:52.997 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.165.72:2379[](http://x.x.165.72:2379)[](http://x.x.165.72:2379[](http://x.x.165.72:2379))]
> > > [2022/07/14 10:45:52.997 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7fec59d7ccb0 for subchannel 0x7fed2d584cc0"]
> > > [2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:544] ["connecting to PD endpoint"] [endpoints=http://x.x.166.70:2379[](http://x.x.166.70:2379)[](http://x.x.166.70:2379[](http://x.x.166.70:2379))]
> > > [2022/07/14 10:45:52.998 +08:00] [INFO] [util.rs:668] ["connected to PD member"] [endpoints=http://x.x.166.70:2379[](http://x.x.166.70:2379)[](http://x.x.166.70:2379[](http://x.x.166.70:2379))]
> > > [2022/07/14 10:45:52.999 +08:00] [INFO] [util.rs:202] ["heartbeat sender and receiver are stale, refreshing ..."]
> > > [2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:573] ["cancel region heartbeat sender"]
> > > [2022/07/14 10:45:52.999 +08:00] [INFO] [tso.rs:148] ["TSO worker terminated"] [receiver_cause=None] [sender_cause=None]
> > > [2022/07/14 10:45:52.999 +08:00] [INFO] [client.rs:136] ["TSO stream is closed, reconnect to PD"]
> > > [2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:230] ["update pd client"] [via=] [leader=http://x.x.166.70:2379[](http://x.x.166.70:2379)[](http://x.x.166.70:2379[](http://x.x.166.70:2379))] [prev_via=] [prev_leader=http://x.x.166.70:2379[](http://x.x.166.70:2379)[](http://x.x.166.70:2379[](http://x.x.166.70:2379))]
> > > [2022/07/14 10:45:53.000 +08:00] [INFO] [util.rs:357] ["trying to update PD client done"] [spend=3.163775ms]
> > > [2022/07/14 10:45:53.000 +08:00] [WARN] [client.rs:138] ["failed to update PD client"] [error="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
> > > [2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:460] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"invalid store ID 570, not found\", details: [] }))"]
> > > [2022/07/14 10:45:53.000 +08:00] [ERROR] [util.rs:469] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:306]: cancel reconnection due to too small interval\")"]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It seems like it never stops reconnecting the non-existing store.
> > 
> > 
> > The reconnection is more likely the result of a request failure.
> > <img alt="image" width="991" src="https://user-images.githubusercontent.com/1446531/178891823-04c94a35-d7c3-45fa-bbd1-14c651a6dc54.png">
> > Currently, we need to figure out what kind of task triggers the `invalid store ID 570` error. As mentioned above, clinic info would be very helpful, which could provide us with more detailed metrics and logs.
> 
> These logs appear after the scale-in operation, let's try to see if we can reproduce this problem. Maybe we should print all stacks when meeting this error

How exactly does the "scale-in operation" work? Is there any forced scale-in operation with putting the store into Tombstone from PD?

* If the scale-in operation is correct, the current guess is that some tasks that need to get the store info from PD become outdated due to a huge backlog.
* If the scale-in operation is not correct, it will cause the region meta info to be not consistent with the actual cluster store info.
