### ISSUE TITLE
after upgrade tikv restart failed (option not match)

### ISSUE THREAD

**Issue by River2000i** [tikv/tikv#13015]
### What version of TiKV are you using?

```
TiKV
Release Version:   5.4.0
Edition:           Community
Git Commit Hash:   b5262299604df88711d9ed4b84d43e9c507749a2
Git Commit Branch: heads/refs/tags/v5.4.0
UTC Build Time:    2022-01-25 07:14:08
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```
### What operating system and CPU are you using?

8core 、16G

### What did you expect?

tikv can upgrade success

### What did happened?

{"namespace":"endless-htap-upgrade-tps-874099-1-247","level":"FATAL","log":"[lib.rs:494] [\"failed to load_latest_options \\\"Invalid argument: Could not find option: : enable_multi_thread_write\\\"\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:493:18\\n   1: std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:702:17\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:588:13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:138:18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:142:14\\n   6: engine_rocks::raw_util::new_engine_opt::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/engine_rocks/src/raw_util.rs:120:33\\n      core::result::Result<T,E>::unwrap_or_else\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1464:23\\n      engine_rocks::raw_util::new_engine_opt\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/engine_rocks/src/raw_util.rs:119:24\\n   7: <raft_log_engine::engine::RaftLogEngine as server::server::ConfiguredRaftEngine>::build\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/server/src/server.rs:1594:26\\n      server::server::TiKvServer<CER>::init_raw_engines\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/server/src/server.rs:1622:27\\n   8: server::server::run_impl\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/server/src/server.rs:155:35\\n      server::server::run_tikv\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/server/src/server.rs:190:5\\n   9: tikv_server::main\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/cmd/tikv-server/src/main.rs:189:5\\n  10: core::ops::function::FnOnce::call_once\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18\\n  11: main\\n  12: __libc_start_main\\n  13: <unknown>\\n\"] [location=components/engine_rocks/src/raw_util.rs:120] [thread_name=main]","container":"tikv","pod":"tc-tikv-2"}

**Comment by ethercflow** [comment]
same as https://github.com/tikv/tikv/issues/13007
