### ISSUE TITLE
tikv cannot start when open titan

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#13038]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   23588581613251bdec283764a604197dd00ca377
Git Commit Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time:    2022-07-14 11:03:14
Rust Version:      rustc 1.62.0-nightly (7c4b47696 2022-04-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce
1、open titan
2、run workload
3、restart one tikv
4、tikv cannot start after restarting tikv（upgrade image which include the pr commit pipeline write）

### What did you expect?
tikv can start when open titan

### What did happened?
"namespace":"glh-master-57b58","level":"FATAL","pod":"tc-tikv-0","container":"tikv","log":"[[lib.rs:494](http://lib.rs:494/)] [\"failed to write to engine: Engine(\\\"Not implemented: \\\")\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:493:18\\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:493:18//n)   1: std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:702](http://panicking.rs:702/):17\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:588](http://panicking.rs:588/):13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:138](http://backtrace.rs:138/):18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:584](http://panicking.rs:584/):5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:142](http://panicking.rs:142/):14\\n   6: raftstore::store::fsm::apply::ApplyContext<EK>::write_to_db::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:529:17\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:529:17//n)      core::result::Result<T,E>::unwrap_or_else\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[result.rs:1464](http://result.rs:1464/):23\\n      raftstore::store::fsm::apply::ApplyContext<EK>::write_to_db\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:528:13\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:528:13//n)   7: raftstore::store::fsm::apply::ApplyContext<EK>::flush\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:634:25\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:634:25//n)   8: <raftstore::store::fsm::apply::ApplyPoller<EK> as batch_system::batch::PollHandler<raftstore::store::fsm::apply::ApplyFsm<EK>,raftstore::store::fsm::apply::ControlFsm>>::end\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:3940:9\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:3940:9//n)      batch_system::batch::Poller<N,C,Handler>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/batch-system/src/batch.rs:482:13\\n](http://github.com/pingcap/tikv/components/batch-system/src/batch.rs:482:13//n)   9: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/batch-system/src/batch.rs:590:17\\n](http://github.com/pingcap/tikv/components/batch-system/src/batch.rs:590:17//n)      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:414:23\\n](http://github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:414:23//n)      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:122](http://backtrace.rs:122/):18\\n  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:500](http://mod.rs:500/):17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:492](http://panicking.rs:492/):40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:456](http://panicking.rs:456/):19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:499](http://mod.rs:499/):30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:248](http://function.rs:248/):5\\n  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:1866](http://boxed.rs:1866/):9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:1866](http://boxed.rs:1866/):9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2022-05-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\\n  12: <unknown>\\n  13: clone\\n\"] [location=/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:529](http://github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:529)] [thread_name=apply-1]"}

**Comment by ethercflow** [comment]
Fixed in https://github.com/tikv/titan/pull/255
