### ISSUE TITLE
tikv oom when tikv instance has a large number of regions such as 30w+

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#13042]
### What version of TiKV are you using?
it doesn't matter

### What operating system and CPU are you using?
5 sets of 7.2*9 disks + 256GB + 96C machines, each machine has 9 instances, the cluster capacity is 153TB, the number of regions is 372w, and each instance has nearly 10w regions

### Steps to reproduce
The memory usage of tikv instance is too high, triggering oom, memory exhaustion, host hang death

### What did happened?
The memory usage of tikv instance is too high, triggering oom, memory exhaustion, host hang death

**Comment by tier-cap** [comment]
There are three main memory cost:
1. The memory for each Peer both in Store and Apply.
2. The memory for each Channel in Store.
3. The memory for each Channel in Apply.

**Comment by tonyxuqqi** [comment]
I think we need to have a formula on memory usage with region count and publish it in TiKV official document.  
And in this case, the fix is to ask user use larger region size.

**Comment by tonyxuqqi** [comment]
Dup with #15701
