### ISSUE TITLE
test_stale_read_while_applying_snapshot always fails in local environment

### ISSUE THREAD

**Issue by SpadeA-Tang** [tikv/tikv#13057]
## Bug Report

In my local environment (ubuntu 22 and mac os), test_stale_read_while_applying_snapshot always fails after https://github.com/tikv/tikv/pull/12533. It can pass before this PR. 

Fail message:
```
thread 'cases::test_replica_stale_read::test_stale_read_while_applying_snapshot' panicked at 'message: "peer 2 is not ready, safe_ts 0, region 1" data_is_not_ready { region_id: 1 peer_id: 2 }'
```

**Comment by SpadeA-Tang** [comment]
@tabokie

**Comment by SpadeA-Tang** [comment]
@NingLin-P

**Comment by tabokie** [comment]
@5kbpers Mind take a look?
