### ISSUE TITLE
Raftstore may broadcast too many messages after one peer store become unreachable

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#13054]
## Bug Report

After one store disconnected, StoreFsm would broadcast a `StoreUnreachable` message to all regions to mark unreachable peers. https://github.com/tikv/tikv/blob/0dff1be50281c72c55c5464751cd733032115ce4/components/raftstore/src/store/fsm/store.rs#L378

But if TiKV has too many regions, handling these `StoreUnreachable` messages could eat raftstore CPU and block all other messages, making TiKV getting stucked.

**Comment by 5kbpers** [comment]
cc @BusyJay

**Comment by 5kbpers** [comment]
> Is there any statistics? Like with how many regions will it become a problem?

In about 800k regions, raftstore could eat up to 800% CPU usage.

**Comment by BusyJay** [comment]
How many cores? And why setting 30 threads for store pool? Most of resources may probably waste in context switch during broadcast.

**Comment by 5kbpers** [comment]
> How many cores? And why setting 30 threads for store pool? Most of resources may probably waste in context switch during broadcast.

At least 40 cores for one TiKV as I remember, actually we tried to scale it to 4 and 8, but raftstore threads CPU still be eaten up, then finally set it to 30
