### ISSUE TITLE
Redhat 8.4: tikv restart by systemd after set memory-usage-limit less than vm message

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#13090]
### What version of TiKV are you using?

sh-4.4# /tiup/deploy/tikv-20160/bin/tikv-server -V
TiKV
Release Version:   6.1.0
Edition:           Community
Git Commit Hash:   080d086832ae5ce2495352dccaf8df5d40f30687
Git Commit Branch: heads/refs/tags/v6.1.0
UTC Build Time:    2022-06-10 11:22:39
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What did you expect?
pod has request 16G memory
		err := tc.UpdateConfig(resource.TiDBClusterUpdateConfigOptions{
			Target: resource.TiKV,
			Config: "memory-usage-limit = \"12G\"\n[storage.block-cache]\ncapacity = \"7G\""})
		return err
	}

### What did happened?
tikv oom and use than 12G.
[2936253.548142] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=cri-containerd-6d9f788aa1549022adddd2d2cd5bcf2c1e6a4376059f5bf95901d9633392db28.scope,mems_allowed=0-1,oom_memcg=/kubepods.slice/kubepods-podb0bd101c_6315_4417_be9c_a2d7c9f3bb9e.slice/cri-containerd-6d9f788aa1549022adddd2d2cd5bcf2c1e6a4376059f5bf95901d9633392db28.scope/system.slice,task_memcg=/kubepods.slice/kubepods-podb0bd101c_6315_4417_be9c_a2d7c9f3bb9e.slice/cri-containerd-6d9f788aa1549022adddd2d2cd5bcf2c1e6a4376059f5bf95901d9633392db28.scope/system.slice/tikv-20160.service,task=tikv-server,pid=2326757,uid=1000
[2936253.548290] Memory cgroup out of memory: Killed process 2326757 (tikv-server) total-vm:19640788kB, anon-rss:15651428kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:32684kB oom_score_adj:-997
[2936254.543814] oom_reaper: reaped process 2326757 (tikv-server), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

![image](https://user-images.githubusercontent.com/9443637/180186429-fc929bb4-9624-45b8-859c-676f2fc30321.png)

**Comment by jebter** [comment]
any update？

**Comment by ethercflow** [comment]
@jebter Has discussed with @mayjiang0203 , She'll reproduce this, then we'll investigate why

**Comment by mayjiang0203** [comment]
After three times try, didn't reproduce oom in dmesg again, but tikv still restart many times.

![image](https://user-images.githubusercontent.com/9443637/185056815-c5b517c3-bba9-4521-8cda-0c3b352ab105.png)


And from systemd log, found that tikv restart by systemd.
journalctl -u tikv-20160.service
Aug 17 11:29:35 tikv1-0 systemd[1]: Stopping tikv service...
-- Subject: Unit tikv-20160.service has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit tikv-20160.service has begun shutting down.
Aug 17 11:29:58 tikv1-0 systemd[1]: tikv-20160.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit tikv-20160.service has successfully entered the 'dead' state.
Aug 17 11:29:58 tikv1-0 systemd[1]: Stopped tikv service.
-- Subject: Unit tikv-20160.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit tikv-20160.service has finished shutting down.
Aug 17 11:29:58 tikv1-0 systemd[1]: Started tikv service.
-- Subject: Unit tikv-20160.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit tikv-20160.service has finished starting up.

**Comment by mayjiang0203** [comment]
Update, after disable auto restart, run 6 hours, didn't hit tikv reset again. 
Need more time to verify this restart can be fixed by disable systemd auto restart.

**Comment by tonyxuqqi** [comment]
@mayjiang0203 After disable auto restart, does the problem exit anymore? If not, we may close it or downgrade the severity.

**Comment by mayjiang0203** [comment]
Yes, after disable restart, didn't hit this again.
