### ISSUE TITLE
commit b558d0 causing 7%~14% performance degradation for sysbench oltp_update_index workload

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#13095]
### Steps to reproduce

compare sysbench oltp_update_index workload with https://github.com/tikv/tikv/commit/b558d0bffc554c4c0094a483c65d95a50a4141cf
 and https://github.com/tikv/tikv/commit/126da29086da78bad3171975d4269ba283d133bd

### What did you expect?
no performance degradation

### What did happened?
commit b558d0 cause 7% ~ 14% performance degradation.

![image](https://user-images.githubusercontent.com/2316425/180250567-14cc2748-69f0-4ba2-b3a2-9acda4c7ef75.png)

**Comment by jebter** [comment]
can it be closed？

**Comment by tabokie** [comment]
It doesn't affect 6.2 anymore, I removed the tag.
