### ISSUE TITLE
br log backup checkpoint doesn't move forward due to"read index not ready, reason can not read index due to merge, region 94812"

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#13126]
### What version of TiKV are you using?
6.2.0

### What operating system and CPU are you using?
K8S

### Steps to reproduce
1. Run workload 
2. Start log backup task 
3. run tikv network partition chaos 20 minutes every 50 minutes

### What did you expect?
Log backup checkpoint should move forward when chaos is restored

### What did happened?
![origin_img_v2_617d52a6-ac84-4b5c-bb85-8f930549599g](https://user-images.githubusercontent.com/7403864/180954542-ce708876-3da9-4338-8940-f1d11ef881b8.jpg)
![origin_img_v2_617d52a6-ac84-4b5c-bb85-8f930549599g](https://user-images.githubusercontent.com/7403864/180954564-f950bd23-bde0-4446-afa8-f69a00097cfb.jpg)
![origin_img_v2_4210aa87-9727-438a-b240-b1dad11b652g](https://user-images.githubusercontent.com/7403864/180954592-48374384-681a-41e6-b2f1-2e763e2cc167.jpg)

**Comment by YuJuncen** [comment]
When (somehow) the gap between admin command `PrepareMerge` and `CommitMerge` get to huge (greater than 30s), this error would be triggered.

Both `PrepareMerge` and `CommitMerge` would make the `version` of region epoch get increased, which triggers the `RegionChanged` observer and fires an initial scanning request. However raftstore would reject the initial scanning request when `PrepareMerge` applied but `CommitMerge` not applied, it simply replies `ReadIndexNotReady`.

**Comment by YuJuncen** [comment]
...and the error `ReadIndexNotReady` isn't an ignorable error in the current implementation, which means this would consume the opportunity of retry and finally exceed it then leading to `FatalError`.

**Comment by YuJuncen** [comment]
The (possible) solutions:

- For the exception `ReadIndexNotReady` because region merging, we can trivially ignore it and give up initial scanning, because both the merge get rolled back or committed, the version would be increased too, hence would trigger a new initial scanning request.
- For this type of error, we can make them consume less retry opportunity (or, retry score?) hence we can tolerate a longer gap time.

**Comment by YuJuncen** [comment]
...another solution is we don't get split / merge from `RegionChanged` observer but `CmdObserver`, by which we can detect whether it is a `PrepareMerge` or `CommitMerge`. When it is `PrepareMerge`, we can simply ignore it and keep observing.

**Comment by YuJuncen** [comment]
We haven't encountered with this anymore in raftstore V1. Perhaps this has been fixed by https://github.com/tikv/tikv/pull/14403. Close it until this happen again.
