### ISSUE TITLE
Analyze response returns wrong count value in RC

### ISSUE THREAD

**Issue by Yisaer** [tikv/tikv#13258]
## Bug Report

ref https://github.com/pingcap/tidb/issues/36983

During TiDB mysql-test, we found a case that tikv returned wrong count value with RC isolation. 20 success in a row with SI isolation.

### What version of TiKV are you using?

nightly

### Steps to reproduce

Running mysql-test `filesort_merge` in local env, meet this error about 3~4 times once 

### What did you expect?

Analyze response return correct value.

### What did happened?

Analyze response return wrong value.

**Comment by sticnarf** [comment]
It's expected. RC does not guarantee cross-region consistency, so it's possible to get wrong count if you have many regions to merge the results.

**Comment by Yisaer** [comment]
The behavior is expected as RC isolevel will ignore txnlock even if the secodary key haven't been commited.
