### ISSUE TITLE
Use stale read to acquire snapshot instead of raw APIs

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#13319]
## Development Task

In the past, we introduce `snapshot_on_kv_engine` and `modify_on_kv_engine` to avoid breaking hibernate regions when doing gc. But now we support stale read, if we always use ts 0 to acquire snapshot, then it will never wake up any regions. So `snapshot_on_kv_engine` can be removed. If we can get the snapshot, then there must be a way to get its underlying storage engine, hence `modify_on_kv_engine` is also unnecessary. There two methods can be removed and make code cleaner.

**Comment by SpadeA-Tang** [comment]
> 

How can we use ts 0 to acquire snapshot?
![image](https://user-images.githubusercontent.com/71589810/185651985-13b08c04-6113-44dd-82d9-913e4ad8b3a1.png)
![image](https://user-images.githubusercontent.com/71589810/185652124-cb70a1ee-82ec-424a-8577-fbc530fd431c.png)

**Comment by tonyxuqqi** [comment]
> > 
> 
> How can we use ts 0 to acquire snapshot? ![image](https://user-images.githubusercontent.com/71589810/185651985-13b08c04-6113-44dd-82d9-913e4ad8b3a1.png)

I think the real question is how is the ts is consumed and what if ts = 0 in its consumer side. If the consumer can work with ts 0, then the check above can be removed.  My understanding is if ts = 0, that means the stale read can be accepted in any case
