### ISSUE TITLE
The address of the check leader message sent to the TiFlash proxy is wrong

### ISSUE THREAD

**Issue by hehechen** [tikv/tikv#13310]
https://github.com/tikv/tikv/blob/1ea26a2ac8761af356cc5c0825eb89a0b8fc9749/components/resolved_ts/src/advance.rs#L400
For TiFlash proxy, should use `store.peer_address` instead of `store.address`.

**Comment by CalvinNeo** [comment]
TiKV always use the same peer_address and address
