### ISSUE TITLE
why use timestamp plus 1 as min commit timestamp when use 1pc or async?

### ISSUE THREAD

**Issue by lee-qiu** [tikv/tikv#13373]
## Question

when use 1pc or async commit, txn will get a timestamp from pd, and set it as min_commit_ts in prewrite request as official blog says, but it seems like txn set timestamp plus one as min_commit_ts in client-go rep. 

is my thought wrong or official blog is a litter outdated?

**Comment by BusyJay** [comment]
@cfzjywxk PTAL

**Comment by cfzjywxk** [comment]
@1150310621 
If the PD timestamp is used directly as the `commit_ts`, it could be equal to a previously committed transaction's commit ts calculated from `max_ts + 1`.

**Comment by lee-qiu** [comment]
Got it and thanks.
