### ISSUE TITLE
Introduce snapshot flow control mechanism

### ISSUE THREAD

**Issue by nolouch** [tikv/tikv#13440]
## Development Task
Introduce a more friendly scale control mechanism for Dynamic Regions.
- [ ] RFC https://github.com/tikv/rfcs/pulls 
### TiKV
- [ ] Snapshot Controller
### PD
- [ ] Global Configuration [store limit by Snapshot IO rate]
- [ ] Feedback Controller algorithm

**Comment by tonyxuqqi** [comment]
resolved
