### ISSUE TITLE
Rollback all locks to prevent from losing the pessimistic lock in flashback

### ISSUE THREAD

**Issue by JmPotato** [tikv/tikv#13493]
## Feature Request

Ref #13303.

Currently, we will delete all locks unconditionally when performing the flashback. Though we will check the minimal resolved TS before a flashback multiple times (https://github.com/pingcap/tidb/pull/37607, https://github.com/tikv/tikv/pull/13412) to prevent breaking any transaction consistency, there is still a case that we should handle when it comes to a pessimistic transaction.

Assume that we have two clients {c1, c2} and a key k1:

1. c1 begins a pessimistic transaction with ts1.
2. c1 creates and writes the k1, which will put a lock record in `lock_cf`.
3. c2 starts to flashback to version ts0 that is smaller than t1, which will delete the pessimistic lock written in step 2.
4. c1 commits the transaction successfully.

We should better fail this kind of transaction to prevent breaking the flashback result, a possible method is to roll back the lock rather than deleting it directly, so that the commit will find a conflict and fail eventually.

**Comment by Connor1996** [comment]
Can you elaborate on why the transaction can commit successfully with the lock deleted

**Comment by JmPotato** [comment]
> Can you elaborate on why the transaction can commit successfully with the lock deleted

Since TiKV may fail to write pessimistic locks due to pipelined process. If the data is not changed after acquiring the lock, we can still prewrite and commit the key. We can regard it as a fallback to the optimistic transaction.

https://github.com/tikv/tikv/blob/4cce9e7869348c8a51894a047c487783d6190312/src/storage/txn/actions/prewrite.rs#L62-L70

**Comment by JmPotato** [comment]
Hi, @sticnarf could you please help add a type label to this issue and merge #13521, I didn't have permission, thx a lot!
