### ISSUE TITLE
qps recovery after 15min when one tikv io hang

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#13524]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   b1854926ad92eeedb2cb38dff2dc4bb6b30d49f0
Git Commit Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time:    2022-09-22 11:03:33
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2022-09-23T14:03:46.213+0800	INFO	k8s/client.go:131	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
 Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: 3cc82517395deba65bf90fac664927954e8907f6
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time:  2022-09-20 11:03:03

### What operating system and CPU are you using?
8c、16G

### Steps to reproduce
inject one tikv io hang
open async io and evict-slow-store-scheduler

    -   name: "one_tikv_io_delay"
        faultType: io_delay(volumeName:tikv,delay:60m)
        selector: "tikv(random)"
        warmUpTime: 10m
        faultDuration: 120m
        recoveryTime: 10m

### What did you expect?
qps can recovery in 2min

### What did happened?
qps recovery after 15min
![BFpsi8VuVc](https://user-images.githubusercontent.com/84712107/191911259-8db288aa-2f8b-4272-bfe1-c0e8605e3103.jpg)
![img_v2_d81eb44c-c0cc-41e7-a398-3a82398225fg](https://user-images.githubusercontent.com/84712107/191911273-7cf33016-ba0f-437b-926c-c147344ec3e9.jpg)

**Comment by tonyxuqqi** [comment]
it's fixed by polished slow score/slow trend
