### ISSUE TITLE
upgrade the dependencies with security vulnerabilities

### ISSUE THREAD

**Issue by hihihuhu** [tikv/tikv#13549]
### Is your feature request related to a problem? Please describe:
there are security vulnerabilities detected by trivy blocking us from using tidb
```
trivy -q image -s HIGH,CRITICAL -f json pingcap/tikv:v6.1.0 | jq ".Results[] | .Vulnerabilities[] | .PkgName" | sort | uniq
"bind-libs"
"bind-tools"
"zlib"
```
### Describe the feature you'd like:
fix all high and critical level security concerns

**Comment by tonyxuqqi** [comment]
It seems to me the vulnerabilities come from the image itself, not the TiKV repo's dependent rust components.

**Comment by lianan-352889950** [comment]
We will solve the high-risk and serious vulnerabilities in the base image in the new 6.1.2 version. As for the vulnerabilities of third-party dependent libraries, we will try our best to fix the high-risk or serious vulnerabilities in the directly referenced libraries.

**Comment by zhangjinpeng1987** [comment]
@lianan-352889950 can we close this issue now?

**Comment by TopScrew** [comment]
The latest scan result for pingcap/tikv@6.5.1 is as follows:
trivy -q image -s HIGH,CRITICAL -f json pingcap/tikv:v6.5.1 | jq ".Results[] | .Vulnerabilities[] | .PkgName" | sort | uniq
"libcom_err"

For the image layer with ARM architecture, all severe and high-risk vulnerabilities have been fixed. The remaining libcom_err vulnerability has not been matched in the Snyk vulnerability database and is considered a false positive for the Alpine system.
