### ISSUE TITLE
Batch snapshot is unsound

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#13553]
### What version of TiKV are you using?
Nightly

### What operating system and CPU are you using?
Doesn't matter

### Steps to reproduce
Concurrent read and conf change may read incomplete data.

### What did happened?
https://github.com/tikv/tikv/pull/7878 introduces batch snapshot across regions. It reorders the snapshot operation and lease check operation, so snapshot is taken after checking lease. It's possible that after checking the lease and before snapshot is taken, the region is removed by conf change. So the snapshot may not contain the complete data.

To solve the problems, we need to make sure snapshot is taken before lease check.

/cc @hicqu

**Comment by gengliqi** [comment]
The second case doesn't exist since the code here has prevented this case. https://github.com/tikv/tikv/pull/7878/files#diff-74e59050058f72120a567a8cbde826478fcc051584b8bafed527d7de74e04fb6R434-R441

**Comment by BusyJay** [comment]
Got it. Then there is only one problem left.

**Comment by MimeLyc** [comment]
update
