### ISSUE TITLE
flashback is incompatible with tiflash

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#13612]
### What version of TiKV are you using?
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   5f978e518901cb92affaa6d2a64b776e3943a27b
Git Commit Branch: flashback_2pc
UTC Build Time:    2022-10-12 11:50:41
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)

### Steps to reproduce
1. set replica with table
2. execute flashback cluster ddl

### What did you expect?
1. ddl execute successfully
2. data is consistent in tikv and tiflash

### What did happened?
tiflash nodes down after ddl 
tikv added a new raft command, need tiflash add process to support it

**Comment by JmPotato** [comment]
This will be fixed once https://github.com/tikv/tikv/pull/13601 and https://github.com/tikv/tikv/pull/13609 are merged, and the TiFlash proxy is updated to the latest version.

**Comment by seiya-annie** [comment]
fixed
