### ISSUE TITLE
Backup txn kv data via br

### ISSUE THREAD

**Issue by 3pointer** [tikv/tikv#13614]
### Is your feature request related to a problem? Please describe:

We can backup `raw` API data via `br` for `tikv` cluster. but for `txn` API data. we don't have such way to do so. and this will decrease the cluster operation and maintenance capabilities of data loss.

### Describe the feature you'd like:

Backup `txn` API data via `br`.

### Describe alternatives you've considered:

~~One easy way to implement this feature is building backup `txn` kv capabilities on existing `raw` kv backup.
The main process is~~
- [ ] ~~implement backup `txn` command in `br`.~~
- [ ] ~~Get global `txn` snapshot timestamp from `pd` and stop GC moving forward during backup.~~
- [ ] ~~Build `EntryScanner` to scan valid `txn` kv data in `tikv`.~~
- [ ] ~~implement restore command in `br`.~~

~~In addition, we need to backup/restore twice internally if we choose this way. because `txn` data has two `CFs`  and `raw` kv backup only support backup one `CF` at a time.~~

After discussed we found another easy way to implement this feature in `br`. see https://github.com/pingcap/tidb/issues/38506

**Comment by siddontang** [comment]
@3pointer no need to control GC? how to guarantee the transaction consistency?

**Comment by 3pointer** [comment]
> @3pointer no need to control GC? how to guarantee the transaction consistency?

Yes, we should control GC during backup. already update the main process.

**Comment by siddontang** [comment]
> In addition, we need to backup/restore twice internally if we choose this way. because txn data has two CFs and raw kv backup only support backup one CF at a time.

@3pointer for TiDB backup, do we also do twice internally? If we use a similar way like backup all databases for TiDB, will it be easier?

**Comment by 3pointer** [comment]
> > In addition, we need to backup/restore twice internally if we choose this way. because txn data has two CFs and raw kv backup only support backup one CF at a time.
> 
> @3pointer for TiDB backup, do we also do twice internally? If we use a similar way like backup all databases for TiDB, will it be easier?

For TiDB backup. we can use `TxnEntryScanner` to get the `txn` data. it only need scan once.
Actually they are different ways. It's hard to see which one is easy. Let me make it more clear.

- Reuse TiDB backup
The key point is reuse [`backup`](https://github.com/tikv/tikv/blob/master/components/backup/src/endpoint.rs#L290) function in TiKV. if choose this way. we may not need to change the code in `TiKV`, but we need to implement the compatible logic in `br`. current `br` TiDB backup meta file depends on `tableInfo` and restore also depends on some `table` logic.

- Reuse Raw backup
The key point is reuse [`backup_raw`](https://github.com/tikv/tikv/blob/master/components/backup/src/endpoint.rs#L447) . if we choose this. we need a few logic in TiKV like this issue described above. but we can reuse the most logic in `br` side. For restore, just add a new `txn` subcommand is enough.

**Comment by 3pointer** [comment]
From my intuition add a new `txn` subcommand and reuse `backup` in `TiKV` is a good choice.

**Comment by siddontang** [comment]
> Reuse Raw backup

@3pointer seem we also need to backup Lock CF, right?

**Comment by 3pointer** [comment]
> > Reuse Raw backup
> 
> @3pointer seem we also need to backup Lock CF, right?

I don't think we need to backup Lock CF. if the Lock CF data exists in a snapshot. it can be removed eventually in whatever situation.

**Comment by 3pointer** [comment]
> From my intuition add a new `txn` subcommand and reuse `backup`(or rename it to `backup_txn`) in `TiKV` is a good choice.

After discussed with @siddontang. we both think the easiest way to implement this feature is reuse tidb backup. and I file an issue in tidb repo. https://github.com/pingcap/tidb/issues/38506

So I think we can close this issue for now and tracing this issue in tidb repo.
