### ISSUE TITLE
after flashback, gc work normal but storage available size is not freed

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#13620]
### What version of TiKV are you using?
[root@10 ~]# /home/tidb/tidb-deploy/tikv-2360/bin/tikv-server -V
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   5f978e518901cb92affaa6d2a64b776e3943a27b
Git Commit Branch: flashback_2pc
UTC Build Time:    2022-10-12 11:50:41
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           release
[root@10 ~]# 

### Steps to reproduce
1. run update workload for about 1 hour with 1.5k tps
2. set gc life time to 2h
3. execute flashback
4. change gc life time to 10 minutes

### What did you expect?
storage available size is freed normally

### What did happened?
storage available size is not freed

**Comment by tonyxuqqi** [comment]
cc @JmPotato

**Comment by JmPotato** [comment]
After some verification, we found that the data during this test was already in an inconsistent state before running the flashback. Will close this issue and then start a new one.

![](https://github.com/tikv/tikv/assets/1446531/58a54bed-1b4b-4233-ac36-f8d4c61630cd)
