### ISSUE TITLE
Send heartbeat to PD as soon as the service is ready

### ISSUE THREAD

**Issue by cosven** [tikv/tikv#13627]
**Problem**
After a tikv instance starts, it will wait for 10s (pd_heartbeat_tick_interval) before sending the first heartbeat to pd. PD treats the store as disconnected before receiving its heartbeat, and PD will not do scheduling work for the store.

For example, in the rolling restart scenario , the service is ready after a tikv restart, but no leader will be migrated within 10s. But in fact, at this time, it can already accept leaders.

**Solution**
Sending a heartbeat to the PD immediately after the service is ready,  which is more reasonable.

/assign @cosven

**Comment by cosven** [comment]
This bug causes the rolling upgrade to take more time.

/severity minor

**Comment by tonyxuqqi** [comment]
It could have side effect that the TiKV is not ready yet but write traffic comes to that TiKV.
