### ISSUE TITLE
PITR checkpoint lag might >5min during/right after single AZ disaster happens

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#13622]
### What version of TiKV are you using?
/ # /tikv-server -V
TiKV
Release Version: 6.2.0-alpha
Edition: Community
Git Commit Hash: https://github.com/tikv/tikv/commit/8b915d3b4894c01c843f452ae5a6a579e4b4b208
Git Commit Branch: heads/refs/tags/v6.3.0
UTC Build Time: 2022-09-22 07:38:02
Rust Version: rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)

### What operating system and CPU are you using?
K8s 

### Steps to reproduce
1. Deploy cluster with 6 TiKV in Azure, each AZ has 2 TiKV, isolation-level configured to by "zone"
2. Start log backup task
3. Inject single AZ failure (injects failure to PD/TiDB/TiKV in a single AZ)
4. Check log backup checkpoint lag

### What did you expect?
When single AZ disaster happens, TiDB can still provide services though it might be downgraded.  PITR checkpoint lag should still be less than 5 minutes.

### What did happened?
From our testing, QPS dropped from 30k to 8.82k, and then stabilized at 13k within 1 minute
![image](https://user-images.githubusercontent.com/7403864/196170886-1d14b100-7454-404b-afc1-c7f45aa16846.png)

During az down fault, checkpoint delay may exceed 5 minutes 
![image](https://user-images.githubusercontent.com/7403864/196171167-2b5597fd-6883-4b59-9195-9f93a8e466e2.png)

22:02 error recover， checkpoint lag could still be > 5 min within 5 minutes after recovery.
![image](https://user-images.githubusercontent.com/7403864/196171526-0c100b6d-f8f8-4bec-92ca-883b0b153c79.png)

After 5 minutes of fault recovery, the checkpoint flag drops to less than 5 minutes, about 3-4 minutes：
![image](https://user-images.githubusercontent.com/7403864/196171830-acdccf5b-bd4b-4617-ad1e-4da5e742b6a6.png)

**Comment by tonyxuqqi** [comment]
Close it for now until it's reproed. With recent enhancement on slow score, it should be fixed.
