### ISSUE TITLE
minSafeTS not change for about 10 minutes

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#13675]
### What version of TiKV are you using?
[root@localhost ~]# /data1/tidb-deploy/tikv-2360/bin/tikv-server -V
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   469eab2cfd0ffe1f6ddb6ab261322488f9880bf8
Git Commit Branch: heads/refs/tags/v6.4.0-alpha
UTC Build Time:    2022-10-25 14:26:09
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
[root@localhost ~]#

### Steps to reproduce
1. install tidb cluster with tiflash, and start pitr task
2. set tiflash replica for user_data1 table
3. flashback to the time before set replica
[msts_not_change.gz](https://github.com/tikv/tikv/files/9867744/msts_not_change.gz)

### What did you expect?
flashback fail for has other ddl in the time range 
### What did happened?
```code
ySQL [flashback2]> select now();
+---------------------+
| now()        |
+---------------------+
| 2022-10-26 14:06:15 |
+---------------------+
1 row in set (0.00 sec)

MySQL [flashback2]> flashback cluster to timestamp '2022-10-26 13:53:46';
ERROR 1105 (HY000): cannot set flashback timestamp to too close to present time
```

**Comment by Defined2014** [comment]
version: v6.4.0-alpha-nightly-20221102
```
tiup playground nightly --tiflash 0 --db 1 --kv 3 --without-monitor
```
Use command above and start a cluster without any manipulation, then do flashback, check minSafeTS failed, TiDB get minSafeTS equals to 0.
