### ISSUE TITLE
Flashback process is blocked for compaction pending too much data

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#13704]
### What version of TiKV are you using?
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   8aa672146661bc719d05b03fc8f40d6bb1b8d24f
Git Commit Branch: HEAD
UTC Build Time:    2022-10-31 08:46:23

### Steps to reproduce
1. start pitr task
2. run workload 10 minutes
3. pause pitr task
4. flashback to the time before pitr task start
5. during flashback restart tikv/tidb/pd/tiflash

### What did you expect?
flashback execute successfully
data is consistent 

### What did happened?
flashback is hang for : 2022-10-31 22:38:47 (GMT+8)TiDB [172.16.6.47:4000](http://172.16.6.47:4000/)[cluster.go:360] ["[ddl] send flashback request"] [region_id=4046518] [start_key=748000000000000014] [end_key=748000000000000019]

check by dev, too much compaction pending

**Comment by JmPotato** [comment]
This could happen when a key is the only key that needs to be flashbacked in a batch, which will make the read phase fall into a dead loop. Introduced in #13695, not in the master.
