### ISSUE TITLE
Should we update `counter`  when the message is timeout?

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#13755]
## Question
The master version
[https://github.com/tikv/tikv/blob/8eaa805dc440dc6c056547c5ebb3989c56dde0c3/components/tikv_util/src/worker/pool.rs#L486-L498](https://github.com/tikv/tikv/blob/8eaa805dc440dc6c056547c5ebb3989c56dde0c3/components/tikv_util/src/worker/pool.rs#L486-L498)

**Comment by sticnarf** [comment]
I don't think so.

The "timeout" works like a ticker. It is usually used to run something at intervals.

It is not the timeout of a specific task. So, the counter needn't be changed.
