### ISSUE TITLE
Make Flashback compatible with CDC

### ISSUE THREAD

**Issue by JmPotato** [tikv/tikv#13787]
Ref #13303.

Since the flashback feature bypasses the standard transaction writing progress, so it basically has two incompatible critical points with the CDC.

1. The Percolator transaction rules are not strictly followed, so CDC will have problems capturing data changes generated by the flashback process.
2. The key cleaning work makes the Resolved TS advance unexpectedly while the flashback data changes are still pushed to the CDC.

To make flashback compatible with CDC, there are several places we need to modify.

- Flashback transaction modification results are basically the same as a 1PC request. So we can make it become or look like a 1PC transaction to make CDC handle it naturally without any other development.
- Same as the 1PC, we need to maintain the memory locks in `ConcurrencyManager` correctly to make sure the Resolved TS won't advance during the flashback progress.

By fixing these two problems, the compatibility issue between Flashback and CDC should be addressed without too many changes.

**Comment by HuSharp** [comment]
if the memory lock is destroyed, consideration must be given to preventing resolved ts.
