### ISSUE TITLE
TiKV Max Resolved TS stop to advance when restore / import data into tikv

### ISSUE THREAD

**Issue by fengou1** [tikv/tikv#13838]
### What version of TiKV are you using?
nightly build-2022, 11, 23

### What operating system and CPU are you using?
centos

### Steps to reproduce
1. create a tidb cluster
2. restore data into cluster

### What did you expect?
max resolved ts shall advance as resolved_ts did

### What did happened?
max resolved ts stop to advance
<img width="688" alt="image" src="https://user-images.githubusercontent.com/85682690/203497837-472a540a-503d-4795-aa8f-4a269c834255.png">

it impact backup and restore, auto_dr_sync etc, those using max resolved ts function.

**Comment by jebter** [comment]
by disign：https://docs.pingcap.com/tidb/dev/tidb-lightning-physical-import-mode#tips-for-using-with-other-components

**Comment by fubinzh** [comment]
After the error happens, new created cdc changefeed  is not able to advance. Escalate it to major.

**Comment by tonyxuqqi** [comment]
cc @BornChanger

**Comment by BornChanger** [comment]
@fubinzh is the problem still there now?

**Comment by fubinzh** [comment]
@BornChanger I didn't see this issue recently.
