### ISSUE TITLE
IPv6 support: tikv should listen on IPv6 instead of IPv4， which cause br restore failed.

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#13847]
### Steps to reproduce

build k8s cluster with ipv6 and ipv4 enabled both, and set ipv6 as default network.

### What did happened?
➜  ~ kubectl -n user-py get pod
NAME                               READY   STATUS    RESTARTS   AGE
basic-discovery-6dd445bb49-6brdn   1/1     Running   0          43h
basic-pd-0                         1/1     Running   0          43h
basic-tidb-0                       2/2     Running   0          43h
basic-tikv-0                       1/1     Running   0          42h
benchtoolset-0                     1/1     Running   0          33m
br-0                               1/1     Running   0          5m48s
➜  ~ kubectl -n user-py exec basic-tikv-0 -c tikv -it -- sh
/ # netstat -lt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:20180           0.0.0.0:*               LISTEN
tcp        0      0 :::20160                :::*                    LISTEN
tcp        0      0 :::20160                :::*                    LISTEN
tcp        0      0 :::20160                :::*                    LISTEN
tcp        0      0 :::20160                :::*                    LISTEN
tcp        0      0 :::20160                :::*                    LISTEN

/br restore full --send-credentials-to-tikv=true --pd http://basic-pd:2379 --storage s3://benchmark/tpcc-1000-4.0 --s3.endpoin
t  xxxxx
Detail BR log in /tmp/br.log.2022-11-25T07.47.17Z
[2022/11/25 07:47:25.458 +00:00] [INFO] [collector.go:69] ["Full Restore failed summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0]
Error: Get "http://basic-tikv-0.basic-tikv-peer.user-py.svc:20180/config": dial tcp [fd00:100:96:1::b]:20180: connect: connection refused; Get "http://basic-tikv-0.basic-tikv-peer.user-py.svc:20180/config": dial tcp [fd00:100:96:1::b]:20180: connect: connection refused;

**Comment by mayjiang0203** [comment]
1 root      0:16 /tikv-server --pd=http://basic-pd:2379 --advertise-addr=basic-tikv-0.basic-tikv-peer.user-py.svc:20160 --addr=0.0.0.0:20160 --status-addr=0.0.0.0:20180 --advertise-status-addr=basic-tikv-0.basic-tikv-peer.user-py.svc:20180 --data-dir=/var/lib/tikv --capacity=0 --config=/etc/tikv/tikv.toml

seems caused by command line parameter setting.

**Comment by mayjiang0203** [comment]
https://github.com/pingcap/tidb-operator/issues/4790 track it in operator repo.

**Comment by mayjiang0203** [comment]
Reopen it, for it is better if we can fix it in TiKV instead of in operator.

**Comment by tonyxuqqi** [comment]
0.0.0.0 Is ipv4 only in most of implementation. For ipv6, it should use :: instead.
