### ISSUE TITLE
Patch backtrace-rs to increase MAPPINGS_CACHE_SIZE

### ISSUE THREAD

**Issue by hehechen** [tikv/tikv#14025]
### Is your feature request related to a problem? Please describe:

https://github.com/pingcap/tiflash/issues/6347.
Thehttps://github.com/pingcap/tiflash/issues/6347#issuecomment-1333038382 is that the backtrace of DWARF is deeper than that of frame pointer. So DWARF need to resolve more shared libraries when resolving symbols. But [the capacity of lib cache in backtrace-rs is only 4](https://github.com/rust-lang/backtrace-rs/blob/5be2e8ba9cf6e391c5fa45219fc091b4075eb6be/src/symbolize/gimli.rs#L55), so cache miss will occurs frequently in DWARF scenarios.
I created a PR to https://github.com/rust-lang/backtrace-rs/pull/503, but it has not been discussed and merged. I think we can patch [backtrace-rs](https://github.com/rust-lang/backtrace-rs) and modify MAPPINGS_CACHE_SIZE to 10.
### Describe the feature you'd like:

Patch [backtrace-rs](https://github.com/rust-lang/backtrace-rs) and modify MAPPINGS_CACHE_SIZE to 10.
### Describe alternatives you've considered:

Merge https://github.com/rust-lang/backtrace-rs/pull/503.
### Teachability, Documentation, Adoption, Migration Strategy:

Not related.

**Comment by sticnarf** [comment]
TiKV statically links most of its dependencies, so I think the default mapping cache size of backtrace-rs is enough for TiKV.

You can patch it only in tidb-engine-ext first.
