### ISSUE TITLE
【witness】enable witness and pitr，inject one tikv io delay 200ms last for 5m，pitr task became to paused

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14137]
### What version of TiKV are you using?
sh-5.1# ./tikv-server -V
TiKV 
Release Version:   6.6.0-alpha
Edition:           Community
Git Commit Hash:   9c0df6d68c72d30021b36d24275fdceca9864235
Git Commit Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time:    2023-02-01 08:37:19
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

./br -V
 Release Version: v6.6.0-alpha
Git Commit Hash: d4e2b2eac1c93cef247ebb7d0bdff83474eda94a
Git Branch: heads/refs/tags/v6.6.0-alpha
Go Version: go1.19.5
UTC Build Time: 2023

### What operating system and CPU are you using?
8c/16GB

### Steps to reproduce
1、enable witness 
2、br restore data
3、enable pitr
4、run workload 
 ["Start remote command"] [cmd="go-tpc tpcc run -D tpcc --host tc-tidb.testbed-glh-c7g8n -P4000 --warehouses 1000 -T 10 --ignore-error '2013,1213,1105,1205,8022,8028,9004,9007,1062' --password ''"] [nodename=benchtoolset]
5、inject chaos
     one tikv io delay 200ms last for 5m

### What did you expect?
pitr task can run normally

### What did happened?
testbed：testbed-glh-c7g8n
logs：http://minio.pingcap.net:38888/buckets/test-infra-testground/browse/YXJjaGl2ZS90ZXN0YmVkLWdsaC1jN2c4bi8=
when inject one tikv io delay，pitr task became to paused and can not recover automatically
![image](https://user-images.githubusercontent.com/84712107/216565589-e17bc204-7152-4f8e-b1d9-d558548a1cbf.png)

sh-5.1# /br log status --pd="tc-pd.testbed-glh-c7g8n.svc:2379"
Detail BR log in /tmp/br.log.2023-02-03T09.18.44Z 
● Total 1 Tasks.
> #1 <
                    name: pitr
                  status: ○ ERROR
                   start: 2023-02-03 07:53:26.333 +0000
                     end: 2090-11-18 14:07:45.624 +0000
                 storage: s3://tmp/log-hatest
             speed(est.): 0.00 ops/s
      checkpoint[global]: 2023-02-03 08:27:54.183 +0000; gap=50m50s
          error[store=5]: KV:LogBackup:RaftReq
error-happen-at[store=5]: 2023-02-03 08:31:55.816 +0000; gap=46m48s
  error-message[store=5]: retry time exceeds: and error and error failed to ge
                          t initial snapshot: failed to get the snapshot (regi
                          on_id = 27955): Error during requesting raftstore: m
                          essage: "peer is a witness of region 27955" is_witne
                          ss { region_id: 27955 }: failed to get initial snaps
                          hot: failed to get the snapshot (region_id = 27955):
                           Error during requesting raftstore: message: "peer i
                          s a witness of region 27955" is_witness { region_id:
                           27955 }: failed to get initial snapshot: failed to 
                          get the snapshot (region_id = 27955): Error during r
                          equesting raftstore: message: "peer is not leader fo
                          r region 27955, leader may Some(id: 27956 store_id: 
                          16816)" not_leader { region_id: 27955 leader { id: 2
                          7956 store_id: 16816 } }
sh-5.1#

**Comment by joccau** [comment]
![image](https://user-images.githubusercontent.com/57036248/216882538-eaf04a58-f1f5-48e7-b479-944eec704aeb.png)

**Comment by Lily2025** [comment]
remove-label may-affects-4.0
/remove-label may-affects-5.0
/remove-label may-affects-5.1
/remove-label may-affects-5.2
/remove-label may-affects-5.3
/remove-label may-affects-5.4
/remove-label may-affects-6.0
/remove-label may-affects-6.1
/remove-label may-affects-6.2
/remove-label may-affects-6.3
/remove-label may-affects-6.4
/remove-label may-affects-6.5

**Comment by ethercflow** [comment]
![image](https://user-images.githubusercontent.com/38067786/216964261-8143f5af-c2f2-4400-9ec9-2de802b9578b.png)

**Comment by ethercflow** [comment]
Fixed by https://github.com/tikv/pd/pull/5918, and tested.
