### ISSUE TITLE
[dynamic regions] region is not split for hot write

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#14135]
## Bug Report

When loading TPCC into 6 nodes, only three of them have heavy write flow. That's because hotspot is not split. We have develop bucket split in the past, what needs to do now is always enable bucket for dynamic regions.

**Comment by bufferflies** [comment]
yes, the hot region is too big and aggregate on one or two regions.  It needs to be splited by `split-buckets ` if the `hot-region-schedule` scheduled region is too big.
