### ISSUE TITLE
【witness】enable witness，scale in one tikv can not successfully due to the leaders and regions can not transfer successfully

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14144]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.6.0-alpha
Edition:           Community
Git Commit Hash:   d1d29203e6a93b05dd435ea27a9b39fb30b23f41
Git Commit Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time:    2023-02-02 11:57:11
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-02-03T18:14:46.483Z	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
2023-02-03T18:14:46.623Z	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
 Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: 7fb70d1e349b8ddae6443978e3cee069fef4ef46
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time:  2023-02-02 11:41:40

### What operating system and CPU are you using?
8core、16GB

### Steps to reproduce
1、enable witness
2、br restore data
3、run workload
4、scale out one tikv successfully
5、scale in one tikv

### What did you expect?
scale in one tikv successfully

### What did happened?
scale in one tikv can not scale in successfully due to the leaders and regions can not transfer successfully
test plan：
https://tcms.pingcap.net/dashboard/executions/plan/1471283
clinic：
https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7195789877722374550?from=1675400361&to=1675482613
![image](https://user-images.githubusercontent.com/84712107/216880780-e851b595-1f4f-417f-b273-2cd190848256.png)
![image](https://user-images.githubusercontent.com/84712107/216881018-632ef2e7-1ce6-41c7-8ee0-166de75f9df9.png)

**Comment by ethercflow** [comment]
fixed in https://github.com/tikv/pd/pull/5940
