### ISSUE TITLE
[Dynamic Regions] store is not balanced during the scale-out

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14178]
### What version of TiKV are you using?

nightly
### What did you expect?
During the scale-out from 3 tikv nodes to 4 tikv nodes, the data movement should come from 3 tikv nodes. 
### What did happened?
 It turned out all the data movement are from one existing tikv. 
 
<img width="814" alt="Screen Shot 2023-02-07 at 11 58 22 AM" src="https://user-images.githubusercontent.com/9442422/217352802-b16ce094-e56f-456c-8457-c07051b6ff03.png">
<img width="809" alt="Screen Shot 2023-02-07 at 12 04 11 PM" src="https://user-images.githubusercontent.com/9442422/217353049-5caf227a-a534-4df4-9d11-409cf657ccfa.png">

**Comment by tonyxuqqi** [comment]
@ bufferflies

**Comment by bufferflies** [comment]
The root cause is that the available doesn't decrease after  move out some region from it, so it's score is always highest.
ref https://github.com/tikv/tikv/issues/14179.

**Comment by tonyxuqqi** [comment]
Not repro-ed any more in latest version.
