### ISSUE TITLE
[Dynamic Regions] PD does not schedule region-balance when there's moderate read-write traffic 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14214]
### What version of TiKV are you using?

release-6.6
### Steps to reproduce

1) Sysbench prepare 150GB data per TiKV
2) scale-out a TiKV on a 3 TiKV cluster , wait for 5 minutes
3)  run Sysbench read-write workload
### What did you expect?
The region balance speed is similar with or without sysbench workload
### What did happened?
The region balance operator is not scheduled when there's moderate read-write workload. 

<img width="548" alt="Screen Shot 2023-02-13 at 12 11 04 PM" src="https://user-images.githubusercontent.com/9442422/218564577-ae34dca2-1c5d-484d-b239-b72fda1b6439.png">
<img width="804" alt="Screen Shot 2023-02-13 at 12 11 46 PM" src="https://user-images.githubusercontent.com/9442422/218564582-61bd3d77-6663-4a58-901d-c93b44beb1af.png">

**Comment by bufferflies** [comment]
The root cause is that the most regions is hot regions,  so `balance-region-scheduler ` cann't pick out the scheduled region.
