### ISSUE TITLE
pitr rpo is more than 5m last for 9min after inject pdleader network partition which trigger pd changed leader

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14241]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.6.0
Edition:           Community
Git Commit Hash:   d7847d1be1a5176652dda0f182527615b5c22016
Git Commit Branch: heads/refs/tags/v6.6.0
UTC Build Time:    2023-02-12 08:08:03
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-02-17T03:25:41.195Z

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
https://tcms.pingcap.net/dashboard/executions/plan/1562736
ha-pdleader-to-all-network-partition-last-for-10m
the time of pd leader changed :  2023-02-17 13:06

### What did you expect?
pitr rpo should be less than 5m

### What did happened?
pitr rpo is more than 5m last for 9min after inject pdleader network partition which trigger pd changed leader
![072042a8-a98b-4310-a5b5-4c5b860f74ec](https://user-images.githubusercontent.com/84712107/219590334-c5d8a860-6114-4c29-8d44-8e975f5b7f8b.jpeg)

![img_v2_8ef80107-4eac-48f4-b1ac-6eb894a0388g](https://user-images.githubusercontent.com/84712107/219590373-ba1dd71a-16cf-4e59-997d-80cc09d7afb7.jpg)

**Comment by Lily2025** [comment]
cc @joccau

**Comment by tonyxuqqi** [comment]
@3pointer  PTAL

**Comment by BornChanger** [comment]
@Lily2025 confirmed that that issue does not occur now.

**Comment by Lily2025** [comment]
fixed
