### ISSUE TITLE
Well-defined behaviors of `WakeUpModeForceLock` accompanied with other special usages in pessimistic locks

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#14293]
This document discusses and specifies how TiKV should handle pessimistic lock requests that has `WakeUpModeForceLock` and other special modes enabled simultaneously. The expected behavior in these cases is unclear or not supported before.  We'll have strictly defined behaviors in these cases upon this document.

When there's no WriteConflict, the behavior of using and not using `WakeUpModeForceLock` should be the same. So we only discuss how it should behave **when WriteConflict occurs**.

## `should_not_exist` (insert)

* If the key doesn't exist: Lock the key as it's very likely that we will still insert this key after statement-retry.
* If the key already exists: There are several choices:
    * ~~**Lock the key**. Provides stable latency for some rare cases. But it will be unlikely that the statement still need to lock this key after statement-retry (the most likely case is that the statement meets duplicate entry error after retrying). Locking the key might be a waste.~~
    * **Do not lock the key and report `WriteConflict` error**. Avoids keeping the lock for nonsense. But there exists cases that will still cause high tail latency.

Example case:

```sql
-- txn1
begin;
insert into t values (1 /* primary key */);
commit;

-- txn2
begin;
delete from t where id = 1;
commit;
```

## `lock_if_exists`

* If the key exists: Lock the key as normal.
* If the key doesn't exist: Again, there are several choices:
    * **Do not lock the key and return `WriteConflict` error**. This makes it behaves like if `WakeUpModeForceLock` is not used, thus it's theoretically possible to lead to high tail latency in some cases.
    * ~~**Do not lock the key and return successful response with `locked_with_conflict`**. Semantically, this is literally the simplest combination of the semantics of `lock_if_exists` and `WakeUpModeForceLock`. However it leads to extra work to record the keys' states in client-go, which may make the maintainability more terrible. Not suggested.~~
    * ~~**Lock the key**. This causes the key that don't need to be lock at all be locked.~~

Personally I prefer returning `WriteConflict` for both of the above options, since I think it simplifies the problem and the cases that it leads to high-tail-latency problem should be rare. I want to see if there are other opinions.

**Comment by MyonKeminta** [comment]
@ekexium @cfzjywxk PTAL

**Comment by ekexium** [comment]
My opinion is to choose the most simple solution for now, since we don't see any necessity to make it more complex.
If there is one in the future, then the concrete scenarios can guide us make the decision.

**Comment by cfzjywxk** [comment]
+1 for simple solutions by now, the above cases are rare and at least the `WakeUpModeForceLock` would not make it worse.
Our goal of `WakeUpModeForceLock` is to optimize the most commonly used case that the contention happens on a single row or key.

**Comment by cfzjywxk** [comment]
BTW I remember when RC is used with `lock_if_exists`, if the key does not exist no `WriteConflict` error would be returned.
