### ISSUE TITLE
[Dynamic Regions]After using MultiRocks DB, the store size of TiKV surged unexpectedly, which is not in line with expectations

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#14301]
version 6.6.0 
workload : tpcc 200 threads  6h
we found that the tikv store size surged unexpectedly with the  MultiRocks DB,is not in line with expectations 
clinic :https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7204975639031210766
![image](https://user-images.githubusercontent.com/85105033/221763820-81951d70-7838-4e6c-8a35-8cd8f8275362.png)

**Comment by tonyxuqqi** [comment]
It's not reproed anymore.
