### ISSUE TITLE
[Dynamic Regions] Multi-RocksDB's data amplification much than than single-rocksdb

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#14307]
### What version of TiKV are you using?

6.6

### Steps to reproduce

tpcc 1k warehouse
clinic https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7204975639031210766 
![image](https://user-images.githubusercontent.com/7677963/222033854-14f5e82e-54fa-47c4-97f0-55fd116dd42c.png)

![image](https://user-images.githubusercontent.com/7677963/222033974-b0013949-a931-4085-964c-e04b632fb39e.png)

**Comment by cscetbon** [comment]
@lilinghai how do you actually test/enable Multi-RocksDB in TiKV ? I don't see parameters in the configuration 😕

**Comment by lilinghai** [comment]
> @lilinghai how do you actually test/enable Multi-RocksDB in TiKV ? I don't see parameters in the configuration 😕
you can set config of tikv wiht storage.engine="partitioned-raft-kv" in a new cluster.  https://docs.pingcap.com/tidb/dev/tikv-configuration-file#engine-new-in-v660

**Comment by tonyxuqqi** [comment]
dup with #14349
