### ISSUE TITLE
[Dynamic Regions] An unavailable region caused sysbench to panic with error code 9005 

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#14314]
version: nightly (master)
workload: sysbench oltp_insert
Sysbench panicked while running oltp_insert due to an unavailable region, which has not been encountered with v6.6.
![image](https://user-images.githubusercontent.com/85105033/222093683-47b2b092-9d40-4579-936c-f7934e2ebd6e.png)

**Comment by shaoxiqian** [comment]
we also meet the error "SQL error, errno = 8027, state = 'HY000': Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV"
![image](https://user-images.githubusercontent.com/85105033/222336751-92be249e-8f6f-44b3-8e09-c9a01ecfc395.png)

**Comment by tonyxuqqi** [comment]
It's  not reproed anymore.  Should be fixed.
