### ISSUE TITLE
[Dynamic Regions]  dynamic change on max-compactions, write-buffer-limit  do not work 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14320]
### What version of TiKV are you using?

nightly
### Steps to reproduce

MySQL [(none)]> set config tikv `rocksdb.write-buffer-limit `='20GB';
Query OK, 0 rows affected, 3 warnings (0.00 sec)

MySQL [(none)]> set config tikv `rocksdb.writecf.max-compactions`=3;
Query OK, 0 rows affected, 3 warnings (0.01 sec)
### What did you expect?
The update succeeds.
### What did happened?
The update does not pass to TiKV. There's no "rocksdb config changed" log.

**Comment by tonyxuqqi** [comment]
write-buffer-limit is quite critical parameter in performance tuning. It would be great to make it dynamic changeable. 
@SpadeA-Tang

**Comment by SpadeA-Tang** [comment]
They have been implemented by https://github.com/tikv/tikv/pull/14565 and https://github.com/tikv/tikv/pull/15425  respectively.
