### ISSUE TITLE
[Dynamic Regions] GC did not work properly with partitioned-raft-kv

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#14339]
### What version of TiKV are you using?
nightly 
git_hash:142e4b4a49109b83b4e034345622f02808415a6e

### Steps to reproduce
go-tpc 1k warehouses 6h 

### What did you expect?
gc work properly
no error during tpcc running
### What did happened?
The workload started at 3:42 AM on March 3rd. The metrics showed that gc did not work from 4:08 AM.
![image](https://user-images.githubusercontent.com/85105033/222700661-991636a5-b0a1-40f3-98fd-124a20959aa9.png)
And from the log we can also identify the GC didn't work properly from 4:08 AM.
![img_v2_4f338562-1bc9-4872-b8ea-9bf9d491351g](https://user-images.githubusercontent.com/85105033/222701296-79fcc530-a556-4801-8222-2d15d9da06fc.jpg)
The load lasted for 6 hours, starting from 3:42 AM and should have ended around 9:42 AM. However, according to the monitoring data, the load ended at 8:46 AM . According to the output from the TPCC client, errors began to occur at 8:46 AM.
![image](https://user-images.githubusercontent.com/85105033/222703908-617b93be-63e2-43c1-a69f-5d706f2982f0.png)
![img_v2_6f28f6a6-0fbb-4fbe-941a-e4ad13a7438g](https://user-images.githubusercontent.com/85105033/222703982-73392025-cae5-477a-94d0-a082b734058c.jpg)

**Comment by tonyxuqqi** [comment]
Fixed
