### ISSUE TITLE
[Dynamic Regions] Bucket flow report triggers much faster region split than before. 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14333]
### What version of TiKV are you using?

nightly  commit hash# 6a906dae15f62be7df7c707c43550e25c0599a9a
### Steps to reproduce

Enable partitioned-raft-kv and run sysbench insert
### What did you expect?
Region split will be stable and slow
### What did happened?
Region split is about 100 per minutes. And many tikv requests failed and grpc latency is very high. 

![Feishu20230302-215556](https://user-images.githubusercontent.com/9442422/222642698-0343575b-d3c0-466d-a1f7-7084f421a6bd.jpeg)
![Feishu20230302-215547](https://user-images.githubusercontent.com/9442422/222642699-a26eb939-ebae-4bc1-801d-dc675f228ee0.jpeg)

**Comment by bufferflies** [comment]
In past, the `split-bukcet-scheduler` split region according the top buckets not the hot regions . I will optimaze the pick strategy order by the in need regions like the scheduled hot regions .
