### ISSUE TITLE
[Dynamic Regions] tikv oom due to memtable is highly used

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14356]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.7.0-alpha
Edition:           Community
Git Commit Hash:   8bfa12dea2d5bd0918b35e5ae041676aeeee77ab
Git Commit Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:    2023-03-05 11:40:05
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-03-06T07:00:46.903Z	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129

### What operating system and CPU are you using?
8c/32G

### Steps to reproduce
https://tcms.pingcap.net/dashboard/executions/plan/1654853
after case ha_tikv(random)_io_delay(10ms), tikv oom multi times
http://perf.pingcap.net:3000/d/C1q8KDMVz/ha-test-summary?orgId=1&var-testbed=endless-ha-test-multi-rocks-tps-1654853-1-283&var-tag=All&var-case_name=All

### What did you expect?
tikv should not be oom

### What did happened?
3 tikvs oom
logs: http://minio.pingcap.net:38888/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLWhhLXRlc3QtbXVsdGktcm9ja3MtdHBzLTE2NTQ4NTMtMS0yODMv
clinic:  https://clinic.pingcap.com.cn/portal/#/login?next=%2Forgs%2F31%2Fclusters%2F7207301522984517045
![image](https://user-images.githubusercontent.com/84712107/223312912-12383b43-42dd-4828-8482-a508deb7d8b4.png)
![image](https://user-images.githubusercontent.com/84712107/223313069-5e16478b-d5a5-43e3-b540-7c1f68c4b252.png)
![774f0822-2aec-4b13-9cbc-c129b94fe008](https://user-images.githubusercontent.com/84712107/223316734-1204cde5-e138-4b06-8978-5f9549ca3bc3.jpeg)

**Comment by Lily2025** [comment]
from lijianjun
kv2's memtable is highly used

**Comment by tonyxuqqi** [comment]
@Lily2025  What's the block cache size is used?
