### ISSUE TITLE
[Dynamic Regions] all tidbs can not start after restart all tidbs、tikvs、pds

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14362]
### What version of TiKV are you using?
./tikv-server -V
 TiKV
Release Version:   6.7.0-alpha
Edition:           Community
Git Commit Hash:   8bfa12dea2d5bd0918b35e5ae041676aeeee77ab
Git Commit Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:    2023-03-05 11:40:05
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
restart all tidbs、tikvs、pds

### What did you expect?
all pods can start normally
https://tcms.pingcap.net/dashboard/executions/plan/1655167
run ha-all-comp-restart

### What did happened?
all tidbs can not start with FATAL error

"[terror.go:300] [\"unexpected error\"] [error=\"[tikv:9002]TiKV server timeout\"] [stack=\"github.com/pingcap/tidb/parser/terror.MustNil\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:300\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:347\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:243\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:250\"] [stack=\"github.com/pingcap/tidb/parser/terror.MustNil\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:300\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:347\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:243\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:250\"]"

![7bbc50b1-f143-433f-86a3-c057004672be](https://user-images.githubusercontent.com/84712107/223604062-1467d8a7-bb14-4639-881d-0b143c4b4580.jpeg)

logs: http://minio.pingcap.net:38888/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLWhhLXRlc3QtbXVsdGktcm9ja3MtdHBzLTE2NTUxNjctMS01MDU=
clinc:  https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7207690969345647578?from=1678202605&to=1678204457

**Comment by tonyxuqqi** [comment]
It's fixed by #14917
