### ISSUE TITLE
[Dynamic Regions] qps drop to zero after inject one tikv io hang

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14378]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.7.0-alpha
Edition:           Community
Git Commit Hash:   fc9cf096b3eddc48e2f1df09dd6d716198067410
Git Commit Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:    2023-03-10 11:42:08
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-03-10T20:30:27.276Z	INFO	k8s/client.go:1

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
inject one tikv io hang
https://tcms.pingcap.net/dashboard/executions/plan/1682105
clinic: https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7208935321555813749?from=1678480214&to=1678483863
logs: http://minio.pingcap.net:38888/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLWhhLXRlc3QtbXVsdGktcm9ja3MtdHBzLTE2ODIxMDUtMS03OTQ=

### What did you expect?
qps can recover within 5min

### What did happened?
qps drop to zero after inject one tikv io hang
![7f7b3f6b-8096-49eb-aab3-c6807586e4db](https://user-images.githubusercontent.com/84712107/224611795-b872aa02-53e5-48ab-a9d7-e002061c9ada.jpeg)

**Comment by tonyxuqqi** [comment]
Dup with https://github.com/tikv/tikv/issues/14532.

**Comment by tonyxuqqi** [comment]
The fix is https://github.com/tikv/tikv/issues/14532
It's because the the other two pears cannot elect a new leader.
