### ISSUE TITLE
Enabling resource control by default results in 6%- 8% performance regression

### ISSUE THREAD

**Issue by Yui-Song** [tikv/tikv#14375]
### What version of TiKV are you using?

commit bb6f5e84762c63d2092bc4741b13db179423aced

### Steps to reproduce

run sysbench oltp_write_only/oltp_update_index and bank benchmark comparing the performance of commit 38568e46b27878222961f64e600d4be317bf288f and commit bb6f5e84762c63d2092bc4741b13db179423aced

### What did you expect?
No performance regression.

### What did happened?
The performance sysbench oltp_write_only/oltp_update_index and bank benchmark downgraded 6%- 8%.
![image](https://user-images.githubusercontent.com/84501897/224189971-536a59c2-f153-4d1e-943a-a4a5d43f456d.png)

**Comment by Connor1996** [comment]
After reverting some changes, the regression is eliminated.
![img_v2_14b28863-cc24-437d-9835-d2794cce96cg](https://user-images.githubusercontent.com/13497871/226270827-720d2640-3469-499d-8178-5bb34931af3c.jpg)
Though still has some gap compared to baseline(v6.5), but it's not related resource control
