### ISSUE TITLE
support disaster recover

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#1439]
Refer https://github.com/pingcap/pd/issues/451

Learn from etcd, we can also support disaster recover in TiKV, but TiKV may be more complex, so this has a low priority.

**Comment by balboah** [comment]
sounds like a pretty important issue! I have this problem now with lost quorum and no clear path on how to recover / force one pd to become leader

**Comment by balboah** [comment]
huh? "balboah unassigned hhkbp2"

**Comment by siddontang** [comment]
Hi @balboah 

Em, can you tell me how can the majority lose? 

We have a pd-recover tool which can recover the PD data.  /cc @nolouch

**Comment by balboah** [comment]
thanks I got pointers to pd-recovery from another source, the majority can loose when you have nodes restarting or crashing :)

**Comment by tennix** [comment]
Yes, on some K8s cloud platform nodes will be removed for HA, if pd is deployed on such environment, pd may lose the majority.
@balboah We'll add official document about recovering pd soon

**Comment by Hoverbear** [comment]
Seems https://github.com/pingcap/pd/tree/master/tools/pd-recover accomplished this? I'll close it, but feel free to re-open.
