### ISSUE TITLE
PTAL PR and ISSUE of client-go

### ISSUE THREAD

**Issue by Smityz** [tikv/tikv#14443]
I pull some PRs and issues in the client-go repo, but it seems no one responded. So I want to ask for help here.
Would TiKV community still accept external contributions now?

https://github.com/tikv/client-go/pull/731
https://github.com/tikv/client-go/pull/736
https://github.com/tikv/client-go/issues/703

**Comment by tisonkun** [comment]
PRs are reviewed. I'll take a look at the feature request issue now.

Closing...
