### ISSUE TITLE
[Dynamic Regions] improve the network traffic spikes when partitioned-raft-kv is enabled

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14458]
### Is your feature request related to a problem? Please describe:

partitioned-raft-kv brings significant overhead of network between tikv, after remove the schedulers, the overhead is not observed
![677daeab-b535-4f49-af45-81f347ffe2dd](https://user-images.githubusercontent.com/2316425/227710939-8d78c514-e5a0-4501-a8b9-316ef6f8c12a.jpeg)

### Describe the feature you'd like:

need to reduce the network traffic spike

### Describe alternatives you've considered:

remove the scheduler, but it's not applicable for real-world application

```
» config set region-schedule-limit 0
Success!
» config set hot-region-schedule-limit 0
Success!
» config set replica-schedule-limit 0
Success!
```

**Comment by dbsid** [comment]
with the pr #6314, the QPS and network throughput is much more stable.

![image](https://user-images.githubusercontent.com/2316425/233754627-fddb693c-0b53-4633-bbdc-c03f5773b412.png)

**Comment by bufferflies** [comment]
close by https://github.com/tikv/pd/pull/6375
