### ISSUE TITLE
[Dynamic Regions] Raft-Engine rewrite load results in qps jitter. 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14462]
## Bug Report

In some heavy read-write workload,  Raft-Engine's rewrite load has strong correlation with grpc qps jitter. 
Though increasing the raft-engine gc threshold could mitigate it,  we may need a better default value as a short term mitigation. 
### What version of TiKV are you using?

v7.0
### What did happened?

<img width="913" alt="Screen Shot 2023-03-23 at 8 20 03 PM" src="https://user-images.githubusercontent.com/9442422/227833664-30996968-702c-49b1-8260-6d190989d1d4.png">

**Comment by tabokie** [comment]
Fixed by https://github.com/tikv/tikv/pull/14700
