### ISSUE TITLE
[Dynamic Regions] Raft log recovery takes 450s after restart, even with 16 raft-engine recovery threads

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14478]
### What version of TiKV are you using?

nightly #5a2ff323d6fae82c624ad802e8100d3154d01ba1
### Steps to reproduce

Have some heavy write traffic for more than 1 hour and restart one tikv.
Assuming raft-engine.recovery-threads: 16
### What did you expect?
TiKV's raft log recovery should be within 30s 
### What did happened?
It takes more than 450s.

Log
"[2023/03/28 23:14:15.854 +00:00] [WARN] [pipe_builder.rs:375] ["The last log file is corrupted but ignored: Rewrite:10668, Corruption: Log item offset is smaller than log batch header length"]
[2023/03/28 23:18:57.322 +00:00] [WARN] [pipe_builder.rs:375] ["The last log file is corrupted but ignored: Append:79833, Corruption: Log item offset is smaller than log batch header length"]
[2023/03/28 23:20:57.085 +00:00] [INFO] [engine.rs:91] ["Recovering raft logs takes 450.324382205s"]
"

Maybe we should flush memtable during the grace tikv restart?

**Comment by tabokie** [comment]
Fixed by https://github.com/tikv/tikv/pull/14700 and https://github.com/tikv/tikv/pull/14917
