### ISSUE TITLE
[Dynamic Regions] upgrade from v6.6. to v7.0 is slow due to Recovering raft logs

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14472]
### What version of TiKV are you using?

v7.0

### What operating system and CPU are you using?

x86
### Steps to reproduce

upgrade a cluster with pure_threshhold = 200GB is slow

### What did you expect?
fast upgrade operation, the elapse time of Recovering raft logs should less than 1 minutes.

### What did happened?

```
[2023/03/28 08:11:06.487 +00:00] [INFO] [engine.rs:91] ["Recovering raft logs takes 252.292317067s"]
```

**Comment by tonyxuqqi** [comment]
dup with #14481
