### ISSUE TITLE
pitr status became paused after injecting network partition between two AZs or one of tikv failure 

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#14545]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.1.0-alpha
Edition:           Community
Git Commit Hash:   abb672b8218307e3811281c22643e0eb2e13cc2c
Git Commit Branch: heads/refs/tags/v7.1.0-alpha
UTC Build Time:    2023-04-08 11:41:27
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-04-10T10:18:48.343+0800	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、create pitr
2、run workload
3、inject network partition between two AZs
clinic：https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7220085244766922657?from=1681093115&to=1681094965

![image](https://github.com/tikv/tikv/assets/84712107/729e49a2-fb76-4b74-a252-2dd48d51a6fa)

### What did you expect?
pitr status should be normal

### What did happened?
pitr status became to paused after inject network partition between two AZs

**Comment by 3pointer** [comment]
we had 1 minute retry for observe region and after that the task enter paused. we can negotiate the proper retry time for this scenario internally.

**Comment by benmaoer** [comment]
It's not a critical bug. It's a better have feature

**Comment by Lily2025** [comment]
v6.5.7, pitr paused after inject one of az failure lasts for 10mins，after fault recover，pitr status is always paused
clinic：https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7319508904069820562?from=1704248700&to=1704250538

**Comment by YuJuncen** [comment]
Should be duplicated with https://github.com/tikv/tikv/issues/16554.
