### ISSUE TITLE
Should avoid disk explosion caused by compaction

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#14540]
### What version of TiKV are you using?

[tidb@ip-172-16-4-49 bin]$ ./tikv-server -V
TiKV
Release Version:   6.6.0
Edition:           Community
Git Commit Hash:   d7847d1be1a5176652dda0f182527615b5c22016
Git Commit Branch: heads/refs/tags/v6.6.0
UTC Build Time:    2023-02-12 08:08:03
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What did happened?

![image](https://user-images.githubusercontent.com/9443637/230592449-4574d48a-063c-411b-a38b-6cf0e0a8a5f9.png)

![image](https://user-images.githubusercontent.com/9443637/230592236-8e25ab51-e74b-4138-9a81-759dd57136de.png)

![image](https://user-images.githubusercontent.com/9443637/230592175-99420321-8cd8-476d-bc15-e982fdb62b39.png)

![image](https://user-images.githubusercontent.com/9443637/230592367-6b835f5c-1cf5-40cd-b875-ca94e8005ea1.png)

**Comment by mayjiang0203** [comment]
MySQL [(none)]> show config where name like '%soft-pending-compaction-bytes-limit%' and type='tikv';
+------+-------------------+----------------------------------------------------------+--------+
| Type | Instance          | Name                                                     | Value  |
+------+-------------------+----------------------------------------------------------+--------+
| tikv | 172.16.4.74:20160 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.74:20160 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.74:20160 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.74:20160 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.74:20160 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.74:20160 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
| tikv | 172.16.4.48:20160 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.48:20160 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.48:20160 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.48:20160 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.48:20160 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.48:20160 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
| tikv | 172.16.4.49:20160 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.49:20160 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.49:20160 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.49:20160 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.49:20160 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.49:20160 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
| tikv | 172.16.4.47:20161 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.47:20161 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.47:20161 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.47:20161 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.47:20161 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.47:20161 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
| tikv | 172.16.4.74:20161 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.74:20161 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.74:20161 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.74:20161 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.74:20161 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.74:20161 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
| tikv | 172.16.4.47:20160 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.47:20160 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.47:20160 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.47:20160 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.47:20160 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.47:20160 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
| tikv | 172.16.4.49:20161 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.49:20161 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.49:20161 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.49:20161 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.49:20161 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.49:20161 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
| tikv | 172.16.4.48:20161 | raftdb.defaultcf.soft-pending-compaction-bytes-limit     | 192GiB |
| tikv | 172.16.4.48:20161 | rocksdb.defaultcf.soft-pending-compaction-bytes-limit    | 192GiB |
| tikv | 172.16.4.48:20161 | rocksdb.lockcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.48:20161 | rocksdb.raftcf.soft-pending-compaction-bytes-limit       | 192GiB |
| tikv | 172.16.4.48:20161 | rocksdb.writecf.soft-pending-compaction-bytes-limit      | 192GiB |
| tikv | 172.16.4.48:20161 | storage.flow-control.soft-pending-compaction-bytes-limit | 192GiB |
+------+-------------------+----------------------------------------------------------+--------+
48 rows in set (0.03 sec)

**Comment by tonyxuqqi** [comment]
Dup with https://github.com/tikv/tikv/issues/15036
