### ISSUE TITLE
[Dynamic Regions] with prefill, raft-engine should recycle the logs rather than rename the logs

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14568]
### What version of TiKV are you using?

v7.0.0

### What operating system and CPU are you using?

x86

### Steps to reproduce

run workload with ttl enable on gcp cloud

### What did you expect?
no latency jitter caused the rewrite flow on raft-engine

### What did happened?
latency jitter caused the rewrite flow on raft-engine

![image](https://user-images.githubusercontent.com/2316425/231746450-c6ffe47d-f195-4c65-a2e7-772c6cc1eb69.png)

**Comment by tabokie** [comment]
Implemented in https://github.com/tikv/raft-engine/pull/310, already rolled out in 7.2
