### ISSUE TITLE
[Dynamic Regions] batch split cause significant  latency jitter

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14566]
### What version of TiKV are you using?

master

### Steps to reproduce

run a workload with ttl enable

### What did you expect?
when ttl is running there is no significant latency jitter caused by batch split.

### What did happened?
![image](https://user-images.githubusercontent.com/2316425/231724417-d9c5827a-2be2-4342-8ffb-baf1f0b88fa5.png)
![image](https://user-images.githubusercontent.com/2316425/231724644-abbe175b-0e60-498c-9de6-1f62b8d2ce32.png)
![image](https://user-images.githubusercontent.com/2316425/231724231-bc514a30-e6fc-4958-a348-09eb437cf93a.png)
![image](https://user-images.githubusercontent.com/2316425/231724341-90b56785-2f9a-4918-8546-33c7fde907c4.png)

**Comment by tonyxuqqi** [comment]
It's closed by #14713
