### ISSUE TITLE
[Dynamic Regions] tablet_snap takes 1.4TB and TiKV running out of space

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14581]
### What version of TiKV are you using?

nightly

### What operating system and CPU are you using?

x86
### Steps to reproduce

run the social network simulation for two days

### What did you expect?
no  running out of space
### What did happened?
running out of space, tablets directory takes 1.4 TB
```
[root@tc-tikv-0 data]# pwd
/var/lib/tikv/data
[root@tc-tikv-0 data]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme4n1    3.6T  3.5T     0 100% /var/lib/tikv
[root@tc-tikv-0 data]# du -sh * | sort -n
0       LOCK
0       raftdb.info
1.4T    tablet_snap
2.1T    tablets
12K     import
20K     last_tikv.toml
29M     rocksdb.info
45G     raft-engine
```

**Comment by bufferflies** [comment]
there are many remaining snapshot file because the sending file failed. TIKV should clean it if sending failed.
![12de6ebb-9865-4d0e-9401-d7fb329280c7](https://user-images.githubusercontent.com/23159587/232374741-5cef23af-526b-4ef9-b6a9-dcb8d3cbdc4f.jpeg)
