### ISSUE TITLE
[Dynamic Regions] the value of metric tikv_unified_read_pool_running_tasks is wrong causing server is busy error

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14633]
### What version of TiKV are you using?

master
### What operating system and CPU are you using?

x86
### Steps to reproduce

run the workload stability test

### What did you expect?
running task tikv_unified_read_pool_running_tasks should be reduced to zero after stopping the workload

### What did happened?
running task is not decreased and causing server is busy error
![image](https://user-images.githubusercontent.com/2316425/233752081-c9e78be6-4dcf-40df-af5b-b9e488096be2.png)
![image](https://user-images.githubusercontent.com/2316425/233752091-951a0f8e-be4d-4208-9380-edafc7b3876e.png)

> 
https://docs.pingcap.com/tidb/stable/tidb-troubleshooting-map#43-the-client-reports-the-server-is-busy-error
4.3.4 TiKV coprocessor is in a queue. The number of piled up tasks exceeds coprocessor threads * readpool.coprocessor.max-tasks-per-worker-[normal|low|high]. Too many large queries leads to the tasks piling up in coprocessor. You need to check whether a execution plan change causes a large number of table scan operations.

**Comment by dbsid** [comment]
![b572b766-7e2c-4e49-8f4a-8830a6f0580c](https://user-images.githubusercontent.com/2316425/233752168-ae854343-069d-4480-a617-355c53f7c5b6.jpeg)

**Comment by dbsid** [comment]
```
sum(tikv_storage_engine_async_request_total{k8s_cluster="$k8s_cluster", tidb_cluster=~"$tidb_cluster.*", instance=~"$instance", type="snapshot", status="all"}) by (instance) -  sum(tikv_storage_engine_async_request_total{k8s_cluster="$k8s_cluster", tidb_cluster=~"$tidb_cluster.*", instance=~"$instance", type="snapshot", status!="all"}) by (instance)
```

![img_v2_67d2f9e3-4e8f-460d-ab37-8441ecffa76g](https://user-images.githubusercontent.com/2316425/234800575-2a95f6de-21ae-4015-8cd9-590bf4722d44.jpg)

**Comment by dbsid** [comment]
This issue is also observed when running tpcc workload using the latest nightly build
`sum(tikv_storage_engine_async_request_total{k8s_cluster="$k8s_cluster", tidb_cluster=~"$tidb_cluster.*", instance=~"$instance", type="snapshot", status="all"}) by (instance) -  sum(tikv_storage_engine_async_request_total{k8s_cluster="$k8s_cluster", tidb_cluster=~"$tidb_cluster.*", instance=~"$instance", type="snapshot", status!="all"}) by (instance)
`

![image](https://user-images.githubusercontent.com/2316425/235281385-56a6f6ce-e8da-446a-9520-ea22a0c343c9.png)

**Comment by overvenus** [comment]
`async_snapshot` seems to be stuck by slow read index. Region 116483 is splitting during that time.

```log
tikv-2023-04-26T19-43-35.048.log:[2023/04/26 19:43:33.719 +08:00] [DEBUG] [lease.rs:106] ["handle reads with a read index"] [request_id=71fc422d-b0ff-4b14-9ef0-b5322be59495] [peer_id=116484] [region_id=116483]​
tikv-2023-04-26T19-39-53.129.log:[2023/04/26 19:39:50.628 +08:00] [DEBUG] [lease.rs:70] ["request to get a read index"] [request_id=71fc422d-b0ff-4b14-9ef0-b5322be59495] [peer_id=116484] [region_id=116483]​
​
tikv-2023-04-26T19-43-35.048.log:[2023/04/26 19:43:33.720 +08:00] [DEBUG] [lease.rs:106] ["handle reads with a read index"] [request_id=2683332a-2557-4bf3-87f8-c148d5ed2a22] [peer_id=116484] [region_id=116483]​
tikv-2023-04-26T19-40-02.016.log:[2023/04/26 19:39:59.695 +08:00] [DEBUG] [lease.rs:70] ["request to get a read index"] [request_id=2683332a-2557-4bf3-87f8-c148d5ed2a22] [peer_id=116484] [region_id=116483]​
​
tikv-2023-04-26T19-43-35.048.log:[2023/04/26 19:43:33.720 +08:00] [DEBUG] [lease.rs:106] ["handle reads with a read index"] [request_id=716ac40a-795c-47ea-a971-31ff99db9357] [peer_id=116484] [region_id=116483]​
tikv-2023-04-26T19-40-10.813.log:[2023/04/26 19:40:09.011 +08:00] [DEBUG] [lease.rs:70] ["request to get a read index"] [request_id=716ac40a-795c-47ea-a971-31ff99db9357] [peer_id=116484] [region_id=116483]​
​
tikv-2023-04-26T19-39-44.710.log:[2023/04/26 19:39:42.865 +08:00] [INFO] [mod.rs:237] ["Propose split"] [peer_id=116484] [region_id=116483]​
...​
tikv-2023-04-26T19-43-35.048.log:[2023/04/26 19:43:33.737 +08:00] [INFO] [snapshot.rs:278] ["init split with snapshot finished"] [peer_id=188077] [region_id=188076]​​​
```

**Comment by overvenus** [comment]
There are two issues in this case.

1. Split is slow because flush memtable is blocked by a false positive write stall.
2. Because the slow split, it triggers `tidb_load_based_replica_read_threshold` and TiDB sends follower reads to TiKV, which are not supported in raftstorev2, follower read is blocked forever.

False positive write stall log:

```log
[2023/04/26 19:39:42.867 +08:00][5][INFO] [116483_5][utilities/checkpoint/checkpoint_impl.cc:97] Started the snapshot process -- creating snapshot in directory /var/lib/tikv/data/tablets/split_1880>[2023/04/26 19:39:42.867 +08:00][5][INFO] [116483_5][utilities/checkpoint/checkpoint_impl.cc:112] Snapshot process -- using temporary directory /var/lib/tikv/data/tablets/split_188076_5.tmp
[2023/04/26 19:39:42.868 +08:00][5][INFO] [116483_5][db/db_impl/db_impl_compaction_flush.cc:2285] [write] WaitUntilFlushWouldNotStallWrites waiting on stall conditions to clear
[2023/04/26 19:43:33.691 +08:00][5][INFO] [116483_5][db/db_filesnapshot.cc:410] Number of log files 0
[2023/04/26 19:43:33.691 +08:00][5][INFO] [116483_5][utilities/checkpoint/checkpoint_impl.cc:127] Hard Linking 002491.sst
... ...
[2023/04/26 19:43:33.692 +08:00][5][INFO] [116483_5][utilities/checkpoint/checkpoint_impl.cc:142] Creating CURRENT
[2023/04/26 19:43:33.692 +08:00][5][INFO] [116483_5][utilities/checkpoint/checkpoint_impl.cc:127] Hard Linking OPTIONS-002434
[2023/04/26 19:43:33.694 +08:00][5][INFO] [116483_5][utilities/checkpoint/checkpoint_impl.cc:178] Snapshot DONE. All is good
[2023/04/26 19:43:33.694 +08:00][5][INFO] [116483_5][utilities/checkpoint/checkpoint_impl.cc:180] Snapshot sequence number: 4773910
```
