### ISSUE TITLE
[Dynamic Regions] with v2, the compaction flow has significant impact on the foreground QPS

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14653]
## Development Task

The compaction flow has huge impact on application query latency and QPS.

![image](https://user-images.githubusercontent.com/2316425/234259331-4b878a1a-057c-49b1-bcf9-5129e7e2d03a.png)
![image](https://user-images.githubusercontent.com/2316425/234259172-7cf98258-0c59-4ff6-a2c3-436b2e4ef679.png)

The below configures does not solve the QPS jitter issue.

```
    config: |
      log-file = "/var/lib/tikv/log/tikv.log"

      [raft-engine]
        purge-threshold = "50GB"

      [resource-control]
        enabled = false

      [rocksdb]
        max-background-flushes = 4
        rate-bytes-per-sec = "0B"
        write-buffer-flush-oldest-first = true
        [rocksdb.defaultcf]
          compression-per-level = ["zstd", "zstd", "zstd", "zstd", "zstd", "zstd", "zstd"]

      [storage]
        engine = "partitioned-raft-kv"
        reserve-space = "0MB"
        [storage.io-rate-limit]
          level-zero-compaction-priority = "low"
          max-bytes-per-sec = "400MiB"
```

**Comment by tonyxuqqi** [comment]
The issue should be greatly mitigated due to many optimizations done in 7.1.  But need to verify with this test case. Downgrade it to major for now.

**Comment by dbsid** [comment]
with the flow control 

```
      [storage]
        engine = "partitioned-raft-kv"
        [storage.io-rate-limit]
          max-bytes-per-sec = "300MiB"
