### ISSUE TITLE
Coprocessor task terminated due to exceeding the deadline in tispark scenario

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#14753]
### What version of TiKV are you using?

6.5.1
### Steps to reproduce

9 tikvs for voter role, 3 tikvs for learner role, tispark read from learner roles.
tispark job is `select * from a_big_table(3T,single replica)` and the learner tikv cpu is about 80% during the spark job
The spark job takes about 30 minutes and failed for the error of `Coprocessor task terminated due to exceeding the deadline` occasionally.
Maybe we can refine ther retry logic for the coprocessor timeout in the tispark or tikv.
### What did you expect?
spark job success

**Comment by tonyxuqqi** [comment]
https://github.com/pingcap/tidb/issues/45298

**Comment by glkappe** [comment]
https://github.com/pingcap/tidb/issues/45298 https://github.com/tikv/client-go/pull/865
I want to make sure they haven't been picked to the release version yet, right?

**Comment by tonyxuqqi** [comment]
@glkappe It's merged.
