### ISSUE TITLE
Compaction is triggered by some kind of NumOfReasons after upgrading

### ISSUE THREAD

**Issue by pcqz** [tikv/tikv#14754]
### What version of TiKV are you using?
v6.5.2

### Steps to reproduce
After upgrading from v6.1.3 to v6.5.2, RocksDB compaction was triggered and may cause a period of write duration increase.

![image](https://github.com/tikv/tikv/assets/45614653/e8ebc0da-289d-47d1-9c0c-03d3ac744b1d)
![img_v2_f6517859-ce86-4680-ab5e-e1906888907g](https://github.com/tikv/tikv/assets/45614653/b8587b63-9c8a-428e-b6bf-9c29691e86a0)
![image](https://github.com/tikv/tikv/assets/45614653/138ecf2b-3c4f-44c3-84a3-a4a719688bc7)

### What did you expect?

No compaction triggered after upgrading.

### What did happened?

Compaction triggered

**Comment by tabokie** [comment]
The real reason should be periodic-compaction. It is automatically enabled (30d) for newer RocksDB with compaction filter: https://github.com/facebook/rocksdb/pull/5865. The compaction triggered after upgrading to TiKV 6.2+ is expected.
