### ISSUE TITLE
Multiple SST files snapshot may trigger flow control

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#14828]
### What version of TiKV are you using?

v6.5.2

### What operating system and CPU are you using?

Not related

### What did you expect?
Do not trigger flow control

### What did happened?
When there is a big region formed for some reason, multiple sst files snapshot may ingest a lot of SSTs in L0 while it only check `ingest_maybe_stall` based on the premise of ingesting only one SST. Then it could be cause too many L0 files and trigger flow control.

![img_v2_eef732cd-8a61-4d54-83e1-260433fcc54g](https://github.com/tikv/tikv/assets/13497871/29cb26c4-99ff-4fc0-9b58-5167302e5ccf)
![img_v2_b19399c4-a552-42e2-ba3e-5121c915e83g](https://github.com/tikv/tikv/assets/13497871/c4628d3e-9ba4-4632-a144-5318925ab9aa)
![img_v2_c56df2db-8cbd-442a-95e8-56e6a10584cg](https://github.com/tikv/tikv/assets/13497871/30a1e22a-10e4-4454-b652-0cbe845c7a7d)

**Comment by tonyxuqqi** [comment]
To ensure atomic ingest of a snapshot, these SSTs must be ingested as a whole. So basically, it's a trade-off between single large SST and L0 file count.

**Comment by tonyxuqqi** [comment]
The real fix is to avoid such big region which is fixed in https://github.com/tikv/tikv/pull/15900
