### ISSUE TITLE
invalid configuration: max_sub_compactions should be greater than 0 and less than or equal to 2

### ISSUE THREAD

**Issue by 3pointer** [tikv/tikv#14877]
### What version of TiKV are you using?

v6.5.2

### What operating system and CPU are you using?

CPU core >= 8

### Steps to reproduce

using config
```
[rocksdb]
max-background-jobs=2
```

### What did you expect?
start tikv-server without FATAL

### What did happened?
[2023/06/05 15:30:44.244 +08:00] [FATAL] [setup.rs:309] ["invalid configuration: max_sub_compactions should be greater than 0 and less than or equal to 2"]

**Comment by 3pointer** [comment]
The default value apply (max-sub-compactions, max-background-jobs) to (3，4）
But if I set max-background-jobs to 2 manually. 
The default value of max-sub-compactions should not make tikv panic.

**Comment by tabokie** [comment]
Just remove the check added in https://github.com/tikv/tikv/pull/13151. sub_compactions are not required to be smaller than background_jobs. They use temporary threads instead of background threads.
