### ISSUE TITLE
RocksDB should avoid large compaction (e.g. 600GB compaction) 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14891]
## Bug Report

Today if the SST is small enough (e.g. < compaction-guard-min-output-file-size) , its keys may cross many regions. And then when it's compacted into L6, it's possible that the compaction input file can be huge (e.g. > 600GB). 
What's worse, during the compaction, all the SST files referenced by the version of the compaction will not be released, which further consumes lots of space. 

We cannot simply reduce the compaction-guard-min-output-file-size threshold because it may negatively impact performance in large data set, and also even if we reduce it to 1MB, it's still possible to have large compaction problem. 

The solution @tabokie propose is that we split the SST into region's boundary, regardless the size whenever we found that this SST will trigger a large compaction. However in normal cases, it's still regulated by the compaction-guard-min-output-file-size.

**Comment by tabokie** [comment]
Dup with https://github.com/tikv/tikv/issues/15058
