### ISSUE TITLE
[Dynamic Regions] Fast DDL generates lots of L0 files in MultiRocksDB

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#14916]
### What version of TiKV are you using?

nightly
### Steps to reproduce

With partitioned-raft-kv enabled, Use Fast DDL to create an new index and import data
### What did you expect?
The speed should be faster than default engine. 
### What did happened?
SST ingest failed because of too many L0 files leading to TiKV ServerBusy.
Below is the SST ingestion picked level in partitioned-raft-kv. All the L0 files are generated by SST ingestion. 
<img width="898" alt="Screen Shot 2023-06-09 at 3 06 34 PM" src="https://github.com/tikv/tikv/assets/9442422/aa7c9bfc-2be3-47a9-9be7-14b17a675ebc">

There're 3 rounds of SST ingestion. Within each round, SST key range are non-overlapping. Between rounds, there's overlap. 
So in the first round, all SSTs are ingested to L6, which is expected. However, in second round, most of them are ingested to L5 and L0. 
Here's the example RocksDB instance's log.
[2780.txt](https://github.com/tikv/tikv/files/11710471/2780.txt)
Below is the example of a unexpected ingestion to L0.  As the log shows, when a L0 file is ingested, there's no other SST files except L6. So it should ingest to non L0 instead. 

> [2023/06/09 17:04:03.071 +00:00][5][INFO] [2780_112][db/external_sst_file_ingestion_job.cc:491] [AddFile] External SST file /var/lib/tikv/data/import/.clone/2935deae-09af-48d6-8b1d-51088ada353e_2780_959_173_write.sst was ingested in L0 with path /var/lib/tikv/data/tablets/2780_112/000624.sst (global_seqno=230)
> [2023/06/09 17:04:03.072 +00:00][5][INFO] [2780_112]EVENT_LOG_v1 {"time_micros": 1686330243071902, "event": "ingest_finished", "files_ingested": ["file", "/var/lib/tikv/data/tablets/2780_112/000624.sst", "level", 0], "lsm_state": [1, 0, 0, 0, 0, 0, 7]}

And from this log, we can know the base level is 6.
> [2023/06/09 17:09:04.913 +00:00][5][INFO] [2780_112](Original Log Time 2023/06/09-17:09:04.913248) [db/compaction/compaction_job.cc:965] [write] compacted to: base level 6 level multiplier 10.00 max bytes base 536870912 files[5 0 0 0 0 0 9] max score 1.25, MB/sec: 10.3 rd, 10.4 wr, level 6, files in(1, 2) out(1 +0 blob) MB in(0.8, 6.7 +0.0 blob) out(7.5 +0.0 blob), read-write-amplify(19.6) write-amplify(9.8) OK, records in: 29705, records dropped: 0 output_compression: ZSTD

Below is the SST ingestion picked level in raft-kv
<img width="895" alt="Screen Shot 2023-06-09 at 3 20 23 PM" src="https://github.com/tikv/tikv/assets/9442422/1662f195-d251-49ac-93ae-3cd0a55146ea">

**Comment by tonyxuqqi** [comment]
use dynamic-level-bytes = false should fix/workaround this issue.

**Comment by tonyxuqqi** [comment]
The other way is to increase the compaction threshold over L0 file count. And in MultiRocksDB, we can do it at region level. 
So the switch_mode (src/import/sst_service.rs) can be extended to specify the key ranges. 
The question is what if the region's range is partially covered by the specified key range. Maybe we should be conservative on this---that is if the region's range is not fully covered by the specified key range, it should not be in import mode.

**Comment by overvenus** [comment]
> The question is what if the region's range is partially covered by the specified key range. Maybe we should be conservative on this---that is if the region's range is not fully covered by the specified key range, it should not be in import mode.

How about using an array of region ID instead? As it has no partial cover issue.

**Comment by SpadeA-Tang** [comment]
> > The question is what if the region's range is partially covered by the specified key range. Maybe we should be conservative on this---that is if the region's range is not fully covered by the specified key range, it should not be in import mode.
> 
> How about using an array of region ID instead? As it has no partial cover issue.

We can include all regions overlapped with the range. In v2, I'm not going to change the rocksdb config now in import mode, and just make these regions pass sst ingestion write stall check.
