### ISSUE TITLE
[Contribute] client-cpp development requires review

### ISSUE THREAD

**Issue by Smityz** [tikv/tikv#14939]
## Development Task
Hello masters, we recently needed to use the C++ SDK to connect to TiKV, so I contributed some code to the client-cpp repository. However, it seems that the repository has not been maintained for a long time, so I'm posting here to bring attention to it. Does the TiKV community still want to maintain client-cpp? If so, I am also willing to assist with contributions.

Related issue:
https://github.com/tikv/client-cpp/issues/18
https://github.com/tikv/client-cpp/issues/16

**Comment by tisonkun** [comment]
Checked.

Closing...

We don't use issue as notifications.
