### ISSUE TITLE
[Dynamic Regions] v2 60% QPS drop compare with v1 with ~5x delete_skipped-index

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#14947]
### What version of TiKV are you using?

master
### What operating system and CPU are you using?

x86
### Steps to reproduce

run a workload with 2 select, 1 insert and 1 commit
### What did you expect?
no performance degradation.

### What did happened?

![image](https://github.com/tikv/tikv/assets/2316425/24b8162a-e4aa-4f93-8358-9c98c01c5119)

![image](https://github.com/tikv/tikv/assets/2316425/718dd3e5-8246-4365-950a-75bcfa5c69a4)

**Comment by dbsid** [comment]
![img_v2_b9c759ae-c2e8-492f-97c7-43db53b9886g](https://github.com/tikv/tikv/assets/2316425/18464980-fa97-4b3b-b56e-5bc93c9da6b2)

**Comment by tonyxuqqi** [comment]
Changing the memtable of lockcf to 2MB greatly mitigate this problem. Downgrade it to major.

**Comment by bufferflies** [comment]
This delete skip happened in lock cf. In dynamic regions, every region store the cf data and compact it, so the frequence of compaction is less than v1. User can downsize the lockcf `write-buffer-size` to speed up the frequence of the flush and compaction. Here is the test result of modify the write-buffer-size:
<img width="1101" alt="image" src="https://github.com/tikv/tikv/assets/23159587/14ecc897-96a1-4f54-be1b-5f0b09bd27a6">

**Comment by tonyxuqqi** [comment]
We're doing the benchmark on different workloads on the reduced lock-cf size.  If there's a sweet spot size, then this issue can be closed.

**Comment by tonyxuqqi** [comment]
It should be greatly mitigated by the new 4MB lock-cf size. Changing it as moderate.

**Comment by bufferflies** [comment]
ref #https://github.com/tikv/tikv/pull/15453

**Comment by bufferflies** [comment]
close #15132
