### ISSUE TITLE
[Dynamic Region] Write hot can't be scheduled with the tpcc preapre insert

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15011]
### What version of TiKV are you using?

Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   de3d6655c3bb0eceac068207fe7ec8be30bdbcc7
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-26 11:13:06
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

tpcc 100k warehouse prepare, 20 tikv and 6 tiflash.
![image](https://github.com/tikv/tikv/assets/7677963/b1d2ed92-989f-47dc-8d21-ef15b91b5af1)

### What did you expect?
tikv store size balance
write flow balance
### What did happened?
not balance as above

**Comment by LykxSassinator** [comment]
/remove-label may-affects-5.1 may-affects-5.2 may-affects-5.3 may-affects-5.4 may-affects-6.1 may-affects-6.5 may-affects-7.1
