### ISSUE TITLE
[Dynamic Region] pitr checkpoint ts lag keep increasing after simulate tikv network partition for 50m and recover

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#15031]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   bd11fb033e85512f0dd20cffaf1bcefc5e8c0bd6
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-27 09:12:24
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-06-28T19:59:01.981+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、start pitr task
2、run tpcc
3、simulate tikv network partition for 50m and recover

### What did you expect?
pitr checkpoint ts lag is less than 5min

### What did happened?
pitr checkpoint ts lag keep increasing after simulate tikv network partition for 50m and recover
![image](https://github.com/tikv/tikv/assets/84712107/ba584fa6-b242-4070-9cf8-4b354abd992a)

**Comment by 3pointer** [comment]
Currently, we can see pitr checkpoint lag increased due to resolved ts lag increased. but the reason why resolved ts increased still no clue.


![31894e8f-9fbe-477e-b680-4fc0ea6d93bc](https://github.com/tikv/tikv/assets/5906259/a575c387-6792-4030-b158-701715a62157)
