### ISSUE TITLE
Leader holds an invalid lease if one node is isolated and one node restarts

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#15035]
## Bug Report

Suppose there are three peers, A, B, C and A is the leader. Linearizability may be violated by following steps:

1. B is isolated from A.
2. A renews its lease.
3. C restarts right after step 2.
4. B starts election right after step 3.
5. B becomes leader before A lease expire.

Now we get two leaders, and both of them think they hold a valid lease.

A possible solution: Peers delay respond request vote after restart, within one election timeout.

```rust
#[test]
fn test_node_lease_restart_during_isolation() {
    let mut cluster = new_node_cluster(0, 3);
    configure_for_lease_read(&mut cluster.cfg, Some(1000), Some(3));
    cluster.run();

    let key = b"k";

    let region = cluster.get_region(key);
    let region_id = region.get_id();
    let peer1 = find_peer(&region, 1).unwrap();
    let peer2 = find_peer(&region, 2).unwrap();

    cluster.must_put(key, b"v0");
    cluster.must_transfer_leader(region_id, peer1.clone());
    must_read_on_peer(&mut cluster, peer1.clone(), region.clone(), key, b"v0");
    cluster.must_transfer_leader(region_id, peer2.clone());
    must_read_on_peer(&mut cluster, peer2.clone(), region.clone(), key, b"v0");

    cluster.add_send_filter(IsolationFilterFactory::new(2));

    // Restart node 3.
    cluster.stop_node(3);
    cluster.run_node(3).unwrap();

    // Let peer1 start election.
    let mut timeout = RaftMessage::default();
    timeout.mut_message().set_to(peer1.get_id());
    timeout
        .mut_message()
        .set_msg_type(MessageType::MsgTimeoutNow);
    timeout
        .mut_message()
        .set_msg_type(MessageType::MsgTimeoutNow);
    timeout.set_region_id(region.get_id());
    timeout.set_from_peer(peer2.clone());
    timeout.set_to_peer(peer1.clone());
    timeout.set_region_epoch(region.get_region_epoch().clone());
    cluster.send_raft_msg(timeout).unwrap();

    let (tx, rx) = mpsc::channel();
    let append_resp_notifier = Box::new(MessageTypeNotifier::new(
        MessageType::MsgAppendResponse,
        tx,
        Arc::from(AtomicBool::new(true)),
    ));
    cluster.sim.wl().add_send_filter(3, append_resp_notifier);
    rx.recv_timeout(Duration::from_secs(5)).unwrap();

    let mut put = new_request(
        region.get_id(),
        region.get_region_epoch().clone(),
        vec![new_put_cmd(key, b"v1")],
        false,
    );
    put.mut_header().set_peer(peer1.clone());
    let resp = cluster.call_command(put, Duration::from_secs(5)).unwrap();
    assert!(!resp.get_header().has_error(), "{:?}", resp);
    must_read_on_peer(&mut cluster, peer2.clone(), region.clone(), key, b"v0");
    must_read_on_peer(&mut cluster, peer1.clone(), region.clone(), key, b"v1");
}
```

### What did you expect?

No stale read.

### What did happened?

Stale read.

**Comment by Connor1996** [comment]
The case uses `MsgTimeoutNow` to trigger the election without prevote. But in a normal scenario, B would start the election with prevote, then C wouldn't vote for B cause C already voted for A in the same term.

**Comment by tonyxuqqi** [comment]
C should not vote for B after the restart. Because it will reset the timeout elapsed and think the lease is not expired and so it will reject B's prevote request. 

 pub fn step(&mut self, m: Message) -> Result<()> {
        // Handle the message term, which may result in our stepping down to a follower.
        if m.term == 0 {
            // local message
        } else if m.term > self.term {
            if m.get_msg_type() == MessageType::MsgRequestVote
                || m.get_msg_type() == MessageType::MsgRequestPreVote
            {
                let force = m.context == CAMPAIGN_TRANSFER;
                **let in_lease: bool = self.check_quorum
                    && self.leader_id != INVALID_ID
                    && self.election_elapsed < self.election_timeout;**

**Comment by BusyJay** [comment]
> But in a normal scenario, B would start the election by election timeout which it's with prevote, then C wouldn't vote for B cause C already voted for A in the same term.

Not true. B's prevote request will use a larger term than C's.

> Because it will reset the timeout elapsed and think the lease is not expired and so it will reject B's prevote request.

Yes, but `leader_id` become `INVALID_ID` after being restarted, so in_lease is false.
