### ISSUE TITLE
tikv panic repeatedly after inject tikv io hang and recover

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#15044]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   56130211bf21cb3aea9c5ecec4952f6fedb33093
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-29 11:14:25
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-06-30T06:29:02.849+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc
2、inject one of tikv hang last for 40m and recover

### What did you expect?
all tikv are normal

### What did happened?
tikv panic repeatly after inject tikv io hang and recover

{"log":"[[lib.rs:497](http://lib.rs:497/)] [\"[region 1728] 1729 applying snapshot failed\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18\\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18//n)   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2032](http://boxed.rs:2032/):9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:692](http://panicking.rs:692/):13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:579](http://panicking.rs:579/):13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:137](http://backtrace.rs:137/):18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:575](http://panicking.rs:575/):5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:65](http://panicking.rs:65/):14\\n   6: raftstore::store::peer_storage::PeerStorage<EK,ER>::check_applying_snap\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:797:21\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:797:21//n)   7: raftstore::store::peer::Peer<EK,ER>::check_snap_status\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2555:15\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2555:15//n)      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2675:13\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2675:13//n)   8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1995:19\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1995:19//n)      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1002:13\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1002:13//n)   9: batch_system::batch::Poller<N,C,Handler>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27\\n](http://github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27//n)  10: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:83:21\\n](http://github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:83:21//n)      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\\n](http://github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13//n)      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:121](http://backtrace.rs:121/):18\\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:551](http://mod.rs:551/):17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:483](http://panicking.rs:483/):40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:447](http://panicking.rs:447/):19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:550](http://mod.rs:550/):30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:513](http://function.rs:513/):5\\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\\n  13: start_thread\\n  14: __GI___clone\\n\"] [location=/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:797](http://github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:797)] [thread_name=raftstore-1-1]","container":"tikv","pod":"tc-tikv-0","level":"FATAL","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}

![image](https://github.com/tikv/tikv/assets/84712107/16a4a595-5a4b-469f-8069-c8c1a72237e4)

**Comment by overvenus** [comment]
Snapshot file is corrupted, checksum mismatch. May be caused by side effects of the injected failure.

```log
2023-06-30 08:40:02	
{"pod":"tc-tikv-1","container":"tikv","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519","log":"[snap.rs:914] [\"scan snapshot of one cf\"] [size=0] [key_count=0] [cf=default] [snapshot=/var/lib/tikv/data/snap/gen_1728_8_21798964_(default|lock|write).sst] [region_id=1728]"}
2023-06-30 08:40:02	
{"pod":"tc-tikv-1","container":"tikv","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519","log":"[snap.rs:914] [\"scan snapshot of one cf\"] [size=0] [key_count=0] [cf=lock] [snapshot=/var/lib/tikv/data/snap/gen_1728_8_21798964_(default|lock|write).sst] [region_id=1728]"}
2023-06-30 08:40:04	
{"pod":"tc-tikv-1","container":"tikv","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519","log":"[mod.rs:285] [\"link encrypted file\"] [dst=/var/lib/tikv/data/snap/gen_1728_8_21798964_write.sst] [src=/var/lib/tikv/data/snap/gen_1728_8_21798964_write.sst.tmp]"}
2023-06-30 08:40:04	
{"pod":"tc-tikv-1","container":"tikv","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519","log":"[mod.rs:285] [\"link encrypted file\"] [dst=/var/lib/tikv/data/snap/gen_1728_8_21798964_write_0001.sst] [src=/var/lib/tikv/data/snap/gen_1728_8_21798964_write_0001.sst.tmp]"}
2023-06-30 08:40:04	
{"pod":"tc-tikv-1","container":"tikv","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519","log":"[snap.rs:1088] [\"scan snapshot\"] [takes=1.602267806s] [size=26957641] [key_count=1391130] [snapshot=/var/lib/tikv/data/snap/gen_1728_8_21798964_(default|lock|write).sst] [region_id=1728]"}
2023-06-30 08:40:04	
{"pod":"tc-tikv-1","container":"tikv","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519","log":"[snap.rs:914] [\"scan snapshot of one cf\"] [size=127771591] [key_count=1391130] [cf=write] [snapshot=/var/lib/tikv/data/snap/gen_1728_8_21798964_(default|lock|write).sst] [region_id=1728]"}
2023-06-30 09:00:03	
{"log":"[snap.rs:293] [\"saving snapshot file\"] [file=/var/lib/tikv/data/snap/rev_1728_8_21798964_(default|lock|write).sst] [snap_key=1728_8_21798964]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:03	
{"log":"[snap.rs:301] [\"saving all snapshot files\"] [takes=222.463962ms] [snap_key=1728_8_21798964]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:03	
{"namespace":"endless-ha-test-ticdc-tps-1744569-1-519","pod":"tc-tikv-1","container":"tikv","log":"[snap.rs:535] [\"sent snapshot\"] [duration=1198.625047693s] [size=26957641] [snap_key=1728_8_21798964] [region_id=1728]","level":"INFO"}
2023-06-30 09:00:03	
{"log":"[raft.rs:2533] [\"[commit: 21798964, term: 8] restored snapshot [index: 21798964, term: 8]\"] [snapshot_term=8] [snapshot_index=21798964] [commit=21798964] [term=8] [raft_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:03	
{"log":"[raft.rs:2652] [\"restored snapshot\"] [snapshot_term=8] [snapshot_index=21798964] [last_term=8] [last_index=21798964] [commit=21798964] [raft_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:03	
{"log":"[raft.rs:2668] [\"switched to configuration\"] [config=\"Configuration { voters: Configuration { incoming: Configuration { voters: {1729, 1730, 1731} }, outgoing: Configuration { voters: {} } }, learners: {}, learners_next: {}, auto_leave: false }\"] [raft_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:03	
{"log":"[raft_log.rs:627] [\"log [committed=21000214, persisted=21000215, applied=20999960, unstable.offset=21000216, unstable.entries.len()=0] starts to restore snapshot [index: 21798964, term: 8]\"] [snapshot_term=8] [snapshot_index=21798964] [log=\"committed=21000214, persisted=21000215, applied=20999960, unstable.offset=21000216, unstable.entries.len()=0\"] [raft_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:05	
{"log":"[peer_storage.rs:688] [\"apply snapshot with state ok\"] [for_witness=false] [state=\"applied_index: 21798964 commit_index: 21000214 commit_term: 8 truncated_state { index: 21798964 term: 8 }\"] [region=\"id: 1728 start_key: 7480000000000000FF625F728000000002FF61238F0000000000FA end_key: 7480000000000000FF625F72FFFFFFFFFFFFFFFFFF0000000000FB region_epoch { conf_ver: 5 version: 451 } peers { id: 1729 store_id: 1 } peers { id: 1730 store_id: 4 } peers { id: 1731 store_id: 13 }\"] [peer_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:05	
{"log":"[peer_storage.rs:1046] [\"finish clear peer meta\"] [takes=4.248µs] [raft_key=1] [apply_key=1] [meta_key=1] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:05	
{"log":"[peer_storage.rs:605] [\"begin to apply snapshot\"] [peer_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[region.rs:448] [\"begin apply snap data\"] [peer_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[peer.rs:4908] [\"region changed after persisting snapshot\"] [region=\"id: 1728 start_key: 7480000000000000FF625F728000000002FF61238F0000000000FA end_key: 7480000000000000FF625F72FFFFFFFFFFFFFFFFFF0000000000FB region_epoch { conf_ver: 5 version: 451 } peers { id: 1729 store_id: 1 } peers { id: 1730 store_id: 4 } peers { id: 1731 store_id: 13 }\"] [prev_region=\"id: 1728 start_key: 7480000000000000FF625F728000000002FF61238F0000000000FA end_key: 7480000000000000FF625F72FFFFFFFFFFFFFFFFFF0000000000FB region_epoch { conf_ver: 5 version: 451 } peers { id: 1729 store_id: 1 } peers { id: 1730 store_id: 4 } peers { id: 1731 store_id: 13 }\"] [peer_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[peer.rs:4849] [\"snapshot is persisted\"] [region=\"id: 1728 start_key: 7480000000000000FF625F728000000002FF61238F0000000000FA end_key: 7480000000000000FF625F72FFFFFFFFFFFFFFFFFF0000000000FB region_epoch { conf_ver: 5 version: 451 } peers { id: 1729 store_id: 1 } peers { id: 1730 store_id: 4 } peers { id: 1731 store_id: 13 }\"] [peer_id=1729] [region_id=1728]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[subscription_manager.rs:427] [\"backup stream: on_modify_observe\"] [op=\"Stop { region: Region { id: 8021, ver: 1728, conf_ver: 5, range: [7480000000000000FF675F728000000012FF3917940000000000FA,7480000000000000FF675F728000000012FF3D72450000000000FA), peers: 1,4,13 } }\"]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[mod.rs:244] [\"delete untracked plaintext file\"] [fname=/var/lib/tikv/data/snap/rev_1728_8_21798964_write.sst.clone]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[mod.rs:285] [\"link encrypted file\"] [dst=/var/lib/tikv/data/snap/rev_1728_8_21798964_write.sst.clone] [src=/var/lib/tikv/data/snap/rev_1728_8_21798964_write.sst]","container":"tikv","pod":"tc-tikv-0","level":"INFO","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[region.rs:531] [\"failed to apply snap!!!\"] [err_code=KV:Raftstore:SnapUnknown] [err=\"Other(\\\"[components/raftstore/src/store/snap.rs:1122]: \\\\\\\"[components/raftstore/src/store/snap.rs:277]: invalid checksum 3706937740 for snapshot cf file /var/lib/tikv/data/snap/rev_1728_8_21798964_write_0001.sst, expected 729878206\\\\\\\"\\\")\"]","container":"tikv","pod":"tc-tikv-0","level":"ERROR","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:07	
{"log":"[region.rs:531] [\"failed to apply snap!!!\"] [err_code=KV:Raftstore:SnapUnknown] [err=\"Other(\\\"[components/raftstore/src/store/snap.rs:1122]: \\\\\\\"[components/raftstore/src/store/snap.rs:277]: invalid checksum 3706937740 for snapshot cf file /var/lib/tikv/data/snap/rev_1728_8_21798964_write_0001.sst, expected 729878206\\\\\\\"\\\")\"]","container":"tikv","pod":"tc-tikv-0","level":"ERROR","namespace":"endless-ha-test-ticdc-tps-1744569-1-519"}
2023-06-30 09:00:08	
{"log":"[lib.rs:497] [\"[region 1728] 1729 applying snapshot failed\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18\\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\\n   6: raftstore::store::peer_storage::PeerStorage<EK,ER>::check_applying_snap\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:797:21\\n   7: raftstore::store::peer::Peer<EK,ER>::check_snap_status\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2555:15\\n      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2675:13\\n   8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1995:19\\n      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1002:13\\n   9: batch_system::batch::Poller<N,C,Handler>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27\\n  10: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:83:21\\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\\n  13: start_thread\\n  14: __GI___clone\\n\"] [location=/home/jenkins/agent/workspace/build-common/go/src/g
```

**Comment by overvenus** [comment]
To mitigate the issue, TiKV can validate snapshot files before stepping snapshot message. If snapshot is corrupted, TiKV drops the snapshot and request a new one.

**Comment by Lily2025** [comment]
the same with https://github.com/tikv/tikv/issues/15292
