### ISSUE TITLE
[Dynamic Region] tikv oom when inject 100ms io delay chaos

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15061]
### What version of TiKV are you using?

TiKV
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   425f6f262f577425612cf1663ea6cceada72c724
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-30 11:15:31
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

30 tikv and sysbench write only workload with about 40T data, open slow store evict scheduler and inject a tikv 100ms io delay chaos
the injected tikv oom
![img_v2_b1199307-9e8a-44c8-9e8d-0e7b2203695g](https://github.com/tikv/tikv/assets/7677963/a6947afd-b739-4e00-a8fc-b2e4ceee9abc)

**Comment by zhangjinpeng87** [comment]
Close this issue temporarily since Dynamic Regions project is paused.
