### ISSUE TITLE
[Dynamic Regions] online qps is unstable for the unexpected flow control

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15113]
### What version of TiKV are you using?

TiKV
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   88bd7f1fe2cbcac31d516f76b10f1f213375a06f
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-07-11 11:13:57
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

30 tikv , 2T every tikv, sysbench wide table read only
![b3fad620-940c-4a10-ac2a-cc1b78d8a726](https://github.com/tikv/tikv/assets/7677963/8f437785-7331-495f-a4c2-991538db61d0)
![735d77e4-c228-47c7-8d23-8f3f4b0bb9ee](https://github.com/tikv/tikv/assets/7677963/84ba57e4-3990-405d-bfe4-aad6f119c3d0)
![img_v2_50783166-5958-4bf7-8eda-b18395bf986g](https://github.com/tikv/tikv/assets/7677963/7911090a-c379-4d20-8b40-fa218c6d0fc7)

**Comment by tonyxuqqi** [comment]
The unstable qps by flow control cannot be reproed anymore, however qps is still unstable sometimes because of IO/CPU impact by compaction. 
Changing the severity to major.

**Comment by tonyxuqqi** [comment]
dup with #14470
