### ISSUE TITLE
Delay flushing raft message may cause high raft log commit duration

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#15175]
## Bug Report

High raft log commit duration (2~4s), even if there are not bottleneck in network / disk io / cpu.

![image](https://github.com/tikv/tikv/assets/2150711/c030ffd7-f6f0-4392-8af8-5538c700165c)

### What version of TiKV are you using?

v5.4.3

### Steps to reproduce

Not clear yet, but we do observe such phenomenon.

### What did you expect?

Commit duration should be less than 100ms.

**Comment by tonyxuqqi** [comment]
Also it's better to add metrics or logs on the commit log latency breakdown, especially on the step raft client get message and send to other tikv.

**Comment by overvenus** [comment]
Turns out the commit log high latency is caused by memory alloc stall.
