### ISSUE TITLE
[Dynamic Regions] enable follower read, qps drop more than 90% lasts for 50m after fault recover（one of tikv failure for 10mins）

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#15189]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   aa3a0b014296b5ee42b88fd67f7ac564a01b60bb
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-07-21 11:51:29
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-07-22T21:18:42.150+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、set tidb_replica_read='follower'
2、run tpcc
3、simulate one of tikv failure for 10mins
injection fault：2023/07/22 19:26:21.394 +08:00
recover fault：2023/07/22 19:36:21.442 +08:00

### What did you expect?
qps can recover after fault recover

### What did happened?
qps drop more than 90% lasts for 50m after fault recover
![image](https://github.com/tikv/tikv/assets/84712107/3b195aaf-c545-4a55-8dc3-f3b9a3468372)

**Comment by bufferflies** [comment]
In partition rocksdb， follower needs to take more time to catch the leader log, so the follower will need to wait for it. 
I will fix it by reject read question if peer is being snapshot or commit index is too later than the read index .

**Comment by bufferflies** [comment]
solved
