### ISSUE TITLE
[Dynamic Regions] br: pitr task in error "retry time exceeds: error failed to get initial snapshot"

### ISSUE THREAD

**Issue by Leavrth** [tikv/tikv#15198]
## Bug Report
See https://github.com/pingcap/tidb/issues/45517

### What version of TiKV are you using?

master
### Steps to reproduce

1. open pitr task in partitioned raft kv cluster
### What did happened?
task error failed to get the snapshot (region_id = 1538): Error during requesting raftstore: message: "read index not ready, reason can not read index due to merge, region 1538

**Comment by tonyxuqqi** [comment]
It's not reproed anymore after merge fix. However region unavailable could still lead to BR failure.
