### ISSUE TITLE
[Dynamic Regions] tikv oom frequently when create table

### ISSUE THREAD

**Issue by aytrack** [tikv/tikv#15190]
### What version of TiKV are you using?

47b4c474e73f6f51c19f137814c7daba78e9c093
### What operating system and CPU are you using?

Linux tc-tikv-0 5.18.12-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 15 07:03:42 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
### Steps to reproduce

1. deploy a cluster with some tikv and tiflash nodes using tidb-operator
2. enable multi rocksdb
3. create some table
### What did you expect?
1. create table success
### What did happened?
1. create table return error ` Error 8027: Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV`
1. tikv oom and restart frequently 
[tikv.log](https://github.com/tikv/tikv/files/12156508/tikv.log)

**Comment by tonyxuqqi** [comment]
tiflash is not supported yet (under development, not ready for test yet)

**Comment by tonyxuqqi** [comment]
Due with #15269
