### ISSUE TITLE
when scale in one TiKV in az-a, it will affect the QPS and Duration of az-a and az-c

### ISSUE THREAD

**Issue by River2000i** [tikv/tikv#15245]
### What version of TiKV are you using?

/ # ./tikv-server --version
TiKV
Release Version:   6.5.3
Edition:           Community
Git Commit Hash:   fd5f88a7fdda1bf70dcb0d239f60137110c54d46
Git Commit Branch: heads/refs/tags/v6.5.0-nightly
UTC Build Time:    2023-06-09 11:05:24
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### What operating system and CPU are you using?

8c 50G(deploy on k8s)
### Steps to reproduce

1. deply cluster in 3 az(us-west-2a\us-west-2b\us-west-2c)
2. import 50T data by lightning, about 20w region
3. run workload
4. `edit tc` to scale in tikv from 5 to 4 in us-west-2a

### What did you expect?

`QPS` and `Duration` affected less

### What did happened?
when scale in one TiKV in az-a, it will affect the QPS and Duration of az-a and az-c at 19:50

`tc-a`
![image](https://github.com/tikv/tikv/assets/96465211/504dfc4e-b9b9-4a85-87ae-57a471f8628f)
![image](https://github.com/tikv/tikv/assets/96465211/6f997bd4-c054-41d7-81dd-bbc9aa0072c2)

`tc-b`
![image](https://github.com/tikv/tikv/assets/96465211/c7b0d494-6828-463e-9950-6bd5039afd0b)
![image](https://github.com/tikv/tikv/assets/96465211/43a1df97-91c0-42ad-9cf3-d73793102fd6)

`tc-c`
![image](https://github.com/tikv/tikv/assets/96465211/2e6daea7-d230-4c0c-95c6-d533bb66d80b)
![image](https://github.com/tikv/tikv/assets/96465211/5030f0c0-19d3-4a97-8929-434b4f6a51c5)

**Comment by cfzjywxk** [comment]
Related improvement is included in https://github.com/tikv/client-go/pull/899
