### ISSUE TITLE
[Dynamic Region] transaction check inconsistent 

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#15261]
### What version of TiKV are you using?
[2023/07/30 04:15:22.889 +00:00] [INFO] [lib.rs:93] ["Git Commit Hash: https://github.com/tikv/tikv/commit/42882f8bcf4ce52ea93f93d325c000147ac2e137"]

### Steps to reproduce
 jepsen-monotonic-pessimistic test
 "Establishes a collection of integers identified by keys. Monotonically
increments individual keys via read-write transactions, and reads keys in
small groups. We verify that the order of transactions implied by each key
are mutually consistent; e.g. no transaction can observe key x increase, but
key y decrease."

### What did you expect?
test case run normally.
### What did happened?
```
  value 5710.\n  - However, T2 < T1, because T2 completed at index 184477, 0.002 seconds before the invocation of T1, at index 184480: a co
ntradiction!"
    "Let:\n  T1 = {:type :ok, :f :inc, :value {7 5874}, :process 66, :time 254441073668, :txn-info {:txn_scope \"global\", :start_ts 44320
9724611526664, :commit_ts 443209724611526684, :txn_commit_mode \"1pc\", :async_commit_fallback false, :one_pc_fallback false}, :index 1858
27}\n  T2 = {:type :ok, :f :read, :value {0 5751, 1 5777, 2 5754, 3 5553, 4 5747, 5 5804, 6 5622, 7 5873}, :process 66, :time 254497650847
, :txn-info {:start_ts 443209724624633866}, :index 185843}\n\nThen:\n  - T1 < T2, because T1 completed at index 185827, 0.000 seconds befo
re the invocation of T2, at index 185828.\n  - However, T2 < T1, because T2 observed 7 = 5873, and T1 observed a higher value 5874: a cont
radiction!"
    "Let:\n  T1 = {:type :ok, :f :inc, :value {5 5821}, :process 104, :time 256807262173, :txn-info {:txn_scope \"global\", :start_ts 4432
09725227565147, :commit_ts 443209725240672283, :txn_commit_mode \"1pc\", :async_commit_fallback false, :one_pc_fallback false}, :index 186
308}\n  T2 = {:type :ok, :f :read, :value {0 5771, 1 5791, 2 5774, 3 5567, 4 5760, 5 5820, 6 5643, 7 5887}, :process 66, :time 25685855673
9, :txn-info {:start_ts 443209725240672285}, :index 186335}\n\nThen:\n  - T1 < T2, because T1's commit-ts 443209725240672283 < T2's start-
ts 443209725240672285.\n  - However, T2 < T1, because T2 observed 5 = 5820, and T1 observed a higher value 5821: a contradiction!"]},
  :timeline {:valid? true},
  :valid? false},
 :valid? false}
 ```

**Comment by seiya-annie** [comment]
[kv3.log.gz](https://github.com/tikv/tikv/files/12226408/kv3.log.gz)
[kv4.log.gz](https://github.com/tikv/tikv/files/12226412/kv4.log.gz)

**Comment by seiya-annie** [comment]
wait following issue be merged, and then check if the issue is still exist
https://github.com/tikv/tikv/issues/14390
https://github.com/tikv/tikv/issues/15242
https://github.com/tikv/tikv/issues/14992

**Comment by zhangjinpeng87** [comment]
Close this issue temporarily since Dynamic Regions project is paused.
