### ISSUE TITLE
[Dynamic Regions] QPS is severe jitter after inject one of tikv network latency with enable evict-slow-trend-scheduler

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#15267]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   284ff3a9ca144619f5efaa357d6c287f1c669982
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-07-31 11:44:07
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-08-01T21:58:35.004+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc with 2w warehouse and 32 thread
2、inject one of tikv network latency 50ms and last for 10m

### What did you expect?
qps can recover within 2min with  enable evict-slow-trend-scheduler

### What did happened?
QPS is severe jitter after inject one of tikv network latency with enable evict-slow-trend-scheduler
![256bd4ac-d102-4103-8f5c-bd036f38239a](https://github.com/tikv/tikv/assets/84712107/e41a6db7-8047-41e8-ad80-48ee2d8acc45)
![img_v2_223dc695-f02c-4c90-9e65-76dbf003ffbg](https://github.com/tikv/tikv/assets/84712107/9d785433-8ead-4947-a270-c9c07fbdb4d8)

**Comment by tonyxuqqi** [comment]
cc @LykxSassinator
