### ISSUE TITLE
Code of Conduct update to replace mediator email with the CNCF committee email

### ISSUE THREAD

**Issue by geekygirldawn** [tikv/tikv#15273]
The CNCF recently formed a Code of Conduct Committee to replace the mediator that was listed as the contact point in the CNCF code of conduct. 

Since the CNCF no longer works with that mediator, can you update your code of conduct with the new contact details: CNCF Code of Conduct Committee - conduct@cncf.io?

It looks like you need to update it in 2 files:
* https://github.com/tikv/tikv/blob/master/CODE_OF_CONDUCT.md
* https://github.com/tikv/async-speed-limit/blob/master/CODE_OF_CONDUCT.md

Here is an example from the updated template:
https://github.com/cncf/project-template/blob/main/CODE_OF_CONDUCT.md

**Comment by overvenus** [comment]
Done, thanks!
