### ISSUE TITLE
raft: add quiescent leader count metric 

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#1531]
Now we have the leader and region count metric for a store, I think we can add a quiescent leader count. 

A quiescent peer means the peer doesn't perform any raft operations like append log / apply log for a time, so we can set quiescent to false if Raft ready has any `committed_entries` or `entries`. 

We can use quiescent leader count to see whether the leader distribution is suitable or not. E.g, each store has 100 leaders, but one store has 90 quiescent leaders. If so, PD may consider schedule the not quiescent leaders to the store. 

/cc @BusyJay @huachaohuang

**Comment by ngaut** [comment]
Let's just add metrics. It's not a clear idea for PD to change the schedule strategy for now.

**Comment by BusyJay** [comment]
I think this can be figured out by written bytes metrics.

**Comment by siddontang** [comment]
not the same. Using written bytes metric we can know the rate active leaders, but we may still want to know it with a Gauge metric.  

Btw, we can check the peer is quiescent or not with written bytes too.

**Comment by BusyJay** [comment]
It's better to implemented this in pd, so TiKV doesn't need to push another metrics and report to pd again. Pd can figure it out by written bytes directly and then report to prometheus.

**Comment by siddontang** [comment]
we can use STORE_PD_HEARTBEAT_GAUGE_VEC directly.

**Comment by brson** [comment]
Is this issue still relevant, and still intended to be implemented in tikv, not pd?

**Comment by siddontang** [comment]
I think we can close it. But another thing is that we may consider support quiescent region.
