### ISSUE TITLE
Feature request: log format in json

### ISSUE THREAD

**Issue by andelf** [tikv/tikv#1532]
We should support json as log format.

**Comment by siddontang** [comment]
How can we do if the json encoded value is too long? truncate?

**Comment by breeswish** [comment]
@Hoverbear PTAL. I think this is now much easier to be implemented.

**Comment by Hoverbear** [comment]
Yeah! I'm happy to take this on, or mentor someone if they'd like to dig in. :)

**Comment by zz-jason** [comment]
I think we can close this issue since the JSON formate has supported in https://github.com/tikv/tikv/pull/7861
