### ISSUE TITLE
TiKV may stuck/panic if a destroy peer message is handled after apply snapshot on raftstore v1

### ISSUE THREAD

**Issue by CalvinNeo** [tikv/tikv#15333]
## Bug Report

Consider a learner node is down when a merging takes place. Then a snapshot of merged target peer will arrive after the node restarts, together with a destroy peer message of source peer.

Consider the apply snapshot is sent and handled before destroy peer, overlap will take place. For Leader, this situation usually do no harm, since a vote request may save us. For Learner, it may stuck if we are using normal mode TiKV, or panic if we are using serverless mode TiKV.

We can't just clean the source peer according to region epoch.

**Comment by tonyxuqqi** [comment]
Does it apply to raftstore-v1 as well? @CalvinNeo

**Comment by CalvinNeo** [comment]
Yes, it applies to raftstore v1. I don't know if is applies to raftstore v2.

**Comment by tonyxuqqi** [comment]
It seems not reproed so far. Close it for now
