### ISSUE TITLE
PiTR resolver may cause TiKV OOM

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#15414]
## Bug Report

Similar to https://github.com/tikv/tikv/issues/14864, PiTR (backup-stream) has its own resolver, and it may cause OOM too.

### What version of TiKV are you using?

\> v6.5.0

### Steps to reproduce

Run a large txn that is much greater than TiKV memory size.

### What did you expect?

No OOM.

### What did happened?

OOM.

**Comment by tonyxuqqi** [comment]
Please help to take care of it all together. Thanks. @overvenus

**Comment by BornChanger** [comment]
Per @overvenus 's suggestion, I assign this issue to @YuJuncen
