### ISSUE TITLE
TiKV's memory usage keeps increases even when region count decreases and block cache cap reaches. 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#15430]
### What did happened?
<img width="811" alt="vEz0hCBQRA" src="https://github.com/tikv/tikv/assets/9442422/736ae72e-1031-4b8b-9e30-e8db7b2c6634">
![Mc09ckIhHN](https://github.com/tikv/tikv/assets/9442422/1a7de6e8-87ad-4e17-b79f-705794034d6e)

**Comment by tonyxuqqi** [comment]
![Mc09ckIhHN](https://github.com/tikv/tikv/assets/9442422/b986ce2a-f2b6-4d92-aa4c-ec5c89eaf448)

**Comment by MimeLyc** [comment]
update
