### ISSUE TITLE
Resolver memory is not reclaimed and may cause OOM

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#15458]
## Bug Report

https://github.com/tikv/tikv/blob/e5efbe697455bd7814c6979df06a8ccf0189909a/components/resolved_ts/src/resolver.rs#L19-L26

TiKV does not reclaim the hashmap in resolver even after all locks are removed.
As a result, memory accumulates over time and may cause OOM, especially for bulk
delete/insert/update workloads that cover many regions. 

Besides the resolver case, we should check all collection type (eg, hashmap and vec)
usage in TiKV code base, make sure they are reclaimed in time.

### What version of TiKV are you using?

\> v4.0.0

### Steps to reproduce

Load a table with many rows, and update all rows in one transaction. 

### What did you expect?

Memory usage before and after the transaction should be the same.

### What did happened?

Memory usage increases.

**Comment by tonyxuqqi** [comment]
Is it because HashMap is not shrunk after the size is reduced a lot?

**Comment by overvenus** [comment]
> Is it because HashMap is not shrunk after the size is reduced a lot?

Exactly.
