### ISSUE TITLE
[Dynamic Regions] periodical performance jitter due to raft-engine log recycle

### ISSUE THREAD

**Issue by glorv** [tikv/tikv#15462]
### What version of TiKV are you using?

nightly

### What operating system and CPU are you using?

aws ec2 m52xlarge(8c64gb with 4000iops 288MB io-bandwidth)

### Steps to reproduce

Deploy a tidb cluster with 1 tikv instance and set replica-count = 1 
use sysbench to  prepare 32 tables with each 10000000 rows of data.
Run sysbench oltp_write_only workload.

The sysbench  scripts is customized with a padding field of 3kb:
```
 CREATE TABLE `sbtest1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `k` bigint(20) NOT NULL DEFAULT '0',
  `c` varchar(300) NOT NULL DEFAULT '',
  `pad` varchar(3000) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `k_1` (`k`)
)
```

### What did you expect?
The performance should be stable when the workload doesn't reach any of the hardware bottleneck.

### What did happened?
The qps is unstable and the qps dropped period match the period when raft-engine's `append-recycle` files count is 0.

![image](https://github.com/tikv/tikv/assets/5196885/08341cf5-f4b7-483a-8e7d-a10ead652586)

![852d002f-c109-4aeb-b815-c3d027d238bc](https://github.com/tikv/tikv/assets/5196885/7cab5d95-5fdc-4d1b-9f57-369a3fc222c0)

![fea554bf-838d-4c72-be66-fe0062a5551c](https://github.com/tikv/tikv/assets/5196885/f95ab7b2-8b46-42c9-8f26-2d7035d39d99)

From the snapshot I can see when the `append-recycle` files count drops to 0 the write duration increases drastically

**Comment by glorv** [comment]
@tabokie @LykxSassinator  Please take a look. When partition-raft-kv is enabled, log compaction may have a longer latency than v1. So maybe we should allow a bigger log file redundancy threshold than the current constant 2.

**Comment by LykxSassinator** [comment]
@glorv FYI, u can have a try by manually opening `raft-engine.prefill-for-recycle` as default when starting. And it will automatically generate the redundant file (recycle logs) as many as possible (count = `raft-engine.purge-threshold` / `raft-engine.target-file-size`), and it will cover this case to avoid the fluctuation when appending if there exists no any more recycle logs. And I think it's enough for your case.

**Comment by glorv** [comment]
@LykxSassinator I have tried `raft-engine.prefill-for-recycle` and it did not solve this problem. And the result matches the metrics in the issue desc as the append-recycle files periodically dropped to 0, pre create some files should have no help in this case.

**Comment by glorv** [comment]
should be fixed by https://github.com/tikv/raft-engine/pull/331
