### ISSUE TITLE
[Titan] the number of live blob file can not be reduced to 0 when enable fallback mode

### ISSUE THREAD

**Issue by dbsid** [tikv/tikv#15507]
### What version of TiKV are you using?

v7.0.0

### What operating system and CPU are you using?

x86
### Steps to reproduce

Load the data and make sure the the total store size is around 100TB, there are 55 stores
1. enable Titan and there is over 70TB in Titan
2. set Titan fallback mode
```
[rocksdb.defaultcf.titan]
blob-run-mode = "fallback"
discardable-ratio = 1.0
```

### What did you expect?
The number of live blob file is reduced to 0

### What did happened?
There are 3 live blob file remaining, each live blob file on 3 TiKV instances. 
Doing a manual compaction on the 3 tikv instances does not remove the live blob files either.

![image](https://github.com/tikv/tikv/assets/2316425/65325a2a-6d9d-4b8b-be65-1386aa2ecd8c)

![image](https://github.com/tikv/tikv/assets/2316425/db90b0b1-59c5-4d93-9e20-78cfc34af361)

**Comment by stevenayu** [comment]
![67b625da-8c3f-45c6-afb7-610d31b55c58](https://github.com/tikv/tikv/assets/28386799/348c1228-f8a1-4e28-b47c-a61fb1f292ab)
v6.5.4 can also reproduce this issue

**Comment by tonyxuqqi** [comment]
No real impact to user behavior, change it to moderate.

**Comment by Connor1996** [comment]
Fixed by https://github.com/tikv/tikv/pull/16338
