### ISSUE TITLE
tikv is crash after ebs volumerestore

### ISSUE THREAD

**Issue by zhongmin-amin** [tikv/tikv#15521]
### Steps to reproduce
1. create cluster
2. do full restore
3. do ebs volumebackup before full restore completed
4. when volumebackup completed, do ebs volume restore

### What did you expect?
1. restore success

### What did happened?
1. tikv is crash
![da75b73a-b3b5-4f52-85c5-7dee609770b1](https://github.com/tikv/tikv/assets/81375082/f4867a32-fb30-46cd-be2b-83eec2584f9e)

**Comment by BornChanger** [comment]
It's duplicated with https://github.com/pingcap/tidb/issues/46850

**Comment by zhongmin-amin** [comment]
duplicate
