### ISSUE TITLE
The `need_restored_data` for multi value index should return false

### ISSUE THREAD

**Issue by YangKeao** [tikv/tikv#15531]
In tidb, `need_restored_data` for multi value index should return false, as the `tp` will become `JSON` when it's marked as an array. I'm not sure whether it's good to modify `get_tp()` to return `json` for every type, but at least we should ignore the `RestoredData` for json, or it will report an error.

**Comment by YangKeao** [comment]
This issue also affects 7.1

**Comment by tonyxuqqi** [comment]
cc @Benjamin2037

**Comment by YangKeao** [comment]
This issue should have been closed by https://github.com/pingcap/tidb/pull/46993. TiDB will set the collation of multi-valued index as `binary`. Sorry, I forgot to close it after merging #46993.
