### ISSUE TITLE
Load base split cannot work with stale read if all reads occurs on the follower

### ISSUE THREAD

**Issue by nolouch** [tikv/tikv#15539]
### What version of TiKV are you using?
6.5.4

### Steps to reproduce
run traffic 30K QPS stale read traffic across 100 keys which consumed 8 cores on TiKV node, but region was not split and moved to other node, deploy in multi-az, and use stale read with:
```
tidb_read_staleness="-60"

tidb_replica_read=closest-replicas
```

### What did you expect?

Load Balanced.

### What did happened?
We can see from metrics and log, tikv tries to split the hot region according to the load base strategy, but it cannot execute on follower peer.
Currently, the follower cannot pass the `pre_propose_raft_command` to proposal a raft_command. all proposals in tikv should be handled in `leader`.
https://github.com/tikv/tikv/blob/f1349113c1465d06fef974ecf95da653a3e3cb8b/components/raftstore/src/store/fsm/peer.rs#L5043-L5058
Details metrics:
![image](https://github.com/tikv/tikv/assets/6428910/b66ef0f1-835b-4343-b5a2-15868d592458)
![image](https://github.com/tikv/tikv/assets/6428910/f9158341-f3c3-4988-b4b0-054090ae2811)
![image](https://github.com/tikv/tikv/assets/6428910/a94cd49f-5a50-47c8-9533-92acdeb47b32)

**Comment by nolouch** [comment]
Consider forward a message to the leader in the `raftstore`. compared with forward in raft layer,  it's a smaller change to the current logic.

**Comment by cfzjywxk** [comment]
@nolouch 
Is it a bug or an enhancement?
