### ISSUE TITLE
[Dynamic Regions] resolved ts can't  advance for long time

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15623]
### What version of TiKV are you using?

TiKV
Release Version:   7.4.0-alpha
Edition:           Community
Git Commit Hash:   e43a157c4a35034dfd705bdd94fac6d958e8a1ff
Git Commit Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:    2023-09-14 11:47:25
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

The cluster contains about 60 tikv with dynamic region enabled, each tikv contains 2.5TB data, a table contains about 6billion rows with each row size about 10kb.
![b8ae02ef-9ddc-4571-aa78-753117c01a19](https://github.com/tikv/tikv/assets/7677963/d3803ef4-1634-4a85-971c-1e9a51014153)

**Comment by overvenus** [comment]
After region merge, TiKV creates a GcPeerRequest with incorrect information. This leads to a misleading GcPeerResponse, causing the target region leader to mistakenly think that the source peers have been garbage collected. As a result, the source peers are left abandoned indefinitely, leading to a stuck resolved ts.

https://github.com/tikv/tikv/blob/4a5fb7321ca2ee2bab0b31f6556c8fb196a590f4/components/raftstore-v2/src/operation/life.rs#L702-L711

After merge, removed peer may come from source region.
