### ISSUE TITLE
[Dynamic Regions] Compared with 7.3.0, write-heavy workloads have 7.6% - 31% performance regression

### ISSUE THREAD

**Issue by Yui-Song** [tikv/tikv#15630]
### What version of TiKV are you using?

nightly

### What operating system and CPU are you using?

arm64 openEuler

### Steps to reproduce

1. deploy tidb clusters with 3 tidb + 3 tikv + 1pd with version 7.3.0 and nightly
2. set tikv-configs: "{storage: {engine: partitioned-raft-kv}, coprocessor: {region-split-size: 1GB, region-max-size: 1.5GB}}" 
3. run the following benchmarks 
 - sysbench oltp_delete, oltp_update_index, oltp_write_only, oltp_read_write
 - benchmarksql
 

### What did you expect?
No performance regression

### What did happened?
Write-heavy workloads have 7.6% - 31% performance regression
![image](https://github.com/tikv/tikv/assets/84501897/5d7bb7a0-3e2a-4d3a-805f-a265695adb79)

**Comment by tonyxuqqi** [comment]
@glorv  PTLA.  Compare the 7.3 and 7.4's metrics on these big regression workloads.

**Comment by glorv** [comment]
Seems this is the side-effect of a smaller default lock-cf write-buffer-size introduced in #15453. The smaller default write buffer size will trigger more flush and level-0 compaction which will consume a lot of cpu and io, and thus have a non-trivial performance impact.
Take oltp_update_index as a example:
metrics of v7.3:

![ba3eee7e-c7c1-490c-965a-368b3cda6543](https://github.com/tikv/tikv/assets/5196885/85b06ad4-91f5-49f7-ad51-0ab7159e3842)
![a1d8e6e9-37ef-4c6f-a552-afb502736002](https://github.com/tikv/tikv/assets/5196885/ea3bd295-0577-4eb5-a533-4d151a261408)

metrics of v7.4 nightly:

![bcecf5f3-268a-4a77-8ad0-a03fd68714df](https://github.com/tikv/tikv/assets/5196885/03b7d5d1-580e-458b-8218-377079a4deac)
![e47b0ebf-5fc3-4a0d-bf16-9f91290a69bf](https://github.com/tikv/tikv/assets/5196885/f0614de7-6073-4808-a443-c95f10a6447c)

@SpadeA-Tang will file a pr to adjust the default lock-cf write-buffer-size and make this config dynamic configurable. We can rerun these cases after the change is merged.
