### ISSUE TITLE
Should we set the dependencies with patch version to make building reproducible?

### ISSUE THREAD

**Issue by wuhuizuo** [tikv/tikv#15654]
## Question

Should we set the dependencies with patch version in `Cargo.toml` file to make building reproducible?

Such as:
from `tempfile = "3.0"` to `tempfile = "3.0.8"`

Ref: https://github.com/tikv/tikv/blob/master/Cargo.toml

**Comment by Connor1996** [comment]
With Cargo.lock, the build is reproducible

**Comment by wuhuizuo** [comment]
Solved.
