### ISSUE TITLE
[Dynamic Regions] resolved ts can't advance in big cluster scenario

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15672]
### What version of TiKV are you using?

Release Version:   7.4.0-alpha
Edition:           Community
Git Commit Hash:   bbfedd409b5965c04b9edcb34f0a0907c75d6dd2
Git Commit Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:    2023-09-22 11:51:22
Rust Version:      rustc 1.73.0-nightly (180dffba1 2023-08-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

The cluster contains about 50 tikv with dynamic region enabled, each tikv contains 2.5TB data, a table contains about 6billion rows with each row size about 10kb. insert, large delete and select workload.
![3e0abebe-ee21-4dee-acfc-c42fc423bfc0](https://github.com/tikv/tikv/assets/7677963/81d178db-8e2e-4eba-8699-b9fe38e85f25)

**Comment by overvenus** [comment]
Resolved ts is blocked by an orphan peer, which its peers are all merged by a target region. The target region does not register GcPeer tick after CommitMerge, so the orphan peer is left behind for a very long time.
