### ISSUE TITLE
Bucket update triggers too many GetRegionByID requests and make PD overwhelmed 

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#15719]
### What version of TiKV are you using?

7.1.1
### Steps to reproduce

In a 200 TiDB nodes cluster, with region size 256MB, bucket size 96MB. 
By default, the region bucket is enabled as 256MB > 2*96MB (https://github.com/tikv/tikv/pull/14255 )
And it could lead to PD overwhelmed as it could get 50K+ qps GetRegionByID calls. 

### What did you expect?
After upgrade from 6.5 to 7.1, the cluster should work.
### What did happened?
PD is overwhelmed and the cluster is not usable. 

{"level":"ERROR","time":"2023/10/06 20:43:31.432 +00:00","caller":"region_cache.go:2034","message":"failed to update buckets","region":"{ region id: 1454572, ver: 492, confVer: 150 }","bucketsVer":55834574848,"latestBucketsVer":60129542
144,"error":"","errorVerbose":"\[ngithub.com/tikv/client-go/v2/internal/retry.(*Backoffer).BackoffWithCfgAndMaxSleep\n\t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:160\ngithub.c](http://ngithub.com/tikv/client-go/v2/internal/retry.(*Backoffer).BackoffWithCfgAndMaxSleep/n/t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:160/ngithub.c)
om/tikv/client-go/v2/internal/retry.(*Backoffer).Backoff\n\t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:120\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadReg](http://github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:120/ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadReg)
ionByID\n\t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1595\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1\n\t/go/pkg/mod/github](http://github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1595/ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1/n/t/go/pkg/mod/github)
.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:2032\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\[ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegionByID\n](http://ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegionByID/n)
\t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1597\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1\n\t/go/pkg/mod/github.com/tikv](http://github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1597/ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1/n/t/go/pkg/mod/github.com/tikv)
/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:2032\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"}
{"level":"ERROR","time":"2023/10/06 20:43:31.430 +00:00","caller":"region_cache.go:2034","message":"failed to update buckets","region":"{ region id: 93795433, ver: 506, confVer: 176 }","bucketsVer":0,"latestBucketsVer":42949672960,"erro
r":"","errorVerbose":"\[ngithub.com/tikv/client-go/v2/internal/retry.(*Backoffer).BackoffWithCfgAndMaxSleep\n\t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:160\ngithub.com/tikv/c](http://ngithub.com/tikv/client-go/v2/internal/retry.(*Backoffer).BackoffWithCfgAndMaxSleep/n/t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:160/ngithub.com/tikv/c)
lient-go/v2/internal/retry.(*Backoffer).Backoff\n\t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:120\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegionByID\n](http://github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/retry/backoff.go:120/ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegionByID/n)
\t/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1595\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1\n\t/go/pkg/mod/github.com/tikv](http://github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1595/ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1/n/t/go/pkg/mod/github.com/tikv)
/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:2032\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\[ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegionByID\n\t/go/pkg](http://ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegionByID/n/t/go/pkg)
/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1597\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1\n\t/go/pkg/mod/github.com/tikv/client-g](http://github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1597/ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1/n/t/go/pkg/mod/github.com/tikv/client-g)
o/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:2032\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"}

**Comment by tonyxuqqi** [comment]
cc @bufferflies Please cherry pick the bucket split/merge logic to 7.1 and 6.5 if code change is not big.

**Comment by dbsid** [comment]
TiDB goroutine for GetRegionByID

```
11 @ 0x19dd096 0x19ed79e 0x1f8c77c 0x2017225 0x201720e 0x20165e5 0x2014f64 0x2016251 0x1ff2db7 0x1ff2c45 0x2232c09 0x233c13a 0x2362854 0x253e87b 0x254b0e4 0x254f3fc 0x1a12c41
# labels: {"plan_digest":"\xb5\xed!\x89VDK_\xe3\xf7%ػ\xa1\xf6\xdc\x05\xcf\xcc1\xa2e\xcat\x1f\xda৳\f\xc75", "sql_digest":"\xb3\x1b\xb7\xefO\\\x05N\x92&\x02\xc4\x1b\xe6\xe6\xe7\xe5 \x1c\xfa\x1f,\xbc\xccL`s\xae\x9fX\x80\xe4"}
#	0x1f8c77b	google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader+0x7b				/go/pkg/mod/google.golang.org/grpc@v1.54.0/internal/transport/transport.go:331
#	0x2017224	google.golang.org/grpc/internal/transport.(*Stream).RecvCompress+0xc4				/go/pkg/mod/google.golang.org/grpc@v1.54.0/internal/transport/transport.go:346
#	0x201720d	google.golang.org/grpc.(*csAttempt).recvMsg+0xad						/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:1058
#	0x20165e4	google.golang.org/grpc.(*clientStream).RecvMsg.func1+0x24					/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:909
#	0x2014f63	google.golang.org/grpc.(*clientStream).withRetry+0x143						/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:760
#	0x2016250	google.golang.org/grpc.(*clientStream).RecvMsg+0x130						/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:908
#	0x1ff2db6	google.golang.org/grpc.invoke+0xd6								/go/pkg/mod/google.golang.org/grpc@v1.54.0/call.go:73
#	0x1ff2c44	google.golang.org/grpc.(*ClientConn).Invoke+0x264						/go/pkg/mod/google.golang.org/grpc@v1.54.0/call.go:37
#	0x2232c08	github.com/pingcap/kvproto/pkg/pdpb.(*pDClient).GetRegionByID+0xc8				/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20230523065550-8b641fa69bf3/pkg/pdpb/pdpb.pb.go:8684
#	0x233c139	github.com/tikv/pd/client.(*client).GetRegionByID+0x3b9						/go/pkg/mod/github.com/tikv/pd/client@v0.0.0-20230519121736-d15a686a670e/client.go:781
#	0x2362853	github.com/tikv/client-go/v2/util.InterceptedPDClient.GetRegionByID+0xb3			/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/util/pd_interceptor.go:116
#	0x253e87a	github.com/tikv/client-go/v2/internal/locate.(*CodecPDClient).GetRegionByID+0x3a		/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/pd_codec.go:112
#	0x254b0e3	github.com/tikv/client-go/v2/internal/locate.(*RegionCache).loadRegionByID+0x323		/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:1601
#	0x254f3fb	github.com/tikv/client-go/v2/internal/locate.(*RegionCache).UpdateBucketsIfNeeded.func1+0xbb	/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20230713054852-a3875bcbc94f/internal/locate/region_cache.go:2032

```
