### ISSUE TITLE
br: pitr-task stuck and log shows "failed to get initial snapshot: failed to get the snapshot"

### ISSUE THREAD

**Issue by AkiraXie** [tikv/tikv#15714]
### What version of TiKV are you using?

/tikv-server -V
TiKV
Release Version:   7.4.0-alpha
Edition:           Community
Git Commit Hash:   bbfedd409b5965c04b9edcb34f0a0907c75d6dd2
Git Commit Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:    2023-09-22 11:51:22
Rust Version:      rustc 1.73.0-nightly (180dffba1 2023-08-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

open pitr
### What did happened?
pitr stuck

logs:
```
2023-09-26 16:55:54 (UTC+08:00)TiKV maincluster-tikv-8.maincluster-tikv-peer.stable-testbed-47l4r.svc:20160[errors.rs:176]  ["backup stream meet error"] [verbose_err="Contextual { context: \"failed to get initial snapshot: failed to get the snapshot  (region_id = 1276484)\", inner_error: RaftRequest(message: \"read index not ready, reason can not read index due to merge, region 1276484\" read_index_not_ready { reason: \"can not read index due to merge\" region_id: 1276484 }) }"] [err="failed to get initial snapshot: failed to get the snapshot (region_id = 1276484): Error during requesting raftstore: message: \"read index not ready, reason can not read index due to merge, region 1276484\" read_index_not_ready { reason: \"can not read index due to merge\" region_id: 1276484 }"] [context="during getting initial snapshot for region id: 1276484 start_key: 748000000000009DFF2C5F728000000005FFC875E10000000000FA end_key: 748000000000009DFF2C5F72800000000CFF1B71680000000000FA region_epoch { conf_ver: 216 version: 3111 } peers { id: 1276485 store_id: 6 } peers { id: 1276486 store_id: 7 } peers { id: 1276487 store_id: 10 role: Learner } peers { id: 1276488 store_id: 11 role: Learner } peers { id: 1276489 store_id: 19 }; can retry = true"]
```

**Comment by YuJuncen** [comment]
This log isn't the real cause. For an unknown reason, initial scanning queue has been stuck.
The regions encountered error are recovered soon.

<img width="390" alt="image" src="https://github.com/tikv/tikv/assets/36239017/aa94f0b0-6132-4419-8e6c-11a88c422031">

**Comment by YuJuncen** [comment]
Also I have tried to reproduce this in latest master with TPCC workload and `shuffle-region-scheduler`. It seems this cannot be reproduced in the latest master for a 4 days run. I'm not sure whether there are some problems about other components or something else.

**Comment by YuJuncen** [comment]
And, I guess this is probably caused by a background panic. Could you upload the stderr log of TiKV?

**Comment by YuJuncen** [comment]
The reason is probably we have moved the execution of storing events to local file to the initial scanning pool, but it doesn't enable the io reactor. Hence once the memory tempfile pool reaches its limit, it will panic during swapping contents out.

**Comment by YuJuncen** [comment]
> The reason is probably we have moved the execution of storing events to local file to the initial scanning pool, but it doesn't enable the io reactor. Hence once the memory tempfile pool reaches its limit, it will panic during swapping contents out.

Nope, writing to local files doesn't requires the IO reactor. we need further digging this by `async-backtrace`.

**Comment by BornChanger** [comment]
@AkiraXie please manage to re-produce the problem with the async-backtrace enhancement.

**Comment by YuJuncen** [comment]
```
--
4505853076451622926
└[components/backup-stream/src/subscription_manager.rs:241] [span_id=4505853076451622926] ["exec_initial_scan"] [region=7187021] [handle="ObserveId(326894)"] [elapsed=58080.514s]
 └[components/backup-stream/src/subscription_manager.rs:201] [span_id=5224177217017217027] ["exec_by_with_retry"] [elapsed=58080.514s]
  └[components/backup-stream/src/subscription_manager.rs:181] [span_id=4382004086698934300] ["exec_by"] [elapsed=58080.514s]
   └[components/backup-stream/src/event_loader.rs:428] [span_id=5974026554974404615] ["do_initial_scan"] [elapsed=58079.534s]
    └[components/backup-stream/src/event_loader.rs:374] [span_id=4517112075520049174] ["scan_and_async_send"] [elapsed=58079.534s]
     └[components/backup-stream/src/event_loader.rs:413] [span_id=6131652541932371986] ["self.quota.pending(event_size)"] [event_size="640387033"] [elapsed=58075.904s]
```

There is a task requires memory more than the memory quota. Then the whole semaphore gets stuck. Perhaps this is a bug (or feature) in the semaphore implementation. Anyway we can workaround this by getting rid of this memory quota.

**Comment by YuJuncen** [comment]
Theoretically this will only happen on clusters with huge lines and #15541 may not really contributes to this.

**Comment by YuJuncen** [comment]
Given #15541 has been delivered to release-7.1, this may affect release-7.1 too. (I guess event w/o #15541 this will affect all older versions...)
