### ISSUE TITLE
Need a standalone space holder file for raft engine

### ISSUE THREAD

**Issue by jackysp** [tikv/tikv#15718]
### What version of TiKV are you using?

v6.5.4

### What operating system and CPU are you using?

Linux

### Steps to reproduce

1. Setup a standalone raft engine data dir (not the same dir of the default data dir of TiKV)
2. Make some no space left error on the raft engine dir
3. Try to recover this TiKV

### What did you expect?
It should be possible to delete the space holder file to release some spaces for raft engine.

### What did happened?

No such file and get some error logs

```
[2023/10/04 20:42:12.390 +00:00] [WARN] [server.rs:583] ["failed to remove space holder on starting: No such file or directory (os error 2)"]
[2023/10/04 20:42:12.390 +00:00] [WARN] [server.rs:592] ["no enough disk space left to create the place holder file"]
```

**Comment by LykxSassinator** [comment]
Nope, this issue can be canceled. 

As discussed offline, and the reason why `place-holder` file cannot be created is that the setting `config.reserve_space` is too big to make the disk reserve free space to create a `place-holder` file. It's clear.
https://github.com/tikv/tikv/blob/88aaaa3e7b1e194d389fee6a9831f7491d7f9acd/components/server/src/common.rs#L201-L215

And as for seperated raft disk in this case, it's also check the above strategy in https://github.com/tikv/tikv/blob/88aaaa3e7b1e194d389fee6a9831f7491d7f9acd/components/server/src/common.rs#L238C4-L253.

So, it's not a bug. This tikv node behaved as expected.
