### ISSUE TITLE
[Dynamic Regions] Compared with v7.3.0, TPCC has a 8% ~ 29% performance regression

### ISSUE THREAD

**Issue by Yui-Song** [tikv/tikv#15735]
### What version of TiKV are you using?

v7.3.0 and nightly
### Steps to reproduce

1. deploy clusters with both v7.3.0 and nightly versions (3 tidb + 3 tikv + 1 pd)
2. cluster configs:
```
TidbConfig:{"mem-quota-query":1073741824,"new_collations_enabled_on_first_bootstrap":false,"prepared-plan-cache":{"enabled":true}}; 
TikvConfig:{"coprocessor":{"region-max-size":"1.5GB","region-split-size":"1GB"},"import.num-threads":64,"storage":{"engine":"partitioned-raft-kv"},"storage.block-cache.capacity":"30GB"}"
```
3. run go-tpc tpcc 1000 warehouses

### What did you expect?
No performance regression.
### What did happened?
 Compared with v7.3.0 (baseline), TPCC has a 8% ~ 29% performance regression.
![image](https://github.com/tikv/tikv/assets/84501897/b0950aff-374f-48a7-8b59-752baa9e2408)

**Comment by tonyxuqqi** [comment]
This is because of the lockcf write buffer limit's behavior, that if it's too small, it would hurt the write heavy workload. 
But if it's big, then it would hurt read-write workload with too many MVCC versions.

**Comment by tonyxuqqi** [comment]
Dup with https://github.com/tikv/tikv/issues/15736
