### ISSUE TITLE
TiKV reports ServerIsBusy error because it can not append raft log

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#15800]
## Bug Report

We met an issue that TiKV keeps server is busy when a tiflash node runs out of disk.

The "Server is busy" error occurs because the raft log cannot be append. The inability to append is caused by the rejection of raft log. The rejection is due to high memory usage in tikv to prevent out-of-memory (OOM) errors. The high memory usage in tikv is a result of caching a large number of raft logs. The reading of a large number of logs is likely caused by tiflash becoming stuck, resulting in a significant lag in the raft log.

<details><summary>Metrics</summary>
<p>

![image](https://github.com/tikv/tikv/assets/2150711/f76dfc2b-342e-4b9a-9cf6-ead75c6e9c8b)
![image](https://github.com/tikv/tikv/assets/2150711/93430ebf-7c75-4ad2-9a3d-65157730081a)
![image](https://github.com/tikv/tikv/assets/2150711/94c2bbab-123b-4cec-bd3b-ea20777d9f11)
![image](https://github.com/tikv/tikv/assets/2150711/c6eda0db-4dac-416c-8fcf-a9fd9aac3ed9)
![image](https://github.com/tikv/tikv/assets/2150711/fc96e83c-21c6-41ea-9b73-7c8c266eefad)

</p>
</details> 

Touch https://github.com/tikv/tikv/issues/14874, tikv log is also overwhelmed with the log "cannot step raft local message".

To resolve the issue, we can:
1. Optimize the memory allocation strategy for each component to avoid such "deadlock" situation.
2. Reject prewrite/commit and other write requests from TiDB, so that no more raft log will be proposed.

### What version of TiKV are you using?

v6.5.4.

### Steps to reproduce

It's not clear.

### What did you expect?

Do not keep server is busy.

### What did happened?

Server is busy.

**Comment by tonyxuqqi** [comment]
update raftstore.evict-cache-on-memory-ratio = 0.15, then it would evict cache when memory ratio is more than 85%.

**Comment by tonyxuqqi** [comment]
It's fixed in 7.5 already by setting raftstore.evict-cache-on-memory-ratio = 0.1
