### ISSUE TITLE
tikv oom when running large-row-values workload

### ISSUE THREAD

**Issue by AkiraXie** [tikv/tikv#15805]
### What version of TiKV are you using?

Release Version:   7.5.0-alpha
Edition:           Community
Git Commit Hash:   b4e0bf7bab6ad395b74c0be938119d82ded4cd2a
Git Commit Branch: heads/refs/tags/v7.5.0-alpha
UTC Build Time:    2023-10-13 11:50:39
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What operating system and CPU are you using?

linux amd64
### Steps to reproduce

1. running large-row-values workload and tps=3000, rowsize=1M

### What did happened?
tikv oom

**Comment by tonyxuqqi** [comment]
@AkiraXie What's the workload to repro it? Is it sysbench prepare or insert?

**Comment by tonyxuqqi** [comment]
@AkiraXie Please specify the TiKV's available memory in this case.

**Comment by afeinberg** [comment]
@AkiraXie can you paste the sysbench commands you used to trigger this? also please let us know the amount of memory available to tikv.

**Comment by overvenus** [comment]
From profile, the major memory consumption is from PiTR components:

1. `backup_stream::event_loader::EventLoader::fill_entries` takes about 36%, it creates too many iterators, same as https://github.com/tikv/tikv/issues/10114 .
2. `backup_stream::router::RouterInner::on_events` uses `zstd_safe::CCtx::try_create` which takes about 47.4%.

| Zstd | RocksDB Iterator |
|--------|--------|
| ![image](https://github.com/tikv/tikv/assets/2150711/15aa7af6-23d1-4fe6-8732-935827e3dfc8) | ![image](https://github.com/tikv/tikv/assets/2150711/3cb103d5-8122-40db-b504-c79094027e2e)| 

Full profile: [profile-3-10-24-02-13-04.zip](https://github.com/tikv/tikv/files/13160751/profile-3-10-24-02-13-04.zip)

**Comment by AkiraXie** [comment]
> @AkiraXie can you paste the sysbench commands you used to trigger this? also please let us know the amount of memory available to tikv.

emm,this workload is not sysbench command ; tikv memory available is 32G

**Comment by AkiraXie** [comment]
after #15714 closed, the situation was not seen
