### ISSUE TITLE
Write QPS drops to 0 after TiKV Restart

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#15864]
### What version of TiKV are you using?

v6.5 
### Steps to reproduce

Have some heavy write and restart one TiKV
### What did you expect?
QPS is not impacted
### What did happened?
QPS drops to nearly 0
<img width="608" alt="Screen Shot 2023-10-27 at 11 26 45 AM" src="https://github.com/tikv/tikv/assets/9442422/b9783840-cc1c-42c5-b820-becf98ea0380">

It may be due to slow disk in this case, however after restart, the block cache hit rate is low initially and also pending raft logs needs to apply. These two IO burst would make TiKV's performance bad initially.

**Comment by LykxSassinator** [comment]
dup with: https://github.com/tikv/tikv/issues/15874
