### ISSUE TITLE
RawKV TTL expire traffic statistics

### ISSUE THREAD

**Issue by Smityz** [tikv/tikv#15873]
### Is your feature request related to a problem? Please describe:

I want to see the data traffic of expired and deleted data with current TTL, and compare it with the current cluster write traffic, so that I can estimate whether the cluster needs to be scaled up.

### Describe the feature you'd like:

I found a similar issue https://github.com/tikv/tikv/issues/13436, but it only shows data expire when backup. I want a monitor shows data expired traffic when serving.

@haojinming @pingyu Do we have plans to support this feature?

**Comment by pingyu** [comment]
What does "data traffic" of expired and deleted data mean, read requests on expired or deleted data ?

Besides, I think main machine metrics (e.g., CPU, memory, disk utilization & usage) are enough for scaling judgement, why you need the "data traffic" ?

**Comment by Smityz** [comment]
I mean I want to see the statistics of expired and deleted data due to TTL in the background, so that I can determine if the cluster is running properly with the correct TTL settings

**Comment by pingyu** [comment]
There is a metrics panel in Grafana for TTL at "TiKV-Details -> TTL". Please take a look for whether it can help you.

And the collection for expired or deleted data is done in process of compaction. You can find metrics for compaction in "TiKV-Details -> RocksDB - kv". Please also refer to https://github.com/tikv/tikv/pull/12853.

**Comment by Smityz** [comment]
Thanks for your suggestion! 
https://github.com/tikv/tikv/pull/12853 This is the metric I want. But I found it does not work in v1_ttl

**Comment by pingyu** [comment]
I think it's a good idea. Could you come and add the metrics? That would be great~

Implementation of compaction filter for V1 TTL is [here](https://github.com/tikv/tikv/blob/0a34c6f4798e6462739152d2364a202996009984/src/server/ttl/ttl_compaction_filter.rs#L18). And you can refer to the implementation for V2 [here](https://github.com/tikv/tikv/blob/0a34c6f4798e6462739152d2364a202996009984/src/server/gc_worker/rawkv_compaction_filter.rs#L205).

**Comment by Smityz** [comment]
Okay, you can assign this task to me
