### ISSUE TITLE
resolved ts can't advance in the batch insert wide table scenario

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15916]
### What version of TiKV are you using?

TiKV
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   0a34c6f4798e6462739152d2364a202996009984
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2023-10-30 11:50:30
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

10 tikv with titan enable
prepare about 20TB sysbench data, and the column `pad` of wide table generated value length is from 100B to 50KB.
### What did you expect?
![image](https://github.com/tikv/tikv/assets/7677963/afd78393-d7b6-409f-97f1-9e83b0d2e35a)

**Comment by overvenus** [comment]
The issue is caused by #15919

**Comment by lilinghai** [comment]
fixed by https://github.com/tikv/tikv/pull/15934
