### ISSUE TITLE
lightning Import sst lost after tikv restart

### ISSUE THREAD

**Issue by aytrack** [tikv/tikv#15912]
### What version of TiKV are you using?

```bash
[root@lightning-0 /]# ./tidb-lightning -V
Release Version: v7.6.0-alpha
Git Commit Hash: a565692dab68be58b12c582470e241e1169f2022
Git Branch: heads/refs/tags/v7.6.0-alpha
Go Version: go1.21.3
UTC Build Time: 2023-10-26 11:39:17
Race Enabled: false

[root@tc-tikv-1 /]# ./tikv-server  -V
TiKV
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   78d835d91b07fb5c18e1158c21841fd43116bc02
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2023-11-01 11:54:32
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

### Steps to reproduce

1. lightning Import data using local tikv-importer
2. restart tikv
### What did you expect?
all tikv nodes will restart without ERROR
### What did happened?
1 tikv node can't start beacus lost lightning Import sst file
![图片](https://github.com/tikv/tikv/assets/10184437/57f7cfa6-63f2-475a-888c-1202f116f742)

**Comment by lance6716** [comment]
The root cause is we changed the filename pattern in https://github.com/tikv/tikv/pull/15795 . And when old version TiKV generate the file and new version TiKV reads it, the filename is changed so report "file not found" error
