### ISSUE TITLE
cb27f2 causes 6%- 10% QPS regression in CH benchmark on ARM64

### ISSUE THREAD

**Issue by Yui-Song** [tikv/tikv#15926]
### What version of TiKV are you using?

https://github.com/tikv/tikv/pull/15726 

### What operating system and CPU are you using?

```
[root@172 ~]# lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    1
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          4
Model:                 0
CPU max MHz:           2600.0000
CPU min MHz:           200.0000
BogoMIPS:              200.00
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              32768K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
NUMA node2 CPU(s):     32-47
NUMA node3 CPU(s):     48-63
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop


[root@172 ~]# cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop
CPU implementer	: 0x48
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd01
CPU revision	: 0

processor	: 1
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop
CPU implementer	: 0x48
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd01
CPU revision	: 0
```

### Steps to reproduce

1. deploy a tidb cluster with 3 tidb + 3tikv + 2tiflash with baseline (v7.1.0) and commit cb27f24b89c8107c9ead57be5016ee779996ac25.
2. run ch-benchmark. 

### What did you expect?
No performance regression.

### What did happened?
There was a 6%- 10% QPS regression in CH benchmark on ARM64.
![image](https://github.com/tikv/tikv/assets/84501897/39548890-9e3c-4b9a-b663-b637f4ddae2b)

**Comment by cfzjywxk** [comment]
From the code the https://github.com/tikv/tikv/pull/15726 should not have effect on normal read writes but only stale read requests.  I think the regression is unrelated to the https://github.com/tikv/tikv/pull/15726 but because of some other reasones.

**Comment by Yui-Song** [comment]
Reproducing the regression with v7.1.0. It seems that the regression is caused by environmental issues. Close this issue.
/close
