### ISSUE TITLE
If titan is enabled for the backup cluster, tikv will crash if titan is not enabled for restore.

### ISSUE THREAD

**Issue by zhongmin-amin** [tikv/tikv#15945]
### Steps to reproduce

1. config tikv titan true
2. do volumebackup
3. restore the cluster, config tikv titan false

### What did you expect?
1. There are documents telling users not to use it this way.

### What did happened?
1. tikv crash
![img_v2_0a19fb25-4412-421f-af64-dfe77b1b7ebg](https://github.com/tikv/tikv/assets/81375082/85c57f85-ab8c-41d7-801b-641e1c7aa9dc)

**Comment by Connor1996** [comment]
It's not only about titan. Config should remain consistent before and after for ebs backup/restore. /cc @BornChanger

**Comment by lilinghai** [comment]
Maybe we should explicitly inform users in the user documentation not to perform such erroneous operations.
