### ISSUE TITLE
Is there any easy way to add a panel of grafana json?

### ISSUE THREAD

**Issue by Smityz** [tikv/tikv#15950]
## Question

I wrote a PR https://github.com/tikv/tikv/pull/15949/files to add some metrics, but I found it was not easy to update grafana json file like `metrics/grafana/tikv_details.json`, is there any easy way to add a panel?
![image](https://github.com/tikv/tikv/assets/22953824/f934626c-022c-4a51-aa9f-a0e82042d6e3)

**Comment by overvenus** [comment]
There is an ongoing effort that can ease the troublesome #15857, but until then you can refer to https://github.com/tikv/tikv/issues/12796#issuecomment-1154954486
