### ISSUE TITLE
vscode 调试单元测试无法断点查看变量 value

### ISSUE THREAD

**Issue by LeoYang90** [tikv/tikv#15965]
## Development Task
![image](https://github.com/tikv/tikv/assets/16485583/2044c522-cb25-4c2e-9fa9-be76ab7088a2)

![image](https://github.com/tikv/tikv/assets/16485583/4ecb4b77-42ca-488a-bff9-c1614647462e)

如何修改配置才能查看 debug 变量信息呢？

**Comment by overvenus** [comment]
I haven't tried vscode debug, usually I add `debug!` log. Maybe you can run the command below.
```
export CI=1
export LOG_FILE=/tmp/test.log 
cargo test -p tests -- --test test_rawkv
```

**Comment by ou-bing** [comment]
https://github.com/tikv/tikv/issues/5572#issuecomment-539884724
参考这个？

**Comment by LeoYang90** [comment]
> [#5572 (comment)](https://github.com/tikv/tikv/issues/5572#issuecomment-539884724) 参考这个？

厉害了 的确可以
