### ISSUE TITLE
Titan store size metric is not accurate

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15971]
### What version of TiKV are you using?

Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   e0fe14d57136f645457bcf14ee5ae1a478be04b8
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2023-11-03 11:51:51
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

sysbench wide table read_write workload
![8e3352e1-ec8b-4b79-b5df-a7bfc72ff942](https://github.com/tikv/tikv/assets/7677963/b0e4491a-7bcd-4fa0-94e8-5a786fadaf1f)
```
[root@tc-tikv-2 data]# du -h -d 1
12K	./import
194M	./snap
12G	./raft-engine
3.1T	./db
3.1T	.
```

**Comment by JasonWu0506** [comment]
@tonyxuqqi  impacted version information?
