### ISSUE TITLE
tikv-ctl modify titan config Invalid argument error

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#15978]
### What version of TiKV are you using?

TiKV
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   e0fe14d57136f645457bcf14ee5ae1a478be04b8
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2023-11-03 11:51:51
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

[root@tc-tikv-2 /]# /tikv-ctl --host [127.0.0.1:20160](http://127.0.0.1:20160/) modify-tikv-config -n rocksdb.defaultcf.titan.blob-run-mode -v fallback
DebugClient::modify_tikv_config: RpcFailure: 2-UNKNOWN "failed to update config, err: Other(\"[components/engine_rocks/src/[cf_options.rs:28](http://cf_options.rs:28/)]: Invalid argument: No blob_run_mode defined for fallback\")"

[root@tc-tikv-2 /]# /tikv-ctl --host [127.0.0.1:20160](http://127.0.0.1:20160/) modify-tikv-config -n rocksdb.defaultcf.titan.blob-run-mode -v read_only
DebugClient::modify_tikv_config: RpcFailure: 2-UNKNOWN "failed to update config, err: \"expect: normal, read-only or fallback, got: \\\"read_only\\\"\""

**Comment by tonyxuqqi** [comment]
Tracked here too: https://github.com/tikv/tikv/issues/15987

**Comment by JasonWu0506** [comment]
@tonyxuqqi does this issue exist in 5.4 and 6.1?
