### ISSUE TITLE
release 7.5.0 Compared with the previous commit, oltp_read_write has a 3.65% regression under 200 concurrency and oltp_insert has a 1.5+% regression under 100 concurrency

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#15994]
### What version of TiKV are you using?
7.1.2 tidb + 7.1.2 pd + patch 7.5.0 tikv

### What operating system and CPU are you using?
ksyun-rocky-16c

### Steps to reproduce
cluster deploy
7.1.2 tidb + 7.1.2 pd + patch 7.5.0 tikv(commit id 9bece34a3b3e3eb2fb5d8296cdbd8a459eeddbd6)
7.1.2 tidb + 7.1.2 pd + patch 7.5.0 tikv(commit id 076b79c54b9e7656f9119865d4ed75bec3bd58d6)

workload
sysbench oltp_read_write /oltp_insert
threads=100/200

### What did you expect?
Compared with 7.1.2 under 200 concurrency, qps should also be similar.

### What did happened?
Compared with the tikv 7.1.2, tikv 7.5.0  has a 5.82% regression under 200 concurrency in oltp_read_write.
![image](https://github.com/tikv/tikv/assets/85105033/1519cdcc-706a-4305-9b8c-058679c0de2a)
Compared with the commit 9bece34a3b3e3eb2fb5d8296cdbd8a459eeddbd6 the commit 076b79c54b9e7656f9119865d4ed75bec3bd58d6  lead oltp_read_write has a 3.65% regression under 200 concurrency and oltp_insert has a 1.5+% regression under 100 concurrency
![image](https://github.com/tikv/tikv/assets/85105033/ea82bd57-10f4-4ee3-8834-74315d61a7ab)
![image](https://github.com/tikv/tikv/assets/85105033/239e1ebb-11ed-4b3d-bfc2-8b5f563bfba6)

The corresponding pr is https://github.com/tikv/tikv/pull/15966

**Comment by MimeLyc** [comment]
update
