### ISSUE TITLE
TiKV OOM

### ISSUE THREAD

**Issue by vzong** [tikv/tikv#15992]
TiKV 7.1.1在开始事务后缺失commit会导致内存膨胀最终OOM，限制memory-usage-limit、storage.block-cache.capacity均无法阻止内存扩张。

大量并发：
txnKVClient.begin();
txnKVClient.put(key, value);
// txnKVClient.commit(); // 遗忘提交事务

**Comment by tonyxuqqi** [comment]
@overvenus Will the recent change in TiKV OOM mitigation solve this issue?

**Comment by vzong** [comment]
Machine:
CentOS 7.6
cpu_logical_number:40
memory:256G



TiKV conf:
memory-usage-limit = "120G"

[raftstore]
raft-base-tick-interval = "2s"

[resolved-ts]
advance-ts-interval = "20s"
scan-lock-pool-size = 8

[rocksdb]
wal-recovery-mode = 0
[rocksdb.defaultcf]
soft-pending-compaction-bytes-limit = "256G"

[server]
grpc-concurrency = 20

[storage]
api-version = 2
enable-ttl = true
[storage.block-cache]
capacity = "60G"

**Comment by vzong** [comment]
resolved-ts.enable设置为false后内存占用明显减少。

[resolved-ts]
enable = false

**Comment by vzong** [comment]
![resolved-ts cpu match with oom](https://github.com/tikv/tikv/assets/7782693/ceb3c25d-85e7-49fb-b45c-09e4cc32ec2c)
![OOM](https://github.com/tikv/tikv/assets/7782693/2c1a42b4-7049-4d24-8a61-705886f6b5c8)

Resolved TS Worker CPU match with OOM。

**Comment by overvenus** [comment]
@vzong Thank you for your feedback! We have fixed a similar OOM issue that is caused by resolved ts. Could you test v7.4.0 or the nightly release? Also, could you share your test client (many prewrite, no commit)?

* https://github.com/tikv/tikv/issues/14864  
* https://docs.pingcap.com/tidb/dev/release-7.4.0

**Comment by overvenus** [comment]
I believe it has been fixed. Feel free to reopen if it happens again.
