### ISSUE TITLE
Reduce the cpu usage of the `snapshot-worker`  thread to prevent it from blocking scheduling.

### ISSUE THREAD

**Issue by bufferflies** [tikv/tikv#16001]
## Development Task
The Snapshot-worker is primarily responsible for applying snapshots, destroying peers, and forwarding snapshot-generate messages. The deletion of peers can consume a significant amount of CPU, resulting in TIKV being unable to handle snapshot-related tasks and thus impacting scheduling.

**Comment by tonyxuqqi** [comment]
@bufferflies Please help to take this improvement.

**Comment by Connor1996** [comment]
It's better to handle the destroying peers in a separate thread pool like how generating snapshots does.

**Comment by Connor1996** [comment]
Duplicated with #12587
