### ISSUE TITLE
TiKV store size can't converges stablly after titan enable

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#16006]
### What version of TiKV are you using?

TiKV
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   7be1b17d72870bb95fcb7443b1f945f9c59657fa
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2023-11-09 11:56:08
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

sysbench wide table read write worload run for some days.
The store size is stable if titan disable, but the store size increase always until disk full if titan enable
![img_v3_0258_298f356f-7f5b-4210-87f9-c616d2f8a65g](https://github.com/tikv/tikv/assets/7677963/e2c087cf-32c6-490e-bbfd-460e2edc12e7)

**Comment by tonyxuqqi** [comment]
Dup with https://github.com/tikv/tikv/issues/16091
