### ISSUE TITLE
Daily run , compared with the previous tikv commit  , commit 7be1b1 leads ycsb workloada/workloadc has a 3% ~ 5% performance regression under 200 concurrency

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#16015]
### What version of TiKV are you using?
nightly

### What operating system and CPU are you using?

rocky -16c46g

### Steps to reproduce

**good tikv commit as baseline**
tidb  commit  92f071afeb7b0b0e8ddadb877464f106015455ab	
tikv  commit  f574ec0830f88a42290f1721a919b6a293cd7cfa	
pd   commit 2c07c241114fe9afabd9927ecbee61c4252f2d8e
test result ****
![image](https://github.com/tikv/tikv/assets/85105033/44da4a60-1aeb-4603-aa11-dee80acf779c)
bad tikv commit
tidb  commit  92f071afeb7b0b0e8ddadb877464f106015455ab	
tikv  commit  7be1b17d72870bb95fcb7443b1f945f9c59657fa	
pd   commit  2c07c241114fe9afabd9927ecbee61c4252f2d8e
test result ****
![image](https://github.com/tikv/tikv/assets/85105033/fe3211a4-66c8-4f01-a64b-1f02dd7b38a0)

### What did you expect?
There is no significant regression compared to the previous commit
### What did happened?
compared with the previous tikv commit  ycsb workloada has more than 3% regression
compared with the previous tikv commit  ycsb workloada has more than 4% regression

**Comment by shaoxiqian** [comment]
label affects-master

**Comment by nolouch** [comment]
only affect master
