### ISSUE TITLE
more than one tikv panic repeatedly and service is unavailable when run workload and add index

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#16030]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.5.0
Edition:           Community
Git Commit Hash:   30b578fdf20c1fd0d73a00ca26d57adb0242652f
Git Commit Branch: heads/refs/tags/v7.5.0
UTC Build Time:    2023-11-17 08:36:40
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-11-20T20:50:32.131+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
tidb_enable_dist_task='on' 
1、run sysbench
2、add index for one table
3、rolling restart pd

### What did you expect?
add index can success and no panic

### What did happened?
tikv panic repeatedly

{"container":"tikv","pod":"tc-tikv-2","level":"FATAL","namespace":"endless-ha-test-add-index-tps-4710408-1-283","log":"[[lib.rs:510](http://lib.rs:510/)] [\"assertion failed: !last_change_ts.is_zero()\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18\\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18//n)   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2032](http://boxed.rs:2032/):9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:692](http://panicking.rs:692/):13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:577](http://panicking.rs:577/):13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:137](http://backtrace.rs:137/):18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:575](http://panicking.rs:575/):5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:65](http://panicking.rs:65/):14\\n   6: core::panicking::panic\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:114](http://panicking.rs:114/):5\\n   7: tikv::storage::txn::actions::common::next_last_change_info\\n   8: tikv::storage::txn::actions::prewrite::PrewriteMutation::check_for_newer_version\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/actions/prewrite.rs:437:21\\n](http://github.com/pingcap/tikv/src/storage/txn/actions/prewrite.rs:437:21//n)   9: tikv::storage::txn::actions::prewrite::prewrite\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/actions/prewrite.rs:86:10\\n](http://github.com/pingcap/tikv/src/storage/txn/actions/prewrite.rs:86:10//n)  10: tikv::storage::txn::commands::prewrite::Prewriter<K>::prewrite\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/commands/prewrite.rs:647:35\\n](http://github.com/pingcap/tikv/src/storage/txn/commands/prewrite.rs:647:35//n)      tikv::storage::txn::commands::prewrite::Prewriter<K>::process_write\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/commands/prewrite.rs:535:19\\n](http://github.com/pingcap/tikv/src/storage/txn/commands/prewrite.rs:535:19//n)  11: <tikv::storage::txn::commands::prewrite::Prewrite as tikv::storage::txn::commands::WriteCommand<S,L>>::process_write\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/commands/prewrite.rs:250:9\\n](http://github.com/pingcap/tikv/src/storage/txn/commands/prewrite.rs:250:9//n)      tikv::storage::txn::commands::Command::process_write\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/commands/mod.rs:691:37\\n](http://github.com/pingcap/tikv/src/storage/txn/commands/mod.rs:691:37//n)  12: tikv::storage::txn::scheduler::TxnScheduler<E,L>::process_write::{{closure}}::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1287:21\\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1287:21//n)      tikv::storage::metrics::with_perf_context::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/metrics.rs:360:19\\n](http://github.com/pingcap/tikv/src/storage/metrics.rs:360:19//n)      std::thread::local::LocalKey<T>::try_with\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:446](http://local.rs:446/):16\\n      std::thread::local::LocalKey<T>::with\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:422](http://local.rs:422/):9\\n      tikv::storage::metrics::with_perf_context\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/metrics.rs:351:5\\n](http://github.com/pingcap/tikv/src/storage/metrics.rs:351:5//n)      tikv::storage::txn::scheduler::TxnScheduler<E,L>::process_write::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1286:17\\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1286:17//n)  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      tikv::storage::txn::scheduler::TxnScheduler<E,L>::process::{{closure}}::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1177:71\\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1177:71//n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      <resource_metering::InTags<T> as core::future::future::Future>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resource_metering/src/lib.rs:266:9\\n](http://github.com/pingcap/tikv/components/resource_metering/src/lib.rs:266:9//n)      tikv::storage::txn::scheduler::TxnScheduler<E,L>::process::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1191:9\\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:1191:9//n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      tikv::storage::txn::scheduler::TxnScheduler<E,L>::execute::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:748:54\\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:748:54//n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n  14: <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23//n)      std::thread::local::LocalKey<T>::try_with\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:446](http://local.rs:446/):16\\n      std::thread::local::LocalKey<T>::with\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:422](http://local.rs:422/):9\\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:62:9\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:62:9//n)      tikv_util::yatp_pool::future_pool::PoolInner::spawn::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:178:27\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:178:27//n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      yatp::task::future::RawTask<F>::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/task/[future.rs:59](http://future.rs:59/):9\\n  15: yatp::task::future::TaskCell::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/task/[future.rs:103](http://future.rs:103/):9\\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/task/[future.rs:387](http://future.rs:387/):20\\n  16: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:199:24\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:199:24//n)  17: yatp::pool::worker::WorkerThread<T,R>::run\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/pool/[worker.rs:48](http://worker.rs:48/):13\\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5572a78/src/pool/[builder.rs:114](http://builder.rs:114/):25\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:121](http://backtrace.rs:121/):18\\n  18: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:551](http://mod.rs:551/):17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:483](http://panicking.rs:483/):40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:447](http://panicking.rs:447/):19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:550](http://mod.rs:550/):30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:513](http://function.rs:513/):5\\n  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\\n  20: start_thread\\n  21: __clone3\\n\"] [location=components/txn_types/src/[types.rs:611](http://types.rs:611/)] [thread_name=sched-worker-pool-1] [thread_id=0x5]"}

**Comment by jebter** [comment]
refer to [#48804](https://github.com/pingcap/tidb/issues/48804)
