### ISSUE TITLE
raftstore: record the data not ready error types more clearly

### ISSUE THREAD

**Issue by cfzjywxk** [tikv/tikv#16113]
## Development Task

When `data_is_not_ready` is encounterred for stale read processing, the type is not clear and record as `Other` error types for the raft kv https://github.com/tikv/tikv/blob/master/src/server/raftkv/mod.rs#L93-L106.

It's better to record specific type clearly in the metrics.

**Comment by Gua00va** [comment]
I would like to work on this issue!

**Comment by Gua00va** [comment]
Should I be opening different PRs for each version?
