### ISSUE TITLE
tikv oom crash during lightning import 80k tables

### ISSUE THREAD

**Issue by aytrack** [tikv/tikv#16229]
### What version of TiKV are you using?

v7.1.2
### Steps to reproduce

1. deploy a cluster with 5 tikv(8c 32g) nodes
2. using tidb-lightning import 8w tables about 1.8T data with local mode 
### What did you expect?
Import data success 
### What did happened?
tikv OOM crash frenquently during CREATE table stage
![img_v3_026c_d25f47f4-b2c8-4127-8806-72eeaedf345g](https://github.com/tikv/tikv/assets/10184437/9f6cce01-533d-4323-8dbe-628ee3fbc484)

**Comment by kennedy8312** [comment]
candidate_1M

**Comment by tonyxuqqi** [comment]
It's likely due to too many region counts

**Comment by zhangjinpeng87** [comment]
@aytrack Would you mind to try the latest LTS version 7.5?

**Comment by overvenus** [comment]
FYI, there is a memory profile in #16243 that shows the majority memory is allocated by peer channels which is the same issue as https://github.com/tikv/tikv/issues/15701.
