### ISSUE TITLE
cluster can not provide service and tikv resolved ts can not go on after inject minio(pitr log backup path) network partition lasts for 10mins 

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#16235]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   5e0d7b1ba9430569886de26b51ca553337a36455
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2023-12-22 11:48:26
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure openssl-vendored
Profile:           dist_release

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run sysbench
2、start pitr (minio is the pitr log backup path) and ticdc
3、inject minio network partition lasts for 10mins and the recover

### What did you expect?
cluster is normal after fault recover

### What did happened?
1、cluster can not provide service
2、tikv resolved ts can go on
3、gc can not go on

clinic：https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7315338102025016150?from=1703315693&to=1703328331

![image](https://github.com/tikv/tikv/assets/84712107/7c2431ac-c4f9-462d-84a8-c0b9e4c5b923)
![image](https://github.com/tikv/tikv/assets/84712107/9aed62df-036a-452d-b862-ec1e8e8f13e9)
![image](https://github.com/tikv/tikv/assets/84712107/731b231e-4563-43e8-8bea-2effe0bbceef)
![image](https://github.com/tikv/tikv/assets/84712107/cf61f39b-601e-437a-ba09-9f0982dcbb23)
![image](https://github.com/tikv/tikv/assets/84712107/19a50225-0dc4-436a-9a20-d85f92fc6fc3)
![image](https://github.com/tikv/tikv/assets/84712107/581b5f54-9cce-4d09-9f30-5cfc2a65b6a2)

**Comment by Lily2025** [comment]
another scene：
with titan and run mussel workload，run chaos test，after inject pd leader io delay 1s and recover，cluster can not write and tikv resolved ts can not go
clinic：
https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7315338102025016150?from=1703315693&to=1703328331
![image](https://github.com/tikv/tikv/assets/84712107/caa794b8-8c06-4e08-9b23-e6a2aa035c27)
![image](https://github.com/tikv/tikv/assets/84712107/8306c559-f01c-476d-9068-8b4c45f8ee2d)
![image](https://github.com/tikv/tikv/assets/84712107/a45cb650-f073-46ab-b638-73319cd763d0)
![image](https://github.com/tikv/tikv/assets/84712107/1d6556bb-96d8-4548-b885-55f695e13aa0)
![image](https://github.com/tikv/tikv/assets/84712107/92d0ee16-7b0d-4784-bba9-5205f2936a9c)
![image](https://github.com/tikv/tikv/assets/84712107/8621f443-3452-4325-8b2a-0355602eca79)

**Comment by overvenus** [comment]
Let's focus on https://github.com/tikv/tikv/issues/16340.
