### ISSUE TITLE
tikv v7.4.0 crash

### ISSUE THREAD

**Issue by vzong** [tikv/tikv#16236]
[2023/12/23 20:07:45.518 +08:00] [FATAL] [lib.rs:510] ["group properties is not set"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:577:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14
   6: tikv_util::thread_group::is_shutdown::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/thread_group.rs:50:13
      std::thread::local::LocalKey<T>::try_with
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:446:16
      std::thread::local::LocalKey<T>::with
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:422:9
      tikv_util::thread_group::is_shutdown
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/thread_group.rs:46:5
   7: <tikv_util::callback::MustCall<T,C,A> as core::ops::drop::Drop>::drop
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/callback.rs:48:17
      core::ptr::drop_in_place<tikv_util::callback::MustCall<raftstore::store::msg::WriteResponse,alloc::boxed::Box<<tikv::server::raftkv::RaftKv<engine_rocks::engine::RocksEngine,raftstore::router::ServerRaftStoreRouter<engine_rocks::engine::RocksEngine,engine_rocks::engine::RocksEngine>> as tikv_kv::Engine>::async_write::{{closure}}>,tikv::server::raftkv::drop_on_applied_callback>>
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:490:1
      core::ptr::drop_in_place<tikv_util::callback::must_call<raftstore::store::msg::WriteResponse,alloc::boxed::Box<<tikv::server::raftkv::RaftKv<engine_rocks::engine::RocksEngine,raftstore::router::ServerRaftStoreRouter<engine_rocks::engine::RocksEngine,engine_rocks::engine::RocksEngine>> as tikv_kv::Engine>::async_write::{{closure}}>,tikv::server::raftkv::drop_on_applied_callback>::{{closure}}>
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:490:1
   8: core::ptr::drop_in_place<alloc::boxed::Box<dyn core::ops::function::FnOnce<(raftstore::store::msg::WriteResponse,)>+Output = ()+core::marker::Send>>
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:490:1
      core::ptr::drop_in_place<raftstore::store::msg::Callback<engine_rocks::snapshot::RocksSnapshot>>
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:490:1
   9: core::ptr::drop_in_place<crossbeam_channel::err::TrySendError<raftstore::store::msg::RaftCommand<engine_rocks::snapshot::RocksSnapshot>>>
      raftstore::router::handle_send_error
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/router.rs:270:1
      raftstore::router::send_command_impl::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/router.rs:112:22
      core::result::Result<T,E>::map_err
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:861:27
      raftstore::router::send_command_impl
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/router.rs:110:5
      raftstore::router::RaftStoreRouter::send_command
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/router.rs:57:9
  10: <tikv::server::raftkv::RaftKv<E,S> as tikv_kv::Engine>::async_write
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/server/raftkv/mod.rs:572:19
  11: tikv_kv::write
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_kv/src/lib.rs:708:19
      tikv::storage::Storage<E,L,F>::delete_range
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/storage/mod.rs:1635:19
      tikv::server::service::kv::future_delete_range
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/server/service/kv.rs:1553:15
  12: <tikv::server::service::kv::Service<E,L,F> as kvproto::protos::tikvpb_grpc::Tikv>::kv_delete_range
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/server/service/kv.rs:207:24
      kvproto::protos::tikvpb_grpc::create_tikv::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/.target/x86_64-unknown-linux-gnu/release/build/kvproto-3b4557dea3832524/out/protos/tikvpb_grpc.rs:1750:9
      grpcio::call::server::execute_unary
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/call/server.rs:745:5
      grpcio::server::ServiceBuilder::add_unary_handler::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/server.rs:196:13
      <grpcio::server::Handler<F> as grpcio::server::CloneableHandler>::handle
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/server.rs:54:9
  13: grpcio::call::server::execute
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/call/server.rs:844:5
  14: grpcio::call::server::UnaryRequestContext::handle
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/call/server.rs:251:20
      grpcio::task::callback::UnaryRequest::resolve
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/task/callback.rs:62:9
      grpcio::task::CallTag::resolve
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/task/mod.rs:178:42
      grpcio::env::poll_queue
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/env.rs:30:9
  15: grpcio::env::EnvBuilder::build::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/env.rs:107:21
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18
  16: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  18: start_thread
  19: __clone
"] [location=components/tikv_util/src/thread_group.rs:50] [thread_name=grpc-server-4]

**Comment by pingyu** [comment]
The panic seems to be caused by thread group properties was not set for gRPC threads.

Invoke `tikv_util::thread_group::set_properties` in [`after_start`](https://github.com/tikv/tikv/blob/4702b9bf6ed8d72d20bedf3de184f63111055b8e/components/server/src/server.rs#L332) should be able to fix the issue.

@vzong Is there any way to reproduce this issue ?

**Comment by vzong** [comment]
We haven't been able to reproduce the crash scenario, such a crash has occurred only once. 
The service shouldn't crash regardless of the status of any properties. This appears to be a bug.
