### ISSUE TITLE
TiKV OOM when importing 130k tables via lightning

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#16243]
### What version of TiKV are you using?
```
TiKV
Release Version:   7.5.0
Edition:           Community
Git Commit Hash:   bd8a0aabd08fd77687f788e0b45858ccd3516e4d
Git Commit Branch: heads/refs/tags/v7.5.0
UTC Build Time:    2023-11-28 13:20:02
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

```

### What operating system and CPU are you using?
X86, Rocky Linux 9.2 Docker Image

### Steps to reproduce
1. TiDB cluster with 9 TiKVs (16c 64g)
2. Use 3 lightning local mode to import 500k tables (schema only, no partition tables, no data) 

### What did you expect?
1. Import should be successful.

### What did happened?
Lightning import failed due to 3 TiKV OOM.
Issues: 
1. There are only 130 tables in TiDB, but there are over 4 million regions
2. TiKV regions not balanced in all TiKVs, and 3 TiKV have 1.4 million regions, others have few regions.

![image](https://github.com/tikv/tikv/assets/7403864/29f6b148-1a3f-4074-95d6-7016f816580f)

![img_v3_026h_16d7c4aa-6b46-4ab4-87b5-a047dc6fd13g](https://github.com/tikv/tikv/assets/7403864/9be9f9c2-1b20-454c-96cc-97d2a049374b)
![img_v3_026h_b47318f3-8ebb-418a-a4d9-c313914324ag](https://github.com/tikv/tikv/assets/7403864/1001c5e5-f03d-4b78-addb-9faf9ca5489a)

**Comment by kennedy8312** [comment]
candidate_1m

**Comment by LykxSassinator** [comment]
dup with https://github.com/tikv/tikv/issues/16229

**Comment by overvenus** [comment]
The memory profile shows that the majority memory is allocated by peer channels which is the same as #15701.
