### ISSUE TITLE
tikv-server should call Transfer leadership before graceful shutdown.

### ISSUE THREAD

**Issue by ngaut** [tikv/tikv#1629]
So tidb doesn't need to wait for the leader election timeout when we do rolling update.

**Comment by siddontang** [comment]
We can do:

1. Add a PD evict-leader-scheduler to transfer the leader 
2. Update the tikv and start it again
3. Remove the evict-leader-scheduler

/cc @andelf

**Comment by BusyJay** [comment]
Or we can do this in TiKV. When TiKV is about to shutdown, it can check if there is any leader, then transfers leader to a random sufficient follower.
