### ISSUE TITLE
Resolve ts can't advance for long time

### ISSUE THREAD

**Issue by lilinghai** [tikv/tikv#16290]
### What version of TiKV are you using?

TiKV
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   1a73761cc93b4914a3db0c1cb545f4b824372733
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2024-01-02 11:45:39
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure trace-async-tasks openssl-vendored
Profile:           dist_release
### Steps to reproduce

wide table read write
![image](https://github.com/tikv/tikv/assets/7677963/b7cfaed4-beb6-42a4-93f9-adaca9b8b85e)

**Comment by overvenus** [comment]
Let's focus on https://github.com/tikv/tikv/issues/16340.
