### ISSUE TITLE
others tikv abnormally restart and workload report “Region is unavailable” after inject one of tikv network partition or failure or rolling restart with titan enable

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#16301]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   df108bf9b70da040428fe7bcf683ca6f37815e82
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2024-01-05 11:42:07
Rust Version:      rustc 1.76.0-nightly (06e02d5b2 2023-12-09)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure trace-async-tasks openssl-vendored
Profile:           dist_release
2024-01-06T16:01:52.041+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
enable titan
1、run workload
2、inject one of tikv network partition last for some time and recover
![image](https://github.com/tikv/tikv/assets/84712107/00f170b2-dcfd-49f0-8a60-10aaf3a77529)

### What did you expect?
no  abnormally restart

### What did happened?
others tikv abnormally restart and workload report “Region is unavailable”

![image](https://github.com/tikv/tikv/assets/84712107/b121c7ca-9968-412e-a634-f2247617e0ba)

**Comment by LykxSassinator** [comment]
Missing related logs, can u upload the logs of `tc-tikv-3`? I didn't found the related logs in `minio`, maybe they're missing.

**Comment by Connor1996** [comment]
It's because Titan is enabled on write cf and there is a compatibility issue of compaction filter on write cf. So it would cause panic from time to time. As Titan wouldn't be enabled in write cf in normal case. Won't fix the compatibility issue.
