### ISSUE TITLE
Jepsen monotonic test failed with timeline contradiction

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#16315]
### What version of TiKV are you using?
7.6.0-pre

### Steps to reproduce
run jepsen monotonic
### What did you expect?
no error report 
### What did happened?
["Let:\n  T1 = {:type :ok, :f :inc, :value {2 12641}, :process 11, :time 142259341484, :txn-info {:txn_scope \"global\", :start_ts 446
833417099673652, :commit_ts 446833417099673682, :txn_commit_mode \"2pc\", :async_commit_fallback false, :one_pc_fallback false}, :index 4
06019}\n  T2 = {:type :ok, :f :read, :value {0 12757, 1 12862, 2 12641, 3 12657, 4 12708, 5 12700, 6 12782, 7 12706}, :process 59, :time
142274456762, :txn-info {:start_ts 446833417099673770}, :index 406059}\n  T3 = {:type :ok, :f :inc, :value {1 12863}, :process 11, :time
142253104563, :txn-info {:txn_scope \"global\", :start_ts 446833417086567261, :commit_ts 446833417099673605, :txn_commit_mode \"1pc\", :a
sync_commit_fallback false, :one_pc_fallback false}, :index 406005}\n\nThen:\n  - T1 < T2, because T1 completed at index 406019, 0.003 se
conds before the invocation of T2, at index 406030.\n  - T2 < T3, because T2 observed 1 = 12862, and T3 observed a higher value 12863.\n
 - However, T3 < T1, because T3 completed at index 406005, 0.000 seconds before the invocation of T1, at index 406006: a contradiction!"]
},
  :timeline {:valid? true},
  :valid? false},
 :valid? false}

**Comment by seiya-annie** [comment]
[node-0.tar.gz](https://github.com/tikv/tikv/files/13858450/node-0.tar.gz)
[node-1.tar.gz](https://github.com/tikv/tikv/files/13858472/node-1.tar.gz)

**Comment by seiya-annie** [comment]
[node-2.tar.gz](https://github.com/tikv/tikv/files/13858515/node-2.tar.gz)
[node-3.tar.gz](https://github.com/tikv/tikv/files/13858525/node-3.tar.gz)

**Comment by seiya-annie** [comment]
[node-4.tar.gz](https://github.com/tikv/tikv/files/13858591/node-4.tar.gz)

**Comment by cfzjywxk** [comment]
Possible relatated to https://github.com/tikv/tikv/pull/16261.

**Comment by cfzjywxk** [comment]
Duplicate with https://github.com/tikv/tikv/issues/16315
