### ISSUE TITLE
Some table properties are incorrect if titan is enabled

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#16319]
### What version of TiKV are you using?
Master branch.

### What did happened?

If Titan is enabled, `PROP_MIN_TS` and `PROP_MAX_TS` may be wrong. If Titan is enabled on CF_WRITE, it may cause TiCDC lose some events.

**Comment by guoxiangCN** [comment]
rawkv with titan sames, min_expire_ts/max_expire_ts cannot be collected if titan enabled since that the ttl store in the value but we can only access the blob index

**Comment by hicqu** [comment]
@guoxiangCN yes. But I don't know how to fix the problem.

**Comment by Connor1996** [comment]
> rawkv with titan also have this problem, min_expire_ts/max_expire_ts cannot be collected if titan enabled since that the ttl store in the value but we can only access the blob index

@guoxiangCN Need to change the property collector API to pass the value
