### ISSUE TITLE
enable titan, update report error after flashback 

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#16313]
### What version of TiKV are you using?
7.6.0-pre

### Steps to reproduce
1. config sync data with cdc 
2. run sysbench to prepare data 
3. run sysbench 10 minutes
4. flashback to after prepare data
5. run sysbench 3 minutes

### What did you expect?
sysbench run normally

### What did happened?
mysql> UPDATE user_data2 SET `j` = '{"number": 57609613 , "string": "zuVYjDnz1qfow0YJzRk6uh74bUBgkTCvu3EWBh7B9VZlJdTwMUM3QojFU0jLOkjXyKRxSRGgbjK2ugqPqayMywQtZ7EWyyNjRXFyg90PSHu4aIx7IuBc7bbUiq8oSlAGycY2Awa7pXQgARLEvUd46DTSySfH1zr8yPsCxMoqikBWrl2eauLrjFPrfNAKWHUt9CXAqS2g"}',`j2` = '[60105263,18124809]',`update_time`=CURRENT_TIMESTAMP WHERE `uid` = 747311;
ERROR 8141 (HY000): assertion failed: key: 74800000000000006b5f698000000000000001000380000000000b672f, assertion: Exist, start_ts: 446871893884010506, existing start ts: 0, existing commit ts: 0

**Comment by seiya-annie** [comment]
@JmPotato

**Comment by JmPotato** [comment]
Might related to #16319.

**Comment by seiya-annie** [comment]
close for test case has been passed in 01-09 dailyrun
