### ISSUE TITLE
titan =true dumpling and pitr has performance regression,which is 24.26% and 11.35%

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#16370]
dumpling test
tidb commit:67c0c7b60204660f2226d2b1e5e3aa0aa1076332
tikv commit:737daffe15aafaa0115067a2898e7d98e19fd448
pd commit:81164e160d4a76bbf4e7fc6a1a004494151ca313

data size: 200 millions records/ 2k fieldlength
restore way: lightning backend=tidb
![image](https://github.com/tikv/tikv/assets/85105033/0ad5ffca-dbcc-40f3-9a75-007497f8bd4e)
metrics
titan true: https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7322931062614394695
titan false:https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7322969270591432376

Pitr
tidb commit: 62c83d40fe2ed742bfaf4b7c64eca0bb1853a94d
tikv commit: 
titan true (39886146a2e314252c26af473808dea8b9dfb2ad) 
titan false(bd8a0aabd08fd77687f788e0b45858ccd3516e4d)
pd commit::754095a9f460dcf31f053045cfedfb00b9ad8e81
![image](https://github.com/tikv/tikv/assets/85105033/2390c95f-b621-49ce-8035-521c5338cab7)
metrics
titan true:https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7320782353791022520
titan false: https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7322747964361503823

**Comment by Connor1996** [comment]
Change the default `min-blob-size` to avoid the regression. Fixed by https://github.com/tikv/tikv/pull/16402
