### ISSUE TITLE
tikv conprof failed

### ISSUE THREAD

**Issue by jebter** [tikv/tikv#16396]
### What version of TiKV are you using?

v7.6.0
### What operating system and CPU are you using?

x86/m1 can be reproduced
### Steps to reproduce

tiup Deploy 7.6.0 tidb and enable conprof to reproduce
### What did you expect?
success
### What did happened?
![image](https://github.com/tikv/tikv/assets/4425235/c710e0f4-e8b9-435e-904c-899c03c4dbd6)

![image](https://github.com/tikv/tikv/assets/4425235/56f90f46-b11b-4397-a1bc-18c9e76e2ea6)

**Comment by Connor1996** [comment]
Add the doc about dependency requirement https://github.com/pingcap/docs-cn/pull/16221
