### ISSUE TITLE
In a cluster of 100 tikv nodes, conprofiling continues to fail

### ISSUE THREAD

**Issue by jebter** [tikv/tikv#16421]
### What version of TiKV are you using?

v7.6.0-pre
### What operating system and CPU are you using?

gcp/x86
### What did happened?
![image](https://github.com/tikv/tikv/assets/4425235/73e7b8d2-6f92-4980-b8a0-d4d451d24ef7)

**Comment by tonyxuqqi** [comment]
Can it be repro-ed in small environment? @jebter

**Comment by jebter** [comment]
not reproduced

**Comment by jebter** [comment]
not reproduced，close
