### ISSUE TITLE
raftstore: Add a timeout mechanism on snapshot send

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#16435]
### What version of TiKV are you using?

7.6 or older

### Steps to reproduce

In an environment where network is very slow,  it's possible that a region's leader cannot transfer leader to other peer.
  "[2024/01/18 08:39:09.814 +00:00] [INFO] [peer.rs:3274] [\"reject to transfer leader\"] [last_index=118] [index=118] [reason=\"pending snapshot\"] [to=\"id: 1013401971 store_id: 3163 role: IncomingVoter\"] [peer_id=1013386609] [region_id=1012011487]",
  
  And this is because the send_snapshot may be stuck and it does not return success or failure, as the log below shows, it did not show either snapshot sent success or failure. 
```
    "[2024/01/18 08:21:11.882 +00:00] [INFO] [snap.rs:1050] [\"scan snapshot\"] [takes=1.354081432s] [size=6574425] [key_count=83914] [snapshot=/var/lib/tikv/snap/gen_1012011487_12_116_(default|lock|write).sst] [region_id=1012011487]",

[2024/01/18 08:21:10.528 +00:00] [INFO] [peer_storage.rs:520] [\"requesting snapshot\"] [request_peer=1013195901] [request_index=0] [peer_id=1013386609] [region_id=1012011487]
```
### What did you expect?
Send snapshot should have timeout mechanism. 
### What did happened?
Send snapshot may be stuck there forever and the leader cannot get rid of the "pending snapshot" status.

**Comment by mittalrishabh** [comment]
What happens if follower response is lost. Is the leader going to remain in ProgressState::snapshot() forever ? https://github.com/tikv/raft-rs/blob/65a00620d80a89603c3358fd4b90265a692ae767/src/raft.rs#L1783

**Comment by mittalrishabh** [comment]
And also i don't see a retry if snapshot send is failed. https://github.com/tikv/tikv/blob/43d0e061159100092d89147480a94b51b6a158b4/src/server/raft_client.rs#L448C8-L448C26

**Comment by glorv** [comment]
@mittalrishabh 
> What happens if snapshot response from follower is lost. Is the leader going to remain in ProgressState::snapshot forever ? 

The peer state is changed the snapshot is sent(either finished or failed), it will call the callback and call `report_snapshot_status` with send a `SignificantMsg::SnapshotStatus` to the raftstore, on this message, the region leader will change target peer's state to Replicate.

> And also i don't see a retry if snapshot send is failed.

Yes, there is no retry here, so if send failed the peer status will change back to replicate. And the snapshot procedure will be trigger after an AppendResponse(triggered by new raft log) or a HeartbeatResponse(if no new message aft 1 tick).

**Comment by mittalrishabh** [comment]
I am new to this code. I still don't understand it. SignificantMsg::SnapshotStatus sends a status message to the peer. I couldn't find the code other than https://github.com/tikv/raft-rs/blob/65a00620d80a89603c3358fd4b90265a692ae767/src/raft.rs#L1783 where peer status in leader is changed to Replicate if snapshot request fails.

**Comment by mittalrishabh** [comment]
I found the code where it is changing it to probe here. https://github.com/tikv/raft-rs/blob/65a00620d80a89603c3358fd4b90265a692ae767/src/raft.rs#L1943. But lets say snapshot request is succeffuly sent but the response is dropped from the peer than would it remain in pause state forever.

**Comment by mittalrishabh** [comment]
it is doing pause here https://github.com/tikv/raft-rs/blob/65a00620d80a89603c3358fd4b90265a692ae767/src/raft.rs#L1979. 
Can you point me to the code who is unpausing after the above code in case of response failure or snapshot failure. I am looking at these places because one of the node was stuck in "snapshot pending" state after logging a snapshot failure message.  

```2024/01/18 08:54:07.429 +00:00] [ERROR] [snap.rs:462] ["failed to send snap"] [err=Grpc(RemoteStopped)] [region_id=1012095669] [to_addr=mussel-prod-replace-tikv-22.mussel-prod-replace-tikv-peer.tidb-mussel-prod-replace.svc.us-east-1a.mussel-prod-replace.tidb.musta.ch:20160]```

**Comment by glorv** [comment]
> Can you point me to the code who is unpausing after the above code in case of response failure or snapshot failure. I am looking at these places because one of the node was stuck in "snapshot pending" state for days after logging a snapshot failure message.

you can see there are both `resume()` call in `handle_append_response` and `handle_heartbeat_response` that will resume the pause status.

**Comment by mittalrishabh** [comment]
makes sense. Thanks for the explanation.
