### ISSUE TITLE
(dr-autosync) v6.5.8 scale in one node from primary datacenter failed during async mode

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/tikv#16465]
### What version of TiKV are you using?

v6.5.8

### Steps to reproduce

1. deploy one tidb cluster with 12 stores, and config it with 5 replicas in dr-auto-sync mode.
2. down two tikvs in the backup center, make replication mode switch to async.
3. Try to scale-in one node in the primary center.

### What did you expect?
Scale in succeeded.

### What did happened?
Scale in hung.

Didn't hit it before https://github.com/tikv/tikv/pull/16174.

**Comment by tonyxuqqi** [comment]
In this case, does the back-up site have two learners for each region?
 If that's the case, it would be blocked by today's check as we likely run into 3 healthy peers and 3 unhealthy peers. And if the remove peer happens on the healthy peer, it would be blocked. 
The argument here is that if the unhealthy peer is learner, then it should not be counted. Then we will have only 3 healthy peers plus one unhealthy learner.  By demoting a healthy peer, we will still have 2 healthy voter which can achieve majority.
