### ISSUE TITLE
leader and region are not balanced during br restore data and losts of miss-peer region after restore finished

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#16491]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.0.0-alpha
Edition:           Community
Git Commit Hash:   00a2518938f6328a305f70215d60355bfd2a3a9e
Git Commit Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time:    2024-02-02 11:42:35
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure trace-async-tasks openssl-vendored
Profile:           dist_release
2024-02-03T17:24:45.309+0800	

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、br restore data
/br restore db --db tpcc20000 --pd tc-pd.endless-ha-test-with-some-feature-tps-6540279-1-119:2379 --storage \"s3://qe-testing/benchmark/tpcc20000?access-key=xxx&secret-access-key=xxx&endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com&force-path-style=false&region=Beijing&provider=ks\" --send-credentials-to-tikv=true --check-requirements=false

### What did you expect?
leader and region are balanced during br restore data

### What did happened?
leader and region are not balanced during br restore data
![img_v3_027o_c6803f2c-70c7-4d0c-a115-4f3d4ed2554g](https://github.com/tikv/tikv/assets/84712107/e1f27344-528b-4cc3-b078-b977fdb289f0)
![image](https://github.com/tikv/tikv/assets/84712107/f6409607-879b-4835-ac57-abd5a79c7a1e)
![img_v3_027o_bfeaebea-b08a-4c41-b9bc-0c7c0234202g](https://github.com/tikv/tikv/assets/84712107/cbc1c53a-9bb0-4a8d-a62c-eae4e1c669b9)

**Comment by LykxSassinator** [comment]
Only affects master.

**Comment by LykxSassinator** [comment]
This issue is caused by the incomplete border check in`check_store_is_busy_on_apply`, which missed the check whether the given store is start from empty.
