### ISSUE TITLE
flaky test all::failed_during_refresh_region – backup-stream::failpoints

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#16514]
https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/42374/tests
Stacktrace
thread 'all::failed_during_refresh_region' panicked at components/backup-stream/tests/failpoints/mod.rs:185:15:
not all keys are recorded: it remains ["7480000000000000ff015f728000000000ff0002840000000000fafffffffffffffe75", "7480000000000000ff015f728000000000ff0002440000000000fafffffffffffffeb5", "7480000000000000ff015f728000000000ff00021a0000000000fafffffffffffffedf"]... (total = 128)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/panicking.rs:72:14
   2: failpoints::suite::assert_empty
   3: failpoints::suite::Suite::check_for_write_records
   4: failpoints::all::failed_during_refresh_region
   5: failpoints::all::failed_during_refresh_region::{{closure}}
   6: core::ops::function::FnOnce::call_once
   7: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/alloc/src/boxed.rs:2015:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Standard Output
running 1 test
connecting channel to 127.0.0.1:44333 for store 1
reading /tmp/.tmpki3Gal/v1/backupmeta
reading /tmp/.tmpki3Gal/v1/backupmeta/517-4db7e1da-9592-43cb-9aa9-1a7353421dab.meta
test all::failed_during_refresh_region ... FAILED

**Comment by YuJuncen** [comment]
I guess this is a bug relates to https://github.com/tikv/tikv/issues/16469 and will probably be fixed by https://github.com/tikv/tikv/pull/16484
