### ISSUE TITLE
CDC resolved ts stucks, CDC incremental scan encountered lots of RegionNotFound error

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#16543]
### What version of TiKV are you using?
TiKV
Release Version:   8.0.0-alpha
Edition:           Community
Git Commit Hash:   e4e273f758c289df9ddf47b73371185bf867b2cd
Git Commit Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time:    2024-02-06 11:42:45
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure trace-async-tasks openssl-vendored
Profile:           dist_release

### What operating system and CPU are you using?
K8s, Rocky Linux 9.3 (Blue Onyx), X86_64

### Steps to reproduce
1. cluster configuration
```
config: |
      log-file = "/var/lib/tikv/log/tikv.log"
      [backup]
        num-threads = 4
      [coprocessor]
        region-max-keys = 6400000
        region-max-size = "640MiB"
        region-split-keys = 5120000
        region-split-size = "512MiB"
      [gc]
        enable-compaction-filter = false
      [import]
        num-threads = 10
      [quota]
        foreground-write-bandwidth = "40MB"
        max-delay-duration = "1s"
      [raft-engine]
        enable = true
      [raftdb]
        max-open-files = 10240
      [raftstore]
        max-leader-missing-duration = "20m"
        region-compact-tombstones-percent = 10
        store-io-pool-size = 16
      [readpool]
        [readpool.unified]
          max-tasks-per-worker = 20000
          max-thread-count = 80
      [resolved-ts]
        advance-ts-interval = "2s"
      [rocksdb]
        max-open-files = 10240
        [rocksdb.defaultcf]
          level0-stop-writes-trigger = 50
          [rocksdb.defaultcf.titan]
            blob-cache-size = "32GB"
            discardable-ratio = 0.4
            min-blob-size = "4KB"
        [rocksdb.titan]
          enabled = true
      [server]
        grpc-concurrent-stream = 65535
      [storage]
        reserve-space = "300GB"
        scheduler-worker-pool-size = 16
        [storage.block-cache]
          capacity = "12GB"
          num-shard-bits = 4
        [storage.flow-control]
          l0-files-threshold = 45
```
2. 3 kafka changefeed running to sync 4000 tables: one changefeed sync workload whose row width is 10kb, the other 2 syncs 2000 tables respectively.  workload througput is about 25MB/s.

### What did you expect?
CDC lag should be stable.

### What did happened?
CDC resolved ts stucked since 02:09 02:46, CDC initial scan encountered lots of "RegionNotFound" error, initial scan not finished in 24h which resulted to CDC changefeed failure.

![image](https://github.com/tikv/tikv/assets/7403864/c66e5c1c-f255-46d1-99ce-11eb19ff7162)

![img_v3_0287_faa5646e-4413-405e-bbeb-0406fe717cfg](https://github.com/tikv/tikv/assets/7403864/6390872e-ab8f-472d-91f1-c9fe36dc6003)
![img_v3_0287_424458c2-6a73-4f17-b270-5cb6633fe03g](https://github.com/tikv/tikv/assets/7403864/02343e4e-24d4-4557-acc7-d27fbb96d50a)
![img_v3_0287_2df9a036-be1a-415b-9bf2-f77b791e291g](https://github.com/tikv/tikv/assets/7403864/07830fad-e601-4c0a-9d23-54fac551b786)

![image](https://github.com/tikv/tikv/assets/7403864/0fcc8827-a24c-4c18-b163-577f5c2ee689)

**Comment by hicqu** [comment]
It's expected. TiCDC is blocked with some reasons, and TiKV reports this error
```
[ERROR] [endpoint.rs:864] ["cdc initialize fail: Sink send error Congested"]
```

then TiKV will report a `RegionNotFound` error to TiCDC. We should replace it with `ServerIsBusy`.

**Comment by fubinzh** [comment]
What is the reason TiCDC is blocked? @hicqu 
> TiCDC is blocked with some reasons, and TiKV reports this error

**Comment by hicqu** [comment]
> What is the reason TiCDC is blocked? @hicqu

TiCDC disk is full.

**Comment by fubinzh** [comment]
CDC disk full issue, tracked by https://github.com/pingcap/tiflow/issues/10641

**Comment by fubinzh** [comment]
Close this issue, as https://github.com/pingcap/tiflow/issues/10641 fixed.
