### ISSUE TITLE
High peer msg duration, should avoid snapshot IO in raftstore

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#16564]
## Bug Report

When taking a store offline, we notice that it would cause high process-ready duration in other stores.

<img width="733" alt="img_v3_028f_96f38cdb-72af-4d84-82eb-ee03f82375dg" src="https://github.com/tikv/tikv/assets/13497871/25b0d818-2e9b-4adf-bc55-3a23e3465197">

It's mainly due to high peer msg handle duration.
![img_v3_028f_095e107c-9f71-4348-99f1-8163d5cfa3cg](https://github.com/tikv/tikv/assets/13497871/4a084173-a8e0-43eb-9af8-4456e1581c27)

As we can see, there is some read io of raftstore. And from CPU profile, `cacl_checksum_and_size` is noticeable. So it's because snapshot checksum scan of `check_snapshot` performed in raftstore thread causes the high duration.
<img width="735" alt="img_v3_028f_fb6549d2-4f30-4f9f-9314-fb32f261ba2g" src="https://github.com/tikv/tikv/assets/13497871/7274b55c-3804-40c4-b64c-a419a7856828">
![img_v3_028f_381b4b0d-c67b-40a0-9971-18820291cb4g](https://github.com/tikv/tikv/assets/13497871/accb4c60-c490-4fa7-a7d7-0ebef610c39b)

**Comment by LykxSassinator** [comment]
### Reference
The related TiKV config can be reviewed from the followings show:
```
config: 
            [cdc]                      
              min-ts-interval = "200ms"
            [raftstore]
              store-io-pool-size = 16
              region-compact-tombstones-percent = 10
              max-leader-missing-duration = "20m"
            [resolved-ts]
              advance-ts-interval = "2s"
            [storage]
              reserve-space = "300GB"
              scheduler-worker-pool-size = 16
            [storage.block-cache]
              num-shard-bits = 4
              capacity = "12GB"
            [quota]
              foreground-write-bandwidth = "40MB"
              max-delay-duration = "1s"
            [rocksdb]
              max-open-files = 10240
              [rocksdb.titan]
                enabled = true
              [rocksdb.defaultcf.titan]
                blob-cache-size = "32GB"
                min-blob-size = "4KB"
                discardable-ratio = 0.4
            [coprocessor]
              region-split-size = "512MiB"
              region-split-keys = 5120000
              region-max-size = "640MiB"
              region-max-keys = 6400000
            [raftdb]
              max-open-files = 10240
            [readpool.unified]
              max-thread-count = 80
              max-tasks-per-worker = 20000
            [server]
              grpc-concurrent-stream = 65535
            [raft-engine]
              enable = true
            [storage.flow-control]
              l0-files-threshold = 45
            [rocksdb.defaultcf]
              level0-stop-writes-trigger = 50
            [gc]
              enable-compaction-filter = false
            [import]
              num-threads = 10
            [backup]
              num-threads = 4
```

**Comment by LykxSassinator** [comment]
Maybe it caused by doing checksum on the too large snapshot as the setting on region size is big in this scenario.

**Comment by Connor1996** [comment]
@LykxSassinator Probabaly. Anyway, we should avoid IO in raftstore thread

**Comment by cfzjywxk** [comment]
Perhaps we need to detail the operations within the store loop that could trigger IO operations.
