### ISSUE TITLE
Restore the Raft local from kvdb if the Raft disk has become inaccessible while the kvdb disk remains intact.

### ISSUE THREAD

**Issue by mittalrishabh** [tikv/tikv#16560]
## Feature Request
Our current setup involves using EBS for both the KV db and the Raft db. The primary reason for this choice is the periodic rotation of nodes, where using local disks would require expensive operations to bootstrap each node during rotation. However, EBS fluctuations can sometimes lead to violations of our write SLO or follower read SLO. To address this issue, we have opened a feature request (https://github.com/tikv/tikv/issues/16457#issuecomment-1928957609) for further improvements.
As an alternative solution, we propose using local drives for the Raft db and EBS for the KV db. To facilitate this, we need to enhance the Tikv recovery process so that it can restore the Raft states from the KV db. 

Currently, the Raft db is used to store the Raft local state, while the KV db stores the apply state. Additionally, snapshot state is stored in the KV db, and in certain failure cases, the local state is restored from the snapshot state. During RAFT initialization, the apply state in the KV db is scanned to restore the local state, either by reading from the Raft db or, in certain failure cases, from the snapshot state.
Our proposal involves storing the Raft local state in the KV db, enabling recovery even if the local disk becomes inaccessible.  It can copy the logs from the apply indx from the peer and replay it locally. 
We acknowledge that this solution carries a risk of data loss if a quorum of compute nodes is lost forever. However, we believe the chances of this occurrence are minimal. 
I understand that it won't be a trivial solution. At this point, I am trying to see the feasibility, and scope the effort.  However i think that https://github.com/tikv/tikv/issues/16457 would be much simpler than this feature request. But I would like to know your opinion too.

**Comment by zhangjinpeng87** [comment]
After https://github.com/tikv/tikv/pull/16626 , I think raft ebs jitter issue can be resolved. @mittalrishabh How about let's close this issue?
