### ISSUE TITLE
TiCDC incremental scan can usage too much CPU under some unkown conditions

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#16601]
### What version of TiKV are you using?
`v6.5.5`.

However, I guess the issue also exists in all later versions.

### What operating system and CPU are you using?
Doesn't matter.

### Steps to reproduce
It can't be reprocued stably. The root cause is still unknown.

### What did you expect?
TiCDC incremental scan shouldn't be too slow.

### What did happened?
TiCDC incremental scan is too slow (about 30min), and incremental scan worker CPU usage is always 100%:

```
[2023/11/27 10:54:58.200 +08:00] [INFO] [replication_manager.go:635] ["schedulerv3: slow table"] [namespace=default] [changefeed=policy-t2o-36] [tableID=52592] [tableStatus=] [checkpointTs=445920115528303141] [resolvedTs=445920115528303141] [checkpointLag=57m32.250351282s]
```

![image-2024-01-22-15-00-49-850](https://github.com/tikv/tikv/assets/8407317/e3fec341-951c-4f72-81d7-e64704862115)

![image-2024-01-22-15-01-14-465](https://github.com/tikv/tikv/assets/8407317/74b31535-1802-45e6-b7e6-1adef463136d)

**Comment by kennytm** [comment]
(reopening, it can still be triggered with non-DDLs like DELETE or TTL.)
