### ISSUE TITLE
Where can I find the logic for advancing the safepoint of apiv2 rawkv

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/tikv#16709]
## Question

same as the title, thanks!
@pingyu

**Comment by pingyu** [comment]
Currently we reuse the GC worker of TiDB.

So you can find the logic in TiDB [`GCWorker`](https://github.com/pingcap/tidb/blob/31c60e0fd64f8de6a19f18707fd194e05263210c/pkg/store/gcworker/gc_worker.go#L742).

There is an example of GC worker logic in [`client-go`](https://github.com/tikv/client-go/tree/master/examples/gcworker) as well. Which would be easier to read.

**Comment by guoxiangCN** [comment]
thanks for you reply! 

It seems that the gcworker of Tidb only handles transaction related tasks. If my TikV cluster does not use Tidb and only stores data from Rawkv apiv2, can it still function properly?

Tikv's causalts will cache a batch of ts, so the safepoint may be pushed to a location that is more updated than the cached ts? Will there be any issues when users write using old TS?

**Comment by pingyu** [comment]
> It seems that the gcworker of Tidb only handles transaction related tasks. If my TikV cluster does not use Tidb and only stores data from Rawkv apiv2, can it still function properly?

Yes. We only utilize the function of advancing GC safe point. The part of resolve transaction locks will have no effect for RawKV.

> Tikv's causalts will cache a batch of ts, so the safepoint may be pushed to a location that is more updated than the cached ts? Will there be any issues when users write using old TS?

In theory this should not happen, as we just cache timestamp for seconds, but GC lifetime will be no less than 10 minutes.

Even in the very corner case this should not be an issue, as GC will never reclaim the latest version of data, no matter what the GC safepoint is.

**Comment by guoxiangCN** [comment]
@pingyu thanks for your reply! 

We forked in Tikv6.5 and developed some features to meet our needs. Currently, we have encountered a serious data inconsistency issue, which is the mismatch between the raft leader and follower data.

Our usage scenarios also use the mechanisms of Mvcc and Safepoint, and we also use the functionality of CompactionFilter, which supports discarding some useless data internally.

According to Rocksdb's documentation, CompactionFilter and DeleteFilesInRange will disrupt the consistency of existing snapshots.

We are currently encountering difficulties in troubleshooting data inconsistency issues, and we believe it is caused by compationFilter.
We have found that TikV also uses compactionfilter internally for GC, including raw and TXN writeCF data. We would like to know if TikV has encountered similar issues.

When performing a raft snapshot in the raft store, it will obtain a snapshot of Rocksdb and record the AppleIndex. Then, based on the snapshot, it will generate snapshot data and store it in SST and Plainfile. However, if a compactionfilter occurs and the data is discarded, the consistency of the snapshot cannot be guaranteed? Raftstore is actually unaware of concepts such as safepoint, commit_ts, and raft entry index. How is its consistency ensured?

If I misunderstood, please correct me! Thank you so much!

**Comment by pingyu** [comment]
What kind of "inconsistency" are you facing ?

> We would like to know if TikV has encountered similar issues.

I think no.

As long as compaction filter only discard garbage, the effective versions should be consistent. Some replicas have more garbage do not break the correctness.
