### ISSUE TITLE
TiKV store down when running workload

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#16716]
### What version of TiKV are you using?
1c7b34419feaf8901046df335d4da55ad3ca9b5d

### What operating system and CPU are you using?
X86 K8S

### Steps to reproduce
1. TiDB Cluster with 30 TiKV node, Titan on, cluster size ~70TB, run 3 workloads:   2 Big tables (15TB each table, row width ~9KB); 4000 small tables (row width ~1.7KB); 1 larger row workload  (row width: ~1MB)

### What did you expect?
TiKV store shoult not down

### What did happened?
After the cluster recently upgraded from 397d8d4894d06913c6bc72304fe1f83ba6fedd33 to 1c7b34419feaf8901046df335d4da55ad3ca9b5d, TiKV down issue is seen when run workload, and restored after workload is stopped.
![img_v3_029d_968e0445-f6d4-47fb-9cd2-5c2cc841d34g](https://github.com/tikv/tikv/assets/7403864/05142498-ce6f-443c-a255-9e4ecb4a4a11)

**Comment by LykxSassinator** [comment]
The testing environment also enables `titan` feature, and tests with `wide-table` workloads.

According to the monitoring metrics, we see that there exists numerous pending tasks in `pd_worker` when executing the test. And the log of one abnormal tikv node shows that this bug might be introduced by one pr starting from 20240322 to 20240325, the related `commit-id` ranges from 397d8d4894d06913c6bc72304fe1f83ba6fedd33 to 1c7b34419feaf8901046df335d4da55ad3ca9b5d.
![img_v3_029d_62d7495f-ff0a-40b2-8813-2f99de7e611g](https://github.com/tikv/tikv/assets/18441614/86df1727-193e-455e-b5bb-6d159865b00f)


Ref: 
The commit id range:
+ 20240322 normal state, with commit-id 397d8d4894d06913c6bc72304fe1f83ba6fedd33
![img_v3_029d_a15a1d20-ffb7-4529-939c-51c8e09bbebg](https://github.com/tikv/tikv/assets/18441614/0b766507-33ff-4ac3-b5aa-c41f4ce75dd3)
+ 20240325 abnormal state, with commit-id 1c7b34419feaf8901046df335d4da55ad3ca9b5d
![img_v3_029d_23cdf093-128e-4f13-ae6e-e6ea2d15caeg](https://github.com/tikv/tikv/assets/18441614/e5f88c08-1fbc-4c80-b94a-a3d3909d9f64)

The first time that this tests encountered this bug:
![img_v3_029d_968e0445-f6d4-47fb-9cd2-5c2cc841d34g](https://github.com/tikv/tikv/assets/18441614/b3bea90c-8abe-418a-ac78-111b2bcbe209)

**Comment by overvenus** [comment]
Touch #16678
