### ISSUE TITLE
Isolation level with Transaction API

### ISSUE THREAD

**Issue by amarjeet000** [tikv/tikv#16728]
Hi, I have one question regarding transaction isolation level with transaction API:

Based on this text about optimistic locking https://tikv.org/deep-dive/distributed-transaction/locking/#practice-in-tikv, it appears that write-skew anomaly would not occur in TiKV. However, in here https://tikv.org/docs/7.1/reference/architecture/overview/#tikv, it specifically mentions that transactional API provides snapshot isolation transaction, in which write-skew anomaly will occur. So, my question is if I need to avoid write-skew anomaly, is it safe to use Txn API or do I have to employ some other mechanisms?

Thanks

**Comment by ekexium** [comment]
Write skew could occur. If you want to avoid it, you can manually "lock" the values you read, which is provided in Txn API.

**Comment by amarjeet000** [comment]
Thanks @ekexium for clarification.
