### ISSUE TITLE
tikv panic when run sysbench and split table

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#16885]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.1.5
Edition:           Community
Git Commit Hash:   93a581c6ea93b7033dd9961923e748b7470e5ea4
Git Commit Branch: HEAD
UTC Build Time:    2024-04-18 08:48:28
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2024-04-18T22:26:13.395+0800	

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run sysbench
-threads=64 --tables=32 --table-size=10000000
2、split table

### What did you expect?
no panic

### What did happened?
tikv panic
`{"namespace":"ha-test-tikv-network-fault-rpt-tps-7568552-1-470","pod":"tc-tikv-2","container":"tikv","level":"FATAL","log":"[lib.rs:510] [\"index out of bounds: the len is 13 but the index is 13\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at workspace/source/tikv/components/tikv_util/src/lib.rs:509:18\\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\\n      std::panicking::rust_panic_with_hook\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\\n   4: rust_begin_unwind\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\\n   5: core::panicking::panic_fmt\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\\n   6: core::panicking::panic_bounds_check\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:150:5\\n   7: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::handle_msgs\\n             at workspace/source/tikv/components/raftstore/src/store/fsm/store.rs:795:13\\n   8: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_control\\n             at workspace/source/tikv/components/raftstore/src/store/fsm/store.rs:984:9\\n      batch_system::batch::Poller<N,C,Handler>::poll\\n             at workspace/source/tikv/components/batch-system/src/batch.rs:369:27\\n   9: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\\n             at workspace/source/tikv/components/raftstore/src/store/worker/refresh_config.rs:83:21\\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\\n             at workspace/source/tikv/components/tikv_util/src/sys/thread.rs:427:23\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\\n  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\\n      std::panicking::try::do_call\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\\n      std::panicking::try\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\\n      std::panic::catch_unwind\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\\n  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\\n  12: start_thread\\n  13: __GI___clone3\\n\"] [location=/workspace/source/tikv/components/raftstore/src/store/fsm/store.rs:795] [thread_name=raftstore-1-0]"}`

**Comment by LykxSassinator** [comment]
dup with https://github.com/tikv/tikv/issues/16639
