### ISSUE TITLE
Raftstore: async-io brings more minor IOs when writing raft logs.

### ISSUE THREAD

**Issue by LykxSassinator** [tikv/tikv#16907]
## Development Task
Previous work in https://github.com/tikv/tikv/pull/16615 shows that the performance on write workloads can be improved as expected by enabling `async-io` as default.

However, we find that `async-io` will make side effects to the log batching mechanism, which will make each batch of writing smaller than disabling` async-io`, according to the metrics from RaftEngine. And smaller batch will make it cannot reach the threshold of compression. Then, it will increase the costs on IO bandwidth (nearly ~10%).
| enable `async-io` | disable `async-io` |
| --- | --- |
| ![image](https://github.com/tikv/tikv/assets/18441614/2149f233-80b7-4ab5-8a91-ceb196b42c6f) |  ![image](https://github.com/tikv/tikv/assets/18441614/e0c2a4ab-254c-4a74-a09b-5193b68dbff8) |

And when we increase the threads of `async-io`, the smaller batching gives higher costs on IOPS.
| RaftEngine - bytes / written | IOPS on Disk |
| --- | --- |
| ![image](https://github.com/tikv/tikv/assets/18441614/511d8e4d-ab9c-485c-8a05-cb2ef54a4810) | ![image](https://github.com/tikv/tikv/assets/18441614/95e1b2eb-81a6-4fb1-a874-c6f46917cb02) |

Finally, by reducing the `raft-engine.batch-compression-threshold` to `4kb` from `8kb`(default), the costs on `async-io` can be eliminated as expected.

So, we should give a more reasonable setting on the compression threshold after enabling `async-io`.

**Comment by zhangjinpeng87** [comment]
@LykxSassinator besides the IO bandwidth, any IOPS changes after enable async-io?

**Comment by kennedy8312** [comment]
@LykxSassinator Are there any pending tasks for this issue? Shall we close this one?

**Comment by LykxSassinator** [comment]
Yep, as https://github.com/tikv/tikv/pull/16967 has been merged to v8.1, this issue can be closed.
