### ISSUE TITLE
in-memory-engine: OLTP-insert has more than 10% regression when in-memory-engine is enabled in a test environment

### ISSUE THREAD

**Issue by tonyxuqqi** [tikv/tikv#16947]
### What version of TiKV are you using?

master branch [c36886a]
### Steps to reproduce

enable in-memory-engine and run sysbench oltp-insert 
And then disable it and restart the tikv,  sysbench oltp-insert again (with same prepared data).

### What did you expect?
The insert TPS has less than 5% regression when in-memory-engine is enabled. 
### What did happened?
It shows that with in-memory-engine, the TPS has 10%+ regression. 

clinic: https://clinic.pingcap.com/portal/#/orgs/1372813089196921458/clusters/7361927152612425097?from=1715034298&to=1715041498

<img width="877" alt="Screen Shot 2024-05-06 at 5 44 08 PM" src="https://github.com/tikv/tikv/assets/9442422/7d03a7c2-3175-46b2-b947-07ac2d7141c9">
<img width="905" alt="Screen Shot 2024-05-06 at 5 47 39 PM" src="https://github.com/tikv/tikv/assets/9442422/1f46e381-0f12-498a-b3e7-cb8fd0bb2a4c">

**Comment by overvenus** [comment]
Set a lower severity, because it only occurs after enabling IME which is not released and is disabled by default.

**Comment by overvenus** [comment]
Latest tests show IME only cause about 3% regression in the oltp-insert scenario which is in the criteria (less than 5%).

| id     | test_start_time     | bench_type | bench_sub_type | tidb_version                | thread | duration(s) | tps   | qps   | avg_latency(ms) | P99_latency(ms) | P999_latency(ms) | monitor_url                                                                 | log_url                                                                     | profile_url                                                                                                                                                                                                                                                                                                                                                                                                    | tidb_cpu_usage | tidb_memory_usage(GB) | tidb_network_traffic(Mbps) | tikv_cpu_usage | tikv_memory_usage(GB) | tikv_network_traffic(Mbps) | tikv_io_throughput(MBps) | arch  | bench_config                                                                                             | testbed                                 | tidb_commit_hash              | tikv_commit_hash                                        | pd_commit_hash                                |                                          |                                          |                                          |
|--------|---------------------|------------|----------------|-----------------------------|--------|-------------|-------|-------|-----------------|-----------------|------------------|-----------------------------------------------------------------------------|-----------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------|-----------------------|----------------------------|----------------|-----------------------|----------------------------|--------------------------|-------|----------------------------------------------------------------------------------------------------------|-----------------------------------------|-------------------------------|---------------------------------------------------------|-----------------------------------------------|------------------------------------------|------------------------------------------|------------------------------------------|
| 514825 | 2024-12-13 18:41:23 | sysbench   | oltp_insert    | 8.5.0-alpha-335-g033b1758a9 | 32     | 7200        | 19580 | 19549 | 1.58            | 3.36            | 39.0             | https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7447876322267744856 | https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7447843930594016493 | http://minio.pingcap.net:9000/benchbot-profile/benchbot-amd64-2xl-sysbench-tps-7698197-1-409/nightly_sysbench_oltp_insert_32_1734091883.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20241213%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241213T124153Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=40d37ac22360512fc74c84e0f9d2d5206c946a95e549b714b7a0f085796c663d | 12.8           | 1.58                  | 43.8                       | 27.2           | 65.1                  | 121                        | 4102                     | amd64 | "Version:nightly; BenchSubType:oltp_insert; Thread:32; ApThread:1; TikvConfig:{""import.num-threads"":15 | ""in-memory-engine"":{""enable"":true}  | "memory-usage-limit"":""36GB" | "storage"":{""block-cache"":{""capacity"":""21.6GB""}}} | benchbot-amd64-2xl-sysbench-tps-7698197-1-409 | 033b1758a90804ab7ce0c9aaece72778b608840a | 601e8a7337049ea541f2f8ffb4179e28b9efc9e1 | 5d62787565f7d238f386fd702e89a1921060f545 |
| 484633 | 2024-12-13 16:35:57 | sysbench   | oltp_insert    | 8.5.0-alpha-334-g5e8d1b8ae1 | 32     | 7201        | 20184 | 20153 | 1.54            | 3.27            | 19.6             | https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7447876322267744856 | https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7447811572448861744 | http://minio.pingcap.net:9000/benchbot-profile/benchbot-amd64-2xl-sysbench-tps-7698197-1-409/nightly_sysbench_oltp_insert_32_1734084358.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20241213%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241213T103626Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=4461006921c86d4b98238abd39e5d2efe5a4dfa93c42872b015573e8b8d80512 | 13.1           | 1.58                  | 44.9                       | 27.4           | 68.8                  | 124                        | 3410                     | amd64 | "Version:nightly; BenchSubType:oltp_insert; Thread:32; ApThread:1; TikvConfig:{""import.num-threads"":15 | ""in-memory-engine"":{""enable"":false} | "memory-usage-limit"":""36GB" | "storage"":{""block-cache"":{""capacity"":""21.6GB""}}} | benchbot-amd64-2xl-sysbench-tps-7698197-1-409 | 5e8d1b8ae1de446841c105d0c177320c88ff893d | 601e8a7337049ea541f2f8ffb4179e28b9efc9e1 | 5d62787565f7d238f386fd702e89a1921060f545 |
