### ISSUE TITLE
In-memory engine: manual load table does work properly

### ISSUE THREAD

**Issue by SpadeA-Tang** [tikv/tikv#16966]
## Bug Report

Manual table load is implemented by using region label and there are some problems for the current implementation.

1. The load will only trigger once. 
2. The range in region label is used as region's range whereas  it is the table's range.

For 1, if the range is evicted due to transfer leader or something, it has no change to be loaded again.
For 2, the range overlap check will be performed when call load_range, so if there's already a sub range that has already been loaded, the load will be rejected. So we have to get the regions within the range, and load them separately.

**Comment by overvenus** [comment]
> For 1, if the range is evicted due to transfer leader or something, it has no change to be loaded again.

Fixed by https://github.com/tikv/tikv/pull/17296

> For 2, the range overlap check will be performed when call load_range, so if there's already a sub range that has already been loaded, the load will be rejected. So we have to get the regions within the range, and load them separately.

Fixed by https://github.com/tikv/tikv/pull/17331
