### ISSUE TITLE
TiKV may OOM if too many regions on a TiKV server 

### ISSUE THREAD

**Issue by wjhuang2016** [tikv/tikv#17072]
### What version of TiKV are you using?

master

### Steps to reproduce

We run a test on a small cluster, 1 TiDB with 8C16G, and 3 TiKV with 8C16G.
The test is about trying to create 1000, 000 tables.
After creating 300, 000 tables, all TiKV start to OOM.
It seems that 300, 000 regions will consume 16G memory, which is higher than we expected.
 

### What did you expect?
TiKV doesn't OOM.

### What did happened?
TiKV OOM.

**Comment by overvenus** [comment]
dup with https://github.com/tikv/tikv/issues/16229
