### ISSUE TITLE
implement missing part of compaction filter for in-memory engine

### ISSUE THREAD

**Issue by SpadeA-Tang** [tikv/tikv#17086]
## Development Task
Compaction Filter is not implemented for HybridEngine. It may not be easily implemented for HybridEngine directly cause RocksEngine is directly used in GcContext :
```
pub struct GcContext {
    pub(crate) db: Option<RocksEngine>,
    pub(crate) store_id: u64,
    pub(crate) safe_point: Arc<AtomicU64>,
    pub(crate) cfg_tracker: GcWorkerConfigManager,
    feature_gate: FeatureGate,
    pub(crate) gc_scheduler: Scheduler<GcTask<RocksEngine>>,
    pub(crate) region_info_provider: Arc<dyn RegionInfoProvider + 'static>,
    #[cfg(any(test, feature = "failpoints"))]
    callbacks_on_drop: Vec<Arc<dyn Fn(&WriteCompactionFilter) + Send + Sync>>,
}
```
We may implement it by using the disk_engine of HybridEngine.

**Comment by overvenus** [comment]
What issue does it cause if we does not enable compaction filter for HybridEngine?

**Comment by SpadeA-Tang** [comment]
> What issue does it cause if we does not enable compaction filter for HybridEngine?

No GC will be performed for RocksDB.
