### ISSUE TITLE
Commit log duration is high when hibernate regions are awake

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#17101]
## Bug Report

![b57e15ae-443b-47de-867e-033bfeb70713](https://github.com/tikv/tikv/assets/13497871/64cc79ca-904d-483b-b399-46779fb66c3f)

**Comment by rleungx** [comment]
I also encounter this issue in a large cluster. It could cause the leader to drop after restarting PD.

**Comment by Connor1996** [comment]
@rleungx It's due to too many messages sent by these regions when they want to be hibernated again which blocks heartbeat/append messages being sent in time.

But why restarting PD would cause leader drop?

**Comment by rleungx** [comment]
I have a large number of regions in one TiKV, maybe because the heartbeat message is not sent in time?

**Comment by Connor1996** [comment]
walkaround: enlarge ` grpc-raft-conn-num`
