### ISSUE TITLE
tikv scaling in blocked due to one region can not transfer

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#17191]
### What version of TiKV are you using?
[2024/06/25 11:43:54.651 +08:00] [INFO] [cmd.go:151] ["Start remote command"] [cmd="/tiup/deploy/tikv-*/bin/tikv-server -V"] [nodename=tikv2]
TiKV 
Release Version:   8.2.0-alpha
Edition:           Community
Git Commit Hash:   87f66434fb7fa2395cb5ebfe45b3f66e2527c451
Git Commit Branch: HEAD
UTC Build Time:    2024-06-24 06:44:26
Rust Version:      rustc 1.77.0-nightly

[2024/06/25 11:43:55.616 +08:00] [INFO] [cmd.go:151] ["Start remote command"] [cmd="/tiup/deploy/pd-*/bin/pd-server -V"] [nodename=pd2]
Release Version: v8.2.0-alpha-97-gdebb5fe
Edition: Community
Git Commit Hash: debb5febb83e032da5a0c0162b1bff656a8fe931
Git Branch: HEAD
UTC Build Time:  2024-06-24 03:24:39

### What operating system and CPU are you using?
8c/16g

### Steps to reproduce
1、scale out tikv from 3 to 6
2、wait for scale out to complete
3、scale in tikv from 6 to 3

### What did you expect?
scale in tikv success

### What did happened?
the status of one tikv is always offline due to one region can not transfer
![img_v3_02c7_125604a5-1a00-4992-aabd-759b2523bf6g](https://github.com/tikv/tikv/assets/84712107/7fbec4a5-b825-43ca-b247-663df1bbbe7d)
![image](https://github.com/tikv/tikv/assets/84712107/c7aae5fe-bba1-4277-8946-0ec65e38365e)

**Comment by glorv** [comment]
@Lily2025 Does metrics and logs still available, please provide the address

**Comment by overvenus** [comment]
Caused by https://github.com/tikv/tikv/issues/17213
