### ISSUE TITLE
Always keep reporting `Already in CPU Profiling`

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#17234]
### What version of TiKV are you using?

v7.5.2

### What operating system and CPU are you using?

![img_v3_02cf_2a47982b-640a-46c7-a49c-769ff40ab27g](https://github.com/tikv/tikv/assets/13497871/9653e929-a855-4af8-8e65-1ce0dc14272f)

**Comment by overvenus** [comment]
I've seen the same message in v7.5.4; we need to cherry-pick the fix for the CPU profile to work.
