### ISSUE TITLE
In-memory Engine: Duplicate error when range cache enabled

### ISSUE THREAD

**Issue by qiaoxinke** [tikv/tikv#17245]
### What version of TiKV are you using?

v8.1.0-20240621-c57aef1

### What operating system and CPU are you using?

tidb cloud dedicated cluster

### Steps to reproduce

1. change "insert" statement in sysbench lua script to "insert ... on duplicate key update ... " as belows.
`   con:query(string.format("INSERT INTO %s (id, k, c, pad) VALUES " ..
                               "(%d, %d, '%s', '%s')  ON DUPLICATE KEY UPDATE k= %d, c='%s', pad='%s'",
                              table_name, id, k_val, c_val, pad_val, k_val, c_val, pad_val))`
2.run sysbench with multi-threads such as threads=100

3. the duplicate entry error will occur with a certain probability but not 100%.
`FATAL: mysql_drv_query() returned error 1062 (Duplicate entry '?' for key 'sbtest17.PRIMARY') for query 'INSERT INTO sbtest17 (id, k, c, pad) VALUES (505, 537, '35427163386-66434975679-60734913781-63936242757-88587149249-49987974580-52063606092-35392391173-06670234997-51692119414', '55391731813-20939278325-13595195053-78812361500-66575989095')  ON DUPLICATE KEY UPDATE k= 537, c='35427163386-66434975679-60734913781-63936242757-88587149249-49987974580-52063606092-35392391173-06670234997-51692119414', pad='55391731813-20939278325-13595195053-78812361500-66575989095''
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_dml_less1000.lua:19: SQL error, errno = 1062, state = '23000': Duplicate entry '?' for key 'sbtest17.PRIMARY'
FATAL: mysql_drv_query() returned error 1062 (Duplicate entry '?' for key 'sbtest17.PRIMARY') for query 'INSERT INTO sbtest17 (id, k, c, pad) VALUES (441, 498, '39737765223-76388610332-37719229090-10882829262-80128900507-84179942182-52918941709-03562905073-72489028054-80380455269', '32143820534-73863753728-80997232311-18470349394-97294667789')  ON DUPLICATE KEY UPDATE k= 498, c='39737765223-76388610332-37719229090-10882829262-80128900507-84179942182-52918941709-03562905073-72489028054-80380455269', pad='32143820534-73863753728-80997232311-18470349394-97294667789''
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_dml_less1000.lua:19: SQL error, errno = 1062, state = '23000': Duplicate entry '?' for key 'sbtest17.PRIMARY'
Error in my_thread_global_end(): 2 threads didn't exit`

### What did you expect?
No duplicate entry error for insert ... on duplicate key update statement.

### What did happened?
Duplicate entry error reported for insert ... on duplicate key update statement.

**Comment by qiaoxinke** [comment]
@overvenus @SpadeA-Tang

**Comment by SpadeA-Tang** [comment]
This issue is not reproduced after serverial reproduction tests, so close it.
