### ISSUE TITLE
Bloom filter is invalidated after upgrade from <=7.1 to >=7.2

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#17272]
## Bug Report

v7.2 includes a rust-rocksdb commit (https://github.com/tikv/rust-rocksdb/pull/740) that unexpectedly changes the bloom filter name, invalidating bloom filters built by TiKV versions <=v7.1.

https://github.com/tikv/rust-rocksdb/blob/224bed6ffa29ba3bbe9a91ef6bda7186200c59a8/librocksdb_sys/crocksdb/c.cc#L3930-L3944

This occurs because filter names are written in SST files, and RocksDB only uses filters included in SST files with matching names.

~To workaround this issue, TiKV needs to add two filters during RocksDB Instantiation, one with the original name, and the other with the new name:~
* ~Original: rocksdb.BuiltinBloomFilter~
* ~New: rocksdb.BuiltinBloomFilter.FullBloom~

(Edit: I made a false assumption, RocksDB can only accept one filter.)

### What version of TiKV are you using?

\>=v7.2

### Steps to reproduce

Upgrade and check if the filter insert metrics in TiKV rocksdb block cache metrics.
It should be similar to the picture in https://github.com/tikv/rust-rocksdb/pull/740#issuecomment-1498394224

### What did you expect?

Bloom filters are still valid.

### What did happened?

Bloom filters are invalidated.

**Comment by v01dstar** [comment]
[This](https://github.com/tikv/rocksdb/blob/45509f0f530ad370863876fc1ee95ccf85bfe96d/table/block_based/block_based_table_builder.cc#L1579-L1581) is how RocksDB persist filters inside SST.

[This](https://github.com/tikv/rocksdb/blob/45509f0f530ad370863876fc1ee95ccf85bfe96d/table/block_based/block_based_table_reader.cc#L921-L922) was how RocksDB determine whether the SST's filter is usable or not. Basically, try to find the filter meta block by looking up the filter's name.

[This](https://github.com/v01dstar/rocksdb/blob/620dcb341c33161cb3ef29e8b146620cfd467564/table/block_based/block_based_table_reader.cc#L1029-L1054) is how RocksDB determine whether the SST's filter is usable or not. Both current "names" and "legacy names" map to the same filter.
