### ISSUE TITLE
Add interfaces needed by `compact-log-backup`.

### ISSUE THREAD

**Issue by YuJuncen** [tikv/tikv#17284]
Basic steps for implantation of log compaction:
- Added `WalkBlobStorage` and implemented it for S3 and GCS.
- Allow the `Read` of the `write` call to borrow local variables.
- Added a new macro `retry_expr!` for retrying.
- Added `Reset` for the reader that generated by `SstWriter`.

**Comment by Tristan1900** [comment]
can we add a few lines of description of this issue, thanks!
