### ISSUE TITLE
CausTS: why requirement of tso in rawkv apiv2 is much less than the client operation

### ISSUE THREAD

**Issue by mzygQAQ** [tikv/tikv#17281]
Logically speaking, each rawput requires 2 tsos, one for the datakey mvcc commit ts and the other for the resovled ts.
But the explanations in the comments are so different. Is there any underlying reason for this？

@pingyu 

https://github.com/tikv/tikv/blob/cc2f344f0bb2bc484b04f9261adb140fb374c8d2/components/causal_ts/src/config.rs#L20

**Comment by pingyu** [comment]
> Logically speaking, each rawput requires 2 tsos, one for the datakey mvcc commit ts and the other for the resovled ts.

You are right. The comment is not correct and should be removed.

One TSO for every batch is an early implementation and changed by #13326.
