### ISSUE TITLE
Serve a proxy at TiKV's Advertise-address

### ISSUE THREAD

**Issue by nicolaslopezbravo** [tikv/tikv#17362]
## Question

Hello, From documentation I've seen the advertising address set up to be the external hostname with the same port as the listening address for PD's and client communication. e.g
```
--addr="0.0.0.0:20160" \
--advertise-addr="192.168.1.106:20160" 
```
Is there any restriction on serving a proxy at this advertising address that will forward requests appropriately to TiKV at its listening address? 
```
--addr="0.0.0.0:20160" \
--advertise-addr="0.0.0.0:20161" 
```
where proxy runs on 0.0.0.0:20161

Thank you.

**Comment by glorv** [comment]
@nicolaslopezbravo From tikv's current implementation, `advertise-addr` is the address for other components to connect to tikv, so I think is viable to set it to a proxy address to tikv's real address.

**Comment by nicolaslopezbravo** [comment]
nice thank you!
