### ISSUE TITLE
Although performance degradation under massive regions is a known issue, in addition to merging regions, are there other methods available?

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#17375]
### What version of TiKV are you using?
v8.2.0

### Steps to reproduce
step1:
1. br restore full datase with 50,000 databases and 250,000 tables (5 tables per databse,2 rows per table and the number of empty region is about 480k）
2. warmup for 10m
3. sysbench run oltp_read_write 5m v1
4. sysbench run oltp_read_write 5m v2
step2:
1. br restore full datase with 1 databases and 16 tables (10M rows per table)
2. warmup for 10m
3. sysbench run oltp_read_write 5m v1
4. sysbench run oltp_read_write 5m v2

### What did you expect?
There is no performance regression with  250,000  tables compared with 16 tables when there are many empty regions. 
### What did happened?
With V2 enabled, the performance of 50,000 databases experiences a 17.22% regression compared to that of a single database.

**Comment by LykxSassinator** [comment]
Can be closed as https://github.com/tikv/tikv/pull/17408 is merged.
