### ISSUE TITLE
During the process of merging regions, TiKV's execution speed is very slow, and it occurs multipl OOM events.

### ISSUE THREAD

**Issue by shaoxiqian** [tikv/tikv#17376]
### What version of TiKV are you using?
nightly

### Steps to reproduce
1. restore full database with 200k databases and 1M tables
2. 2M empty regions were created
3. pd config set merge-schedule-limit 512

### What did you expect?
tikv will not be the bottleneck for merging regions and not oom
### What did happened?
1. There are too many pending tasks(mergeing regions)
2. Tikv occurs multipl OOM events.

**Comment by LykxSassinator** [comment]
Can be closed as #17408 is closed.
