### ISSUE TITLE
Optimize suspending writes when memory usage is high

### ISSUE THREAD

**Issue by nolouch** [tikv/tikv#17392]
## Background 
Here are 3 tikv

- tikv-2: Has the least remaining disk space (20G) < 5%, with some 'AlmostFull' errors, it refuse the write, and also other nodes do not send append log messages to this node (this issue lacks monitoring for handling proposals correctly if the majority of peers are disk full, as noted in Pull Request [handle proposals correctly if majority peers are disk full by hicqu · Pull Request #10671 · tikv/tik](https://github.com/tikv/tikv/pull/10671)).
![image](https://github.com/user-attachments/assets/912d8079-6be6-4f45-af71-f983e7c56d08)

- tikv0: because tikv-2 not push ahead raftlog, so tikv0, tikv-0 cannot compact log, the memory increase. after high memory usage in tikv0, it refuse to write(append):
![image](https://github.com/user-attachments/assets/defe13df-e2f9-47b4-854c-6eabe83b7d9a)
![image](https://github.com/user-attachments/assets/df166408-2293-4103-956e-ebd25defbc23)

- tikv1: also cannot server write because other 2 node stop append. 
 
![image](https://github.com/user-attachments/assets/d8215051-ba62-4a03-a45b-b26f371c23a6)
![image](https://github.com/user-attachments/assets/d4dfaea9-ae22-4634-8d66-40f35199304e)

##  What do you want to see
Improve this case: We need to prevent the expansion of this failure radius. the RAC is one node disk full, but the others are not full.  which lets another node's memory increase and another node's server because busy, it is unreasonable. if `tikv-0` can evict the entry cache or compaction log force, then `tikv-0` will not cause fault propagation, thereby reducing the explosion radius.

Improve the observability: the tidb side and client side see some error backoff is regionMiss or regionUnabliable, from the log, it report server is busy from `tikv-2`, the root cause is actually from the `tikv-1` with disk full.

## Version
v6.1.3

**Comment by AndreMouche** [comment]
seems similar with https://github.com/tikv/tikv/issues/15800

**Comment by hhwyt** [comment]
The issue is caused by too many entries in the entry cache on followers. leading to rejected writes.

One current solution is to trigger entry cache eviction earlier to prevent write rejections. A potential future optimization could involve treating followers differently, as they don’t need to cache as many entries as the leader, which uses in-memory entries to replicate them to other followers.​
