### ISSUE TITLE
PR#17486 may cause 5.3% performance regression in sysbench

### ISSUE THREAD

**Issue by owlsome2501** [tikv/tikv#17510]
### What version of TiKV are you using?

tikv/tikv@070cbd53a569f643e190a50d11bd790827441e69

### What operating system and CPU are you using?

K8S, x86

### Steps to reproduce

1. Deploy a cluster with 3 TiDB and 3 Tikv.
2. Run benchmark sysbench (oltp_read_write).

### What did you expect?

No performance regression.

### What did happened?

#17486 caused QPS regression 5.32% in benchmark sysbench (oltp_read_write) compared to baseline 77313.87.

| description       | tidb                                                    | tikv                                                 | pd                                               | QPS                   |
| ----------------- | ------------------------------------------------------- | ---------------------------------------------------- | ------------------------------------------------ | ------------------------------------ |
| last success      | pingcap/tidb@fef43c563900dc9f4692c14246259c7df2f5d715     | tikv/tikv@3ca20467241c587bbf13c373c19710adf9bda83d     | tikv/pd@a4ae781d07dcc75db681cb475c6785d830e410ac     | 74049.18            |
| first regression  | pingcap/tidb@fef43c563900dc9f4692c14246259c7df2f5d715 | tikv/tikv@070cbd53a569f643e190a50d11bd790827441e69 | tikv/pd@a4ae781d07dcc75db681cb475c6785d830e410ac | 73204.30        |

**Comment by glorv** [comment]
Like discussed in #17494, the regression is an accumulation of many different changes overtime. For the logic of #17486, I don't think it will cause any side-effect as its change is on a very cold path and target feature is disabled by default.
