### ISSUE TITLE
PR#17555 may cause 7.4% performance regression in benchmarksql

### ISSUE THREAD

**Issue by owlsome2501** [tikv/tikv#17568]
### What version of TiKV are you using?

tikv/tikv@7a8d05ad8088120a2654516c6f6f0079bf677783

### What operating system and CPU are you using?

K8S, x86

### Steps to reproduce

1. Deploy a cluster with 3 TiDB and 3 Tikv.
2. Run benchmark benchmarksql (benchmarksql-1k).

### What did you expect?

No performance regression.

### What did happened?

#17555 caused QPS regression 7.45% in benchmark benchmarksql (benchmarksql-1k) compared to baseline 60193.12.

| description       | tidb                                                    | tikv                                                 | pd                                               | QPS                   |
| ----------------- | ------------------------------------------------------- | ---------------------------------------------------- | ------------------------------------------------ | ------------------------------------ |
| last success      | pingcap/tidb@249e88cd5a58aa1d2238797d155bbea88cc818de     | tikv/tikv@5abe1dd188192c37f9759b6ae3be21f23c06fb36     | tikv/pd@23d544f374e00a6c03a86437b57bd26365cb11ef     | 59101.24            |
| first regression  | pingcap/tidb@249e88cd5a58aa1d2238797d155bbea88cc818de | tikv/tikv@7a8d05ad8088120a2654516c6f6f0079bf677783 | tikv/pd@23d544f374e00a6c03a86437b57bd26365cb11ef | 55710.90        |

**Comment by LykxSassinator** [comment]
This performance regression can be reproduced by re-testing ?

**Comment by overvenus** [comment]
Update: Further testing conducted by @owlsome2501 reveals only a 3.4% regression. Given that the error margin is approximately 4%, and 3.4% is significantly lower than the 7.4% initially reported in this issue, this may be a false alarm.

**Comment by cfzjywxk** [comment]
It's a test environemnt issue verified by @owlsome2501 .
