### ISSUE TITLE
heatmap panel should use increase instead of rate

### ISSUE THREAD

**Issue by 0xdeafbeef** [tikv/tikv#17586]
https://github.com/tikv/tikv/blob/e6b3613ec8b689a3ed3ce5a8380490f0a9eca3c9/metrics/grafana/common.py#L919
![image](https://github.com/user-attachments/assets/c7afd660-fded-4eb2-8f91-b69b3918877c)
![image](https://github.com/user-attachments/assets/5d6bec96-bbb0-455a-bac6-167a754f8f53)

Otherwise you will get `count/$__rate_interval` instead of real count

**Comment by overvenus** [comment]
Thanks you for your report!

Just notice there is an errata in Grafana blog https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/#:~:text=Note%3A%20I%20accidentally,appearance.
