### ISSUE TITLE
tikv panic repeatedly when tikv rolling restart after update region size

### ISSUE THREAD

**Issue by Lily2025** [tikv/tikv#17639]
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.4.0
Edition:           Community
Git Commit Hash:   fa6e1753c2c4916ae5918281db3d863ec47ce322
Git Commit Branch: HEAD
UTC Build Time:    2024-10-10 06:40:20
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2024-10-13T04:46:35.930+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc 
2、update region size from 96M to 128M

### What did you expect?
no panic

### What did happened?
tikv panic repeatedly
`{"namespace":"e2e-oltp-dynamic-r-upt-c-stab-tps-7634930-1-417","log":"[lib.rs:479] [\"called `Option::unwrap()` on a `None` value\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at workspace/source/tikv/components/tikv_util/src/lib.rs:478:18\\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9\\n      std::panicking::rust_panic_with_hook\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:649:13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18\\n   4: rust_begin_unwind\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5\\n   5: core::panicking::panic_fmt\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14\\n   6: core::panicking::panic\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:144:5\\n   7: core::option::Option<T>::unwrap\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:931:21\\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_refresh_region_buckets\\n             at workspace/source/tikv/components/raftstore/src/store/fsm/peer.rs:6391:26\\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_casual_msg\\n             at workspace/source/tikv/components/raftstore/src/store/fsm/peer.rs:1168:17\\n   8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs\\n             at workspace/source/tikv/components/raftstore/src/store/fsm/peer.rs:704:48\\n   9: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\\n             at workspace/source/tikv/components/raftstore/src/store/fsm/store.rs:1096:9\\n  10: batch_system::batch::Poller<N,C,Handler>::poll\\n             at workspace/source/tikv/components/batch-system/src/batch.rs:380:27\\n  11: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\\n             at workspace/source/tikv/components/batch-system/src/batch.rs:551:17\\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\\n             at workspace/source/tikv/components/tikv_util/src/sys/thread.rs:438:13\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18\\n  12: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\\n      std::panicking::try::do_call\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\\n      std::panicking::try\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\\n      std::panic::catch_unwind\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5\\n  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\\n  14: start_thread\\n  15: clone3\\n\"] [location=/workspace/source/tikv/components/raftstore/src/store/fsm/peer.rs:6391] [thread_name=raftstore-5-1] [thread_id=119]","pod":"tc-tikv-3","level":"FATAL","container":"tikv"}`

**Comment by LykxSassinator** [comment]
Confused.

According to the error stack, it showed that TiKV has `panic`ed at unexpected code line:
https://github.com/tikv/tikv/blob/fa6e1753c2c4916ae5918281db3d863ec47ce322/components/raftstore/src/store/fsm/peer.rs#L6383-L6395
