### ISSUE TITLE
Slow score fails to update during IO hang

### ISSUE THREAD

**Issue by hhwyt** [tikv/tikv#17679]
### What version of TiKV are you using?

v8.4.0

### What operating system and CPU are you using?

8c/32g

### Steps to reproduce

1、run tpcc with 64 threads
2、inject one of tikv io hang

### What did you expect?
The slow score of IO-hanging TiKV node rapidly increase to 100.

### What did happened?
The slow score is low, while the pending tasks on pd_worker rapidly increase.

![img_v3_02fn_1c270cbd-e8a3-4796-b006-42f9ddecb29g](https://github.com/user-attachments/assets/15bd8ddf-f835-4a9b-92e4-ac185ef74766)
![img_v3_02fn_6fe5eb07-3b4e-4f91-97c9-3d29ae87b66g](https://github.com/user-attachments/assets/86f445e7-b989-41a9-ace8-7906685db131)
![img_v3_02fn_087d2fcb-8691-4565-9aa4-cf17076def9g](https://github.com/user-attachments/assets/3f14495e-27ae-437e-8e6e-f90af030a1b6)
![img_v3_02fn_bb1b565e-1505-4782-a983-ee9e072139eg](https://github.com/user-attachments/assets/6eed60e6-9347-4fac-b3f0-6ab65e3e81ff)

**Comment by hhwyt** [comment]
This is a random bug.

**Comment by hbisheng** [comment]
Same issue as #17939
