### ISSUE TITLE
TiDB latency not stable and TiKV OOM if running cdc changefeed when titan is on and average region size is large

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#17696]
### What version of TiKV are you using?
v8.4.0
31aa015dbe96bc5bcd676d7e32450f0205ceb104

### What operating system and CPU are you using?
X84, K8S

### Steps to reproduce
1. Deploy v8.4.0 cluster with 6 TiKV node (16C64G), titan is on.
2. br restore 4000 tables (~10TB)
3. start log backup task
4. create one CDC kafka changefeed to replicate the workload to Kafka
5. run workload

### What did you expect?
TiDB latency should be stable, when running workload

### What did happened?
TiDB latency not stable, and TiKV OOM seen.

![image](https://github.com/user-attachments/assets/28718d80-cdcd-43b1-8c45-2503735089c5)
![image](https://github.com/user-attachments/assets/5fcdc076-9a75-44a4-835b-6db078a786c2)

**Comment by overvenus** [comment]
The direct cause of this OOM is that CDC tasks piles up in the channel, from "apply" to "cdc," because the processing of `old_value_cb` is slowing down the CDC thread. Additionally, `old_value_cb` holds a snapshot, which can quickly result in millions of live snapshot counts.

![{601CC9E3-F873-407E-9811-006B7BF08D07}](https://github.com/user-attachments/assets/093983ce-2c15-4a6a-927e-c29814346125)

https://github.com/tikv/tikv/blob/5a703ad8412d687e18efbe14c419967c323360a5/components/cdc/src/observer.rs#L124-L136

---

To resolve this issue, we can tracking pending CDC tasks memory usage and stops observe if a region exceeds memory quota.

**Comment by fubinzh** [comment]
https://github.com/tikv/tikv/pull/17724 partly fixed this issue, by taking cdc tasks into memory quota to prevent the TiKV OOM caused by too many pending tasks. 
With this fix, TiKV will not OOM, and TiDB latency can be relatively stable. But we still have the issue that CDC replication capability is greatly impacted due to "slow processing of old_value_cb", this is tracked in another issue: https://github.com/tikv/tikv/issues/17781

Test results with fix (TiKV Commit: https://github.com/tikv/tikv/commit/22bbfeb958936ab75dda1f60ca6bdc1cc0bb5231)
![image](https://github.com/user-attachments/assets/18c2e458-ff1e-461a-aa9a-117540e7c731)
![image](https://github.com/user-attachments/assets/03c9678c-bb89-4eb4-9eb5-c2c306852904)
![image](https://github.com/user-attachments/assets/20ca87da-32d6-4ccc-ab3e-b91233b533ad)
![image](https://github.com/user-attachments/assets/3f02719a-724f-4bd6-b33e-177a42a69be8)
![image](https://github.com/user-attachments/assets/2180fbe9-0a10-4646-a1b7-d1eb2b20fd5f)
![image](https://github.com/user-attachments/assets/957013e9-7a9d-4bf2-af67-0264286f124a)

**Comment by fubinzh** [comment]
Tested the scenario with v8.1.1 build.
- This issue is NOT reproducible with v8.1.1 release when tikv region-split-size = "256MiB" and pd region-split-size = "128MiB" (Actual avg region size: ~120MB)
![image](https://github.com/user-attachments/assets/17a73341-953c-4bab-be72-d8eb92b1e525)
![image](https://github.com/user-attachments/assets/ad4ebd98-4859-4e4a-bd97-6abd09c9be02)


- This issue is reproducible with v8.1.1 release when tikv region-split-size = "512MiB" and pd  region-split-size = "256MiB" (Actual avg region size: ~320MB)


```
# tikv
[rocksdb]
  max-open-files = 10240
  [rocksdb.titan]
    enabled = true
  [rocksdb.defaultcf.titan]
    blob-cache-size = "24GB"
    min-blob-size = "4KB"
    discardable-ratio = 0.4

[coprocessor]
  region-split-size = "256MiB"
  region-split-keys = 2560000
  region-max-size = "384MiB"
  region-max-keys = 3840000

#pd
[schedule]
  max-merge-region-size = 256
  max-merge-region-keys = 2560000
```

![image](https://github.com/user-attachments/assets/a92fa778-d43c-4d7f-abf4-dd7f892fb2d0)
![image](https://github.com/user-attachments/assets/a85c0249-ecf8-4917-9a40-e7bd7877b866)
