### ISSUE TITLE
CDC lag up to 2.5h when titan is on and region size is large (280MB+)

### ISSUE THREAD

**Issue by fubinzh** [tikv/tikv#17781]
### What version of TiKV are you using?
v8.4.0 
Commit: 22bbfeb958936ab75dda1f60ca6bdc1cc0bb5231

### What operating system and CPU are you using?
X86, Docker 

### Steps to reproduce
1. Deploy v8.4.0 cluster with 6 TiKV node (16C64G), titan is on.
2. br restore 4000 tables (~8TB), avg region size is about 280MB+ after restore 
3. start log backup task
4. create one CDC kafka changefeed to replicate the workload to Kafka
5. run workload

### What did you expect?
https://github.com/tikv/tikv/pull/17724 partly fixed issue https://github.com/tikv/tikv/pull/17724, by taking cdc tasks into memory quota to prevent the TiKV OOM caused by too many pending tasks. With this fix, TiKV will not OOM, and TiDB latency can be relatively stable. But we still have the issue that CDC replication capability is greatly impacted due to "slow processing of old_value_cb", we want this issue be fixed as well.

### What did happened?
With https://github.com/tikv/tikv/pull/17724, 
- Takes 2.8h to finish initial scan of 2h cdc lag. The initial scan speed is 4X slower than that of v8.3.0
- CDC lag up to 2.5h during normal replication
![image](https://github.com/user-attachments/assets/03c9678c-bb89-4eb4-9eb5-c2c306852904)
![image](https://github.com/user-attachments/assets/20ca87da-32d6-4ccc-ab3e-b91233b533ad)
![image](https://github.com/user-attachments/assets/3f02719a-724f-4bd6-b33e-177a42a69be8)
![image](https://github.com/user-attachments/assets/2180fbe9-0a10-4646-a1b7-d1eb2b20fd5f)
![image](https://github.com/user-attachments/assets/957013e9-7a9d-4bf2-af67-0264286f124a)

**Comment by v01dstar** [comment]
Opened another issue #17877
