### ISSUE TITLE
Importer: why we do the checksum operation on the sst just written by tikv?

### ISSUE THREAD

**Issue by mzygQAQ** [tikv/tikv#17804]
https://github.com/tikv/tikv/blob/962553d85013d273008a9168f843b577e591386d/src/import/sst_service.rs#L642

In our tests, the checksum operation‘s io cost is too much, our importer::write disk write io reach 700M/s, the read io from this checksum also cost 700M/s
This interferes with the writing speed, even that the speed of writing through importerWrite is not as fast as writing through upper level Raft.
If it weren't for this read, I think the write speed could have been greatly improved.

This file was written by TiKV, not downloaded through the download interface. Why do we need to do an expensive checksum?

@Connor1996

**Comment by Connor1996** [comment]
Checking the checksum after downloading is a general practice. Ingesting corrupted data would get more trouble. Though, maybe can make it optional.

**Comment by mzygQAQ** [comment]
> Checking the checksum after downloading is a general practice. Ingesting corrupted data would get more trouble. Though, maybe can make it optional.

This checksum opeartion is under ImportSST::write/raw_write, not under downloadRPC,  the SST file was written by TiKV self instead of download from s3 etc, i dont think this checksum is useful ^V^

**Comment by Connor1996** [comment]
There is still a chance that writing is corrupted. The mindset is check the file before ingesting no matter where it came from. Though I agree, it's expensive and can make it optional.

**Comment by mzygQAQ** [comment]
oh~ thanks for you reply
