### ISSUE TITLE
In-memory Engine: bank workload has more than 12% regression when IME is enabled

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#17838]
## Bug Report

tps | qps | avg_latency(ms) | P99_latency(ms) | monitor_url
-- | -- | -- | -- | --
2376 | 55945 | 1.7 | 13.5 | https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7434582726429575662
2722 | 64090 | 1.47 | 10.8 | https://clinic.pingcap.com.cn/portal/#/orgs/33/clusters/7434582726429575662

![img_v3_02gj_319701c8-f367-472a-80e4-2f2878c0686g](https://github.com/user-attachments/assets/d4db26e7-8654-447c-b416-8ea76658d71b)

The first half of the test shows a significant difference, according to the above metric.

### What version of TiKV are you using?

Nightly, 2024-11-08

### Steps to reproduce

Run bank workload.

### What did you expect?

No regression or less than 5%.

### What did happened?

More than 12%.

**Comment by glorv** [comment]
I have reran this benchmark multiple times and this kind of large regression never recurred. So I'll close this issue now. We may reopen it if it occurs again.
