### ISSUE TITLE
tikv does not build on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [tikv/tikv#1965]
1. What version of Rust are you using (`rustc --version`)?
Beta 1.19 and Nightly 1.20 downloaded from - https://static.rust-lang.org/dist/rust-beta-powerpc64le-unknown-linux-gnu.tar.gz

2. What operating system and processor architecture are you using?
ppc64le, RedHat 7.3

3. What did you do?
Build tikv using make / make static_release
The build fails with the following error
error[E0432]: unresolved import `types::os::arch::c95::*`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.12/rust/src/liblibc/lib.rs:100:9
    |
100 | pub use types::os::arch::c95::*;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `arch` in `os`
... ...

4. Analysis so far:
Initially, I was suspecting that the libc crate is not ported for ppc64le, however, after interacting with the rust community, I found that support for ppc64le is available in the latest version of the libc crate.
https://github.com/rust-lang/rust/issues/42858

They suggest upgrading utime, nix and other tikv dependencies to the latest version for better platform compatibility. 

I am currently trying to understand what all might need to be updated- any pointers/thoughts on this would be of great help - thanks in advance!!

Regards,
Priya

**Comment by siddontang** [comment]
Hi @seth-priya 

We only support x86-64 architecture and don't support ppc64le.

**Comment by seth-priya** [comment]
Hi @siddontang, thanks for your response! 
I understand the tikv currently does not support ppc64le architecture and have, towards that end, started porting it. 
We have validated and found that tidb (now) and pd build and successfully pass all their unit tests on ppc64le, so it would be great to get tikv working as well!

**Comment by siddontang** [comment]
Hi @seth-priya 

Can you upgrade libc with `cargo update -p libc` and make again?

**Comment by seth-priya** [comment]
Hi @siddontang, thanks for your inputs!

I tried this and it fails while compiling **strsim** and **flat_map**

Here is what I did (on a fresh checkout and clean environment)

bash-4.2#  cargo update -p libc
error: There are multiple `libc` packages in your project, and the specification `libc` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  libc:0.1.12
  libc:0.2.21

bash-4.2# cargo update -p libc:0.1.12
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/pingcap/kvproto.git`
    Updating git repository `https://github.com/pingcap/grpc-rs.git`
    Updating git repository `https://github.com/pingcap/rust-rocksdb.git`
    Updating git repository `https://github.com/pingcap/tipb.git`
    Updating git repository `https://github.com/pingcap/rust-prometheus.git`
    Updating git repository `https://github.com/busyjay/jemallocator.git`

First few lines of the error:
   Compiling strsim v0.6.0
error[E0432]: unresolved import `types::os::arch::c95::*`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.12/rust/src/liblibc/lib.rs:100:9
    |
100 | pub use types::os::arch::c95::*;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `arch` in `os`

and last few
error[E0204]: the trait `Copy` may not be implemented for this type
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.12/rust/src/liblibc/lib.rs:441:26
    |
441 |                 #[derive(Copy, Clone)]
    |                          ^^^^
...
444 |                     pub ifa_name: *mut c_char,
    |                     ------------------------- this field does not implement `Copy`

   Compiling flat_map v0.0.4
error: aborting due to previous error(s)

Rust and cargo versions on my system are:
bash-4.2# rustc --version
rustc 1.20.0-nightly (859c3236e 2017-06-26)
bash-4.2# cargo --version
cargo 0.21.0-nightly (d26fd6f08 2017-06-20)

I will continue to dig into this.

**Comment by seth-priya** [comment]
Hi @siddontang,, just a quick update.

I updated strsim, flat_map and a few more dependencies using cargo update. I could proceed, however now I am getting an error while compiling nix and simply updating that using cargo update does not help.

bash-4.2# cargo update -p nix:0.5.1
    Updating registry `https://github.com/rust-lang/crates.io-index`
bash-4.2# cargo update -p nix:0.6.0
    Updating registry `https://github.com/rust-lang/crates.io-index`
bash-4.2# make
cargo build --release --features "default"
   Compiling libc v0.1.12
   Compiling nix v0.5.1
   Compiling librocksdb_sys v0.1.0 (https://github.com/pingcap/rust-rocksdb.git#f7c020d8)
   Compiling grpc-sys v0.1.0 (https://github.com/pingcap/grpc-rs.git#5e425f27)
   Compiling sys-info v0.4.1
   Compiling nix v0.6.0
error[E0432]: unresolved import `types::os::arch::c95::*`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.12/rust/src/liblibc/lib.rs:100:9
    |
100 | pub use types::os::arch::c95::*;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `arch` in `os`

error[E0432]: unresolved import `types::os::arch::c99::*`

Looks like the latest version of nix 0.8.1, https://crates.io/crates/nix should work as it depends on libc 0.2.21 - will check how to update nix, next

**Comment by siddontang** [comment]
Hi @seth-priya 

Maybe you can remove Cargo.lock and compile again.

**Comment by siddontang** [comment]
@seth-priya 

Seem you can try:

1. Remove Cargo.lock
2. Use 0.2.24 for libc in Cargo.toml `libc = "0.2.24"`
3. Remove `features = ["static-link"]` in  Cargo.toml for `[dependencies.grpc]`

I tried above and can use the latest libc to build TiKV.

**Comment by seth-priya** [comment]
Sure - will try, I did try "make clean" some time back, but again hit the same issue with nix. I will try removing Cargo.lock explicitly, otherwise go back and have a closer look at the error being thrown by nix. Thanks!

**Comment by seth-priya** [comment]
@siddontang 
Thanks! I think I am hitting another problem on ppc64le ....

Just to be sure, I created a clean setup and tried the above steps i.e.
1.Remove Cargo.lock
2.Use 0.2.24 for libc in Cargo.toml  libc = "0.2.24" 
3.Remove  features = ["static-link"]  in Cargo.toml for  [dependencies.grpc] 

However, it failed at the below point   Compiling ordermap v0.2.10
error[E0432]: unresolved import `types::os::arch::c95::*`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.12/rust/src/liblibc/lib.rs:100:9
    |

 I am suspecting that this is because there are other dependencies in Cargo.toml that in turn depend on libc (specifically libc-0.1.12) and will need to be updated as well for the build to work.

That is what I have been trying, but looks like there are multiple such dependencies and it will take some effort to figure them all out, unless there is a way to do a recursive update.

**Comment by siddontang** [comment]
Hi @seth-priya 

I think you can file an issue for the ordermap repository and let it updates libc.

**Comment by seth-priya** [comment]
@siddontang, I could resolve the issue with ordermap by specifying the latest version of that in tikv Cargo.toml as follows:
ordermap = "0.2.10"

I did similar changes for other dependencies as their latest versions depend on libc 0.2.x

However, there is a compilation issue with nix - it seems that even latest release 0.8.1 does not support ppc64le, mainline does. I could build the mainline version and am trying to build tikv with that.

**Comment by siddontang** [comment]
Cool @seth-priya 

Wait for your good news :-)

**Comment by seth-priya** [comment]
Just wanted to provide a quick update here - 
I am continuing to work on this. However, this is a bit complicated as there are a number of dependencies that themselves will first need to be updated to use the latest versions of nix and / or libc in particular. 

Some of these include jemallocator (systest depends on libc 0.1), signal (depends on nix 0.6, that does not support Power), kvproto (this again depends on nix 0.6). grpc-rs might also require some changes because it is currently using an older version of boringssl. Simply upgrading the versions for these does not seem to work as some of interfaces have changed across the versions.

In the meantime, I have been successfully able to build/validate some of the other dependencies on Power. These include the mainline versions of nix , boringssl, tipb, rust-Prometheus, kcov,  libprotoc, gflags among others.

**Comment by seth-priya** [comment]
@siddontang - just wanted to provide an overall summary of the progress of the port to ppc64le, so far.

1- As a first step, all the dependencies (gflags, rocksdb, kcov, rustfmt) could be successfully built from source and validated.
2- Version of the following dependencies had to be updated in Cargo.toml - num, utime, url, mio as their older versions were not supported on ppc64le.
3- Interacted with the nix community and they confirmed that ppc64le is now supported as a Tier-1 architecture. They have now released version 0.9.0, that has support for ppc64le. nix would need to be updated to this version in tikv.
4- Submitted PR https://github.com/tailhook/signal/pull/8 to upgrade the version of nix used by signal. A new version of signal "0.4" (with ppc64le support) is released with this change and the version for signal in tikv needs to be updated to this.
5 - Submitted PR to upgrade libc version in jemallocator
https://github.com/alexcrichton/jemallocator/commit/0003dce9bdf8b32dc255c1f720aa1a084f9ca734
This is now supported on ppc64le.
6 - Updated grpc-rs to use grpc master (PR yet to be raised)
7 - Successfully re-built kvproto using updated grpc-rs (PR yet to be raised)
8 - Modified sys-info-rs code to support ppc64le (PR yet to be raised).

With the above changes, I was able to proceed with tikv compilation - 112 dependencies seem to have been complied as part of tikv compilation process (including all direct dependencies listed in Cargo.toml).

Currently tikv compilation is failing because of using a newer version of mio - basically the APIs used by tikv have been deprecated in newer versions of mio - I shall raise a separate issue to discuss that with the community.

Thanks!

**Comment by siddontang** [comment]
Greate @seth-priya 

You can send us a PR to support ppc64le.

> Submitted PR to upgrade libc version in jemallocator

we don't use alex jemallocator, we use https://github.com/busyjay/jemallocator, /cc @BusyJay seem we can update with the change.

**Comment by BusyJay** [comment]
Yes. And we don't have to use mio actually, we may not depend on it anymore in the future.

**Comment by seth-priya** [comment]
Thanks @siddontang, @BusyJay - I will submit a PR for tikv as soon as all the compilation issues are resolved and I have am able to run the unit tests. Currently, I am stuck on the mio issue as compilation fails at this point.
@BusyJay is there are a way to skip this (mio dependency) locally? When are the changes for removing mio expected? 
@BusyJay also let me know if I need to raise a PR to https://github.com/busyjay/jemallocator to merge that change made here https://github.com/alexcrichton/jemallocator/commit/0003dce9bdf8b32dc255c1f720aa1a084f9ca734?

Thanks!!

**Comment by BusyJay** [comment]
I'm afraid you can't skip it locally without changing the code (a lot). But last time I checked, mio provides a compatible layer via an additional deprecated crate. So you should be able to update the mio by adding this additional dependency. Although this may hurt performance.

You can just ignore jemallocator for now. It won't be enabled unless mem-profiling feature is eanbled.

**Comment by seth-priya** [comment]
Thanks Jay, that helps - Yes, I have started working on using the "deprecated" APIs after upgrading mio, I believe since the longer term plan is to remove dependency on mio, use of deprecated APIs for now to identify and fix the next set of compilation issues on ppc64le would be good way forward. I can re-visit mio later, as required.

**Comment by seth-priya** [comment]
Just a quick update on where I am with the port on ppc64le ...

I was able to resolve mio issues by using the latest version of mio 0.6.3 with the deprecated APIs. Subsequently, tikv compilation was failing due to use of jemalloc, which I have temporarily tried to disable by disabling memory profiling. Now I am getting the following issue 
   Compiling tikv v0.0.1 (file:///root/tikv)
error[E0599]: no associated item named `CeilInt` found for type `tipb::expression::ScalarFuncSig` in the current scope
   --> src/coprocessor/select/xeval/evaluator.rs:555:13
    |
555 |             ScalarFuncSig::CeilInt => self.ceil_int(ctx, expr),
    |             ^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `FloorInt` found for type `tipb::expression::ScalarFuncSig` in the current scope
   --> src/coprocessor/select/xeval/evaluator.rs:557:13
    |
557 |             ScalarFuncSig::FloorInt => self.floor_int(ctx, expr),
    |             ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `tikv`.

To learn more, run the command again with --verbose.

Looking into it further.
Meanwhile the changes for sys-info-rs have been up-streamed and the community has released a new version of the crate.

**Comment by BusyJay** [comment]
We update tipb recently and remove these item already. Maybe you need to merge master or keep using the same revision of tipb your branch used to.

**Comment by seth-priya** [comment]
@BusyJay , thanks - will try that!!

**Comment by seth-priya** [comment]
I was able to run "cargo build" successfully after upgrading the dependencies and tikv fork to the latest. I went a step further and tried to run "cargo test". 

This is what I have till now
test result: ok. 370 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/bench_tikv-3efc343e4c6c3898

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/tikv_ctl-6dd3468767879809

running 1 test
test tests::test_ctl_mvcc ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/tikv_server-5e714a9e2a8b0611

running 1 test
test signal_handler::imp::tests::test_stats_print ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/tests-4d8719e4fa57ca4e

running 330 tests 
....
test result: FAILED. 212 passed; 118 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test tests'

Looking into the test failures.

**Comment by seth-priya** [comment]
Failure count is now down from 118 to 2 for the above set. @siddontang , @BusyJay , is there a way to run each test module independently so that I can identify if there are any issue beyond the current 2 failures? 
Also is there a way to run each test case independently to help with debugging? 
Thanks!

**Comment by BusyJay** [comment]
Well done! You can filter the test cases you want by append extra args to command `cargo test`. For more information, please see the output of command `cargo test --help`.

**Comment by seth-priya** [comment]
Thanks for the quick response!! Will try that

**Comment by seth-priya** [comment]
Quick update - after disabling the failing modules, I executed the complete set of tests on the forked branch (with changes to support ppc64le) on both x86 and ppc64le. There are 3 test failures in all. Analysis is as follows:
1- raftstore::test_split_region::test_server_split_region_diff_check
Fails on both ppc64le and x86. However passes when run individually - cargo test raftstore::test_split_region::test_server_split_region_diff_check
2 - raftstore::test_snap::test_server_snapshot
Fails on x86, passes on ppc64le
3. raftstore::test_multi::test_multi_server_random_restart
Random failure on x86, ppc64le. I have observed this to fail randomly on the current tikv master as well - on my local x86 setup.
All other tests passed. I will continue to debug the failures.

**Comment by BusyJay** [comment]
Tests can fail when too many cases running concurrently, because some tests depends on timeout which may exceed if the machine performs poorly. You can use `cargo test -- --test-threads=2` to limit the concurrent jobs. It will be helpful if you can provide some logs.

**Comment by seth-priya** [comment]
Thanks @BusyJay and sorry for the delay - I got back to this after being out for a couple of weeks. I was re-visiting the changes I have made, with the intention of raising a PR. 

One of the first things that will need to be sorted out is the dependency on grpc (via grpc-rs). I have started a new discussion for that here: 
https://github.com/pingcap/grpc-rs/issues/90

**Comment by seth-priya** [comment]
Thanks to pointers from @BusyJay latest grpc-rs works on ppc64le and so does kvproto (using grpc-rs from github). Only change required to kvproto for ppc64le would be update grpcio version, once it is released, to make it work on ppc64le. 

This covers all dependencies except jemallocator. Raised PR for that here:
https://github.com/BusyJay/jemallocator/pull/1

Now, for the tikv changes, I am planning to split the changes into two parts:
1 - Changes for updating dependencies other than mio 
2 - mio update changes.

I will create a fresh fork with the latest code and test the first set of changes on Intel to ensure that nothing breaks.

**Comment by siddontang** [comment]
Hi @seth-priya 

Can it work now?

**Comment by seth-priya** [comment]
Hi @siddontang - thanks for checking back, I am still trying to work through the last few (mostly test suite related) issues on ppc64le. Meanwhile, I have raised a PR for upgrading the mio version, that will be required and based on discussion above. I will try to get the hopefully last patch out soon.

**Comment by seth-priya** [comment]
Hi @siddontang , @BusyJay - this query is not related directly related to the issue here, but was (just out of curiosity) wondering if the release plan for tikv is published at some place (for example when are we expecting the first GA)? Once, we have the GA out, do we plan to publish the package @ crates.io for example? I was having a discussion with the nix community a few days back on gitter and they were also asking some of these questions. 

Looking at this - https://pingcap.github.io/blog/2017/05/27/rust-in-tikv/#timeline
we would be close?

Thanks!

**Comment by siddontang** [comment]
Hi @seth-priya 

We will release GA version soon, in this month. But we have no plan to publish to crates now because we think TiKV is a binary execution, not a library.

We have to do lots of work to guarantee stability and performance, which takes a long time and delays the GA release, sorry.

**Comment by seth-priya** [comment]
Thanks @siddontang for the details.

For this particular issue (ppc64le support), apart from the open PR, there is one last issue (jemalloc issue mentioned above) that I am now trying to resolve (had by-passed this call on ppc64le to try and move ahead). Everything, apart from this seems to be working 

  = note: /usr/bin/ld: /root/tikv/target/debug/deps/tikv_server-9c7aaf9d3bc56a45.tikv_server0.rust-cgu.o: undefined reference to symbol 'malloc_stats_print'
          //usr/lib/powerpc64le-linux-gnu/libjemalloc.so.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `tikv`.

**Comment by seth-priya** [comment]
So, there was issue linking to libjemalloc on ppc64le. This change in build.rs seems to work:
    #[cfg(target_arch = "powerpc64" && target_endian = "little")]
     println!(r"cargo:rustc-link-lib=jemalloc");
will do so more testing on latest code and add it to the PR. 

Thanks!

Priya

**Comment by BusyJay** [comment]
Hi, @seth-priya. Recently we remove the mio eventloop from raftstore completely so that TiKV will not depend on mio directly anymore. Would you like to check it out again to see whether it can compile on ppc64le?

**Comment by seth-priya** [comment]
Hi @BusyJay thanks a lot for letting me know - yes I will try it out and let you know

**Comment by seth-priya** [comment]
@BusyJay - quick update - this is looking quite good, so far - I just had to disable the sse flag for rocksdb to get it to build (no other changes were required) for "make build". For, "make test", set AFL_NO_X86=1, first 800+ tests passed before execution was terminated with following error 

test coprocessor::test_select::test_output_offsets ... ok
**E0123 09:06:46.438678648   31242 ev_posix.cc:227]            No event engine could be initialized from epollex
error: process didn't exit successfully: `/tikv/target/debug/deps/integrations-79c58c087a6b4954 --nocapture` (signal: 6, SIGABRT: process abort signal)
Makefile:95: recipe for target 'test' failed
make: *** [test] Error 101**

**Comment by BusyJay** [comment]
We enable epollex engine for grpc in tests. It seems that your linux version is outdated, which doesn't contain the required features of epollex engine. @overvenus Do you have any workaround?

If you want to hack around, you can remove 
https://github.com/tikv/tikv/blob/0f3f02af0a6d32523304381a44b3bfe257acd5b7/components/test_util/src/lib.rs#L48-L49
to get around this problem temporary.

**Comment by seth-priya** [comment]
@BusyJay, thank you for the inputs.

FYI, system info
root@7c71d347018c:/tikv# uname -a
Linux 7c71d347018c 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 16:44:15 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux

and yes, as per https://grpc.io/grpc/core/md_doc_core_grpc-polling-engines.html
•Linux:◦**epollex** (default but requires kernel version >= 4.5),

so, I guess that explains.

- I confirmed that there are no further issues observed after commenting out the above lines. All the tests passed!

Thanks for your support!!
