### ISSUE TITLE
100 million rows to add the column and set the default value is also faster. What is this principle?

### ISSUE THREAD

**Issue by aiaix** [tikv/tikv#2338]
100 million rows to add the column and set the default value is also faster. What is this principle?
TIDB PRE-GA

mysql> alter table sbtest1 add pad1 char(5) default '1'; 
Query OK, 0 rows affected (1.02 sec)

**Comment by zhangjinpeng1987** [comment]
@aiaix Add a column just need modify the table's schema and define when missing this column in row use default value instead, consequently it is fast.

**Comment by aiaix** [comment]
@zhangjinpeng1987   翻译

But when I look at the data, the column of historical data also have value, and how this value is coming. If the historical data has changed, it will not be so quick

**Comment by zhangjinpeng1987** [comment]
@aiaix `the column of historical data also have value`, how do you observed the historical data? by SQL?

**Comment by aiaix** [comment]
@zhangjinpeng1987  YES

**Comment by zhangjinpeng1987** [comment]
@aiaix What does `historical` mean? Rows inserted before column added?

**Comment by aiaix** [comment]
@zhangjinpeng1987  



Table sbtest1 has 100 million data

mysql> desc sbtest1;
+-------+------------------+------+------+---------+----------------+
| Field | Type             | Null | Key  | Default | Extra          |
+-------+------------------+------+------+---------+----------------+
| id    | int(11) UNSIGNED | NO   | PRI  | NULL    | auto_increment |
| k     | int(11) UNSIGNED | NO   |      | 0       |                |
| pad   | char(5)          | YES  |      | 0       |                |
| pad1  | char(5)          | YES  |      | 1       |                |
+-------+------------------+------+------+---------+----------------+
4 rows in set (0.01 sec)

mysql> alter table sbtest1 add pad3 char(1) default 'a';
Query OK, 0 rows affected (1.05 sec)

mysql> select id ,pad3 from sbtest1 order by id limit 5;
+----+------+
| id | pad3 |
+----+------+
|  1 | a    |
|  2 | a    |
|  3 | a    |
|  4 | a    |
|  5 | a    |
+----+------+
5 rows in set (0.03 sec)

mysql> select id ,pad3 from sbtest1 order by id desc limit 5;
+------------+------+
| id         | pad3 |
+------------+------+
| 1000000001 | a    |
|  100000000 | a    |
|   99999999 | a    |
|   99999998 | a    |
|   99999997 | a    |
+------------+------+
5 rows in set (0.02 sec)

**Comment by zhangjinpeng1987** [comment]
@aiaix default value `a` is only in schema, not in every existing rows, the speed is rational.

**Comment by aiaix** [comment]
The value a exists on each line and can be viewed.
You can compare the following example

mysql> alter table sbtest1 add pad4 char(5);
Query OK, 0 rows affected (1.02 sec)

mysql> alter table sbtest1 alter column pad4 set default 'b'; 
Query OK, 0 rows affected (1.02 sec)

mysql> select id ,pad3,pad4 from sbtest1 order by id desc limit 5;
+------------+------+------+
| id         | pad3 | pad4 |
+------------+------+------+
| 1000000001 | a    | NULL |
|  100000000 | a    | NULL |
|   99999999 | a    | NULL |
|   99999998 | a    | NULL |
|   99999997 | a    | NULL |
+------------+------+------+
5 rows in set (0.03 sec)

mysql> select id ,pad3,pad4 from sbtest1 order by id  limit 5;
+----+------+------+
| id | pad3 | pad4 |
+----+------+------+
|  1 | a    | NULL |
|  2 | a    | NULL |
|  3 | a    | NULL |
|  4 | a    | NULL |
|  5 | a    | NULL |
+----+------+------+
5 rows in set (0.01 sec)

**Comment by zhangjinpeng1987** [comment]
@aiaix Can be viewed not means this value must be existed in each row, it is default value, so we can only store it in schema. When you retrieve this row and TiDB will find there is no such column in row, at the same time there is a record in schema says default value of this column is `a`, so TiDB set `a` for this column.

**Comment by Hoverbear** [comment]
Seems this question is answered. :) Closing.
