### ISSUE TITLE
tikv stop leads to inconsistent state

### ISSUE THREAD

**Issue by bradrhod** [tikv/tikv#2344]
built binaries, 2 days ago installed on ubuntu 16.04 VM.  Building a cluster 3x 2 proc pd nodes 5x 8- proc data nodes on google cloud. Data nodes initially had 25Tb of hard drive.  

I want to shrink to 15 Tb.  This is non-production, so don't care about the data. 

So I downed the tikv-server process on the first data node.  Deleted the /data directory (where the storage was mounted).   By downing the tikv-server process, I mean I did kill <pid> on that process.

Now I am trying to bring up that tikv-server back online.  
`./bin/tikv-server --pd="10.1.0.30:2379,10.1.0.31:2379,10.1.0.32:2379" --addr="10.1.0.20:20160"  --store=tikv1 --log-file=tikv-server.log --data-dir="/data"`
When I try to start it first error is that --data-dir is used twice.  It is not. Looking into things it seems that data-dir is getting sent down from Placement Driver (PD).  So trying to start without giving --data-dir and you get 
`2017/09/26 18:54:00.763 util.rs:308: [ERROR] fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:3236 address:\"10.1.0.20:20160\" , already registered by id:4 address:\"10.1.0.20:20160\" state:Offline ") }))`

running pd-ctl 
store shows that server 4 matches this servers ip.  So I try `store delete 4`.  That works. But the store state remains state=1 state_name="Offline".  I have waited hours, no change.  The database only has 1 table with 1 row, so no data in that server yet.

How do I force the removal of store 4, so i can bring this tikv-server back online?

**Comment by siddontang** [comment]
Hi @bradrhod 

What does the  `store` command show with `pd-ctl`?

**Comment by bradrhod** [comment]
Sorry, I do not have the server in that state anymore. 

It was showing store 4 was Offline.  But never removed store 4 from the stores.  Waited 24 hours. 

Is there a way to say to really delete store 4, so can reuse that IP address?

**Comment by siddontang** [comment]
If the store 4 shows Tombstone in the `pd-ctl` `store` command , the store is removed completely, and then you can reuse the IP again. 

Can we show me the result of `store`?

**Comment by Hoverbear** [comment]
Hi! This issue is stale, I'm closing it. Please reopen it if it's still an issue for you.
