### ISSUE TITLE
raftstore: remove mio

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#2516]
For https://github.com/pingcap/tikv/pull/2364 

It is hard for us to maintain mio 0.5 now, but mio 0.6 channel performance is not good. So we dicide to remove mio and use thread + channel to refactor raftstore directly. I think we should have following things to do:

- [x] implement a simple timer or use an existing library. 
- [x] let worker return channel full error, see #2514  
- [x] introduce the on_tick mechanism for the worker, see #2515 

/cc @BusyJay @seth-priya @overvenus

**Comment by seth-priya** [comment]
Hi @siddontang, thanks for copying me on the issues.

Based on what I see above, there seems to be an interdependency between the various sub-tasks that have been defined here. To, that end I was trying to understand the plan from an implementation and execution perspective. 

For example, is there any particular sequence in which these need to be implemented/taken forward and if so, are there defined timelines as such? I see that 2514 and 2515 are assigned, so would @BusyJay and @overvenus be actively working on these? 

Apologies for asking so many questions, just wanted to be sure I understand! 

Thank you,
Priya

**Comment by siddontang** [comment]
Thanks @seth-priya 

2514 and 2515 are not only for raftstore refactor, but also for scheduler and other thread workers. So I separate them and assign to our colleagues at first. But we have not been working on these, only want to finish them at this week, It is very appreciated that you can help us to support these.

**Comment by seth-priya** [comment]
Thanks for the response @siddontang 

So, I have been looking at this for a couple of weeks now, but I am not yet confident that I will be able to take this through to completion without some support from your side. The main reason being that the proposed changes (especially scheduler and timer) seem to touch upon some of the core tikv functionality and I don't want to jump into it without a complete understanding of the architecture, functionality and implementation of tikv + mio. 

I think I would need someone who has a good understanding of the code base to review any code that I might write (or code changes that I might make) and provide ongoing and continuous feedback as I move along, if I have to take this forward. 

Please advise. 

Thanks again for your continued support with this.
Priya

**Comment by siddontang** [comment]
Hi @seth-priya 

@hicqu has now been working to refactor the worker to support #2515  and #2514. After these finished, I think the left important thing is to support a timer based on the worker.

The worker will call the on_tick periodically, so we can check the timer in the on_tick function, maybe you can try to help us add a timer implementation at first :-)

**Comment by seth-priya** [comment]
ok, thanks!

**Comment by siddontang** [comment]
@seth-priya 

We have already refactored the worker mechanism and I think we can go on now. Can you help us remove mio now? 

@hicqu please give an example on how to use worker + timer.

**Comment by seth-priya** [comment]
@siddontang - thanks, yes I can take this forward now.

@hicqu an example would certainly help, thank you!

**Comment by hicqu** [comment]
Here is a simple example to use `Timer` with `Worker`:
```rust
use util::worker::{Runnable, RunnableWithTimer, Worker};
use util::timer::Timer;

#[derive(Debug)]
enum Tick {
    Raft,
    RaftLogGc,
}

#[derive(Debug)]
enum Msg {
    RaftCmd,
    RaftMessage,
}

struct RaftStoreRunner {
    periodic_tasks: HashMap<Tick, Duration>,
}

impl Runnable<Msg> for RaftStoreRunner {
    fn run(&mut self, t: Msg) {
        println!("got Msg: {:?}", t);
    }
}
impl RunnableWithTimer<Msg, Tick> for RaftStoreRunner {
    fn on_timeout(&mut self, timer: &mut Timer<Tick>, tick: Tick) {
        println!("got timeout: {:?}", tick);
        let timeout = self.periodic_tasks
            .get(&tick)
            .unwrap_or(Duration::from_millis(200));
        timer.add_task(timeout, tick);
    }
}

fn main() {
    let mut runner = RaftStoreRunner {
        periodic_tasks: HashMap::new(),
    };
    runner
        .periodic_tasks
        .insert(Tick::RaftCmd, Duration::from_millis(100));

    let mut timer: Timer<Tick> = Timer::new(16);
    timer.add_task(Duration::from_millis(100), Tick::RaftCmd);
    timer.add_task(Duration::from_millis(300), Tick::RaftMessage);

    let worker = Worker::new("raftstore");
    worker.start_with_timer(runner, timer).unwrap();
}
```

**Comment by hicqu** [comment]
Any progress? @seth-priya ?

**Comment by seth-priya** [comment]
@hicqu - Sorry for the delayed response -  I was caught up with something else. I have started on this and will share a more detailed update in a couple of days

**Comment by seth-priya** [comment]
Hi @hicqu , @siddontang , just wanted to let you know that I have still not been able to make any real progress on this as I have been caught up with a bunch of high priority urgent requests :( I will try to get to this as soon as I can ...

**Comment by sch00lb0y** [comment]
@siddontang @breeswish 
Anyone working on this?
If not, I'm willing to work on this.

**Comment by siddontang** [comment]
Thanks, @sch00lb0y 

Sorry that now we have been refactoring raftstore which will remove mio at the same time. But you can help us do other things :-)

@Hoverbear I think we should publish the doc "What can the community do" to others join us easily now.

**Comment by Hoverbear** [comment]
@siddontang I'll close this issue, then.

I agree, we should release it. :) Do you want me to make a PR to the blog?
