### ISSUE TITLE
coprocessor: add metric to distinguish point get and scan

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#2517]

**Comment by BusyJay** [comment]
If you just want to distinguish point get and scan, then there is already a [metric](https://github.com/pingcap/tikv/blob/master/src/coprocessor/metrics.rs#L85).

**Comment by siddontang** [comment]
Got it, so here we should add this metric to Grafana.

**Comment by breeswish** [comment]
In 4.0 most of point gets will use KvGet / KvBatchGet interface and there is less demands to have this feature.
