### ISSUE TITLE
TiKV Error Log

### ISSUE THREAD

**Issue by adiu** [tikv/tikv#2678]
2018/01/12 11:57:16.807 panic_hook.rs:99: [ERROR] thread 'raftstore-4' panicked '[region 1001] 1003 unexpected raft log index: last_index 250061 < applied_index 250069' at "src/raftstore/store/peer_storage.rs:484"
stack backtrace:
   0:     0x7f9182d3a97e - backtrace::backtrace::libunwind::trace
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace<closure>
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x7f9182d3b103 - backtrace::capture::{{impl}}::new
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/target/release/build/backtrace-9ec19ed81b12399b/out/capture.rs:79
   2:     0x7f91825ff305 - tikv::util::panic_hook::set_exit_hook::{{closure}}
                        at src/util/panic_hook.rs:98
   3:     0x7f9182e03c86 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:611
   4:     0x7f9182e03b14 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:571
   5:     0x7f9182e03a19 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:521
   6:     0x7f91826760a5 - tikv::raftstore::store::peer_storage::{{impl}}::new
                        at src/raftstore/store/peer_storage.rs:484
   7:     0x7f91823c4b79 - tikv::raftstore::store::peer::{{impl}}::new<tikv::server::transport::ServerTransport<tikv::server::transport::ServerRaftStoreRouter, tikv::server::resolve::PdStoreAddrResolver>,tikv::pd::client::RpcClient>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/raftstore/store/peer.rs:309
   8:     0x7f91823c881c - tikv::raftstore::store::peer::{{impl}}::create<tikv::server::transport::ServerTransport<tikv::server::transport::ServerRaftStoreRouter, tikv::server::resolve::PdStoreAddrResolver>,tikv::pd::client::RpcClient>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/raftstore/store/peer.rs:282
   9:     0x7f91823f4347 - tikv::raftstore::store::store::{{impl}}::init::{{closure}}<tikv::server::transport::ServerTransport<tikv::server::transport::ServerRaftStoreRouter, tikv::server::resolve::PdStoreAddrResolver>,tikv::pd::client::RpcClient>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:293
                         - tikv::raftstore::store::engine::scan_impl<closure>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/raftstore/store/engine.rs:310
                         - tikv::raftstore::store::engine::Iterable::scan_cf<rocksdb::rocksdb::DB,closure>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/raftstore/store/engine.rs:286
                         - tikv::raftstore::store::store::{{impl}}::init<tikv::server::transport::ServerTransport<tikv::server::transport::ServerRaftStoreRouter, tikv::server::resolve::PdStoreAddrResolver>,tikv::pd::client::RpcClient>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:254
                         - tikv::raftstore::store::store::{{impl}}::new<tikv::server::transport::ServerTransport<tikv::server::transport::ServerRaftStoreRouter, tikv::server::resolve::PdStoreAddrResolver>,tikv::pd::client::RpcClient>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/raftstore/store/store.rs:234
  10:     0x7f918231e062 - tikv::server::node::{{impl}}::start_store::{{closure}}<tikv::pd::client::RpcClient,tikv::server::transport::ServerTransport<tikv::server::transport::ServerRaftStoreRouter, tikv::server::resolve::PdStoreAddrResolver>>
                        at /home/jenkins/workspace/build_unportable_tikv_1.0/go/src/github.com/pingcap/tikv/src/server/node.rs:342
                         - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  11:     0x7f918231f13d - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:364
                         - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
                         - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:479
  12:     0x7f9182e0ad9c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  13:     0x7f91823cb135 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libstd/panicking.rs:458
                         - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:361
                         - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:363
                         - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /checkout/src/liballoc/boxed.rs:682
  14:     0x7f9182e0286b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
  15:     0x7f9181860df2 - start_thread
  16:     0x7f91813782cc - clone
  17:                0x0 - <unknown>

**Comment by BusyJay** [comment]
Has there been any power failures or disk corruptions?

**Comment by Hoverbear** [comment]
Stale, closing. Please reopen if you have more issues.
