### ISSUE TITLE
Use smallvec to optimize memory allocation

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#2679]
There are many small allocations in our codebase. For example, a table key's length is 27 generally. I think keys whose length is less than 32 can be stored on stack. This can save at lease one allocation when read/write kv. For better performance, we may need to support it in protobuf crate too.

**Comment by breeswish** [comment]
In MVCC, we have an internal task to track zero copy, which is WIP.

In coprocessor, the new execution framework heavily utilize smallvec.

I think we can close this issue now.
