### ISSUE TITLE
metric: support gRPC Pull mechanism for Prometheus

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#2761]
Now we use Push mechanism, which is not recommended by Prometheus, but unfortunately, TiKV can only support gRPC but not HTTP so Prometheus can't pull the metric from TiKV directly. To solve this, we need a proxy like:
```
              HTTP           gRPC
Prometheus -----------Proxy ------ TiKV
```

For TiKV, we need to define a gRPC like `dump_metrics(content_type string) -> Vec<u8>`,  content_type is text or protocol buffer. Btw, in `tikv-ctl`, we can use text format to dump the metric too. 

For Proxy, we may use https://github.com/grpc-ecosystem/grpc-gateway or others, but here we don't want to deploy one Proxy for one TiKV, but one Proxy for many or all TiKVs, so maybe we will write one. But at first, we can use gateway.

**Comment by overvenus** [comment]
The `gRPC` part in TiKV is done. #2780

**Comment by overvenus** [comment]
Closed, as it has been resolved in https://github.com/pingcap/tidb-inspect-tools/pull/41.

**Comment by breeswish** [comment]
I have a question.. Why did we use a proxy to do this task? Honestly the proxy is acting exactly like the original push gateway and share common pitfalls. Replacing push gateway with our own proxy is just deceiving ourselves.

The [Prometheus documentation](https://prometheus.io/docs/practices/pushing/) listed several pitfalls when abusing Pushgateway as we previous do:

> - When monitoring multiple instances through a single Pushgateway, the Pushgateway becomes both a single point of failure and a potential bottleneck.
> - You lose Prometheus's automatic instance health monitoring via the up metric (generated on every scrape).
> - The Pushgateway never forgets series pushed to it and will expose them to Prometheus forever unless those series are manually deleted via the Pushgateway's API.

The pitfall point 1 and 2 still exists if we use a proxy.

**Comment by overvenus** [comment]
It depends how you deploy proxy and tikv. Eg, one proxy one tikv, then you overcome pitfall 1 and 2.

**Comment by breeswish** [comment]
@overvenus It's much like 1 kv 1 pushgateway? 🤣
