### ISSUE TITLE
try to use MaskedVByte to speed up varint decoding

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#2763]
Refer http://maskedvbyte.org/

We should do the benchmark and see whether it can work well for us or not.

**Comment by codeworm96** [comment]
Hi. Since Rust recently started to provide SIMD in the nightly std, I am interested in working on a branch of that. May I have a try?

**Comment by breeswish** [comment]
@codeworm96 Of course! In addition we can consider using foreign libraries if exists.

**Comment by breeswish** [comment]
Looks like this algorithm is mainly for decoding multiple varints at once according to the paper. However in TiKV the scenario is different, we mostly only want to decode 1 varint. Closing.
