### ISSUE TITLE
inject failures for read pool

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#2797]
Previously proposed in https://github.com/pingcap/tikv/pull/2713

It would be nice to use failure injection to cover some error conditions (like snapshot failed).

**Comment by siddontang** [comment]
@brson 

maybe we need to add a doc about how to use `fail-rs` to let contributors use `fail`.

**Comment by breeswish** [comment]
Closed in https://github.com/tikv/tikv/pull/4376
