### ISSUE TITLE
Update to futures 0.2

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#2845]
[futures-rs](https://github.com/rust-lang-nursery/futures-rs) is ~~reaching~~ 0.2. There are some API changes though. We need to adapt our code base to the latest version once futures-rs 0.2 is stable.

**Comment by breeswish** [comment]
Note: relative crates should also be updates, i.e. futures-cpupool.

**Comment by breeswish** [comment]
As part of the task "dependency upgrade", if you would like to work on this, please add yourself to the assignee :) @Hoverbear  You may also need to update the grpc because it uses futures as well.

**Comment by overvenus** [comment]
It looks like 0.1 and 0.2 are incompatible, we needs to update futures for grpc-rs first.

**Comment by brson** [comment]
Yes, futures 0.2 has been yanked and is a dead end. Closing this. We need to wait for the ecosystem to sort out the future of futures. Closing.
