### ISSUE TITLE
balancer not works.

### ISSUE THREAD

**Issue by Martwu** [tikv/tikv#2856]
Please answer these questions before submitting your issue. Thanks!

```
What version of Rust are you using (rustc --version)?
1.21.0-nightly (215e0b10e 2017-08-08)
```
on `./tikv-server --version`

What operating system and processor architecture are you using?
```
uname -a
Linux X 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

3. What did you do?
I would like to delele a tikv then add the other one. 

4. What did you expect to see?

Status of deleted one become "offline" then "tombstone",  and region number of that increases no longer.  Region number of new one increases.

5. What did you see instead?

region number of deleted one keep increasing.  that of new one keep 0.

**Comment by Martwu** [comment]
relate to this issue [https://github.com/pingcap/tikv/issues/2840](https://github.com/pingcap/tikv/issues/2840)

**Comment by siddontang** [comment]
PTAL @nolouch

**Comment by nolouch** [comment]
@Martwu  could you please provide more detail information about cluster status. you can get stores information via `pd-ctl`, and some [metrics](https://github.com/pingcap/docs/blob/master/op-guide/dashboard-overview-info.md) via the monitor.

**Comment by Martwu** [comment]
@nolouch I am sorry, I have been destroy that environment. And I deploy a cluster by ansible. That works.
