### ISSUE TITLE
some un-pushed builtin UDFs 

### ISSUE THREAD

**Issue by zz-jason** [tikv/tikv#2918]
All the builtin UDFs supported by TiDB are: 
https://github.com/pingcap/tidb/blob/master/expression/builtin.go#L292

All the builtin UDFs can be pushed down to TiKV are: 
https://github.com/pingcap/tidb/blob/master/expression/expr_to_pb.go#L265

Following is part of UDFs which are still not being pushed to TiKV:

## cast functions
- [x] ast.Cast

## logic functions
- [x] ast.LogicXor

## arithmetical functions.
- [ ] ast.UnaryMinus
- [ ] ast.Mod
- [ ] ast.IntDiv

## bitwise functions
- [ ] ast.BitLength
- [ ] ast.BitNeg
- [ ] ast.BitCount
- [ ] ast.LeftShift
- [ ] ast.RightShift
- [x] ast.And
- [x] ast.Or
- [x] ast.Xor

## compare functions
- [ ] ast.IsTruth
- [ ] ast.IsFalsity
- [ ] ast.Regexp
- [ ] ast.Greatest
- [ ] ast.Least
- [ ] ast.Interval

## math functions
- [x] ast.Abs
- [ ] ast.Acos
- [ ] ast.Asin
- [ ] ast.Atan
- [ ] ast.Atan2
- [ ] ast.Ceil
- [ ] ast.Ceiling
- [ ] ast.Conv
- [ ] ast.Cos
- [ ] ast.Cot
- [ ] ast.CRC32
- [ ] ast.Degrees
- [ ] ast.Exp
- [ ] ast.Floor
- [ ] ast.Ln
- [ ] ast.Log
- [ ] ast.Log2
- [ ] ast.Log10
- [ ] ast.PI
- [ ] ast.Pow
- [ ] ast.Power
- [ ] ast.Radians
- [ ] ast.Rand
- [ ] ast.Round
- [ ] ast.Sign
- [ ] ast.Sin
- [ ] ast.Sqrt
- [ ] ast.Tan
- [ ] ast.Truncate

## time functions
- [ ] ast.AddDate
- [ ] ast.DateAdd
- [ ] ast.SubDate
- [ ] ast.DateSub
- [ ] ast.AddTime
- [ ] ast.ConvertTz
- [ ] ast.Curdate
- [ ] ast.CurrentDate
- [ ] ast.CurrentTime
- [ ] ast.CurrentTimestamp
- [ ] ast.Curtime
- [ ] ast.Date
- [ ] ast.DateLiteral
- [ ] ast.DateDiff
- [ ] ast.Day
- [ ] ast.DayName
- [ ] ast.DayOfMonth
- [ ] ast.DayOfWeek
- [ ] ast.DayOfYear
- [ ] ast.Extract
- [ ] ast.FromDays
- [ ] ast.FromUnixTime
- [ ] ast.GetFormat
- [ ] ast.Hour
- [ ] ast.LocalTime
- [ ] ast.LocalTimestamp
- [ ] ast.MakeDate
- [ ] ast.MakeTime
- [ ] ast.MicroSecond
- [ ] ast.Minute
- [ ] ast.Month
- [ ] ast.MonthName
- [ ] ast.Now
- [ ] ast.PeriodAdd
- [ ] ast.PeriodDiff
- [ ] ast.Quarter
- [ ] ast.SecToTime
- [ ] ast.Second
- [ ] ast.StrToDate
- [ ] ast.SubTime
- [ ] ast.Sysdate
- [ ] ast.Time
- [ ] ast.TimeLiteral
- [ ] ast.TimeFormat
- [ ] ast.TimeToSec
- [ ] ast.TimeDiff
- [ ] ast.Timestamp
- [ ] ast.TimestampLiteral
- [ ] ast.TimestampAdd
- [ ] ast.TimestampDiff
- [ ] ast.ToDays
- [ ] ast.ToSeconds
- [ ] ast.UnixTimestamp
- [ ] ast.UTCDate
- [ ] ast.UTCTime
- [ ] ast.UTCTimestamp
- [ ] ast.Week
- [ ] ast.Weekday
- [ ] ast.WeekOfYear
- [ ] ast.Year
- [ ] ast.YearWeek
- [ ] ast.LastDay

## string functions
- [ ] ast.ASCII
- [ ] ast.Bin
- [ ] ast.Concat
- [ ] ast.ConcatWS
- [ ] ast.Convert
- [ ] ast.Elt
- [ ] ast.ExportSet
- [ ] ast.Field
- [ ] ast.Format
- [ ] ast.FromBase64
- [ ] ast.InsertFunc
- [ ] ast.Instr
- [ ] ast.Lcase
- [ ] ast.Left
- [ ] ast.Right
- [ ] ast.Length
- [ ] ast.LoadFile
- [ ] ast.Locate
- [ ] ast.Lower
- [ ] ast.Lpad
- [ ] ast.LTrim
- [ ] ast.Mid
- [ ] ast.MakeSet
- [ ] ast.Oct
- [ ] ast.Ord
- [ ] ast.Position
- [ ] ast.Quote
- [ ] ast.Repeat
- [ ] ast.Replace
- [ ] ast.Reverse
- [ ] ast.RTrim
- [ ] ast.Space
- [ ] ast.Strcmp
- [ ] ast.Substring
- [ ] ast.Substr
- [ ] ast.SubstringIndex
- [ ] ast.ToBase64
- [ ] ast.Trim
- [ ] ast.Upper
- [ ] ast.Ucase
- [ ] ast.Hex
- [ ] ast.Unhex
- [ ] ast.Rpad
- [ ] ast.CharFunc
- [ ] ast.CharLength
- [ ] ast.CharacterLength
- [ ] ast.FindInSet

**Comment by breeswish** [comment]
Close for #5751
