### ISSUE TITLE
Bind port only right before server start

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#2999]
Currently the listen port is bind long before start, so that checking TiKV running according to port is not reliable. We need to bind the port right before the server starts.

**Comment by Hoverbear** [comment]
:+1: Great catch.

**Comment by codeworm96** [comment]
I would like to have a try. Could you provide more information?

I think it happens ![here](https://github.com/pingcap/tikv/blob/master/src/server/server.rs#L171).

**Comment by breeswish** [comment]
@codeworm96 You can add some sleep between server.start() and server::new(), and you will find that, before start is called, the port is already binded. This is because we currently bind port first, then initialize some rest component, and finally `server.start()`.

**Comment by breeswish** [comment]
@codeworm96 Notice that, the reason that we bind port before initialization is to support binding at port 0 (and other services rely on the actual port), which is useful in CI to avoid port conflict.

**Comment by codeworm96** [comment]
I see. I tested grpc-rs. The binding happens [here](https://github.com/pingcap/tikv/blob/956e7e96061fc82ba94108843185fd806861cf4d/src/server/server.rs#L120), long before start.
