### ISSUE TITLE
Implement logfile rotation by size

### ISSUE THREAD

**Issue by Hoverbear** [tikv/tikv#3035]
After #3010 is merged we'll be doing our logging on another thread and using `slog` instead of `log`. This is excellent, and `slog` almost fulfills our needs, except there is no file rotation.

This feature is desirable because it lets us prevent log files becoming huge. This has been a problem previously in high load deployments.

We should alter the rotating file logger in `src/util/file_log.rs` to rotate based on file size.

We can get the size of a file via [`std::fs::Metadata`](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.len).

**Comment by vbmade2000** [comment]
Are you planning to use logrotate utility (For Linux only) or any other mechanism ?

**Comment by andylokandy** [comment]
@vbmade2000 This is already implemented 😆 https://github.com/tikv/tikv/pull/6148
