### ISSUE TITLE
Use protobuf enums to replace coprocessor constants like REQ_TYPE_DAG

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3038]
Due to historical reasons, we are using standalone constants like REQ_TYPE_DAG, REQ_TYPE_ANALYZE and REQ_TYPE_CHECKSUM. This can be replaced by embedding enums in the protobuf file. This change can help simplify our code and make TiKV & TiDB source more consistent.

Note:

1. To complete this task, you need to update TiDB as well.
2. Because this is a breaking change, we may not merge the PR immediately. Instead it may be deferred to our 3.0 release.

**Comment by BusyJay** [comment]
I don't think it's a good idea. This doesn't provide enough benefits while breaks a lot of things.

**Comment by Hoverbear** [comment]
Let's discuss if this is a good action before asking folks to tackle it. :)

**Comment by breeswish** [comment]
There looks to be no notable advantages, other than prettier code. Close.
