### ISSUE TITLE
Utilize `oneof` in the protobuf

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3039]
Due to historical reasons, we are implementing our own `oneof` in coprocessor. For example, the `coprocessor::Request` protobuf message contains a `data: Vec<u8>`, which is the serialized message data for different kind of requests.

By using `oneof`, we can avoid deserialize two times (1 for message in `Request` and 1 for message in `Request.data`), which can eliminate memory copies and make code simpler.

Note:

- To complete this task, you need to update TiDB as well.
- Because this is a breaking change, we may not merge the PR immediately. Instead it may be deferred to our 3.0 release.

**Comment by BusyJay** [comment]
/cc @coocood PTAL 

> ... two times ...

Actually it's either deserialized by the library or by ourself.

**Comment by breeswish** [comment]
@BusyJay Yes, I mean, there is extra byte copies.

**Comment by breeswish** [comment]
Considering our protocol changing a schema cost too much, while advantage is only cleaner code base. Close it for now.
