### ISSUE TITLE
Use `cargo clippy` instead of the clippy plugin

### ISSUE THREAD

**Issue by oli-obk** [tikv/tikv#3090]
We're planning on removing the clippy plugin interface, because rustc will remove it someday anyway. All that is required on your end is to remove the clippy feature and replace all cfgs that depend on it with the `cargo-clippy` feature which is automatically enabled by cargo clippy.

So you can then use `cargo clippy` instead of `cargo build --features=clippy`. Note that cargo clippy requires a `cargo install clippy` first.

**Comment by siddontang** [comment]
Thanks @oli-obk 

PTAL @Hoverbear

**Comment by Hoverbear** [comment]
Thanks for telling us @oli-obk ! We'll migrate. :) Assigning myself to keep track of this but if someone else wants to tackle it I'm happy to give it up or help out.

**Comment by oli-obk** [comment]
If you want a "seamless" transition, you can use `RUSTC_WRAPPER=clippy-driver CLIPPY_TESTS=true cargo $somecommand`, which will basically replace your `rustc` with a `rustc` that has clippy built into it.

We're working on improving the experience around that.
