### ISSUE TITLE
Reduce dependency version conflicts

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3146]
In [Cargo.lock](https://github.com/pingcap/tikv/blob/master/Cargo.lock) we can see many dependencies have multiple versions, for example, bitflags has occurred 4 times and lazy_static has occurred 3 times. Mostly, we can resolve this by updating some dependencies.

**Comment by niedhui** [comment]
Hi, I want to pick this issue.  Seems the first thing need to do is to upgrade `mio` to 0.6( bitflags depends on nix, nix depends on mio). and I found there is a  closed issue #1050 (upgrade to mio 0.6). is it OK if I upgrade the mio?

**Comment by breeswish** [comment]
@BusyJay Are there any known issues of upgrading mio?

**Comment by BusyJay** [comment]
mio will be removed when threaded raftstore is landed. Let's hold it until then.

**Comment by breeswish** [comment]
@BusyJay Sure! @niedhui May be you can take a look at other dependencies? As I remembered, a lot of other dependencies are duplicated as well.

**Comment by niedhui** [comment]
got it.
