### ISSUE TITLE
Utilize the new GitHub issue template

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3151]
For now, when creating issues, we can see a predefined template, which is designed for reporting bugs. However the community (and we) may raise other kind of issues, for example, enhancement ideas and questions. We can utilize the latest GitHub multi issue template feature to handle these different type of initial templates to be more friendly.

See: https://help.github.com/articles/about-issue-and-pull-request-templates/

**Comment by Hoverbear** [comment]
:+1: I think this is a really great idea.
