### ISSUE TITLE
Use tarpaulin binary in CI instead of compile a new one

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3250]
First, the compatible rustc version for compiling tarpaulin might not exactly the same as our projects, so we cannot freely choice a tarpaulin version currently. Second, it takes us several minutes to install the tarpaulin in CI. If we use a binary version as tarpaulin's CI did, these issues can be eased.

**Comment by siddontang** [comment]
do we still have this problem? @breeswish

**Comment by Hoverbear** [comment]
I think it's worth a try. :)

**Comment by breeswish** [comment]
Use our own Jenkins CI now.
