### ISSUE TITLE
Some Prevote tests cannot pass reliably.

### ISSUE THREAD

**Issue by Hoverbear** [tikv/tikv#3385]
In #3386 we determined that some prevote tests cannot pass reliably.

This is because we attach a `MessageTypeNotifier` which listens for a specific message type to be send in some duration.

The way we use it is by creating a failure, such as a partition, then recovering it and immediately attaching the notifiers.

Some notes:

* Attaching the notifiers before clearing the partitioning means we accidentally clear the notifiers as well.
* Since the notifiers are attached after the partition is removed it's entirely possible that the prevote messages will be sent before we can go an attach the notifier.
* It was manually verified even in failing test cases that a prevote was sent as appropriate.

In #3386 we disabled these unreliable tests, enabling them will require some thought around how to catch these messages.

**Comment by 5kbpers** [comment]
Close this issue since we opened some other issues for specified tests.
