### ISSUE TITLE
Make DEFAULT_REQUEST_MAX_HANDLE_SECS configurable

### ISSUE THREAD

**Issue by birdstorm** [tikv/tikv#3423]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now DEFAULT_REQUEST_MAX_HANDLE_SECS is set as a constant 60 seconds, i.e., a coprocessor request waiting longer than 60s will be cancelled to reduce chances of stacking requests on TiKV server, and an otherError 'request outdated' will be thrown. However, for some OLAP queries, coprocessor requests might take longer than expected, and a queueing request should be considered normal rather than simply cancelled. While TiKV will not know the scenario the request is working in, users should be able to give a hint of the desired request outdated timeout.

**Describe the feature you'd like:**

Let user able to configure DEFAULT_REQUEST_MAX_HANDLE_SECS.

**Describe alternatives you've considered:**

add DEFAULT_REQUEST_MAX_HANDLE_SECS into config.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Hoverbear** [comment]
Hi @birdstorm! I think this is a valid request. Thanks!

I'm going to flag it up for help wanted and invite contributors to work on this.  :)

To anyone wanting to work on this, please let us know, and feel free to ping me for help!

**Comment by birdstorm** [comment]
Seems it has already been configurable via `server.end-point-request-max-handle-duration`.
