### ISSUE TITLE
Choose different split policy according to the region size and desire size

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#3431]
When write load is high, it's very easy that split check scan can't catch up with the data written. This can lead to a very large region.

#1243 can ease the problem. However scan a large region can also consume a lot of time and CPU. Tests show that large region can still easily show up even with batch split implemented, although split is speeded up.

When a region becomes large, it's more practical to divide it into smaller chunk quickly. This can be achieved via size estimate, which can be calculated from SST properties. Although it may not be accurate enough, it's OK for a large region:
1. Split needs to be fast for large region;
2. Because the region is large enough, use a larger size limit usually won't lead to small trunks;
3. If the split region is still large, we can use split scan to split into regions with more accurate sizes.

Besides, a large region is usually more emergent to be split. So we can change the split check queue from a naive FIFO queue to a priority queue so that large region can be split early and quickly.

**Comment by siddontang** [comment]
I think first we can

1. Merge the batch split PR
2. use batch split + approximate split key to relieve the problem.
3. Others.

/cc @Connor1996

**Comment by Connor1996** [comment]
got it

**Comment by BusyJay** [comment]
Can this be closed, @Connor1996 ? If it can, please links to the PRs that resolve the issue.

**Comment by Connor1996** [comment]
Fix by https://github.com/tikv/tikv/pull/3511
