### ISSUE TITLE
which API should I use ?

### ISSUE THREAD

**Issue by carr123** [tikv/tikv#3440]
there are two types of tikv client api, Raw KV api and transactional kv api. 
I want to implement a redis like KV system, so which type of api should i use to get the most read/write performance ?
I read stories about eleme.com, who has successful practice in tikv for production usage. i wonder how 
eleme take advantage of the tikv api.

**Comment by ddorian** [comment]
You can contribute to https://github.com/yongman/tidis for example.

See apis: https://www.pingcap.com/docs/tikv/go-client-api/ (non transactional is faster).
