### ISSUE TITLE
Starting `tikv-ctl` with no arguments results in unreachable!()

### ISSUE THREAD

**Issue by Hoverbear** [tikv/tikv#3453]
## Bug Report

**What version of Rust are you using?**
N/A

**What operating system and CPU are you using?**
N/A

**What did you do?**

```
tikv-ctl
```

**What did you expect to see?**

The output of:

```
tikv-ctl -- --help
```

**What did you see instead?**

```
thread 'main' panicked at 'internal error: entered unreachable code', src/bin/tikv-ctl.rs:109:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sch00lb0y** [comment]
This issue has been solved I guess.

**Comment by Hoverbear** [comment]
Thanks for noticing, @sch00lb0y
