### ISSUE TITLE
Can diesel be used with TiKV?

### ISSUE THREAD

**Issue by Boscop** [tikv/tikv#3462]
Can diesel be used with TiKV? If not, what should be used instead? :)

**Comment by siddontang** [comment]
Hi @Boscop 

Do you mean https://github.com/diesel-rs/diesel? 
 
It is an ORM framework and I haven't used it before, seem we can use it directly with TiDB.

**Comment by Boscop** [comment]
Thanks for the quick reply.

Yes, I meant using diesel with TiDB (not TiVK directly)..
I've been using diesel for postgres dbs in my Rust server, but for a new project I want to try TiDB (it's also a Rust server).
How can diesel ORM be used with TiDB in my Rust server? Should I just treat it as MySQL?
Can diesel also be used to generate & run db migrations on my TiDB database?

If it doesn't work the same way as using diesel with MySQL, do you have an example repo somewhere that shows the steps for TiDB?

Thanks :)

**Comment by breeswish** [comment]
@Boscop Yes, you just need to treat it as MySQL. We are MySQL protocol compatible and SQL syntax compatible. However note that not all kind of DDL operations are supported (see https://github.com/pingcap/docs/blob/master/sql/ddl.md#difference-from-mysql) so you may need extra work.

**Comment by Hoverbear** [comment]
Hi! I think this question is answered. I'll close it but you're welcome to reopen if that didn't work for you.
