### ISSUE TITLE
[Alerting] server report failures  will cause data loss?

### ISSUE THREAD

**Issue by jiancaiHub** [tikv/tikv#3465]
## Question

Alerting Info：

> server report failures

TiKV Doc：

> server report failures：正常情况显示 No data，如果出现了 Unreachable，说明 TiKV 之间通信有问题

Questions：

- Alerting will cause data loss or query error?

- There will be scenes triggering alarms？

![image](https://user-images.githubusercontent.com/16162787/44195677-5e928280-a16c-11e8-843a-4c3c68c84824.png)

**Comment by breeswish** [comment]
> Alerting will cause data loss or query error?

There will be query errors if majority is lost (and insertion or updates will fail but existing data will not be influenced). If only minority is lost, queries should be normal (but query duration may be longer, waiting for new leader election).

> There will be scenes triggering alarms？

It's very common, for example, when one TiKV is gone, or the network of the machine is down.

**Comment by jiancaiHub** [comment]
@breeswish thanks a lot~
