### ISSUE TITLE
Test the performance difference between RPN and naive recursion

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#3524]
Currently coprocessor expression is executed recursively, which can be expensive. Maybe we need to test how it performs when expression is expanded in a loop. We can translate the expression tree into an RPN, and than maintain a vector as its stack. The vector can be reused across all the rows.

**Comment by breeswish** [comment]
We are definitely using RPN now.

Additionally, here is a benchmark: https://gist.github.com/breeswish/6c98e7a41940547a93fa674a04557fbe
