### ISSUE TITLE
trace! is executed when log level > trace

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3537]
## Bug Report

```rust
    fn foo(kind: &str) -> ::std::time::Instant {
        println!("foo is called, kind = {}", kind);
        ::std::time::Instant::now()
    }
    trace!("foo after init log, now = {:?}", foo("after"));
```

Output:

```
foo is called, kind = after
```

As you can see, trace body is not outputted (expected), but trace body is really executed (unexpected). If what we are tracing is time consuming, it will hurt performance badly.

**Comment by BusyJay** [comment]
See also: https://github.com/tikv/tikv/pull/3010#issuecomment-388385374.

Although slog-stdlog is the one to be blamed this time.
