### ISSUE TITLE
Log cleaning

### ISSUE THREAD

**Issue by liubo0127** [tikv/tikv#3550]
## Feature Request

**Is your feature request related to a problem? Please describe:**
It will cause disk space not to be freed.

**Describe the feature you'd like:**
Add automatic log cleaning.

**Describe alternatives you've considered:**
Can configure crontab to clean up the logs.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Hoverbear** [comment]
@liubo0127 Definitely a legitimate request. :)

Since we're not logging to something like the systemd journal we need to worry about this.

**Comment by siddontang** [comment]
From @iamxy 

It is better for the users themselves to decide when to clean the log, so I will close this issue.
