### ISSUE TITLE
How does tikv maintain the monotonic of (raft) log Index

### ISSUE THREAD

**Issue by wolfkdy** [tikv/tikv#3559]
I've read your optimizations to raft, which can be found here(https://zhuanlan.zhihu.com/p/25735592)
There are severial points not mentioned in the article, but I think quite important. I'm not fimiliar with
RUST, so I wonder if someone can give me clues.
**Q1**:  Client(or proxy layer, not important) sends write requests to leader parallelly,  The requests are transformed into raftlog( I guess)。But raft has the requirement of monotonic log indexes. How did you 
transform parallel write requests into monotonic indexed raft logs ?
(addition: A direct way is to serialize parallel writes into a FIFO-queue, the queue has a single consumer, In this way, things are quite natural. But writes to the raftlog are single-threaded.)

Raft can be devided into two seperated parted. the raftlog and the (statemachine) kvstore.  the paper says logs can not be applied into kvstore until they are committed by the raft algorithm. My question is:
**Q2**: Will tikv apply raftlog locally before it has been committed by raft?
(addition: afaik, In raft, there is no need to rollback the statemachine layer after a election, since every log applied to statemachine is committed by raft. But this mechanism makes lantency longer)

**Comment by siddontang** [comment]
1. We use one queue for the Raft write, it is in sequence. 
2. No, the log can only be applied after committed.
