### ISSUE TITLE
skip_bcast_commit will delay follower's apply process

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#3578]
## Bug Report

**What version of Rust are you using?**
rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**What operating system and CPU are you using?**
Centos 7.3

**What did you do?**
Writing data continuously.

**What did you expect to see?**
Leader will be elected as soon as split finished.

**What did you see instead?**
I find that if region split happens, the new generated region can't elect a leader for about 2 seconds. After some investigation, i found that two followers applied split command 2 seconds after it has applied in leader. If i turn off `skip_bcast_commit`, this delay will go away.

**Comment by siddontang** [comment]
@zhangjinpeng1987 

`skip_bcast_commit` can reduce the message and help us gain a better performance, seem that for the admin operation, we need to force bcast, maybe we can use Context to do it.

/cc @Hoverbear @BusyJay
