### ISSUE TITLE
Use module path instead of file name in logging

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3587]
## Feature Request

Sometimes file name is identical enough, for example, multiple files are named as `mod.rs`, and it will be the name just printed out. This is actually not helpful for identifying issues. We can use module path instead.

**Comment by breeswish** [comment]
@BusyJay @Hoverbear How do you think?

**Comment by BusyJay** [comment]
I'm afraid it will be too long. Generally, combine file name and line number can identify a log location precisely.

**Comment by breeswish** [comment]
@BusyJay I was looking at the trace level logging, and these logs are really hard to identify location. How about truncating long module names using ..., like "raftstore::(...)::store::Peer"?

**Comment by Hoverbear** [comment]
What about the full file path? It will probably be shorter than module path.

**Comment by breeswish** [comment]
We have unified log format RFC. Closing.

**Comment by kennytm** [comment]
Unified log format doesn't really solve the ambiguity problem. There are still tons of `mod.rs` and `util.rs` which we can't identify the actual source without guessing 😞.

```
$ find src -name '*.rs' | grep -o '/[^/]*$' | sort | uniq -c | sort -r
  44 /mod.rs
  13 /metrics.rs
   9 /config.rs
   4 /util.rs
   4 /errors.rs
   3 /error.rs
   2 /transport.rs
   2 /table.rs
   2 /store.rs
   2 /snap.rs
   2 /readpool_context.rs
   2 /peer.rs
   2 /local_metrics.rs
   2 /keys.rs
   2 /future.rs
   2 /engine.rs
   2 /debug.rs
   2 /column.rs
   2 /client.rs
   2 /batch.rs
```
