### ISSUE TITLE
Run coverage report for PRs

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3591]
## Feature Request

Previously we disabled running coverage in PR #3247 because tests are run twice which slows down CI a lot.

Now [Tarpaulin supports returning test error codes](https://github.com/xd009642/tarpaulin/issues/119) so maybe we could merge them together and bring Tarpaulin back for PRs.

**Comment by siddontang** [comment]
you can have a try later @breeswish

**Comment by breeswish** [comment]
@siddontang It is rather a simple task. I marked it as help wanted so that contributions are welcome! :)

**Comment by siddontang** [comment]
Got it

**Comment by breeswish** [comment]
We are switching to our own CI platform so that community may not help us do this task any more. Closing.
