### ISSUE TITLE
Two single-threaded modules in TiKV limit the performance of TiDB

### ISSUE THREAD

**Issue by jaltabike** [tikv/tikv#3595]
I recently performed a custom benchmark for TiDB.
Through this benchmark, I suspect that the performance of my TiDB be limited by two single-threaded modules of TiKV: "raft store" and "async apply".

Specific symptoms were as follows.
While benchmarking, there was enough room for system resource usage of TiDB and TiKV like follows:
(CPU usage was around 60% and IO utilization was under 20%.)
![image](https://user-images.githubusercontent.com/1661884/45405387-9b836380-b69d-11e8-85e8-bf9afeaaedb8.png)

But, even if the query request rate increased,  there was a limit to the QPS increase.

I thought that performance bottleneck would be "raft store" and "async apply", which are probably "single-threaded" modules in TiKV, and the clues are:
- In Grafana Dashboard, the CPU usage of these threads was close to 100% each:
![image](https://user-images.githubusercontent.com/1661884/45405861-798ae080-b69f-11e8-8e3a-d24cc2653a46.png)
- using "top -H", the CPU usage of two threads (raftstore-? and apply-worker) was always almost 100% each.
(*is "apply-worker" in the result of "top -H" the same with "async apply" in Grafana Dashboard?)

Here's a summary of my questions:
1. Is "raft store" really single thread? Is "async apply" really single thread?
2. What do they actually do?
3. Are they really the bottlenecks in my situation?
4. Is there any solution to the above problem? Can adjusting the settings alleviate this problem?
5. Two issues [2960](https://github.com/tikv/tikv/pull/2960) and [3568](https://github.com/tikv/tikv/pull/3568) seem to be related to my problem. Are you planning to make "raft store" and "aync apply" multi-threaded?
6. I would like to analyze this issue in more depth. How do you usually do for profiling TiKV? Not familiar with Rust, I couldn't profile TiKV well. I tried to use perf as follows:
   sudo perf record -F 99 --pid ????? --call-graph dwarf sleep 30
   sudo perf report
But, symbols were missing (or demangled?) in the result of perf:
![image](https://user-images.githubusercontent.com/1661884/45407335-1485b980-b6a4-11e8-91de-88d7699da888.png)

**Comment by BusyJay** [comment]
Yes. Both "raftstore" and "async apply" are single thread for now. And we are working on replacing it with thread pool. raftstore drives raft FSMs and serializes raft log. "async apply" applies raft logs and serializes user data.

From the picture you posted, it's likely that "async apply" becomes the bottleneck in your situation. I think a solution may depend on the specific situation. Generally, this can be solved by making TiKV scale horizontally. For example, since there is still room on the machine, you can consider deploying two or more TiKV instances on the same node.

> ...But, symbols were missing (or demangled?) in the result of perf...

Those symbols showed in the picture are expected. As it shows, apply-worker is busy writing to rocksdb, which we are using to save user data. We have some open source tools for analyzing TiKV in depth, feel free to check it out [here](https://github.com/pingcap/tidb-inspect-tools/tree/master/tracing_tools). Contributions are welcome.

> ...Are you planning to make "raft store" and "aync apply" multi-threaded?

Single thread model used to work well for its high performance and simplicity. Although we can utilizing multiple cores by deploying multiple process, but it's not friendly for deployment. That's why we have two PRs trying to make them scale. There are still work need to be done, and hopefully we can make it available soon.

**Comment by jaltabike** [comment]
@BusyJay 
Thank you for your reply. It is very helpful to me. :)

**Comment by jaltabike** [comment]
@BusyJay 
I configured TiDB as you recommended above and performed the same benchmark again.
I added another TiKV instance to each node where an existing TiKV instance was deployed.
As a result, "async apply" became not the bottleneck:
![image](https://user-images.githubusercontent.com/1661884/45485683-783ae000-b793-11e8-9c45-56ea2b44703d.png)
I expected that QPS can be increased up to twice than before.
However, QPS increased a little (about 20%),
and there still was a room for system resource usage of TiDB and TiKV like follows:
(CPU usage was around 80% and IO utilization was still under 20%.)
![image](https://user-images.githubusercontent.com/1661884/45485913-3bbbb400-b794-11e8-8e5b-c09e4e6fede6.png)

In this time, it seemed that rocksdb was the bottleneck:
![image](https://user-images.githubusercontent.com/1661884/45486091-d5836100-b794-11e8-8dc3-8551311a1a03.png)
But, I don't know whether rocksdb CPU over 100% means that rocksdb is overloaded.
There were 6 rocksdb:bgs in my TiDB and max CPU usage could be 600%.
Nevertheless, does rocksdb CPU over 100% mean rocksdb is overloaded?
And, was rocksdb the bottleneck in my case?
Can I increase a system resource utilization and QPS more by adjusting the configurations?

**Comment by BusyJay** [comment]
> does rocksdb CPU over 100% mean rocksdb is overloaded

No.

> was rocksdb the bottleneck in my case?

There is no enough information to give the conclusion. You can try to use the Report button on the grafana dashboard to generate a complete report.

> by adjusting the configurations

It depends. You can also try to increase the benchmark concurrency.

**Comment by jaltabike** [comment]
@BusyJay 
Thank you for your reply.
I attach my report: [test-cluster-tikv.pdf](https://github.com/tikv/tikv/files/2381474/test-cluster-tikv.pdf)
Please take a look.
I already increased the benchmark concurrency until QPS no longer increases.

**Comment by BusyJay** [comment]
@DorianZheng would you like to take a look?

**Comment by DorianZheng** [comment]
@jaltabike I downloaded your report, but it seems that it's already damaged. Could you upload it again?

**Comment by jaltabike** [comment]
@DorianZheng 
I'm so sorry, I upload it again:
[test-cluster-tikv.pdf](https://github.com/tikv/tikv/files/2387167/test-cluster-tikv.pdf)

**Comment by DorianZheng** [comment]
@jaltabike Looks like it haven't reached bottleneck. Could you increase the number of threads (maybe double it or even higher) of the benchmark?

**Comment by jaltabike** [comment]
@DorianZheng 
I upload another report in which TiKV seems to reached bottleneck:
- Benchmark concurrency: use about 3000 clients -> TPS: 21,899.3 / MTT: 139.3
[document_20180919_3000.pdf](https://github.com/tikv/tikv/files/2394987/document_20180919_3000.pdf)
- Benchmark concurrency: use about 6000 clients -> TPS: 21,153.7 / MTT: 287.6
[document_20180919_6000.pdf](https://github.com/tikv/tikv/files/2394988/document_20180919_6000.pdf)

Increasing benchmark concurrency increases latency (MTT) only and does not increase TPS anymore.
Although the workload used is slightly different here (each transaction contains a single insert query, not a batch of insert queries), there is a similar problem: raft store, a single-threaded module in TiKV, seems to limit the performance of TiDB.

**Comment by DorianZheng** [comment]
@jaltabike What kind of network you are using, 1000Mbps or 10000Mbps? And what about your network interface card, 1000Mbps or 10000Mbps? Can you post the graph of network traffic too? I wonder if it is reach the network bottleneck.

**Comment by jaltabike** [comment]
@DorianZheng 
The graph of network traffic (when using about 3000 clients) was as follows:
- Inbound: tidb
![image](https://user-images.githubusercontent.com/1661884/45731722-e52afb80-bc13-11e8-9c16-9f8198b2ff6d.png)
- Outbound: tidb
![image](https://user-images.githubusercontent.com/1661884/45731738-f7a53500-bc13-11e8-82ee-e61460da7f6d.png)
- Inbound: tikv
![image](https://user-images.githubusercontent.com/1661884/45731758-0c81c880-bc14-11e8-91af-7f8cd65ebc98.png)
- Outbound: tikv
![image](https://user-images.githubusercontent.com/1661884/45731778-228f8900-bc14-11e8-88a6-a6c4ddaba6f1.png)

TiDB cluster was deployed on 9 AWS EC2 instances (i3.4xlarge type).
3 instances were used for TiDB and PD, and other 6 instances were used for TiKV.
Clients (load generator) were deployed on 3 AWS EC2 instances (c5.2xlarge type).
Amazon states that network performance of these EC2 instances is up to 10 gigabit,
but I don't know if these instances use multi-queue NIC.

**Comment by DorianZheng** [comment]
@BusyJay PTAL

**Comment by Hoverbear** [comment]
Hi folks, this issue has been stale for nearly 6 months so I'll close it now. YOu can reopen it if it's still relevant.
