### ISSUE TITLE
CI target cache might be broken now

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3600]
## Bug Report

From CI ([example](https://circleci.com/gh/tikv/tikv/13897)), we can see that it takes 0 seconds to download `target` cache. It might indicate that cache is not found. This lead to 30 minutes' built time. Previously when we have a target cache, it can be only 8 minutes ideally.

**Comment by chux0519** [comment]
It seems the cache key  should have `-{{ .Environment.CIRCLE_SHA1 }}` suffix. Adding the suffix may fix this.

**Comment by yangwenmai** [comment]
@breeswish You can review the pr #3619 .

**Comment by breeswish** [comment]
We are not using circle CI any more now. Closing.
