### ISSUE TITLE
coprocessor/codec/mysql/duration.rs:  function`micro_secs` of struct `Duration` return nanoseconds.

### ISSUE THREAD

**Issue by koushiro** [tikv/tikv#3601]
## Bug Report

I am a beginner of tikv.
I found this function when I wanted to add some push down scalar functions about time.
The name of the function is confusing.

```rust
pub fn micro_secs(&self) -> u32 {
       self.dur.subsec_nanos()
}
```

This function is currently only used in `to_decimal` of `Duration` and `Display` of `Duration`, like this:
```rust
let nanos = self.micro_secs() / (10u32.pow(NANO_WIDTH - u32::from(self.fsp)));
```

But in the function `round_frac` of `Duration`

```rust
let nanos = f64::from(self.dur.subsec_nanos())
            / f64::from(10u32.pow(NANO_WIDTH - u32::from(self.fsp)));
```

So I think it might be a bug.
Maybe I can submit a PR.

**Comment by BusyJay** [comment]
Yes, it's a wrong name. Feel free to fix it.
