### ISSUE TITLE
How can I  completely the transactions?

### ISSUE THREAD

**Issue by hellotomfan** [tikv/tikv#3617]
When some transactions wrote conflict, I got following logs:
```
INFO[0001] con:0 2PC clean up done, tid: 402977248933576732 
INFO[0001] con:0 2PC clean up done, tid: 402977248920469560 
INFO[0001] con:0 2PC clean up done, tid: 402977248907362321 
INFO[0001] con:0 2PC clean up done, tid: 402977248933576756 
```
and I don't rollback these transaction because they were invalid. 
I think I get these logs because I don't completely close these transactions. How can I completely close these transactions?

**Comment by zhangjinpeng1987** [comment]
@hellotomfan Can you provide more logs?
