### ISSUE TITLE
compile error:  does "raft" version mistake in Cargo.toml?

### ISSUE THREAD

**Issue by fredchenbj** [tikv/tikv#3632]
## Bug Report

**What version of Rust are you using?**
rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**What did you do?**
make build

**What did you see instead?**
error[E0599]: no method named `skip_bcast_commit` found for type `raft::RawNode<raftstore::store::peer_storage::PeerStorage>` in the current scope
--> src/raftstore/store/peer.rs:1070:37
|
1070 | self.raft_group.skip_bcast_commit(true);
| ^^^^^^^^^^^^^^^^^
error[E0599]: no method named `skip_bcast_commit` found for type `raft::RawNode<raftstore::store::peer_storage::PeerStorage>` in the current scope
--> src/raftstore/store/peer.rs:1297:37
|
1297 | self.raft_group.skip_bcast_commit(false);
| ^^^^^^^^^^^^^^^^^
error: aborting due to 2 previous errors

** reason about compile error**
In cargo.toml, raft version is required 0.3.1, but `fn skip_bcast_commit` is only found in 0.4.0.

**Comment by BusyJay** [comment]
I guess `Cargo.lock` is mutated on your workspace locally, which is expected to lock the version of raft to specific commit.

**Comment by BusyJay** [comment]
@Hoverbear Do you have time to update the raft dependency to latest release?

**Comment by fredchenbj** [comment]
@BusyJay Thanks. I used the domestic Cargo Sources(https://mirrors.ustc.edu.cn/crates.io-index), so the Cargo.lock file changed.

**Comment by Hoverbear** [comment]
@BusyJay We cannot update the raft version until https://github.com/pingcap/kvproto/pull/296. Once that is merged I will make a PR.

**Comment by MyonKeminta** [comment]
Seems the issue was solved. Should we close this?
