### ISSUE TITLE
Remove --exclude tikv_fuzz

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3638]
## Feature Request

Currently [we have --exclude tikv_fuzz in Makefile](https://github.com/tikv/tikv/blob/3ee21dca43d5fc9d16542e751c5961dceaf21e5f/Makefile#L87). It will be nice to remove it.

**Comment by zhangjinpeng1987** [comment]
@overvenus PTAL

**Comment by breeswish** [comment]
Fixed after fuzz refinement.
