### ISSUE TITLE
[TiKV Client][C++][Error Handling] how to handle "Not Leader" error

### ISSUE THREAD

**Issue by Xavier1994** [tikv/tikv#3656]
## Question

I'm writing cpp client for TiKV, I get some problem  about error handling

1. I send a request to a region, but get "Region Is Stale" error, because the target region has been split into two new region. for example, the original region is **{region id: 1000, conf ver: 4, ver: 5}**,
new regions **{region id: 1000, conf ver: 4, ver: 6}**, **{region id: 1001, conf ver: 4, ver:6}**
2. I get new region info from the return error, drop old region info from my local region cache and add new region info into my local region cache.  
3. I send a new request to new region **{region id: 1001, conf ver: 4, ver:6}** and get a "Not Leader" error, but the error has no leader info, so i can't update the region's leader info. 
4. I drop the region from local cache and try to get region info from PD, but PD doesn't have the region's info. 

So what should i do if i get a "Not Leader" error without new leader info.

I have read the TiKV go client code, but still confusing

**Comment by c4pt0r** [comment]
@siddontang  @disksing  PTAL

**Comment by gregwebs** [comment]
You might be interested to learn about the Rust client being worked on (it would also expose a C interface). @Hoverbear

**Comment by siddontang** [comment]
@Xavier1994 
 
Very glad to hear that you are building a C++ client for TiKV.
Seems that Region 1001 has not elected a new leader and reported to PD, so you can't get the leader info from PD. In Go client, we will wait some time and retry to get it again.

**Comment by Hoverbear** [comment]
Hi @Xavier1994, if you encounter any problems with your effort to develop a TiKV client please feel very welcome to open any issues here. We are excited  about this project! You can also contact me at andrew@pingcap.com if you would like to ask something privately.

Thanks so much for your efforts!
