### ISSUE TITLE
One of tikv instances is always restarting every minute

### ISSUE THREAD

**Issue by powqabc** [tikv/tikv#3658]
There is a tidb cluster and the structure of tikv instance like this：
![image](https://user-images.githubusercontent.com/10123620/46664249-04a1bc80-cbf3-11e8-886b-6b4ce7062c00.png)
Now,the Tikv2-1 tikv instance is always restarting.There are some messages like this:
![image](https://user-images.githubusercontent.com/10123620/46664475-b80ab100-cbf3-11e8-9640-f5677f9307c6.png)
And,the version of tikv is this:
![image](https://user-images.githubusercontent.com/10123620/46664510-d07acb80-cbf3-11e8-80c8-61ca0ee17ba1.png)

**Comment by breeswish** [comment]
@overvenus  PTAL

**Comment by zhangjinpeng1987** [comment]
@powqabc Does the machine has restarted?

**Comment by siddontang** [comment]
do you enable `sync-log`? seem the raft log is lost.

**Comment by powqabc** [comment]
> @powqabc Does the machine has restarted? It looks has lost some raft entries.

I confirmed that the machine has restarted. Now, what do I need to do?

**Comment by powqabc** [comment]
> do you enable `sync-log`? seem the raft log is lost.

I set sync-log=false

**Comment by hicqu** [comment]
The reason is some raft entries are lost when the machine down. You can use [tikv-ctl tombstone](https://github.com/pingcap/docs-cn/blob/master/tools/tikv-control.md) to remove the bad region `702622` from the store.

**Comment by powqabc** [comment]
> The reason is some raft entries are lost when the machine down. You can use [tikv-ctl tombstone](https://github.com/tikv/tikv/blob/master/docs/tools/tikv-control.md) to remove the bad region `702622` from the store.

Thank you
