### ISSUE TITLE
#[should_panic] unit tests cannot pass CI

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3664]
## Bug Report

As title describes, `#[should_panic]` tests, or tests using `catch_unwind` cannot pass CI, even if they succeeded actually.

Previously found in https://github.com/tikv/tikv/pull/3629#issuecomment-424557383

**Comment by breeswish** [comment]
@BusyJay Since the checking script that cannot support should_panic was written by you, you may have some new ideas about how to fix it?

**Comment by breeswish** [comment]
Currently it blocks #3629 because there are panic tests in that PR.

**Comment by BusyJay** [comment]
You can use `recover_safe` instead of `#[should_panic]` or `catch_unwind`, so panic trace won't be printed out.

**Comment by breeswish** [comment]
@BusyJay Good idea! So this issue won't block #3629 but still nice to be fixed some day.

**Comment by Hoverbear** [comment]
I think this is a bug with how TiKV does CI. `#[should_panic]` tests don't cause `cargo test` to return non-zero. This doesn't change when you enable backtraces or logs.

```
hoverbear@nomad:~/temp ‹master*›$ cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s                                                                                                                                
     Running target/debug/deps/temp-7c021f9e90acc06f

running 1 test
test panic_stuff ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests temp

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

hoverbear@nomad:~/temp ‹master*›$ echo $?
0
hoverbear@nomad:~/temp ‹master*›$ cat src/lib.rs 
fn stuff() {
    panic!("Hello, world!");
}

#[test]
#[should_panic]
fn panic_stuff() {
    stuff();
}
```

**Comment by breeswish** [comment]
@Hoverbear Yeah.. The problem is that our CI script tried to parse panic messages from output.. so even if it returned with exit code 0, it is still treated as failures :(

**Comment by Hoverbear** [comment]
Oh no.

**Comment by BusyJay** [comment]
We don't use `should_panic`, we can do `catch_unwind` if necessary.
