### ISSUE TITLE
Tikv: How to config to use a large region ?

### ISSUE THREAD

**Issue by romiguan** [tikv/tikv#3665]
### Env: 
    _tikv 2.1.0-rc.1  PD: v2.1.0-rc.1-1-g47a950e_
### Question:
In our production scenario, we will provision data offline and then put it to production env. And in production env, only batchGet(300 keys one batch) is performed, no put operation.
Our test result shows that under high concurrency, since one goroutine per region, too many goroutines generated in TikvRawClient and the response cost is high. So we want to increase the region size to a bigger value to decrease the num of regions.
    In TiKV configuration file, we found below configs:
```
[coprocessor]
split-region-on-table = true
batch-split-limit = 10
region-max-size = "384MB"
region-split-size = "256MB"
region-max-keys = 500000
region-split-keys = 300000

```
For example, if I want to enlarge the region size to 10x bigger, just increasing above 4 configurations to 10x value, Is is right? We have enlarge the region-xxx configs to 10x bigger, but the region size is only 3-4 times bigger. Please indicate how to configure a bigger region size as expected, thanks.

**Comment by breeswish** [comment]
Hi,

Large region is highly not recommended, which usually degrades performance instead. For your scenario, how about adjusting [grpc-connection-count](https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L219)?

For your question, you may take a look at the keys in region and check out whether they exceeds the configuration. Also if you are changing region size over existing data, it won't take effect immediately.

**Comment by romiguan** [comment]
> Hi,
> 
> Large region is highly not recommended, which usually degrades performance instead. For your scenario, how about adjusting [grpc-connection-count](https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L219)?
> 
> For your question, you may take a look at the keys in region and check out whether they exceeds the configuration. Also if you are changing region size over existing data, it won't take effect immediately.

We use a proxy to wrap the batchGet operation(using tikv raw client) to tikv server, not use tidb. Then how to change it ? We have found that it is hard-coded in client code.
