### ISSUE TITLE
test_delay_split_region failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3669]
## Bug Report

See https://circleci.com/gh/tikv/tikv/14340

@overvenus @hicqu PTAL

**Comment by overvenus** [comment]
PTAL @BusyJay

**Comment by siddontang** [comment]
PTAL @zhangjinpeng1987

**Comment by overvenus** [comment]
Another failed tests https://circleci.com/gh/tikv/tikv/14521

**Comment by MyonKeminta** [comment]
It fails randomly and may either panic [here](https://github.com/tikv/tikv/blob/7315140a1a6b29b724d362c3b0f64ea8e19424c9/tests/raftstore_cases/test_split_region.rs#L335) (`thread 'raftstore_cases::test_split_region::test_delay_split_region' panicked at 'can't get value None for key "k4"'`)  or [here](https://github.com/tikv/tikv/blob/7315140a1a6b29b724d362c3b0f64ea8e19424c9/tests/raftstore_cases/test_split_region.rs#L315)(`thread 'raftstore_cases::test_split_region::test_delay_split_region' panicked at 'can't get value None for key "k0"'`)

**Comment by breeswish** [comment]
Failure: https://circleci.com/gh/tikv/tikv/14762

**Comment by Hijiao** [comment]
It fails [here](https://github.com/tikv/tikv/blob/7315140a1a6b29b724d362c3b0f64ea8e19424c9/tests/raftstore_cases/test_split_region.rs#L323) too.  (`thread 'raftstore_cases::test_split_region::test_delay_split_region' panicked at 'can't get value None for key "k5"`)

**Comment by Hijiao** [comment]
@BusyJay Why sleep only 100ms? is it too short?
>     cluster.must_put(b"k4", b"v4");
>     sleep_ms(100);
>     check_cluster(&mut cluster, b"k4", b"v4", false);
 [line312](https://github.com/tikv/tikv/blob/7315140a1a6b29b724d362c3b0f64ea8e19424c9/tests/raftstore_cases/test_split_region.rs#L312) and [line332](https://github.com/tikv/tikv/blob/7315140a1a6b29b724d362c3b0f64ea8e19424c9/tests/raftstore_cases/test_split_region.rs#L332)
