### ISSUE TITLE
Selection executor does not handle start_scan or stop_scan correctly

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3677]
## Bug Report

As title describes.

By default, `stop_scan` will return `None` and we explicitly implemented these interface for Table Scan and Index Scan. However we may have the following scenario: selection + table_scan. Then it will break.

Also it can be seen that the best solution is to inherit start_scan and stop_scan from child executors by default (currently our behaviour is override with None).

**Comment by malc0lm** [comment]
@breeswish Hi, I'm trying to fix this issue, but I didn't understand your scenario "selection + table_scan" which you mentioned above.  In test "test_selection_executor_simple", "SelectionExecutor" has a "src" field which is just "TableScanExecutor", and it works fine. So what does "selection + table_scan" mean? I'm starter for tikv :)

**Comment by malc0lm** [comment]
@breeswish Hi, I'm trying to fix this issue, but I didn't understand your scenario "selection + table_scan" which you mentioned above.  In test "test_selection_executor_simple", "SelectionExecutor" has a "src" field which is just "TableScanExecutor", and it works fine. So what does "selection + table_scan" mean? I'm starter for tikv :)

**Comment by jswh** [comment]
This issue is opened at 15 Oct 2018, is it still valid?

**Comment by BusyJay** [comment]
It's still valid for 3.0 when using streaming call. Since 4.0 is released and streaming call is not used by default, I think we can mark it as won't fix and close it.
