### ISSUE TITLE
TiKV support encryption before store into the low level engine

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#3680]
## Feature Request

TiKV support encrypting the data before store it into the low level engine.

**Comment by MyonKeminta** [comment]
Emmm, why is this feature important?

**Comment by breeswish** [comment]
@MyonKeminta This seems to be a feature very useful for enterprises.

**Comment by breeswish** [comment]
How about utilizing RocksDB's env encryption? https://github.com/facebook/rocksdb/blob/189f0c27aaecdf17ae7fc1f826a423a28b77984f/include/rocksdb/env_encryption.h

**Comment by siddontang** [comment]
I think using RocksDB's is enough.

**Comment by siddontang** [comment]
BTW, @huachaohuang you must also consider this.

**Comment by MyonKeminta** [comment]
One thing we should also take care is that, sometimes a little data would show up in logs. If we do want to encrypt data on disk, I think these logs should also be treated carefully.

**Comment by Hoverbear** [comment]
@MyonKeminta maybe we can also encrypt the logs?

**Comment by gregwebs** [comment]
TiKV has support for encryption at rest now. @yiwu-arbug  should this issue be closed?

I came here from this page which is out of date: https://tikv.org/docs/3.0/tasks/configure/security/

**Comment by yiwu-arbug** [comment]
Closing stale issue.
