### ISSUE TITLE
Consider choosing block strategy for slog-async

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#3695]
## Question

There are lot of `slog-async: logger dropped messages due to channel overflow, count: 7` in tikv's log file. The `count: 7` means 7 logs have been drop due to slogger channel full. There is no way to recover dropped logs, which is not helpful for debugging. The behaviour is controlled by `slog_async::OverflowStrategy`. Instead of `OverflowStrategy::DropAndReport`(current strategy), please consider choosing `OverflowStrategy::Block`, so tikv prints all logs.

**Comment by Hoverbear** [comment]
Already fixed in `master` quite some time ago:

https://github.com/tikv/tikv/blob/d046faecf56a11e526ce4f0211fe76ac5f1c7296/src/bin/util/setup.rs#L39-L62

**Comment by Hoverbear** [comment]
Ah, of course!

**Comment by hicqu** [comment]
Why not remove redudant logs? For example, `CompactLog` is print too frequently.

**Comment by Hoverbear** [comment]
@hicqu We don't ever want to drop logs (this is a bug). Removing redundant logs is a feature request, and can have it's own issue. :)
