### ISSUE TITLE
Backward raw scan

### ISSUE THREAD

**Issue by kamijin-fanta** [tikv/tikv#3705]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When used as KVS, if the direction of scanning is one side, twice the capacity is required.

**Describe the feature you'd like:**

Add reverse option to raw_scan.

**Describe alternatives you've considered:**

I think that it will be such a proto file.
https://github.com/kamijin-fanta/kvproto/commit/3e914a67e191

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by MyonKeminta** [comment]
It's a reasonable feature. Would you like to help implementing it?
Your changes to kvproto seems well, but I think it will be better if we also add the `reverse` field to `RawBatchScanRequest`

**Comment by MyonKeminta** [comment]
Would you like to have a try? 🤣

**Comment by kamijin-fanta** [comment]
yes!!

**Comment by kamijin-fanta** [comment]
Merged
