### ISSUE TITLE
TiKV Server crashed in rocksdb.bg2

### ISSUE THREAD

**Issue by shafreeck** [tikv/tikv#3709]
## Bug Report

**What version of Rust are you using?**
Installed by ansible, release 2.0.6

**What operating system and CPU are you using?**

CentOS Linux release 7.3.1611 (Core)
```
processor       : 39
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb00001d
cpu MHz         : 2200.000
cache size      : 25600 KB
physical id     : 1
siblings        : 20
core id         : 12
cpu cores       : 10
apicid          : 57
initial apicid  : 57
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc dtherm arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4403.54
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```
**What did you do?**

It occured when importing large dataset with small key-value sizes. I can not reproduce it now and ther is no coredump file.

**What did you expect to see?**

DO NOT CRASH

**What did you see instead?**
TiKV Server crashed

**Other info**
[2577231.277642] rocksdb:bg2[33473]: segfault at 7b23 ip 00005580bce6fc81 sp 00007f843a1fd090 error 4 in tikv-server[5580bbf51000+145b000]

**Comment by solotzg** [comment]
@huachaohuang PTAL.

**Comment by huachaohuang** [comment]
Looks like it ran into a weird address, can you try to do this:

`addr2line -e /path/to/tikv-server 7b23`

BTW, anything special happened when it crashed? Like it was shutting down?

**Comment by shafreeck** [comment]
Has lost the environment and outdated for a long time. Close it now.
