### ISSUE TITLE
TiKV can not stop immediately when compacting

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#3734]
## Bug Report

**What did you do?**
A user feedbacks that he sometimes encounters that TiKV can not restart quickly when compacting.  For the worst case, TiKV restart takes about 30 minutes or so.

the log will be attached later.

**Comment by zhangjinpeng1987** [comment]
Any more informations?

**Comment by darren** [comment]
sorry, I have not tried to restart tikv recently, 
when rc.5 is out, I will tried to update and restart all instances to see if problem can be reproduced.

**Comment by Connor1996** [comment]
Fixed in https://github.com/tikv/tikv/pull/16700
