### ISSUE TITLE
TiKV build error!!!

### ISSUE THREAD

**Issue by kg88** [tikv/tikv#3748]
## Question
When I  build TiKV , somthing is worng. 
--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:118 (include)

CMake Warning at cmake/gflags.cmake:26 (message):
  gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:120 (include)

CMake Warning at cmake/benchmark.cmake:26 (message):
  gRPC_BENCHMARK_PROVIDER is "module" but BENCHMARK_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:121 (include)

cc1: warnings being treated as errors
In file included from /root/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.0/grpc/third_party/boringssl/third_party/fiat/curve25519.c:38:
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.0/grpc/third_party/boringssl/third_party/fiat/../../include/openssl/sha.h:111: 错误：没有声明任何东西
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.0/grpc/third_party/boringssl/third_party/fiat/../../include/openssl/sha.h:112: 错误：没有声明任何东西
cc1: 错误：无法识别的命令行选项“-Wno-free-nonheap-object”
gmake[4]: *** [third_party/boringssl/third_party/fiat/CMakeFiles/fiat.dir/curve25519.c.o] 错误 1
gmake[3]: *** [third_party/boringssl/third_party/fiat/CMakeFiles/fiat.dir/all] 错误 2
gmake[2]: *** [CMakeFiles/grpc.dir/rule] 错误 2
gmake[1]: *** [grpc] 错误 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.28/src/lib.rs:631:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Please hlep me, thank you.

**Comment by ice1000** [comment]
Please provide your cmake version, rust toolchain (cargo, rustc, etc) version, the command line flag you used to build tikv, and maybe the Cargo.toml of your project (in particular the tikv related part), thank you.

**Comment by ice1000** [comment]
Sounds like it's a `grpcio` related build error, you can go to github.com/pingcap/grpc-rs to see if there's already a solution.

**Comment by kg88** [comment]
OK,
cmake version 3.5.2
rust version 1.30.0

Cargo.toml
[package]
name = "tikv"
version = "2.1.0-rc.2"
keywords = ["KV", "distributed-systems", "raft"]
publish = false

[features]
default = []
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
mem-profiling = ["jemallocator"]
no-fail = ["fail/no_fail"]

[lib]
name = "tikv"

[[bin]]
name = "tikv-server"

[[bin]]
name = "tikv-ctl"

[[bin]]
name = "tikv-importer"

[[bench]]
name = "raftstore"
harness = false

[[bench]]
name = "benches"

[dependencies]
log = { version = "0.3", features = ["release_max_level_debug"] }
slog = "2.3"
slog-async = "2.3"
slog-scope = "4.0"
slog-stdlog = "3.0.4-pre"
slog-term = "2.4"
byteorder = "1.2"
rand = "0.3"
quick-error = "1.2.2"
tempdir = "0.3"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.8"
fs2 = "0.4"
protobuf = "~2.0"
nix = "0.11"
utime = "0.2"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "0.2.1"
backtrace = "0.2.3"
clap = "2.32"
url = "1.5"
regex = "1.0"
fnv = "1.0"
sys-info = "0.5.1"
indexmap = { version = "1.0", features = ["serde-1"] }
mio = "0.5"
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"
tokio-timer = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rustc-serialize = "0.3"
zipf = "0.2.0"
bitflags = "1.0.1"
fail = "0.2"
uuid = { version = "0.6", features = [ "serde", "v4" ] }
grpcio = { version = "0.4", features = [ "secure" ] }
raft = "0.3"
crossbeam-channel = "0.2"
crossbeam = "0.2"
fxhash = "0.2"
derive_more = "0.11.0"
num = "0.2.0"
hex = "0.3"
rust-crypto = "^0.2"

[replace]
"raft:0.3.1" = { git = "https://github.com/pingcap/raft-rs.git" }

[dependencies.murmur3]
git = "https://github.com/pingcap/murmur3.git"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"

[dependencies.tipb]
git = "https://github.com/pingcap/tipb.git"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
version = "0.1.4"

[dependencies.jemallocator]
git = "https://github.com/busyjay/jemallocator.git"
branch = "dev"
features = ["profiling"]
optional = true

[dev-dependencies]
test_util = { path = "components/test_util" }
test_raftstore = { path = "components/test_raftstore" }
test_storage = { path = "components/test_storage" }
test_coprocessor = { path = "components/test_coprocessor" }
criterion = "0.2"
arrow = "0.10.0"

[target.'cfg(unix)'.dependencies]
signal = "0.6"

[workspace]
members = [
  "fuzz",
  "components/test_raftstore",
  "components/test_storage",
  "components/test_coprocessor",
  "components/test_util",
  "components/codec",
]

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
codegen-units = 4
# The release profile, used for `cargo build --release`
[profile.release]
lto = true
opt-level = 3
debug = true
# TODO: remove this once rust-lang/rust#50199 and rust-lang/rust#53833 are resolved.
codegen-units = 1

# The benchmark profile is identical to release, except that lto = false
[profile.bench]
lto = false
opt-level = 3
debug = true
codegen-units = 1

**Comment by kg88** [comment]
Maybe my CMake version is not correct

**Comment by ice1000** [comment]
CMake 3.5 is fine.

**Comment by kg88** [comment]
I cannot find solution，so terrible.

**Comment by ice1000** [comment]
Can you try replacing
```toml
grpcio = { version = "0.4", features = [ "secure" ] }
```
with
```toml
grpcio = { version = "0.4", features = [ "secure", "openssl" ] }
```

**Comment by ice1000** [comment]
Sorry, it's in an unpublished version of grpcio.

**Comment by ice1000** [comment]
I've found a similar issue: https://github.com/pingcap/grpc-rs/issues/110

**Comment by kg88** [comment]
I tried and he said :

the package `tikv` depends on `grpcio`, with features: `openssl` but `grpcio` does not have these features.

**Comment by kg88** [comment]
I will see the issue.

**Comment by kg88** [comment]
@ice1000
I find the fault, cmake version must be >3.8 now. Thank you very very much,bro!

**Comment by ice1000** [comment]
> I find the fault, cmake version must be >3.8 now. Thank you very very much, bro!

Can you elaborate? What is actually causing the issue?

**Comment by kg88** [comment]
@ice1000 
grpc must use the cmake version >3.8,  I install cmake versoin 3.12.0, and it works.

**Comment by kg88** [comment]
@ice1000
https://github.com/pingcap/grpc-rs
You can see that : 
Prerequisites

    CMake >= 3.8.0
    Rust >= 1.19.0
    By default, the secure feature is enabled, therefore Go (>=1.7) is required.

**Comment by ice1000** [comment]
But pingcap/grpc-rs#250

**Comment by ice1000** [comment]
And in grpc's code base

```cmake
cmake_minimum_required(VERSION 2.8)
```
:confused:

**Comment by ice1000** [comment]
I'm happy that CMake >3.8 resolves your issue, but as one of the maintainers of grpcio, I'd like to see the actual cause and try to make it compatible with the Ubuntu's default CMake version (3.5, which can be easily installed via `sudo apt install cmake`)

**Comment by ice1000** [comment]
This is why I commented https://github.com/tikv/tikv/issues/3748#issuecomment-436471489 , because cmake 3.5.1 works fine with grpcio in pingcap/grpc-rs#250 .

**Comment by kg88** [comment]
@ice1000
If I find the same bug, I will  discuss with you,sir.

**Comment by ice1000** [comment]
Thank you!
