### ISSUE TITLE
gcc 4.9 internal error when building TiKV

### ISSUE THREAD

**Issue by kg88** [tikv/tikv#3754]
## Question
My gcc version -- 4.9.0

when I make build the TiKV, it said:
--- stderr
thread 'main' panicked at '

Internal error occurred: Command "/usr/local/gcc/bin/gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/root/\xe6\xa1\x8c\xe9\x9d\xa2/tikv/target/release/build/zstd-sys-bb65b8cc2fe0387c/out/zstd/lib/compress/huf_compress.o" "-c" "zstd/lib/compress/huf_compress.c" with args "gcc" did not execute successfully (status code exit code: 1).

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by ice1000** [comment]
Could you please try with a newer version of gcc? Like 8.1?

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-8 g++-8
```

**Comment by ice1000** [comment]
This looks like a bug of old gcc, see the beginning of the error message.

> Internal error occurred

**Comment by ice1000** [comment]
Should we document the least tested gcc version? Friendly ping @overvenus

**Comment by kg88** [comment]
Ok, I will try. It may spend long time to run.

**Comment by kg88** [comment]
It doesn't work. I will update gcc again.

**Comment by kg88** [comment]
So bad!
My gcc version is 8.1.0
      Compiling zstd-sys v1.4.4+zstd.1.3.5 (https://github.com/gyscos/zstd-rs.git#0100c848)
error: failed to run custom build command for `zstd-sys v1.4.4+zstd.1.3.5 (https://github.com/gyscos/zstd-rs.git#0100c848)`
process didn't exit successfully: `/newdisk/tikv/target/debug/build/zstd-sys-d5428f28dfd1830d/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/debug.o" "-c" "zstd/lib/common/debug.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/entropy_common.o" "-c" "zstd/lib/common/entropy_common.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/error_private.o" "-c" "zstd/lib/common/error_private.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/fse_decompress.o" "-c" "zstd/lib/common/fse_decompress.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/pool.o" "-c" "zstd/lib/common/pool.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/threading.o" "-c" "zstd/lib/common/threading.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/xxhash.o" "-c" "zstd/lib/common/xxhash.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/common/zstd_common.o" "-c" "zstd/lib/common/zstd_common.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/compress/fse_compress.o" "-c" "zstd/lib/compress/fse_compress.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/compress/hist.o" "-c" "zstd/lib/compress/hist.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("cc")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/compress/huf_compress.o" "-c" "zstd/lib/compress/huf_compress.c"
cargo:warning=/tmp/cc8WefQu.s: Assembler messages:
cargo:warning=/tmp/cc8WefQu.s:247: Error: no such instruction: `shlx %r13,%rax,%rax'
cargo:warning=/tmp/cc8WefQu.s:288: Error: no such instruction: `shlx %rcx,%r13,%rcx'
cargo:warning=/tmp/cc8WefQu.s:311: Error: no such instruction: `shlx %r12,%rcx,%r12'
cargo:warning=/tmp/cc8WefQu.s:326: Error: no such instruction: `shlx %rdx,%rcx,%rcx'
cargo:warning=/tmp/cc8WefQu.s:429: Error: no such instruction: `shrx %rdx,%rax,%rsi'
cargo:warning=/tmp/cc8WefQu.s:679: Error: no such instruction: `shlx %r9,%rsi,%rsi'
cargo:warning=/tmp/cc8WefQu.s:763: Error: no such instruction: `shrx %rax,%rsi,%rsi'
cargo:warning=/tmp/cc8WefQu.s:822: Error: no such instruction: `shlx %r9,%rcx,%rsi'
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-DZSTD_LIB_DEPRECATED=0" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/newdisk/tikv/target/debug/build/zstd-sys-4c9ce07942fcb1dc/out/zstd/lib/compress/huf_compress.o" "-c" "zstd/lib/compress/huf_compress.c" with args "cc" did not execute successfully (status code exit code: 1).

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make: *** [clippy] 错误 101

**Comment by kg88** [comment]
@ice1000 
Yes , I try. It doesn't work again. It is so strange! 
It runs well on my mac, mybe I will give up centos.

**Comment by DorianZheng** [comment]
@kg88 looks like `as` can't recognize `shlx` instruction, could you update your `binutils`
FYI
```
wget https://ftp.gnu.org/gnu/binutils/binutils-2.31.1.tar.gz
tar -zxf binutils-2.31.1.tar.gz 
cd binutils-2.31.1
make 
make install
```

**Comment by Hoverbear** [comment]
Hi! Seems this question is resolved. Please reopen if it's not.
