### ISSUE TITLE
CompactLog is too noisy under heavy write load

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#3762]
## Feature Request

**Is your feature request related to a problem? Please describe:**
The `CompactLog` is too noisy under heavy write load.

**Describe the feature you'd like:**
We can reduce the related logs by enlarge compact step. At the same time we can add a last compacted time for each region. When the last compacted time is long enough we can dynamically 
use a small compact step for this region. This can prevent the applied raft logs occupy too many disk space.

**Comment by Hoverbear** [comment]
Seems duplicate of https://github.com/tikv/tikv/issues/3770
