### ISSUE TITLE
test_follower_slow_split failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3793]
## Bug Report

https://circleci.com/gh/tikv/tikv/14968?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by huachaohuang** [comment]
https://circleci.com/gh/tikv/tikv/15035?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by overvenus** [comment]
test_follower_slow_split failed again. https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/8463/pipeline/126

**Comment by gengliqi** [comment]
close because the duration after the last failed test is too long and can not see the log
