### ISSUE TITLE
Encode the "signed" information into types to simplify copr builtins

### ISSUE THREAD

**Issue by niedhui** [tikv/tikv#3803]
## Feature Request

**Is your feature request related to a problem? Please describe:**

currently , in some  builtin functions, we always need to  check whether the `Int` is unsigned after calling `eval_int`. If forgot, then we will get unexpected behavior.  the current implementation `builtin_string#left/right`, `builtin_math#round` is incorrect when the input is u64.

**Describe the feature you'd like:**

Can we introduce a `BigInt`, just wrapped the `i64` representation of the number, and whether it is `unsigned`?  then we can leave all the `unsigned` and overflow related logic to it. and 
1. we can impl `Add/Sub/Mul/Div/Rem/Cmp` on it. 
2. we can add some as_xx function, when do casting, normally we want the closest value if trucation occured, not just truncate the higher bits

**Teachability, Documentation, Adoption, Migration Strategy:**

I make a quick implementation to describe it,  https://github.com/niedhui/tikv/commit/ac1f85a32cce00c20428742734a3238cdfe86559

**Comment by ice1000** [comment]
> Can we introduce a BigInt, just wrapped the i64 representation of the number, and whether it is unsigned?

Don't you think the name is ambiguous? I agree with the idea though.

**Comment by niedhui** [comment]
agreed 🤣 . not found a good name,  just pick a simple name so we can start  discuss on it . Maybe WrappedInt or something else.

**Comment by breeswish** [comment]
Thanks. Do you mean that you would like to introduce a special structure (i.e. your `BigInt`), instead of a just simple `i64`, to handle int number eval types?

**Comment by niedhui** [comment]
yes. currently ,we use `i64` and `unsigned flag` to represent mysql BigInt. sometimes `i64` is fine, like `CONV(N,from_base,to_base)`,  if user input a `u64::max_value() - 1`, mysql just treat it as `-2`.
but there are lot where we need to figure out whether it'a `u64` or `i64`, using ` xxx.field_type().flag().contains(FieldTypeFlag::UNSIGNED)`, a litte cumbersome. so maybe we can abstract some common logic to the struct. I think it's similar to the `eval_string_and_decode` function

**Comment by breeswish** [comment]
Looks like a good idea! But I have some concern about introducing extra field "unsigned", since we are now vectorizing the Coprocessor and adding extra field for each datum will decrease the effectiveness of cache line as well as SIMD in future.

@zz-jason PTAL, How about introducing new eval types for unsigned types?

**Comment by breeswish** [comment]
@ice1000 Yes, that's my preferred solution as well. However I believe this requires some change at TiDB side first

**Comment by zz-jason** [comment]
I think it's better not to bind the type information with the concrete value. As @breeswish mentioned in the above, this `Bigint` is not efficient in the SIMD instructions. And also, a lot of memory are wasted in the vectorized execution to store the same type info for a vector of values.

> using `xxx.field_type().flag().contains(FieldTypeFlag::UNSIGNED)`, a litte cumbersome.

Can we implement a function like `IsUnsigned()` for field type? The function call can be simplified to `xxx.field_type().IsUnsigned()`

**Comment by zz-jason** [comment]
> Any possibility to introduce new types? So all these "constraints" exist only at compile time.

In MySQL, all the numeric types can be unsigned: https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html. 😂

**Comment by niedhui** [comment]
thanks for all your response.
I used to be a web developer, the most straight way to reduce common logic is introducing an Object.
but as performance is very important in TiKV, I'll look into SIMD first.

> Can we implement a function like IsUnsigned() for field type? The function call can be simplified to xxx.field_type().IsUnsigned()

the most common and cumbersome logic is : unsigned?, positive?,  safely cast to other numeric type(truncate to closed value, not truncte just the higher bits)

**Comment by breeswish** [comment]
I think actually the complex part is not testing the sign, but casting number into a smaller width. I agree that it should be simplified, but I don't have a very good idea now. We need more discussion over this change.

**Comment by niedhui** [comment]
@breeswish can we add an inline helper method `is_unsigned` to `Expression` first , so we can call 
```
let unsigned = self.children[0].is_signed();
```
instead of 
```rust
        let unsigned = self.children[0]
            .field_type()
            .flag()
            .contains(FieldTypeFlag::UNSIGNED);
```
since there're so many places we need to call this when implement `builtin` functions, the four line code really boring when I need to do this 😭

**Comment by breeswish** [comment]
Hmm. In fact, originally it looked like this. However later, considering that there are so many flags and it is not convenient to add function multiple times for each corresponding flag this kind of function was removed. So maybe we can just add convenient functions for some common flags instead, just like you proposed?

**Comment by niedhui** [comment]
I

**Comment by niedhui** [comment]
I think it's  a kind of delegation refactor for convenience. I'll open a PR to discuss later

**Comment by breeswish** [comment]
According to some latest attempts in batch execution, we are now using the following approach (in batch execution):

1. Store i64 and u64 together in i64, as before. (maybe change in future).
2. If some UDF has different implementations for signed / unsigned, then we need to write two functions (so that the checking of signed / unsigned is *outside* the loop).
3. The checking of signed or not is performed in the mapping function, outside UDF.

This works pretty well so far, as an alternative and the final solution to the problem that this issue is going to take care of. So I'm going to close this issue. Feel free to discuss about the new implementation.
