### ISSUE TITLE
IndexScanExecutor is slower than TableScanExecutor

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3815]
## Bug Report

```
table_scan_primary_key  time:   [1.8638 us 1.9087 us 1.9560 us]
normal_index_scan_primary_key                        
                        time:   [2.7520 us 2.7852 us 2.8214 us]
```

See https://github.com/tikv/tikv/pull/3776 and https://github.com/tikv/tikv/pull/3814

**Comment by siddontang** [comment]
em, can we investigate why?

**Comment by Hijiao** [comment]
After carefully comparing the `table_scan_primary_key` and `normal_index_scan_primary_key`, I 
 found there are a little difference between the two.
In `normal_index_scan_primary_key`, the `foo` column will add one index 
```
  let foo = ColumnBuilder::new().col_type(TYPE_LONG).index_key(index_id).build(); 
```
but it will not in `table_scan_primary_key`.
```
  let foo = ColumnBuilder::new().col_type(TYPE_LONG).build();
```
After adding the index key in `table_scan_primary_key`, the cost improved 33.47% in my computer, from 
```
table_scan_primary_key  time:   [2.0632 us 2.1019 us 2.1422 us]
```
to 
```
table_scan_primary_key  time:   [2.7829 us 2.8412 us 2.9006 us]
                        change: [+30.166% +33.476% +36.853%] (p = 0.00 < 0.05)
```

**Comment by Hijiao** [comment]
In conclusion, IndexScanExecutor will not be slower than TableScanExecutor if they do the similar pre-action.

**Comment by Hijiao** [comment]
@breeswish I look through the `TableBuilder`, if column has `index`, then the length of `Table.idxs` would be double,  and the double items would be saved to storage when `Store::execute`, which will affect the `next` in a way.

**Comment by Hijiao** [comment]
In your scenario, 10 ids and 10 foos will be added to the storage. if id is primary key, the total entry will be 30. if foo has index too, then the total entry in storage will grow up to 40.

**Comment by breeswish** [comment]
@Hijiao I don't think double entries will cause double time cost, as BTreeMap's complexity is O(logN) 🤣 Needs more investigation.

**Comment by breeswish** [comment]
@Hijiao is right. I made entries double in `TableScanExecutor` and indeed it becomes slower. This case shows that when we write micro benchmarks, the trivial part of the layered foundation (i.e. the mock) can have notable impactions, since the benchmark itself is also small. This brings new challenges that we must not neglect.
