### ISSUE TITLE
Retry connecting to pd on startup

### ISSUE THREAD

**Issue by morgo** [tikv/tikv#3827]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently I use `sleep 5` in my script after starting pd, but before starting tikv.  i.e.
```
./bin/pd-server  --data-dir=pd --log-file=pd.log &
sleep 5
./bin/tikv-server --pd="127.0.0.1:2379" --data-dir=tikv -A 127.0.0.1:20165 --log-file=tikv.log &
sleep 5
./bin/tidb-server --store=tikv --path="127.0.0.1:2379"
```

**Describe the feature you'd like:**

It would be nice if `tikv-server` retried connecting to the `pd-server` in a loop.  After ~10 seconds of not being able to connect, it can exit with an error.

A similar feature request for the `tidb-server` is here: https://github.com/pingcap/tidb/issues/1620

**Describe alternatives you've considered:**

The current solution does work.  I feel it puts some burden on users though, for a simple troubleshooting use case.

**Teachability, Documentation, Adoption, Migration Strategy:**

Only requires minimal docs.

**Comment by siddontang** [comment]
PTAL @nolouch
