### ISSUE TITLE
test_node_split_brain failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#3831]
## Bug Report

https://circleci.com/gh/tikv/tikv/14974

**Comment by BusyJay** [comment]
Any updates on this issue?

**Comment by overvenus** [comment]
Another failed test, https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/8350/nodes/132/steps/1180/log/?start=0

[internal.pingcap.net.txt](https://github.com/tikv/tikv/files/3553879/internal.pingcap.net.txt)

**Comment by overvenus** [comment]
Can not reproduce on master branch (tested 2077 times), closed. Feel free to reopen if it occurs again.
