### ISSUE TITLE
Cargo update failed due to not finding of raft:0.3.1

### ISSUE THREAD

**Issue by AbnerZheng** [tikv/tikv#3836]
## Question
After cloning the Tikv project, I run the command 'cargo update', but failed. The failed message is: 

> error: no matching package for override `https://github.com/rust-lang/crates.io-index#raft:0.3.1` found                                                                                                                            
> location searched: https://github.com/pingcap/raft-rs.git
> version required: = 0.3.1

My Environment:
OS: MAC OS 10.14.1
cargo version: cargo 1.29.0-nightly (af9e40c26 2018-07-05)
rustup version: rustup 1.14.0 (1e51b07cc 2018-10-04)
rustc version: rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**Comment by siddontang** [comment]
oh, PTAL @Hoverbear

**Comment by Hoverbear** [comment]
Blocked by https://github.com/pingcap/kvproto/pull/296

**Comment by ice1000** [comment]
@Hoverbear pingcap/kvproto#296 is merged, any updates?
