### ISSUE TITLE
max block cache metrics shows uncorrectly

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#3862]
## Bug Report

![image](https://user-images.githubusercontent.com/1080370/49232069-38000b00-f42e-11e8-8c2f-58db7697f3ed.png)

A user uses different block cache for TiKVs, e.g. for one TiKV, he sets 23 GB for write, but another is less than 15 GB(maybe), but for the metric, we can see the max cache is just 13.8 GB. I can ensure that the all TiKV servers use whole cache.

I think we need to adjust metrics if TiKV has different configs.

**Comment by BusyJay** [comment]
We now share cache between cf and db.
