### ISSUE TITLE
replace rust-crypto with ring

### ISSUE THREAD

**Issue by niedhui** [tikv/tikv#3875]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`rust-crypto` hasn't been updated for couple of years. I think  https://github.com/briansmith/ring is a better option.
Currently, it was only used in the `builtin_encryptions.rs` for `md5`, `sha1` and `sha2` implementations .

**Comment by breeswish** [comment]
I agree with this proposal. In addition, Ring has been used in rustls so that it seems to be promising.

**Comment by breeswish** [comment]
Marking this issue as help-wanted so that others can start to work on it.

**Comment by niedhui** [comment]
thanks  , I'll implement this

**Comment by ice1000** [comment]
DateHub

**Comment by niedhui** [comment]
@breeswish 
after quick research , I found here some issues with using `ring` in `TiKV` 
for digest, it drop support for `MD5` and and sha224( https://github.com/briansmith/ring/issues/438)
for aes/des, it seems only support GCM mode. 🤣 
so maybe we should use some small crates( [sha-1](https://crates.io/crates/sha-1), [sha2](https://crates.io/crates/sha2), [md-5](https://crates.io/crates/md-5), [aes](https://crates.io/crates/aes), [des](https://crates.io/crates/des) ) of [RustCrypto](https://github.com/RustCrypto)

**Comment by niedhui** [comment]
BTW, looking forward to seeing you @breeswish , in shanghai. next week ?

**Comment by breeswish** [comment]
Oh, that's bad news 🤣I also found out "use at your own risk" in Rust Crypto README. Considering security, maybe we should use rust-openssl instead?

**Comment by breeswish** [comment]
@niedhui That's ok! You can contact me privately through email :P

**Comment by niedhui** [comment]
using `rust-openssl ` failed.  crate `grpcio` links BoringSSL, which is incompatible with OpenSSL.  https://github.com/sfackler/rust-openssl/issues/765

**Comment by breeswish** [comment]
@overvenus Would you like to take a look and give help? grpcio 0.4 has already landed master but PRs are failing.

**Comment by BusyJay** [comment]
I suggest to combine ring with rust-crypto, to make things simple and somewhat more secure, as openssl is not as secure as it seems, which is the exact reason why boringssl is implemented.

**Comment by niedhui** [comment]
IMHO, `ring` is really not a good option for our situation .  as I metioned before: 
1. for AES/DES, it only support GCM mode for now,  and we do not need this mode
2. for degest, it does not support `MD5` and `sha224`
3. as a result, if we choose `ring`, we can only use it for some `SHA` and `rand` funcitons

`boringSSL` is truely more secure than `openSSL`, but if we want to  be compatible with `MySQL`, it's a tradeoff.   what's you opinion,   @BusyJay

**Comment by BusyJay** [comment]
Alright, seems there is a missing crate.

**Comment by briansmith** [comment]
> @breeswish
> for digest, it drop support for `MD5` and and sha224

Why do you need MD5 and SHA-224? SHA-224 isn't horrible but MD5 is useless as a security mechanism now; see https://github.com/corkami/pocs/tree/master/collisions. If you have the ability to remove MD5 support from your product, I recommend doing so. Almost nobody uses SHA-224 so I would suggest dropping it, if possible.

> for aes/des, it seems only support GCM mode. 🤣

Which modes do you need?

**Comment by niedhui** [comment]
@briansmith it's all about to be compatible with with MySQL 😞

**Comment by breeswish** [comment]
That's true sadly @briansmith We need to support it as long as MySQL supports it.

**Comment by iosmanthus** [comment]
> > @breeswish
> > for digest, it drop support for `MD5` and and sha224
> 
> Why do you need MD5 and SHA-224? SHA-224 isn't horrible but MD5 is useless as a security mechanism now; see https://github.com/corkami/pocs/tree/master/collisions. If you have the ability to remove MD5 support from your product, I recommend doing so. Almost nobody uses SHA-224 so I would suggest dropping it, if possible.
> 
> > for aes/des, it seems only support GCM mode. rofl
> 
> Which modes do you need?

By default, MySQL's  [`aes_encrypt`](https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_aes-encrypt) apply ECB mode, but it can be configed by env variable [block_encryption_mode](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_block_encryption_mode)

**Comment by kennytm** [comment]
We could use the `md5` package in additional to `ring` for `MD5()` support.

**Comment by iosmanthus** [comment]
If we want to add function `aes_encrypt/aes_decrypt`, maybe we have to keep `rust-crypto` and add [`stream-ciphers`](https://github.com/RustCrypto/stream-ciphers) because MySQL's `block_encryption_mode` supports: `ECB, CBC, CFB1, CFB8, CFB128, OFB`

**Comment by niedhui** [comment]
I'm going close this issue, since #3886 has been merged
