### ISSUE TITLE
Extract a new component for common dependencies

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#3887]
There are some crates that are dependented by multiple components, eg, both `tikv`, `test_coprocessor`, `test_storage` and `test_raftstore` depends on `kvproto`, as a result, when we upgrade or test another branch of `kvproto`, we have to change theirs `Cargo.toml`s. It would be convenient to upgrade or test new branch if we add a new component which exports `kvproto` and any other components depend on it.

**Comment by breeswish** [comment]
Maybe it can be just placed inside components!
