### ISSUE TITLE
Upgrade to Rust 2018

### ISSUE THREAD

**Issue by brson** [tikv/tikv#3896]
Upgrade TiKV to a recent nightly, then upgrade it to Rust 2018 edition. Upgrade dependencies as necessary.

**Comment by ice1000** [comment]
Related: pingcap/grpc-rs#256

**Comment by brson** [comment]
I think turning on Rust 2018 requires a major version bump because using any 2018 features breaks backwards compatibility. Does anybody have opinions or has seen any discussion on this subject?

**Comment by brson** [comment]
I've landed the jemalloc changes and am now focused on upgrading the toolchain without yet turning on Rust 2018. The current problem I'm running into is that both fuzzers break with the upgraded toolchain, so that's the next problem to tackle.

**Comment by brson** [comment]
The libfuzzer breakage is caused by https://github.com/rust-lang/rust/issues/53945

**Comment by brson** [comment]
This is dragging on. The latest problem is that [benchmarks of the new toolchain](https://github.com/tikv/tikv/pull/4000#issuecomment-452201222) show a number of bad regressions. One obvious culprit I overlooked is that most of our benchmark crates don't link to jemalloc. So I'm fixing that now in

**Comment by brson** [comment]
The toolchain upgrade PR is ready to merge: https://github.com/tikv/tikv/pull/4000

Next step is to redo the 2018 upgrade from scratch (my current branch is way out of date).
