### ISSUE TITLE
TiKV go client txn API encounter go build error

### ISSUE THREAD

**Issue by alexweili** [tikv/tikv#3900]
I encountered the same issue solved in
https://github.com/tikv/tikv/issues/3828

After following the fix, I can build and run the first example of Raw Key/Value API.

Still, I still have issues on the Transaction API:
```
$ go build txn_api.go 
go: finding github.com/pingcap/pd/pd-client latest
../../go/pkg/mod/github.com/pingcap/tidb@v2.0.9+incompatible/store/tikv/kv.go:28:2: unknown import path "github.com/pingcap/pd/pd-client": cannot find module providing package github.com/pingcap/pd/pd-client
```

This issue also happens in master when I try to use tikv API.

**Comment by alexweili** [comment]
BTW, `txn_api.go` is mostly the example in https://github.com/pingcap/docs/blob/master/tikv/go-client-api.md#try-the-transactional-key-value-api

Thanks,

**Comment by overvenus** [comment]
Looks like something went wrong with the pd client. PTAL @disksing @nolouch

**Comment by disksing** [comment]
Hi, looks like you are using tidb of v2.0.9 and pd with master branch. Please try to use master tidb explicitly:
```
GO111MODULE=on go get -u github.com/pingcap/tidb@master
```

**Comment by alexweili** [comment]
Yes, this worked, thanks!
