### ISSUE TITLE
TiKV Rust/C++ client

### ISSUE THREAD

**Issue by Tachone** [tikv/tikv#3919]
How long will the tikv rust client(with c wrapper) or c++ client be published?
I think it is neccessary, because there are so many projects based on c/c++, do you have a timetable?

**Comment by siddontang** [comment]
Hi @Tachone 

We have no clear plan for the c++ client now, may start this work after finishing Rust client. 

For the Rust client, maybe the first version is in Jan next year.

**Comment by siddontang** [comment]
We very hope that someone can help us add the C++ client :-)

**Comment by Tachone** [comment]
I am trying to do this, but it is not a easy work...
