### ISSUE TITLE
BatchGet/Put in TiKV client?

### ISSUE THREAD

**Issue by zjut-Tach** [tikv/tikv#3935]
Is BatchGet/Put  an atomic api?
* If the answer is yes, how can it be implemented by not using translation？
* If the answer is no,  the only way to do atomic batch operation is  using tnx.begin().. tnx.end()?

**Comment by siddontang** [comment]
@zjut-Tach 

If you want to use Raw API and all the keys in one batch belong to one region, your operation is atomic.

**Comment by Hoverbear** [comment]
Seems this question is answered! Closing.
