### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by mateng0915** [tikv/tikv#3947]
## Machine info:
5 machine all ssd 64 core/ 256GB 
## TiDB Version 
release 2.1 ( the official website recommend)

## Bug description:
 Using 20 threads to insert 1TB data to TiKV, when almost finished, it will raise the error Lost connection to MySQL server during query
 2018-12-16 08:30:38 start to insert data
 2018-12-18 04:10:55 RROR 2013 (HY000) at line 117: Lost connection to MySQL server during query
2018-12-18 04:23:53 stop to insert data

## Exception Logs
![image](https://user-images.githubusercontent.com/26053753/50134972-71a99080-02cd-11e9-9b82-8ded209489a4.png)

![image](https://user-images.githubusercontent.com/26053753/50134986-8128d980-02cd-11e9-87fe-aecfc6f7fa90.png)

0:10:55.213 region_cache.go:482: [info] drop regions that on the store 1(192.168.3.246:20160) due to send request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded

/home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleCopResponse

/home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace

**Comment by siddontang** [comment]
can you provide the TiKV logs and metrics?

**Comment by siddontang** [comment]
PTAL @hicqu

**Comment by hicqu** [comment]
What client do you use to insert data, sysbench or YCSB? And is there any batch strategy when inserting?

**Comment by Hoverbear** [comment]
Closing this issue as we're not getting any feedback.
