### ISSUE TITLE
copr/codec/mysql/time: invalid_zero function isn't working as expected.

### ISSUE THREAD

**Issue by koushiro** [tikv/tikv#3953]
## Bug Report

**What version of Rust are you using?**
rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**What operating system and CPU are you using?**
OS: Arch Linux 
Kernel: x86_64 Linux 4.19.8-arch1-1-ARCH
CPU: Intel Core i7-8650U @ 8x 4.2GHz

**What did you do?**

```rust
/// In go, time.Date(0, 0, 0, 0, 0, 0, 0, time.UTC) will be adjusted to
/// -0001-11-30 00:00:00 +0000 UTC, whose timestamp is -62169984000.
const ZERO_TIMESTAMP: i64 = -62169984000;

#[inline]
fn zero_time(tz: Tz) -> DateTime<Tz> {
    tz.timestamp(ZERO_TIMESTAMP, 0)
}

#[inline]
pub fn zero_datetime(tz: Tz) -> Time {
    Time::new(zero_time(tz), TimeType::DateTime, mysql::DEFAULT_FSP).unwrap()
}

#[derive(Clone, Debug)]
pub struct Time {
    // TimeZone should be loaded from request context.
    time: DateTime<Tz>,
    time_type: TimeType,
    fsp: u8,
}

impl Time {
    fn parse_datetime_internal(s: &str, fsp: i8, tz: Tz, is_float: bool) -> Result<Time> {
        ...
        if year == 0 && month == 0 && day == 0 && hour == 0 && minute == 0 && sec == 0 {
                println!("zero time: {:?}", zero_datetime(tz));
                return Ok(zero_datetime(tz));
        }
        ...
    }

    pub fn parse_datetime(s: &str, fsp: i8, tz: Tz) -> Result<Time> {
        Time::parse_datetime_internal(s, fsp, tz, false)
    }

    pub fn parse_utc_datetime(s: &str, fsp: i8) -> Result<Time> {
        Time::parse_datetime(s, fsp, Tz::utc())
    }

    pub fn invalid_zero(&self) -> bool {
        self.time.month() == 0 || self.time.day() == 0
    }
}
```

When I call `let t = Time::parse_utc_datetime("0000-00-00", 0).unwrap();`, it will return  `zero_datetime(Tz::utc())`.
In function `invalid_zero`, `self.time.month()` and `self.time.day()` are 11 and 30 respectively, so `t.invalid_zero()` will be false instead of true as I expected.

**Comment by huachaohuang** [comment]
Sorry, I don't think I understand the problem, can you give a snippet to demonstrate the problem?

**Comment by koushiro** [comment]
```rust
#[test]
fn test_time_is_invalid_zero() {
    let t = Time::parse_utc_datetime("0000-00-00", 0).unwrap();
    // I think the result of t.invalid_zero() should be true.
    assert_eq!(t.invalid_zero(), false); 
}
```
Add the above test case to the coprocessor/codec/mysql/time/mod.rs and then run the command:
`cargo test coprocessor::codec::mysql::time::tests::test_invalid_zero`

**Comment by huachaohuang** [comment]
Oh, interesting, would you like to help to debug it?

**Comment by koushiro** [comment]
```rust
/// In go, time.Date(0, 0, 0, 0, 0, 0, 0, time.UTC) will be adjusted to
/// -0001-11-30 00:00:00 +0000 UTC, whose timestamp is -62169984000.
const ZERO_TIMESTAMP: i64 = -62169984000;

fn parse_datetime_internal(s: &str, fsp: i8, tz: Tz, is_float: bool) -> Result<Time> {
    ...
    if year == 0 && month == 0 && day == 0 && hour == 0 && minute == 0 && sec == 0 {
        println!("zero time: {:?}", zero_datetime(tz));
        return Ok(zero_datetime(tz));
    }
    ...
}
```
When the `parse_utc_datetime('0000-00-00', 6)` is called, 
because of the value of `ZERO_TIMESTEAMP`, 
`Time.DateTime` will be `-0001-11-30T00:00:00NonFixed(UTC)`, 
so that `Time.Datetime.month()` is equals to `11` and `Time.Datetime.day()` is equals to `30`.

`crate chrono` does not seem to construct of a Datetime structure with a month and day value of ZERO, so **I don't have a good idea.**

Maybe add a flag into Time structure when the result of parsing month or parsing day is ZERO?（only in the case that the the result of parsing datetime is all ZEROs）, just like

```rust
#[derive(Clone, Debug)]
pub struct Time {
    // TimeZone should be loaded from request context.
    time: DateTime<Tz>,
    time_type: TimeType,
    fsp: u8,
    invalid_zero: bool,  // true when the value of month or day is ZERO.
}

fn parse_datetime_internal(s: &str, fsp: i8, tz: Tz, is_float: bool) -> Result<Time> {
    ...
    if month == 0 || day == 0 {
        self.invalid_zero = true;
    }
    if year == 0 && month == 0 && day == 0 && hour == 0 && minute == 0 && sec == 0 {
        println!("zero time: {:?}", zero_datetime(tz));
        return Ok(zero_datetime(tz));
    }
    ...
}

pub fn invalid_zero(&self) -> bool {
    self.invalid_zero
}
```

Does anybody else has a good idea or has a solution on this problem?

BTW, why using timestamp of time.Date(0, 0, 0, 0, 0, 0, 0, time.UTC) in golang as ZERO_TIMESTAMP in Tikv？For consistency?

**Comment by huachaohuang** [comment]
@koushiro Thanks for your effort, @breeswish PTAL.

**Comment by breeswish** [comment]
@koushiro Thanks for your report. This is a known issue that TiKV Coprocessor does not support zero month or day (totally). It's fine to just keep the current behaviour, but will be great if we can fix it! Currently, we don't have plans to fix it yet. Maybe we need to introduce the time wrapper as TiDB does.

**Comment by iosmanthus** [comment]
Will be fixed in https://github.com/tikv/tikv/pull/5473
