### ISSUE TITLE
proposal: consider removing single scheduler worker

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#3968]
## Feature Request

I have been thinking this (removing the single scheduler worker) for a long time. Now, if we want to execute a transaction write command like Prewrite or Commit, the flow is:

1. The gRPC thread receives the command
2. gRPC thread sends this command to the Scheduler thread
3. The Scheduler thread appends this command to the latches. 
4. If the command acquires all the locks, the Scheduler thread will send a message to the local read thread to get a snapshot.
5. The local read thread will send the snapshot and corresponding context to the worker pool.
6. When the worker pool executes the command, it will send the message to the raftstore thread and enter Raft flow. 
7. After the Raft flow is finished, the corresponding callback function is called, which will send a message to the Scheduler thread.
8. The Scheduler thread releases the lock which the command holds and sends a response message to the gRPC thread.
9 The gRPC thread replies to the client. 

As you can see, we have many thread interaction for one command, if we can reduce this, we can reduce the context switch and of course reduce the latency. 

The Scheduler is a single thread which can't be scaled, although it can't become the bottleneck of the whole system, I still want to remove it. The main thought is to use a global thread-safe Latch which all the threads can operate it. 

It may be easy, because now if a command wants to acquire the lock, it must sort the keys and acquire the key lock orderly, vice versa. So we can use something like `Arc<Vec<Mutex<Deque>>>` for the latch, the Latch vector is fixed so it is thread-safe. So now the gRPC thread can operate the Latch directly, and when the command is applied, the Raft apply thread can operate the Latch too. 

This can remove the Scheduler thread and remove at least two thread interaction: 

1. gRPC -> Scheduler, Scheduler -> Local read => gRPC -> Local read. 
2. Apply thread -> Scheduler, Scheduelr -> gRPC => Apply thread -> gRPC.

I just write a simple code to check whether it can work or not. https://github.com/siddontang/tikv/tree/siddontang/no-scheduler, for simplify, I still keep the tasks and task contexts hash map (I use a `Vec<Mutex<HashMap>>` with 1024 size to reduce lock contention, but I think it is better to append the Task to the Latch queue directly, not any HashMap). 

In my computer, I just start 1 PD and 1 TiKV, use go-ycsb `go-ycsb run tikv -P workloads/workloada -p tikv.type=txn` with following workload:

```
recordcount=1000000
operationcount=1000000
workload=core
readallfields=true
readproportion=0
updateproportion=0
scanproportion=0
insertproportion=1
requestdistribution=uniform
```

The results are:

```
// master ee39d52d8e1bb2007632220a8c89f2092d3fa239
INSERT - Takes(s): 9.9, Count: 47889, OPS: 4832.8, Avg(us): 20786, Min(us): 7628, Max(us): 139276, 95th(us): 41000, 99th(us): 78000
INSERT - Takes(s): 19.9, Count: 103030, OPS: 5174.6, Avg(us): 19344, Min(us): 7199, Max(us): 139276, 95th(us): 37000, 99th(us): 65000
INSERT - Takes(s): 29.9, Count: 149507, OPS: 4998.7, Avg(us): 20001, Min(us): 7029, Max(us): 220657, 95th(us): 39000, 99th(us): 65000

// remove scheduler 
INSERT - Takes(s): 9.9, Count: 61291, OPS: 6179.4, Avg(us): 16219, Min(us): 5266, Max(us): 90647, 95th(us): 30000, 99th(us): 43000
INSERT - Takes(s): 19.9, Count: 116927, OPS: 5870.0, Avg(us): 17043, Min(us): 5265, Max(us): 234391, 95th(us): 32000, 99th(us): 48000
INSERT - Takes(s): 29.9, Count: 170173, OPS: 5687.3, Avg(us): 17566, Min(us): 5004, Max(us): 270553, 95th(us): 33000, 99th(us): 52000
```

As you can see, the performance is better. we need to do more tests later.
 
Of course, removing Scheduler thread can increase the pressure for gRPC and Apply thread, because now they need to care how to operate the Latch, but gRPC and Apply can scale, so it may be not a problem later. 
For better performance, we may use a lock-free deque for Latch, but it is hard to write correctly. 

I think it is worth to try. 

/cc @zhangjinpeng1987 @overvenus @breeswish

**Comment by overvenus** [comment]
Fixed in #4098
