### ISSUE TITLE
How to reduce request wait duration

### ISSUE THREAD

**Issue by Xavier1994** [tikv/tikv#3976]
## Question

I have a pure read workload on TiKV(guarantee all data fit in block cache, and read cache hit is 100%), I find my latency is influenced by request wait time(which is the time mio's sender send RaftCmd to event loop). And my three tikv instances's metric about request wait time is different

<img width="508" alt="2018-12-25 9 30 23" src="https://user-images.githubusercontent.com/11145343/50423141-6980c080-088c-11e9-878a-62088be4e1e6.png">
<img width="491" alt="2018-12-25 9 30 38" src="https://user-images.githubusercontent.com/11145343/50423142-6a195700-088c-11e9-97cc-f92517579016.png">
<img width="514" alt="2018-12-25 9 30 52" src="https://user-images.githubusercontent.com/11145343/50423143-6a195700-088c-11e9-8fdb-d650b8cd132f.png">

two of them is about 0.5ms, but one is 8ms, So I'm wondering what factors can influence this metric and how can i reduce the request wait time

Deploy
3 * TiKV, PD * 1, Version 2.1, 16C32G

**Comment by siddontang** [comment]
@Xavier1994 

How many regions do you have ? Can you generate the metrics report and send to us? 

PTAL @Connor1996

**Comment by Xavier1994** [comment]
@siddontang region's number is 580, and 15W read QPS, I will send metric report to you

**Comment by Connor1996** [comment]
@Xavier1994 you can just send the report to me (zhangbokang at pingcap.com)
