### ISSUE TITLE
Replace trait `Factory` with closure

### ISSUE THREAD

**Issue by Fullstop000** [tikv/tikv#3988]
I noticed the `TODO` below
https://github.com/tikv/tikv/blob/72bf02f8a71fef7d66c69deb1f9e0b25ba49a9ee/src/server/readpool/mod.rs#L56-L58
Maybe now we can replace the trait `Factory` with closure since RFC-2132 is completed.

https://github.com/rust-lang/rfcs/pull/2132
https://github.com/rust-lang/rust/issues/44490

**Comment by siddontang** [comment]
Cool @Fullstop000 

Please do it. But do we need to upgrade to Rust 2018 at first?

**Comment by Fullstop000** [comment]
@siddontang `Copy/Clone closure` is stabilized since 1.26 so I believe it should work without Rust 2018.
