### ISSUE TITLE
How many rows can be put in a single transaction?

### ISSUE THREAD

**Issue by bcstyle** [tikv/tikv#3992]
Apologize if this has already been addressed in documentation that I missed. I'm wondering how many rows can theoretically be put in a single transaction? Any benchmark on this? Thank you.

**Comment by siddontang** [comment]
Hi @bcstyle 

Using batch has better performance, but if the batch size is too large, it may be conflicted with other transaction and the rollback will cause the performance reduction too much. 

You can try using batch in your own workload, use different batch and choose which is the better one.

**Comment by Hoverbear** [comment]
Seems this question is answered. I'll close this!
