### ISSUE TITLE
Does new titan engine compatiable with old rocksdb engine?

### ISSUE THREAD

**Issue by fredchenbj** [tikv/tikv#4001]
## Question

Before asking a question, make sure you have:

Does new titan engine compatiable with old rocksdb engine in TiKV? Could I use the new titan-version tikv-server to rolling update existing clusters and not do harm to the existing data?

**Comment by fredchenbj** [comment]
Thanks @DorianZheng, we want to test this Titan-base version and to use it in product environment ASAP,  thus reduce the Write Amplification. If have any problem or question, we would like to give issues in community.

**Comment by DorianZheng** [comment]
@fredchenbj We will not recommend you to use it in product environment until we merge it to release branch because it's still a beta version now, but you could do some benchmark and test on it first.

**Comment by fredchenbj** [comment]
@DorianZheng OK, we will do more test and benchmark, and wait for the release version to use in product environment. Thanks.

**Comment by DorianZheng** [comment]
#4002 Since this PR is already merge, I will close this issue. If you have any question about `Titan`, it's very welcome to file an issue🤗
