### ISSUE TITLE
How to choose the value for max-merge-region-keys and max-merge-region-size to enable region merge?

### ISSUE THREAD

**Issue by darren** [tikv/tikv#4012]
## Question

In our TiDB cluster, we have 319736 (x 5) regions now, we use replication factor of 5. We are considering enable region merge. [pd-scheduler-config.md ](https://github.com/tikv/tikv/blob/master/docs/op-guide/pd-scheduler-config.md) mentions region merge. merge is not enabled by default. 

So my questions are:
1. Is region merge stable enough to be used in production?
2. How to choose the best value for max-merge-region-keys and max-merge-region-size?
3. Are there any side effects if region merge is enabled?  eg: region balance overhead in case of tikv node failure.

Thanks!

**Comment by siddontang** [comment]
PTAL @Connor1996

**Comment by Connor1996** [comment]
1. not stable yet, and it will be stable in next release version 3.0 if everything as expected. If it doesn't hurt your performance badly, we are not recemmend you to enable it in production.
2. there is a default value for master branch, you can refer it
```
max-merge-region-size = 20
max-merge-region-keys = 200000
```
3. No

**Comment by darren** [comment]
Thanks!
