### ISSUE TITLE
test_node_merge_multiple_snapshots_together failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4026]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/734/nodes/100/steps/394/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/735/nodes/106/steps/539/log/?start=0

**Comment by Connor1996** [comment]
Duplicated with https://github.com/tikv/tikv/issues/7351
