### ISSUE TITLE
Support adjusting log level dynamically through HTTP API

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4033]
## Feature Request

Now we have TiKV HTTP API port. We can add an interface to it to adjust log level dynamically.

**Comment by TennyZhuang** [comment]
It seems that it's not reasonable to add a POST API in status_server, maybe we need some router and split different HTTP request to different handler.

**Comment by breeswish** [comment]
Or maybe we can just rename status_server to a broader name so that it can handle more tasks.
