### ISSUE TITLE
Stash MsgTimeout to fix transfer leader bug

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#4045]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now, TiKV cluster adds node in two stages, a leader first adds a learner, after the learner catches up, the leader promtes the learner as a voter(node). However, there is a small gap between the leader and the learner that the leader thinks the learner has become a voter while the learner does apply `AddNode` yet. During the gap, the leader may transfter leadership to the the learner and the learner rejects `MsgTimeout`, this will cause the leader stops serving read requests about 10 seconds (an election timeout). 

**Describe the feature you'd like:**

Stash `MsgTimeout` in learner, so a learner can start election once it becomes a voter.

**Describe alternatives you've considered:**

Apply conf change when the learner receives the conf change command. Cc https://github.com/pingcap/raft-rs/issues/144

**Comment by Fullstop000** [comment]
I notice that https://github.com/tikv/tikv/pull/3878 introduces a mechanism that if we promotes a peer from `Learner` to `Node` recently (default 3 sec),  leadership transfer propose will be rejected without retrying .
Maybe 3878 is try to resolve the issue you mention here ?

**Comment by overvenus** [comment]
#3878 partially resolves the issue, let's say there is a learner runs slowly and applies `AddNode` after 4 seconds later, its leader sends a `MsgTimeout` between 3~4s, then there will be about 6 seconds that the region does not serve read requests.

**Comment by BusyJay** [comment]
Fixed by #6539.
