### ISSUE TITLE
raft lib bug: In handle_heartbeat_response, the leader will lose the reply request of readindex

### ISSUE THREAD

**Issue by zhongleihe** [tikv/tikv#4071]
`  fn handle_heartbeat_response(
        &mut self,
        m: &Message,
        prs: &mut ProgressSet,
        send_append: &mut bool,
        more_to_send: &mut Option<Message>,
    ) {
        // Update the node. Drop the value explicitly since we'll check the qourum after.
        {
            let pr = prs.get_mut(m.get_from()).unwrap();
            pr.recent_active = true;
            pr.resume();

            // free one slot for the full inflights window to allow progress.
            if pr.state == ProgressState::Replicate && pr.ins.full() {
                pr.ins.free_first_one();
            }
            if pr.matched < self.raft_log.last_index() {
                *send_append = true;
            }

            if self.read_only.option != ReadOnlyOption::Safe || m.get_context().is_empty() {
                return;
            }
        }

        if !prs.has_quorum(&self.read_only.recv_ack(m)) {
            return;
        }

        let rss = self.read_only.advance(m);
        for rs in rss {
            let mut req = rs.req;
            if req.get_from() == INVALID_ID || req.get_from() == self.id {
                // from local member
                let rs = ReadState {
                    index: rs.index,
                    request_ctx: req.take_entries()[0].take_data(),
                };
                self.read_states.push(rs);
            } else {
              /*
Each loop overrides to_send , but readindex req may come from a different slave. Causes some slaves to accept no return request.*/
                let mut to_send = Message::new()
                to_send.set_to(req.get_from());
                to_send.set_msg_type(MessageType::MsgReadIndexResp);
                to_send.set_index(rs.index);
                to_send.set_entries(req.take_entries());
                *more_to_send = Some(to_send);
            }
        }
    }
`

Each loop overrides "to_send" , but readindex req may come from a different slave. Causes some slaves to accept no return request.

**Comment by rleungx** [comment]
@zhongleihe Thanks for your feedback!
Could you please follow our template to edit your issue? It's not quite straightforward to figure out what is your question.

**Comment by Fullstop000** [comment]
It seems that we only send the last `ReadIndexStatus` and drop the previous reading requests if using `ReadOnlyOption::Safe`
```rust
        for rs in rss {
            let mut req = rs.req;
            if req.get_from() == INVALID_ID || req.get_from() == self.id {
                // from local member
                // ...
            } else {
                let mut to_send = Message::new();
                to_send.set_to(req.get_from());
                to_send.set_msg_type(MessageType::MsgReadIndexResp);
                to_send.set_index(rs.index);
                to_send.set_entries(req.take_entries());
                // only send the last one here
                *more_to_send = Some(to_send);
            }
        }
```
I thinks this is a critical issue but does tikv just use lease read ? @rleungx

**Comment by BusyJay** [comment]
This can become a problem when implementing follower read. /cc @nolouch
