### ISSUE TITLE
server::load_statistics::linux::tests::test_thread_load_statistic fails unexpectedly

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4103]
As stated in title. I've seen this fail recently. No further info.

**Comment by brson** [comment]
I am still seeing this locally.

**Comment by brson** [comment]
I think asserting that the load is > %80 is not reasonable on a machine where other processes might be running (like they are on my local machine). I'd suggest just asserting that there is > 0 load is the best that can be done here, at least without asking the scheduler give the scheduler some kind of high priority.

**Comment by hicqu** [comment]
Seems the case didn't fail for some days. So let's keep it now? In my opinion 80% is more strong to say our algorithm to calculate the load is correct.
