### ISSUE TITLE
typos in src/server/debug.rs

### ISSUE THREAD

**Issue by fredchenbj** [tikv/tikv#4109]
## Bug Report

`fn compact` in "src/server/debug.rs" have two places of log `info!` with typos `manual comapct` , it would be hard to find manual compact message in tikv logs.

**Comment by BusyJay** [comment]
Thanks for your report, nice catch! Would you like to help us to correct them?

**Comment by fredchenbj** [comment]
@BusyJay OK, I would correct it.
