### ISSUE TITLE
Consider ThinLTO vs LTO vs no LTO with respect to compile time and runtime performance

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4163]
Right now we have full LTO on for the 'release' profile, and LTO off for the 'bench' profile. Full LTO makes a lot of sense for published builds, because it is the most effective, and the slowest, but for local testing probably not, either ThinLTO or no LTO is probably sufficient for many cases.

I believe with the current config that our benches are both using incremental compilation and no LTO at all, which is a somewhat strange combination, particularly for benchmarking.

Investigate whether the dev profile is using any type of LTO.

**Comment by brson** [comment]
ThinLTO has some performance sacrifices, https://github.com/rust-lang/rust/issues/47745 among others.

**Comment by brson** [comment]
[These scripts](https://gist.github.com/brson/881717fc59c12465b35577fc59eb98b3) can be used to compare all the tikv benchmarks before and after LTO adjustments.

**Comment by brson** [comment]
debuginfo, panic=unwind, codegen-units=1, non-incremental, thin lto:

real    9m57.195s
user    22m48.391s
sys     0m22.081s

----

So that's all very encouraging. Next step is to do runtime
benchmarking of these configurations to see what the impact is.

**Comment by brson** [comment]
Here's some runtime benchmarking.

command: `cargo clean && cargo bench --no-run && time cargo bench`
toolchain: rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)
platform: Linux

debug=true, panic=unwind, codegen-units=1, incremental=false, **lto=true**:

real    33m39.746s
user    21m38.901s
sys     3m41.782s

debug=true, panic=unwind, codegen-units=1, incremental=false, **lto=thin**:

real    32m54.446s
user    20m44.634s
sys     3m53.565s

The full runtime of the benchmarks is consistent between LTO styles.

Individual benchnmarks: https://gist.github.com/brson/d4f5f6d97c0abd24aa000e0daf66f559

Notice that there are unpredictable variations in the benchmarks
using the stock runner, but the criterion benchmarks are all steady.

I'm not sure what to make of that.

**Comment by brson** [comment]
I think this is sufficiently considered.

Thin LTO is much faster than full LTO, changes individual benchmark performance in the unpredictable ways LTO does. Surprisingly, it may increase overall performance, per my testing.

I will propose using thin LTO everywhere except for the production builds.

**Comment by siddontang** [comment]
> Surprisingly, it may increase overall performance

Oh, strange, can we use it in production?

**Comment by brson** [comment]
@siddontang Looking back through my notes I can't find anything that supports the statement "may increase overall performance". I suspect what I meant to say was "my decrease full rebuild time", since I would expect the extra incremental bookkeeping to increase full rebuild time.

So the answer to your question is no.

Here are the results suggesting a decrease in full rebuild time:

command: time cargo bench --no-run
toolchain: rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)
platform: Linux
commit-base: 970c1c8eb49a16864540a4ac3a45030992943fc3

debug=false, panic=unwind, opt-level=3, codegen-units=1, incremental=false, lto="thin":

real    32m25.529s
user    89m29.843s
sys     2m38.158s

debug=false, panic=unwind, opt-level=3, codegen-units=1, **incremental=true**, lto="thin":

real    31m31.788s
user    91m57.819s
sys     2m39.051s

surprising result: incremental makes the build faster? maybe through parallelism

---

command: cargo bench --no-run && time cargo bench
toolchain: rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)
platform: Linux
commit-base: 970c1c8eb49a16864540a4ac3a45030992943fc3

debug=false, panic=unwind, opt-level=3, codegen-units=1, incremental=false, lto="thin":

real    32m52.245s
user    21m0.920s
sys     3m42.073s

debug=false, panic=unwind, opt-level=3, codegen-units=1, **incremental=true**, lto="thin":

real    33m28.512s
user    21m24.646s
sys     3m50.110s

**Comment by brson** [comment]
@siddontang here's the result that showed an increase in perf with thinlto:

```
command: `cargo clean && cargo bench --no-run && time cargo bench`
toolchain: rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)
platform: Linux

debug=true, panic=unwind, codegen-units=1, incremental=false, **lto=true**:

real    33m39.746s
user    21m38.901s
sys     3m41.782s

debug=true, panic=unwind, codegen-units=1, incremental=false, **lto=thin**:

real    32m54.446s
user    20m44.634s
sys     3m53.565s
```

Those results were accompanied by these complete bench results: https://gist.github.com/brson/d4f5f6d97c0abd24aa000e0daf66f559

In this test the overall time decreased slightly by using thin lto instead of lto, while individual benchmarks changed unpredictably.

I'd want to do more tests before assuming the results are valid.

**Comment by brson** [comment]
My current plan is to use thinlto for the release profile, and full lto for publication.

**Comment by brson** [comment]
This will be complete once https://github.com/tikv/tikv/pull/4996 lands.

**Comment by brson** [comment]
Done!
