### ISSUE TITLE
Break TiKV up into multiple dependencies

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4165]
The less code in TiKV the less compilation must be done when it changes. There are probably modules yet that can be pulled out into the components directory. Crates that add more parallelism are best, but ones that don't _might_ be useful - depends on how the resulting full-rebuild and partial-rebuild times end up.

Make sure to measure the rebuild time before and after.

**Comment by brson** [comment]
The next step here is simply to investigate where modules can be pulled out of tikv, give it a try and see if something is feasible.

@BusyJay I wonder if you have ideas about which modules could most easily be pulled out of tikv into crates.

**Comment by breeswish** [comment]
Duplicates https://github.com/tikv/tikv/issues/3352
