### ISSUE TITLE
Grafana: variable instance has a typo and most metrics don't support variable query

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4181]
## Bug Report

**What did you expect to see?**
**What did you see instead?**

![image](https://user-images.githubusercontent.com/1080370/52177315-29511e00-27fa-11e9-88f0-948e22100986.png)

The instance label should be `instance`, not `Instantce`

Btw, most of the TiKV metrics don't support instance filter, e.g, for the Store Size panel, the query is

```
sum(tikv_engine_size_bytes) by (instance)
```

We should change to 

```
sum(tikv_engine_size_bytes{instance=~"$instance"}) by (instance)
```

So we can use instance filter to only choose special TiKV.

**Comment by rleungx** [comment]
Fixes via pingcap/tidb-ansible#669.
