### ISSUE TITLE
Add tcmalloc support to the tikv_alloc crate

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4191]
Today we use the jemalloc allocator, with a stock configuration, encapsulated in the `tikv_alloc` crate, in `components/tikv_alloc`.

Modify `tikv_alloc` to also support [tcmalloc](https://github.com/jmcomets/tcmalloc-rs), compare benchmarks with jemalloc and tcmalloc ([these scripts](https://gist.github.com/brson/881717fc59c12465b35577fc59eb98b3) might be helpful).

This will require adjusting the tikv_alloc features, because they aren't quite right currently: remove the "no-jemalloc" feature, so that disabling jemalloc means setting `default-features = false`. That will require adjusting the various conditional compiles in lib.rs like `#[cfg(all(unix, not(fuzzing), not(feature = "no-jemalloc")))]`.

Also remove the `no-jemalloc` feature from tikv's `Cargo.toml`, change the tikv_alloc crate to `default-features = false`, and add `tikv_alloc/jemalloc` to tikv's default features. That way enabling tcmalloc for tikv means passing `cargo build --no-default-features --features="tikv_alloc/tcmalloc".

I think the above two paragraphs make sense and will work, but I'm not sure.

Then add tcmalloc to tikv_alloc as an optional crate, so that enabling it requires `default-features = false` and `features = ["tcmalloc"]`. Then modify lib.rs to enable tcmalloc when `feature = "tcmalloc"`, following the existing patterns.

Even if tcmalloc doesn't improve performance compared to jemalloc, I'm inclined to check in the feature anyway, to establish the patterns for `tikv_alloc`s allocator abstraction.

**Comment by ZhangHanDong** [comment]
@brson  [PR 4207](https://github.com/tikv/tikv/pull/4207)

**Comment by brson** [comment]
Done.
