### ISSUE TITLE
Remove `extern crate` statements from the repo

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4196]
TiKV is on Rust 2018 now. That means that for the most part `extern crate` isn't needed. Remove all that you can.

Resources:

- [Edition Guide - No more extern crate](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html#no-more-extern-crate)
- [Edition Guide - Macro changes](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/macros/macro-changes.html)

Note that the code in the `fuzz` directory is still on 2015, so don't change anything there.

**Comment by wujunze** [comment]
Let me give this a try.  
Tanks

**Comment by brson** [comment]
It's all yours @wujunze !

**Comment by wujunze** [comment]
OK  @brson

**Comment by ICEYSELF** [comment]
@wujunze Are you still working on this? If not, I will start.

**Comment by wujunze** [comment]
I am doing   Thanks

**Comment by wujunze** [comment]
This task looks very interesting and you are welcome to complete it together @ICEYSELF 
https://github.com/tikv/tikv/pull/4297

**Comment by brson** [comment]
Looks like this is fixed.
