### ISSUE TITLE
Convert trait objects to `dyn` traits

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4197]
TiKV is using Rust 2018 now. Let's migrate to the `dyn` syntax for trait objects. This should be pretty easy with the `#![deny(bare_trait_objects)]` lint. Just apply that to the tikv crate root and fix all the errors.

Then do the same for the bins, tests and benches listed in `Cargo.toml`, and the same for the component projects in the `components` directory.

**Comment by crlf0710** [comment]
let me give this a try.
