### ISSUE TITLE
test failed with "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4219]
## Bug Report

**What did you do?**

make test and failed 

**What did you expect to see?**

All tests passed 

**What did you see instead?**

```
test raftstore::test_multi::test_node_consistency_check ... ok
thread 'raftstore::test_conf_change::test_server_pd_conf_change' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1009:5
test raftstore::test_merge::test_node_check_merged_message ... ok
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1009:5
thread 'raftstore::test_multi::test_server_leader_change_with_uncommitted_log' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1009:5
thread 'raftstore::test_multi::test_multi_server_latency' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1009:5
```

Seem that we create too many threads in the test. Our test may create many threads and the `cargo test` will run many tests (maybe depending on the CPU number) at the same time in parallel, which may cause this problem. 

I use `export RUST_TEST_THREADS=4` and the tests pass. 

So maybe we should:

1. Use fewer test threads 
2. Or adjust the thread number in tests

**Comment by BusyJay** [comment]
I will take a look to the problem.

**Comment by breeswish** [comment]
We need to investigate why it is ok previously.

**Comment by breeswish** [comment]
I found that 592c0838d (Dec 18) is the first commit that makes these tests fail on my machine.

**Comment by breeswish** [comment]
@Connor1996 PTAL as well

**Comment by Connor1996** [comment]
maybe it is related to file handle limit. In my commit, the test will call `flush_cf` in a loop which generates many files. @breeswish

**Comment by breeswish** [comment]
@Connor1996 Got it

**Comment by BusyJay** [comment]
On my local tests, the error is reported after a854feee9f4a503d127fe5db95ae7c40cea93c74. It has something to do with resource reclaim in gRPC service. Maybe there is memory leak that leads to never-dropped tokio reactor.

**Comment by hicqu** [comment]
I agree with @BusyJay . According to my test, the initial tikv opens `187` fds. after I start/stop a tidb, the fd numbers of tikv is `187` -> `190` -> `193` -> `196` -> `199` -> `200` -> `201` -> `202` ...
So there must be something unreleased after the gRPC connection to tidb is closed.

**Comment by BusyJay** [comment]
I do a simple experiment and findout that all runtimes are dropped properly, so grpcio seems not to be the one to be blamed. :rofl:

**Comment by BusyJay** [comment]
After #4256, the error never show up on my machine. Do you want to have a try? @siddontang @breeswish

**Comment by BusyJay** [comment]
All tests pass on my local machine after merging #4256. Feel free to reopen it if you have further problem.
