### ISSUE TITLE
test log wrapper does not contain jemalloc

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4220]
## Bug Report

**What did you do?**

make test

**What did you expect to see?**

all tests passed

**What did you see instead?**

```
error: ./target/debug/log_wrappers-277edbd461a788c9 does not contain jemalloc
```

Do we need to exclude this test from jemalloc checking?

**Comment by brson** [comment]
It's a simple fix: https://github.com/tikv/tikv/pull/4267
