### ISSUE TITLE
cases::test_stale_read::test_stale_read_during_merging failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4246]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/1607/nodes/109/steps/587/log/?start=0

**Comment by overvenus** [comment]
The test failed due to its merge request is rejected by log gap too large.

> 2019/02/20 15:52:27.574 peer.rs:1678: [WARN] [region 1000] 1001 skip proposal: Other(StringError("[src/raftstore/store/peer.rs:1587]: log gap (0, 6] is too large, skip merge"))

However, the test asserts regions are merged successfully at https://github.com/tikv/tikv/blob/e26ceadcdfe94fb6ff83b5abb614ea3115394bcd/tests/failpoints/cases/test_stale_read.rs#L311-L313
