### ISSUE TITLE
Vulnerability reporting process

### ISSUE THREAD

**Issue by Hoverbear** [tikv/tikv#4263]
As part of our effort to become part of the CNCF incubating group, we need to have a "Passing" Core Infrastruture Initiative badge.

We need to consider: **Is it appropriate for security bugs to always be reported via the "Bug Report" issues on Github?** If it isn't, we need to otherwise fulfill this criteria. If it is, we need to say that on the page.

This issue tracks this criteria: https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md#vulnerability_report_process

> The project MUST publish the process for reporting vulnerabilities on the project site. (URL required) [vulnerability_report_process]
> E.g., a clearly designated mailing address on https://PROJECTSITE/security, often in the form security@example.org. This MAY be the same as its bug reporting process. Vulnerability reports MAY always be public, but many projects have a private vulnerability reporting mechanism. 

Closing this issue would mean that there is a tikv.org/security page and a mailing address security@tikv.org.

**Comment by Hoverbear** [comment]
@siddontang Do you think it's appropriate for even critical security bugs to be reported via the bug reporting process?

**Comment by dcalvin** [comment]
@queenypingcap FYI

**Comment by Hoverbear** [comment]
We did this! Closing!
