### ISSUE TITLE
use HTTP to enable jemalloc profile 

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4272]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now we can send SIGUSR2 to TiKV to start the jemalloc profiler, send the signal again to stop it,  then use the jemalloc tool to analyze the result. 

**Describe the feature you'd like:**

I think we can make it more easy to use as Go does. We can use HTTP like accessing `http://127.0.0.1:20180/debug/pprof/head?seconds=30`, which will enable profiler, let it run 30s and disable it. We can also generate the result and show it on web page directly.  

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by YangKeao** [comment]
I am working on this issue. Plan to add a new entry in status server (such as `(&Method::GET, "/jeprof")`) which dumps prof to a temporary file and show it on web page. 

For example, access `/jeprof?seconds=30` will start the profiler, wait asynchronously for 30 seconds and dump the profile, finally return the result and stop the profiler. (Maybe deleting the dump file is also needed, I want to know whether there is a way to dump profile into ram directly?)

BTW: I noticed that send signal `SIGUSR2` to TiKV will only start but never stop profiler.

**Comment by skyline75489** [comment]
Can this be closed since #4600 is merged?
