### ISSUE TITLE
Titan is not compatible with DeleteFilesInRanges

### ISSUE THREAD

**Issue by DorianZheng** [tikv/tikv#4288]
## Bug Report

According to my test, using DeleteFilesInRanges in Titan will lead to inconsistent read. 

In TiKV, we can simply set `use_delete_files` in https://github.com/tikv/tikv/blob/e1984bcc3c3ed96544eb4012da71137509f7d145/src/raftstore/store/worker/region.rs#L466
to false to solve this issue.

**Comment by siddontang** [comment]
how can we solve this problem absolutely? 

Another thing is that seems Titan doesn't support DeleteRange, right? @DorianZheng

**Comment by DorianZheng** [comment]
Titan support DeleteRange. I haven't figured out what's wrong with DeleteFilesInRanges yet. I need some time to investigate.

**Comment by yiwu-arbug** [comment]
This should have have been fixed a while ago.
