### ISSUE TITLE
TiKV go-client dependency install failed

### ISSUE THREAD

**Issue by jaltabike** [tikv/tikv#4289]
Following the guide (https://github.com/tikv/tikv/blob/master/docs/clients/go-client-api.md),

I create the example go-client program using the Transactional Key-Value API.

When installing dependencies (i.e., running "go get github.com/pingcap/tidb@master"),

I met the same issue solved in https://github.com/tikv/tikv/issues/3900#issue-389056974.

Following the solution in https://github.com/tikv/tikv/issues/3900#issuecomment-445759807,

I ran "go get -u github.com/pingcap/tidb@master" and got following error:
$ GO111MODULE=on go get -u github.com/pingcap/tidb@master
go: finding github.com/pingcap/tidb master
go: finding github.com/cznic/mathutil latest
go: finding github.com/ngaut/sync2 latest
go: finding github.com/StackExchange/wmi latest
go: finding github.com/golang/groupcache latest
go: finding github.com/remyoudompheng/bigfft latest
go: finding github.com/google/btree latest
go: finding github.com/coreos/pkg latest
go: finding github.com/beorn7/perks latest
go: finding github.com/tiancaiamao/appdash latest
go: finding sourcegraph.com/sourcegraph/appdash-data latest
go: finding github.com/ngaut/pools latest
go: finding github.com/coreos/go-systemd latest
go: finding google.golang.org/genproto latest
go: finding github.com/ugorji/go/codec latest
go: finding github.com/xiang90/probing latest
go: finding github.com/shurcooL/vfsgen latest
go: finding golang.org/x/net latest
go: finding github.com/prometheus/procfs latest
go: finding github.com/pingcap/parser latest
go: finding github.com/codahale/hdrhistogram latest
go: finding github.com/cznic/sortutil latest
go: finding gopkg.in/tomb.v1 latest
go: finding sourcegraph.com/sourcegraph/appdash latest
go: finding golang.org/x/tools latest
go: gopkg.in/stretchr/testify.v1@v1.3.0: go.mod has non-....v1 module path "github.com/stretchr/testify" at revision v1.3.0
go: finding github.com/prometheus/client_model latest
go: finding github.com/spaolacci/murmur3 latest
go: finding github.com/pingcap/kvproto latest
go: finding golang.org/x/sys latest
go get: error loading module requirements

**Comment by DorianZheng** [comment]
@disksing PTAL

**Comment by disksing** [comment]
Hi @jaltabike , seems there are something wrong with network. Can you successfully download packages from `golang.org`? (try `go get -v golang.org/x/sys`)

**Comment by jaltabike** [comment]
Hi @disksing
Yes, I can.

$ go get -v golang.org/x/sys
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys?go-get=1
go: finding golang.org/x/sys latest
go: downloading golang.org/x/sys v0.0.0-20190228071610-92a0ff1e1e2f
Fetching https://golang.org/x?go-get=1
Parsing meta tags from https://golang.org/x?go-get=1 (status code 200)
Fetching https://golang.org?go-get=1
Parsing meta tags from https://golang.org?go-get=1 (status code 200)

**Comment by siddontang** [comment]
@disksing 
maybe we can replace golang.org to github.com/golang :-) 

Can we let the user use tikv/client-go now? so we don't need to depend on tidb.

**Comment by disksing** [comment]
@siddontang We can't use `github.com/golang` directly unless we replace all import path in the package. `tikv/client-go` is still not ready yet.

**Comment by disksing** [comment]
Hi @jaltabike , could you try `go get -u -v github.com/pingcap/tidb@master`? I still suspect that it is related to the network. It just simply works in my machine following the documentation. BTW, please paste the output of `go version` too.

**Comment by jaltabike** [comment]
$ go get -u -v github.com/pingcap/tidb@master
go: finding github.com/pingcap/tidb master
go: finding github.com/ngaut/pools latest
go: finding github.com/eknkc/amber latest
go: finding github.com/shurcooL/httpfs latest
go: finding github.com/ngaut/sync2 latest
go: finding github.com/StackExchange/wmi latest
Fetching https://golang.org/x/tools?go-get=1
go: finding github.com/etcd-io/gofail latest
go: finding github.com/shurcooL/vfsgen latest
go: finding github.com/spaolacci/murmur3 latest
go: finding github.com/ugorji/go/codec latest
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools?go-get=1
go: finding github.com/prometheus/client_model latest
Fetching https://gopkg.in/tomb.v1?go-get=1
go: finding github.com/prometheus/procfs latest
go: finding golang.org/x/tools latest
Parsing meta tags from https://gopkg.in/tomb.v1?go-get=1 (status code 200)
get "gopkg.in/tomb.v1": found meta tag get.metaImport{Prefix:"gopkg.in/tomb.v1", VCS:"git", RepoRoot:"https://gopkg.in/tomb.v1"} at https://gopkg.in/tomb.v1?go-get=1
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys?go-get=1
Fetching https://go.uber.org/zap?go-get=1
go: finding github.com/pingcap/parser latest
go: finding github.com/tiancaiamao/appdash latest
go: finding github.com/coreos/pkg latest
Fetching https://golang.org/x/net?go-get=1
go: finding gopkg.in/tomb.v1 latest
Fetching https://golang.org/x/sync?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
get "golang.org/x/net": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/sync?go-get=1 (status code 200)
get "golang.org/x/sync": found meta tag get.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at https://golang.org/x/sync?go-get=1
go: finding golang.org/x/sys latest
Parsing meta tags from https://go.uber.org/zap?go-get=1 (status code 200)
get "go.uber.org/zap": found meta tag get.metaImport{Prefix:"go.uber.org/zap", VCS:"git", RepoRoot:"https://github.com/uber-go/zap"} at https://go.uber.org/zap?go-get=1
go: finding github.com/pingcap/tipb latest
Fetching https://go.uber.org/atomic?go-get=1
go: finding github.com/golang/groupcache latest
Fetching https://gopkg.in/natefinch/lumberjack.v2?go-get=1
Parsing meta tags from https://go.uber.org/atomic?go-get=1 (status code 200)
get "go.uber.org/atomic": found meta tag get.metaImport{Prefix:"go.uber.org/atomic", VCS:"git", RepoRoot:"https://github.com/uber-go/atomic"} at https://go.uber.org/atomic?go-get=1
go: finding golang.org/x/sync latest
go: finding golang.org/x/net latest
go: finding github.com/pingcap/goleveldb latest
go: finding github.com/pingcap/log latest
Parsing meta tags from https://gopkg.in/natefinch/lumberjack.v2?go-get=1 (status code 200)
get "gopkg.in/natefinch/lumberjack.v2": found meta tag get.metaImport{Prefix:"gopkg.in/natefinch/lumberjack.v2", VCS:"git", RepoRoot:"https://gopkg.in/natefinch/lumberjack.v2"} at https://gopkg.in/natefinch/lumberjack.v2?go-get=1
go: finding github.com/beorn7/perks latest
go: finding github.com/google/btree latest
Fetching https://gopkg.in/yaml.v2?go-get=1
go: finding github.com/pingcap/kvproto latest
Fetching https://sourcegraph.com/sourcegraph/appdash?go-get=1
go: finding github.com/cznic/sortutil latest
Fetching https://go.uber.org/multierr?go-get=1
Fetching https://golang.org/x/text?go-get=1
Fetching https://gopkg.in/check.v1?go-get=1
Parsing meta tags from https://go.uber.org/multierr?go-get=1 (status code 200)
get "go.uber.org/multierr": found meta tag get.metaImport{Prefix:"go.uber.org/multierr", VCS:"git", RepoRoot:"https://github.com/uber-go/multierr"} at https://go.uber.org/multierr?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
Fetching https://gopkg.in/fsnotify.v1?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text?go-get=1
Parsing meta tags from https://sourcegraph.com/sourcegraph/appdash?go-get=1 (status code 200)
get "sourcegraph.com/sourcegraph/appdash": found meta tag get.metaImport{Prefix:"sourcegraph.com/sourcegraph/appdash", VCS:"git", RepoRoot:"https://github.com/sourcegraph/appdash"} at https://sourcegraph.com/sourcegraph/appdash?go-get=1
Parsing meta tags from https://gopkg.in/check.v1?go-get=1 (status code 200)
get "gopkg.in/check.v1": found meta tag get.metaImport{Prefix:"gopkg.in/check.v1", VCS:"git", RepoRoot:"https://gopkg.in/check.v1"} at https://gopkg.in/check.v1?go-get=1
Fetching https://sourcegraph.com/sourcegraph/appdash-data?go-get=1
Parsing meta tags from https://gopkg.in/fsnotify.v1?go-get=1 (status code 200)
get "gopkg.in/fsnotify.v1": found meta tag get.metaImport{Prefix:"gopkg.in/fsnotify.v1", VCS:"git", RepoRoot:"https://gopkg.in/fsnotify.v1"} at https://gopkg.in/fsnotify.v1?go-get=1
Parsing meta tags from https://sourcegraph.com/sourcegraph/appdash-data?go-get=1 (status code 200)
get "sourcegraph.com/sourcegraph/appdash-data": found meta tag get.metaImport{Prefix:"sourcegraph.com/sourcegraph/appdash-data", VCS:"git", RepoRoot:"https://github.com/sourcegraph/appdash-data"} at https://sourcegraph.com/sourcegraph/appdash-data?go-get=1
go: finding github.com/codahale/hdrhistogram latest
Fetching https://google.golang.org/appengine?go-get=1
go: finding github.com/cznic/mathutil latest
go: finding sourcegraph.com/sourcegraph/appdash latest
Fetching https://google.golang.org/grpc?go-get=1
go: finding sourcegraph.com/sourcegraph/appdash-data latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/blacktear23/go-proxyprotocol latest
go: finding github.com/tmc/grpc-websocket-proxy latest
Parsing meta tags from https://google.golang.org/appengine?go-get=1 (status code 200)
get "google.golang.org/appengine": found meta tag get.metaImport{Prefix:"google.golang.org/appengine", VCS:"git", RepoRoot:"https://github.com/golang/appengine"} at https://google.golang.org/appengine?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc?go-get=1
go: finding github.com/xiang90/probing latest
Fetching https://golang.org/x/crypto?go-get=1
go: finding github.com/remyoudompheng/bigfft latest
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
get "golang.org/x/crypto": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto?go-get=1
go: finding github.com/pingcap/gofail latest
Fetching https://gopkg.in/stretchr/testify.v1?go-get=1
Fetching https://honnef.co/go/tools?go-get=1
go: finding github.com/pingcap/check latest
Parsing meta tags from https://gopkg.in/stretchr/testify.v1?go-get=1 (status code 200)
get "gopkg.in/stretchr/testify.v1": found meta tag get.metaImport{Prefix:"gopkg.in/stretchr/testify.v1", VCS:"git", RepoRoot:"https://gopkg.in/stretchr/testify.v1"} at https://gopkg.in/stretchr/testify.v1?go-get=1
Fetching https://gopkg.in/alecthomas/kingpin.v2?go-get=1
go: finding github.com/coreos/go-systemd latest
Fetching https://golang.org/x/oauth2?go-get=1
go: finding golang.org/x/crypto latest
Fetching https://google.golang.org/genproto?go-get=1
Parsing meta tags from https://gopkg.in/alecthomas/kingpin.v2?go-get=1 (status code 200)
get "gopkg.in/alecthomas/kingpin.v2": found meta tag get.metaImport{Prefix:"gopkg.in/alecthomas/kingpin.v2", VCS:"git", RepoRoot:"https://gopkg.in/alecthomas/kingpin.v2"} at https://gopkg.in/alecthomas/kingpin.v2?go-get=1
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
get "golang.org/x/oauth2": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2?go-get=1
Parsing meta tags from https://google.golang.org/genproto?go-get=1 (status code 200)
get "google.golang.org/genproto": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at https://google.golang.org/genproto?go-get=1
Parsing meta tags from https://honnef.co/go/tools?go-get=1 (status code 200)
get "honnef.co/go/tools": found meta tag get.metaImport{Prefix:"honnef.co/go/tools", VCS:"git", RepoRoot:"https://github.com/dominikh/go-tools"} at https://honnef.co/go/tools?go-get=1
Fetching https://golang.org/x/time?go-get=1
Parsing meta tags from https://golang.org/x/time?go-get=1 (status code 200)
get "golang.org/x/time": found meta tag get.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at https://golang.org/x/time?go-get=1
go: finding github.com/kr/logfmt latest
go: finding golang.org/x/oauth2 latest
go: finding google.golang.org/genproto latest
Fetching https://gopkg.in/resty.v1?go-get=1
go: finding honnef.co/go/tools latest
go: finding github.com/mwitkow/go-conntrack latest
Parsing meta tags from https://gopkg.in/resty.v1?go-get=1 (status code 200)
get "gopkg.in/resty.v1": found meta tag get.metaImport{Prefix:"gopkg.in/resty.v1", VCS:"git", RepoRoot:"https://gopkg.in/resty.v1"} at https://gopkg.in/resty.v1?go-get=1
go: finding golang.org/x/time latest
Fetching https://cloud.google.com/go?go-get=1
go: finding github.com/golang/glog latest
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: gopkg.in/stretchr/testify.v1@v1.3.0: go.mod has non-....v1 module path "github.com/stretchr/testify" at revision v1.3.0
go: finding github.com/alecthomas/units latest
go: finding github.com/alecthomas/template latest
go: finding github.com/rogpeppe/fastuuid v1.0.0
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code 200)
get "cloud.google.com/go": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at https://cloud.google.com/go?go-get=1
go get: error loading module requirements

$ go version
go version go1.11.2 linux/amd64

**Comment by disksing** [comment]
Hi @jaltabike, it is really a very strange problem. I have tried to reproduce it using go1.11.2 in my environment but with no luck :(

I noticed an error about `testify` from the log you provided:
```
go: gopkg.in/stretchr/testify.v1@v1.3.0: go.mod has non-....v1 module path "github.com/stretchr/testify" at revision v1.3.0
```
After search go source code, I found that it should reported from here: https://github.com/golang/go/blob/d346a9b7725b5313ddda3913cbcd5ff5fba0c909/src/cmd/go/internal/modfetch/coderepo.go#L339

From the context of the source code, I think the error is reported because the module path defined in `stretchr/testify/go.mod` (which is `github.com/stretchr/testify`) does not have suffix of "v1".

Another discovery is that the version of testify that tidb depends on is 1.2.2 (see https://github.com/pingcap/tidb/blob/e7ff050a453c8b8564b30c7c55b993a11c44b1d9/go.mod#L86), which does not have the `go.mod` file. You should not need to download the 1.3.0 version of testify when `go get tidb`.

I have no clear conclusion on this issue at present, I am sorry. Maybe you can try to clean up the cache in your GOPATH and try again :(

/cc @tiancaiamao Do you have any ideas?

**Comment by jaltabike** [comment]
@disksing
OK. Thank you for your help.

**Comment by tiancaiamao** [comment]
I meet the same problem.
Tomorrow I'll try to upgrade Go1.12, after the upgrading I'll check it again @disksing
