### ISSUE TITLE
coprocessor: parsing error is never returned

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#4293]
When it fails to parse a request, the error is wrapped in an dummy handler which is returned from the function with a fake context and supposed to be executed inside read pool.

https://github.com/tikv/tikv/blob/e53a8c21d77d8ce0e06b855fbe31ee9f8cd525a2/src/coprocessor/endpoint.rs#L196-L211

However endpoint will continue to get a snapshot first using the fake context, which will always fail as it's an invalid context.

https://github.com/tikv/tikv/blob/e53a8c21d77d8ce0e06b855fbe31ee9f8cd525a2/src/coprocessor/endpoint.rs#L344-L357

So a strange error from raftstore is returned instead of the actual error which is the parsing error in the first place.

The bug is introduced in #3515, and affects v2.1.x and v3.0.x, needs to be fixed soon.

@disksing @breeswish PTAL

**Comment by siddontang** [comment]
Finally, we find this problem 😭 

Btw, why parsing failed? the request is too big? @BusyJay

**Comment by disksing** [comment]
The request can be unmarshalled in Go. I guess the problem is the  DAG request recurses too deep.

**Comment by breeswish** [comment]
Interesting finding. Looks like we must find a way that parsing failed errors are returned immediately instead of partially finished the pipe line.

**Comment by breeswish** [comment]
Fixed in #4303
