### ISSUE TITLE
TiKV may not report errors if port is in conflict

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#4323]
Because TiKV binds port using SO_REUSEPORT, so if the port is binded by other process with SO_REUSEPORT already, the instance can start successfully without errors. However new connections may not be accepted by the started instance, so it's idle and no errors or warnings are reported.

This can easily happen if multiple instances are sharing the same machine while they are not configured properly.

**Comment by siddontang** [comment]
can we add `SO_REUSEADDR` to avoid this?

**Comment by BusyJay** [comment]
Yes. It should solve the problem. And gRPC sets `SO_REUSEADDR` by default.

**Comment by brson** [comment]
If grpc already uses `SO_REUSEADDR` which are the network connections that it needs to be added to?

**Comment by sticnarf** [comment]
Would you please explain a bit more about how `SO_REUSEADDR` solves this? I think it unrelated.

To my understanding, gRPC uses `SO_REUSEPORT` to enable multi-processing. But `SO_REUSEADDR` does not limit another process to bind to the same address and port. 

I cannot think of a perfect solution. But I think we may bind to the port w/o `SO_REUSEPORT` first to detect if it conflicts, then we close it and run gRPC on it. It is not an atomic operation to re-bind the port, but for the situation when people run multiple instances in one machine with the same port, I think people start instances manually. It is rare that another server starts just between we close the first socket and run the new one. So I believe it helps.

**Comment by kennytm** [comment]
For the record, we've spent a few hours today checking why Lightning randomly got some "UNIMPLEMENTED" gRPC error from Importer, before we (through Wireshark) realized that both TiKV and Importer are configured to bind to the same port.

**Comment by BusyJay** [comment]
@sticnarf  The purpose we used `SO_REUSEPORT` is to bind to an address that is hold by other socket in TIME_WAIT state. So using `SO_REUSEADDR` is sufficient to solve the problem.

> ...SO_REUSEADDR does not limit another process to bind to the same address and port.

It does. See http://man7.org/linux/man-pages/man7/socket.7.html.

**Comment by youjiali1995** [comment]
> @sticnarf The purpose we used `SO_REUSEPORT` is to bind to an address that is hold by other socket in TIME_WAIT state. So using `SO_REUSEADDR` is sufficient to solve the problem.
> 
> > ...SO_REUSEADDR does not limit another process to bind to the same address and port.
> 
> It does. See http://man7.org/linux/man-pages/man7/socket.7.html.

gRPC don't need the ability of `SO_REUSEPORT` to solve thundering herd problem? Why it uses `SO_REUSEPORT` instead of `SO_REUSEADDR`?

**Comment by BusyJay** [comment]
gRPC use EPOLLEXCLUSIVE to avoid waking up multiple threads at a time. But we do need to check whether there is performance regression after disabling so_reuseport.

Another unsafe way is try to check if the port is bound before starting up. It's racy to do the check and should be considered only when all other solutions don't work out.

**Comment by youjiali1995** [comment]
> gRPC use EPOLLEXCLUSIVE to avoid waking up multiple threads at a time. But we do need to check whether there is performance regression after disabling so_reuseport.
> 
> Another unsafe way is try to check if the port is bound before starting up. It's racy to do the check and should be considered only when all other solutions don't work out.

`EPOLLEXCLUSIVE` can wake up more than one threads. We need benchmark it. And it's odd to use both `EPOLLEXCLUSIVE` and `SO_REUSEPORT`...😂

**Comment by hunterlxt** [comment]
Hi all, I've benchmarked on the weekend and I found that QPS got better in benchmark with sysbench after `reuse_port(false)`. Here are some pieces of QPS result.

```bash
sysbench --config-file=config select_random_points --tables=32 --table-size=1000000
before:14299
after:20455
sysbench --config-file=config oltp_point_select --tables=32 --table-size=1000000 
before:53926
after:58163
sysbench --config-file=config oltp_update_index --tables=32 --table-size=1000000
before:6974
after:7022
```

BTW, cluster just used default config and sysbench driver is deployed on the same node as TiDB with 64 threads.

**Comment by youjiali1995** [comment]
> Hi all, I've benchmarked on the weekend and I found that QPS got better in benchmark with sysbench after `reuse_port(false)`. Here are some pieces of QPS result.
> 
> ```shell
> sysbench --config-file=config select_random_points --tables=32 --table-size=1000000
> before:14299
> after:20455
> sysbench --config-file=config oltp_point_select --tables=32 --table-size=1000000 
> before:53926
> after:58163
> sysbench --config-file=config oltp_update_index --tables=32 --table-size=1000000
> before:6974
> after:7022
> ```
> 
> BTW, cluster just used default config and sysbench driver is deployed on the same node as TiDB with 64 threads.

Interesting...
