### ISSUE TITLE
float_str_to_int_string should not return error

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4327]
## Bug Report

TiDB with TiKV:

```
mysql> CREATE TABLE t1 (s VARCHAR(50));
Query OK, 0 rows affected (0.12 sec)

mysql> INSERT INTO t1 VALUES('99999999e1000');
Query OK, 1 row affected (0.02 sec)

mysql> SELECT * from t1 where s;
ERROR 1105 (HY000): Other(StringError("[src/coprocessor/codec/convert.rs:321]: [1264] Data Out of Range"))
```

TiDB without TiKV:

```
mysql> CREATE TABLE t1 (s VARCHAR(50));
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES('99999999e1000');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * from t1 where s;
+---------------+
| s             |
+---------------+
| 99999999e1000 |
+---------------+
1 row in set, 1 warning (0.00 sec)
```

MySQL:

```
mysql> CREATE TABLE t1 (s VARCHAR(50));
Query OK, 0 rows affected (0.16 sec)

mysql> INSERT INTO t1 VALUES('99999999e1000');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * from t1 where s;
+---------------+
| s             |
+---------------+
| 99999999e1000 |
+---------------+
1 row in set, 1 warning (0.00 sec)
```

According to TiDB's [implementation](https://github.com/pingcap/tidb/blob/469fa877d6c3f8851760eade5f8601dcbbbd4d59/types/convert.go#L274) of `float_str_to_int_string` it returns warnings instead of errors. That should be the main reason why this fails in TiKV.

**Comment by liufuyang** [comment]
Is this some easy task, perhaps I can try give some help on it?
Looks like I just need to return some warning here:
https://github.com/tikv/tikv/blob/02ebbd69d0c7332e5776248122e0e59949317f57/src/coprocessor/codec/convert.rs#L306
?

**Comment by breeswish** [comment]
@liufuyang Yes, you just need to change errors to warnings. Notice that the function itself is not accepting some context for writing warnings, so you need to modify these function signatures.

**Comment by liufuyang** [comment]
hmm... can you help me find some code that returns Warnings so I can try do the same here? I am pretty new to tikv and kind of new to Rust. I know the type Result kind of well but I am not sure how to change this to some Warning type :)

**Comment by breeswish** [comment]
@liufuyang You can grep for "append_warning" and you will see that normally there will be a `ctx.warnings.append_warning`. So to append warnings the function should accept that ctx first (and you need to change the signature)

**Comment by liufuyang** [comment]
@breeswish Thanks :)

Okay. Before I go further with that, I just tried some corner cases for fun. It seems our code in here in tikv (or maybe also in tidb, if you can help me test it would be nice), that when the input is `"9e20"`, which is a number bigger than i64_max, the code here passes without returning a Err:
Input: `"9e20"`
Current float_str_to_int_string() output:
`900000000000000000000`
while i64_max is
`9223372036854775807`

**This seems to be another potential bug in the code?** As I also tried with "9e20" on MySQL 5.7 it seems output warning as well:
```
mysql> INSERT INTO t1 VALUES('9e20');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * from t1 where s;
+------+
| s    |
+------+
| 9e20 |
+------+
1 row in set, 1 warning (0.00 sec)
```

**Comment by liufuyang** [comment]
I actually not sure how mysql works, it seems that `"1e5"` will not cause warning but "1e10" will...

```
mysql> SELECT * from t1 where s;
+------+
| s    |
+------+
| 1e5  |
+------+
1 row in set (0.00 sec)

mysql> INSERT INTO t1 VALUES('1e10');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * from t1 where s;
+------+
| s    |
+------+
| 1e5  |
| 1e10 |
+------+
2 rows in set, 1 warning (0.00 sec)

mysql> SHOW WARNINGS;
+---------+------+-------------------------------------------+
| Level   | Code | Message                                   |
+---------+------+-------------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: '1e10' |
+---------+------+-------------------------------------------+
```

Not exactly sure what I am doing here but do we try to make tidb behave exactly the same as MySQL5.7 or...? 🤔

**Comment by Hoverbear** [comment]
Hi @morgo, can you take a look at this compatibility issue?

**Comment by morgo** [comment]
This is really weird.  It looks like the insert is behaving as expected, but on reading the data TiKV is evaluating the values to compare them to `s`.

So for a quick test case that is legal:
```
CREATE TABLE t1 (s VARCHAR(50));
INSERT INTO t1 VALUES ('100'), (NULL);
SELECT * FROM t1 WHERE s; -- must check that the value is not null
```
So there has to be a `NOT NULL` check, but I am not sure casting a string value that looks numeric is required to do that (it's a bug).  It should only compare for nullability and not cast in doing so.  It is a subtle bug, because the cast is only used for compare, and doesn't affect the returned value.

Taking your minimal test case:
```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (s VARCHAR(50));
INSERT INTO t1 VALUES('9e20');
select * from t1 where s;
```

PTAL @zz-jason

**Comment by morgo** [comment]
It looks like this behavior might be required for MySQL compatibility (sorry, it's not common syntax - so I am less familiar):
```
mysql57> INSERT INTO t1 VALUES (NULL), ('0'), ('0.0');
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql57> SELECT * FROM t1;
+------+
| s    |
+------+
| NULL |
| 0    |
| 0.0  |
+------+
3 rows in set (0.00 sec)

mysql57> SELECT * FROM t1 WHERE s;
Empty set (0.00 sec)
```

I would have interpreted `WHERE s` as "where s is not null", but it looks like MySQL doesn't do that.  It will cast values to compare.  It can even produce a warning:

```
mysql57> TRUNCATE t1;
Query OK, 0 rows affected (0.02 sec)

mysql57> INSERT INTO t1 VALUES (NULL), ('0'), ('0.0'), ('NULL');
Query OK, 4 rows affected (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql57> SELECT * FROM t1 WHERE s;
Empty set, 1 warning (0.00 sec)

mysql57> SHOW WARNINGS;
+---------+------+-------------------------------------------+
| Level   | Code | Message                                   |
+---------+------+-------------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: 'NULL' |
+---------+------+-------------------------------------------+
1 row in set (0.00 sec)
```

It is possible the only part broken here is the type used for casting before comparing.

**Comment by liufuyang** [comment]
@morgo If necessary, perhaps you can help open another issue on this weird behavior of MySQL?

I made a PR https://github.com/tikv/tikv/pull/4336 in the hope to firstly solve the issue mentioned here at the top. I hope here we can continue discussion here about making "99999999e1000" can be selected. The issue you talked above seems has a much larger scale and discuss here further might make things more confusing here :P

**Comment by liufuyang** [comment]
@breeswish The PR has been merged, do we need to test it again manually to verify it before we close this issue?

**Comment by breeswish** [comment]
Yes! :) Would you like to have a try with latest master?

**Comment by liufuyang** [comment]
Never really did this before, I guess I can use the tidb-docker-compose repo for this, right?

**Comment by Hoverbear** [comment]
@liufuyang Should be do-able that way. You'd set up the docker-compose and make TiKV work "from source" via the instructions here I think:  https://github.com/pingcap/tidb-docker-compose#bring-up-tidb-cluster

**Comment by breeswish** [comment]
@liufuyang Or you may just use tidb-ansible from https://github.com/pingcap/tidb-ansible, but subsitute the tikv binary in resources/bin from the one downloaded by ansible to yours.

**Comment by liufuyang** [comment]
Looks like the newest image has been updated with my changes. I tried with tidb-docker-compose and just start it with the default settings. Then do test like
```
mysql> CREATE TABLE t1 (s VARCHAR(50));
Query OK, 0 rows affected (0.20 sec)

mysql> INSERT INTO t1 VALUES('99999999e1000');
Query OK, 1 row affected (0.04 sec)

mysql> SELECT * from t1 where s;
+---------------+
| s             |
+---------------+
| 99999999e1000 |
+---------------+
1 row in set, 1 warning (0.00 sec)

mysql> SHOW WARNINGS
    -> ;
+---------+------+-----------------------------------------------------------------+
| Level   | Code | Message                                                         |
+---------+------+-----------------------------------------------------------------+
| Warning | 1105 | Eval("BIGINT value is out of range in \"99999999e1000\"", 1690) |
+---------+------+-----------------------------------------------------------------+
1 row in set (0.01 sec)
```

Noticing the warning number is different from the standard MySQL warning which is 1292 seen from above discussion. This is expected, as in PR https://github.com/tikv/tikv/pull/4336 we appended warnings as `Error::overflow()` instead of `Error::truncated_wrong_val()`.

Perhaps we can close this issue now? 🤔

**Comment by liufuyang** [comment]
I also made a PR https://github.com/tikv/tikv/pull/4413 to fix the output format.

**Comment by breeswish** [comment]
Yes! Thanks a lot!
