### ISSUE TITLE
error: ./target/debug/tikv-server does not enable sse4.2

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4330]
## Bug Report

This error is shown for in CI:

```
+ sh check-sse4_2.sh
checking bins for sse4.2
checking binary ./target/debug/tikv-server for sse4.2
_ZN7rocksdb6crc32c10ExtendImplIXadL_ZNS0_L10Fast_CRC32EPmPPKhEEEEjjPKcm
_ZN7rocksdb6crc32cL10Fast_CRC32EPmPPKh
error: ./target/debug/tikv-server does not enable sse4.2
checking binary ./target/debug/tikv-importer for sse4.2
_ZN7rocksdb6crc32c10ExtendImplIXadL_ZNS0_L10Fast_CRC32EPmPPKhEEEEjjPKcm
_ZN7rocksdb6crc32cL10Fast_CRC32EPmPPKh
error: ./target/debug/tikv-importer does not enable sse4.2
some binaries do not enable sse4.2
fix this by building tikv with ROCKSDB_SYS_SSE=1
script returned exit code 1
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/2134/pipeline

**Comment by breeswish** [comment]
Just caught another failure:

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/2137/pipeline

This error happens pretty frequently.. @overvenus PTAL

**Comment by overvenus** [comment]
It was caused by missing gdb in our CI before. Now https://github.com/tikv/tikv/pull/4329 shows this issue is  resolved.
