### ISSUE TITLE
Consider using galemu in FixtureStore

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4339]
## Feature Request

Because of lacking GATs, `FixtureStore` clones data when an scanner is created from it. This makes benchmarks complicated (to bypass this clone cost) or inaccurate (clone cost is counted).

Looks like for now we have a choice to resolve this before GATs is landed: https://github.com/1aim/galemu

**Comment by iosmanthus** [comment]
@breeswish Could we just modify the representation of `FixtureStoreScanner` and let it wrap an `std::collections::btree_map::Iter` which is an iterator that yields references of items in `BTreeMap`. And then we can clone the data in `BTreeMap` by need.
https://github.com/tikv/tikv/blob/cb0e3046ca315ce00964b9bf11bd210c08f4ccdf/src/storage/txn/store.rs#L278-L280

**Comment by iosmanthus** [comment]
@breeswish I check [the documentation of `galemu`](https://docs.rs/galemu/0.2.2/galemu/), it seems that we need to change the definition of  trait `Store` to (some details omitted):
```rust
use galemu::{Bound, BoundExt};
pub trait Store {
    type Scanner: for<'s> BoundExt<'s> + Scanner;
    fn scanner<'s>(&self) -> Bound<'s, Self::Scanner>;
}
```
It will be a disaster when GATs is landed and harm for the current APIs the depends on `Store`.

Or, we could add a lifetime to `Store`:
```rust
pub trait Store<'s>: Send {
    type Scanner: Scanner;
    fn scanner(&'s self) -> Self::Scanner;
}
```
So, we can return a `std::collections::btree_map::Iter` which iterates over `BTreeMap` by reference as a `Scanner` when `impl Store for FixtureStore`.

**Here is a demo:**
```rust
use std::slice::Iter;
pub trait Store<'s>: Send {
    type Scanner: Iterator;
    fn scanner(&'s self) -> Self::Scanner;
}

pub struct FixtureStore<T> {
    data: Vec<T>,
}

impl<T> FixtureStore<T> {
    pub fn new(data: Vec<T>) -> Self {
        Self { data }
    }
}

impl<'s, T: 's + Send> Store<'s> for FixtureStore<T> {
    type Scanner = Iter<'s, T>;
    fn scanner(&'s self) -> Self::Scanner {
        self.data.iter()
    }
}
```
If you think it's worthwhile I will try to open a PR.

**Comment by breeswish** [comment]
@iosmanthus Nice work. I previously tried to use Store<'s> but it is more complicated because `Store` is stored in a lot of places (so it's indeed also a large API change). May you try with `fn scanner<'s>(&self) -> Bound<'s, Self::Scanner>;` to see if it needs a lot of changes?

**Comment by iosmanthus** [comment]
> @iosmanthus Nice work. I previously tried to use Store<'s> but it is more complicated because `Store` is stored in a lot of places (so it's indeed also a large API change). May you try with `fn scanner<'s>(&self) -> Bound<'s, Self::Scanner>;` to see if it needs lesser changes?

 `fn scanner<'s>(&self) -> Bound<'s, Self::Scanner>;` require `Self::Scanner` satisfy trait bound: `BoundExt<'s>`. To Add `BoundExt<'s>` for `Store::Scanner`, we need to use `create_gal_wrapper_type_for` for every `Scanner` type to create a wrapper type in order to lift the lifetime. It looks like: 
```rust
#![feature(arbitrary_self_types)]
use galemu::{create_gal_wrapper_type, Bound, BoundExt};

pub trait Store {
    type Scanner: Scanner + for<'s> BoundExt<'s>;
    fn scanner<'s>(&'s self) -> Bound<'s, Self::Scanner>;
}

pub trait Scanner: for<'a> BoundExt<'a> {
    type Item;
    fn next(self: &mut Bound<Self>) -> Option<Self::Item>;
}

type Iter<'a> = std::slice::Iter<'a, i32>;
create_gal_wrapper_type! {
    pub struct IterWrap(Iter<'a>);
}

impl Scanner for IterWrap {
    type Item = i32;
    fn next(self: &mut Bound<Self>) -> Option<Self::Item> {
        let me = IterWrap::get_mut(self);
        me.next().cloned()
    }
}

pub struct NewStore(Vec<i32>);
impl Store for NewStore {
    type Scanner = IterWrap;
    fn scanner(&self) -> Bound<Self::Scanner> {
        IterWrap::new(self.0.iter())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn it_works() {
        let store = NewStore(vec![1, 2, 3, 4]);
        let mut scanner = store.scanner();
        let mut result = vec![];
        while let Some(i) = scanner.next() {
            result.push(i);
        }
        assert_eq!(vec![1, 2, 3, 4], result);
    }
}
```
It we use GATs, no wrapper type are needed.
The wraper type created by the macro is annoying and will recude the readability of the code.
Maybe we cound wait GATs land and change the code. It seems like the core system for GATs is already in place.
