### ISSUE TITLE
Accept & for Tz

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4341]
## Feature Request

Currently mostly `Tz` is passed by value, i.e. it is copied when it is passed to elsewhere. However, actually `Tz`'s [size is pretty large](https://github.com/chronotope/chrono-tz/issues/27) thanks to the interesting chrono-tz implementation.. This means that it may be faster to pass `Tz` by reference.

**Comment by iosmanthus** [comment]
Maybe we can just remove the derived `Copy` trait of `Tz` in https://github.com/tikv/tikv/blob/5a296bc4ff9bc36a7d7da0732de1c5ba85d5c176/src/coprocessor/codec/mysql/time/tz.rs#L22-L34
But it seems `EvalConfig` has the same problem as `Tz` which derive redundant `Copy` trait.
https://github.com/tikv/tikv/blob/c772ec291d0c6dc58361cc57f04170c98857285f/src/coprocessor/dag/expr/ctx.rs#L53-L71
But I am still digging for the downside of the changing

**Comment by breeswish** [comment]
Yes, maybe we can just remove the Copy of `Tz`. The Copy of EvalConfig is just added recently and it can be removed safely.

**Comment by iosmanthus** [comment]
@breeswish maybe I can open a pr in this afternoon after I check the rest of the codes that depend on `EvalConfig` and `Tz`~ thx!

**Comment by breeswish** [comment]
Implemented in #4380
