### ISSUE TITLE
coprocessor/builtin_string: bug exist in InstrBinary

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#4344]
## Bug Report

In PR #4340 for function `InStrBinary`, there are two bugs:
1.  A binary string shouldn't be decode by UTF-8, this may cause an error when meet string not encoded by UTF-8.
2. for empty substr the result should be `1` instead of `0`, in MySQL  5.6

```
mysql> SELECT INSTR('', '');
+---------------+
| INSTR('', '') |
+---------------+
|             1 |
+---------------+
1 row in set (0.00 sec)

mysql> SELECT INSTR('tidb', '');
+-------------------+
| INSTR('tidb', '') |
+-------------------+
|                 1 |
+-------------------+
1 row in set (0.00 sec)

mysql> SELECT INSTR('', 'tidb');
+-------------------+
| INSTR('', 'tidb') |
+-------------------+
|                 0 |
+-------------------+
1 row in set (0.00 sec)

```

**Comment by AndreMouche** [comment]
@TigerInYourDream would you like to fix it?

**Comment by iosmanthus** [comment]
@AndreMouche maybe I can fix it. I will try.

**Comment by iosmanthus** [comment]
@AndreMouche It seems not so complicated, maybe I can fix it. It will try.

**Comment by iosmanthus** [comment]
`instr_binary` use a subroutine to find the substring position use the naive string-search algorithm which takes time `O(mn)` so does lots of functions in [src/coprocessor/dag/expr/builtin_string.rs](https://github.com/tikv/tikv/blob/master/src/coprocessor/dag/expr/builtin_string.rs): `locate_binary_2_args, locate_binary_3_args ...`.

If `s` and `substring` is in UTF-8 encoding, we can use [`find method on String`](https://doc.rust-lang.org/std/string/struct.String.html#method.find), however,  there is no such method on slice such as `&[u8]`. But I found a [crate](https://github.com/bluss/twoway) that can matching bytes and it uses [two-way algorithm](http://www-igm.univ-mlv.fr/~lecroq/string/node26.html) which run in `O(m+n)` time.

If we refactor the code of `instr_binary` with the crate, we can get the following code:
```rust
#[inline]
pub fn instr_binary<'a, 'b: 'a>(
    &'b self,
    ctx: &mut EvalContext,
    row: &'a [Datum],
) -> Result<Option<i64>> {
    let s = try_opt!(self.children[0].eval_string(ctx, row));
    let substr = try_opt!(self.children[1].eval_string(ctx, row));
    if s.is_empty() {
        return Ok(Some(0));
    }
    if substr.is_empty() {
        return Ok(Some(1));
    }
    Ok(twoway::find_bytes(&s, &substr)
        .map(|i| (i + 1) as i64)
        .or(Some(0)))
}
```

I will open a pr if you think it's worthwhile. @AndreMouche thx!

**Comment by AndreMouche** [comment]
It looks good to me @iosmanthus
