### ISSUE TITLE
slog kvs are missing in CaseTraceLogger 

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#4361]
## Bug Report

**What did you do?**

`make trace_test`

**What did you expect to see?**

```
2019/03/12 13:51:49.548 node.rs:203: [INFO] alloc store id
2019/03/12 13:51:49.565 node.rs:218: [INFO] alloc first region id
2019/03/12 13:51:49.565 node.rs:225: [INFO] alloc first peer id for first region
2019/03/12 13:51:49.614 node.rs:136: [INFO] try bootstrap cluster
2019/03/12 13:51:49.771 node.rs:203: [INFO] alloc store id
2019/03/12 13:51:49.790 node.rs:326: [INFO] start raft store thread
```

The log is not complete, miss important info, eg, cluster id/store id/region id

**What did you see instead?**

All slog kvs are retained.

**Comment by breeswish** [comment]
For contributors who want to fix this:

Currently CaseTraceLogger does not output kv pairs:

https://github.com/tikv/tikv/blob/192cd352667fa52fb0f205a0ad517b12ae9f150e/components/test_util/src/logging.rs#L33

We can just refer to slog-term's implementation to output kv pairs:

https://github.com/slog-rs/term/blob/e5518f68b00f088c19aaa8238a23dac3a7aa8843/src/lib.rs#L394
