### ISSUE TITLE
error: ./target/debug/tikv-server does not enable sse4.2

### ISSUE THREAD

**Issue by jaltabike** [tikv/tikv#4367]
## Bug Report

**What version of Rust are you using?**

rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)

**What operating system and CPU are you using?**

Ubuntu 18.04.2 LTS
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**What did you do?**

run "make dev"

**What did you expect to see?**
Successful building and testing

**What did you see instead?**
When "checking binary ./target/debug/tikv-server for sse4.2",
I met an error:
error: ./target/debug/tikv-server does not enable sse4.2

**Comment by siddontang** [comment]
PTAL @overvenus

**Comment by overvenus** [comment]
Hi @jaltabike Have you installed gdb?

**Comment by jaltabike** [comment]
Hi, @overvenus 
Yes.

$ gdb --version
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

**Comment by siddontang** [comment]
oh, it is very strange to let user install gdb....

Btw, how about Windows.

**Comment by overvenus** [comment]
Could you `cat /proc/cpuinfo` ? @jaltabike 

------------------

I will remove sse4.2 check for `make dev`. @siddontang

**Comment by jaltabike** [comment]
```$ cat /proc/cpuinfo```
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
stepping	: 9
microcode	: 0x8e
cpu MHz		: 900.062
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 7200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
...
```

**Comment by jaltabike** [comment]
Now, "make dev" runs successfully.

**Comment by brson** [comment]
cc @shafreeck I'm finding that the new objdump-based check doesn't work here:

```
objdump --disassemble=_ZN7rocksdb6crc32c10ExtendImplIXadL_ZNS0_L10Fast_CRC32
EPmPPKhEEEEjjPKcm ./target/release/tikv-importer
objdump: option '--disassemble' doesn't allow an argument
```

```
objdump --version
GNU objdump (GNU Binutils for Ubuntu) 2.30
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by brson** [comment]
I can get the script to work if I remove the `=symbol` part of the command, but it is very slow since it's disassembling everything.

**Comment by shafreeck** [comment]
@brson 
I found that the `=symbol` feature first appeared on the newest version 2.32. https://sourceware.org/binutils/docs-2.32/binutils/objdump.html#objdump

We can not get a reliable result if disassemble all the binary other than the symbol.

**Comment by shafreeck** [comment]
Maybe we should use a common way to achieve this...

**Comment by shafreeck** [comment]
There is a complex solution

Find the addresses of the symbol first

```sh
> nm target/release/tikv-server | grep -A1 " _.*Fast_CRC32.*"
0000000000f64db0 t _ZN7rocksdb6crc32c10ExtendImplIXadL_ZNS0_L10Fast_CRC32EPmPPKhEEEEjjPKcm
0000000000f64e60 t _ZN7rocksdb6crc32c10ExtendImplIXadL_ZNS0_L10Slow_CRC32EPmPPKhEEEEjjPKcm
```

Disassemble using `--start-address` and `--stop-address`

```sh
> objdump --start-address 0x0000000000f64db0 --stop-address 0x0000000000f64e60 -d target/release/tikv-server | grep ".*f2.*0f 38.*crc32"
  f64df0:       f2 48 0f 38 f1 06       crc32q (%rsi),%rax
  f64dfa:       f2 48 0f 38 f1 46 f8    crc32q -0x8(%rsi),%rax
  f64e18:       f2 48 0f 38 f1 06       crc32q (%rsi),%rax
```

**Comment by shafreeck** [comment]
@brson I fix the bug with the solution mentioned above. Review this PR if you like: https://github.com/tikv/tikv/pull/4934

**Comment by BusyJay** [comment]
Thanks @shafreeck
