### ISSUE TITLE
Merge Msg::Proposal into Msg::Apply to reduce apply worker messages

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#4375]
`apply::Msg::Proposal` contains callbacks of proposals, which will be invoked when the proposals is applied. So for now, there are at least two messages are sent to apply workers `Msg::Proposal` and `Msg::Apply`, in fact they can be merged into one message, by this way we can simplify the apply workflow and may improve performance.

`apply::Msg`: 

https://github.com/tikv/tikv/blob/7165e0f3c10104810b7533985f48ea78e4eab07b/src/raftstore/store/fsm/apply.rs#L2200-L2212

**Comment by ngaut** [comment]
Good catch.
