### ISSUE TITLE
Correct style to compile tikv with latest kvproto

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#4384]
## Question

I have tried to compile TiKV with latest kvproto, and meet a problem about `#[cfg(lib_use_protobuf]`. Seems we must pass `--cfg lib_use_protobuf` to rustc, otherwise compile will fail.
I found that it works: `export RUSTFLAGS="--cfg lib_rust_protobuf"`, but as you can see it's ugly. Anyone has a better solution?
@nrc @brson @breeswish please take a look if you are free, thanks!

**Comment by breeswish** [comment]
Looks like this is a custom condition. Can we achieve this by using features?

**Comment by kennytm** [comment]
These should certainly be changed to `#[cfg(feature = "protobuf-codec")]` and `#[cfg(feature = "prost-codec")]` in kvproto.

**Comment by brson** [comment]
I agree with @kennytm.

**Comment by siddontang** [comment]
PTAL @nrc

**Comment by nrc** [comment]
This is already fixed as suggested on kvproto master.
