### ISSUE TITLE
tikv v2.1.6 compiled with warning

### ISSUE THREAD

**Issue by Xuanwo** [tikv/tikv#4394]
## Question

When I tried to compile tikv 2.1.6, I faced following error, plz check whether it has been fixed in master (so it will not happen in next release)

```
warning: unused import: `kvproto::errorpb::Error as ErrorHeader`
  --> src/storage/engine/rocksdb.rs:18:5
   |
18 | use kvproto::errorpb::Error as ErrorHeader;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

```

**Comment by siddontang** [comment]
@Xuanwo 

can you help us fix this?

**Comment by Xuanwo** [comment]
Ok

**Comment by Xuanwo** [comment]
Hi, @siddontang, I did some resaerch on this problem.

`fail_point!` will not be expanded will feature `no_fail`, so the `ErrorHeader` will not be used. I find out following ways to solve it, plz take a look.

- use `kvproto::errorpb::Error` directly in the macro
- use `use kvproto::errorpb::Error as ErrorHeader` in the macro
- Add `#[cfg(not(feature = "no_fail"))]` before the use

And I will make a PR to solve it~

**Comment by Xuanwo** [comment]
Problem solved in pr 4408， closed.
