### ISSUE TITLE
Upgrade jemalloc to v0.3

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4406]
Edit: A new version of jemallocator has been released. The task here is to upgrade jemalloc, jemalloc-sys, and jemalloc-ctl.

Should wait until after https://github.com/tikv/tikv/pull/4416#issuecomment-476242997 lands.

---

I've only just discovered that jemallocator/master is at version 0.3.0, but the latest jemallocator crate (the one we are linking to) is only at 0.1.9 and was published last July.

When I did the toolchain upgrade that refactored our jemalloc code I moved from @BusyJay's fork (I think) to the published version. I could have reverted jemallocator progress by doing so.

So maybe the published versions of jemallocator are deprecated. Not sure. I've asked [here](https://github.com/gnzlbg/jemallocator/issues/112#issuecomment-474689132).

We may need to change the dependency back to a git revision.

I marked this high priority because I think it is a release blocker to be on the "wrong" version of our allocator.

**Comment by brson** [comment]
jemallocator v0.3 is released

**Comment by brson** [comment]
jemalloc-ctl, which we depend on, still hasn't been updated for 0.3. I've been testing the pre-release version and will push to get it published.

**Comment by LykxSassinator** [comment]
`jemalloc` has already been upgraded to `v0.5.x`, this issue has become out-of-date.

Given that no further feedback regarding this issue has been reported, it can be safely closed.
