### ISSUE TITLE
protoc required by build but not included in Dockerfile

### ISSUE THREAD

**Issue by CrazyNash** [tikv/tikv#4422]
## Bug Report

**What version of Rust are you using?**

build in docker

**What operating system and CPU are you using?**

build in docker

**What did you do?**

```
cd tikv
docker build -t tikv:v1 .
```
```
   Compiling cop_datatype v0.0.1 (/go/src/github.com/pingcap/tikv/components/cop_datatype)
error: failed to run custom build command for `kvproto v0.0.1 (https://github.com/pingcap/kvproto.git#84f2c621)`
process didn't exit successfully: `/go/src/github.com/pingcap/tikv/target/release/build/kvproto-20e0446f3572c4d0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Invalid version of protoc (required 3.1.x), or protoc not installed

stdout:

', /root/.cargo/git/checkouts/kvproto-e694950bee90bc86/84f2c62/build.rs:65:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [release] Error 101
```

**What did you expect to see?**

All required tools are included in Dockerfile, so it builds without any dependency from host.

**What did you see instead?**

protoc missed resulted in build failure

**Comment by breeswish** [comment]
@zhouqiang-cl PTAL

**Comment by breeswish** [comment]
Thanks for your report! We have recently updated our build requirement but docker image is not updated. We will fix it soon.

**Comment by Hoverbear** [comment]
I'm working on a fix here.

**Comment by CrazyNash** [comment]
any update?

**Comment by Hoverbear** [comment]
@CrazyNash I have a testing branch here I'm just trying to get integrated with our release process. Could you try `make docker` with https://github.com/Hoverbear/tikv/tree/test-docker-hub ?

**Comment by CrazyNash** [comment]
I hit network issue, will try to fix that first

**Comment by CrazyNash** [comment]
@Hoverbear sorry for late response, but it failed in this way

![image](https://user-images.githubusercontent.com/39256431/56879532-b7e8da80-6a8b-11e9-8173-c0e3dd838f46.png)

**Comment by Hoverbear** [comment]
@CrazyNash I tried to reproduce on Windows 10 and Arch Linux and didn't experience the same problem. :( I did update the branch today, but I don't think anything I did relates to this problem. I'm puzzled how this is happening.

What OS and Docker version were you using?

**Comment by CrazyNash** [comment]
@Hoverbear CentOS 7.5 +Docker 18.09.2+ Go 1.12

**Comment by Hoverbear** [comment]
@CrazyNash I'm also running Docker 18.09. This is very odd. It seems it's actually finding a syntax error in some example of a upstream dependency.. 😵 Are you able to `make release` on your local machine?

Can you build https://github.com/bitflags/bitflags/releases/tag/1.0.1 on your local machine?

**Comment by BusyJay** [comment]
Now protoc is not required anymore.
