### ISSUE TITLE
Cannot find module providing package github.com/pingcap/pd/pd-client

### ISSUE THREAD

**Issue by ehds** [tikv/tikv#4434]
When I run the [example](https://github.com/tikv/tikv/blob/master/docs/clients/go-client-api.md) code ,I got the error like that:
```
build command-line-arguments: cannot load github.com/pingcap/pd/pd-client: cannot find module providing package github.com/pingcap/pd/pd-client
```
I searched this question on google, stackoverflow and issues, but I got nothing.

**Comment by siddontang** [comment]
@disksing 

seem now it is better for us to migrate to use client-go directly.

**Comment by disksing** [comment]
Hi @ehds, if you want to do some experimentation, try using https://github.com/tikv/client-go and there are examples in the example directory. Note that that project is still iterating, so the API may change in the near future.

**Comment by ehds** [comment]
> Hi @ehds, if you want to do some experimentation, try using https://github.com/tikv/client-go and there are examples in the example directory. Note that that project is still iterating, so the API may change in the near future.

OK, thanks for your help.
