### ISSUE TITLE
how to try titan store engine in recent tidb cluster

### ISSUE THREAD

**Issue by ericisme** [tikv/tikv#4466]
i have an tidb cluster in production env,

after i readed the article Titan 的设计与实现 (https://www.pingcap.com/blog-cn/titan-design-and-implementation/), than i want to try it.

but there some question i want to know before i do it,

as the article says,:

"在 TiKV 中使用 Titan
目前 Titan 在 TiKV 中是默认关闭的，我们通过 TiKV 的配置文件来决定是否开启和设置 Titan，相关的配置项包括 [rocksdb.titan] 和 [rocksdb.defaultcf.titan]， 开启 Titan 只需要进行如下配置即可"

is that means i only just to add this config to the tikvl.toml and restart tikv-server will done?

other, i want to try this operation,
add a new tikv instance into cluster, and only set this tikv [rocksdb.titan] enabled = true,
but the old tikv instance didn't apply this config, and i use store delete command to tomb the old tikv instance, do it one by one, after all tikv instance is replaced.
after i using titan, and i will check the range query performce if i cant accpet, if i didn't accpet the perfomence, i want to rollback the none-titan tikv, can i use the operation that one by one to replace titan-tikv to none-titan-tikv?

**Comment by yiwu-arbug** [comment]
Thank you for your interest in Titan. Titan is not released yet, and only available in master branch. It is not suitable for production use, yet. For test, if you build tikv from master, yes, adding the config and restart should be sufficient to enable Titan. But Titan does not support rollback to be without Titan right now.

**Comment by ericisme** [comment]
@yiwu-arbug thanks

**Comment by lnparker** [comment]
> Thank you for your interest in Titan. Titan is not released yet, and only available in master branch. It is not suitable for production use, yet. For test, if you build tikv from master, yes, adding the config and restart should be sufficient to enable Titan. But Titan does not support rollback to be without Titan right now.

hello, can titan now be used for production? thank u

**Comment by Connor1996** [comment]
@lnparker Yes~
