### ISSUE TITLE
Link tcmalloc statically

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4471]
## Feature Request

**Is your feature request related to a problem? Please describe:**

After https://github.com/tikv/tikv/pull/4370 tikv can be built with tcmalloc instead of jemalloc, but the tcmalloc crate doesn't actually build tcmalloc, but assumes it exists.

**Describe the feature you'd like:**

Make the tcmalloc crate implement tcmalloc. [This PR](https://github.com/jmcomets/tcmalloc-rs/pull/3) does so. After the above two PRs land, upgrade tcmalloc.

**Describe alternatives you've considered:**

Not adding tcmalloc to tikv_alloc.

**Teachability, Documentation, Adoption, Migration Strategy:**

Bleh.

**Comment by siddontang** [comment]
@brson 

If we can do this, which means imbedding gperftools statically, I think we can let TiKV support CPU/Mem profile directly, right? 

/cc @breeswish

**Comment by brson** [comment]
@siddontang yeah it has cpu profiling, heap profiling, and heap checking, and works with the pprof tool.

**Comment by breeswish** [comment]
Interesting, I guess the most notable benefit is memory related profiling. My previous attempt over CPU profiling doesn't need tcmalloc: https://github.com/tikv/tikv/pull/3971

BTW are we going to opt-in tcmalloc to replace jcmalloc, or just leaving a choice?

**Comment by siddontang** [comment]
I prefer just leaving a choice. But if we can prove tcmalloc has better performance, we can enable it by default.

**Comment by siddontang** [comment]
hello @brson 

Can we use your branch to try in TiKV at first, I think we don't need to wait the PR merged.

**Comment by brson** [comment]
I would definitely not pick tcmalloc over jemalloc without very convincing evidence. Jemalloc looks to be much more developed and developer friendly. tcmalloc has almost no documentation and comes with dire warnings about using the wrong unwinder. I mostly see this as an extra tool, and an easy way to compare allocators.

@siddontang I will put together a branch that can be used for testing.

**Comment by siddontang** [comment]
Got it @brson
