### ISSUE TITLE
Utilize Criterion's new feature iter_batched_ref

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4508]
## Feature Request

`iter_batched_ref` / `iter_batched` is a replacement for `iter_with_setup` available in latest Criterion, which provides more accurate time measurement. We can utilize these two functions to make our benchmark results more accurate.

**Comment by jswh** [comment]
I did something work, but not sure if there is a change to to use iter_batched_ref as the document described

> If the setup value implements Drop and you don't want to include the drop time in the measurement, use iter_batched_ref, otherwise use iter_batched.

**Comment by breeswish** [comment]
@jswh Yes, in most of the time we only want to test how long it takes for a single iteration and we don't want to count the duration of Drop.

**Comment by hk1997** [comment]
Hello, I'm new to this project and looking to make my first PR.  
Is this issue suitable for me?

**Comment by breeswish** [comment]
Close for #4539
