### ISSUE TITLE
Why did this test fail?  

### ISSUE THREAD

**Issue by ZhangHanDong** [tikv/tikv#4510]
## Question

the PR test run failed: https://github.com/tikv/tikv/pull/4370 

![image](https://user-images.githubusercontent.com/27893/55882032-678e0380-5bd6-11e9-9eee-16e1475cd93c.png)

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
