### ISSUE TITLE
Support GiB and its families

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#4541]
Technically, units with binary prefixes are based on 2, for example, 1 GiB = 1024 MiB, and without the binary prefixes are based on 10, for example, 1 GB = 1000 MB.

TiKV only supports units without binary prefixes and treats them as if they are prefixed. To make it more precise, we need to support GiB and its families too. And to keep compatibility, GB and its families should still be treated as they are.

**Comment by siddontang** [comment]
I remember that we have discussed this problem a long time before. I think to make us less trouble, I prefer treating GB and GiB the same...

**Comment by siddontang** [comment]
seem CockroachDB met the same problem before https://github.com/cockroachdb/cockroach/issues/4735

**Comment by BusyJay** [comment]
Agree. The purpose of this issue is to add support for *iB in ReadableSize parser.

**Comment by siddontang** [comment]
Got it

**Comment by lysu** [comment]
@BusyJay  maybe this is good to the version downgrade..

I had try master code then downgrade to 3.0.rc1...but meet this

```
thread 'main' panicked at 'invalid auto generated configuration file "/data/deploy/data/last_tikv.toml", err only B, KB, MB, GB, TB, PB are supported: "10MiB" for key `readpool.storage.stack-size`', src/config.rs:1122:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook
             at libstd/panicking.rs:227
   3: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   4: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   6: tikv_server::main
             at src/config.rs:1122
   7: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
   8: main
   9: __libc_start_main
  10: <unknown>
```

then I need manual to replace MiB back to MB for every nodes....

maybe some big cluster upgrade need take care this problem :D

**Comment by BusyJay** [comment]
Sorry to see that happen, but it's intended not to support version downgrade.
