### ISSUE TITLE
Support batchSplit in kvserver API

### ISSUE THREAD

**Issue by disksing** [tikv/tikv#4572]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB needs to split a region into many regions when creating a table with table partition. https://github.com/pingcap/tidb/pull/10221

**Describe the feature you'd like:**

Like old `splitRegion` command, but can set multiple keys to split a region into a batch of regions using only 1 rpc call.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by siddontang** [comment]
@nolouch 

Another thing I want to care about is not to merge these manually split regions. Now the time is 1h, after that, the merge operator can choose these regions, but mostly, we don't want to merge them.

**Comment by disksing** [comment]
@siddontang PD will **not** merge the regions because partition tables have different table id.

**Comment by disksing** [comment]
Already fixed: https://github.com/tikv/tikv/pull/5458
