### ISSUE TITLE
Error report not precise when fuzzer fail

### ISSUE THREAD

**Issue by whoiscc** [tikv/tikv#4585]
## Bug Report

**What version of TiKV are you using?**

3.0.0-beta.1

**What operating system and CPU are you using?**

macOS 10.14.4, core I5

**What did you do?**

```
make build
cargo run --package fuzz -- run honggfuzz  fuzz_coprocessor_codec_decimal
```

The fuzzer is failed in my environment because some unknown reason, and the output looks like this:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target/debug/fuzz run honggfuzz fuzz_coprocessor_codec_decimal`
error: no such subcommand: `hfuzz`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Honggfuzz exited with code Some(101)" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The line says `no such subcommand` is very confusing.

Also, the afl fuzzer also fails on my machine with this output:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/fuzz run Afl fuzz_coprocessor_codec_decimal`
error: no such subcommand: `afl`

	Did you mean `doc`?

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "error building afl instrumented binary, exit code Some(101)" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by siddontang** [comment]
PTAL @breeswish

**Comment by ice1000** [comment]
Could you please run `cargo install honggfuzz` and try again?

**Comment by ice1000** [comment]
I'm getting this compilation error after trying to update the currently dependent honggfuzz library :worried: :

```
--- stderr
linux/bfd.c:26:10: fatal error: bfd.h: No such file or directory
 #include <bfd.h>
          ^~~~~~~
compilation terminated.
```

**Comment by ice1000** [comment]
According to the [documentation](https://github.com/tikv/tikv/tree/master/fuzz#honggfuzz), you'll need to install the fuzzers (like for honggfuzz, use `cargo install honggfuzz --version 0.5.34`) prior to running the fuzzers.

However, I've created a PR (#4586) that tries to install the fuzzers automatically.

**Comment by whoiscc** [comment]
Installing honggfuzz manually works, however, this is unrelated to the original problem.

**Comment by breeswish** [comment]
We need to enhance the error process for the fuzzing cli. PRs are welcome!
