### ISSUE TITLE
test_region_change_observer fail

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#4594]
## Bug Report

<https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/3752/pipeline/135/>

**TiKV Version:** https://github.com/5kbpers/tikv/tree/50103159042c47962d21d3315a1ac832accf0d39

PTAL @MyonKeminta @hicqu

**Comment by MyonKeminta** [comment]
`must_add_peer` failed on a NodeCluster.
@overvenus PTAL

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
