### ISSUE TITLE
Change batch limit executor's tests to test behaviour instead of implementation

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4603]
## Feature Request

Currently the `BatchLimitExecutor`'s unit test heavily depends on the internal implementation, which is generally considered as a bad practice. We should rewrite these tests to test behaviour instead, e.g. what we expect for the first call, what for the second call, under different scenarios, etc.

**Comment by andylokandy** [comment]
The only internal usage in tests I found is just the `remaining_rows` in `test_limit_remaining`, and it appears just once. Are there any other places I should notice?

**Comment by breeswish** [comment]
@andylokandy Nop. However these tests have a fundamental problem, which is, if you follow the way that these tests write (using the MockExecutor in that module), you will fall into depending on internal implementations to test specific behaviour, otherwise the test would be very complex.

**Comment by breeswish** [comment]
@andylokandy You may refer to https://github.com/tikv/tikv/blob/master/src/coprocessor/dag/batch/executors/selection_executor.rs to see how "good" tests should be.
