### ISSUE TITLE
Support IPV6 address

### ISSUE THREAD

**Issue by rleungx** [tikv/tikv#4693]
## Feature Request
Currently, TiKV doesn't support IPV6 address. 
<img width="1238" alt="Screen Shot 2019-05-14 at 8 36 35 PM" src="https://user-images.githubusercontent.com/35896542/57699837-4021cf00-768b-11e9-8daf-91ecee793d5d.png">
We may need to support it in the future.

**Comment by kennytm** [comment]
A valid IPv6 socket address should be written as `[::1]:20160` — note the square brackets. If that `::1:20160` comes from user's settings it would be user's mistakes.

**Comment by rleungx** [comment]
Fixed by https://github.com/tikv/grpc-rs/pull/283
