### ISSUE TITLE
cargo audit error

### ISSUE THREAD

**Issue by koushiro** [tikv/tikv#4703]
## Bug Report

**What did you do?**

>➜  tikv git:(master) cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 24 security advisories (from /home/koushiro/.cargo/advisory-db)
    Scanning Cargo.lock for vulnerabilities (306 crate dependencies)
error: Vulnerable crates found!

>ID:	 RUSTSEC-2019-0003
Crate:	 protobuf
Version: 2.0.4
Date:	 2018-06-08
URL:	 https://github.com/stepancheg/rust-protobuf/issues/411
Title:	 Out of Memory in stream::read_raw_bytes_into()
Solution: upgrade to: 

>error: 1 vulnerability found!

It makes Jenkins job failed.

**Comment by Hoverbear** [comment]
From @zhangjinpeng1987 

![image](https://user-images.githubusercontent.com/130903/57826844-d7edee80-7759-11e9-80cc-93eb64374f8e.png)

**Comment by Hoverbear** [comment]
There is a fix pending on our internal infrastructure.

**Comment by kennytm** [comment]
We're currently only ignoring the audit, but the actual fix is still not applied. Let's keep this open until protobuf is updated and the audit is re-enabled.

**Comment by BusyJay** [comment]
The error was passed and daily audit check has been setup for quite a while.
