### ISSUE TITLE
MvccProperty should consider delete version

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#4740]
## Bug Report

We decide whether need to gc based on MvccProperty max row version. But if the compaction is not performed on the SSTs after GC, the max row version would still large so that GC is triggered again and again which is unnecessary.

https://github.com/tikv/tikv/blob/master/src/storage/mvcc/reader/reader.rs#L432

maybe we can add a delete_version to `MvccProperty`, once delete_version/num_version exceeds a threshold, we can think it is the case that GC is already performed, but just compaction process doesn't touch the SST and skip GC.

**Comment by siddontang** [comment]
how do you find this problem, through metrics?

**Comment by siddontang** [comment]
how do you find this problem, through metrics?

**Comment by Connor1996** [comment]
@MyonKeminta tests GC and finds that GC is always working even there is no new write. The log shows that GC is not skipped because the `max_row_version` always exceeds the threshold. Maybe this case is not the actual reason for his test but seems it really exists.

**Comment by MyonKeminta** [comment]
This happened on my test cluster for ResolveLocks. The symptom is, after normally running without heavy writting and a rebooting, one of the TiKVs stopped skipping GC and scans every region, which can be seen in metrics. Then I added logs to the `need_gc` function and found that nearly all regions has `max_row_versions == 132`. Then this symptom disappeared after a full compaction.

**Comment by zhangjinpeng1987** [comment]
@MyonKeminta Any update for this issue?

**Comment by MyonKeminta** [comment]
The GC problem I mentioned is finally confirmed not caused by issue, and that problem doesn't matter much and will no longer exist with compaction filter. Then the deleted version information is already added to MvccProperties before (https://github.com/tikv/tikv/pull/7172). I think this issue can be closed.
