### ISSUE TITLE
storage::lock_manager::waiter_manager::tests::test_waiter_manager failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4742]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/4717/pipeline

**Comment by breeswish** [comment]
Failed again in https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/5046/pipeline

**Comment by youjiali1995** [comment]
I have changed the timeout of `recv`, and there are no more failures so far. Close it.
