### ISSUE TITLE
*: Many possible spelling mistakes.

### ISSUE THREAD

**Issue by xiekeyi98** [tikv/tikv#4758]
## Bug Report

**What version of TiKV are you using?**

N/A

**What operating system and CPU are you using?**

N/A

**What did you do?**
![image](https://user-images.githubusercontent.com/7782671/58240989-a6d77480-7d7e-11e9-890a-255becbc22e6.png)

As the pic says, we could fix these spelling mistakes to make the code fresh.

**Comment by BusyJay** [comment]
Cool! Can you send a PR to fix these?
