### ISSUE TITLE
Relax batch table scan & batch index scan compatibility check

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4762]
## Feature Request

Currently we will fallback all requests that contains Enum / Set column in the table/index scan to non-batch executors. However, as long as we don't need to decode these columns, it is fine to use batch table/index scan executor.

**Comment by jswh** [comment]
Just set the types to pass the should batch test. Is there any thing else to do?

**Comment by breeswish** [comment]
@jswh Looks like no.
