### ISSUE TITLE
What is the relationship between `sync-log` and `wal-bytes-per-sync`

### ISSUE THREAD

**Issue by Yriuns** [tikv/tikv#4828]
## What is the relationship between `sync-log` and `wal-bytes-per-sync`

I know that each `TiKV` instance contains two `RocksDB` instances, one is `Raft RocksDB`, stores `raft log` and the other stores `key-value`.
I also know that in a standard raft write process, the raft cluster should persist log before respond `success`.

My question are:
1. If `wal-bytes-per-sync` is not `0`, when we calls something like `save_to_raft_RocksDB(log)`, the log will be put in the `memtable` of `RocksDB` and return `ok` to the `RocksDB client`. But the log might be waiting to be persisted into the `WAL` in the background. So if the power is cut off at this time, will the log be lost?
2. The introduction of `sync-log` says 
    ```toml
    ## Whether to force to flush logs.
    ## Set to `true` (default) for best reliability, which prevents data loss when there is a power
    ## failure.
    sync-log = true
    ```
    I wonder if it means that, if I set `sync-log = true`, `Raft RocksDB` will save every write into `WAL`? In other words, it will overwrite `wal-bytes-per-sync` (set it to 0)?

**Comment by breeswish** [comment]
@Connor1996 Could you help answer this?

**Comment by Connor1996** [comment]
Not quite sure. /cc @yiwu-arbug

**Comment by yiwu-arbug** [comment]
@Yriuns your understanding for the options are all correct. `sync-log=true` sync WAL for every write, while if `sync-log=false` the WAL is being sync per `wal-bytes-per-sync`.

**Comment by Yriuns** [comment]
@yiwu-arbug  Thanks a lot! So even if `raft` responds `ok`, there is still the possibility of losing at most `wal-bytes-per-sync` bytes data. Have I understood correctly?

**Comment by yiwu-arbug** [comment]
@Yriuns yes, if `sync-log=false`.

**Comment by Yriuns** [comment]
@yiwu-arbug Thank you very much!
