### ISSUE TITLE
why do we need to install zlib manually before compiling TiKV?

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4884]
## Question

```
See also "/home/ec2-user/tikv/target/release/build/libtitan_sys-38cfcaa1f85522bd/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find zlib (missing: ZLIB_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/ec2-user/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/9940d00/librocksdb_sys/rocksdb/cmake/modules/Findzlib.cmake:17 (find_package_handle_standard_args)
  cmake/rocksdb_flags.cmake:35 (find_package)
  CMakeLists.txt:11 (include)

```

I have to run `sudo yum install zlib-devel` before. IMO, we should build and link zlib statically.

**Comment by yiwu-arbug** [comment]
RocksDB cmake script assume linking with system provided zlib when `WITH_ZLIB=1`, which we set in "build.rs". We need to update our "build.rs" to pass zlib link path and set compile flags instead.

**Comment by siddontang** [comment]
another thing is that why do we need to install gflags manually too?

**Comment by BusyJay** [comment]
It doesn't link to the system zlib before. I guess maybe recent changes break the behavior.

**Comment by yiwu-arbug** [comment]
It doesn't seems to me there's recent change to the behavior. How we link with zlib doesn't change since https://github.com/pingcap/rust-rocksdb/commit/fbee9afdfc8d120935fa9f91d7629a74f86d721d, and how rocksdb cmake script handle zlib doesn't change since https://github.com/facebook/rocksdb/commit/185ade4c0c91288ae268f6ceca8310421325cea4 ...

**Comment by yiwu-arbug** [comment]
@siddontang regarding gflags, on my side it only warns gflags not exist, but it continue to build without error. Is it not the case on your side?

**Comment by yiwu-arbug** [comment]
Sent https://github.com/pingcap/rust-rocksdb/pull/303 for zlib fix.

**Comment by siddontang** [comment]
> we can turn off gflags warning with WITH_GFLAGS=OFF. Just want to confirm, are we building rocksdb tools (ldb, sst_dump, db_bench, etc..) with rust-rocksdb or tikv?

@yiwu-arbug 

we embed ldb in TiKV.

**Comment by siddontang** [comment]
maybe we can build a similar tool in rust-rocksdb which not uses gflags.

**Comment by yiwu-arbug** [comment]
should have been fixed a while ago.
