### ISSUE TITLE
Turn on cargo pipelining

### ISSUE THREAD

**Issue by brson** [tikv/tikv#4897]
Cargo pipelining improves compile time noticeably. Upgrade the toolchain, then turn it on.

Since it requires setting an environment variable, probably it needs to be done in the makefile, then instructions added to the readme for doing it manually with plain cargo.

Some old links and instructions here: https://github.com/tikv/tikv/issues/4166

**Comment by siddontang** [comment]
@brson 

Please do it ASAP, I can't wait to use it.

**Comment by brson** [comment]
Fixed.
