### ISSUE TITLE
support HTTP API to handle configuration 

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4901]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Our contributor @liufuyang uses K8s to deploy TiKV, and finds that it is hard to know the configuration of running TiKV. 

**Describe the feature you'd like:**

Provide some HTTP APIs to let us handle configurations, e.g:

```
// Get the configuration of TiKV
GET /config
GET /config?section=xxx 
GET /config?section=xxx&key=xxx

Update some configuration of TiKV
PUT /config -d '{ section: { key : value}}'
```

**Describe alternatives you've considered:**

We can also use tikv-ctl to do this, but mostly I think using an HTTP way is better.

PTAL @liufuyang @BusyJay

**Comment by liufuyang** [comment]
I think it is nice to add some GET config endpoints as we already have some http endpoints on the server.

But I am not sure whether or not  to support the utility to update configs as well. Will it make you have to maintain two places in order for the update config feature to work when some of the configs changes or new configs being added?  🤔

**Comment by siddontang** [comment]
You can add GET at first.

Now we support all(get, update config) through gRPC in tikv-ctl, we plan to migrate all to HTTP so we can write a unified ctl tool to operate PD, TiKV and TiDB.

**Comment by Hoverbear** [comment]
In #4444 we talked about adding Actix, so this could be used here too

**Comment by jlerche** [comment]
I would like to work on this if nobody else has already started.

**Comment by Hoverbear** [comment]
Thanks @jlerche . Do you think you could start with supporting `get` for now?

Since you're not (at the moment) a member of the TiKV project I can't assign you, but we'd really love to let you tackle this!

Is there any way we can support you? You can chat with me on Slack if you have any roadblocks. :)

**Comment by jlerche** [comment]
`get` sounds like a good start. I will definitely be pinging you on slack as I work through this 😝

**Comment by liufuyang** [comment]
@jlerche I am in the process to try to get https://github.com/tikv/tikv/pull/4444/ this in, which added some extra http endpoint. And my plan was to add those configuration http endpoints as well afterwards. The reason I am waiting to not start add config related endpoints now is that I am waiting to have a decision here https://github.com/tikv/tikv/issues/4906 - where we are talking whether we will introduce some web frameworks. If we do, adding some new endpoints would be hopefully easier. (Which also means if you work on this now, a big part of your changes might need some rework.)

So I would advice you wait for a while before starting, unless you really could not find any other simple issue to work on :) 

Keep an eye on the decision here https://github.com/tikv/tikv/issues/4906 and let me know what you think :)

**Comment by jlerche** [comment]
No problem, waiting for #4906 makes a lot of sense!

**Comment by liufuyang** [comment]
@jlerche as #4444 is merged and #4906 is still in discussion, have you got any tasks on your hand to keep you busy? Otherwise I guess it might be okay now to at least start looking into how to add those HTTP API to handle configurations. Do you still want to take on this?

**Comment by jlerche** [comment]
Yes I’m still up for working on this! I can definitely start now although it seems perhaps it might be worthwhile to still wait for #4906?

**Comment by liufuyang** [comment]
@jlerche I think you can start on this now, probably the only file you need to work on is `src/server/status_server.rs`. Ping me when have any progress or questions, I would like to see how this can be done as well :)

**Comment by jlerche** [comment]
Closed by #4997

**Comment by skyline75489** [comment]
Seems this issue can be closed now?

**Comment by BusyJay** [comment]
Indeed, thanks for reminding.
