### ISSUE TITLE
should use a larger value for the default block cache 

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4904]
## Question

Now we use shared block cache by default and the default value is "1GB", which means that if we forget to set it explicitly and not set previous RocksDB block caches of different column families, we will only use 1GB.

I think we should keep the same as before, if not set, may calculate the block cache. Mostly, we will use half of the memory.

**Comment by yiwu-arbug** [comment]
I believe our default cache size is 45% physical memory.  Do you find it not being the case?
https://github.com/tikv/tikv/blob/master/src/storage/config.rs#L96

**Comment by yiwu-arbug** [comment]
The config template has a ="1GB" value, but it is just an example.

**Comment by siddontang** [comment]
got it, seem I made a mistake. sorry.
