### ISSUE TITLE
how to disable gRPC batch mechanism

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#4905]
## Question

I use go-ycsb and set TiKV max batch size to 0 to disable gRPC batch explicitly, but to my surprised, I still find gRPC uses batch:

![image](https://user-images.githubusercontent.com/1080370/59566041-12b2b180-908d-11e9-8746-a73fc91f7b90.png)

How to disable it?

**Comment by hicqu** [comment]
How do you set `max-batch-size` to 0?

**Comment by siddontang** [comment]
https://github.com/pingcap/go-ycsb/blob/master/db/tikv/db.go#L37

```
-p tikv.batchsize = 0
```

**Comment by hicqu** [comment]
Please try `-p "tikv.batchsize=0"`.
