### ISSUE TITLE
Verify range for Table / Index scan executor

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4907]
## Feature Request

In coprocessor, we need to report errors when table ranges are sent to index scan executor, or index ranges are sent to table scan executor.

**Comment by lpan** [comment]
Hi, I am interested in working on this :slightly_smiling_face: I am really new to this project. Do you have any resources/pointers for me to get started on this?

**Comment by breeswish** [comment]
@lpan Thanks for the interest! You need to add code to verify whether or not key meets the format (for index scan, it should be prefixed with tXXXXXXXX_iXXXXXXXX and for table scan it should be prefixed with tXXXXXXXX_rXXXXXXXX) in `TableInnerExecutor::decode_row`, `IndexInnerExecutor::decode_row`, `BatchTableScanExecutor::process_kv_pair` and `BatchIndexScanExecutor::process_kv_pair`.

**Comment by lonng** [comment]
@breeswish I think the easiest way is to check all ranges in `builder.rs`

**Comment by breeswish** [comment]
@lonng 
- It cannot avoid invalid ranges like `[tXXXXXXX1_r, tXXXXXXX2_r)`
- End key is not required to be in format `tXXXXXXXX_r` since we will only scan keys < end key.

**Comment by lpan** [comment]
@breeswish @lonng thanks so much everyone! I will dive into it soon. Will keep you posted if I run into any questions or blockers 🙂

**Comment by lpan** [comment]
Hey everyone, I am planning to do one of the [training courses](https://www.pingcap.com/blog/distributed-systems-training-in-go-and-rust/) before I start digging into TiKV. :slightly_smiling_face: 

Anyone feels free to take over this issue while I am doing the course! Thanks!

**Comment by FateTHarlaown** [comment]
Hi, I'm trying to fix this.
should we add a new type of error for wrong type of key range ?  Maybe the meaning of `Storage` and `EvaluateError` is not suitable.

**Comment by breeswish** [comment]
@FateTHarlaown Hi, thanks for your interest. It can be an evaluation error since this error happens when evaluating the coprocessor request (invalid request, or more precise, invalid range).

**Comment by breeswish** [comment]
Already finished.
