### ISSUE TITLE
TiKV's log is too large

### ISSUE THREAD

**Issue by yiran-idea** [tikv/tikv#4952]
Tikv logs will not be deleted circularly. One of our tikv instance logs reaches 1.4T (4T hard disk).How to set up a fixed number of days, or a fixed size, for tikv logs?

**Comment by hicqu** [comment]
Please set this field in your tikv.toml:
```
log-rotation-timespan = "24h"
```
If it's not supported yet, please upgrade your TiKV to latest versions.

**Comment by howaboutsynergy** [comment]
Hey, any idea why the log file size although seen as 1036 bytes by `ls -la` and `stat`, is reported as 140Meg by `du -h` and `compsize`, as seen here: https://github.com/kilobyte/compsize/issues/27#issue-502197861

I mean, why the wrong file size? maybe's something I did?

**Comment by Hoverbear** [comment]
@howaboutsynergy Please note we don't recommend running TiKV on COW filesystems like btrfs or zfs. 

But you may wish try disabling COW on the data dir of TiKV? https://wiki.archlinux.org/index.php/Btrfs#Disabling_CoW
