### ISSUE TITLE
compact command cannot flush all memtable

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4956]
## Bug Report

Occurs from v2.0.0 beta to v3.0.0. Previous versions are not tested.

![image](https://user-images.githubusercontent.com/1916485/59988937-847f9200-966f-11e9-95f6-adf54cc0504b.png)

When using tikv-ctl to compact the tikv:

```
./tikv-ctl --host 172.16.30.40:30171 compact -c default      
store:"172.16.30.40:30171" compact db:KV cf:default range:[[], []) success!
./tikv-ctl --host 172.16.30.40:30171 compact -c write  
store:"172.16.30.40:30171" compact db:KV cf:write range:[[], []) success!
./tikv-ctl --host 172.16.30.40:30171 compact -c lock 
store:"172.16.30.40:30171" compact db:KV cf:lock range:[[], []) success!
```

Inspected that memtable of write and lock cannot be fully flushed. However default CF is fine.

**Comment by zhangjinpeng1987** [comment]
@Little-Wallace PTAL

**Comment by Little-Wallace** [comment]
Cf::lock and cf::write both set **memtable_prefix_bloom_size_ratio** to 0.1,  which would apply for **memtable_prefix_bloom_size_ratio** * **write_buffer_size** byte memroy to create **DynamicBloom**, and this operation use the same allocator with **Memtable**.
Here is code: [memtable.cc](https://github.com/facebook/rocksdb/blob/v6.1.2/db/memtable.cc#L117)
