### ISSUE TITLE
Change error, panic, and log outputs from Debug to Display

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#4960]
## Feature Request

Currently in many places we use Debug to output errors, which is not a good way since we mostly want customized outputs (like hex output keys).

**Comment by brson** [comment]
"{:?}" is used to create error types, in log messages and in panic messages. "{}" should be used everywhere possible.

Exceptions where it's fine to use "{:?}" include in test cases and assertions. "{}" should still be preferred, but it's probably not worth introducing any extra code for them.
