### ISSUE TITLE
update crate and reduce the crate different versions 

### ISSUE THREAD

**Issue by uvd** [tikv/tikv#4976]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**
update crate and reduce the crate different versions 

- [x] hashbrown  [hashbrown_0.5](https://github.com/rust-lang/hashbrown/releases/tag/v0.5.0)    #4972 
- [ ] hashbrown remove
- [x] lazy_static 1.3.0 #4977 
- [x]  tempdir replace 3.0 [tempfile](https://github.com/Stebalien/tempfile/releases/tag/v3.0.8) #4978 
- [ ] nom  5.0
- [ ] rand  reduce different versions  update crate
- [ ] crossbeam  reduce different versions  update crate
- [ ]  arbitrary reduce different versions  update crate
- [ ]  unicase reduce different versions  update crate
- [ ] winapi reduce different versions update crate

**Comment by Connor1996** [comment]
according to https://github.com/tikv/tikv/issues/5002, you can just remove `HashBrown`
