### ISSUE TITLE
Do not panic when failed to write log

### ISSUE THREAD

**Issue by sunxiaoguang** [tikv/tikv#5042]
## Feature Request
Do not panic when failed to write log

**Is your feature request related to a problem? Please describe:**
TiKV is going to panic when fails to write log. Although it makes debugging harder without log, but panicking seems to be a little overreacting for this scenario.
 
**Describe the feature you'd like:**
Do not panic when logger encounters error

**Describe alternatives you've considered:**
Change file logger only and make ti not returning any error.  

**Teachability, Documentation, Adoption, Migration Strategy:**
NA

**Comment by sunxiaoguang** [comment]
components/tikv_util/src/logger/mod.rs

![image](https://user-images.githubusercontent.com/3982329/60776732-db519500-a160-11e9-9267-8f2f787ac7d4.png)

Simply remove `panic!("logger encountered error");` would work

**Comment by siddontang** [comment]
maybe we can output to the stderr, not panic. 

/cc @BusyJay

**Comment by sunxiaoguang** [comment]
Looks like the fatal_logger is actually going to write to stderr. If we all agree that it shouldn't panic under this scenario, simply remove panic! and `TiKV cannot continue working` message from fatal log would work. 

> maybe we can output to the stderr, not panic.
> 
> /cc @BusyJay

**Comment by divinerapier** [comment]
I am a beginner, and I want to try it, please give me a change, thank you.
