### ISSUE TITLE
KV transaction throughput significantly drops off

### ISSUE THREAD

**Issue by darren-west** [tikv/tikv#5055]
### Version:
Version 2.1.12
Specifically the docker image - pingcap/tikv:v2.1.12 

### Environment:
Running a cluster of 3 TiKV and  PD in kubernetes.

### What we are doing:
We inserted approximately 500,000 key/values with a size of at most 4kb. Using the [go-client](https://github.com/tikv/client-go), we perform two sets and one get as part of the transaction. 

### What we expect:
The transaction time to remain consistent. 

### What happens:
The transaction time/commit time increased 5 times.  Memory and CPU seem consistent. 

The only obvious increase is scheduler command duration.
![image](https://user-images.githubusercontent.com/20109821/60890689-bb4ece00-a253-11e9-8476-fe010033858b.png)

Restarting the cluster resolves the issue.

**Comment by disksing** [comment]
Hi @darren-west , does workload have some differences before and after the time point(around 13:23) when latency starts to increase? Please also take a look at the grafana panels for grpc message count and grpc duration.

**Comment by darren-west** [comment]
@disksing this proved to be an IOPS issue. Thanks for your help.
