### ISSUE TITLE
scan(Iter) get deleted keys

### ISSUE THREAD

**Issue by tdzl2003** [tikv/tikv#5058]
## Bug Report

**What version of TiKV are you using?**
3.0.0-beta.1

**What operating system and CPU are you using?**
 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Ubuntu 18.04

**What did you do?**
make some change of transaction basic sample in [client-go](https://github.com/tikv/client-go), do scan(`txn.Iter` with prefix) after deletion

```go
        // delete
	err := dels([]byte("key1"), []byte("key2"))
	if err != nil {
		panic(err)
	}

	// scan
	ret, err := scan([]byte("key"), 10)
	for _, kv := range ret {
		fmt.Println(kv)
	}
	if err != nil {
		panic(err)
	}
```

**What did you expect to see?**
I expect to see no key because all of them was deleted.

**What did you see instead?**
I see every deleted key with 0 byte content
```
key1 =>  ([])
key2 =>  ([]) 
```

Whose duty should it be to filter deleted keys? server? client driver? user program?

**Comment by tdzl2003** [comment]
https://github.com/tikv/website/blob/c59bc396f53d3adb5029d9274c7ac7d88294709f/content/deep-dive/key-value-engine/rocksdb.md#compactrange

Answer to myself: I think GC process will delete these keys called `tombstone entries`, but it's still possible to get tombstone entries before they are collected. So user program still have duty to filter result of scanning.

Tombstone entries should not be too much if there's enough data.

**Comment by disksing** [comment]
Hi @tdzl2003 Could you please provide the changed test code you were using?

**Comment by disksing** [comment]
Hi @tdzl2003 It turns out to be a bug of client-go. I'm fixing it.
