### ISSUE TITLE
Broken link in Wiki (again)

### ISSUE THREAD

**Issue by smthpickboy** [tikv/tikv#5064]
There's #4988 reporting broken link couple days ago, but there're still problems. README.md has a link to https://github.com/tikv/tikv/wiki/TiKV-Documentation, and most links in this page, are broken, such as https://github.com/tikv/tikv/blob/master/docs/op-guide/deploy-tikv-using-docker-compose.md .

The links in https://github.com/tikv/tikv/wiki are fine, though.

**Comment by disksing** [comment]
Thanks for your report @smthpickboy 
Please take a look @dcalvin

**Comment by dcalvin** [comment]
Thanks @smthpickboy. We just restructured the documentation on Wiki so the link to it might be changed but not updated in Readme. That explained why links in https://github.com/tikv/tikv/wiki are fine.

**Comment by dcalvin** [comment]
Closed as Merged
