### ISSUE TITLE
build_release is not appear in makefile rules

### ISSUE THREAD

**Issue by dhcn** [tikv/tikv#5069]
## Bug Report
build_release is not appear in makefile rules， but it appear in Dockerfile
**What version of TiKV are you using?**

**What operating system and CPU are you using?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by disksing** [comment]
@dhcn Thanks for feedback. We will start to get it fixed.

**Comment by siddontang** [comment]
#5017 fixes it.
