### ISSUE TITLE
Support generating flame graph from HTTP API

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5124]
## Feature Request

In https://github.com/tikv/tikv/pull/3971 we added support for the cpu profiler, which is able to start profiling via its interface. Together with https://github.com/jonhoo/inferno we should be able to provide an easy-to-use interface to capture flame graph directly, from our HTTP API. It is much more friendly to use than running `perf record ... && perf script ... && perl ....`, especially considering that no extra dependencies are needed.

Related: https://github.com/tikv/tikv/issues/4195

**Comment by jlerche** [comment]
I can work on this if nobody else is.

**Comment by siddontang** [comment]
great, @jlerche

**Comment by breeswish** [comment]
@jlerche Feel free to ask for help!

**Comment by siddontang** [comment]
PTAL @zhouqiang-cl
