### ISSUE TITLE
error: crate `librocksdb_sys` required to be available in rlib format, but was not found in this form

### ISSUE THREAD

**Issue by brson** [tikv/tikv#5130]
Per @BusyJay:

> I occasionally run into error when make dev:

> > error: crate `librocksdb_sys` required to be available in rlib format, but was not found in this form

> @Brian Anderson  Do you have any ideas?

My first guess is that this is a cargo pipelining bug, as it has only shown up recently and specifically happens with `make` (where pipelining is turned on). Reportedly the problem goes away by running `make` again, which also makes me think its likely a pipelining-related concurrency bug.

cc @nrc 

Similar report https://github.com/rust-lang/cargo/issues/6993, closed as unreproducible.

Our current toolchain is nightly-2019-06-14. Probably worth doing an upgrade just as a stab-in-the-dark.

cc @alexcrichton

**Comment by ehuss** [comment]
> Our current toolchain is nightly-2019-06-14.

Yes, there was a fix (https://github.com/rust-lang/cargo/pull/7008) which landed somewhere around 2019-06-18.

**Comment by brson** [comment]
Thanks for the scoop @ehuss !

**Comment by brson** [comment]
I'm working on a rustup.

**Comment by Roundtree-Larry** [comment]
Any solution please ? I get the same error
