### ISSUE TITLE
How does 5 tikv nodes handle two nodes fault?

### ISSUE THREAD

**Issue by Sraw** [tikv/tikv#5159]
## Question
In [FAQ](https://github.com/tikv/tikv/wiki/TiKV-FAQ#can-raft--multiple-replicas-in-the-tikv-architecture-achieve-absolute-data-security-is-it-necessary-to-apply-the-most-strict-mode-sync-log--true-to-a-standalone-storage), it says that a cluster of 5 tikv nodes can tolerate two nodes fault. I don't fully understand how does it work? I mean as raft requires >50% nodes return ACK, with a replica equals to 3, even two nodes down in 5 nodes cluster may cause some regions that are left only one copy. In this case, how could raft receives >50% ACK?

Or do I misunderstand this FAQ, it actually says 5 nodes with a replica equals to 5?

**Comment by BusyJay** [comment]
Good point! It means to say 5 replicas instead of 5 nodes. Would you like to send a PR to fix that?

**Comment by Sraw** [comment]
I don't find a way to fix in this repository and the wiki also doesn't have `edit` button.

**Comment by siddontang** [comment]
PTAL @dcalvin

**Comment by dcalvin** [comment]
Will update in doc sources. Will fix in Wiki. Currently our FAQ only exists on the Wiki page. But will add one on the Doc site very soon. Thanks. @Sraw

**Comment by dcalvin** [comment]
Updated @Sraw. Please check again.

**Comment by Sraw** [comment]
Well, the page is totally unavailable now. Redirect to the main page and prompt "You do not have permission to update this wiki."

**Comment by dcalvin** [comment]
Sorry, @Sraw  I am not sure what happened. I just re-edited and saved again. Should be fine now. By the way, we are migrating the whole documentation to tikv.org. Stay tuned.

**Comment by Sraw** [comment]
Thanks for your efforts, it now works :)

**Comment by dcalvin** [comment]
You are welcome. Closing this issue now.
