### ISSUE TITLE
Exclude block cache from core dump

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#5161]
Make use of rocksdb's `JemallocNodumpAllocator` feature to exclude block cache from core dump. https://github.com/facebook/rocksdb/blob/v5.18.3/include/rocksdb/memory_allocator.h#L39

We should first expose the API via rust-rocksdb. Example:
https://github.com/pingcap/rust-rocksdb/pull/290

Then add an option to tikv to enable the feature. Example:
https://github.com/tikv/tikv/pull/4563

**Comment by yiwu-arbug** [comment]
cc @wujy-cs

**Comment by wujy-cs** [comment]
Okay I will work on this.
