### ISSUE TITLE
Unstable test: raftstore::test_lease_read::test_read_index_when_transfer_leader_1

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#5163]
raftstore::test_lease_read::test_read_index_when_transfer_leader_1

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7178/nodes/132/steps/1138/log/?start=0

**Comment by breeswish** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/7359/pipeline/134

**Comment by overvenus** [comment]
Another failed case https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/8471/nodes/149/steps/1120/log/?start=0

PTAL @hicqu

**Comment by mahjonp** [comment]
Today occurred 2 times:
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18074/pipeline/171

**Comment by LykxSassinator** [comment]
This case is out-of-date and this issue can be safely closed.
