### ISSUE TITLE
test_node_merge_catch_up_logs_restart failed

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5202]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7375/nodes/116/steps/568/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7374/nodes/116/steps/566/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7372/nodes/116/steps/579/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7369/nodes/116/steps/668/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7368/nodes/116/steps/665/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7363/nodes/116/steps/668/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7361/nodes/116/steps/667/log/?start=0

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7360/nodes/116/steps/667/log/?start=0

**Comment by breeswish** [comment]
@Connor1996 PTAL, thanks!

**Comment by Connor1996** [comment]
working on that
