### ISSUE TITLE
bench raftstore::store::fsm::router::tests::bench_send failed

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#5209]
## Bug Report

**What version of TiKV are you using?**

Commit: 995257ddb1c926cfce638663b66c92809064eedd

**What operating system and CPU are you using?**

MacOSX

**What did you do?**

```
RUST_BACKTRACE=1 cargo bench --no-default-features --features " jemalloc sse failpoints"
```

**What did you expect to see?**

Bench passed

**What did you see instead?**

```
failures:

---- raftstore::store::fsm::router::tests::bench_send stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Full(..)"', src/libcore/result.rs:999:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: core::ops::function::FnOnce::call_once
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: test::run_test
  11: test::run_tests_console
  12: test::test_main
  13: test::test_main_static
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
  17: std::rt::lang_start_internal
  18: main


failures:
    raftstore::store::fsm::router::tests::bench_send
```

**Comment by yiwu-arbug** [comment]
Tested on macos 11.1, clang 12.0.0 with current master 60f3c51fb and the `cargo bench` command succeeded. I added `protobuf-codec`, `test-engines-rocksdb` features due to recent changes. Full command:
```
RUST_BACKTRACE=1 cargo bench --no-default-features --features " jemalloc sse failpoints protobuf-codec test-engines-rocksdb"
```
In particular the `raftstore::store::fsm::router::tests::bench_send` does not exists in current master.

**Comment by yiwu-arbug** [comment]
The `bench_send` bench is under component/batch-system now. I'll try to run it on Mac.

**Comment by yiwu-arbug** [comment]
The `bench_send` bench does build and run on Mac with current master. I'll send a PR to fix the build when building the `batch-system` crate alone.
<img width="715" alt="WeChatWorkScreenshot_5f9b64de-7086-40ba-aec9-58716d6d1d61" src="https://user-images.githubusercontent.com/2606959/103594906-d59c5300-4eae-11eb-8401-cecbd0db9a23.png">
