### ISSUE TITLE
kv prewrite slow on insert with big rowsize

### ISSUE THREAD

**Issue by cfzjywxk** [tikv/tikv#5279]
## Bug Report

**What version of TiKV are you using?**

TiKV 4.0.0-alpha 
Git Commit Hash:   `4f782d4a74487484298c4a8473961bcbfabd9c25`
Git Commit Branch: master
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)

default tikv config parameters without modifying anything, deployed with ansible

**What operating system and CPU are you using?**

linux idc machine with 40core cpu 188GB mem 7TB nvme disk

**What did you do?**

runing tests on "load data statements",  that is inserts with batch size rows per transaction

schema like
```
CREATE TABLE `tin_n_10wb` (
  `pk` int(11) DEFAULT NULL,
  `col1` blob DEFAULT NULL,
  `col2` text DEFAULT NULL,
`col3` varchar(200) DEFAULT NULL,
  ...
 `col95` blob DEFAULT NULL,
 `col96` text DEFAULT NULL,
  ...

column content like
len("G2jOVOMOg3Cnub2jCuXtn0AO1V5hONfLftt0cBHX74itPKMm2uVj1Ax1GfykLLR6PxGclMhPRQxoCe8ZvYI096goa6CsxKHiBvpl7SOp0ax5vl1QNYUZq2x2") = 120
```
inserts with 100k rows, (one row 120 * 100 = 12KB,  batchsize = 5k, one batch = 60MB, batchsize = 1k, batchsize=12MB)

```
MySQL [b100c]> load data local infile '/data1/rwork/10wbigrow.dat' into table b100c;
Query OK, 100000 rows affected (13 min 18.90 sec)
Records: 100000  Deleted: 0  Skipped: 0  Warnings: 0

set tidb_dml_batch_size = 1000;
MySQL [b100c]> load data local infile '/data1/rwork/10wbigrow.dat' into table 1k_2;
Query OK, 100000 rows affected (1 min 1.28 sec)
Records: 100000  Deleted: 0  Skipped: 0  Warnings: 0

```
on tidb statistics, committing one txn on batchsize=5k costs about 40s, committing one txn on batchsize =1k cost about (300-800ms),  the rt on load stmt is quite different

prewrite on batchsize = 5k is quite slow from grafana data(32s), prewrite  on batchsize = 1k,  durations is also not very stable 

tidb  kv request 
![image](https://user-images.githubusercontent.com/3692139/62998640-bb6b6a80-be9e-11e9-8b0f-832cd44f1483.png)

tikv grpc details
![image](https://user-images.githubusercontent.com/3692139/62998760-14d39980-be9f-11e9-9274-47e19bb7e473.png)

**does tikv has some perf problem on this workload(batch insert with many columns and big row size)**

related bench on this tidb pr(https://github.com/pingcap/tidb/pull/11533)

**What did you expect to see?**

**What did you see instead?**

**Comment by zhangjinpeng1987** [comment]
For the TiKV metrics, seems you didn't choose the same time range as TiDB?

**Comment by cfzjywxk** [comment]
kv metric is the latter tests on batch size = 2k, tidb prewrite metric shows 8s and 4s(the latter two blue line after 12:40)

**Comment by cfzjywxk** [comment]
another run on batchsize = 5k
TiDB metric
![image](https://user-images.githubusercontent.com/3692139/63140506-ba5c4980-c014-11e9-868f-bcc5ff22040d.png)

TiKV metric
![image](https://user-images.githubusercontent.com/3692139/63140561-e11a8000-c014-11e9-895b-306dc09dc0e3.png)

**Comment by zhouqiang-cl** [comment]
solved. closed
