### ISSUE TITLE
unknown field `import-dir`, expected `num-threads` or `stream-channel-window` for key `import`

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5286]
## Bug Report
when upgrade 2.14 to master there are errors in tikv's log
**What did you expect to see?**
upgrade success
**What did you see instead?**

**Comment by kennytm** [comment]
On 4.0 all unrecognized settings will cause failure to catch typo. All config not related to TiKV should be removed. In particular, in the `[import]` key **only** the following two keys are acceptable:

```toml
[import]
num-threads = 8
stream-channel-window = 128
```

If there are any other keys (probably due to mixing with TiKV Importer config), please remove them before upgrading.

**Comment by zhangjinpeng1987** [comment]
@kennytm But the error shows stream-channel-window is unknown field, please investigate the root cause.

**Comment by kennytm** [comment]
@zhangjinpeng1987 The title isn't the real error message. Only zhouqiang knows the full error message but he didn't give it to me 😒 

![IMG_2031](https://user-images.githubusercontent.com/103023/63207278-b8b68280-c0f5-11e9-9a75-26da06a6fcdc.JPG)

**Comment by zhouqiang-cl** [comment]
@kennytm well, I did not have the message too,  I will try to reproduce it and then post it here

**Comment by mahjonp** [comment]
The TiKV panic when I tried to reproduce this issue.

```bash
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'invalid auto generated configuration file /data1/jenkins/deploy/data/last_tikv.toml, err unknown field `import-dir`, expected `num-threads` or `st
ream-channel-window` for key `import`', src/config.rs:1462:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: tikv::config::TiKvConfig::from_file::{{closure}}
             at src/config.rs:1462
  10: cmd::server::run_tikv
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libcore/result.rs:818
  11: tikv_server::main
             at cmd/src/bin/tikv-server.rs:143
  12: std::rt::lang_start::{{closure}}
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/rt.rs:64
  13: main
  14: __libc_start_main
  15: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mahjonp** [comment]
I find that check_and_persist_critical_config read last_tikv.toml and the panic may come from here. @kennytm

**Comment by zhouqiang-cl** [comment]
@zhangjinpeng1987 already reproduce. It is beacuse screenshot not full. @cwen , we also need to verify the last_tikv.toml

**Comment by kennytm** [comment]
On TiDB an unknown field will cause *warning* by default, unless a "strict mode" flag is enabled. 

This "strict mode" toggle cannot be implemented in TiKV yet, since `#[serde(deny_unknown_fields)]` is a compile-time attribute which will drop the entire parsed value on error.  We'll see something like serde-rs/serde#1609 to reach parity with TiDB.

**Comment by breeswish** [comment]
@BusyJay @kennytm Do we need to revert commit https://github.com/tikv/tikv/commit/034379605e8805c2ce2016903e21e3bd0521f64e ? We have last_tikv configuration, which definitely may contain deleted fields. This will cause upgrade failure.

**Comment by kennytm** [comment]
(We didn't backport #5190 to 3.0, so we have plenty of time to decide 😉)

**Comment by breeswish** [comment]
@kennytm Yup, that's why I bring the discussion in this issue, instead of in our ONCALL channel :)

**Comment by breeswish** [comment]
@BusyJay @overvenus PTAL

**Comment by overvenus** [comment]
I think the ideal solution should be printing a warning and then continue to deserialize when it meets an unknown field.

**Comment by BusyJay** [comment]
I agree that we should revert it until serde-rs/serde#1609 is fixed.

**Comment by zhouqiang-cl** [comment]
ping  @kennytm
