### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [tikv/tikv#5312]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz) fuzzers (This is generic step not-connected to fuzzit) which I saw you already implemented partially 
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-rust](https://github.com/fuzzitdev/example-rust) and you can see an example of "in the wild" integration [prometheus/prometheus](https://github.com/prometheus/prometheus), [coredns/coredns](https://github.com/coredns/coredns), [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by breeswish** [comment]
Hi, @yevgenypats Thanks for the interest! In our initial version we were indeed used cargo-fuzz. Later, in order to support different fuzzers other than libfuzzer (like hongfuzz and AFL), we implemented our own fuzz infrastructure, which is able to fuzz the same code using different fuzzers. Do you have any suggestions to integrate this kind of infra to your fuzzing platform, so that we can keep both benefits without introducing duplicate code?

**Comment by yevgenypats** [comment]
Hi @breeswish! So I didn't try yet but I think this will be possible. as long as you can build a binary with libFuzzer engine then it will work. I'm not sure how your current infra works? Can I pass flags at build-time to define which fuzzing engine I want?

**Comment by breeswish** [comment]
@yevgenypats Yes! As you can see:

https://github.com/tikv/tikv/tree/master/fuzz#fuzz-specific-target-with-a-fuzzer

Actually we simply pass some flags to `cargo run`: https://github.com/tikv/tikv/blob/master/fuzz/cli.rs#L305 and it can be simply modified to `cargo build` to produce binary only.

**Comment by yevgenypats** [comment]
cool so It looks like it will be relatively easy integration. 

Also, I need to mention that we have a [reward program](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

**Comment by breeswish** [comment]
@yevgenypats Thanks for the link! I think we can do it by our own. In fact currently we have our own platform running fuzz tests but the platform is not specifically designed for this purpose. Fuzzit looks to be pretty awesome so that we don't need to maintain our own.

**Comment by yevgenypats** [comment]
sounds good! feel free to ping me any time if you have questions or need help (we are in beta so documentation is not perfect yet:)), also you can join our slack channel https://slack.fuzzit.dev and dm there.

**Comment by yevgenypats** [comment]
Closing as fuzzit was acquired by GitLab.
