### ISSUE TITLE
Unaudited, old crypto (hash) crates in build graph?

### ISSUE THREAD

**Issue by Hoverbear** [tikv/tikv#5313]
## Bug Report

If you run `cargo tree --insert --package rand:0.3.23` (after installing `cargo-tree`) you will find this:

```bash
hoverbear@Obsidian:~/git/tikv$ cargo tree --invert --package rand:0.3.23
rand v0.3.23
└── rust-crypto v0.2.36
    └── tidb_query v0.0.1 (/home/hoverbear/git/tikv/components/tidb_query)
        ├── test_coprocessor v0.0.1 (/home/hoverbear/git/tikv/components/test_coprocessor)
        │   [dev-dependencies]
        │   └── tikv v4.0.0-alpha (/home/hoverbear/git/tikv)
        │       ├── test_coprocessor v0.0.1 (/home/hoverbear/git/tikv/components/test_coprocessor) (*)
        │       ├── test_raftstore v0.0.1 (/home/hoverbear/git/tikv/components/test_raftstore)
        │       │   └── test_storage v0.0.1 (/home/hoverbear/git/tikv/components/test_storage)
        │       │       └── test_coprocessor v0.0.1 (/home/hoverbear/git/tikv/components/test_coprocessor) (*)
        │       │       [dev-dependencies]
        │       │       └── tikv v4.0.0-alpha (/home/hoverbear/git/tikv) (*)
        │       │   [dev-dependencies]
        │       │   └── tikv v4.0.0-alpha (/home/hoverbear/git/tikv) (*)
        │       └── test_storage v0.0.1 (/home/hoverbear/git/tikv/components/test_storage) (*)
        └── tikv v4.0.0-alpha (/home/hoverbear/git/tikv) (*)
```

You can see that `rust-crypto = "^0.2"` is part of our `tidb_query` crate.

I was curious why this crate, `rust-crypto` uses such an old version of `rand`... We have 5 versions of `rand` in our build graph and this is the oldest:

```
  rand:0.3.23
  rand:0.4.6
  rand:0.5.6
  rand:0.6.5
  rand:0.7.0
```

So I took a look at https://github.com/DaGenix/rust-crypto to see if this crate had an update.

This crate, `rust-crypto` has not been updated in 4 years, and contains code that has not cryptographic code which has been audited formally.

Do we have a policy around which crypto crates we select?

I worry this crate may be vulnerable to timing attacks or other exotic attacks. These attacks could, in theory, impact our users.

We are using the following parts of it:

```bash
use crypto::{
    digest::Digest,
    md5::Md5,
    sha1::Sha1,
    sha2::{Sha224, Sha256, Sha384, Sha512},
};
```

We may get better mileage adopting one or some of these from https://github.com/RustCrypto/hashes. These seem more modern and better maintained. There is also https://github.com/stainless-steel/md5 and https://github.com/mitsuhiko/rust-sha1/ which exist.

### What version of TiKV are you using?

Master

### What operating system and CPU are you using?

Any

### Steps to reproduce

Explore `cargo tree --invert --package rand:0.3.23`

**Comment by Hoverbear** [comment]
@nrc volunteered to ask around if there are any recommendations.

**Comment by iosmanthus** [comment]
As discussed in https://github.com/tikv/tikv/issues/5145, we could introduce an `OpenSSL` compatible library such as `LibreSSL`(supported by `grpc-rs` now), to replace [DaGenix/rust-crypto](https://github.com/DaGenix/rust-crypto). Maybe it will be more secure and reduce the count of dependencies.

**Comment by overvenus** [comment]
LibreSSL has some known issues like #5389 and #5340 .

**Comment by Hoverbear** [comment]
@overvenus Please open a new issue for that because this issue is not regarding SSL. :)

**Comment by brson** [comment]
I believe `rust-crypto` turned into https://github.com/RustCrypto/, so upgrading to those projects is probably an easy step.

Getting off the old rand crates is probably smart too.

Though if we're only using digest functions I think the risk of vulnerabilities is pretty low. I believe those are not the parts of crypto that tend to be susceptible to timing attacks.

**Comment by Hoverbear** [comment]
Closing due to #3886
