### ISSUE TITLE
bench fail with clang 11

### ISSUE THREAD

**Issue by niedhui** [tikv/tikv#5460]
## Bug Report

when I run `cargo bench --package tidb_query`, I got `signal: 11, SIGSEGV: invalid memory reference` on my MBP using clang 11.  and It's ok on another machine running clang 11, so I guess maybe it's related to clang 11.  Xcode 11 (currently GM version) will use clang 11, 

### What version of TiKV are you using?
master branch

### What operating system and CPU are you using?
MacOS 10.15 beta

Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0

### Steps to reproduce

`cargo bench`
or 
`cargo bench --package tidb_query`

### What did you expect?

show me the benchmark result

### What did happen?

```
    Finished release [optimized] target(s) in 1.17s
     Running target/release/deps/cmd-d5ca6d0add5262c3
error: process didn't exit successfully: `/....../tikv-master/target/release/deps/cmd-d5ca6d0add5262c3 --bench` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by niedhui** [comment]
I was trying to configure jemalloc with --enable-debug by enabling  `debug` feature of jemalloc-sys,  the bench just pass 😢 

```
[dependencies.jemalloc-sys]
version = "0.1.8"
optional = true
features = ["stats", "debug"]
```

**Comment by niedhui** [comment]
I found even a simple 'hello world' project cannot be benched with `jemallocator` on my machine, so there's nothing related to TiKV, sorry for bothering.

**Comment by siddontang** [comment]
@niedhui 

have you filed an issue to jemallocator?

**Comment by siddontang** [comment]
or can you use the jemalloc in C directly?

**Comment by niedhui** [comment]
By using jemallocator, it can build, run. But `cargo bench` will fail. 
Since my OS is a beta version,  I'll try to narrow the issue by using other MBP tomorrow.
