### ISSUE TITLE
3.0.1 tikv start failed [region 11899496] 11899499 to_commit 4872027 is out of range [last_index 4872026]"]

### ISSUE THREAD

**Issue by saup007** [tikv/tikv#5508]
### What version of TiKV are you using?
```
../bin/tikv-server --version
TiKV
Release Version:   3.0.1
Git Commit Hash:   4151dc8878985df191b47851d67ca21365396133
Git Commit Branch: HEAD
UTC Build Time:    2019-07-16 01:02:34
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)
```

### What operating system and CPU are you using?
```
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
```

### What did you expect?
```
[tidb@h1351 bin]$  ./tikv-ctl --db /data1/deploy/data/db/ bad-regions
all regions are healthy

[tidb@h1351 bin]$  ./tikv-ctl --db /data1/deploy_20161/data/db bad-regions
all regions are healthy
```

**Comment by saup007** [comment]
tivk log

[tikv.log](https://github.com/tikv/tikv/files/3641408/tikv.log)
[tikv_stderr.log](https://github.com/tikv/tikv/files/3641409/tikv_stderr.log)

**Comment by hicqu** [comment]
Seems you set `sync-log` to `false` in your tikv.toml. Please set it to true to avoid data lose when machine fail. For your case if you want to recover the cluster, please restart your TiKV one by one.
