### ISSUE TITLE
run `cargo test` in master's components/tidb_query failed

### ISSUE THREAD

**Issue by H-ZeX** [tikv/tikv#5509]
### What version of TiKV are you using?

In the master tikv (7cbf045bb6bf7255ddedd44e76beba98efedd2e6), 

### What operating system and CPU are you using?

```
processor	: 39
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping	: 1
microcode	: 0xb00001f
cpu MHz		: 1972.534
cache size	: 25600 KB
physical id	: 1
siblings	: 20
core id		: 12
cpu cores	: 10
apicid		: 57
initial apicid	: 57
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bogomips	: 4399.40
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

### Steps to reproduce

Create a new OS user, so `.cargo` dir under home is empty.
Install a new rust env.
cd `components/tidb_query`
run `cargo test`.
will report link error such as 
```
          /tmp/test_tmp_2/tikv-7cbf045bb6bf7255ddedd44e76beba98efedd2e6/target/debug/deps/libopenssl_sys-40383d0da2264c5e.rlib(asn1_par.o): In function `ASN1_tag2str':
          /tmp/test_tmp_2/tikv-7cbf045bb6bf7255ddedd44e76beba98efedd2e6/target/debug/build/openssl-sys-b00afba846c352da/out/openssl-build/build/src/crypto/asn1/asn1_par.c:369: multiple definition of `ASN1_tag2str'
          /tmp/test_tmp_2/tikv-7cbf045bb6bf7255ddedd44e76beba98efedd2e6/target/debug/deps/libgrpcio_sys-0b6595ea2a7b83cd.rlib(asn1_par.c.o):/home/hzx/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.5.0-alpha.4/grpc/third_party/boringssl/crypto/asn1/asn1_par.c:61: first defined here
 ```

the full log is here https://gist.github.com/H-ZeX/68475699eb0fb5c054c6addb7abd791f

**Comment by Hoverbear** [comment]
Related to https://github.com/tikv/tikv/pull/3886 ?

**Comment by Hoverbear** [comment]
Can you please try doing `cargo test --all` from `tikv/`, and see if that works, then try from `tikv/components/tidb_query` again? I was able to replicate and fix it that way.

**Comment by H-ZeX** [comment]
I run `cargo test --all` from `tikv/` and run `cargo test` in `tikv/components/tidb_query` again. It report same error, too. This tikv https://github.com/tikv/tikv/commit/7cbf045bb6bf7255ddedd44e76beba98efedd2e6

**Comment by H-ZeX** [comment]
I diff two log(one is https://github.com/tikv/tikv/commit/7cbf045bb6bf7255ddedd44e76beba98efedd2e6, 
 another one is this failure's log, their log is same)

**Comment by iosmanthus** [comment]
I encounter the same problem while trying to run `cargo test`, however, I can run `cargo build` successfully.

**Comment by H-ZeX** [comment]
Yes, `cargo clippy` and `cargo check` will success. But `cargo test` will failed. In this dir `components/tidb_quer`.

**Comment by Hoverbear** [comment]
So it looks like there are being multiple copies of openSSL built in. I suspect it's because of our multiple vendored OpenSSL libs?

Could you try #5525?
