### ISSUE TITLE
Rewrite ScannerBuilder and ScannerConfig

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5531]
## Feature Request

Current `ScannerBuilder` and `ScannerConfig` is confusing.

1. It names as a builder but does not fully act as the [builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html). For example, it marks optional configs like `desc` as required.

2. `ScannerConfig::create_cf_cursor` is very easy to cause mistakes. It takes the ownership and clears the key range only for DEFAULT CF, which is not reflected according to its name or signature. We must carefully review the code to ensure the order of calling to avoid key ranges being accidentally taken.

**Comment by leiysky** [comment]
Why would `ScannerBuilder` take bounds for `CF_DEFAULT`?

**Comment by breeswish** [comment]
@leiysky It's an optimization to avoid clone for the last access of the range.

**Comment by leiysky** [comment]
@breeswish Fine.

So what we should fix:

1. Make all the fields of `ScannerConfig` optional(or only `desc`).

2. Find a explicit way to `take` the bounds. Like impl a `create_last_cf_cursor` method which would `take` the bounds.

What do you think of it?
