### ISSUE TITLE
Use async/await and futures 0.3

### ISSUE THREAD

**Issue by nrc** [tikv/tikv#5542]
Async/await is on the path to stable, and is much clearer to read and write than raw futures. Tokio is also working on futures 0.3 native support, so it would be great to use async/await and futures 0.3 in TiKV. We probably want to do this migration in gRPC and Raft before getting started here, otherwise we'll have to mess around with the compatibility layer.

**Comment by Hoverbear** [comment]
This might be a fairly long task but there'd be ample mentorship opportunities and lots of small tasks we could plan out and work on!

**Comment by palash25** [comment]
Hi :wave: I am very new to Rust and I am looking to make my first PR so if this task can be broken into smaller task please ping me I would like to take a crack at one of those :smile:

**Comment by nrc** [comment]
Hi @palash25, although this is going to be fairly easy, I think it will not be easy enough if you are new to Rust (unfortunately the labels aren't fine-grained enough, but there should be something like: easy-ish, no experience with TiKV needed, suitable for an intermediate Rust programmer).

There are probably some tasks in TiKV which are suitable, perhaps https://github.com/tikv/tikv/issues/4923 or https://github.com/tikv/tikv/issues/4508 ?

**Comment by hk1997** [comment]
Hi, I would like to take up this issue. 
@Hoverbear  @nrc Can you help in breaking it up into smaller tasks.

**Comment by nrc** [comment]
Hi @hk1997, a good first task would be to identify everywhere where we use futures. Primarily identify any futures which we define ourselves (I think mostly we use futures from grpc-rs) and then find places where they are used - I think most important (and easy to find) is where we return a future from  a function.

Depending on what you find will influence what we do next. I think we will want to find some boundaries where we convert from 0.1 to 0.3 futures and then change as many uses as we can to async/await.

**Comment by siddontang** [comment]
I think we can start this work now. maybe at first, we must upgrade to the newest toolchain :-)

@nrc  can you open a project and create some tasks, so we can involve the community to do this.

**Comment by jswh** [comment]
I am also interested in this task.Ping me if the project has been started.

**Comment by nrc** [comment]
I think the first task is to port grpc-rs to futures 0.3, unfortunately that is likely to be the hardest part to do too.

I will make some tasks, but it is a bit involved so it might take a while (I feel like it does not need to be rushed because we need grpc-rs done first).

**Comment by govardhangdg** [comment]
Hello! Are there any updates regarding this? I'd like to get involved.
Thanks.

**Comment by nrc** [comment]
No update sorry, still waiting on making changes to grpc-rs which we haven't had time to do :-(

**Comment by hunterlxt** [comment]
Most of this work is finished
