### ISSUE TITLE
if I only want a Tikv instance without pd,what shoud I do?

### ISSUE THREAD

**Issue by mysunnyshine** [tikv/tikv#5561]
## Question

if I only want a Tikv instance without PD, what shoud I do? I am not familiar with Rust, so any example?

**Comment by siddontang** [comment]
Hi @mysunnyshine 

Now TiKV must be worked with PD. why do you want to run one TiKV instance, seems it is meaningless in production. But I guess it may be interested in testing/benchmarking.

**Comment by Hoverbear** [comment]
I think this question is answered so I'm going to close it. :) PLease feel free to re-open this issue if you have further problems.
