### ISSUE TITLE
remove threadpool in tikv_util and use tokio thread pool in all

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#5608]
## Question

Now we have heavily used tokio thread pool, but one place (raftstore worker) still use https://github.com/tikv/tikv/blob/master/components/tikv_util/src/threadpool.rs.

We can easily remove the threadpool, and use tokio thread pool. we can use Lazy future to wrap the task and pass to tokio thread pool.

**Comment by hk1997** [comment]
Hi I'm new to this project and looking to contribute. 
Any guidance on how I can solve this issue

**Comment by BusyJay** [comment]
@hk1997 Thanks! You can just remove the thread pool implement and replace all the usages with future pool in https://github.com/tikv/tikv/tree/master/components/tikv_util/src/future_pool.

**Comment by hk1997** [comment]
@BusyJay  the methods for both threadpool and future_pool are different and I'm not able to find suitable implementations for start, stop and execute methods for threadpool. 
Further, ThreadPoolBuilder is only being used in https://github.com/tikv/tikv/blob/master/src/raftstore/store/worker/region.rs 

While only usage of FuturePoolBuilder is found in https://github.com/tikv/tikv/blob/master/src/storage/txn/sched_pool.rs

I'm not able to find method variants of **start, stop and execute** for threadpool in future_pool.

**Comment by BusyJay** [comment]
The pool is started when it's created. You can use `spawn` to replace `execute`. There is no `stop` method, you can add an implementation to future pool if it's necessary.

/cc @breeswish

**Comment by breeswish** [comment]
@hk1997 Future pool stops automatically when there is no more reference count to it.

**Comment by hk1997** [comment]
I'm very new to rust programming and I'm not able to debug this error. 
I changed line 597 in https://github.com/tikv/tikv/blob/master/src/raftstore/store/worker/region.rs to
where pool is is FuturePool object
![Screenshot from 2019-10-12 22-28-27](https://user-images.githubusercontent.com/24357957/66705058-b9f3dc80-ed3f-11e9-9095-c13242569f4e.png)

Here's the error:
![Screenshot from 2019-10-12 22-28-00](https://user-images.githubusercontent.com/24357957/66705075-e14aa980-ed3f-11e9-968b-6e15e427104c.png)

**Comment by psinghal20** [comment]
@hk1997 The closure is expected to take zero arguments whereas the above example closure takes one argument which it ignores. Just remove the `_` argument from closure.

For more information on closures, take a look at the rust lang book: https://doc.rust-lang.org/book/ch13-01-closures.html

**Comment by govardhangdg** [comment]
Hello! I was wondering if it's okay to take up this issue. There have been no updates for about 4 months now. I'd like to give it a shot. Thanks.

**Comment by BusyJay** [comment]
@hk1997 Are you still working on this?

@govardhangdg let's wait for @hk1997's response for some days.

**Comment by hk1997** [comment]
Hi, sorry I don't think I would be able to work on this one.

**Comment by BusyJay** [comment]
Thanks for the quick reply. @hk1997 

@govardhangdg I think you can start your work now. But you can replace it with yatp instead, which is developed by us and will be the only thread pool in the codebase at some point.

**Comment by govardhangdg** [comment]
Okay, thanks.

**Comment by govardhangdg** [comment]
@BusyJay  I've managed to change the occurrences of tikv_util::ThreadPool to ThreadPool provided by yatp crate. The only place I was able to find the use of  tikv_util::ThreadPool was in https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/worker/region.rs. The new code did pass both the tests that were present in the same file. I can create a pull request. Although I do have doubts regarding certain things. 

1. I've chosen to use futures instead of callbacks in the yatp::task. I'd like to know if it's okay.
2. I'm not really sure what has to be provided as the name parameter for the Builder(from yatp). Previously `thd_name!("snap-generator")` was passed to the ThreadPoolBuilder, for a similar purpose.
3. I had to use the `Extra` from yatp in order to satisfy the `WithExtra` trait when spawning a new task. But I am not sure of the right way to create a new `Extra` struct that is right in this case.

Thanks.

**Comment by BusyJay** [comment]
> ...chosen to use futures instead of callbacks in the yatp::task...

It's OK.

> ..what has to be provided as the name parameter for the Builder(from yatp)...

Just `thd_name!("snap-generator")` is enough.

> ...the right way to create a new Extra struct...

Use `single_level` in this case.

**Comment by govardhangdg** [comment]
@BusyJay Thanks. I have created a pull request.
