### ISSUE TITLE
test_raftstore::cluster::Cluster<T>::try_merge panicked at 'called `Result::unwrap()` on an `Err` value: Timeout("request timeout for 3s")'

### ISSUE THREAD

**Issue by H-ZeX** [tikv/tikv#5614]
## Bug Report

[The log is here](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/9894/nodes/96/steps/705/log/?start=0)
[The test is here](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9894/pipeline/)

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
