### ISSUE TITLE
'test_backup::test_backup_and_import' panicked at 'message: "stale command"', components/backup/tests/integrations/test_backup.rs:100:9

### ISSUE THREAD

**Issue by H-ZeX** [tikv/tikv#5630]
## Bug Report

[The test is here](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9970/pipeline)

**Comment by overvenus** [comment]
Dup #5601 and will be fixed by #5635 .
