### ISSUE TITLE
unstable test: raftstore::test_prevote::test_prevote_reboot_majority_followers

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#5642]
raftstore::test_prevote::test_prevote_reboot_majority_followers

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/10107/pipeline

**Comment by zhouqiang-cl** [comment]
the same as https://github.com/tikv/tikv/issues/5615

**Comment by LykxSassinator** [comment]
Given that the current Long Term Support (LTS) versions have resolved this issue, it is now considered outdated and can be safely closed.
