### ISSUE TITLE
Enable tikv to perf itself

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5666]
### Is your feature request related to a problem? Please describe:
In the old days. we need a `perf record` to perf tikv's userstack profile. Can we
try to enable perf tikv it self and can query to get the profiles such as query `debug/profiling?seconds=10`

**Comment by zhouqiang-cl** [comment]
we already need to modify tidb-ansible to install perf

**Comment by zhouqiang-cl** [comment]
There is already have an perf tool in tikv https://github.com/gperftools/gperftools
but it use tcmalloc. we can do just bring gperftools and let malloc still use jemalloc

**Comment by siddontang** [comment]
I check the gperftools and find that supporting the CPU profiler is not too hard, we can even abstract to an independent crate to do this.

**Comment by YangKeao** [comment]
#5686 is the very first step of this issue. It links gperftools and unwind. And it dynamically linked libstdc++ (as required by gperftools). 

Next step I will make profiling feature as the default choice and add relative http interface to status server.

**Comment by breeswish** [comment]
Duplicates to #5124
