### ISSUE TITLE
Can we have client for tikv

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5699]
### Is your feature request related to a problem? Please describe:
Some times we want to have a client like `mysql` or `redis-cli`, which can put/get value from tikv direct

### Describe the feature you'd like:
just like `redis-cli` or `mysql`

**Comment by siddontang** [comment]
seem we can do some in `tikv-ctl` already and you can improve it continuously.

**Comment by Hoverbear** [comment]
We have https://github.com/tikv/client-rust

There was some work here on making a CLI client https://github.com/Hoverbear/client-rust/tree/cli-client by @sciamp-dev
