### ISSUE TITLE
UCP: Extract tidb_query into different workspaces

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5706]
## Description

tidb_query consists of:

1. Data structure implementations
2. Volcano model UDF (depend on 1)
3. Volcano model executors (depend on 1, 2, 3)
4. Vectorized UDF (depend on 1)
5. Vectorized Aggregation functions (depend on 1, 4)
6. Vectorized executors (depend on 1, 4, 5).

We can extract each of it into a different workspace, to reduce benchmark and compile time.

## Score 

* 605

## Mentor(s)

* @andylokandy 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

**Comment by TennyZhuang** [comment]
This PR means that PCP task can be unrelated with performance?

or the definition of performance in PCP including the efficiency of developer(

**Comment by breeswish** [comment]
@TennyZhuang Only easy task can be unrelated to performance

**Comment by SSebo** [comment]
progress update: already read tikv-source-code-reading blog 14 15 16, right now reading the tidb_query source code

**Comment by SSebo** [comment]
@breeswish mentor, is there any relation between `Data structure implementations` in description and tidb_query_datatype in source code ?

**Comment by breeswish** [comment]
@SSebo `tidb_query_datatype` is a WIP place to put these data structures. You may want to put these data structure implementations in there.

**Comment by SSebo** [comment]
progress update: still working on it

**Comment by ziyi-yan** [comment]
Hi, @andylokandy @breeswish! I just picked up the challenge and read through three coprocessor-related blogposts from PingCAP. I will get more familiar with the code tomorrow, but I think we need a clearer goal.
The description says "extract each of it into a different workspace". Does that mean "into different crates"? If that's the case, how many and what crates should we end up with? Should we end up with 6 different crates like the description listed?

**Comment by SSebo** [comment]
I currently split `tidb_query` to `tidb_query_scalar` and `tidb_query_vector`. But there are so much compile errors to be fixed.

**Comment by breeswish** [comment]
My suggestion is to extract according to the PR description, otherwise you are very likely to meet cycle dependencies.

1. Data structure implementations
2. Volcano model UDF (depend on 1)
3. Volcano model executors (depend on 1, 2, 3)
4. Vectorized UDF (depend on 1)
5. Vectorized Aggregation functions (depend on 1, 4)
6. Vectorized executors (depend on 1, 4, 5).

**Comment by SSebo** [comment]
😢

**Comment by ziyi-yan** [comment]
Hi, @breeswish!

After skimming through current `tidb_query` crate, I have done some categorization based on the top-level directories under `components/tidb_query/src`:

1. Data structure implementations
   - expr
   - expr_util
   - codec
2. Volcano model UDF (depend on 1)
   - _NO IDEA_
3. Volcano model executors (depend on 1, 2, 3)
   - executor
4. Vectorized UDF (depend on 1)
   - rpn_expr
5. Vectorized Aggregation functions (depend on 1, 4)
   - aggr_fn
6. Vectorized executors (depend on 1, 4, 5).
   - batch

And `storage` module and some other code (`tidb_query/src/*.rs`) will be left at `tidb_query` crate.
I’m sorry I have no idea about the second part. Should we extract it from any modules?

Looking forward to your reply. And if it’s on the right direction, I will submit a draft PR later.

Thanks.

**Comment by ziyi-yan** [comment]
Hi, @andylokandy! Any comments or suggestions on my plan above? Thanks!

**Comment by SSebo** [comment]
@ziyi-yan

- You are on the right track.
-  `expr` in your first `Data structure implementations` should be the `Volcano model UDF (depend on 1`.
- Because of the tidb_query splited into 6 crates, the test cases will be messed up. `cfg(test)` wil not propagate to leaf crate.
- `tidb_query_codegen` use `crate::tidb_query` to find some types not longer works, you should change them to the new crate.

BTW, I already worked  on this issue for several weeks, and pushed a PR. This issue is not easy as it looks like when you want to make the tests pass.

**Comment by ziyi-yan** [comment]
Thanks for your reply! @SSebo 
I still have some questions about `expr` module. It's actually depended by all other modules under `tidb_query/src`, but mostly just `use crate::expr::EvalContext;`. Maybe we should put this part of code in part 1 and leave other volcano-model-related code into part 2.

**Comment by SSebo** [comment]
Yes, I put `use crate::expr::EvalContext` into `tidb_query_datatypes`

**Comment by breeswish** [comment]
Resovled by https://github.com/tikv/tikv/pull/7084
