### ISSUE TITLE
Batch Resolve Coprocessor Locks

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5707]
## Description

Currently Coprocessor returns error immediately as soon as it meets a lock during scanning. When there are multiple locks in the scanning range this may result in high latency due to resolving locks one by one and there are RTTs for each resolve operation. This task is to allow Coprocessor returning multiple locks all at once when possible so that multiple locks can be resolved. Thus performance can be improved when there are heavy conflicts. Notice that you need to modify both TiKV and TiDB code in order to make them cooperate together.

## Difficulty

- Medium

## Score

- 2100

## Mentor(s)

- @loong
- @busyjay
- @breeswish

## Recommended Skills

- Rust and Go language
- TiKV transaction model

**Comment by breeswish** [comment]
See https://github.com/tikv/tikv/issues/5215

**Comment by Fullstop000** [comment]
It seems that TiDB `ResolveLocks` has supported resolving multiple locks at once but not in a concurrent style. Do we need to improve it?

**Comment by breeswish** [comment]
Since UCP is ended, this issue is closed now. See https://github.com/tikv/tikv/issues/5215 for further updates.
