### ISSUE TITLE
PCP-15: Improve LIKE() performance

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5709]
## Description

In TiKV, LIKE() is implemented the same way as other UDF functions, which is, a LIKE() implementation for Scalar arguments, and an automatically generated wrapper around it for Vector arguments. However, it is not efficient since some pre-calculations can be done beforehand when LIKE() is applied over vector arguments (but constant pattern string). Additionally, TiKV’s LIKE() implementation does not resist some common glob attacks, like some patterns described by https://research.swtch.com/glob .

The task is to implement LIKE() efficiently that will not suffer from complicated patterns and can utilize the feature that the pattern may be a constant. Hint: a possible solution can be compiling the pattern into an regular expression and reuse it when pattern is a constant.

## Difficulty

- Medium

## Score

- 1500

## Mentor(s)

- @breeswish
- @lonng

## Recommended Skills

- Algorithm
- Rust language

**Comment by liufuyang** [comment]
Having interest in this as well, is it this function we are aiming to improve?
https://github.com/tikv/tikv/blob/master/components/tidb_query/src/expr_util/like.rs#L44

**Comment by breeswish** [comment]
@liufuyang Yes. Note that this function implementation is now shared in both vec and non-vec. However the optimization can be only applied to vec.
