### ISSUE TITLE
PCP-19: Improve IN() performance

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5713]
## Description

The implementation of IN() function in TiKV is not efficient. It compares the first argument (let's call it src) with the rest (let's call it matches) one by one. When matches are constants, we can build a hash set for once and use this hash set for all src.

Notice that matches may be a mixture of constants and non-constants. We can build the hash set for constants and if there are remaining non-constant matches we can then compare one by one.

For string kind parameters, a trie tree may be preferred over the hash set.

## Difficulty

- Medium

## Score

- 2100

## Mentor(s)

- @breeswish
- @lonng

## Recommended Skills

- Algorithm

**Comment by liufuyang** [comment]
This sounds like an interesting task. However where can I find this IN function? :)

**Comment by breeswish** [comment]
Yes! @liufuyang

**Comment by breeswish** [comment]
Adjusted from 1500 to 2100 since this task requires to correctly implement Hash for existing types.
