### ISSUE TITLE
UCP: Add Tracing to Coprocessor

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5714]
## Description

It is usually difficult to know which part costs a lot of time for a single Coprocessor request. Although TiKV provides per-executor time statistics (called `ExecSummary`) for TiDB's `EXPLAIN ANALYZE` requests, it is still too rough. For example, we cannot know how long it spends in the MVCC layer itself, or the RocksDB itself. Further more, since TiDB aggregates all requests' ExecSummary together to display a single `EXPLAIN ANALYZE` result, users are not able to know per-request statistics.

This task is to implement tracing at the lowest possible performance cost. It should be able to record how long each key step takes, since the request is received. This will be very helpful to trace performance spikes and performance issues for minor requests. Only requests that enables tracing should be traced. When tracing is not enabled there should be no performance impact.

Goals:

- Discover or design & implement a general tracing library / layer (in tikv's `components` directory):
  - Nearly zero-cost (i.e. performance impact for TPC-H < 1%) when tracing is **not** dynamically enabled (you may consider using generics to minimize the runtime cost)
  - Low-cost when tracing is enabled (i.e. performance impact for TPC-H < 5%).
  - Compatible with OpenTracing
  - Can be easily used to trace across thread boundaries without too many modification

- Add tracing to Coprocessor EndPoint (`coprocessor/`) and Coprocessor Executors (`components/tidb_query`).
  - The effort to add tracing should be small, so that we can easily apply this mechanism to the rest of the TiKV.
  - Tracing context should be able to be passed into thread pools.

You don't need to pass tracing context to lower levels like MVCC in this task. There could be future tasks (if time permits) for it.

## Score

- 6351

The score can be adjusted to higher if the actual amount of work is notably more than we expected.

## Mentor(s)

- @andylokandy 
- @sticnarf 
- @breeswish 

## Recommended Skills

- Professional Rust programming
- System programming
- OpenTracing

**Comment by Hoverbear** [comment]
How can we know if requests enable tracing?

**Comment by breeswish** [comment]
@Hoverbear There isn't one for now -- The protocol needs to be modified and TiDB needs to pass the tracing status down to TiKV.

**Comment by Hoverbear** [comment]
Do you have a suggestion for how it should work?

**Comment by breeswish** [comment]
@Hoverbear Modifying the kvproto / tipb to include a field indicating whether or not tracing is enabled should be enough
