### ISSUE TITLE
Copr SIG: Implement more UDF

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5727]
## Feature Request

Currently there are a lot of implemented UDF in TiKV Coprocessor. However they do not have vectorized implementation and their push down is not enabled in TiDB due to lack of testing.

You can:
- Choose an UDF implementation which do not have vectorized implementation, migrate it for the vectorized framework.
- Choose an UDF vectorized implementation, add integration tests for it and enable the push down in TiKV.
- Implement a new UDF in TiKV. The implementation must have both vectorized version and non-vectorized version. Basic unit tests are required.

This task can be claimed by multiple contributors.

**Comment by hawkingrei** [comment]
I will enable the push down of JSONLength.let me try it.

**Comment by breeswish** [comment]
Close in favor of https://github.com/tikv/tikv/issues/5751
