### ISSUE TITLE
PCP-32: Improve performance of Chunk Encoder

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5729]
## Description

TiDB and TiKV talk using Chunk encoding now. For data scanned directly from KV store, TiKV parses them to `Datum` first, then encode the Datum into Chunk format. We can directly transform Datum bytes to Chunk bytes though, without the need to build the `Datum` structure. This saves from memory copy and is more efficient.

Goals:

- Implement efficient codec for transforming row datum into Chunk format.

## Difficulty

- Medium

## Score

- 2100

## Mentor(s)

- @breeswish
- @lonng
- @wshwsh12 

## Recommended Skills

- Rust programming
- Go programming

**Comment by ichn-hu** [comment]
Can I try this issue in my spare time?

**Comment by Renkai** [comment]
I will do this

**Comment by breeswish** [comment]
@Renkai Thanks for the interest! I can change this issue to a PCP issue. Do you need a PCP issue for it so that you can also get reward points?

**Comment by Renkai** [comment]
@breeswish Thanks for you response! It would be better to change to a PCP issue after I finish the current one.[dogge]

**Comment by Renkai** [comment]
In progress
