### ISSUE TITLE
PCP-21: Titan GC doesn’t affect online write

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#5739]
## Description

Currently [Titan](https://github.com/pingcap/titan) GC will write memtable, this may affect online write. How to reduce or eliminate this impact? 

## Difficulty

- Hard

## Score

- 27000

## Mentor(s)

- @yiwu-arbug, @Connor1996 

## Recommended Skills

- Algorithm

**Comment by tabokie** [comment]
I will work on this during the weekend. /cc @yiwu-arbug @Connor1996

**Comment by you06** [comment]
@tabokie you may sign up the PCP first

https://github.com/tidb-perf-challenge/pcp/issues/new?assignees=&labels=&template=performance-challenge-program.md&title=PCP%2FSign+Up

**Comment by tabokie** [comment]
> @tabokie you may sign up the PCP first
> 
> https://github.com/tidb-perf-challenge/pcp/issues/new?assignees=&labels=&template=performance-challenge-program.md&title=PCP%2FSign+Up

@you06 done.
