### ISSUE TITLE
Implement zstd dictionary compression in Titan

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#5743]
## Description

Implement zstd dictionary compression in [Titan](https://github.com/pingcap/titan)

The task consist of the following steps:

- [x] Update blob file format to accommodate zstd dictionary: https://github.com/pingcap/titan/issues/108
- [x] Build blob file using zstd dictionary compression https://github.com/pingcap/titan/issues/118
- [x] Read blob from file with dictionary compression https://github.com/tikv/titan/pull/192
- [ ] Expose dictionary compression option to tikv https://github.com/tikv/tikv/pull/15979
- [ ] Benchmark performance: read/write performance, compression rate

You can take https://github.com/facebook/rocksdb/pull/4952 as reference, and utilities already implemented in rocksdb can all be used in Titan.

## Difficulty

- Hard

## Score

- 3000

## Mentor(s)

- @yiwu-arbug @Connor1996 

## Recommended Skills

- Algorithm

**Comment by foeb** [comment]
Hi! I'd like to work on this.

**Comment by foeb** [comment]
I'm backing out of this story since I don't have enough time. Thanks again, @yiwu-arbug!

**Comment by yiwu-arbug** [comment]
now part of #8635
