### ISSUE TITLE
PCP-20: Reduce latch wait duration

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#5746]
## Description

In storage model, before a key write to engine, latch must be held first, currently we use a fixed array to simulate hash table, but when there are many keys concurrently, fake conflicts will increase latch wait duration. Verify case: Sysbench 128 threads batch(batch = 100) insert, from the metric we can see there is no latch wait duration. 

## Difficulty

- Medium

## Score

- 1500

## Mentor(s)

- @zhangjinpeng1987

## Recommended Skills

- Algorithm

**Comment by hhwyt** [comment]
I would like to try this. Can you give me some hint on how to construct the verify case? @breeswish @zhangjinpeng1987

**Comment by siddontang** [comment]
maybe we can use multi fixed arrays, e.g, 16 arrays with 1m slots, for a key, first, we use hash(key) mod 16 to locate the array, and then use hash(key) mod  1m.

**Comment by zhangjinpeng1987** [comment]
@hhwyt  Verify case: Sysbench 128 threads batch(batch = 100) insert, from the metric we can see there is no latch wait duration.

**Comment by zhangjinpeng1987** [comment]
@hhwyt By the way, you must finish some easy tasks before start medium or hard tasks.

**Comment by hhwyt** [comment]
> maybe we can use multi fixed arrays, e.g, 16 arrays with 1m slots, for a key, first, we use hash(key) mod 16 to locate the array, and then use hash(key) mod 1m.

I get it. We only need to make the probability small enough in theory. I think 16*1m slots maybe a little many, maybe we can refer to the [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem), roughly estimate how many slots are needed to get a suitable probability of collision.

**Comment by hhwyt** [comment]
> @hhwyt By the way, you must finish some easy tasks to achieve 600 score before start medium or hard tasks. Please pick some easy tasks from https://github.com/tikv/tikv/projects/20

Roger that. I will first familiarize myself with TiKV by trying to solve other easy problems. Thanks for suggestions!

**Comment by hhwyt** [comment]
Anyone can freely take over this issue :)

**Comment by zhangjinpeng1987** [comment]
> > maybe we can use multi fixed arrays, e.g, 16 arrays with 1m slots, for a key, first, we use hash(key) mod 16 to locate the array, and then use hash(key) mod 1m.
> 
> I get it. We only need to make the probability small enough in theory. I think 16*1m slots maybe a little many, maybe we can refer to the [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem), roughly estimate how many slots are needed to get a suitable probability of collision.

I think to calculate the probability of collision you can refer to the bloomfilter.

**Comment by innerr** [comment]
Is someone working on this now? if there is no one I would like to do that

**Comment by zhangjinpeng1987** [comment]
https://github.com/tikv/tikv/pull/6094 has fixed this issue, so close it.
