### ISSUE TITLE
Async apply may cause state machine inconsistent?

### ISSUE THREAD

**Issue by ckanner** [tikv/tikv#5766]
## Async write
Tikv use raft to ensure state machine consistent in ervery node. We can only async apply the write to the state machine in every node and return the result to client when the Raft log is majority committed.

## Background
There are three nodes(A, B, C). A client requests to node-A. The raft log has been majority appended to their raft logs, then node(A, B, C) begin to async apply the write to the state machine.

Once node-A has been apply the write to the state machine successfully, node-A will return the result to the client, regardless of whether node(B, C) applied successfully.

In some scenarios, machine B's disk is full, so node-B can not apply the write to the state machine successfully. And the state machine between A and B are inconsistent.

## Question
Is there any solution in tikv in the above scenarios?

**Comment by gengliqi** [comment]
If node-B's disk is full, tikv on node-B will panic. You can just move the data to a new high-capacity disk and restart tikv. The correctness is still guaranteed by raft. Raft algorithm cannot guarantee all node's state machine is same every moment. It just guarantees that a log is not changed after being committed. It's state machine's duty to apply these committed log in sequence. In other words, if some bad things happens(e.g. disk full, outage) before applying all committed log, state machine will apply these committed log after recovery. So the consistency is still guaranteed.
