### ISSUE TITLE
Linearizability question

### ISSUE THREAD

**Issue by GrapeBaBa** [tikv/tikv#5796]
## Question

Suppose two transactions T1(R:X,W:Y) AND T2(R:Y,W:Z), T1 get a begin ts 10 and commit ts 15; T2 get a begin ts 16. Can it happen if T2 read Y before T1 lock Y? It may cause T2 get a older version Y.

**Comment by MyonKeminta** [comment]
It's not possible as long as the timestamp oracle can promise it gives strictly increasing timestamps. A transaction always acquire the commit_ts after successfully writing all locks, so when T1 starts getting the commit_ts, it must have already written all locks it needs. Meanwhile, T2 will do the read operation only when it successfully gets its start_ts 16, which is absolutely allocated later than T1's commit_ts 15. So the time order of these events must be as this:

T1 write lock on Y < T1 start getting commit_ts < oracle allocates 15 < oracle allocates 16 < T1 finish getting start_ts < T1 reads Y

As a result, when T2 reads Y, Y must not be in the state before T1's lock is written.

**Comment by GrapeBaBa** [comment]
Thanks, I saw it.
