### ISSUE TITLE
Cannot remove down tikv node

### ISSUE THREAD

**Issue by yester354** [tikv/tikv#5797]
## Question

one of my tikv node down because of data corruption，i need remove it， i had execute store delete comand two days ago
，but its region count almost keep the same ，i cannot remove the abnormal node，how can i do it

**Comment by nolouch** [comment]
@yester354  This is most likely due to an unhealthy store state, such as has a lot of regions that are not elected leader.

**Comment by Connor1996** [comment]
This is caused by no leader region, see #5852

**Comment by Connor1996** [comment]
After using `tikv-ctl tombstone` to remove the stale peer, the no leader region can do election normally.
