### ISSUE TITLE
Split may leave stale region info

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#5852]
Consider a region A with three peers. Then region A adds a new learner peer and splits a new region B. So the state of region A  and region B would be:

-  region A [peer1, peer2, peer3, peer4(learner, uninitialized)]
-  region B [peer5, peer6, peer7, peer8(learner, uninitialized)]

peer8 applies snapshot before peer4:

- region A [peer1, peer2, peer3, peer4(learner, uninitialized)]
- region B [peer5, peer6, peer7, peer8(learner)]

Then region B promotes and then removes the peer8:

- region A [peer1, peer2, peer3, peer4(learner, uninitialized)]
- region B [peer5, peer6, peer7]

Now, peer4 may apply a snapshot but not promoted to be a voter

- region A [peer1, peer2, peer3, peer4(learner)]
- region B [peer5, peer6, peer7]

then peer4 catch up the log and performs the split process, that is to say, peer4 splits the peer8 of region B again:

- region A [peer1, peer2, peer3, peer4(learner)]
- region B [peer5, peer6, peer7] peer8(learner)

Note that: peer8 is created again with learner state, but it is not in the peer list of peer5, peer6, and peer7. Due to peer8 is learner, it will never send request vote to other peers, so other peers of region B will never know the existence of peer8.

Further, peer8's info is left on that store forever, and it can't be deleted automatically even if region B is merged. This may cause other regions with overlapped range can not add their peer successfully to that store (namely down peer), due to TiKV will reject to create a peer which is overlapped with existence peer on itself.

**Comment by Connor1996** [comment]
To solve this issue, we should check the region whether is already tombstone before performing splitting. 
Also, after discussion with @BusyJay, we'd better handle merge case when validating peer from PD https://github.com/tikv/tikv/blob/master/src/raftstore/store/worker/pd.rs#L651, so the peer can be removed itself automatically. /cc @gengliqi

**Comment by MimeLyc** [comment]
REFRESH
