### ISSUE TITLE
Lots of regions cause high raftstore cpu usage 

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#5854]
### What version of TiKV are you using?
v3.0.4
### Steps to reproduce
In user cases. There are 200,000,000 regions.  The raftstore cpu will increase to more then 200%

### What did you expect?
TiKV use less CPU

**Comment by siddontang** [comment]
have you enabled "hiberante region"?

**Comment by zhouqiang-cl** [comment]
No. Did not enable it. Need some test

**Comment by nolouch** [comment]
@zhouqiang-cl  200,000,000 regions ... are you sure?
cc @BusyJay

**Comment by BusyJay** [comment]
Enabling hibernate regions should solve your problem.

**Comment by siddontang** [comment]
please enable hibernate region and check the CPU again @zhouqiang-cl
