### ISSUE TITLE
Replica read may cause tikv panic

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#5875]
## Bug Report
A newly created peer has empty region info until it applies snapshot. If a read request is sent to it, it will cause panic at https://github.com/tikv/tikv/blob/master/src/raftstore/store/fsm/peer.rs#L2425.

Replica read should skip these peers because it will take a long time to catch up with the leader.

**Comment by 5kbpers** [comment]
Good catch, I will investigate it.

**Comment by 5kbpers** [comment]
Could you give me a more concrete detail? Like the backtrace.

**Comment by 5kbpers** [comment]
Have investigated this issue, the panic would happen during the time between the store creates a `PeerFsm` and the peer handles `ExecResult::ChangePeer`.
This case should be covered by our long-running test, I will address that after fixing this bug.
