### ISSUE TITLE
copr: the `left_shift` result inconsistent with TiDB

### ISSUE THREAD

**Issue by lonng** [tikv/tikv#5905]
## Bug Report

See: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/187/pipeline

### What version of TiKV are you using?

See CI log.

**Comment by lonng** [comment]
@gauss1314 Please take a look.

**Comment by gauss1314** [comment]
Hi, 

> **NoPushDown Output**: 
field1	field2	field3	field4	field5
**PushDownWithoutVec Output**: 
field1	field2	field3	field4	field5
0	NULL	NULL	0	1
**PushDownWithVec Output**: 
field1	field2	field3	field4	field5
0	NULL	NULL	0	1

It seems that both vectorized and non-vectorized `left_shift` result are inconsistent with TiDB.

So I try to solve this problem by:
1. Check `NoPushDown` method source code (I have no idea about `NoPushDown` ).
2. Check the `checked_shl` method how it behavior when it in corner case like `NULL` in rust.

**Comment by lonng** [comment]
Seems the tikv implementation is incorrect. from TiDB:
```go
func (b *builtinLeftShiftSig) evalInt(row chunk.Row) (int64, bool, error) {
	arg0, isNull, err := b.args[0].EvalInt(b.ctx, row)
	if isNull || err != nil {
		return 0, isNull, err
	}
	arg1, isNull, err := b.args[1].EvalInt(b.ctx, row)
	if isNull || err != nil {
		return 0, isNull, err
	}
	return int64(uint64(arg0) << uint64(arg1)), false, nil
}
```
