### ISSUE TITLE
PCP: Filter SST based on MVCC properties

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#6065]
## Description

This task aims to implement an iterator that can filter SSTs based on [RocksDB table properties](https://github.com/tikv/rocksdb/blob/c06b54d0c6fb8c46ee98744544b003ff4f87c269/include/rocksdb/table_properties.h#L67-L73). 
For now, TiKV encodes its own properties into every SST files, e.g.,

https://github.com/tikv/tikv/blob/c301438a4025acf0d62487cf520badf87635140d/src/raftstore/coprocessor/properties.rs#L45-L53

After the task, we expect to see an iterator that can skip SST file whose `max_ts` is less than a given ts.

## Difficulty

- Easy

## Score

- 50

## Mentor(s)

- @Connor1996 

## Recommended Skills

- Algorithm

**Comment by yiwu-arbug** [comment]
Discussed with @Connor1996 offline and this task is doable by having a custom "bloom filter". 

@overvenus just curious what's the use case for this?

**Comment by siddontang** [comment]
PTAL @overvenus

**Comment by yiwu-arbug** [comment]
Seems rocksdb already have the options and it was added by cockroachdb guys 2 years ago: https://github.com/facebook/rocksdb/commit/7891af8b53be9a1a2181b46767561fad8e862a2e cc @overvenus @Connor1996

**Comment by Connor1996** [comment]
@yiwu-arbug great! seems it's exactly what we want.

**Comment by Connor1996** [comment]
Due to facebook/rocksdb@7891af8, and rust-rocksdb already has related binding. So we can simply realize it by setting a read option with a table filter to the iterator.

``` rust
struct MaxTsFilter { max_ts: u64}
impl TableFilter for MaxTsFilter {
     fn table_filter(&self, props: &TableProperties) -> bool {
        // get mvcc property
        // get max_ts in mvcc property
        max_ts <= self.max_ts;
     }
}

let opts = ReadOptions::new();
opts.set_table_filter(table_filter);
let iter = db.iter(opts);
```

**Comment by overvenus** [comment]
RocksDB has already implemented the feature, this issue is no longer hard, but rather easy, I will adjust difficulty and score.
