### ISSUE TITLE
failpoints::cases::test_replica_read::test_read_after_cleanup_range_for_snap panicked at 'called `Result::unwrap()` on an `Err` value: Timeout'

### ISSUE THREAD

**Issue by H-ZeX** [tikv/tikv#6083]
## Bug Report

The test: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/13221/pipeline/196

In order to avoid the link is expired, the log is in the file
[log.txt](https://github.com/tikv/tikv/files/3899849/log.txt)

**Comment by mahjonp** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/17909/pipeline/114
