### ISSUE TITLE
tikv-ctl unsafe recover can lead to inconsistent replica list

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#6107]
Suppose region 1 has three replicas A, B and C, and A is leader. A adds a new replica D and then both A and D are corrupted, and B has applied the conf change while D has not. Using tikv-ctl will remove both A and D from B's local peer list and just remove A from C's. After B and C are started, C will apply the conf change add D to its list. So B's peer list becomes (B, C), and C's list is (B, C, D).

To get a consistent list, we need to skip mutating the list after an unsafe recovery. A simple way is maintain a tombstone store list on every node. When applying conf change, ignore the targets that locate on the store. Note that conf version should still be increased to reach the correct version.

/cc @disksing @hicqu

**Comment by hicqu** [comment]
Stores could be only `tombstone` for some special regions, but still useful for other regions.
So, there are 2 question:
1. The list is for all regions, or for some special regions?
2. When will the list be clear?

**Comment by BusyJay** [comment]
Another way is to scan all the logs and mutate the id to a special value, which we should treat as no-op. It requires to update region peer list and logs atomically.

**Comment by disksing** [comment]
any update?

**Comment by BusyJay** [comment]
It's still under discussion.

I think the safest way for the problem is generating a snapshot from a node that has applied most up to date data, and restoring it on all other remaining node.

This approach is generic and work on many situation.

**Comment by NingLin-P** [comment]
I have an idea for this problem: for each peer removed by tikv-ctl append one `RemovePeer` raft log on every peer of the region because every peer has these logs so they must commit and send to the apply worker. Also tikv-ctl remove peer from store's local peer list as before, and because there is at most one unapplied `confchange`, so at most one `RemovePeer` logs appended by tikv-ctl will success, others will result in a `remove missing peer` error log, for the epoch of these `RemovePeer` logs we can simply set to the same `epoch { ver: exist_ver, conf_ver: exist_confver + 1 }`.

**Comment by BusyJay** [comment]
> because every peer has these logs so they must commit and send to the apply worker

So you mean propose a conf change after restarting all the remaining nodes?

>  because there is at most one unapplied confchange

No, it's only guaranteed that at most one uncommitted conf change.

**Comment by NingLin-P** [comment]
> So you mean propose a conf change after restarting all the remaining nodes
No, just append log (write to rocksdb) without propose when tikv-ctl remove peer.
 
> No, it's only guaranteed that at most one uncommitted conf change.
I think the guaranteed is most one unapplied conf change.

**Comment by BusyJay** [comment]
> No, just append log (write to rocksdb) without propose when the nodes are down.

How to guarantee safety? raft-rs can't distinguish difference of logs when they have the same term and index. So it's possible appending a log in followers can break consistency.

> I think the guaranteed is most one unapplied conf change.

For example, if an isolated follower recover, it can receive multiple committed conf changes from leader and crash before applying.

**Comment by BusyJay** [comment]
I have a new idea. Instead of mutating the state manually, we rely on the log replication to handle changes correctly.

Let's introduce a FORCE_LEADER state. If a peer enters a `FORCE_LEADER` state, it will become leader immediately without counting majority votes. And all its logs will also be committed without replicating to majority. A node in `FORCE_LEADER` state will only accept new conf change proposals and `EXIT_FORCE_LEADER` proposal. After exiting `FORCE_LEADER`, it will need a new election to become leader again.

Because all fixing commands are proposed as logs, so all previous working logs will still being applied correctly. Fixing commands will also be replicated to other nodes and executing in the same order, so consistency is guaranteed in the end.

`FORCE_LEADER` state can be implemented as custom quorum function so that we can ensure logs will be replicated to all known working nodes.

PD should be the one to trigger `FORCE_LEADER` state transition. It can either broadcast failure node list to all alive nodes and let them triggering `FORCE_LEADER` state or send a command to control specific region. It's required that failure nodes should never be able to rejoin the cluster and should be physically stopped.

**Comment by NingLin-P** [comment]
> Let's introduce a FORCE_LEADER state. If a peer enters a `FORCE_LEADER` state, it will become leader immediately without counting majority votes. And all its logs will also be committed without replicating to majority. A node in `FORCE_LEADER` state will only accept new conf change proposals and `EXIT_FORCE_LEADER` proposal. After exiting `FORCE_LEADER`, it will need a new election to become leader again.

We may need mechanisms to ensure more things:
- Only one alive peer enter `FORCE_LEADER` state, so conflict entries (same index with different term) won't be committed 
- The alive peer with the highest `commit_index` enter `FORCE_LEADER` state, so `MsgAppend` won't be rejected because log index lower than the receiver's `commit_index`
