### ISSUE TITLE
Fix design of engine_traits for mutual associated types / type bound equality

### ISSUE THREAD

**Issue by brson** [tikv/tikv#6124]
Part of https://github.com/tikv/tikv/issues/4184, abstracting the storage engine.

My most recent work in https://github.com/tikv/tikv/pull/6122 ran into a problem with the way associated types are used in engine_traits.

The basic problem is that multiple traits have different associated types which must resolve to the same type in generic functions, but I don't know how to make that happen. Here is a simplified example:

```
trait KvEngine {
    type Snapshot: Snapshot;
    
    fn get_snapshot(&self) -> Self::Snapshot;
}

trait Snapshot {
    type KvEngine: KvEngine;
    
    fn snap(&self, e: &Self::KvEngine);
}

fn do_thing<E>(e: &E) where E: KvEngine {
    let snapshot = e.get_snapshot();
    snapshot.snap(&e);
}
```

This doesn't compile because:

```
   |
15 |     snapshot.snap(e);
   |                   ^ expected associated type, found type parameter
   |
   = note: expected type `&<<E as KvEngine>::Snapshot as Snapshot>::KvEngine`
              found type `&E`
```

I don't know the idiomatic solution to this today.

**Comment by nrc** [comment]
I think `Snapshot` should not have the engine assoc type - assoc types should be a DAG, IMO.

You can then do something like:

```
trait KvEngine {
    type Snapshot: Snapshot;
    
    fn get_snapshot(&self) -> Self::Snapshot;
}

trait Snapshot: Sized {
    fn snap<K: KvEngine<Snapshot = Self>>(&self, e: &K);
}

fn do_thing<E>(e: &E) where E: KvEngine {
    let snapshot = e.get_snapshot();
    snapshot.snap(e);
}
```

You might need some intermediate bounds too - like a trait which is a sub-trait of `KvEngine` and abstracts over the things `Snapshot` requires from a `KvEngine`.

**Comment by BusyJay** [comment]
How about
```
fn do_thing<E>(e: &E)
where
    E: KvEngine,
    E::Snapshot: Snapshot<KvEngine=E>
{}
```

**Comment by overvenus** [comment]
I'm not sure what we want to with `fn snap`(maybe create a new snapshot?), though I think we can change `KvEngine` to a genic parameter.

```
trait KvEngine {
    type Snapshot: Snapshot;

    fn get_snapshot(&self) -> Self::Snapshot;
}

trait Snapshot {
    type SyncSnap;

    fn into_sync(&self) -> Self::SyncSnap;

    fn snap<E: KvEngine>(&self, e: &E)
    where
        Self: Sized;
}

fn do_thing<E>(e: &E) -> Box<dyn Snapshot<SyncSnap = ()>>
where
    E: KvEngine,
    E::Snapshot: Snapshot<SyncSnap = ()> + 'static,
{
    let snapshot = e.get_snapshot();
    snapshot.snap(e);

    Box::new(snapshot)
}
```

**Comment by brson** [comment]
Thanks for the suggestions. I'll do some experiments with these ideas and report back.

**Comment by brson** [comment]
I've addressed this in https://github.com/tikv/tikv/pull/6179 by turning any "backward"-referencing associated types into type parameters on the trait.
