### ISSUE TITLE
Fail to execute `cargo check` in `components/tikv_util` 

### ISSUE THREAD

**Issue by iosmanthus** [tikv/tikv#6145]
### Steps to reproduce
`cargo check` in `components/tikv_util` 
### What did you expect?
`cargo check` exits normally.

### What did happen?
`cargo check` failed and report: 
```
error[E0599]: no method named `generate_files` found for type `&Builder` in the current scope
  --> /home/iosmanthus/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-build-0.10.0/src/lib.rs:56:14
   |
56 |         self.generate_files();
   |              ^^^^^^^^^^^^^^

error: aborting due to previous error

```

**Comment by cireu** [comment]
`components/tidb_query` can't run `cargo check` neither.

**Comment by breeswish** [comment]
@nrc @BusyJay @brson PTAL, thanks! It might not be friendly that general cargo commands doesn't work in our project.

**Comment by nrc** [comment]
You must specify either `prost-codec` or `protobuf-codec` feature for it to work. It would be better if this was not required, but it is tricky
