### ISSUE TITLE
PCP: Refine LocalHistogramTimer in rust-prometheus

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#6171]
## Description

Currently `LocalHistogramTimer` isn't actually local. It clones the global histogram inside.

A proposed change can be:

```rust
impl LocalHistogram {
    fn observe_closure_duration<F, T>(&self, f: F) -> T where F: FnOnce() -> T {
        ...
    }
}
```

The usage can be:

```rust
some_local_histogram.observe_closure_duration(|| {
    do_something()
})
```

## Difficulty

- Easy

## Score

- 50

## Mentor(s)

- @breeswish

## Recommended Skills

- Rust programming

**Comment by Renkai** [comment]
pick up challenge,unformally

**Comment by breeswish** [comment]
Implemented in https://github.com/tikv/rust-prometheus/pull/296
