### ISSUE TITLE
some test run in `make dev` not run on CI

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#6180]
### What did you expect?
`make ci_test` just run one `cargo test` and create test binarys. but in `make dev` it has three `cargo test`. seems we miss some tests in CI. 
The pr https://github.com/tikv/tikv/pull/6101 did not run success in `make dev`, but in ci it success

**Comment by mahjonp** [comment]
Got, I will make it rollback to use `make dev` now.

**Comment by zhouqiang-cl** [comment]
And in order to speed ci. maybe we can run the 3 `cargo test` in multi node. and then run the tests

**Comment by mahjonp** [comment]
Sorry, but I see that there were no commits passed the CI test. And for the two `cargo test` we have ignored, one is about bench and another is about mem-profiling, I think they won't cause some important cases to be missed.
