### ISSUE TITLE
Show profile and enabled features in version output

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#6195]
It will be nice to know how the binary is compiled including its enabled features and profile.

Usually the information is collected by build script, but build script was removed from the project due to #3368.

Fortunately we still have Makefile. Giving that we already need to use `make dist_release` to generate binaries used in production, I think it's OK to rely on Makefile to gather those necessary information. For features, we can just dump the environment variable `ENABLE_FEATURES`. For profile, we can either define a new environment variable, or just inspect the value of cargo environment variable `OUT_DIR`, which should have sub-string `target/release/` for release profile and `target/debug/` for debug profile.

Contributors can add the information into function `tikv_version_info`, which is defined in src/lib.rs.

/cc @overvenus @nrc

**Comment by zhangmoon** [comment]
I'd like to try this.

**Comment by BusyJay** [comment]
@zhangmoon Thanks!

Just another thought, maybe the build script can be just added to simplify the detection. But make sure to print "cargo:rerun-if-changed=build.rs" to avoid triggering the rebuild accidentally like #3368.

/cc @breeswish

**Comment by BusyJay** [comment]
Resolved by #6215.
