### ISSUE TITLE
Support Restore Raw KV

### ISSUE THREAD

**Issue by 3pointer** [tikv/tikv#6220]
### Is your feature request related to a problem? Please describe:

This is a part of implementing Raw KV backup & restore ( pingcap/br#86 ).

### Describe the feature you'd like:

current [download](https://github.com/tikv/tikv/blob/master/components/sst_importer/src/sst_importer.rs#L89) and [ingest](https://github.com/tikv/tikv/blob/master/components/sst_importer/src/sst_importer.rs#L60) already support Txn KV. so we can reuse download and ingest logic.then we need  
1. skip rewrite rule in download
2. adapt to raw kv in download

**Comment by 3pointer** [comment]
Currently we can deal this with BR, so ignore this issue

**Comment by MyonKeminta** [comment]
TiKV don't need any modification to support this. Close it.
