### ISSUE TITLE
TiKV server doesn't start at all

### ISSUE THREAD

**Issue by sntdevco** [tikv/tikv#6235]
## Bug Report

When TiKV servers are started in the following way:
```shell
./bin/tikv-server --pd-endpoints="127.0.0.1:2379"  --addr="127.0.0.1:20160"  --data-dir=tikv1  --log-file=tikv1.log
```
The command fails with the following log:
```log
[2019/12/14 09:20:24.009 +05:30] [FATAL] [server.rs:492] ["the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 82920"]
```

### What version of TiKV are you using?
Release Version:   4.0.0-alpha
Git Commit Hash:   b147b38eeaae4129e7e3eb7c06e270b8e0682697
Git Commit Branch: master
UTC Build Time:    2019-12-13 12:51:13
Rust Version:      rustc 1.39.0-nightly (c6e9c76c5 2019-09-04)

### What operating system and CPU are you using?
Ubuntu Server 18.04.3 LTS (CPU: vCPU)

### Steps to reproduce
Launch `tikv-server` using the given command

### What did you expect?
TiKV was expected to start as normal, but instead it failed
Current file descriptor limit:
`cat /proc/sys/fs/file-max` => 100000
So I can't see the reason why this failed

**Comment by zhangjinpeng1987** [comment]
@sntdevco Would you mind show the output of `ulimit -n`?

**Comment by 5kbpers** [comment]
`/proc/sys/fs/file-max` is the kernel-level limit on the number of FDs, you could change the process-level limit through `ulimit -n 82920` or modifying `/etc/security/limits.conf`.

**Comment by sntdevco** [comment]
@zhangjinpeng1987 It is 82920
