### ISSUE TITLE
Add uptime metrics

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#6271]
## Feature Request

Add uptime metrics as TiDB to show how long it is since TiKV is started.

**Comment by 5kbpers** [comment]
![image](https://user-images.githubusercontent.com/20279863/74038753-a01b8b00-49fb-11ea-8719-3adb5e915273.png)
Added it to tidb-ansible: https://github.com/pingcap/tidb-ansible/pull/1134
