### ISSUE TITLE
Switch to use TiDB's Duration memory layout for Copr Duration

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#6368]
## Description

Currently TiKV's Duration is implemented using bit flags. It can be changed to stick to TiDB's Duration memory layout (which uses `gotime.Duration` directly) so that Coprocessor can support executing over TiDB's Chunk format directly in future.

Goals:

1. Removes the fsp in current Duration implementation.
2. Change to use the same memory format for the Duration.
3. Your new implementation should be compatible with the Chunk format.

## Difficulty

- Medium

## Score

- 2700

## Mentor(s)

- @breeswish 
- @iosmanthus 

## Recommended Skills

- Rust and Golang programming

**Comment by andylokandy** [comment]
Alright then

**Comment by breeswish** [comment]
@andylokandy Remember to do it in non-working time :)
