### ISSUE TITLE
A failed merge may cause a later success merge lost data

### ISSUE THREAD

**Issue by gengliqi** [tikv/tikv#6460]
Suppose region A wants to merge to region B.
But after executing the PrepareMerge, region B split and change the epoch. So this merge must be rollback.

Then region A starts the next merge and it succeeds.
Unfortunately, a peer runs slowly and its apply index is smaller than the first PrepareMerge log index.  
At this time, this peer's corresponding target peer is applying CommitMerge and sends msg to this peer for catching up logs.

After this peer applies the first PrepareMerge log, it mistakenly thinks itself is up to date for the **next** merge. So the target peer will go on applying CommitMerge.

Some data may be lost because the source peer doesn't apply all of the logs in the process of merging.

**Comment by zhangjinpeng1987** [comment]
@gengliqi Do you have solution to fix it?

**Comment by gengliqi** [comment]
> @gengliqi Do you have solution to fix it?

Yes. The fix PR is almost finished. (needs to add more tests)
