### ISSUE TITLE
Consider setting `recycle_log_file_num` in RocksDB?

### ISSUE THREAD

**Issue by huachaohuang** [tikv/tikv#6486]
### Describe the feature you'd like:

Setting `recycle_log_file_num > 0` to speed up WAL in sync mode.

### Teachability, Documentation, Adoption, Migration Strategy:

```c++
  // Recycle log files.
  // If non-zero, we will reuse previously written log files for new
  // logs, overwriting the old data.  The value indicates how many
  // such files we will keep around at any point in time for later
  // use.  This is more efficient because the blocks are already
  // allocated and fdatasync does not need to update the inode after
  // each write.
  // Default: 0
  size_t recycle_log_file_num = 0;
```

**Comment by siddontang** [comment]
Thanks @huachaohuang 

I remember I did a simple test before and found using this feature can improve the performance in a simple benchmark but had a little gained when benchmarking TiDB. 

But I still think we need to enable this. Can you send a PR to change it?

**Comment by huachaohuang** [comment]
Well, I am reviewing some RocksDB options recently. So maybe I will drop by and make some contributions if I find other interesting options that also apply to TiKV.

**Comment by yiwu-arbug** [comment]
Related bug fix in upstream: https://github.com/facebook/rocksdb/pull/5900

**Comment by yiwu-arbug** [comment]
Looks like it's not compatible with point-in-time recovery which we are using: https://github.com/facebook/rocksdb/pull/6351

**Comment by huachaohuang** [comment]
@yiwu-arbug Thanks for reminding.
