### ISSUE TITLE
RocksDB log rotate away even when panic_mark_file is set

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#6495]
### What version of TiKV are you using?
v3.0.5

### What operating system and CPU are you using?
unknown

### Steps to reproduce
For a instance we see rocksdb detected LSM corruption (with force_consistency_checks=true) and set background error. Tikv server set panic_mark_file and exist accordingly. Then the tikv server fall in restart loop, each time refuse to start since panic_mark_file exists. However, rocksdb log and manifest at the point of corruption is rotated away, makes it impossible to investigate the corruption. I checked the logic, tikv call `fatal!` which call `std::process::exit` if panic_mark_file exists before opening rocksdb, so the above shouldn't happen. I also run tikv locally but didn't reproduce the issue. 

My question is how this could happen and is there anything we can do to prevent rocksdb log being purged.

link to the issue: https://asktug.com/t/topic/2528

### What did you expect?
Tikv should not start rocksdb when panic_mark_file is set.

### What did happened?
See above.

**Comment by BusyJay** [comment]
The issue said mark file had been deleted. I think it worked as expected.

**Comment by yiwu-arbug** [comment]
@BusyJay you are right. I double check the log and the mark file was deleted and thus tikv restarts rocksdb.
