### ISSUE TITLE
Configuration validation doesn't find misspelled option names in config file

### ISSUE THREAD

**Issue by kolbe** [tikv/tikv#6498]
### What version of TiKV are you using?

```
Release Version:   3.1.0-beta.1
Git Commit Hash:   b8b9327f615e9c54a08772b53505a9f864ce55cb
Git Commit Branch: release-3.1
UTC Build Time:    2020-01-12 05:58:49
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)
```

### What operating system and CPU are you using?

Darwin seastar.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

### Steps to reproduce

```
printf %s\\n > tikv.toml '[rocksdb]' 'max_open_files = 20000'
tikv-server -C ./tikv.toml --pd=127.0.0.1 --config-check
tikv-server -C ./tikv.toml --pd=127.0.0.1  2>&1 | grep -o 'max.open.files..........'
```

### What did you expect?

Using `max_open_files` should either work correctly or should cause configuration validation to fail. Silently accepting invalid configuration items can lead to serious security issues and a lot of wasted time for DBAs.

### What did happened?

TiKV silently accepted `max_open_files` instead of `max-open-files`, even though `max_open_files` is invalid and has no effect.

**Comment by kennytm** [comment]
cc serde-rs/serde#1609.

**Comment by siddontang** [comment]
@kennytm 

seem serde hasn't solved this problem, so what can we do in TiKV now?

**Comment by kennytm** [comment]
We could either:

1. generate 2 sets of structs (manually or via proc macros), one for --config-check which has  `#[serde(deny_unknown_fields)]` and one for normal use which does not have the attribute; or
2. patch serde ourselves, and use our fork until it is merged upstream.

**Comment by kolbe** [comment]
I'd rather the default behavior be for tikv-server to refuse to start if there are any invalid options in a config file, regardless of whether --check-config is used.

I got some pushback on this being the default in tidb-server, but I did add a --strict-config option there. Maybe the same could be done in TiKV?

**Comment by kennytm** [comment]
@kolbe 

> I'd rather the default behavior be for tikv-server to refuse to start if there are any invalid options in a config file, regardless of whether --check-config is used.

We tried that but it breaks backward compatibility (#5286) and needs to be reverted. 

Adding a `--strict-config` still requires https://github.com/tikv/tikv/issues/6498#issuecomment-578289387 since currently `serde` only supports picking a single behavior (ignore or error) per type.

**Comment by gregwebs** [comment]
Should we extend serde for our use case then?
