### ISSUE TITLE
Set write_global_seqno=false for file ingestion

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#6501]
Currently for file ingest to rocksdb, we use the default `write_global_seqno=true` option. With the option on, rocksdb write global seqno in ingested SST files. The operation is done while holding global db mutex, and require an IO. It will impact p99 write latency. This is the behavior when rocksdb initially introduce file ingestion. Later the `write_global_seqno=false` option is introduce where the global seqno is written to manifest file, and the IO operation is outside of the critical section.

The task is to expose the option from rust-rocksdb side, and update TiKV to set `write_global_seqno=false` on ingesting SST file.

Note: after setting `write_global_seqno=false`, DB is not able to be opened by TiKV 2.1 or earlier version.

Task breakdown:
- [ ] (in https://github.com/tikv/rust-rocksdb) Update `IngestExternalFileOptions` to allow setting `write_global_seqno`
- [ ] (in https://github.com/tikv/tikv) Update all call site of `IngestExternalFileOptions` to set write_global_seqno=false.

**Comment by yiwu-arbug** [comment]
cc @BusyJay this could be among storage stability TODO list, although relatively minor.

**Comment by yiwu-arbug** [comment]
cc @Connor1996

**Comment by Connor1996** [comment]
TiKV doesn't promise backward compatibility. LGTM, but maybe we disable it since 4.0, not 3.0/3.1(not sure if anyone is using it)

**Comment by yiwu-arbug** [comment]
@hskang9 mind take a look at this task and let me know if you have any questions? Thanks.

**Comment by sunxiaoguang** [comment]
Looks like this feature was implemented recently. We can close it if I'm not wrong.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/3982329/130467666-d6d9018c-f214-4de3-aecf-6d0a8e09e47b.png">

PTAL @yiwu-arbug

**Comment by yiwu-arbug** [comment]
@sunxiaoguang thanks for notice. closing.
