### ISSUE TITLE
[GSoC Proposal] Support Cold/Hot Tier storage in TiKV

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#6507]
TiKV uses RocksDB as its storage layer, currently RocksDB support assigns a list of path, newer data is placed into paths specified earlier in the list while older data gradually moves to paths specified later in the list. For example we may use a 300GB fast local SSD as the first path, and a 2TB HDD disk as the second path, and an 16TB remote network disk as the last path. This will reduce the total cost, but the older data doesn’t mean it is cold data. If there is some older but frequently accessed data, it will host in block-cache normally, but the total memory is limited. If this frequently accessed data can be pulled up to the first path(the local fast ssd), it can achieve a better read performance for TiKV.

**Comment by hskang9** [comment]
Hello @yiwu-arbug, I am interested in this task, where can I get started?

**Comment by yiwu-arbug** [comment]
@hskang9 Thank you for interest for the project. Please join tikv-wg.slack.com on Slack and ping me (Yi Wu). We can discuss in more detail. Thanks.

**Comment by govardhangdg** [comment]
Hello @yiwu-arbug! I am interested in taking  this project up as part of GSoC.

**Comment by yiwu-arbug** [comment]
No applicant at last. Closing.
