### ISSUE TITLE
TiKV /debug/pprof/profile should recognize go tool pprof

### ISSUE THREAD

**Issue by YangKeao** [tikv/tikv#6523]
### Is your feature request related to a problem? Please describe:

If I use `go tool pprof -http=:8080 http://status_server/debug/pprof/profile\?seconds=10`, `parsing profile: unrecognized profile format` will occur. That's because TiKV doesn't recognize pprof's request and return an svg format flamegraph.

### Describe the feature you'd like:

Now it takes two step to use `go tool pprof` to perf TiKV.

1. Download perf protobuf through curl `curl -H "Content-Type: application/protobuf"  http://status_server/debug/pprof/profile\?seconds=50 > some.pb`

2. Use pprof to decode this protobuf `go tool pprof -http=:8080 some.pb`.

We can reduce this procedure to single step by recognizing pprof's request.

### Describe alternatives you've considered:

The request of pprof can be detected with `User-Agent: Go-http-client`. Though this will influence all go client.

**Comment by siddontang** [comment]
Mostly, for TiDB, we will fetch the PB file at first then use `go tool pprof` to see it. So I think the current way is fine.

**Comment by YangKeao** [comment]
Ok. If it's acceptable. That's fine :rocket:
