### ISSUE TITLE
When sync-log=false, fsync raftdb before kvdb persists data

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#6540]
There are value in using sync-log=false when small data loss on edge case can be tolerate, and bare metal performance is desired. However, current a TiKV node may not be able to recovery from power off, if kvdb have newer data than raftdb. This can be fixed by fsync raftdb before every time kvdb persists it's data (e.g. flush memtable). This can be done in rocksdb `OnFlushBegin` callback.

**Comment by Rustin-Liu** [comment]
I am working on it.

**Comment by yiwu-arbug** [comment]
Thanks for offer to help. Do you mind joining tikv slack (tikv-wg.slack.com) and join the #engine-sig channel for discussion? Thanks.

**Comment by BusyJay** [comment]
I don't think this is going to solve the issue as expected. KV db persists data by writing to WAL, it doesn't matter whether memtable is flushed.

**Comment by yiwu-arbug** [comment]
@BusyJay great thanks for chime in. I don't know why I totally forget WAL. Looks like the fix is only useful after we remove kvdb WAL. Otherwise, together with the fix, a WAL filter can be implemented to avoid replaying those data newer than raft log. I would prefer we wait till kvdb WAL is removed to get this fix.

**Comment by zhangjinpeng1987** [comment]
https://github.com/tikv/tikv/pull/8631 has removed the sync-log parameter.
