### ISSUE TITLE
UCP: Add WAL write duration metric

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#6541]
## Description

We need to add WAL write duration stats on rocksdb side and expose it through prometheus. The metric is useful in debugging write latency issue. It can tell whether write latency change is caused by IO or CPU usage. In particular, it consist of the following tasks:
- [x] in https://github.com/tikv/rocksdb repo, add a new enum value `DB_WRITE_WAL_TIME` to `Histograms`. Follow the example of how `DB_WRITE` is measured (https://github.com/tikv/rocksdb/blob/6.4.tikv/db/db_impl/db_impl_write.cc#L90), add a `StopWatch` to measure time spend in `DBImpl::WriteToWAL` (https://github.com/tikv/rocksdb/blob/6.4.tikv/db/db_impl/db_impl_write.cc#L1108)
- [ ] (optional) contribute the code to upstream https://github.com/facebook/rocksdb
- [x] in https://github.com/tikv/rust-rocksdb repo, run librocksdb_sys/src/generate.py to update code correspondingly.
- [x] in https://github.com/tikv/tikv repo, follow what's done for `DbWrite` in engine_metrics.rs, add changes for `DbWriteWalTime` correspondingly.
- [ ] in https://github.com/pingcap/tidb-ansible repo, in scripts/tikv_details.json file, search for `tikv_engine_write_micro_seconds`, follow what's done to add config for `tikv_engine_write_wal_time_micro_seconds`.
- [ ] Testing: start a tidb cluster on your compute using tidb-ansible. Open Grafana and turn to tikv details page. In RocksDB - kv and RocksDB - raft sections, locate the "Write WAL duration` graph. Take a snapshot and post here.

## Difficulty

- Medium

## Score

- 1300

## Mentor(s)

- @yiwu-arbug 

## Recommended Skills

- C++
- Rust

**Comment by siddontang** [comment]
can you give more information about how to support it?

**Comment by yiwu-arbug** [comment]
@hawkingrei let me know if you have any questions! For online discussion, join tikv-wg.slack.com in Slack and join #engine-sig channel.

**Comment by yiwu-arbug** [comment]
@hawkingrei Thanks for picking up the task! Let me know if you have any questions. For online chat, you can join tikv-wg.slack.com on Slack and join #engine-sig channel.

**Comment by hawkingrei** [comment]
Thank you. I will try it at weekends. If I have any questions, I will communicate with you.

**Comment by hawkingrei** [comment]
@yiwu-arbug PLAT (#153)[https://github.com/tikv/rocksdb/pull/153]

**Comment by yiwu-arbug** [comment]
@hawkingrei I'm updating rust-rocksdb for you at https://github.com/tikv/rust-rocksdb/pull/445

**Comment by hawkingrei** [comment]
@yiwu-arbug I add DbWriteWalTime to tikv now.
