### ISSUE TITLE
Config for Block-Cache Capacity lose efficacy when we use TiDB Lightning to import data.

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/tikv#6545]
### What version of TiKV are you using?

master: 7c679639885172814c4ef28f00d190337ce284a4

### What operating system and CPU are you using?

AWS i3.4xlarge

### Steps to reproduce

We execute 'drop table' in a TiDB-cluster, and then import data to TiKV by TiLightning.
Then I observer the size of block cache decreasing to 4GB from 64GB. 

### What did you expect?
We expect that the capacity of block-cache remain unchanged.
### What did happened?
![image](https://user-images.githubusercontent.com/16376959/74008129-19df5480-49bb-11ea-8308-452e8aa14173.png)

**Comment by siddontang** [comment]
PTAL @kennytm

**Comment by kennytm** [comment]
Likely caused by this line

https://github.com/tikv/tikv/blob/bd94da3107ad4d515458068b124d8b107ebac1e6/components/sst_importer/src/import_mode.rs#L105

**Comment by Little-Wallace** [comment]
Importer would set the config backup when it turns to 'normal_mode'. But if TiKV uses 'shared_cache' , importer would changed it by the value of cf-options's block-cache-size.
```
cf_opts.set_block_cache_capacity(self.block_cache_size)?;
```

**Comment by Little-Wallace** [comment]
TODO:

- We need to find out why the size of block-cache was changed into '4GB' rather than '128MB', which is size of block-cache of `RAFT_CF`. 'raft-cf' is the last CF in RocksDB.
- Add interface to get capacity of `shared-block-cache`, and pass `shared` to importer.
- Ban interface `set_block_cache_capacity` of `ColumnFamilyOptions` if this CF use a shared block-cache.
