### ISSUE TITLE
Support collation in Coprocessor executors

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#6577]
## Feature Request

This is a follow up for https://github.com/tikv/tikv/issues/6574. Coprocessor aggregate and topN executors need to be updated to respect collation.

- [x] Vec TopN
- [x] Vec Stream Aggregate
- [x] Vec Fast Hash Aggregate
- [x] Vec Slow Hash Aggregate
- [x] Vec Simple Aggregate  -- No need to update

**Comment by andylokandy** [comment]
@breeswish Does non-vec executor even exist?

**Comment by breeswish** [comment]
@andylokandy Yes and they will not be removed in 4.0 so that we need to support them. See `executor` directory.
