### ISSUE TITLE
raftstore: read index may fail after node restart

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#6596]
## Bug Report

After a leader hibernates, it doesn't send heartbeats to replicas. Once a replica is restarted at this time, the replica cannot find who the leader is, then all the read index requests will be rejected.

**Comment by zhangjinpeng1987** [comment]
@5kbpers @gengliqi Does https://github.com/tikv/tikv/pull/6598 fix this issue?

**Comment by 5kbpers** [comment]
@zhangjinpeng1987 No, but this issue can be fixed by a similar way.
