### ISSUE TITLE
2020-02-18: 25% performance regression on TPCC

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#6638]
## Bug Report

There is a 25%  performance regression on our TPCC daily benchmarking.

1. What did you do?

Run performance test daily

2. What did you expect to see?

None.

3. What did you see instead?

Version:
tidb: 6d50a47a8b70df8b6d43bc9b593c7602fe997f3c(master) 2020-02-16 11:55:03
tikv: aa786e1c3cd20260ce3258779438b29afbd933fc(master) 2020-02-17 08:10:55
pd: a1e13640572e3d6eadabf76c2869541c0c443956(master) 2020-02-17 01:50:09

Compare:
tidb: https://github.com/pingcap/tidb/compare/6d50a47...6d50a47
tikv: https://github.com/tikv/tikv/compare/36dab75...aa786e1
pd: https://github.com/pingcap/pd/compare/a1e1364...a1e1364

tidb_max_cpu: 16.16, delta: -15.90%
tikv_max_cpu: 18.91, delta: 33.37%
tidb_max_memory: 1679.57 MiB, delta: -14.28%
tikv_max_memory: 2121.40 MiB, delta: -96.43%

Measured tpmC (NewOrders): 17772.85 ± 0.00% (std=0.00), delta: -25.22% (p=nan)

4. What version of TiKV are you using?

aa786e1c3cd20260ce3258779438b29afbd933fc

**Comment by nrc** [comment]
The offending PR was backed out, so this is fixed. I'm redoing the PR in #6644
