### ISSUE TITLE
Cannot compile TiKV on ARM64

### ISSUE THREAD

**Issue by n0vad3v** [tikv/tikv#6639]
### What version of TiKV are you using?

v4.0.0-beta

### What operating system and CPU are you using?

CentOS 7.6 with arm64.

### Steps to reproduce

`ROCKSDB_SYS_SSE=0 make dist_release`

### What did you expect?
The successful compile of TiKV.

### What did happened?
```
error[E0433]: failed to resolve: could not find `arch` in `self`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.3/src/lib.rs:50:37
   |
50 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
   |                                     ^^^^ could not find `arch` in `self`
   Compiling error-chain v0.12.1
   Compiling publicsuffix v1.5.3
error: aborting due to previous error
For more information about this error, try `rustc --explain E0433`.
error: could not compile `raw-cpuid`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It seems that `raw-cpuid` does not support arm.

**Comment by kennytm** [comment]
Thanks for the report.

The build failure is caused by lovesegfault/cache-size#3. We'll workaround it by making `cache-size` (and thus `raw-cpuid`) an x86-only dependency.

**Comment by brson** [comment]
This bug is still present, with a slightly different version of raw-cpuid:

```
error[E0433]: failed to resolve: could not find `arch` in `self`
  --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-8.1.2/src/lib.rs:50:37
   |
50 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
   |                                     ^^^^ could not find `arch` in `self`

   Compiling const-random-macro v0.1.6
error: aborting due to previous error
```

I don't see cache-size in Cargo.lock, but I do see raw-cpuid being used by the x86 crate, which is used by perfcnt, which is used by criterion-perf-events.

**Comment by brson** [comment]
I put in a PR that should fix the build.
