### ISSUE TITLE
too many "all pending logs are applied" logs

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#6649]
### What version of TiKV are you using?
Latest master.

### What operating system and CPU are you using?
No matter.

### Steps to reproduce
Start **one** tikv server and keep inserting.

### What did you expect?
Nothing.

### What did happened?
TiKV keep printing "all pending logs are applied" logs.

**Comment by hicqu** [comment]
I guess it's introduced by early apply. PTAL @BusyJay thanks!

**Comment by BusyJay** [comment]
But early apply has not been merged into master yet. See #6154.

**Comment by BusyJay** [comment]
It should be caused by apply yield.
