### ISSUE TITLE
Coredump when running test case

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#6651]
## Bug Report

When running
```
make dev
```
, after a long test case name and it printed a core dump message without any panic or fail case name. The message looked like following:
```
tikv-e88ed24a0ad8c177: /home/jay/.cargo/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/6191b41/librocksdb_sys/rocksdb/memory/jemalloc_nodump_allocator.cc:123: virtual rocksdb::JemallocNodumpAllocator::~JemallocNodumpAllocator(): Assertion `s.ok()' failed.
```
@yiwu-arbug @Connor1996 any ideas?

### What version of TiKV are you using?
master

### What operating system and CPU are you using?
Linux

### Steps to reproduce
I can't reproduce it anymore. But what I did was just `make dev`.

### What did you expect?
Tests finish normally.

### What did happened?
Coredumped.

**Comment by yiwu-arbug** [comment]
This is rocksdb failed to destroy jemalloc arena that it creates for block cache. Without a reproduce it is hard to know what's the error return from jemalloc. Related code: https://github.com/facebook/rocksdb/blob/master/memory/jemalloc_nodump_allocator.cc#L92

**Comment by zhangjinpeng1987** [comment]
Can't reproduce again.
