### ISSUE TITLE
Broadcast WakeUp message for awakening hibernated regions after node restarts

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#6667]
### Is your feature request related to a problem? Please describe:

After enable `hibernate regions`, the leader may go into `Idle` State. If a region splits during a node is down, after that node restarts, the newly created region will not be created on the node until the leader is awakened.

### Describe the feature you'd like:

It may hurt the performance of replica read. We could add an **option** for broadcasting `MsgWakeUp` after a node is restarted.

**Comment by BusyJay** [comment]
Is it solved?

**Comment by 5kbpers** [comment]
> Is it solved?

Not yet. Is it duplicate with https://github.com/tikv/tikv/issues/9022 ?

**Comment by BusyJay** [comment]
Perhaps. It depends on which "leader" it refers to in sentence:
>  the newly created region will not be created on the node until the leader is awakened.

And 
> We could add an option for broadcasting MsgWakeUp after a node is restarted.

will not solve the problem as the split learner doesn't exit at all.

**Comment by BusyJay** [comment]
@5kbpers do you have time to solve this?
