### ISSUE TITLE
kv_pessimistic_lock can return values to reduce RPCs

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#6680]
### Describe the feature you'd like:

In pessimistic transaction, TiDB executes DML first to get modifications it needs to write, then acquires pessimistic locks on each modication. In some cases, If we know what need to write, e.g., select ... for update where pk = 1, we can lock the key directly and return the value to TiDB. If that, we can reduce some RPCs in some cases.

Furthermore, because pessimistic transaction needs the latest value, we can return the latest value and its commit ts to TiDB instead of a write conflict error to eliminate retry.

**Comment by innerr** [comment]
OH, I think this had been done on branch tpcc-perf

**Comment by youjiali1995** [comment]
> OH, I think this had been done on branch tpcc-perf

Yes. It should also implement in master.
