### ISSUE TITLE
The link for `Try TiKV and TiDB` is broken in Readme.md

### ISSUE THREAD

**Issue by lsampras** [tikv/tikv#6688]
## Bug Report

The link for `Try TiKV and TiDB` under [Try TiKV](https://github.com/tikv/tikv#testing-deployment) leads to `404`.

The current URL is `https://github.com/pingcap/docs/blob/master/dev/how-to/get-started/deploy-tidb-from-docker-compose.md`

Should this be pointing at [docs/how-to/get-started/deploy-using-docker-compose.md](https://github.com/tikv/tikv/blob/master/docs/how-to/get-started/deploy-using-docker-compose.md) instead.

I can submit a PR on this if needed....

**Comment by ngaut** [comment]
Please file a PR, thank you.
