### ISSUE TITLE
Coprocessor Cache is unsound

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#6690]
## Bug Report

The Coprocessor cache works as follows, similar to HTTP cache:

1. TiDB sends a request to TiKV
2. TiKV returns the response, with current apply index.
3. TiDB caches the request, response, apply index.
4. Next time, before TiDB sending the same request, TiDB checks whether this request is cached.
  - If request exists in TiDB local cache, TiDB sends request to TiKV, carry with last apply_index.
  - If request not exists in TiDB local cache, TiDB sends request normally.
5. If TiKV receives a request with apply_index, TiKV checks whether latest apply_index matches the provided apply_index.
  - If apply_index is unchanged, it means the response in TiDB is valid, so TiKV returns empty response (with cache hit = true flag)
  - If apply_index is changed, TiKV returns normal response with current apply index.
6. If TiDB receives a response, with cache hit = true flag, TiDB fills the response from the local cache.

The "same request" concept is determined by the request payload without Timestamp, which means, sending request with different Timestamp but identical process payload is the same request. This is to make sure that in most cases the cache can work (since we almost never provide the same timestamp).

This process has a bug. If we send request use a old TS, cached response **may** not be safely used for a new TS. If old TS cannot scan **latest** data, then the response must not be cached.

The proposed change is as follows:

1. Add a field to Coprocessor response, indicating whether this response can be safely cached by TiDB.
2. When scanning data in MVCC, currently we skip (seek) directly to `${key}{start_ts}`. We can change to skip to `${key}{max_ts}`. If scanned key ts > start_ts, it means we found data newer than TS, so that this response must not be cached.
3. When we received locks, we also need to check the lock ts.

**Comment by innerr** [comment]
Start working on it
