### ISSUE TITLE
UCP: Update PD member information every 10 minutes

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#6734]
## Description

We need to update PD member info every 10 minutes. For now, TiKV updates PD member info only  PD leader changes, so TiKV may hold stale info when we add new PD node or remove old PD node and very easy to connect to a wrong address. By updating member info every 10m, we minimize the time window of holding stale info.

## Score 

* 950

## Mentor(s)
* @overvenus 

## Recommended Skills

* Rust asynchronous programming (future-rs & tokio)

## Learning Materials

* [futures doc](https://docs.rs/futures/0.1.29/futures/)
* [tokio doc](https://docs.rs/tokio/0.2.12/tokio/)

**Comment by govardhangdg** [comment]
@zhangjinpeng1987 can you please tell what these challenges are for? Also if they are open for anyone?

**Comment by zhangjinpeng1987** [comment]
> @overvenus , @zhangjinpeng1987 can you please tell what these challenges are for? Also if they are open for anyone?

@govardhangdg This challenge is an activity of PingCAP, will start in a few days, it is for everyone. I will give you more information after it is started.

**Comment by codeworm96** [comment]
I am currently working on this.

**Comment by zhangjinpeng1987** [comment]
> @overvenus , @zhangjinpeng1987 can you please tell what these challenges are for? Also if they are open for anyone?

This activity has started. https://pingcap.com/community/tidb-usability-challenge/

**Comment by rleungx** [comment]
IMO, 10 minutes is still too long for scaling out/in scenarios. @overvenus
