### ISSUE TITLE
UCP: Migrate scalar function `GreatestDecimal` from TiDB

### ISSUE THREAD

**Issue by lonng** [tikv/tikv#6745]
## Description

Port the scalar function `GreatestDecimal` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @breeswish 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

**Comment by breeswish** [comment]
This function has a non-vec implementation, but missing a vec implementation. Close for it is a migration task.
