### ISSUE TITLE
UCP: Migrate scalar function `Uncompress` from TiDB

### ISSUE THREAD

**Issue by lonng** [tikv/tikv#6778]
## Description

Port the scalar function `Uncompress` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @sticnarf 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

**Comment by yeshengm** [comment]
This issue is addressed as a whole in #7807
