### ISSUE TITLE
UCP: Migrate scalar function `JsonDepthSig` from TiDB

### ISSUE THREAD

**Issue by lonng** [tikv/tikv#6809]
## Description

Port the scalar function `JsonDepthSig` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @mapleFU 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

**Comment by skyzh** [comment]
@mapleFU It seems that this has been solved in https://github.com/tikv/tikv/pull/6167 . Maybe we can close this issue?
