### ISSUE TITLE
UCP: Migrate scalar function `Left` from TiDB

### ISSUE THREAD

**Issue by lonng** [tikv/tikv#6937]
## Description

Port the scalar function `Left` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @breeswish 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

**Comment by govardhangdg** [comment]
@lonng  @breeswish, can more information be given about the task. I assumed that I had to write some scalar functions in the https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) and https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr). But there are already implementations of `Left` in https://github.com/tikv/tikv/blob/master/components/tidb_query/src/expr/builtin_string.rs#L875 and 
https://github.com/tikv/tikv/blob/master/components/tidb_query/src/rpn_expr/impl_string.rs#L148. So, I'm confused regarding what has to be done for this task.

**Comment by lonng** [comment]
@govardhangdg I am sorry to confuse you, it's my mistake to file this issue, the function has been implemented, but I was negligent. I will close this issue, thanks for your report.
