### ISSUE TITLE
UCP: Migrate scalar function `Ord` from TiDB

### ISSUE THREAD

**Issue by lonng** [tikv/tikv#6945]
## Description

Port the scalar function `Ord` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @iosmanthus 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

**Comment by jyizheng** [comment]
The links for learning materials are broken.

**Comment by psinghal20** [comment]
I think it is already implemented here: https://github.com/tikv/tikv/blob/master/components/tidb_query_normal_expr/src/builtin_string.rs#L985-L1002
