### ISSUE TITLE
UCP: Migrate scalar function `Right` from TiDB

### ISSUE THREAD

**Issue by lonng** [tikv/tikv#6948]
## Description

Port the scalar function `Right` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @lonng 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

**Comment by palash25** [comment]
@lonng I found this in the codebase `ScalarFuncSig::Right => right_fn_meta(),` has this already been implemented? should this issue be closed?

**Comment by lonng** [comment]
Closed via #6499
