### ISSUE TITLE
Upgrade the outdated vulnerable dependencies

### ISSUE THREAD

**Issue by shafreeck** [tikv/tikv#7004]
### Is your feature request related to a problem? Please describe:

Many of the TiKV dependent libraries are outdated, the latest version may have security issues fixed. Update these libraries to avoid potential vulnerabilities.

### Describe the feature you'd like:

Update the vulnerable or non-maintained libraries.

**Comment by hunterlxt** [comment]
Is it feasible to use the following method ?
grpc-rs compiles bindings by itself during the CI to compare the submitter's code. TiKV can perform `cargo update` detection during the CI to confirm that the submitter's code uses the latest master version
@BusyJay

**Comment by BusyJay** [comment]
It;'s not required to use master version. What the issue describes is different from what you are saying. The issue is about getting rid of vulnerable dependencies reported by `cargo audit`.

**Comment by BusyJay** [comment]
There is still one vulnerable dependency not resolved.
