### ISSUE TITLE
Integrate the fuzz-testing into CI

### ISSUE THREAD

**Issue by shafreeck** [tikv/tikv#7007]
### Is your feature request related to a problem? Please describe:

TiKV integrates multiple different fuzzing libraries to test their project extensively, namely
LLVMs libfuzzer, AFL and Googles Honggfuzz. However, the tests do not run in an
automated pipeline and are currently run sporadically in a manual fashion. To strengthen
the projects security posture, it is recommended to reintegrate the tests into an
automated CI task, running them at least in a monthly rhythm.

### Describe the feature you'd like:

Add the fuzz-testing back to the CI

**Comment by gregwebs** [comment]
another possible rhythm is as part of the release process

**Comment by zhouqiang-cl** [comment]
already done weeks ago
https://internal.pingcap.net/idc-jenkins/job/tikv_continue_fuzz/
