### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by shafreeck** [tikv/tikv#7008]
### Is your feature request related to a problem? Please describe:

To ensure a secure and responsible disclosure of security vulnerabilities, it is important
to have a dedicated point of contact. This person/team should be known, meaning that
all necessary information such as an email address and preferably also encryption keys
of that contact should be communicated appropriately.
The MAINTAINERS.md file lists email addresses of project maintainers that can be
contacted to report vulnerabilities. However, the document omits important details, such
as the respective PGP keys and an outline of the disclosure process. The guideline on
where to report security issues is quite hidden as it is part of the document that also
explains how to set up certificates in TiKV. This is clearly not the appropriate place to
present this kind of information. Instead, it is advised to put all details related to reporting

### Describe the feature you'd like:

Add SECURITY.md in the root repository.

**Comment by dcalvin** [comment]
Closing this issue as resolved in https://github.com/tikv/tikv/pull/7820
