### ISSUE TITLE
Add vulnerability disclosure documentation and link it to the “Community” menu

### ISSUE THREAD

**Issue by shafreeck** [tikv/tikv#7009]
### Is your feature request related to a problem? Please describe:

Currently, the “Secure Config” section contains information on how to report security issues. This may
be rather hard to find and should be more easily reachable from the main website. For
example, the “Community” drop-down could include a reference to the vulnerability
disclosure documentation, to ensure security researchers can responsibly disclose
potential security issues.

**Comment by dcalvin** [comment]
Vulnerability disclosure process as included  https://github.com/tikv/tikv/issues/7008.
