### ISSUE TITLE
status server TLS

### ISSUE THREAD

**Issue by gregwebs** [tikv/tikv#7014]
## Feature Request

The status server should be able to accept TLS connections to encrypt communication. As noted in the security review it has the potential to leak sensitive information.

The security review also mentioned the need to lift TODOs out of the code and into the issue tracker. There is a TODO in the code for this issue right now "TODO: support TLS for the status server."

@shafreeck can you add this to the Security project?

**Comment by niedhui** [comment]
There's a pending PR 😄 https://github.com/tikv/tikv/pull/5393

**Comment by yiwu-arbug** [comment]
mark as done
