### ISSUE TITLE
The argument "metrics-addr" is not working as expected

### ISSUE THREAD

**Issue by silentred** [tikv/tikv#7021]
### What version of TiKV are you using?

Release Version:   3.0.10
Git Commit Hash:   cad9806bf66f0239ef242a7f8c4af22716345c81
Git Commit Branch: release-3.0
UTC Build Time:    2020-02-20 11:44:39
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)

### What did you expect?
Run tikv-server with the arg --metrics-addr <IP:PORT>, the status service would listen on <IP:PORT>

### What did happened?
If the --metrics-addr is set with any value, the status service is not up. The config server.status-addr has to be set to start the status service.

I think it is related to the following codes: 
- config.metric.address is set by https://github.com/tikv/tikv/blob/master/cmd/src/setup.rs#L144
- status_enabled cannot be true if config.metric.address is not empty https://github.com/tikv/tikv/blob/master/cmd/src/server.rs#L733

As this PR #4279 suggests, the goal of adding the arg "metrics-addr" is to make using status service easier.

**Comment by BusyJay** [comment]
Thanks for your report. It's working as expected. `metrics-addr` is where metrics are pushed to, and `status-addr` is where metrics are pulled from, they are different.

I do think it's confusing to have both `metrics-addr` and `status-addr`. Now that we are migrated to pull style, maybe we should sunset `metrics-addr` and hide it from command line. What do you think? /cc @siddontang

**Comment by silentred** [comment]
@BusyJay Thanks. I thought `config.metric.address` was a deprecated config. I will close this issue.

**Comment by silentred** [comment]
@BusyJay Since TiKV is using pulling sytle instead of pushing, I think it would be convenient to expose `status-addr` in command line arguments.

**Comment by siddontang** [comment]
@BusyJay 

For "metrics-addr", I prefer hiding it in the command line at first to keep compatibility. 

Later, we can remove this flag.

**Comment by siddontang** [comment]
> I think it would be convenient to expose status-addr in command line arguments.
@silentred seem you can pass the address explicitly here.

**Comment by silentred** [comment]
@siddontang I've forked a branch having the `status-addr` cmd line argument and run some tests. It seems the status-addr value is saved to pd after TiKV's first start. I am not sure about it.

**Comment by silentred** [comment]
@siddontang Thanks, I will close this issue.
