### ISSUE TITLE
`acquire_pessimistic_lock` has very poor performance if there are many `Write::Lock`s

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#7024]
## Bug Report
With https://github.com/tikv/tikv/pull/6696, TiDB uses `kv_pessimistic_lock` to get the value of a key in some cases. If there are many `Write::Lock`s, the performance is very poor. We should optimize it.
![image](https://user-images.githubusercontent.com/14819777/76084829-c37e2980-5feb-11ea-95a0-e747244094bc.png)

**Comment by siddontang** [comment]
how do you found this problem?

**Comment by sticnarf** [comment]
I think the problem actually has nothing to do with `acquire_pessimistic_lock` itself. The impact is significant because this actions requires a latch and there's no concurrency for a single key.

**Comment by youjiali1995** [comment]
However, the performance degrades. We didn't optimize `MvccReader` for reading data like `PointGetter` or sth else. I think we should do.

**Comment by youjiali1995** [comment]
It's not safe to eliminate `Write::Lock` because it makes commit requests not idempotent. For example, a transaction commits the `select-for-update` key and the lock is removed without a `Write::Lock` left. It's possible that TiDB fails to receive the response and retry. However, the lock is missing and the transaction can't know whether the lock is removed by itself or another one. Even if it doesn't affect correctness because it only happens to secondary locks and we can swallow the error, it may hide the real bugs.

Another problem is it may cause write skew according to this [article](https://mp.weixin.qq.com/s?__biz=MzI1MzYzMjE0MQ==&mid=2247486255&idx=1&sn=ee933f326cfc755289b52d9bb41a129c&chksm=e9d0c0cddea749db184de9415471056acad11ca24888e71404b542a216526fe1ddbafc3f3f75&scene=0&xtrack=1#rd). I don't agree with it but we can postpone the improvement for safety.

 With this fix https://github.com/tikv/tikv/pull/8850, the performance is similar to `PointGetter` now.

**Comment by youjiali1995** [comment]
With this fix https://github.com/tikv/tikv/pull/8850, the performance is similar to `PointGetter` now. Now the problem is how to avoid the regression caused by too many versions, so close it.
