### ISSUE TITLE
UCP: REQUEST_BATCH_SIZE_HISTOGRAM_VEC is not using static metrics

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#7036]
## Description

`REQUEST_BATCH_SIZE_HISTOGRAM_VEC` can be changed to use static metrics to improve performance.

You can see samples like https://github.com/tikv/tikv/pull/4826

## Score 

* 50

## Mentor(s)

* @breeswish 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Rust

**Comment by siddontang** [comment]
can you give some guides about how to optimize it?

**Comment by breeswish** [comment]
@siddontang Added a sample.

**Comment by jyizheng** [comment]
Which part of #4826 is relevant to the issue here?

**Comment by jyizheng** [comment]
@breeswish Which part of #4826 is relevant to the issue here?
