### ISSUE TITLE
UCP: Pause split check when generating a snapshot

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#7058]
## Description

When bulk insert is too fast, a region can be split frequently, which will make snapshot stale very soon. It's possible that a follower can hardly catch up logs with leader when every snapshot becomes stale immediately. pingcap/ticdc#330.

To resolve the issue, split check can be paused if a leader is about to generate and send a snapshot. However to avoid large regions, if the region size exceeds a hard limit, the split check should be resumed.

Split check is issue in file [peer.rs](https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/fsm/peer.rs), snapshot can be checked by snapshot manager or in [peer_storage](https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/peer_storage.rs#L437).

## Difficulty

- Easy

## Score

- 300

## Mentor(s)

- @BusyJay 

## Recommended Skills

- Raft
- Rust

## Learning Materials

This is a comprehensive issue, more codebase information please ref to [contribution-map](https://github.com/pingcap/tidb-map/blob/master/maps/contribution-map.md#tikv-distributed-transactional-key-value-database).

**Comment by SSebo** [comment]
progress update: learning raft and source code.

**Comment by SSebo** [comment]
@BusyJay 

> if the region size exceeds a hard limit, the split check should be resumed.

Is the `size` here if refer to storage size or both storage and keys size?

**Comment by BusyJay** [comment]
Both storage size and key count should be considered. If the estimated storage size or key count is more than two times of `region_max_size` or `region_max_keys`, split should be resumed.

**Comment by SSebo** [comment]
@BusyJay hi mentor, sorry for ask a question not related to this issue, right now our online system use grpc-rs is stop service 😢. Could you give me some advice ? 

thread 'thread 'grpc-poll-5grpc-poll-6' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ', src/libcore/result.rssrc/libcore/result.rs::11651165::55

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'grpc-poll-30' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1165:5
thread 'grpc-poll-1' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1165:5
t

**Comment by SSebo** [comment]
@BusyJay hi, mentor, I don't know if I am on the right track.
- after some dig in, I did not find split check in `store/peer.rs` which you put in the description, but found in https://github.com/tikv/tikv/blob/74854810ac3de2cd60c0566384e09d63c5b1b2d2/components/raftstore/src/store/fsm/peer.rs#L2531. Is it the split check you mention to ? 
- Is it ok to add a logic to check snapshot status in `on_split_region_check_tick` by use `self.ctx.snap_mgr`? I found snapshot manager maintain `registry: HashMap<SnapKey, Vec<SnapEntry>>`,  loop the map to check every snapshot will get the 'Generating' or `Sending` status.
- what is `pause` mean?  just skip the `SplitCheckTask` in `on_split_region_check_tick` ? or spawn a new future to wait something?

**Comment by skyitachi** [comment]
I found use `region_scheduler.is_busy()` to check where snapshot is generating，but I can't found in peerfsm to get region checker coprocesssor config to get `region_max_size` and `region_split_keys`

**Comment by BusyJay** [comment]
@SSebo 
Sorry for the late reply.

1. Yes, you are correct. And now it's fixed.
2. That's not enough. There is a gap between generating and sending. So best way is to check raft peers' progresses, which has a flag indicating if it's about to generate and sending snapshot.
3. Skip it is enough.

**Comment by skyitachi** [comment]
@BusyJay, can use  `region_scheduler.is_busy` to check whether snapshot is generating?

**Comment by BusyJay** [comment]
When a snapshot is being generated, snap_state will become Generating:

https://github.com/tikv/tikv/blob/3a4f6fcc30b30367b122f7a95e0337837f2ade34/components/raftstore/src/store/peer_storage.rs#L868

After that, it's OK to split the region.

**Comment by SSebo** [comment]
@BusyJay hi, mentor, need help
- I found in `fsm/peer`, `self.ctx.cfg.region_max_size` is deprecated, and no way to get `region_max_keys`.
- `region_max_keys` and `region_max_size` has been moved to `coprocessr/split_check`,  how could i get `snap_state` in there?

**Comment by BusyJay** [comment]
To simplify the case, I think you can just set a max skip times. Split check should not be skipped more than 3 times.

**Comment by SSebo** [comment]
@BusyJay If bulk insert is really fast, the speed is changing in different situation,  I am just afraid skip constant times will not enough all the same.

**Comment by BusyJay** [comment]
Yes. There is a trade off between region size and snapshot success rate. Split check is triggered every 10 seconds, If a snapshot can't be generated in 30 seconds, it might be just too large to be generated. Split it into smaller size can help generation.
