### ISSUE TITLE
UCP: Support TLS for the TiKV status server

### ISSUE THREAD

**Issue by shafreeck** [tikv/tikv#7068]
## Description
TiKV takes security seriously.  The status server of TiKV is an HTTP service that is used to supply users with the metrics, configuration, profile, etc. The HTTP server is not safe enough and the data transmitted is not encrypted. It is necessary to support TLS for the TiKV status server.

Closes #7014 

## Difficulty

- Easy

## Score

- 300

## Mentor(s)

- @overvenus 

## Recommended Skills

- TLS
- Rust

## Learning Materials

https://docs.rs/openssl/0.9.20/openssl/ssl/index.html

**Comment by breeswish** [comment]
May be we can push forward this PR? https://github.com/tikv/tikv/pull/5393

**Comment by shafreeck** [comment]
Not regarded as a UCP issue
