### ISSUE TITLE
GC: support to delay the GC for delete record

### ISSUE THREAD

**Issue by 5kbpers** [tikv/tikv#7113]
## Feature Request

In incremental backup & restore, the GC interval may be tuned into much longer in that GC would delete the delete record in the write cf.
To relax the limitation of the GC interval, we could introduce another interval to GC the delete record. That could be like, GC would delete the delete records which were written at more than 30min before the current Safepoint.

**Comment by youjiali1995** [comment]
@MyonKeminta PTAL

**Comment by MyonKeminta** [comment]
Sounds reasonable to me. Let's wait for merging @hicqu 's compaction filter and decide how to do next.

**Comment by 5kbpers** [comment]
Closed it since we already have gc safepoint service.
