### ISSUE TITLE
test raftstore::test_stale_peer::test_node_stale_peer_out_of_region ... thread 'main' panicked

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7167]
raftstore::test_stale_peer::test_node_stale_peer_out_of_region

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18994/pipeline/230 Integration Part16

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
