### ISSUE TITLE
Improve the coverage of the components/codec module

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#7186]
Improve the coverage of the components/codec module https://codecov.io/gh/tikv/tikv/tree/master/components/codec: 

buffer

- [ ] Cursor::bytes
- [ ] Cursor::advance
- [ ] Cursor::advance_mut
- [ ] u8::advance_mut

bytes

- [ ] MemComparableByteCodec::get_first_encoded_len_internal

convert

- [ ] encode_i64_to_comparable_u64
- [ ] decode_comparable_u64_to_i64
- [ ] encode_f64_to_comparable_u64
- [ ] decode_comparable_u64_to_f64

number

- [ ] NumberCodec::encode_u8
- [ ] NumberCodec::decode_u8
- [ ] NumberCodec::encode_u16
- [ ] NumberCodec::decode_u16
- [ ] NumberCodec::encode_u32
- [ ] NumberCodec::decode_u32
- [ ] NumberCodec::encode_u64
- [ ] NumberCodec::decode_u64
- [ ] NumberCodec::encode_u64_desc
- [ ] NumberCodec::decode_u64_desc
- [ ] NumberCodec::encode_i64
- [ ] NumberCodec::decode_i64
- [ ] NumberCodec::encode_i64_desc
- [ ] NumberCodec::decode_i64_desc
- [ ] NumberCodec::encode_f64
- [ ] NumberCodec::decode_f64
- [ ] NumberCodec::encode_f64_desc
- [ ] NumberCodec::decode_f64_desc
- [ ] NumberCodec::encode_u16_le
- [ ] NumberCodec::decode_u16_le
- [ ] NumberCodec::encode_i16_le
- [ ] NumberCodec::decode_i16_le
- [ ] NumberCodec::encode_f32_le
- [ ] NumberCodec::decode_f32_le
- [ ] NumberCodec::encode_u32_le
- [ ] NumberCodec::decode_u32_le
- [ ] NumberCodec::encode_i32_le
- [ ] NumberCodec::decode_i32_le
- [ ] NumberCodec::encode_u64_le
- [ ] NumberCodec::decode_u64_le
- [ ] NumberCodec::encode_i64_le
- [ ] NumberCodec::decode_i64_le
- [ ] NumberCodec::encode_f64_le
- [ ] NumberCodec::decode_f64_le
- [ ] NumberCodec::encode_var_i64

**Comment by liyiheng** [comment]
I'd like to handle it.

**Comment by abbccdda** [comment]
@zhangjinpeng1987 Could I work on this issue? 

Just to clarify, the goal is to ensure all listed functions have test coverage, correct? Btw, it seems not all the listed functions are not covered, for example most functions in NumberCodec are covered with tests already.

**Comment by zhangjinpeng1987** [comment]
@abbccdda some functions are not fully covered, for example some branch is not covered.
