### ISSUE TITLE
UCP: Add metric for raft entries cache

### ISSUE THREAD

**Issue by zhangjinpeng1987** [tikv/tikv#7222]
## Description

Add an `IntGauge` type metric(you can ref to the [AUTO_GC_SAFE_POINT_GAUGE](https://github.com/tikv/tikv/blob/master/src/server/metrics.rs#L258)) to show the total memory usage of all [raft entries caches](https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/peer_storage.rs#L513)
Split from https://github.com/tikv/tikv/issues/6717

## Difficulty

- Medium

## Score

- 300

## Mentor(s)

- @zhangjinpeng1987
- @BusyJay 

## Recommended Skills

- Rust

**Comment by zhangjinpeng1987** [comment]
@Rustin-Liu PTAL

**Comment by Rustin-Liu** [comment]
@you06  Could you please take a look?

**Comment by you06** [comment]
@Rustin-Liu try again please.
