### ISSUE TITLE
UCP: Automatically dismiss "Import mode"

### ISSUE THREAD

**Issue by kennytm** [tikv/tikv#7223]
## Description

When using TiDB Lightning or BR to ingest data into a TiKV cluster, these tools will place every TiKV node into an "[import mode](https://github.com/tikv/tikv/blob/master/components/sst_importer/src/import_mode.rs)" to speed up writing (while sacrificing storage space). 

Normally, when these tools have completed operation, they will instruct TiKV to move back to "normal mode". However, when Lightning or BR crashed, the TiKV nodes will be stuck in "import mode" forever until we manually switch back (which not many people will remember to do so).

To implement this enhancement, you should

* Set up a timer. When time's up, change the TiKV back into normal mode. Reset the timer when the `sst_importer` client actively request staying in import mode.
    * Lightning already sends a "switch to import mode" continuously every 5 minutes. You don't need to care about fixing Lightning/BR in this issue.
* Add a configuration for the timer's duration.
* Include a test case showing that a TiKV does indeed move back to "normal mode" after a certain time period.

## Score

* 605

## Mentor(s)

* @kennytm

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

**Comment by TennyZhuang** [comment]
> Reset the timer when the sst_importer client actively request staying in normal mode. 

I guess here should be import mode

**Comment by kennytm** [comment]
Fixed the typo, thanks.
