### ISSUE TITLE
Unknown time zone 'posixrules'

### ISSUE THREAD

**Issue by YangKeao** [tikv/tikv#7243]
## Bug Report

Cannot start tidb because of timezone error: unknown timezone 'posixrules'.

### Steps to reproduce

Start tidb and tikv on a machine with America/New_York timezone.

This was caused by realpath of `America/New_York` will lead to `/usr/share/zoneinfo/posixrules`. But the `chrono_tz` doesn't understand `posixrules` in its implementation of [`from_str`](https://docs.rs/chrono-tz/0.5.1/src/chrono_tz/home/cratesfyi/cratesfyi/debug/build/chrono-tz-81e187c3996d21f6/out/timezones.rs.html#605-1202)

Related logic in TiKV is at `/components/tidb_query/src/codec/mysql/time/tz.rs`

```
    /// Constructs a time zone from the name. If the specified time zone name is `system`,
    /// a local time zone will be constructed.
    pub fn from_tz_name(name: &str) -> Option<Self> {
        if name.to_lowercase() == "system" {
            Some(Tz::local())
        } else {
            chrono_tz::Tz::from_str(name).ok().map(Tz::Name)
        }
    }
```

**Comment by BusyJay** [comment]
This doesn't seem to be a bug of TiKV. TiKV just translates what is passed by TiDB.

**Comment by gregwebs** [comment]
@YangKeao what version are you using. This may be fixed in a recent version of TiDB as per: https://github.com/pingcap/tidb/pull/20560/files

**Comment by gregwebs** [comment]
There is definitely an error here in TiKV though. `ok()` should almost never be used, and this is no exception. This method should return a `Result`.

A worse problem is that TiDB seems to write the timezone of the system to TiKV and then does not encounter this error until it is read out from TiKV later: TiDB is then in an unrecoverable crashing state.

I encountered this when I had an /etc/localtime read out by TiDB as prefixed with 'SystemV/`

**Comment by BusyJay** [comment]
TiKV will treat `None` as an error in 

https://github.com/tikv/tikv/blob/2a2fa03da53b63f3fc24d7ea53aead40176979b5/components/tidb_query_datatype/src/expr/ctx.rs#L133

. `ok()` can be used if the actual error is straightforward or doesn't matter.

**Comment by BusyJay** [comment]
Close as it seems to be fixed on TiDB side as @gregwebs said.
