### ISSUE TITLE
`make docker` doesn't work on MacOS

### ISSUE THREAD

**Issue by oraluben** [tikv/tikv#7257]
## Bug Report
I was trying to build a docker image for tikv on my mac, and it shows some error message as below.
I briefly searched among the issues and didn't find some existing issues, so I'm not sure if this is intended or not.

### What version of TiKV are you using?
not relevant

### What operating system and CPU are you using?
MacOS

### Steps to reproduce
run `make docker`

### What did you expect?
command succeeds without error

### What did happened?
```
$ make docker
bash ./scripts/gen-dockerfile.sh | docker build -t pingcap/tikv -f - .
sed: illegal option -- r
...
```

**Comment by tedgkassen** [comment]
I had this issue the other day.  Whichever version of `sed` ships with MacOS is not the version anticipated by this script. Try installing gnu-sed via:
`brew install gnu-sed` 
and make sure that `/usr/local/opt/gnu-sed/libexec/gnubin` appears before wherever the default `sed` i s in your path

**Comment by andylokandy** [comment]
Thank you @bunker-inspector !
