### ISSUE TITLE
Max Key & Value Size?

### ISSUE THREAD

**Issue by ClickSimply** [tikv/tikv#7272]
## Question

First, the slack and discourse links in the issue template are no longer working. 👍 

I'm not able to find any data on max key/value size in TiKV.  I looked over all the documentation on the website and found this issue: https://github.com/tikv/tikv/issues/2438 which seems to indicate the max key size is 4KB with a disagreement on max value size.

Is the maximum size for the keys/values documented anywhere?  I'd like to know for a project I'd like to use TiKV for.

**Comment by fredchenbj** [comment]
for the maximum size for key is 4KB and defined in `const DEFAULT_MAX_KEY_SIZE: usize = 4 * 1024;` and the maximum size for value is 8MB and defined in `raft_entry_max_size: ReadableSize::mb(8),`.

**Comment by ClickSimply** [comment]
Thank you!
