### ISSUE TITLE
raftstore::test_conf_change::test_conf_change_fast failed

### ISSUE THREAD

**Issue by mahjonp** [tikv/tikv#7396]
raftstore::test_conf_change::test_conf_change_fast

Latest failed builds:
https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/20152/consoleFull

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
