### ISSUE TITLE
After a user starts TiKV, other users will not be able to start TiKV

### ISSUE THREAD

**Issue by HunDunDM** [tikv/tikv#7462]
### What version of TiKV are you using?

TiKV
Release Version:   4.1.0-alpha
Git Commit Hash:   f2e7a835f61734409c5174a208164348b7326d6d
Git Commit Branch: master
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           release

### What operating system and CPU are you using?

Unable to start

### Steps to reproduce

* User `foo` starts tikv at <ADDRESS 1>
* User `bar` starts tikv at <ADDRESS 2>

### What did you expect?

All started successfully.

### What did happened?

User `bar` cannot start tikv.

**Reason**: Running tikv will create a new lock under `/tmp/TIKV_LOCK_FILES/` to prevent starting multiple tikv at the same address. However, the folder permissions are owned by user `foo` at this time, and `bar` has no permissions.

```
# ll -a TIKV_LOCK_FILES
drwxr-xr-x     2 foo  foo     4096 Apr 14 19:03 .
drwxrwxrwt. 6927 root root 1298432 Apr 15 08:02 ..
-rw-r--r--     1 foo  foo        0 Apr 14 19:03 0.0.0.0_38820
```

**Comment by hunterlxt** [comment]
Master has fixed
