### ISSUE TITLE
Rollback records of non-existent secondary keys needn't be protected.

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#7490]
### What version of TiKV are you using?

v3.0, v3.1, v4.0

### What did you expect?
Only `cleanup` or `check_txn_status` need to write the protected rollback record.

### What did happened?
`rollback` calls `cleanup` and it writes protected rollback record for all non-exsitent keys which may causes performance regression in heavy contention workload with optimistic transaction. See https://github.com/tikv/tikv/issues/7435

**Comment by sticnarf** [comment]
Latest TiDB should use pessimistic transactions by default. Why there is also a significant regression?

**Comment by youjiali1995** [comment]
I remember transactions in ycsb are all implicit. I suspect it causes performance regression but I don't have evidence..

**Comment by youjiali1995** [comment]
We can file a PR and bench it to see whether it is the root case. @mahjonp can help with it if we have a binary with the patch.

**Comment by mahjonp** [comment]
It's effective.

```
Version:
tidb: 6a45a7d6eee51cc67e42f510b203eeb256da634d(master) 2020-04-08 09:51:47
tikv: 9d864e9d4da2ff73361df6439061a71b5ae3ecb9(HEAD) 2020-04-16 10:44:50
pd: c84d31bb4639448c6f8a3032b335b2171f9c99e2(master) 2020-04-10 04:59:20

Compare:
tidb: https://github.com/pingcap/tidb/compare/6a45a7d...6a45a7d
tikv: https://github.com/tikv/tikv/compare/cc67b7f...9d864e9
pd: https://github.com/pingcap/pd/compare/c84d31b...c84d31b

type: mysql

workload: <workloada>

read: *QPS: 2732.40 ± 0.0000% (std=0.00) delta: 51.73%
update: *QPS: 2630.40 ± 0.0000% (std=0.00) delta: 51.51%
```
