### ISSUE TITLE
Undefined behavior in tidb_query_datatype's RowSlice

### ISSUE THREAD

**Issue by brson** [tikv/tikv#7613]
## Bug Report

`RowSlice` does an unsafe pointer cast that is often unaligned. This is undefined behavior, which could potentially lead to miscompilation.

Here is the source: https://github.com/tikv/tikv/blob/7565efc9af7be6ef0f1adb6b51152c2c455a0f9c/components/tidb_query_datatype/src/codec/row/v2/row_slice.rs#L149

The fix isn't simple, so I'm just filing a bug cc @breeswish.

Potential fixes are to accumulate the casted items into a new buffer instead of slicing the original buffer, but that costs an allocation. Another fix would be to change the serialization such that the cast always ends up aligned, while adding an assertion here that the alignment is correct.

Tested against commit adf3a9408c4ec20cb8b19676d79c9087c3e72b40

Found with miri (cc @oli-obk 👍 ).

**Comment by breeswish** [comment]
Maybe we can drop the usage of slice at all. The slice is constructed to reuse the binary search method from std. We can write our own binary search using explicitly unaligned memory access.

**Comment by breeswish** [comment]
@zhongzc PTAL

**Comment by zhongzc** [comment]
> Maybe we can drop the usage of slice at all. The slice is constructed to reuse the binary search method from std. We can write our own binary search using explicitly unaligned memory access.

Writing our own binary search has to deal with the endian at every comparison. Or any other good idea?
