### ISSUE TITLE
UCP: use key only support of Titan for rawkv scan

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#7614]
## Description

Add key only option for rawKV scan API. It can reduce the message size sending on network and leverage key only feature if Titan enabled. 
- You should set `opts.set_titan_key_only(true)` for raw scan (you can refer to reference https://github.com/tikv/tikv/pull/4966)
- And add an option for client-go https://github.com/tikv/client-go/issues/45
## Difficulty

- Easy

## Score

- 300

## Mentor(s)

- @Connor1996 

## Recommended Skills

- Rust

**Comment by TommyCpp** [comment]
Hi @Connor1996 Not sure if I get this correctly but I see the raw Kv API already included a `key_only` options. So the only change I made is to enable the Titan's `key_only` options if `key_only` in raw Kv API is `true`. Please let me know if that looks reasonable.

Also not sure how to properly test it, may need to integrate with client(like go_client)? It would be nice if you have any advice. Thanks in advance.

**Comment by Connor1996** [comment]
You are right, it seems too easy. Let's add an option to client-go and test it.
https://github.com/tikv/client-go/issues/45

**Comment by yiwu-arbug** [comment]
reopening to wait for go-client side of change.

**Comment by Connor1996** [comment]
All works finished

**Comment by yiwu-arbug** [comment]
@TommyCpp @Connor1996 can you link the client-go PR here? thanks.

**Comment by yiwu-arbug** [comment]
@TommyCpp @Connor1996 @you06 do we need to run any comment to properly claim the UCP being finished?

**Comment by you06** [comment]
This PR is not related with this task correctly, I've fixed the points. @yiwu-arbug no need to run command for this.

**Comment by you06** [comment]
BTW, @TommyCpp, you have awarded a badge for usability challenge program! Please fill the form to get your reward! http://tidbcommunity.mikecrm.com/QMCv4QL

**Comment by TommyCpp** [comment]
> BTW, @TommyCpp, you have awarded a badge for usability challenge program! Please fill the form to get your reward! http://tidbcommunity.mikecrm.com/QMCv4QL

That's awesome, thanks a lot!
