### ISSUE TITLE
Support change `rate_bytes_per_sec` dynamically

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#7615]
Changing `rate_bytes_per_sec` dynamically will help us solve the problem without restarting when rocksdb background compaction affects the latency of the foreground writes.

Not sure, how hard is it. Will take an investigation later and mark it as a UCP issue.

**Comment by Connor1996** [comment]
Also, we can enable it by default and set with `auto_tuned=true`, there is a related issue https://github.com/tikv/tikv/issues/6484

**Comment by yiwu-arbug** [comment]
wait for dynamic config change stable then use it?

**Comment by Connor1996** [comment]
@yiwu-arbug No matter how to use it, by tikv-ctl or whatever. We just need to make it can be changed dynamically first. It's frequently adjusted for latency jitter issues.

**Comment by yiwu-arbug** [comment]
It is changeable on rocks side, but not via `SetOptions`: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/rate_limiter.h#L38

**Comment by yiwu-arbug** [comment]
Another thing to note is currently `rate_bytes_per_sec` is not set on raftdb, make it less useful. I think we need to have kvdb and raftdb share one rate limiter, but maybe we need to customize the rate limiter to allow raftdb have higher priority to get quota.

**Comment by Connor1996** [comment]
As I understand, raftdb's compaction flow won't that high? So it's unnecessary to set for raftdb.

**Comment by yiwu-arbug** [comment]
> As I understand, raftdb is small enough and its compaction flow won't that high? So it's unnecessary to set for raftdb.

yeah, yeah, but then the behavior is not so clear when `rate-bytes-per-secs` is not controlling the overall IO. I'm wondering if raftdb can also bring some IO spikes, but I don't have any test result.

**Comment by Connor1996** [comment]
Closed by https://github.com/tikv/tikv/pull/8124
