### ISSUE TITLE
UCP: support dumping region meta by http

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#7626]
## Description

We already support dumping region info by tikv-ctl, but
1. it's not easy to use comparing to REST API
2. it lacks raft memory information.

When we support label based replication, the information can become more critical for problem diagnosis.

The output better in JSON format, should include everything in raft status, raft local state, apply state and region local state.

## Difficulty

- Easy

## Score

- 300

## Mentor(s)

- @busyjay

## Recommended Skills

- Rust

**Comment by FateTHarlaown** [comment]
Hi, I'm interested in this issue，but i 'm not familiar with the http service of tikv, can I have some guide or material about this?

**Comment by BusyJay** [comment]
http service is defined in status_server.rs, entry point is https://github.com/tikv/tikv/blob/master/src/server/status_server.rs#L402.
