### ISSUE TITLE
Consider only permit Merging state when applying CommitMerge

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#7651]
When executing CommitMerge, we will check the peer state of the source peer.  It permits not only `Merging` but also `Normal`. https://github.com/tikv/tikv/blob/66feb3862ceb1c7eb3a29c13644ffce51a112be1/components/raftstore/src/store/fsm/apply.rs#L1998

I believe, permitting `Normal` state is because it checks the state before catches up the logs for source peer at the very first version of merge mechanism.
https://github.com/tikv/tikv/blob/2f64951ae991e2c5fb30fbc511135f53acbcede3/src/raftstore/store/worker/apply.rs#L1441

So it'd better to only permit `Merging` state to avoid unexpected conditions.

**Comment by gengliqi** [comment]
That's right! The source peer state must be `Merging` in current implementation. 
Nice catch! @Connor1996

**Comment by BusyJay** [comment]
Indeed.
