### ISSUE TITLE
Always enable pessimistic transaction

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#7652]
TiKV has a switch to turn off the support for pessimistic transaction because it's an experimental feature in v3.x:
https://github.com/tikv/tikv/blob/66feb3862ceb1c7eb3a29c13644ffce51a112be1/src/server/lock_manager/config.rs#L16

And there are lots of annoying codes for it. For example, 
https://github.com/tikv/tikv/blob/66feb3862ceb1c7eb3a29c13644ffce51a112be1/cmd/src/server.rs#L430
and 
https://github.com/tikv/tikv/blob/66feb3862ceb1c7eb3a29c13644ffce51a112be1/src/storage/txn/process.rs#L489

Now it's the time to remove them all, but we should keep the configuration for the backward compatibility.

**Comment by tangwz** [comment]
let me fix it.

**Comment by abbccdda** [comment]
Hey @tangwz  if you haven't started working on this ticket, do you mind me picking it up?

@youjiali1995 Just for a bit more context, we are going to turn on `pessimistic transaction` in all cases? So we should try to remove all the passed-down boolean flags such as `is_pessimistic_txn` in our codebase, correct?

**Comment by youjiali1995** [comment]
@abbccdda Sorry for the late reply. We are going to support pessimistic transactions in all cases which means removes the configuration to disable pessimistic transactions, and it's users' choice to choose whether it uses optimistic transactions or pessimistic transactions. So TiKV still needs to judge whether the transaction is optimistic or pessimistic.

**Comment by abbccdda** [comment]
@youjiali1995 I see, so the lock_mgr should get rid of the `optional` type and always be initialized, while we still need to check transaction time on runtime.

**Comment by youjiali1995** [comment]
Yes.
