### ISSUE TITLE
The TiKV and PD storage size is not equal

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7721]
## Bug Report

<img width="601" alt="屏幕快照 2020-04-30 下午7 45 33" src="https://user-images.githubusercontent.com/23521459/80706657-3bb02980-8b1b-11ea-92ef-431b57b4572c.png">
<img width="600" alt="屏幕快照 2020-04-30 下午7 45 54" src="https://user-images.githubusercontent.com/23521459/80706664-3d79ed00-8b1b-11ea-8bf5-11ca6fda2734.png">

### What version of TiKV are you using?

master

### What did you expect?
They should be the same

**Comment by Connor1996** [comment]
can't be reproduced, maybe there is something wrong with this cluster that accumulates snapshots?

**Comment by zhouqiang-cl** [comment]
> can't be reproduced, maybe there is something wrong with this cluster that accumulates snapshots?

Let me reproduce it and then ping you

**Comment by zhouqiang-cl** [comment]
> can't be reproduced, maybe there is something wrong with this cluster that accumulates snapshots?

Sorry. I did not reproduce it too, can we just leave a metric(it confuse me when having two metric?

**Comment by Connor1996** [comment]
> > can't be reproduced, maybe there is something wrong with this cluster that accumulates snapshots?
> 
> Sorry. I did not reproduce it too, can we just leave a metric(it confuse me when having two metric?

Most of the time, there are the same. But we can't leave only a metrics, because the difference between the two can reflect if there is any snapshot accumulation.
