### ISSUE TITLE
Full chunk-based computing in coprocessor

### ISSUE THREAD

**Issue by TennyZhuang** [tikv/tikv#7724]
Using [TiDB Chunk format](https://github.com/pingcap/tidb/blob/9627132db25e5cb560ba6ed89c2e39c32edb267a/util/chunk/chunk.go) in the `coprocessor` framework instead of `VectorValue`.

Detail Design (Draft): https://github.com/tikv/rfcs/pull/43/

## Development Task

- [x] Implement type safe chunk format.
- [x] Modify `rpn_fn` macro.
- [x] Modify all builtin functions using new signature.

## Mentor

* @TennyZhuang 
* @breeswish 

Please contact with mentors before start working on the task.

**Comment by ranjithkumar007** [comment]
I am interested in this project. 
Are there any pre-requisite tasks to be completed to participate in this community bridge project?

**Comment by TennyZhuang** [comment]
Sorry for late reply. the issue is currently a draft without detailed design, but feel free to apply for the project.

Currently there are no pre-requisite tasks because we are still working on the RFC (link can be found in the issue description).

**Comment by championshuttler** [comment]
Hey @TennyZhuang ! I am willing to get mentored for this issue for the Community Bridge program. Can you please help me in getting started with it?

Thanks

**Comment by breeswish** [comment]
Still have some remaining tasks, re-open.

**Comment by choleraehyq** [comment]
Do we have any benchmark result about this?

**Comment by skyzh** [comment]
@choleraehyq Yep but I forgot where I put it. We have micro-benchmarks and we saw 10x performance improvements on varcher processing. However, there are not that much improvements in fixed-size types probably due to the compiler is not using vectorization instruction sets for these operations, also branching for `Option`.

**Comment by choleraehyq** [comment]
> @choleraehyq Yep but I forgot where I put it. We have micro-benchmarks and we saw 10x performance improvements on varcher processing. However, there are not that much improvements in fixed-size types probably due to the compiler is not using vectorization instruction sets for these operations, also branching for `Option`.

But TiKV store values in row format, and converting from row format to chunk structure has cost. I'm curious that if this optimization does have positive impact for all workloads?
