### ISSUE TITLE
TiKV should recover in 30s after tikv reboot

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7726]
## Bug Report
When a tikv reboot. the tikv will recover in 1min ~ 1min 30 seconds

### What version of TiKV are you using?

master

### What operating system and CPU are you using?

Linux/x86_64

### Steps to reproduce

when running tpcc. then reboot a tikv server. It will take about 1m ~ 1m30s to recover 

### What did happened?
<img width="606" alt="屏幕快照 2020-05-06 下午7 09 19" src="https://user-images.githubusercontent.com/23521459/81171226-9d1a4180-8fce-11ea-872c-697883421e16.png">
<img width="599" alt="屏幕快照 2020-05-06 下午7 09 28" src="https://user-images.githubusercontent.com/23521459/81171232-9ee40500-8fce-11ea-90a8-a9de15e80f2b.png">

**Comment by siddontang** [comment]
can you provide more detailed information?

**Comment by zhangjinpeng1987** [comment]
Any update @gengliqi ?

**Comment by Little-Wallace** [comment]
This PR [tidb#17541](https://github.com/pingcap/tidb/pull/17541) has solved part of this problem. It could make tidb find the leader of region in TiKV has changed earlier and retry again. 

But we still need to speed up the election of raft algorithm, which may cost a long time to decide one leader when a TiKV instance crash. It is not a bug of TiKV, but we need to optimize it.
