### ISSUE TITLE
TiKV OOM

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7741]
## Bug Report

When using https://github.com/pingcap/go-tpc to prepare data. TiKV can be OOM

### What version of TiKV are you using?

```
["Release Version:   4.1.0-alpha"]
["Git Commit Hash:   a10af42339893a390a54f3d98f39fd9180dffee5"]
["Git Commit Branch: apply-metrics"]
["UTC Build Time:    2020-04-30 05:06:42"]
["Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)"]
```

### What operating system and CPU are you using?

Linux x86_64
### Steps to reproduce

```
./bin/go-tpc -T 80 -H 172.16.4.98 -P 4000 -D tpcc30k tpcc --warehouses 30000 --parts 4 prepare
```
after about 8 hour. TiKV will OOM

### What did you expect?
TiKV should not OOM

### What did happened?
TiKV OOM
<img width="597" alt="屏幕快照 2020-05-06 下午5 50 08" src="https://user-images.githubusercontent.com/23521459/81163969-20816600-8fc2-11ea-882c-e1fdeb46d80c.png">

**Comment by 5kbpers** [comment]
The `Apply wait duration` metric is much high, so I guess it was caused by the messages sent to apply fsm is blocked in the channel.
After tuning the intervals of apply yield and fsm reschedule of batch system, this issue seems to be alleviated.

**Comment by 5kbpers** [comment]
#7837 enables TiKV to tune the intervals of apply yield and fsm reschedule of batch system.
