### ISSUE TITLE
QPS continue reduce when running TPCC

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7745]
## Bug Report

QPS continue to reduce when running TPCC
<img width="296" alt="屏幕快照 2020-05-06 下午7 43 37" src="https://user-images.githubusercontent.com/23521459/81173065-06e81a80-8fd2-11ea-9c20-e20e7352af83.png">

### What version of TiKV are you using?

master

### What operating system and CPU are you using?

Linux/x86_64

### Steps to reproduce

Running TPCC.
Wait for about a few hours. Then the QPS drops much

### What did you expect?
The QPS should still be high

### What did happened?
QPS drops about 5k in 2 hours

**Comment by zhangjinpeng1987** [comment]
@hicqu How about the test result for gc with compaction filter?

**Comment by zhouqiang-cl** [comment]
The result of GC compaction filter is much better
![企业微信截图_684bb01c-053e-40ea-9fa0-76e33a9ea531](https://user-images.githubusercontent.com/23521459/82106640-e009b100-9754-11ea-8507-171dd36e4289.png)

**Comment by zhouqiang-cl** [comment]
1. prepare go-tpc data in `compaction` branch, and run go-tpc, it is OK
2. After the binary from  compaction upgrade to master, then run go-tpc, there are some inconsistent
```
[CUR] PAYMENT - Takes(s): 10.0, Count: 2117, TPM: 12717.5, Sum(ms): 28354, Avg(ms): 13, 95th(ms): 24, 99th(ms): 32, 99.9th(ms): 32
[CUR] STOCK_LEVEL - Takes(s): 9.9, Count: 203, TPM: 1224.4, Sum(ms): 2913, Avg(ms): 14, 95th(ms): 20, 99th(ms): 24, 99.9th(ms): 24
execute run failed, err exec DELETE FROM new_order WHERE (no_w_id, no_d_id, no_o_id) IN (
	(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?)
) failed Error 8021: inconsistent extra index PRIMARY, handle 30082058 not found in table
execute run failed, err exec DELETE FROM new_order WHERE (no_w_id, no_d_id, no_o_id) IN (
	(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?),(?,?,?)
) failed Error 8021: inconsistent extra index PRIMARY, handle 30082058 not found in table
Finished
```
