### ISSUE TITLE
Using RocksDB range deletion to truncate a continuously huge range of data

### ISSUE THREAD

**Issue by zhangjinpeng87** [tikv/tikv#7803]
### Is your feature request related to a problem? Please describe:

Currently, we use RocksDB DeleteFilesInRange to truncate a continuously huge range of data, and delete those keys not deleted by DeleteFilesInRange. If there are many left keys, the delete operation will hurt the online QPS. 

### Describe the feature you'd like:

A candidate solution to this issue is using range deletion to cleanup these left keys. 
- Call DeleteFilesInRange to delete those SST files covered by this range. This step is necessary because it can reclaim most of the disk space ASAP, and will extremely reduce the amount of the following compaction job.
- Call DeleteRange to mark this range is deleted.
- Call CompactRange to trigger manual compaction for this range. This step will reclaim the left disk space ASAP, also will make there are not too many range deletion marks, because too many range deletion marks will hurt read performance.

### Describe alternatives you've considered:

@Little-Wallace is working on a workaround that collects these keys into an SST file, and then using IngestExternal SST to insert these delete keys. It relief this issue, but still needs to write these keys into RocksDB(although using ingest SST).

**Comment by siddontang** [comment]
Can we call `DeleteRange` directly instead of calling `DeleteRangeInFiles` + `DeleteRange` together?

**Comment by siddontang** [comment]
another risk is the stability of DeleteRange, we have met some problems before.

can we use this feature in production now? @ajkr

**Comment by ajkr** [comment]
I am biased but I think it is usable in production. We have a few FB users (open source ones include Rocksandra, EdenFS, osquery; there are at least two internal users as well). One of the internal users has good correctness verification abilities - not sure about the rest. Also cockroach uses it heavily in the most recent few releases and has good correctness verification. We also run it in CI correctness/crash tests that combine it with various options and verify correct result.

Still I expect to find feature interaction bugs when a user tries a new combination of DeleteRange+other options/features. I'm not really sure what to do about it besides ask users to test their specific use case a lot and in the meantime strengthen our correctness tests for random feature interactions.

**Comment by yeyypp** [comment]
Hi guys
Does tikv use the DeleteRange with DeleteFileInRange and CompactRange now?
And where should I look into if I want to learn more about how tikv deletion work?
Thanks!
