### ISSUE TITLE
Encounter region unavailable when selecting data

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#7853]
### What version of TiKV are you using?
Commit Hash: 2be16853e00681f858e3902328ee44a7037ed8c1

### What operating system and CPU are you using?
Linux/x86_64

### Steps to reproduce
run [follower read workflow](https://github.com/pingcap/tipocket/blob/master/argo/workflow/follower-read.yaml) up to 24h

### What did you expect?
The case doesn't fail until the time slice is exhausted.
### What did happened?
case failed and [here](https://github.com/pingcap/tipocket/blob/master/tests/follower/follower.go#L300) log: `region unavailable`

NOTE: I cannot get more log about tikv or tidb because tipocket does not support this behavior.

**Comment by zhangjinpeng1987** [comment]
What is 4.67 cluster? Can you provide the deployed topology?

**Comment by hunterlxt** [comment]
The test scenario is that while split table, `insert` and `select count(*)` are performed simultaneously from different clients.

**Comment by hunterlxt** [comment]
## Reason Investigation
The `region unavailable` is the error message printed by the client. The log of tidb shows that the backoffer exceed 40s, along with some specific error messages. The error message prints out the last three messages, all of which are region epoch not match.

Select a region and track its error message in tikv and find that its epoch has changed after on split, but tidb still uses the old epoch to request tikv. The corresponding warn information was also reported in tikv, that is, epoch not match.

After the failure caused by region miss, tidb will update the region cache information from PD. According to the log time, the PD has received the updated epoch information of the tikv leader before the timeout error is reported in tidb.

After analyzing the tidb code, the problem is in the backoffer mechanism. The backoffer of the `boRegionMiss` has a backoff mechanism with a starting time of 2ms and a maximum of 500ms. After log verification, a SQL command will share the same backoffer, that is, if multiple regions return `epoch not match` error, then the backoffer will quickly rise to 500ms. It is easy to exceed the preset time limit of 40s, causing SQL errors on the client.

**Comment by hunterlxt** [comment]
## Solution Validation
Modified the tidb code to change the backoffer in coptask to generate a independent backoffer for each task. After tests, I did not encounter the region unavailable error.

But this almost caused the backoffer to fail, because each time an error is encountered, a new task will be generated, so a new backoffer will be used. However, I want to associate a backoffer with a specific region.

My job now is to study a good way to modify the backoffer in coptask code to bind the region information to one backoffer. For example, create a HashMap.
