### ISSUE TITLE
Got oneshot canceled error when selecting data

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#7854]
### What version of TiKV are you using?
Commit Hash: 2be16853e00681f858e3902328ee44a7037ed8c1

### What operating system and CPU are you using?
Linux/4.67 environment

### Steps to reproduce
run [follower read workflow](https://github.com/pingcap/tipocket/blob/master/argo/workflow/follower-read.yaml) up to 24h in 4.67 cluster

### What did you expect?
The case doesn't fail until the time slice is exhausted.
### What did happened?
case failed and tipocket log shows: 
```
2020/05/14 22:12:16 follower.go:300: [fatal] Error 1105: other error: unknown error "[src/coprocessor/endpoint.rs:314]: oneshot canceled" 
```

NOTE: I cannot get more log about tikv or tidb because tipocket does not support this behavior.

**Comment by sticnarf** [comment]
This happens when the callback of getting snapshot is not called. However, there is not enough information to determine why the callback is not called.

**Comment by youjiali1995** [comment]
I guess it's only related to replica read, so it's not very critical.

**Comment by youjiali1995** [comment]
It has been fixed. #7921 is a workaround.
