### ISSUE TITLE
Channel disconnected error is not handled correctly

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#7855]
## Bug Report

https://github.com/tikv/tikv/blob/00fe91fcf8bde4233d15b754f6fca7c4f17b7579/components/raftstore/src/store/fsm/store.rs#L1783-L1790

Either region is removed or TiKV is shutting down can cause `Disconnected` error, treating all as if removal can lead to snapshot corruption.

We may also need to examine other `Disconnected` cases in the codebase too.

**Comment by hicqu** [comment]
Closed by https://github.com/tikv/tikv/pull/7877.
