### ISSUE TITLE
Questions: rustfmt provides incorrect format

### ISSUE THREAD

**Issue by Yiyiyimu** [tikv/tikv#7859]
Hi all!
I'm trying to work on #7833 . But when I try to use rustfmt, the resulted format is not as expected.
The input format and other functions' format is:
```
pub fn rpad_utf8(arg: &Option<Bytes>, len: &Option<Int>, pad: &Option<Bytes>) -> Result<Option<Bytes>> {
```
But the formatted version would become multiline indentation:
```
pub fn rpad_utf8(
    arg: &Option<Bytes>,
    len: &Option<Int>,
    pad: &Option<Bytes>,
) -> Result<Option<Bytes>> {
```
Since I'm not sure which config file rustfmt.toml I should look for, I uninstalled and re-installed rustfmt to make sure it stays the default settings, but the ouput is the same. Is there some point I'm missing?

**Comment by glorv** [comment]
This is because the line is too long (105 chars), so the rustfmt will format it to the vertical mode, I think this is ok. See [here](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#attr_fn_like_width) for more details.

**Comment by Yiyiyimu** [comment]
Thank you @glorv for your kind reply! I should've read configurations of rustfmt more carefully.
