### ISSUE TITLE
tokio-threadpool reads stale stack frames in status_service

### ISSUE THREAD

**Issue by brson** [tikv/tikv#7868]
## Bug Report

Address sanitizer reports invalid reads inside tokio-threadpool during status_service test cases. The code in question is pretty complex, and on a drop path, so I haven't been able to verify that it is definitely wrong, but there are unsafe thread locals involved, so it seems plausibly wrong.

tokio-threadpool is deprecated so it seems a solution is just to replace it completely, presumably with yatp cc @sticnarf 

### What version of TiKV are you using?

e5afd630e35b42e970e6184e8b71eb98263a9363

### What operating system and CPU are you using?

Linux

### Steps to reproduce

```
ASAN_OPTIONS=allow_addr2line=true RUSTFLAGS="-Zsanitizer=address" cargo -Zbuild-std test --target=x86_64-unknown-linux-gnu --lib -p tikv -- security_status_service_without_cn
```

### What did happened?

https://gist.github.com/brson/049fbb51e7cf6a7e373a652e4bffbaf2

**Comment by sticnarf** [comment]
The status server uses hyper. We cannot replace it with yatp because hyper requires a tokio runtime.

I'm not sure if upgrading it to hyper 0.13 with tokio 0.2 solves this problem.

**Comment by brson** [comment]
afaik hyper does not require tokio, but it does use tokio by default.
