### ISSUE TITLE
Question about RocksDB sst file key seq number

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#7884]
## Question

tikv-ctl ldb manifest_dump shows a sst have an unusual sequence number:
```bash
$ tikv-ctl ldb manifest_dump --db=./db --hex --verbose
...
  AddFile: 3 11810117 8799460 '7A7480000000000003FFDC5F728000000025FF1C6F490000000000FAFA37774395BBEEB7' seq:202343829848, type:0 .. '7A7480000000000003FFFA5F72800000009FFFCC8C940000000000FAFA3775B440D3FE4B' seq:0, type:1
  AddFile: 3 11810118 8713891 '7A7480000000000003FFFA5F72800000009FFFCC8C9C0000000000FAFA3775B440D3FE4B' seq:0, type:1 .. '7A7480000000000004FF065F728000000253FF40926D0000000000FAFA37E0E180C3E28F' seq:202253695508, type:0
  ColumnFamily: 0 # default cf
...
```

The manifest is produced from a TiKV v3.1.0, and there are 6 levels in total.
File 11810117 @ level 3, start key's seq is 202343829848 and end key's seq is 0.
File 11810118 @ level 3, start key's seq is 0 and end key's seq is 202253695508.

I wonder if this is normal or not?

**Comment by zhangjinpeng1987** [comment]
It is normal if one of the input sst file's global sequence number is 0, and another input sst file's global seq no is not 0.
