### ISSUE TITLE
TiKV Leader suddenly drop and there are many TiKV Server is Busy

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7890]
## Bug Report
When using go-tpc load data, The leader reblance. and there are many `TiKV Server is Busy`
![企业微信截图_1b4ceec4-6cb0-4be7-bc93-3bb7ec9d5816](https://user-images.githubusercontent.com/23521459/82527461-1ab28580-9b69-11ea-9019-dfff58af985c.png)
![企业微信截图_0f4f6fbf-79a6-4d51-9437-8621b00d589a](https://user-images.githubusercontent.com/23521459/82527468-1edea300-9b69-11ea-9eeb-cd24dccbb1d5.png)

### What version of TiKV are you using?

2fdb280
### What operating system and CPU are you using?

Linux/x86_64
### Steps to reproduce

```
mysql -u root -h 172.16.4.98 -P 4000 -e "DROP DATABASE tpcc40k"
mysql -u root -h 172.16.4.98 -P 4000 -e "CREATE DATABASE tpcc40k"
./bin/go-tpc -T 80 -H 172.16.4.98 -P 4000 -D tpcc40k tpcc --warehouses 40000 --parts 4 prepare
```

### What did you expect?
No leader rebalance

**Comment by zhangjinpeng1987** [comment]
From the "server is busy" you can obviously see that it is because "RocksDB write stall". It is normal in current version if the writing flow is heavy, we have a plan to eliminate "write stall" by controlling the writing flow in advance.
@zhouqiang-cl I think we can remove the bug label.

**Comment by Connor1996** [comment]
It's not a bug
