### ISSUE TITLE
Why tikv require "nodelalloc" for ext4?

### ISSUE THREAD

**Issue by cannium** [tikv/tikv#7892]
The [document](https://tikv.org/docs/3.0/tasks/deploy/ansible/) requires `nodelalloc` to be configured, but not explained. I'm curious why, someone gives me a pointer?

**Comment by zhouqiang-cl** [comment]
@ethercflow will answer it

**Comment by ethercflow** [comment]
Two reasons:
1. security  
 https://lwn.net/Articles/322823/;
2. performance
The default ext4 mount option is `delalloc` - delayed on-disk block allocation for writes. This can cause a bottleneck in the system under high write conditions resulting in slow io drain to disk;

**Comment by cannium** [comment]
I should say your answer causes more confusion than clarification. 
For the security part, the [bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/317781) referenced by the [article](https://lwn.net/Articles/322823/) is fixed ten years ago, and I believe rocksdb would call `fsync()` at proper time to ensure data security. 
For the performance part, as I understand, the option `delalloc` would cause ext4 to delay block allocation as possible to batch writes, this would improve performance, not the opposite. Also from the [article](https://lwn.net/Articles/322823/):
```
"Delayed allocation" means that the filesystem tries to delay the allocation of physical disk blocks for written data for as long as possible. This policy brings some important performance benefits.
```
So is this `nodelalloc` requirement decided by test or some deduction? I might need more materials.

**Comment by siddontang** [comment]
I remember that we used `delalloc` before but met data lost on VM or cloud instance crashed, so we decide to use `nodelalloc`.

**Comment by ethercflow** [comment]
For the security part, although it has been fixed, some users may still use an older kernel version.
For the performance part, you can get more detailed information from: https://access.redhat.com/solutions/472273.

**Comment by cannium** [comment]
Unfortunately I don't have access to a RedHat subscription but I understand your rationale. Thanks for your patience.

**Comment by ethercflow** [comment]
You're welcome, welcome to discuss  :)
