### ISSUE TITLE
QPS drops to zero when loading data

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7899]
## Bug Report
QPS drop to zero when loading data

### What version of TiKV are you using?

```
Release Version:   4.0.0-rc.2
Edition:           Community
Git Commit Hash:   2fdb2804bf8ffaab4b18c4996970e19906296497
```
### Steps to reproduce

```
./bin/go-tpc -T 80 -H 172.16.4.98 -P 4000 -D tpcc40k tpcc --warehouses 40000 --parts 4 prepare
```
run for about 10 hour, then there is a QPS drops
<img width="576" alt="屏幕快照 2020-05-22 下午2 36 16" src="https://user-images.githubusercontent.com/23521459/82638531-a72c7900-9c39-11ea-9295-335d17e71ab7.png">

### What did you expect?
No QPS drops to zero

**Comment by Little-Wallace** [comment]
It is not a bug. But there is no more message left.
