### ISSUE TITLE
Proposal: add --advertise-status-addr flag to specify the status address to advertise

### ISSUE THREAD

**Issue by cofyc** [tikv/tikv#7920]
### Is your feature request related to a problem? Please describe:

In #7658, the status address reported to PD is the address the `tikv-server` listens on. 

This makes `tikv-server` not possible to listen to the wildcard address ('0.0.0.0', '::' or '*').

related issues: #2511, #2539

### Describe the feature you'd like:

Like `--advertise-addr` flag, we can add `--advertise-status-addr` flag to specify the status address to advertise (fallback to `--status-addr` if not present).

### Teachability, Documentation, Adoption, Migration Strategy:

#7658

**Comment by cofyc** [comment]
cc @NingLin-P @overvenus @rleungx What do you think?

**Comment by cofyc** [comment]
cc @Yisaer @tennix

**Comment by tennix** [comment]
Yes,reusing `status-addr` as advertise address will confuse users.

**Comment by overvenus** [comment]
TiCDC has [the same problem](https://github.com/pingcap/ticdc/pull/546/files#diff-1427b112aa72f64adcf839007e954d56R36-R37) before, and it also adds `--advertise-status-addr`.

**Comment by overvenus** [comment]
PTAL @iamxy @siddontang , thanks!

**Comment by siddontang** [comment]
I think we should support this.

**Comment by Yisaer** [comment]
Would this feature be ported to 4.0 GA?

**Comment by siddontang** [comment]
@lonng 

TiUP may also need to consider this.

**Comment by lonng** [comment]
Please make me known if this feature is released, and we will take it into account TiUP.

**Comment by overvenus** [comment]
FYI, this request will be resolved in https://github.com/tikv/tikv/pull/7944.

**Comment by cofyc** [comment]
hi,  @NingLin-P @overvenus @rleungx 

 the status address to advertise can fallback to `--status-addr` to be compatible with `4.0.0`, but I think we should not fail when the address specified via `--status-addr` is a wildcard address (e.g. 0.0.0.0:<port>). Old TiKV setups which use `--status-addr 0.0.0.0:<port>` flag will fail to start after the upgrade.

Here is my suggestion:

- If `--advertise-status-addr` is specified, validates it's not a wildcard address as it will be reported to PD
- If `--advertise-status-addr` is no specified, to keep compatible with `4.0.0`, we can fallback to `--status-addr` but don't validate it's not a wildcard address as it's the address `tikv-server` listens on.
 
what do you think？
 
https://github.com/tikv/tikv/blob/e32993782e9d4522cb446c3a82229840894ae905/src/server/config.rs#L199-L213

**Comment by NingLin-P** [comment]
Thanks! @cofyc , https://github.com/tikv/tikv/pull/8016 will fix it.
