### ISSUE TITLE
It takes 10 mins to recover QPS

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7941]
### What version of TiKV are you using?

4.0.0-rc.2

### What operating system and CPU are you using?

Linux

### Steps to reproduce

1. run a go-tpc with 40k warehouse
2. kill a tikv-server in 20 mins.
![企业微信截图_9b9be7d0-e806-4149-8d11-4e8260630068](https://user-images.githubusercontent.com/23521459/82856401-75b8f380-9f40-11ea-9f28-d5139c533e57.png)

### What did you expect?
It recover in 2 mins

### What did happened?
It recover in 10 mins

**Comment by gengliqi** [comment]
It may be caused by tidb backoff at least 1(then 2, 4, 8, 10)ms when getting the `not leader` response.

**Comment by zhouqiang-cl** [comment]
@gengliqi 's commit improve much, but still have 3-4 minutes to recover
![企业微信截图_4828e831-c2bd-437f-ba0c-1afdb89a2c1e](https://user-images.githubusercontent.com/23521459/83125068-91bbc100-a109-11ea-8c4d-206289925988.png)
