### ISSUE TITLE
AskTUG: Coprocessor support `bson` and `protocobuffers`

### ISSUE THREAD

**Issue by AndreMouche** [tikv/tikv#7960]
## Feature Request

Could we support to push down functions for `bson` and `protocobuffers`?
With the above feature, tikv will be more friendly to users from No-SQL such as MongoDB. Then the No-SQL users can use tikv's computation source as `TiDB` did.

This is from [ask-tug](https://asktug.com/t/topic/34614/49?u=shirly-pingcap)

**Comment by zhangjinpeng1987** [comment]
Contributors are welcome to take this task.

**Comment by breeswish** [comment]
The actual demand is to support a custom logic. Let's track it in https://github.com/tikv/tikv/issues/8036
