### ISSUE TITLE
Release pipelined pessimistic lock

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#7980]
## Development Task
We have implemented the pipelined process, but we still have somethings to do:
- [ ] https://github.com/tikv/tikv/issues/8045
- [x] Test: what the abortion ratio under heavy conflict workload
- [x] Make region schedule not affect it
- [ ] Enable it by default

**Comment by youjiali1995** [comment]
If TiKV fails to write pessimistic locks because the region is transferring leader, splitting, or merging with another one, pessimistic transactions may fail due to write conflict. We need to avoid it as far as possible.

One solution is only when the pipelined lock requests are proposed to the raft group successfully, TiKV can respond to TiDB. We don't care about the failure during log replication, because if it happens, it means the cluster is unstable, some transaction will fail inevitably. 

However, peers don't reject proposals during splitting and merging, but all proposals are rejected to apply, so we can reject them. To avoid this change resulting in more backoff of TiDB, I think we can save these proposals in memory and notify TiDB when the split or merge is done.

BTW, please abstract the interface well. @gengliqi

**Comment by youjiali1995** [comment]
I think we can write a test program to calculate the abort ratio at first, and it can evaluate the value of the change.

**Comment by gengliqi** [comment]
got it. I will write a test first.

**Comment by youjiali1995** [comment]
Now it won't fail to acquire pessimistic locks unless there is a network partition or node crash. To keep the consistency to the old version, don't enable it by default in v4.0.
