### ISSUE TITLE
TiKV data size continue to drop when chaos is enable

### ISSUE THREAD

**Issue by zhouqiang-cl** [tikv/tikv#7984]
## Bug Report

When shutdown chaos is enabled. The size continues to drop
![企业微信截图_486c7620-9082-4a93-9774-c5f9a5301d31](https://user-images.githubusercontent.com/23521459/83381251-c46bff00-a412-11ea-9bf8-786e7df4337a.png)

### What version of TiKV are you using?

```
Release Version:   4.1.0-alpha
Edition:           Community
Git Commit Hash:   27b9bf8890f5d2f28ec28ad8fe0aef2dba11118d
Git Commit Branch: gc-with-compaction-filter
UTC Build Time:    2020-05-28 11:02:38
Rust Version:      rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```

### What operating system and CPU are you using?

Linux

### What did you expect?
Size not reduce

### What did happened?
Size reduce

**Comment by overvenus** [comment]
From metrics of TiKV, TiKV is actively GC outdated data during that time, this is may reclaim some space.

<details><summary>Metrics</summary>

![image](https://user-images.githubusercontent.com/2150711/83601517-560a7680-a5a3-11ea-81a3-3b18b866d41b.png)

![image](https://user-images.githubusercontent.com/2150711/83601510-51de5900-a5a3-11ea-9bdd-e02cde57ada5.png)

</details>
