### ISSUE TITLE
Avoid the impact of `Write::Lock` and `Write::Rollback` on read

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#7989]
## Description
If a key is `select-for-update`ed many times, the read performance degrades because TiKV writes a `Write::Lock` on the key and it needs to skip all `Write::Lock`s to find the useful write record: https://github.com/tikv/tikv/issues/7024, https://github.com/tikv/tikv/pull/5405#issuecomment-528290353

We can eliminate `Write::Lock`s and `Write::Rollback`s on secondary keys. Please be careful about protected rollback records. They must exist to guarantee correctness.

**Comment by sticnarf** [comment]
So how about the `Lock`s and `Rollback`s on primary keys?
For optimistic transactions, TiDB can just choose a non-`Lock` key as the primary key. But as for pessimistic transactions, we must use the first key to lock as the primary key, we cannot workaround this problem.

**Comment by youjiali1995** [comment]
> So how about the Locks and Rollbacks on primary keys?

Keep them.

> For optimistic transactions, TiDB can just choose a non-Lock key as the primary key. But as for pessimistic transactions, we must use the first key to lock as the primary key, we cannot workaround this problem.

One solution is transaction record like crdb which is never read unless resolves locks.

**Comment by youjiali1995** [comment]
`Write::Lock` may be necessary to guarantee the correctness: https://mp.weixin.qq.com/s?__biz=MzI1MzYzMjE0MQ==&mid=2247486255&idx=1&sn=ee933f326cfc755289b52d9bb41a129c&chksm=e9d0c0cddea749db184de9415471056acad11ca24888e71404b542a216526fe1ddbafc3f3f75&scene=0&xtrack=1#rd. We should be careful.

**Comment by youjiali1995** [comment]
Close it because it's not suitable for async-commit.
