### ISSUE TITLE
Suggest to use BoringSSL in TiKV

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#8021]
## Proposal
From #5022 and #5140, TiKV started to use LibreSSL and then OpenSSL as SSL library. Our original intention was to avoid the dependency of Go, and at the same time do not want to sacrifice security feature. But OpenSSL has been proven to be less secure. However, grpc-rs is about to upgrade the version of grpc core, and I found that grpc compiling is no longer dependent on Go.

So let's back to use default secure feature in grpc-rs. cc @siddontang @BusyJay @overvenus

**Comment by hunterlxt** [comment]
cc @hicqu

**Comment by yiwu-arbug** [comment]
Just curious, is there any reference for OpenSSL being less secure?

**Comment by BusyJay** [comment]
I think openssl is used for at least three reasons:

1. To solve https://github.com/tikv/tikv/issues/5389.
2. Coprocessor needs to use APIs from openssl to implement several hash related and crypto related functions.
3. Status server is implemented using hyper, which will depend on openssl. So only switching openssl in grpc doesn't make much sense.

**Comment by hunterlxt** [comment]
#5389 issue exists in OpenSSL not BoringSSL. The second one reason you said just adds some binary volume, it's not reason. The third one is not reason. @BusyJay

**Comment by BusyJay** [comment]
>  The second one reason you said just adds some binary volume, it's not reason.

I'm not sure what do you mean by "not reason", do you mean it's not a blocker? I'm afraid it is, more to see #3875.

> The third one is not reason.

Can you explain more why do you think it's OK to depend on both boringssl and openssl? Supposing boringssl was really more secure than openssl and it was possible to link to both libraries, it would not make tikv more secure as tls connections were still handled by openssl.

**Comment by hunterlxt** [comment]
> BTW, some time ago, when I tested the reload cert function, I found that openssl-vendored is more prone to coredump, and the probability is much greater than boringssl or directly use the openssl provided by the system.
What do you think of this

**Comment by BusyJay** [comment]
Reloading coredump is a bug of grpc itself, rather than these libraries.

**Comment by yiwu-arbug** [comment]
> I think openssl is used for at least three reasons:
> 
> 1. To solve #5389.
> 2. Coprocessor needs to use APIs from openssl to implement several hash related and crypto related functions.
> 3. Status server is implemented using hyper, which will depend on openssl. So only switching openssl in grpc doesn't make much sense.

encryption-at-rest is also using openssl.

**Comment by hunterlxt** [comment]
Given that since the last switch to openssl, many places have introduced the function of openssl, so the switch to boringssl cost is high. Closing the issue.
