### ISSUE TITLE
Big endian support

### ISSUE THREAD

**Issue by xieqiang2020** [tikv/tikv#8041]
### Is your feature request related to a problem? Please describe:

#8017 Build tidb_query_datatype failed on s390x platform (LinuxOne, RHEL) which is big endian. According to @breeswish 's comment, "currently both TiDB and TiKV only supports little endian."

### Describe the feature you'd like:

Add big endian support so that tidb_query_datatype can be built successfully on s390x platform.

### Describe alternatives you've considered:

N/A

### Teachability, Documentation, Adoption, Migration Strategy:

N/A

**Comment by zhangjinpeng1987** [comment]
In the recent 6 months, we do not have plans to support it, if you are interested in this feature, feel free to implement it. Contributions are welcome.
