### ISSUE TITLE
set concurrency automatically during backup with BR

### ISSUE THREAD

**Issue by DanielZhangQD** [tikv/tikv#8076]
### Is your feature request related to a problem? Please describe:

Currently, when users do backup with BR, they have to manually adjust the `concurrency` setting, however, TiKV is aware of the CPU resources it can use, so it would be better that TiKV can adjust the concurrency setting automatically according to its resources, e.g., 12 CPUs is set for TiKV Pod in Kubernetes cluster, then during backup, if users do not set concurrency explicitly, TiKV set it to 12.
### Describe the feature you'd like:

TiKV can adjust the concurrency setting automatically according to its resources during backup.

**Comment by djshow832** [comment]
Which concurrency do you refer to? Can you show me?

**Comment by DanielZhangQD** [comment]
> Which concurrency do you refer to? Can you show me?

@kennytm Could you please help update the required info?

**Comment by kennytm** [comment]
This.

https://github.com/tikv/tikv/blob/e112c313700de1fc93ce9f142123117fc0da4b27/components/backup/src/endpoint.rs#L116
