### ISSUE TITLE
raftdb log is printed into tikv log file

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#8117]
### What version of TiKV are you using?
master

### Steps to reproduce
Run tikv. Look at tikv log (e.g. deploy/log/tikv.log). Raftdb log are mixed with tikv log in the file.

After #7358 we switch to use tikv logger instead of rocksdb native logger to dump logs. By default rocksdb logs (kvdb and raftdb) should be in their respective directories (e.g. deploy/data/db and deploy/data/raft). On master, however, raftdb log is printed into tikv log. kvdb is fine though.

**Comment by breeswish** [comment]
Currently RocksDB logs cannot be searched in TiDB Dashboard. Do you think it's necessary to add support?

**Comment by yiwu-arbug** [comment]
@breeswish it will be great if we have that.
