### ISSUE TITLE
optimize stale epoch handling when splitting. 

### ISSUE THREAD

**Issue by siddontang** [tikv/tikv#816]
E.,g [a, c) -> [a, b) + [b, c)

We may meet following cases:
1. Keys in the request are all in [a, b), we can still execute this request no matter the epoch is stale. 
2. Keys are all in [b, c), ticlient now may retry, but later tikv may execute this too if the new region leader is in the same store. 
3. Keys cover [a, c), we can combine 1 and 2. 

/cc  @BusyJay @disksing

**Comment by Hoverbear** [comment]
I'm closing this stale issue, please re-open it if it's still a problem and you'd like to revisit it.
