### ISSUE TITLE
Consider deleting snapshot file in other thread.

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#8160]
![image](https://user-images.githubusercontent.com/13497871/86077527-b1eeef00-babe-11ea-8edf-77da79382bf3.png)
I observed a high casual message process duration in my own cluster which doing a lot of generating snapshots.

From reading the code, I suspect it is due to snap GC. Now, snap GC is triggered by `CasualMessage::GcSnap` and delete snapshot files in raftstore thread. It may cost some time which slows the speed of processing raft ready.

**Comment by AndreMouche** [comment]
unlabel type/enhancement,compont/raft

**Comment by hbisheng** [comment]
I think this issue has mostly been solved by https://github.com/tikv/tikv/pull/12415 which added a background thread for cleaning up snapshot files. But I found one remainig case of snapshot deletion within the raftstore thread and opened https://github.com/tikv/tikv/pull/17155 to fix it. We can let the PR close this issue.
