### ISSUE TITLE
Change max replicas may cause region unavailable

### ISSUE THREAD

**Issue by rleungx** [tikv/tikv#8169]
## Bug Report
Consider this case:
```
max-replicas = 5
dc1 has two zones: zone1, zone2
dc2 has two zones: zone3, zone4
dc3 has one zones: zone5
```

After dc2 is crushed, we want to improve the availability and change `max-replicas` from 5 to 3. But PD can't know it since it doesn't exceed the max downtime and may send remove peer command to dc1. This peer will be removed and the region becomes unavailable because we have 4 peers and 2 of them are down.

**Comment by BusyJay** [comment]
There is no way to guarantee complete availability during conf change.  I suggest to changing replicas only after changing state either automatically or manually. And PD should pick down node over health node.

**Comment by BusyJay** [comment]
Now we support joint consensus, perhaps PD can use joint consensus to remove two nodes at a time.

**Comment by HunDunDM** [comment]
> Now we support joint consensus, perhaps PD can use joint consensus to remove two nodes at a time.

I will try to improve the logic.

**Comment by HunDunDM** [comment]
I think this issue can be closed.

* If the PD knows which down-peers are, the PD will first delete the down-peers.
* If the PD does not know what the down-peers are, only TiKV can guarantee this. But according to @BusyJay , that can't be done.
* Even with joint consensus, the PD might try to remove both dc1 and dc3 peers, and still get an error.
* The only solution is to not set `max-replicas` directly but to remove dc2 via `Placement Rules`, which guarantees that peers of other dcs will not be removed.
