### ISSUE TITLE
Don't allow conf remove until leader has applied to current term

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#8184]
## Bug Report

We allow green gc to scan the store data directly without leader. @youjiali1995 suggested that it can miss data if an old leader is removed before new leader has applied all the logs from last term. To get around the problem, we can prevent proposing any conf change remove until leader is able to read.

/cc @gengliqi @NingLin-P

**Comment by youjiali1995** [comment]
I failed to write a test for this case because the new leader already reject conf change before applying all logs from the last term in raft-rs: https://github.com/tikv/raft-rs/blob/5ca2e467cd34a9b104bc9ee6074fb338cbf532e8/src/raft.rs#L1019-L1024.

**Comment by youjiali1995** [comment]
It's a problem in theory. I will add a test to prevent it from code change in the future.

**Comment by BusyJay** [comment]
Cool! Thanks for the investigation! @youjiali1995.

**Comment by NingLin-P** [comment]
> if an old leader is removed before new leader has applied all the logs from last term.

I think this may not happen, to remove the old leader we need to propose a conf change log at current term, and log entries from last term will be applied before this log.

**Comment by youjiali1995** [comment]
> > if an old leader is removed before new leader has applied all the logs from last term.
> 
> I think this may not happen, to remove the old leader we need to propose a conf change log at current term, and log entries from last term will be applied before this log.

No. The leader needn't apply the log. As long as the log is committed, the old leader can remove itself.

**Comment by BusyJay** [comment]
Why close this? I thought you would add a test.

**Comment by NingLin-P** [comment]
> No. The leader needn't apply the log. As long as the log is committed, the old leader can remove itself.

This may be true when joint consensus is in use, but currently, all committed logs need to be applied before taking effect.

**Comment by youjiali1995** [comment]
https://github.com/tikv/tikv/blob/f17378681dbd2e01fac5dd3a04a5b593270017b7/tests/failpoints/cases/test_gc_worker.rs#L81 covers this case.

**Comment by BusyJay** [comment]
The problem may not exist.

Because we don't allow a leader to remove itself, so the command must be proposed by leaders at previous terms. When a peer finds itself is removed, it will skip applying any further logs.

https://github.com/tikv/tikv/blob/35c66d38ff8180f3652643e35575590d9ab57fc1/components/raftstore/src/store/fsm/apply.rs#L829-L833

So it will not apply any proposals even they are committed and will not apply any reads as it can't apply to any logs at current term, whose index should be larger than the admin proposal.

We have also introduced transaction pipelines that may not wait for raftstore applying. But they take affect only when a peer has applied to current term, so they will not expose new changes as analyzed above.

It's still possible that new leader has applied some mutations from old leader, which is committed by new leader, before removing itself. But since read is denied, so the mutations are not observable by the client, which won't affect the correctness of two phase commit.

Async commit compatibility is another problem that beyond this issue.

/cc @youjiali1995 @NingLin-P @gengliqi PTAL

**Comment by NingLin-P** [comment]
> Because we don't allow a leader to remove itself, so the command must be proposed by leaders at previous terms

When `raftstore.allow_remove_leader` (default `false`) set to `true`, a leader can propose a `confchane` to remove itself.

**Comment by BusyJay** [comment]
Indeed, I will send a PR to remove the configuration.

**Comment by gengliqi** [comment]
I find green gc can miss data in another situation below.
1. a leader applies a raft log and responses to the client
2. TiKV of this leader crashes and restarts, the data may be stale than before because we don't set sync option for applying
3. green gc worker scans all of the peer of this region and misses the data written before

TiKV relies on the guarantee that a leader of region can be read after it has applied to the current term.
But green gc worker bypasses the raftstore layer which leads to this problem.

**Comment by BusyJay** [comment]
We will deprecate hibernate regions in the long term, and green gc will be disabled too. So we may not need to solve the problem at all.
