### ISSUE TITLE
encryption: Turn file dictionary into log style

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#8212]
### Is your feature request related to a problem? Please describe:
When encryption is turned on, TiKV keeps a file dictionary to keep track of metadata of each file (encryption method, key used, and IV). The metadata for each file is around 32 bytes. Currently when the storage layer create or delete a file, we need to rewrite the whole file dictionary file, which could be a problem. Consider a 1TB database and average 8M SST files in rocksdb. That's 128K files * 32 bytes = 4M file dictionary size, which is comparable to SST file size. This will at least increase IO and slow down compaction, which introduce performance problem. We should consider turning it into a log style file, where each time we need to update file dictionary, we only append the record to the end of the file.

### Describe the feature you'd like:
as above

### Describe alternatives you've considered:
We can inline encryption metadata in each data file (either as header or footer), the downside:
1. not compatible with current approach
2. it makes data file size differ from actual content size. It complicates logics that depend on file size.

**Comment by yiwu-arbug** [comment]
Please also add tipocket test for this change.

**Comment by hunterlxt** [comment]
> Please also add tipocket test for this change.

Ok, I'll collaborate with @mahjonp

**Comment by siddontang** [comment]
em, will be the size of the log file increased all the time? do we have a Snapshot mechanism to shrink the size?

**Comment by yiwu-arbug** [comment]
> em, will be the size of the log file increased all the time? do we have a Snapshot mechanism to shrink the size?

yes, there's the `security.encryption. file-dictionary-rewrite-threshold` (default 1M) config controls after how many delete operations shall we rewrite the whole file and start again.

**Comment by JaySon-Huang** [comment]
This feature was cherry-pick to release-4.0 branch and released with v4.0.9 at last. The PR is https://github.com/tikv/tikv/pull/9195
