### ISSUE TITLE
Monitor memory allocation by each thread

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#8235]
### Is your feature request related to a problem? Please describe:
Jemalloc has stats about memory allocated and deallocated by each thread. We can use this metrics to get an approximate how memory distribute.

We can maintain a global map that stores pointer of the metrics when a thread is started, and cleared before the thread exits. The key to attain the pointer is `thread.allocatedp` and `thread.deallocatedp`.

Another useful information is arena that bound to the thread. It can be obtained by `thread.arena`. The information can be stored with allocation metrics and output to response when allocation is accessed at https://github.com/tikv/tikv/blob/master/src/server/service/debug.rs#L371.

**Comment by abbccdda** [comment]
s/alloction/allocation

**Comment by abbccdda** [comment]
Thanks for the proposal, I will make an attempt on this.

**Comment by BusyJay** [comment]
Thanks! Just ping me if have any problem.

**Comment by BusyJay** [comment]
thread.arena is not supported yet.

**Comment by glorv** [comment]
#16255 added support for collect per-thread memory usage.
