### ISSUE TITLE
cases::test_conf_change::test_destroy_local_reader not work

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#8248]
### What version of TiKV are you using?
Master

### Steps to reproduce
cargo test --package tests --features failpoints --test failpoints -- cases::test_conf_change::test_destroy_local_reader --exact --nocapture

### What did you expect?
failpoint code executes after `fail::cfg(reader_has_delegate, "panic").unwrap();` but indeed it not, so failpoint config is invalid.

**Comment by NingLin-P** [comment]
> failpoint code executes after fail::cfg(reader_has_delegate, "panic").unwrap(); but indeed it not.

This is expected, the test case testing that the `ReadDelegate` should be destroyed after the peer removed, and the failpoint will panic if the `ReadDelegate` still exists.

**Comment by hunterlxt** [comment]
Ok, I didn’t expect failpoint to be used as `assert`, closed this issue.
