### ISSUE TITLE
cases::test_coprocessor::test_deadline_2 not work

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#8254]
### What version of TiKV are you using?
master

### Steps to reproduce
- add `println!("list {:?}", fail::list());` at `fail_point!("rockskv_async_snapshot",`
- `cargo test --package tests --test failpoints -- cases::test_coprocessor::test_deadline_2 --exact --nocapture`

### What did you expect?
fail::list prints failpoint configuration

**Comment by MyonKeminta** [comment]
Similar to https://github.com/tikv/tikv/issues/8255 , it's expected. You added the print statement to the function that's expected to be never invoked.
