### ISSUE TITLE
cases::test_merge::test_node_merge_crash_when_snapshot not work

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#8278]
### What version of TiKV are you using?
master

### What operating system and CPU are you using?
ubuntu 20.04

### Steps to reproduce
`cargo test --package tests --test failpoints -- cases::test_merge::test_node_merge_crash_when_snapshot --exact --nocapture`

### What did you expect?
failpoint "on_region_worker_destroy" code be executed.

### What did happened?
but it's not

**Comment by gengliqi** [comment]
The failpoint `on_region_worker_destroy` is truly useless. I will remove it in next pr.
