### ISSUE TITLE
cases::test_replica_read::test_duplicate_read_index_ctx not work

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#8285]
### What version of TiKV are you using?
655c5058d806eaa5b149872cc757cd1aa127c826

### What operating system and CPU are you using?
ubuntu 2004

### Steps to reproduce
cargo test --package tests --test failpoints -- cases::test_replica_read::test_duplicate_read_index_ctx --exact --nocapture

### What did you expect?
failpoint config correctly

**Comment by BusyJay** [comment]
Is it still a problem in master?

**Comment by hunterlxt** [comment]
@5kbpers PTAL

**Comment by 5kbpers** [comment]
The failpoint `pause_on_peer_collect_message` was used for ensuring all messages were put into the same batch.
If the messages were sent very fast, this failpoint will be removed before it was executed.
So this behavior is expected, will close this issue.
