### ISSUE TITLE
Let Coprocessor completely work in the batch mode

### ISSUE THREAD

**Issue by iosmanthus** [tikv/tikv#8288]
### Is your feature request related to a problem?
Currently, the batch executors of coprocessor don't support in a server-side streaming request. If such a request was received, we would fall back to using the old execution framework. The old execution share exactly the same logic with the batch one which complicates our codebase and inhibits our coprocessor maximize its performance.
https://github.com/tikv/tikv/blob/66d2566c166e74bedca8b3172f6a2a95bf01efd4/src/coprocessor/dag/mod.rs#L65

### Describe the feature you'd like:
The remove of the old execution framework consists of 3 steps:
1. Remove the fallback check in the `DagHandlerBuilder`.
2. Overwrite the default implementation in `RequestHandler::handle_streaming_request` for `BatchDAGHandler`.
3. Pass the integration tests.

### Teachability, Documentation, Adoption, Migration Strategy:
Here is a WIP pull request to refer: https://github.com/tikv/tikv/pull/5945

**Comment by Renkai** [comment]
pick up challenge
