### ISSUE TITLE
Memory  usage gradually grows up and OOM when running random merge

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#8315]
### What version of TiKV are you using?

Master (8faf2601b981f3ac58b902f8a1c0d24ba41b60b1)

### What operating system and CPU are you using?

k8s, CPU: require 4, limit 16;  memory require 16G, limit 32G

### Steps to reproduce

1. Load some data, generate lot of regions
![image](https://user-images.githubusercontent.com/9948422/88361600-25c5a400-cdac-11ea-83b6-d326011e3b51.png)
![image](https://user-images.githubusercontent.com/9948422/88361720-92d93980-cdac-11ea-8737-d93c7754efd1.png)

2. Enable random merge

3. Wait

### What did you expect?

TiKV runs normally

### What did happened?

TiKV's memory usage gradually grows up and OOM

![image](https://user-images.githubusercontent.com/9948422/88361836-ffeccf00-cdac-11ea-9cf5-b606d9c9c243.png)

...and it's not used by block cache

![image](https://user-images.githubusercontent.com/9948422/88361861-18f58000-cdad-11ea-8547-09ab3367005f.png)

I don't know the reason but I'm afraid there are some memory leak.

cc @BusyJay

**Comment by BusyJay** [comment]
Thanks for the report! I will investigate it.

**Comment by youjiali1995** [comment]
@MyonKeminta How did you find it?

**Comment by MyonKeminta** [comment]
@youjiali1995 Just testing running CDC with random merge and then found TiKV's memory keeps growing. Then I disable CDC and run random merge again and found it still keeps growing.
