### ISSUE TITLE
Finished issues should be closed

### ISSUE THREAD

**Issue by name1e5s** [tikv/tikv#8360]
## Bug Report

I found that some finished issues are still open. Maybe it's better to close them. Here is the list.

| Issue Number | Finished In... |
| ------------------ | ------------------ |
| #6959  | #7195  |
| #6948  | #6499 |
| #6947 | #8312  |
| #6945  | #7769  |
| #6930 | #6361 |
| #6925  | #7010 |
| #6882 | #7086 |
| #6828 | #6645 |
| #6829 | #6647 |

**Comment by glorv** [comment]
@lonng PTAL

**Comment by lonng** [comment]
Done
