### ISSUE TITLE
what‘s version is 4.1.0-alpha ？

### ISSUE THREAD

**Issue by lddlww** [tikv/tikv#8366]
tikv-server -V
```
TiKV 
Release Version:   4.1.0-alpha
Git Commit Hash:   36dab75da84ec57374d364a4a4af9146ec31df07
Git Commit Branch: master
UTC Build Time:    2020-02-17 01:39:18
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```

when i use v4.0.3 to upgrade tikv，i meet error：
```
2020/07/29 17:19:30.784 +08:00] [ERROR] [util.rs:340] ["request failed"] [err="Grpc(RpcFailure(RpcStatus { status: 2-UNKNOWN, details: Some(\"version should compatible with version  4.1.0-alpha, got 4.0.3\") }))"]
```

**Comment by sticnarf** [comment]
4.1.0-alpha is the version of the current master branch. It's higher than 4.0.x versions.

**Comment by lddlww** [comment]
how solve this problem?

**Comment by breeswish** [comment]
This error means you are previously using a nightly version (v4.1.0), and then try to "downgrade" to a stable version v4.0.3 and it cannot proceed. If this is a development environment, suggest to keep using nightly version.

**Comment by lddlww** [comment]
it’s product env

**Comment by sticnarf** [comment]
There is no guarantee that downgrading from a nightly version to a stable version would work. A force downgrade can be DANGEROUS.

**Comment by lddlww** [comment]
mean，don't change it，just keep it as it is？

**Comment by sticnarf** [comment]
Right, it's dangerous to change.

If you really want to use another version, remember to backup your data.

**Comment by lddlww** [comment]
is it(```4.1.0-alpha nightly version```) possible to upgrade to the ```v4.1.0 stable``` use ```tiup```，after ```v4.1.0 stable``` public？

**Comment by sticnarf** [comment]
It's also not recommended because we allow incompatible changes to master during development. Sorry for that.

**Comment by lddlww** [comment]
so，what i can do is to import tikv data，then export tikv data to another version？

**Comment by sticnarf** [comment]
It's not guaranteed to be safe to let nightly and stable tikv nodes coexist. If you really want to use the dangerous way, you can use `pd-ctl` to change the cluster version to a low version: https://docs.pingcap.com/tidb/stable/pd-control#config-show--set-option-value--placement-rules

**Comment by lddlww** [comment]
how can i do to remove v4.1.0-alpha safely?

**Comment by sticnarf** [comment]
You can't. You either create a new cluster and import. Or just change the cluster version in PD and simply do a upgrade (can be unsafe).

**Comment by lddlww** [comment]
@sticnarf 
i see，thanks for your patience
