### ISSUE TITLE
No saving uninitialized peer's raft hard state may lead to two same-term raft leaders

### ISSUE THREAD

**Issue by gengliqi** [tikv/tikv#8381]
## Bug Report

https://github.com/tikv/tikv/blob/e95e7c5db5be2239805fff2c336bc1b6087ad3ab/components/raftstore/src/store/peer_storage.rs#L1354-L1360

As above code, TiKV doesn't save uninitialized peer's raft hard state. If an uninitialized peer grants its vote to a specific candidate, this information can be lost when this TiKV down. It means this peer can also grant its vote to another candidate.

It may break raft's **Election Safety** rule, i.e. at most one leader can be elected in a given term.

For example, there are 3 peers. One of them is uninitialized. For some reason, the other two peers start to request a vote. And this uninitialized peer grants its votes to both of them. (Its TiKV is down and restarts between two votes.

In normal cases, if a region migrates to another place, we do it one by one. PD adds a new peer and then removes an old peer. i.e. peer count changes from 3 to 4 and then to 3.

Since PD does not remove an old peer if the new peer is uninitialized, the only possible problem is when there are 4 peers and the new peer is uninitialized. But in previous cases, we can find that two same-term leaders event can't happen even if this new peer grants its vote to two candidates. 

It can be easily proved. For example, peer A B C D(uninitialized). peer A and B become candidates. C grants its vote to A and D grants its vote to A and B. A gets 3 votes and becomes leader while B only gets 2.

* What if we use `joint consensus`?
It doesn't like the previous case. I think this bug can really break the correctness.

* How to fix it?
I think saving raft hard state is necessary. But there are some corner cases that need to be handled.
For example, the following code in `on_ready_split_region` https://github.com/tikv/tikv/blob/e95e7c5db5be2239805fff2c336bc1b6087ad3ab/components/raftstore/src/store/fsm/peer.rs#L2031-L2045
If a new peer is created from splitting, another uninitialized peer with the same peer id may have already existed. The previous method is just to remove that uninitialized peer, but what if that peer has already voted to someone?

**Comment by NingLin-P** [comment]
When PD adds a new peer to a raft group, PD will add it as a learner first and wait until it catches up log (at this time, it should be initialized) then propose another `confchange` to promote it to voter. This workflow should reduce the chance of two same-term raft happens.

**Comment by BusyJay** [comment]
Duplicated with #3572.

Though I don't recall how did I conclude it was safe even after applying snapshot. You can write a test case to see if there can be problem. As a quick and easy workaround, we can deny promoting an uninitialized learner to voter.

**Comment by gengliqi** [comment]
> When PD adds a new peer to a raft group, PD will add it as a learner first and wait until it catches up log (at this time, it should be initialized) then propose another `confchange` to promote it to voter. This workflow should reduce the chance of two same-term raft happens.

I forgot it is a learner at this time. This rule must be ensured by PD even the joint consensus is used.

**Comment by gengliqi** [comment]
The rule is **Forbid promoting an uninitialized learner to voter**.
