### ISSUE TITLE
More tombstone keys in the memtable of rocksdb and the seek duration may increase

### ISSUE THREAD

**Issue by zhenjiaogao** [tikv/tikv#8437]
### Is your feature request related to a problem? Please describe:
When there are more tombstone keys in the memtable of rocksdb, the seek duration may increase. Currently, there is no effective monitoring metrics in Grafana to locate this problem.

### Describe the feature you'd like:

It is recommended to add some grafana metric to help us accurately locate this problem and detect this abnormality in TiKV, and actively flush to reduce the impact on rocksdb-kv seek duration.

### Describe alternatives you've considered:

Manual compaction.

**Comment by Connor1996** [comment]
Duplicate with https://github.com/tikv/tikv/issues/8486
