### ISSUE TITLE
Last configuration can be corrupted when disk is full

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#8438]
## Bug Report

TiKV save current configuration before startup. If disk is full at that time, the configuration can be partially saved hence corrupted. It's recommended to check if the configuration is the same before saving so that a lot of writes can be saved. If they are different, we should dump and rename instead of writing directly.

**Comment by gentcys** [comment]
Does `check if the configuration is the same` mean to compare two instances of `TiKvConfig` struct?

**Comment by BusyJay** [comment]
Maybe check the serialized result is simpler.

**Comment by gentcys** [comment]
I'd like to work on this.
