### ISSUE TITLE
coprocessor: redact log

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#8469]
## Development Task

In #7758 we are adding `security.redact-info-log` option to TiKV, to hide user data from printing into info log. The option provide a way for users to avoid leaking sensitive data into info log, when they want to transfer the info log out of the storage node to use in other systems. However the PR only handles MVCC and storage engine KVs. It does not handle coprocessor logs. We need to redact log for the coprocessor module when the option is on.

The task is part of https://github.com/pingcap/tidb/issues/18566 and we target to include it in 5.0 release.

**Comment by breeswish** [comment]
@iosmanthus PTAL, the dead line is to finish it when 5.0 is released, which is not very urgent.

**Comment by BusyJay** [comment]
I think searching `encode_upper` should be sufficient enough for most cases in TiKV. And for data from protobuf struct, you need to updates protobuf-build to change the format. Also there maybe also cases that logging error with raw Debug/Display format.

**Comment by yiwu-arbug** [comment]
@BusyJay I was wondering if it is possible to update protobuf generated code to redact log. What you are saying is it is possible. Is there any pointers? We can separated it in another task.

**Comment by BusyJay** [comment]
@nrc Do you know how to redact binary in protobuf-build? It was customized by trait `PbPrint` before.

**Comment by nrc** [comment]
I think we still customise using PbPrint, this is the modified branch: https://github.com/pingcap/rust-protobuf/tree/v2.8. Or you can just make changes to the code directly in that branch.

**Comment by breeswish** [comment]
The basic redact is implemented in 5.0.0. Closing.
