### ISSUE TITLE
copr: add non-nullable and writer support for varg rpn_fn

### ISSUE THREAD

**Issue by skyzh** [tikv/tikv#8491]
### Is your feature request related to a problem? Please describe:

https://github.com/tikv/rfcs/pull/43 only adds non-nullable and writer support for normal rpn_fn. We could implement this on varg rpn_fn.

### Describe the feature you'd like:

Implement non-nullable and writer support for varg rpn_fn.

### Teachability, Documentation, Adoption, Migration Strategy:

Modifying https://github.com/tikv/tikv/blob/master/components/tidb_query_codegen/src/rpn_function.rs is enough.

Then we could define something like:

```rust
#[rpn_fn(vargs, writer)]
pub fn repeat(input: &[BytesRef], writer: BytesWriter) -> Result<BytesGuard> 
```

**Comment by Xuanwo** [comment]
Maybe we can close this issue after #8740 && #8771 get merged?
