### ISSUE TITLE
crossbeam-channel 0.4 has undefined behavior

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#8492]
## Bug Report

See https://github.com/crossbeam-rs/crossbeam/pull/533

### What version of TiKV are you using?

Nightly

**Comment by zhangjinpeng1987** [comment]
@sticnarf Seems crossbeam has fixed this problem, can we update it now?

**Comment by sticnarf** [comment]
> @sticnarf Seems crossbeam has fixed this problem, can we update it now?

This issue was resolved by https://github.com/tikv/tikv/pull/8803.
