### ISSUE TITLE
Document Engine sub-type in kv module as a part of doc quest

### ISSUE THREAD

**Issue by palash25** [tikv/tikv#8546]
Related to: https://github.com/tikv/sig-transaction/issues/25

Hi I would like to try documenting [`Engine`](https://github.com/tikv/tikv/blob/master/src/storage/kv/mod.rs#L95) as a part of the doc quest. 

@nrc can you please add this issue link to the parent issue in the sig-transaction repo

**Comment by nrc** [comment]
Awesome!

cc @brson who has le the work on the Engine trait.

**Comment by palash25** [comment]
I had a question regarding this, does documenting the methods under Engine trait also come under the scope of this issue or is it just the comments on top of the trait, because if it is the latter, I can't really think of much to document

**Comment by nrc** [comment]
It would be good to document the methods. As you say, there is not a lot to say about the trait itself.
