### ISSUE TITLE
Improve TiKV performance by compressing data

### ISSUE THREAD

**Issue by arthuryangcs** [tikv/tikv#8549]
This is my performance test report：
[https://github.com/arthuryangcs/High-Performance-TiDB-Homework/blob/master/lesson-03/perf.md](https://github.com/arthuryangcs/High-Performance-TiDB-Homework/blob/master/lesson-03/perf.md)

I think the bottleneck of cluster is the IO of TiKV. Maybe we can compress data which storage on the desk to optimize the performance. It's a space-time tradeoff. The methods including but not limited to the data compression algorithm and a more compact data structure.

**Comment by arthuryangcs** [comment]
This is my performance test report：
[https://github.com/arthuryangcs/High-Performance-TiDB-Homework/blob/master/lesson-03/perf.md](https://github.com/arthuryangcs/High-Performance-TiDB-Homework/blob/master/lesson-03/perf.md)

I think the bottleneck of cluster is the IO of TiKV. Maybe we can compress data which storage on the desk to optimize the performance. It's a space-time tradeoff. The methods including but not limited to the data compression algorithm and a more compact data structure.

**Comment by nolouch** [comment]
Hi, @arthuryangcs .  There are several optional compression algorithms for rocksdb, maybe you can check the [document](https://github.com/facebook/rocksdb/wiki/Compression#compression-library).

**Comment by yiwu-arbug** [comment]
yes, rocksdb is already doing compression, and we support various compression algorithms. One thing we can try is enabling dictionary compression https://facebook.github.io/zstd/#small-data. Are you interested in contributing?
