### ISSUE TITLE
Add blob cache usage metrics for Titan

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#8552]
Now, we only have blob cache hit metrics for Titan. It would be useful to have a blob cache usage metrics just like block cache usage. 

Task breakdown:
- Add an API for rust-rocksdb to get `blob_cache_usage`, you can refer to how we added block cache usage before https://github.com/tikv/rust-rocksdb/pull/198
- Collect the blob cache usage metrics in TiKV, see how we do it for block cache usage https://github.com/tikv/tikv/blob/master/components/engine_rocks/src/rocks_metrics.rs#L1071
- Add a blob cache usage panel for Titan in grafana

**Comment by Rustin-Liu** [comment]
I am try to working on this.

**Comment by Connor1996** [comment]
@Rustin-Liu Thanks!
@zhuboshuai Do you have been working on it? If that, please inform @Rustin-Liu
