### ISSUE TITLE
Description of the 'split.qps-threshold' parameter is missing in the config-template file 

### ISSUE THREAD

**Issue by zhenjiaogao** [tikv/tikv#8582]
### What did you expect?
Description of the 'split.qps-threshold' parameter is missing in the config-template file 

### What did happened?
Add  'split.qps-threshold' parameter description in the config-template file

**Comment by kennytm** [comment]
This issue is unrelated to SIG-Tools (BR).

**Comment by BusyJay** [comment]
Can they use `tikv-server --print-sample-config` to get accurate available public configurations?

**Comment by zhenjiaogao** [comment]
The new version of tidb-operator in the future will support a common structure and does not depend on the output of the template configuration file or `./tikv-server --print-sample-config`.
