### ISSUE TITLE
Coprocessor support ENUM / SET

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#8605]
## Development Task

Currently TiKV Coprocessor does not support ENUM / SET data types, so that expressions related to these data types cannot be pushed down, which greatly affects performance in some scenarios. We have met this case several times.

This task is to add ENUM / SET data type support to the TiKV Coprocessor.

There are some previous discussions in https://github.com/tikv/tikv/issues/5738 . Some content is outdated. According to our latest studies, the idea "Always treat ENUM / SET as string" raised in https://github.com/tikv/tikv/issues/5738#issuecomment-568288021 will not work in some edge cases, so that I would like to recommend to implement this feature by introducing two brand new `EvalType`s.

@skyzh will attach a detailed RFC about how to implement this feature later.

**Comment by skyzh** [comment]
I’ll look into this soon.

**Comment by skyzh** [comment]
RFC: https://github.com/tikv/rfcs/pull/57

**Comment by WT-Liu** [comment]
This issue is for the TiKV CommunityBridge project. Mentee candidates who want to participate in CommunityBridge with the TiKV project are expected to join [Slack Channel](https://join.slack.com/t/tikv-wg/shared_invite/enQtNTUyODE4ODU2MzI0LWVlMWMzMDkyNWE5ZjY1ODAzMWUwZGVhNGNhYTc3MzJhYWE0Y2FjYjliYzY1OWJlYTc4OWVjZWM1NDkwN2QxNDE) (#community-bridge-2020) to have self-introductions before applying.

**Comment by Xuanwo** [comment]
Roadmap here: #9066

**Comment by zz-jason** [comment]
@Xuanwo how to enable it in TiDB?

**Comment by skyzh** [comment]
> @Xuanwo how to enable it in TiDB?

We only finished the part of TiKV. Now TiKV supports enum/set-based aggregator and functions. Later we will need to modify TiDB to cooperate with this part.

**Comment by Xuanwo** [comment]
As described in the roadmap, we still have work to do on tipb/tidb side to make this feature work.

**Comment by zz-jason** [comment]
got, thanks

**Comment by skyzh** [comment]
Now we have implemented enum and set calculation on TiKV side, and this issue could be closed. The pushdown part is tracked at TiDB repo https://github.com/pingcap/tidb/issues/23619.
