### ISSUE TITLE
Status port refused connection when tls enabled

### ISSUE THREAD

**Issue by lucklove** [tikv/tikv#8641]
### What version of TiKV are you using?

I have test `v4.0.2`, `v4.0.4`, both have this issue.

### What operating system and CPU are you using?

Linux/Centos 7

### Steps to reproduce

These steps are taken on the same host with IP 172.16.5.140

1. Start a pd-server with the command:
```sh
exec bin/pd-server \
    --name="pd-172.16.5.140-2379" \
    --client-urls="https://0.0.0.0:2379" \
    --advertise-client-urls="https://172.16.5.140:2379" \
    --peer-urls="https://172.16.5.140:2380" \
    --advertise-peer-urls="https://172.16.5.140:2380" \
    --data-dir="/data2/pd-2379/data" \
    --initial-cluster="pd-172.16.5.140-2379=https://172.16.5.140:2380" \
    --config=conf/pd.toml
```

2. Start a tikv-server with the command:
```sh
exec bin/tikv-server \
    --addr "0.0.0.0:20160" \
    --advertise-addr "172.16.5.140:20160" \
    --status-addr "0.0.0.0:20180" \
    --pd "172.16.5.140:2379" \
    --data-dir "/data2/tikv-20160/data" \
    --config conf/tikv.toml
```

3. Execute the commands
```sh
curl https://172.16.5.140:20180/metrics  # the 1st curl
curl http://172.16.5.140:20180/metrics    # the 2nd curl
curl https://172.16.5.140:20180/metrics  # the 3rd curl
```

### What did you expect?
The 1st and 3rd curl should both success.

### What did happened?
Only the 1st curl success. 
The 2nd curl failed with `curl: (56) Recv failure: Connection reset by peer`.
And the 3rd and latter curl will fail with `curl: (7) Failed to connect to 172.16.5.140 port 20180: Connection refused`

### IMO
I think this may be related to https://github.com/tikv/tikv/issues/8449

**Comment by hunterlxt** [comment]
It has now been determined that it is introduced by https://github.com/tikv/tikv/pull/7893
