### ISSUE TITLE
Improve the read performance of MvccTxn

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#8650]
## Description
TiKV uses MVCC to implement transaction. It has to fetch the specified version of a key to check some constraints, for example:
* Whether the transaction has been committed or rolled back.
* Fetch the value of the key in lock-and-read.

There are some help-wanted issues related to it:
* https://github.com/tikv/tikv/issues/7024
* https://github.com/tikv/tikv/issues/8229

## Score

* 2000

## SIG Slack Channel

You can join [#sig-transaction](https://tikv-wg.slack.com/archives/CU0TU3GSE) on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)

* @youjiali1995  

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Rust

## Learning Materials

* https://github.com/facebook/rocksdb/wiki/Prefix-Seek

**Comment by YangKian** [comment]
Hi~I'd like to have some try. Since I'm a newbie in both rust and TiKV, I'll start from learning the material you listed and read some related TiKV code. Are there any other Suggestions I can follow by?

**Comment by youjiali1995** [comment]
Hi, @YangKian. The transaction part of the high-performance TiDB lesson is coming soon and the description of this issue isn't complete. I will elaborate it later. 

There are some references to this issue:
- [TiKV 源码解析系列文章（十二）分布式事务](https://pingcap.com/blog-cn/tikv-source-code-reading-12/)
- [TiKV 源码解析系列文章（十三）MVCC 数据读取](https://pingcap.com/blog-cn/tikv-source-code-reading-13/)

And also you should know how RocksDB reads values: https://github.com/facebook/rocksdb/wiki/rocksdb-basics. The part you need to modify is [MvccReader](https://github.com/tikv/tikv/blob/master/src/storage/mvcc/reader/reader.rs).

**Comment by YangKian** [comment]
Get~ Thanks for the elaborate learning materials, I'll read them first :)

**Comment by blueseason** [comment]
> elaborate



> Hi, @YangKian. The transaction part of the high-performance TiDB lesson is coming soon and the description of this issue isn't complete. I will elaborate it later.
> 
> There are some references to this issue:
> 
> * [TiKV 源码解析系列文章（十二）分布式事务](https://pingcap.com/blog-cn/tikv-source-code-reading-12/)
> * [TiKV 源码解析系列文章（十三）MVCC 数据读取](https://pingcap.com/blog-cn/tikv-source-code-reading-13/)
> 
> And also you should know how RocksDB reads values: https://github.com/facebook/rocksdb/wiki/rocksdb-basics. The part you need to modify is [MvccReader](https://github.com/tikv/tikv/blob/master/src/storage/mvcc/reader/reader.rs).

What's the goal of this improvement? Can you update it?

**Comment by youjiali1995** [comment]
@blueseason Sorry, it can be resolved by https://github.com/tikv/tikv/pull/8514. I will remove the help wanted label.
