### ISSUE TITLE
Benchmark for the memory lock using different concurrent structures like self-balanced trees

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#8653]
## Description
TiKV writes locks to a memory lock table during prewrite to guarantee the correctness of async commit, and read operations need to check locks in it. The performance of the memory lock table is important, and we use [crossbeam-skiplist](https://github.com/tikv/tikv/pull/8608) as the memory lock table now. The task for you is to find the optimal data structures for it which should has great performance and low memory overhead.

## Score

* 6600

## SIG Slack Channel

You can join [#sig-transaction](https://tikv-wg.slack.com/archives/CU0TU3GSE) on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)

* @sticnarf   

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Rust
* Benchmark

## Learning Materials

* https://github.com/tikv/sig-transaction/blob/master/design/async-commit/README.md

**Comment by Fullstop000** [comment]
What's the status of this issue?

**Comment by youjiali1995** [comment]
It has been resolved by @sticnarf , so close it.
