### ISSUE TITLE
UnsafeDestroyRange may cause panic for a concurrent generating snap when Titan enabled

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#8661]
When Titan enabled, after doing deletefiles(deleteblobfiles), iterating on the deleted range may encounter `MissingBlobFile` error. So we set a special `key_only` for Titan when doing the scan-delete.

Whereas, if there is a concurrent generating snap process, it will encounter the `MissingBlobFile` error and panic in final after trying 5 times. So it's better to delete blob files in the range after TiKV finishing scan-delete on that range.

**Comment by yiwu-arbug** [comment]
How could it have concurrent snapshoting, after delete range issued?

**Comment by Connor1996** [comment]
Cause `UnsafeDestroyRange` doesn't go through the Raft, whereas called by TiDB directly. So it's possible that there is a concurrent snapshot generation issued by Raft.
