### ISSUE TITLE
compression ratio of L6 is even smaller than L5/L4

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#8721]
![image](https://user-images.githubusercontent.com/13497871/93966115-78184680-fd96-11ea-827f-233d9e8e346e.png)
It can be observed in multiple clusters.

**Comment by Connor1996** [comment]
Some thoughts:
- ingested files doesn't use zstd compression
- By dynamical level bytes, L6 may accumulate some files with no compression at first

**Comment by Connor1996** [comment]
Also why L0's is better than L2/L3

**Comment by yiwu-arbug** [comment]
Fixed by #8908
