### ISSUE TITLE
TiKV status down when accept http requests with TLS enabled

### ISSUE THREAD

**Issue by aylei** [tikv/tikv#8738]
### What version of TiKV are you using?

`v4.0.6`

### What operating system and CPU are you using?

Ubuntu v14.04

### Steps to reproduce

1. start tikv with TLS enabled
2. access the tikv status port in http, e.g. `curl localhost:20180`
3. As an example, `curl` will return `curl: (56) Recv failure: Connection reset by peer`, and TiKV reports:

```
[2020/09/25 05:52:21.348 +00:00] [ERROR] [mod.rs:739] ["Status server error: hyper::Error(Accept, Custom { kind: Other, error: \"TLS handshake error\" })"]
```

4. Then the status server will go down and cannot recover without restarting server:

![image](https://user-images.githubusercontent.com/18556593/94231672-16431280-ff37-11ea-98a2-6c0f58f8e949.png)

### What did you expect?

TiKV reject http requests when TLS enabled, without status server crashing

**Comment by BusyJay** [comment]
It should be fixed by #8654, which is expected to be released as part of v4.0.7.
