### ISSUE TITLE
Unsupported datum flag 6 for Int vector

### ISSUE THREAD

**Issue by liuhuanHappyStudy** [tikv/tikv#8769]
## Question

1 queries executed, 0 success, 1 errors, 0 warnings

SELECT tidb_version()
Release Version: v4.0.0
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time: 2020-05-28 01:37:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

When the field in select contains error_type, the client will report an error: Error code: 1105
Int vector unsupported benchmark mark 6

E.g: SELECT * FROM `checking_diff` LIMIT 0, 1000; 或者：SELECT `error_type` FROM `xlink_dev`.`checking_diff` LIMIT 10
Error code: 1105
**Unsupported datum flag 6 for Int vector**

Execution time: 0 sec
Transmission time: 0 sec
Total time: 0.030 sec

Table Structure：
CREATE TABLE `checking_diff` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `third_trade_no` varchar(50) DEFAULT NULL COMMENT '第三方订单号',
  `out_trade_no` varchar(40) DEFAULT NULL COMMENT '外部订单号',
  `third_amount` bigint(20) DEFAULT NULL COMMENT '第三方订单金额',
  `total_amount` bigint(20) DEFAULT NULL COMMENT '平台订单金额',
  `**error_type**` int(1) DEFAULT NULL COMMENT '1:长款,2:短款,3金额差异,4,存疑,5正常',
  `trade_time` datetime DEFAULT NULL COMMENT '交易时间',
  `checking_date` date DEFAULT NULL COMMENT '对账时间yyyy-MM-dd',
  `institution_code` varchar(15) DEFAULT NULL COMMENT '通道编码',
  `merchant_id` int(11) DEFAULT NULL COMMENT '商户号',
  `checking_type` char(1) DEFAULT NULL COMMENT '类型 1.以商户维度处理， 2.以渠道维度处理',
  `task_id` int(11) DEFAULT NULL COMMENT '任务ID',
  `status` int(1) DEFAULT NULL COMMENT '0:未处理,1:已处理',
  `pre_order_no` varchar(64) DEFAULT NULL COMMENT '业务单号',
  `trade_type` varchar(32) DEFAULT NULL COMMENT '交易类型',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1350001

**tidb err log:**
[2020/09/30 14:05:00.917 +08:00] [ERROR] [conn.go:728] ["command dispatched failed"] [conn=39770] [connInfo="id:39770, addr:218.76.8.29:51551 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="SELECT * FROM `checking_diff`\n LIMIT 0, 1000"] [txn_mode=PESSIMISTIC] [err="[tikv:10000]Unsupported datum flag 6 for Int vector"]

_OR_

[2020/09/30 14:11:50.995 +08:00] [ERROR] [conn.go:728] ["command dispatched failed"] [conn=39770] [connInfo="id:39770, addr:218.76.8.29:51551 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="SELECT `error_type` FROM `xlink_dev`.`checking_diff` limit 10\n"] [txn_mode=PESSIMISTIC] [err="[tikv:10000]Unsupported datum flag 6 for Int vector"]

When the field in select not contains **error_type**, the client will be OK!

E.g: SELECT  id,out_trade_no,total_amount  FROM `xlink_dev`.`checking_diff` LIMIT 10
I can get data. like:
id	out_trade_no	total_amount
614475	155620200620204001243192647	100000
614476	155620200620101638376361568	35300
614477	155620200620170048273962003	2500
614478	155620200620115259958601672	2300
614479	155620200620195604353658283	6000
614480	155620200620190112050360721	500
614481	155620200620180806875679726	12300
614482	155620200620204517311275053	1800
614483	155620200620200312118124573	6000
614484	155620200620182145869736211	300

**Comment by djshow832** [comment]
Hi, it's a TiDB issue. You can submit it in TiDB repo and label it with `sig/ddl`.

**Comment by wjhuang2016** [comment]
Link to https://asktug.com/t/topic/37617

**Comment by breeswish** [comment]
Is this issue resolved?

**Comment by glkappe** [comment]
+1，Fresh case，v4.0.6

--------------
SELECT m.status FROM testxxx_20210207 as m WHERE m.ship_time >= '2021-02-03' AND m.ship_time <= '2021-02-04'
--------------

ERROR 1105 (HY000): Unsupported datum flag 2 for Int vector

**Comment by glkappe** [comment]
@djshow832 Does this issue exist in the pingcap/tidb repo?

**Comment by djshow832** [comment]
It's probably a TiDB bug, not a TiKV bug. It's not solved as far as I know.
