### ISSUE TITLE
Would raw kv interface support atomic operations like CAS(compare and set)?

### ISSUE THREAD

**Issue by cannium** [tikv/tikv#8841]
### Is your feature request related to a problem? Please describe:

Nope

### Describe the feature you'd like:

I'd like to use the raw kv interface for better performance, but certain operations require compare-and-set and other atomic support.

### Describe alternatives you've considered:

I might consider some other distributed kv storage.

### Teachability, Documentation, Adoption, Migration Strategy:

e.g. I have a pair `SomeK -> SomeV`, when updating SomeK concurrently, by first read `SomeV`, then modify and update `SomeV`, I need CAS to ensure the correctness of the program.

**Comment by cannium** [comment]
Sorry, might be a duplicate of https://github.com/tikv/tikv/issues/3015
But I emphasize more on raw kv interface because for txn kv, I can use transaction.

**Comment by andylokandy** [comment]
Duplicated issue. We've been internally discussing the feature, and you can add comments to https://github.com/tikv/tikv/issues/3015.
