### ISSUE TITLE
Add more test to cover Load-base-split

### ISSUE THREAD

**Issue by lhy1024** [tikv/tikv#8862]
## Description

TiKV crashes in the [previous code](https://github.com/tikv/tikv/issues/8574) which means the unit tests do not cover this case i.e. Task::AutoSplit. I find it is added from #6663. We need to add more test to cover it

## Score

- 900

## Mentor

- @lhy1024

## Recommended Skills

- Rust

**Comment by hbina** [comment]
I don't see any crashes in the reference issue?

**Comment by lhy1024** [comment]
> I don't see any crashes in the reference issue?

The fixed pr is #8585 and I hope we can add more unit test to avoid similar problems

**Comment by lhy1024** [comment]
add some test in #10543 and challenge-program is end
