### ISSUE TITLE
Restore slow down due to rewriting file/key.dict after enabling encryption at rest

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#8916]
## Bug Report

Restore slow down due to rewriting file/key.dict after enabling encryption at rest.

### What version of TiKV are you using?

release-4.0

### Steps to reproduce

BR restore 1T backup.

### What did you expect?

Restore should not slow down greatly due to encryption at rest.

### What did happened?

Restore becomes slower as sst file increases.

![image](https://user-images.githubusercontent.com/2150711/97679021-b0b2ea80-1acf-11eb-8cc5-1655780f22e9.png)

Flame graph https://gist.github.com/overvenus/ba034073b37e8ed461bc550b9a97ddd6

**Comment by overvenus** [comment]
Cc https://github.com/pingcap/br/issues/570

**Comment by hunterlxt** [comment]
Closed. ref https://github.com/tikv/tikv/pull/8960 https://github.com/tikv/tikv/pull/8865
