### ISSUE TITLE
Output slow log containing scan details for KvGet and kvBatchGet

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#8933]
### Is your feature request related to a problem? Please describe:

Now TiKV prints slow log when Coprocessor request takes long time. It is useful to debug issues. However for other requests, like KvGet, KvBatchGet and write requests these information is not available. It is nice to have one!

### Describe the feature you'd like:

Output slow log, containing scan details, like how many tombstones scanned (PerfContext), how is the block-cache hit, how many versions scanned, etc.

Scan details should be at least added to KvGet and KvBatchGet, since in 4.0 TiDB heavily utilize these two interface now. It would also be nice to be added to other interfaces.

### Teachability, Documentation, Adoption, Migration Strategy:

Note that these scan information for KvGet and KvBatchGet is added in https://github.com/tikv/tikv/pull/8814. What you need to do is just print a log when it takes long time. Also considering https://github.com/tikv/tikv/issues/8932 maybe you'd better let the slow threshold configurable.

**Comment by RaymondWaterlooLi** [comment]
I am new to this project, but may I work on this issue?

**Comment by breeswish** [comment]
Close for https://github.com/tikv/tikv/issues/8944
