### ISSUE TITLE
Return wait time and process time for KvGet and KvBatchGet

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#8942]
## Description

Now we have wait time and process time for Coprocessor request. However for other KV requests, like Get and BatchGet, this information is not available. Adding such information may help us figure out where latency comes from, for example, when TiDB's latency is 100ms while TiKV's latency is 70ms, the delta 30ms may come from network latency or Go routine scheduling.

This is a subtask extracted from https://github.com/tikv/tikv/issues/8938, only focus on KvGet and KvBatchGet, so that the development can be easier.

You need to do the following things:

1. Add wait time and process time fields in the Get and BatchGet response in [kvproto](https://github.com/pingcap/kvproto).
2. Count the wait time and the process time in TiKV KvGet and KvBatchGet, and return these time in the response. 

## Score

- 600

## Mentor(s)

- @breeswish
- @zhongzc

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Rust
* Protobuf

**Comment by hi-rustin** [comment]
@Patrick0308  Please try again.

**Comment by YKG** [comment]
Hi @breeswish , I'd like to add a note here. For the sysbench oltp_update_index workload, the delta time starts from the network packet been received in TiKV and ends with the `request_handler` in `kv.rs::batch_commands()` for heavy load. Actually the delta time is the queueing time. I collected all the RPC timestamp both in TiDB and TiKV, and I got some interesting information, one of them is that for the `Get` commands, ~100% of the RPC lifetime spent in the queueing, and less than 1% time spent in TiKV processing.

I can upload the data I collected if you are interested, and I also have a plot for these duration comparison.

**Comment by breeswish** [comment]
@YKG  Great job! Your information is very valuable. We do not handle queue time (especially when it is batched in gRPC) well in this case. Maybe we can cover some easy problems first.  If you are interested in what we are doing, you can send the resume to breezewish@pingcap.com

/cc @zhongzc pay attention to the note here, if tracing does not cover the gRPC batch case.

**Comment by zhongzc** [comment]
@breeswish

For now, the tracing processing, says that an RPC's send time is when a request is passed to batch commands, not the real RPC send time. Similarly, the "receive time" of a request batched in batch commands is when the request begins to handle.

For the gRPC batch case, maybe gRPC lib should record the wanted information and pass them to the application via `RequestContext`.

**Comment by YKG** [comment]
Hi @breeswish @zhongzc , sorry for late feedback because get up late. I'm glad to receive the resume invititaion, I'll send it to you later today.

The attachment is the PPT for HPTC defense, The last two plots are for `BatchCommand::Get`.

[Latency Tracing for TiDB community.pptx](https://github.com/tikv/tikv/files/5676897/Latency.Tracing.for.TiDB.community.pptx)

Our workgroup slack channel is here: https://tidbcommunity.slack.com/archives/C01AW0Z9PLM

**Comment by YKG** [comment]
@zhongzc If my memory is correct, it's you who are working on TiKV opentracing support? While I'm working on tracing the latency during HPTC, I found you have a draft PR for TiKV tracing, I should have ask you for help to speed up, just too busy to to ask. Accoring to my investigation, opentracing normally requries the span starts and ends in the same stack frame, which is seems like not suitable for rust async, so I didn't follow the opentracing way, am I correct?

**Comment by zhongzc** [comment]
@YKG An async task contains a series of `poll` function calls. They won't overlap, and every call will stay in the single thread. You can trace async task by instrumenting the `poll` if you prefer tracing of thread-local flavor.

**Comment by YKG** [comment]
I also checked the netwrok latency by collecting the packets timestamp and compare to TiDB's and TiKV's, that is not a issue, the timestamp diff nomally less than 1ms even in a high RPC latency environment.

**Comment by YKG** [comment]
@zhongzc so if it's possible, could you please tell me how to starts a span in the `request_handler` and ends it in `response_retriever`? In my approach, I have `KV1` tracepoint(`kv1_tracer.push(id)`) in `request_handler` and a `KV2` tracepoint(`kv2_tracer.push(*id)`) in `response_retriver`, how can I starts a span at `KV1` and ends it at `KV2`?

**Comment by zhongzc** [comment]
@YKG I don't think there's another approach easier than your original way.

An intuitive alternative is to share a span with these two points, started by `KV1`, finished by `KV2`. Because the span is modified by two threads, `mutex` or `atomic` is needed.

If you are intended to use existing tracing frameworks, for most of them like opentracing, minitrace, you may need to transmit the tracer manually from the place where it is initialized to the place where it is finished. It means the channel type no long to be `(id, resp)`, instead it will be `(id, resp, tracer)`.

**Comment by YKG** [comment]
@zhongzc I agree with you that mutex or atomic do needed, but although these two places are in different `futures`, but they are not in the different `threads`, both are runing in the same thread.

Yes, I also guess the framewroks may need to use channels to finish this work. I did some compartion between `crossbeam`/`std::mpsc`/`flume`/`vector push`, those channels approach overhead is much bigger than `vec.push`.

**Comment by YKG** [comment]
Hi @breeswish , I sent the resume last week, but I didn't see any feedback, was there any problem?

**Comment by breeswish** [comment]
> Hi @breeswish , I sent the resume last week, but I didn't see any feedback, was there any problem?

Sorry! I didn't noticed the email. I have re-checked my inbox and found your email. I will take a look.

**Comment by sunxiaoguang** [comment]
Hi @breeswish , is this issue valid for other people to work on?

**Comment by zhongzc** [comment]
Let's get started with KvGet! @jackwener 

[ExecDetailsV2](https://tikv.github.io/doc/kvproto/kvrpcpb/struct.ExecDetailsV2.html) is now embedded in [GetResponse](https://tikv.github.io/doc/kvproto/kvrpcpb/struct.GetResponse.html), which contains statistical fields including
 - [ScanDetailV2](https://tikv.github.io/doc/kvproto/kvrpcpb/struct.ScanDetailV2.html) and
 - [TimeDetail](https://tikv.github.io/doc/kvproto/kvrpcpb/struct.TimeDetail.html)

These statistics need to be filled. The current work progress is as follows:
 - [x] The record for ScanDetailV2 has been done at https://github.com/tikv/tikv/pull/8814/files
 - [x] The record for [TimeDetail.kv_read_wall_time_ms](https://tikv.github.io/doc/kvproto/kvrpcpb/struct.TimeDetail.html#structfield.kv_read_wall_time_ms) has been done at https://github.com/tikv/tikv/pull/10343/files
 - [ ] [TimeDetail.process_wall_time_ms](https://tikv.github.io/doc/kvproto/kvrpcpb/struct.TimeDetail.html#structfield.process_wall_time_ms)
 - [ ] [TimeDetail.wait_wall_time_ms](https://tikv.github.io/doc/kvproto/kvrpcpb/struct.TimeDetail.html#structfield.wait_wall_time_ms)

To record `process_wall_time_ms` and `wait_wall_time_ms`, let's first figure out the lifetime of KvGet:
 1. GetRequest is received
 2. The request is put into the thread pool and waiting for processing
 3. The request is started to process and waiting for a prepared snapshot
 3. Fetch the associated value from the snapshot
 
Let's simply the above to 4 stages: **Begin** -> **Scheduled** -> **SnapshotReceived** -> **Finished**.

Look inside codebase:

### Begin
https://github.com/tikv/tikv/blob/12c9d659a28f97265768709b54833659d4127465/src/storage/mod.rs#L328-L332

### Scheduled
https://github.com/tikv/tikv/blob/12c9d659a28f97265768709b54833659d4127465/src/storage/mod.rs#L336-L350

### SnapshotReceived
https://github.com/tikv/tikv/blob/12c9d659a28f97265768709b54833659d4127465/src/storage/mod.rs#L366-L369

### Finished
https://github.com/tikv/tikv/blob/12c9d659a28f97265768709b54833659d4127465/src/storage/mod.rs#L387-L396

We treat the time duration
- from **Begin** to **Scheduled** as `schedule_wait_time`
- from **Scheduled** to **SnapshotReceived** as `snapshot_wait_time`
- from **Begin** to **SnapshotReceived** as `total_wait_time` i.e. `wait_wall_time_ms`
- from **SnapshotReceived** to **Finished** as `total_process_time`, i.e. `process_wall_time_ms`

Our goal is
> Count the wait time and the process time in TiKV KvGet and KvBatchGet, and return these time in the response.

Hope these are enough information for you, and welcome to ask for more!

**Comment by breeswish** [comment]
See future works here: https://github.com/tikv/tikv/issues/11525
