### ISSUE TITLE
Make slow log threshold configurable

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#8945]
## Description

Now TiKV prints Coprocessor slow log when it takes more than 1 second to process, which is not flexible enough. For example, in some cases the slow request only takes less than 1 second. 

You need to:

1. Add a configuration item `end_point_slow_log_threshold` in `server/config.rs`.
2. Output the slow log which is now printed in https://github.com/tikv/tikv/blob/master/src/coprocessor/tracker.rs#L218 based on this config item.

If https://github.com/tikv/tikv/issues/8944 is implemented, you need to add something similar to KvGet and KvBatchGet as well. The config can be `kv_operation_slow_log_threshold` in `server/config.rs` (200 points extra).

## Score

- 400

## Mentor(s)

- @breeswish
- @zhongzc

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Rust

**Comment by zhongzc** [comment]
cc @hi-rustin
