### ISSUE TITLE
Rolling upgrade from 2.1 or older version to newer version may break region replicas consistency

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#8967]
## Bug Report
Due to compatibility issues introduced in https://github.com/tikv/tikv/pull/3807, the new and old versions will behave differently for split operation. Therefore, during the upgrade process, when the leader of a region is of version 2.1 and the follower is version 3.0, if the region promotes learner after the split is initiated, the follower of version 3.0 will silently ignore the split operation. Thus, the follower's region epoch version will be smaller than the leader's region epoch version. When the leader transfers the leader to this follower, this new leader will always complain epoch not match because the epoch version is less than the epoch version stored by the PD. Eventually, the read, write, and scheduling requests of this region cannot succeed, and the region cannot provide services normally.

### Phenomenon:

- When rolling upgrade, the leader fails to transfer and can not provide service with the error of “get snapshot failed: EpochNotMatch”. 
- There are some regions always with pending peer

**Comment by zhangjinpeng1987** [comment]
@Connor1996 Please add the workaround

**Comment by Connor1996** [comment]
Workaround:
1. Disable PD schedule by setting all xxx-limit to 0
2. Confirm there is no schedule operation by `pd-ctl operator show`
3. Confirm no pending-peer by `pd-ctl region check pending-peer`
4. Wait 5 minutes (you can wait even longer to avoid extreme condition)
5. Do rolling upgrade
6. After finishing upgrading, enable PD schedule

**Comment by Connor1996** [comment]
Won't fix cause it's hard to relieve an already existed incompatibility problem. So please just use the workaround to avoid this case when doing a rolling upgrade.
