### ISSUE TITLE
copr: UTF8 functions should consider collation

### ISSUE THREAD

**Issue by andylokandy** [tikv/tikv#8986]
Some [UTF8 functions](https://github.com/tikv/tikv/blob/master/components/tidb_query_vec_expr/src/impl_string.rs) in TiKV coprocessor do not properly take collation into consideration. For example, [`instr_utf8`](https://github.com/tikv/tikv/blob/44f189c39460ccec75c3f0a5d0210c82eeddc6fa/components/tidb_query_vec_expr/src/impl_string.rs#L561) now compares two strings by their lowercase representation, which is not the right definition.

Related functions:
- [ ] ord (may need to split into ord_utf8)
- [ ] ~~instr_utf8~~
- [x] find_in_set
- [x] strcmp
- [ ]  ~~Locate2ArgsUTF8~~
- [ ] ~~Locate3ArgsUTF8~~

**Comment by andylokandy** [comment]
Useful reference: https://github.com/tikv/tikv/blob/308c641fce76c65313f9ffa491f0b4a5be8b1f70/components/tidb_query_vec_expr/src/impl_like.rs#L12

**Comment by TszKitLo40** [comment]
Can I try `strcmp` and `strcmp_utf8`?

**Comment by andylokandy** [comment]
@TszKitLo40 

> Can I try strcmp and strcmp_utf8? Is strcmp like the function in C++?

Yes, sure! You need to use a [collator](https://tikv.github.io/doc/tidb_query_datatype/codec/collation/trait.Collator.html) to compare strings [here](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/impl_string.rs#L684). In order to retrieve a collator, you need to expose the collator as a generic parameter like [this](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/impl_string.rs#L101). At last, the [function entrance](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/lib.rs#L589) needs to be replaced by a collation mapper like [this](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/lib.rs#L93) .

**Comment by TszKitLo40** [comment]
> @TszKitLo40
> 
> > Can I try strcmp and strcmp_utf8? Is strcmp like the function in C++?
> 
> Yes, sure! You need to use a [collator](https://tikv.github.io/doc/tidb_query_datatype/codec/collation/trait.Collator.html) to compare strings [here](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/impl_string.rs#L684). In order to retrieve a collator, you need to expose the collator as a generic parameter like [this](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/impl_string.rs#L101). At last, the [function entrance](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/lib.rs#L589) needs to be replaced by a collation mapper like [this](https://github.com/tikv/tikv/blob/515df8d552cce67111991fc6b205ec2905716c2b/components/tidb_query_expr/src/lib.rs#L93) .

Do you mean replace `strcmp` with `strcmp_utf8` or add add new function `strcmp_utf8`?

**Comment by andylokandy** [comment]
You don't have to. The collator itself can handle the charset difference.

**Comment by TszKitLo40** [comment]
I am pleased to implement the rest part.

**Comment by TszKitLo40** [comment]
For `find_in_set` and `ord`, should we use `collator` too?

**Comment by andylokandy** [comment]
I'm sure that find_in_set has to be collation-aware.

**Comment by TszKitLo40** [comment]
Should we need to consider `C::IS_CASE_INSENSITIVE` like `locate_2_args_utf8` and is the logic almost the same like `locate_2_args_utf8` ?

**Comment by andylokandy** [comment]
Changing `.position(|str_in_set| str_in_set == s)` to `.position(|str_in_set| C::sort_compare(str_in_set, s) == Ordering::Equal)` should be enough?

**Comment by TszKitLo40** [comment]
`C::sort_compare(str_in_set, s)` will have error, should we use `position(|str_in_set| C::sort_compare(str_in_set.as_bytes(), s.as_bytes()).unwrap() == Ordering::Equal` instead, but it seems that the test will fail.

**Comment by TszKitLo40** [comment]
I changed it to `let result = String::from_utf8_lossy(str_list)
        .split(',')
        .position(|str_in_set| C::sort_compare(str_in_set.as_bytes(), s).unwrap() == Ordering::Equal)
        .map(|p| p as i64 + 1)
        .or(Some(0));`, but it seems the test will fail.

**Comment by TszKitLo40** [comment]
I use `let result = String::from_utf8_lossy(str_list)
        .split(',')
        .position(|str_in_set| C::sort_compare(str_in_set.as_ref(), s).unwrap() == Ordering::Equal)
        .map(|p| p as i64 + 1)
        .or(Some(0));` but the test fill fail.

**Comment by andylokandy** [comment]
Do you mean the intergration test?

**Comment by TszKitLo40** [comment]
The `test_find_in_set`.

**Comment by andylokandy** [comment]
Do you know which case failed? And in addition, you can use `bstr` instead of `String::from_utf8_lossy`.

**Comment by TszKitLo40** [comment]
The first case `("foo", "foo,bar", Collation::Utf8Mb4Bin, 1)` failed, and the result is -1

**Comment by TszKitLo40** [comment]
Do you mean `bstr::{ByteSlice, ByteVec}`?

**Comment by TszKitLo40** [comment]
Should `ord` like `locate_2_args` which is split into `locate_2_args_utf8`?

**Comment by andylokandy** [comment]
> Should ord like locate_2_args which is split into locate_2_args_utf8?

Seems not necessary

**Comment by TszKitLo40** [comment]
> > Should ord like locate_2_args which is split into locate_2_args_utf8?
> 
> Seems not necessary

Also use `collator` to do that? But `ord` just decode and convert the arg to utf8 bytes, and iterate it reversely to get the result.

**Comment by TszKitLo40** [comment]
It seems that `bstr::decode_utf8` can't be replaced by `C::Charset::decode_one` directly, and the return value of `C::Charset::decode_one` is `Option<(Self::Char, usize)>`, how can we get the usize from it?
