### ISSUE TITLE
Add dynamic parameters to set the threshold of tikv's slow query

### ISSUE THREAD

**Issue by zhenjiaogao** [tikv/tikv#9001]
### Is your feature request related to a problem? Please describe:

By default, when the execution time of sql exceeds 1s, it will be recorded as sql-query in tikv log, and there is no parameter to define the threshold of sql-query.

### Describe the feature you'd like:
It is recommended to add a parameter to enable users to define the threshold of slow-query.

**Comment by breeswish** [comment]
Related: https://github.com/tikv/tikv/issues/8945

**Comment by breeswish** [comment]
https://github.com/tikv/tikv/pull/9061

Slow log config is implemented.
