### ISSUE TITLE
`make` doesn't run on NixOS

### ISSUE THREAD

**Issue by humancalico** [tikv/tikv#9015]
### What operating system and CPU are you using?

NixOS 20.09
### Steps to reproduce and what happened

On running make build on NixOS it fails with the following output
```
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
cargo build --no-default-features --features "jemalloc portable sse protobuf-codec test-engines-rocksdb"
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: /bin/bash: No such file or directory
make: *** [Makefile:147: build] Error 127
```

### Cause and possible fix
This happened because the Makefile runs it with the SHELL `/bin/bash`
https://github.com/tikv/tikv/blob/75f9982d57697b3743a39d60590c95cbdc0145db/Makefile#L34
but NixOS doesn't store it's packages in `/bin` instead they are stored in `/nix/store` so changing it to `/nix/store/15ixk6qgzm66l6xvsb3yjv57104gvfxl-system-path/bin/bash` worked. I don't know much about `Makefile`s but checking the path of bash with something like `whereis bash` and then using it's output should work. wdyt?

**Comment by iosmanthus** [comment]
@humancalico FYI, https://github.com/iosmanthus/tikv-flake contains a shell env for building TiKV.

**Comment by humancalico** [comment]
@iosmanthus This is great. Thanks!
