### ISSUE TITLE
does tikv 4.1.0-alpha  compatible 4.0.x ?

### ISSUE THREAD

**Issue by lddlww** [tikv/tikv#9017]
![image](https://user-images.githubusercontent.com/27006237/98807980-71cd4f00-2456-11eb-8344-c68c4465b456.png)

i download wrong tikv version（already build in production），which contains the follow info：
```
TiKV 
Release Version:   4.1.0-alpha
Git Commit Hash:   36dab75da84ec57374d364a4a4af9146ec31df07
Git Commit Branch: master
UTC Build Time:    2020-02-17 01:39:18
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```

i wonder to know ，when i use ```tiup backup``` to backup this version（```4.1.0-alpha```），then restore to tikv ```4.0.x```，does it work and compatible？

**Comment by andylokandy** [comment]
I think it's not.

**Comment by lddlww** [comment]
how can i do？

**Comment by andylokandy** [comment]
Are you using TiDB or plain TiKV?

**Comment by lddlww** [comment]
tidb

**Comment by andylokandy** [comment]
you can use [dumpling](https://github.com/pingcap/dumpling) to dump the data and import it into other cluster.

**Comment by lddlww** [comment]
it's more spent time

**Comment by andylokandy** [comment]
`tiup backup` is not compatible between these two versions, so dumpling is the most viable way I can see.

**Comment by lddlww** [comment]
ok，thanks for patience
