### ISSUE TITLE
PD worker is blocked by `get_region_approximate_size`

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#9024]
## Bug Report

PD worker is blocked by `get_region_approximate_size` for a long time if there are some huge regions. We have met a cluster with a few huge regions (around 50~60 GB), the cluster is not functioning normally to PD schedule (add peers/transfer leader) due to PD worker is blocked.

### What version of TiKV are you using?

v4.0.7

Flamegraph

https://gist.github.com/overvenus/87185107dc291d397021706b013d5ad4

**Comment by Connor1996** [comment]
I have encountered it before. Maybe it's not blocked totally, but just costs too much time on every `GetTableProperty`? With this, you can see that there are a lot of pending tasks in pd worker from metrics.

**Comment by Little-Wallace** [comment]
OK. I will move it to another thread.

**Comment by hicqu** [comment]
Is it better to change the property block from `4k` to `512k`?

**Comment by Connor1996** [comment]
> Is it better to change the property block from `4k` to `512k`?

Seems the metadata blocks are not partitioned(not for sure), so it would not follow the block size. And I don't think it's the reason for this problem. I suspect it's due to some slow path from the kernel level.

**Comment by Little-Wallace** [comment]
This problem has been solved by #9081
