### ISSUE TITLE
Peer reject to transfer leader because of pending conf change

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/tikv#9041]
### What version of TiKV are you using?

master: 33daf202a99d381b8b2526d391732ae94febecc1

### Steps to reproduce

Run go-tpc and tiup reload some config. Then I cancel this  rolling update operation by mistake. Then some peers keep pending conf change and reject to transfer leader.

```
[2020/11/13 15:11:03.120 +08:00] [INFO] [peer.rs:2741] ["reject to transfer leader"] [last_index=147624] [index=139752] [reason="pending conf change"] [to="id: 6695 store_id: 1"] [peer_
id=6694] [region_id=6692]
```

### What did happened?

Leaders of TiKV can not balance.
![image](https://user-images.githubusercontent.com/16376959/99040635-70ba3000-25c4-11eb-8f4c-3dce921f9dbc.png)

**Comment by BusyJay** [comment]
Close due to stale.
