### ISSUE TITLE
batch_get doesn't return all results when encountering a memory lock

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#9069]
### What version of TiKV are you using?

Master

### What did happened?

Here we check the lock table and when we meet the first memory lock, we return it back to the client: https://github.com/tikv/tikv/blob/f5409492a862e6ead06b2cbf4b7818fd6dc655e1/src/storage/mod.rs#L493

However, TiDB incrementally gets the locked keys if some keys are locked: https://github.com/pingcap/tidb/blob/aa9f7584f8fbcdb1dec35e3fa520224825000112/store/tikv/snapshot.go#L339

The behavior requires TiKV to return all existing KV pairs instead of returning the first lock.

**Comment by sticnarf** [comment]
## Solution 1

Solve it at TiKV side. We keep the semantics of BatchGet. Check all keys in the lock table and query all the unlocked keys. However, there is some trouble to support it in follower read. We need to modify the protocol  to support checking all keys and returning all the locks in the lock table.

- Advantage: Consistent semantics
- Disadvantage: Lots of changes.

## Solution 2

Solve it at TiDB side. Handle async commit locks specially in BatchGet. If the returned lock is an async-commit lock, do not change pending keys and resend the original BatchGet request directly.

- Advantage: Change is small.
- Disadvantage: Increase a special case in the interface.

**Comment by cfzjywxk** [comment]
Maybe solution 2 is better to avoid much extra test works since we already have much work to do?

**Comment by sticnarf** [comment]
Closed by https://github.com/tikv/tikv/pull/9077 and https://github.com/pingcap/tidb/pull/21157
