### ISSUE TITLE
TiKV panic because of ingest failed by importer.

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/tikv#9099]
### What version of TiKV are you using?

master: 2b983187b8108770f06a684dc5a32629314bf1a8
This bug may be related to https://github.com/tikv/tikv/pull/8869

### Steps to reproduce

Enable encryption and import 14K warehouse tpcc data to TiDB. Then tikv was killed by oom-killer. TiKV failed to restart because of ingesting.

### What did you expect?
I think tikv did not remove the ingest file from key-manager correctly.
![image](https://user-images.githubusercontent.com/16376959/100086255-22d8de00-2e88-11eb-8e27-e9e5cc409aad.png)
![image](https://user-images.githubusercontent.com/16376959/100086349-4439ca00-2e88-11eb-99fd-cae6ac59a690.png)

### What did happened?
![image](https://user-images.githubusercontent.com/16376959/100086160-f755f380-2e87-11eb-9568-d879d3ec1288.png)

**Comment by yiwu-arbug** [comment]
There are recent changes in importer that could be related: #8985 #9000

**Comment by yiwu-arbug** [comment]
Do we still have TiKV log? If so, we can check `KeyManager`'s operations on the file.

**Comment by yiwu-arbug** [comment]
This one should have been fixed by #9105. If not, please reopen.
