### ISSUE TITLE
New Row Format column_id representation doesn't match the design document.

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#9124]
## Bug Report

According the document of the new row format, the row stores a series of  column_ids. When some of the column_ids is large enough, or the value length is large enough, the value will be marked as a big value, otherwise it's small. For small values, each column_id is represented by 1 byte (max 255); for big values,  it's represented by 2 bytes (max 65535).

However in the code, the function that verifies the column_id writes:

https://github.com/tikv/tikv/blob/3d6dbd7d5ecbc46cbb9962d3864b673ef9843e17/components/tidb_query_datatype/src/codec/row/v2/row_slice.rs#L112-L120

And also, when searching column_ids from the value:

(In fn `search_in_non_null_ids`)
https://github.com/tikv/tikv/blob/3d6dbd7d5ecbc46cbb9962d3864b673ef9843e17/components/tidb_query_datatype/src/codec/row/v2/row_slice.rs#L71

(In fn `search_in_null_ids`)
https://github.com/tikv/tikv/blob/3d6dbd7d5ecbc46cbb9962d3864b673ef9843e17/components/tidb_query_datatype/src/codec/row/v2/row_slice.rs#L107

It looks like everything is using u32 for big values. It doesn't match the design document.

By the way, we also lacks of tests that allocates column_id over 65536.

cc @cfzjywxk @breeswish

**Comment by MyonKeminta** [comment]
Sorry to disturb. What I found is an old version of document. In the final design document it's indeed defined as 4 bytes, and the implementation is also 4 bytes.

**Comment by breeswish** [comment]
The new document is not public, maybe we should update https://github.com/pingcap/tidb/blob/master/docs/design/2018-07-19-row-format.md ?

**Comment by MyonKeminta** [comment]
@breeswish Is that document still up-to-date enough? If so, I think it should be updated.

**Comment by breeswish** [comment]
@coocood PTAL whether we should update our RFC to refine the actual implementation, thanks!

**Comment by coocood** [comment]
@MyonKeminta 
The doc is consistent with the implementation.
```
If the row is big, each column ID takes 4 bytes, otherwise the column ID takes 1 byte. The IDs array is sorted in an ascending order.
```

**Comment by MyonKeminta** [comment]
Ok. Thanks!
