### ISSUE TITLE
key not in region use java sdk 

### ISSUE THREAD

**Issue by yinghonghui** [tikv/tikv#9157]
## Question

I use java sdk to set value in tikv.but pd response Incorrect region info to a key.so report “key not in region” exception when executing set operation.

**Comment by andylokandy** [comment]
Thanks for reporting. Seems that you sent requests to the wrong tikv store. Do you have any detailed information about the platform you used and the process or code to reproduce that.

**Comment by yinghonghui** [comment]
> Thanks for reporting. Seems that you've sent requests to the wrong tikv store. Do you have any detailed information about the platform you used and the process or code to reproduce that.

tidb集群版本为4.0， tikv java client 3.0报 key not in region 异常，看到这个异常是tidb2.x里已经修复的bug，不知道是什么条件触发了这个异常。 也用golang的客户端 client-go测试过， 并未有这个异常发生。写入的key的特征是前缀一样的key。
现象：
pd返回key相关region 92， 用./pd-ctl check region的一致性，没有异常。日志里看到有region92的分裂和合并。
![image](https://user-images.githubusercontent.com/18246565/100833560-2b8f6c80-34a5-11eb-89f9-95611f64de63.png)

以下是客户端代码：
![image](https://user-images.githubusercontent.com/18246565/100833571-35b16b00-34a5-11eb-9719-ebdb50d59f23.png)

服务端的grafana有异常：
![image](https://user-images.githubusercontent.com/18246565/100833595-3f3ad300-34a5-11eb-9340-8d0067108c26.png)

以下是服务端的错误日志
![image](https://user-images.githubusercontent.com/18246565/100833619-4a8dfe80-34a5-11eb-9f75-0078306b10ea.png)

pd返回region92的startkey比endkey长很多
![image](https://user-images.githubusercontent.com/18246565/100833633-537ed000-34a5-11eb-85f2-644405670da1.png)

一致性check没问题
![image](https://user-images.githubusercontent.com/18246565/100833655-5da0ce80-34a5-11eb-949f-e253049b3260.png)
![image](https://user-images.githubusercontent.com/18246565/100833666-62fe1900-34a5-11eb-9202-9183016f8391.png)

**Comment by andylokandy** [comment]
If you confirmed that go-client works, it's not likely tikv that cause the problem. You can submit an issue in java client repo(https://github.com/tikv/client-java).

**Comment by yinghonghui** [comment]
> If you've confirmed that go-client works, it's unlikely that tikv causes the problem. You can submit an issue in java client repo (https://github.com/tikv/client-java).

I had submit an issue in java client repo (https://github.com/tikv/client-java).But no one responds.
https://github.com/tikv/client-java/issues/101

**Comment by andylokandy** [comment]
You can join transation slack channel (https://slack.tidb.io/invite?team=tikv-wg&channel=sig-transaction&ref=community-sig) to contact the author directly.
