### ISSUE TITLE
Slot collision on latch with and (&) operator

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#9162]
## Bug Report

Using and (&) operator to calculate slots index can lead to severe collision.
https://github.com/tikv/tikv/blob/9b8785a42f6e03621c0d0ce66799761b3e00f9cc/src/storage/txn/latch.rs#L212-L214

See more: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cdfa59d515af83e611e9492d5da3ecac

### What version of TiKV are you using?

master

**Comment by Little-Wallace** [comment]
TiKV will use a power of two as the real capacity of latches instead of the value configure by user. See  https://github.com/tikv/tikv/blob/master/src/storage/txn/latch.rs#L136

**Comment by youjiali1995** [comment]
Latch size is rounded up to the power of 2. & equals % in this case.
