### ISSUE TITLE
Support build on Apple Silicon/M1

### ISSUE THREAD

**Issue by Fullstop000** [tikv/tikv#9192]
## Feature Request

Support native build on Apple Silicon/M1

And I'm currently working on this. Here are some complete tasks and related issues:

- [x] `tame-oauth` : 0.4.2 -> 0.4.5
   - [x] `ring`: 0.16.12 -> 0.16.19 https://github.com/briansmith/ring/issues/1063
   - [x] `openssl-src`: 111.10.2+1.1.1g -> 111.12.0+1.1.1h
- [ ] `tikv/rust-rocksdb` build fail on Apple Silicon  https://github.com/tikv/rust-rocksdb/issues/576
- [ ] Rocksdb build fail on Apple Silicon https://github.com/rust-rocksdb/rust-rocksdb/issues/482
- [ ] TBD

**Comment by Fullstop000** [comment]
It's exciting that this is done by @sticnarf on his m1 machine!!! Please wait for his PRs.

**Comment by sticnarf** [comment]
## Prerequisites
- [ ] https://github.com/tikv/rocksdb/pull/219
- [ ] https://github.com/tikv/titan/pull/199
- Upgrade bindgen version to `0.56`
  - tikv/grpc-rs
  - tikv/rust-rocksdb
  - YangKeao/rust-papi (optional)
- Patch tikv/rust-rocksdb
- Fix link_name of `statfs` and `fstatfs` in rust-lang/libc
