### ISSUE TITLE
tipocket list_append fails on follower read and async commit

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#9208]
### What version of TiKV are you using?

Nightly

### Steps to reproduce

Use https://github.com/pingcap/tipocket/pull/331. Run `./bin/append -txn-mode=optimistic -replica-read=follower -nemesis=shuffle-leader-scheduler,shuffle-region-scheduler,shuffle-region-scheduler`.

Log archive: [append-failure-follower-read.tar.gz](https://github.com/tikv/tikv/files/5664896/append-failure-follower-read.tar.gz)

**Comment by sticnarf** [comment]
Here is another failure with more logs, debug tikv branch: https://github.com/tikv/tikv/tree/16bfed453a6ff674bd4aba21c0e5173958323a9e

[append-failure-3.tar.gz](https://github.com/tikv/tikv/files/5672370/append-failure-3.tar.gz)

**Comment by sticnarf** [comment]
I find this test also fails on master **even without async commit**.
cc @5kbpers

**Comment by youjiali1995** [comment]
> I find this test also fails on master **even without async commit**.
> cc @5kbpers

How about release-4.0?

**Comment by sticnarf** [comment]
> > I find this test also fails on master **even without async commit**.
> > cc @5kbpers
> 
> How about release-4.0?

It doesn't fail on release-4.0.
