### ISSUE TITLE
TiKV's distributed GC may keep scanning and consuming CPU when there's very low write flow

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#9216]
## Bug Report

This is an old problem that has been recorded in our internal jira. We now also record it on github.

### What version of TiKV are you using?

4.0.x, 3.0.x

### What operating system and CPU are you using?

-

### Steps to reproduce

1. Load a lot of data to the cluster
2. Do some update to the data, but very rarely.
3. In a little chance the problem may happen: there may be a range of regions that cannot skip GC by checking `need_gc`.

### What did you expect?

Most of the regions can skip GC since there are little writing flow

### What did happened?

GC may be unable to skip regions in a large range, and keeps scanning and consuming CPU but makes nonsense.

The root cause is that, in this situation, there may be an SST file that spans a very large range staying in a upper layer. It's not compacted to lower layer for a long time due to low write flow. If there is a key that has more than 100 versions in the SST, then it will be recorded into the `max_row_versions` field in the SST file's properties. Therefore, all regions that's covered by the SST file will get this value, causing the GC not being skipped.

**Comment by hicqu** [comment]
Seems the only place that too many versions for one user key hurts performance is `MvccReader::get_txn_commit_record`. So how about not consider `max_row_versions` in `check_need_gc`, but send a GC task if `MvccReader::get_txn_commit_record` found too many versions for a key?

**Comment by youjiali1995** [comment]
Fixed by https://github.com/tikv/tikv/pull/9703
