### ISSUE TITLE
server::status_server::tests::test_change_log_level failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9221]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37506/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37506/display/redirect</a>

**Comment by BusyJay** [comment]
There is only one fail step that is timeout. And the timeout case is not what title says. Is the provided link correct?

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37567/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37567/display/redirect</a>

**Comment by KivenChen** [comment]
> There is only one fail step that is timeout. And the timeout case is not what title says. Is the provided link correct?

Thanks for your feedback. This issue was created as part of the CI service that's being tested.
We are looking into this issue. Another case failure is raised with the same attribution, could you pls check if there's any more problem.
[https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37567/display/redirect](https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37567/display/redirect)

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37571/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37571/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37603/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37603/display/redirect</a>
