### ISSUE TITLE
storage::test_raft_storage::test_auto_gc failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9230]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37168/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37168/display/redirect</a>

**Comment by sticnarf** [comment]
Duplicated by #6400

**Comment by hicqu** [comment]
Closed by https://github.com/tikv/tikv/pull/9386.
