### ISSUE TITLE
raftstore::test_merge::test_request_snapshot_after_propose_merge failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9231]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37640/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37640/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37950/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37950/display/redirect</a>

**Comment by sticnarf** [comment]
Duplicated by #8517

**Comment by hicqu** [comment]
Closed by #9379 .
