### ISSUE TITLE
server::kv_service::test_split_region failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9233]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37646/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37646/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37683/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37683/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37899/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37899/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37903/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37903/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37944/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37944/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37987/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37987/display/redirect</a>

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
