### ISSUE TITLE
cases::test_cmd_epoch_checker::test_accept_proposal_during_conf_change failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9236]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37666/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37666/display/redirect</a>

**Comment by andylokandy** [comment]
It is an unstable test. Did it pass eventually?

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
