### ISSUE TITLE
FAIL: /home/jenkins/agent/workspace/tikv_ghpr_integration_ddl_test/go/src/github.com/pingcap/tidb-test/_vendor/pkg/mod/github.com/pingcap/tidb@v0.0.0-20190520045437-2d70e4da27d7/cmd/ddltest/index_test.go:127: TestDDLSuite.TestIndex failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9251]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_integration_ddl_test/11022/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_integration_ddl_test/11022/display/redirect</a>

**Comment by BusyJay** [comment]
Such failures should probably not be related to TiKV.
