### ISSUE TITLE
server::status_server::tests::test_change_log_level failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9258]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37603/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37603/display/redirect</a>

**Comment by KivenChen** [comment]
Yet another case failure: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/38023/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/38023/display/redirect</a>

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
