### ISSUE TITLE
cases::test_early_apply::test_multi_early_apply failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9263]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37907/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37907/display/redirect</a>

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
