### ISSUE TITLE
cases::test_conf_change::test_stale_peer_cache failed

### ISSUE THREAD

**Issue by KivenChen** [tikv/tikv#9264]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37979/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37979/display/redirect</a>

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
