### ISSUE TITLE
Need API reference for TiKV.

### ISSUE THREAD

**Issue by weidagang** [tikv/tikv#933]
Please answer these questions before submitting your issue. Thanks!
1. What version of Rust are you using (`rustc --version`)?
2. What operating system and processor architecture are you using?
3. What did you do?
   If possible, provide a recipe for reproducing the error.
   A complete runnable program is good.
4. What did you expect to see?

TiKV API reference.
1. What did you see instead?

None.

**Comment by ngaut** [comment]
Currently we just have a go client to access TiKV which is embedded is TiDB. I built a quick demo by using transaction API. reference: https://gist.github.com/ngaut/90039802ba81ebde4c6135ea1ecb7b55
You may need to change the address of Placement Driver to point to your Placement Driver.

You can also find the implementation of go client driver in case you want to build driver in other languages. Please see https://github.com/pingcap/tidb/tree/master/store/tikv

**Comment by doublex** [comment]
+1
The TKIV database looks very promising.
Would be nice to have:
a) Some information about the current status + a small roadmap
b) Either a RESTful interface, or a C driver (could be used by many other languages) or at least some information how to access the k/v-database.

**Comment by ngaut** [comment]
Hi, doublex:
Thanks for your advices, The better way would be supporting RESTful API. We will support it later.

**Comment by doublex** [comment]
Are there any plans to create a C/C++ client and/or a RESTful API?

**Comment by amirouche** [comment]
There is [roadmap](https://github.com/pingcap/tikv/issues/933)

**Comment by rohitjoshi** [comment]
ideally, if TiKV support `Redis` protocol, we can leverage existing Redis clients in various languages.

**Comment by Hoverbear** [comment]
@rohitjoshi You may be interested in https://github.com/yongman/tidis

**Comment by ZhangHanDong** [comment]
Need RESTful API

**Comment by Hoverbear** [comment]
You can track work on a Rust client here: https://github.com/tikv/client-rust

Currently I am not aware of a RESTful API being planned.

**Comment by ZhangHanDong** [comment]
@Hoverbear OK,thanks

**Comment by Hoverbear** [comment]
Hi! https://github.com/tikv/client-rust is a good reference now, you can generate the docs with `cargo doc --open`. We're also working on documenting our code a lot more.

We do have an issue to create a full reference for our protobufs, you can track that here if it's relevant. #4262 

I'm going to close this issue as it's quite old and very broad.
