### ISSUE TITLE
Stale read when using read_index request

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#9351]
## Bug Report

Similar to #9208, ReadIndex request can be given a stale index after just transferring leader. The API doesn't seem to be used anymore, so the best way to solve it is removing the API completely.

@NingLin-P @gengliqi PTAL

/cc @solotzg, just make sure tiflash will not use the API in the future.

**Comment by solotzg** [comment]
since 4.0.8, tiflash won't use ReadIndex to get read-index from leader directly.

**Comment by BusyJay** [comment]
I remember there is a solution to use proxy to do reading across DC, which also use read index. @hicqu Is it still a valid solution? Is the stale read proposal a good alternative to it?

**Comment by hicqu** [comment]
@BusyJay that solution is paused and I think the stale read proposal is more useful than that.

Is it necessary to fix the bug for `TiFlash ^4.0.7`? If so we need to fix it, or we can remove the API directly.

**Comment by BusyJay** [comment]
The only way to fix for them is using a hotfix. I suggest to ask them to upgrade to v4.0.9 instead.

**Comment by hicqu** [comment]
Can it be closed now?

**Comment by BusyJay** [comment]
Why? The API still exists and it can return wrong result.
