### ISSUE TITLE
TiKV's "read flow" statistics are inconsistent with "store read rate" statistics of PD

### ISSUE THREAD

**Issue by jiyingtk** [tikv/tikv#9391]
### What version of TiKV are you using?

TiKV 
Release Version:   4.1.0-alpha
Edition:           Community
Git Commit Hash:   3a02e74293b1a47ed03ec26d47cc31e9eafea673
Git Commit Branch: master
UTC Build Time:    2020-12-26 12:16:11
Rust Version:      rustc 1.49.0-nightly (b1496c6e6 2020-10-18)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb
Profile:           release

### Steps to reproduce

Using sysbench to load table with large row sizes:
CREATE TABLE `sbtest1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `k` int(11) NOT NULL DEFAULT 0,
  `c` varchar(6342) NOT NULL DEFAULT '',
  `pad` char(8) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `k_1` (`k`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1029168;

Then execute random point get:
SELECT * FROM sbtest1  WHERE id = ?;

### What did happened?

It is found that PD's "store read rate" statistics are inconsistent with TiKV's "read flow" statistics: 
![image](https://user-images.githubusercontent.com/22238878/103327396-57dfde00-4a8f-11eb-9fd7-a0c0c62b2c9c.png)
![image](https://user-images.githubusercontent.com/22238878/103329596-4bac4e80-4a98-11eb-8b7b-4559f301b1f7.png)
The problem seems to be that half of the keys are not included (Since gRPC message count is half of the read keys.)
![image](https://user-images.githubusercontent.com/22238878/103329671-bbbad480-4a98-11eb-8c34-0bb3ec992021.png)

**Comment by hicqu** [comment]
It's expected because `Keys flow` in `RocksDB-kv` contains all CFs. Generally a kv_get command will access `write` CF and `default` CF one time. So It's about double of `kv_get` command count.
