### ISSUE TITLE
Security check doesn't work in MacOS

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#9411]
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

MacOS

### Steps to reproduce

```shell
make dev
```

### What did happened?

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Security check passed.
```

Clearly the grep of the security check does not work in MacOS. And it correctly reports security check pass incorrectly as well.

**Comment by skyzh** [comment]
@gregwebs is already working on this in #9377
