### ISSUE TITLE
Can tikv reduce read consistency

### ISSUE THREAD

**Issue by slow-zhang** [tikv/tikv#9416]
## Question
I want to ask if there are any parameters in tikv that can adjust the read consistency?
Our current scenario does not require linear consistency, we want to improve read performance.

My idea is to get a read bypass the raft directly read rocksdb.

I use raw kv API in a tikv+pd system.

**Comment by slow-zhang** [comment]
@sre-bot

**Comment by yiwu-arbug** [comment]
TiKV provides snapshot isolation, and the consistency level is not changeable. AFAIK it utilize lease read so only a small number of read requests has to go through raft. Hope that answers your question.

**Comment by slow-zhang** [comment]
Thanks, this is very helpful.
