### ISSUE TITLE
raftstore: the invalid read delegates in local reader may not be removed forever

### ISSUE THREAD

**Issue by NingLin-P** [tikv/tikv#9469]
## Bug Report

Although https://github.com/tikv/tikv/pull/4765 introduce the `invalid` flag to remove the invalid `ReadDelegate`s on `LocalReader`, but the flag only be checked when handling a request to the `ReadDelegate`, if the `ReadDelegate` is marked as invalid and no incoming request to it, the `ReadDelegate` not be removed and consuming memory.

Although `mem::size_of::<ReadDelegate>()` is 122 bytes, but if this case happened the `ReadDelegate` will not be removed forever, and the memory occupied by these invalid `ReadDelegate` will only increase not decrease as TiKV running.

**Comment by NingLin-P** [comment]
PTAL @hicqu @BusyJay

**Comment by BusyJay** [comment]
Perhaps it can also use `LruCache` instead of `HashMap` to maintain a reasonable size.

**Comment by NingLin-P** [comment]
> Perhaps it can also use `LruCache` instead of `HashMap` to maintain a reasonable size.

`LruCache` only remove one item each time when its capacity is full.  As TiKV run long enough, the capacity we set to `LruCache` will full and after that it may bring extract cost when handling request for a delegate not in the cache.

I think it may better to keep an unlimited `HashMap` and when we need insert new delegate to `LocalReader`, check `delegates.len() > store_meta.readers.len() * 1.5` then remove all `invalid` delegates if it is true.

**Comment by BusyJay** [comment]
What's the extract cost comparing to a `HashMap` and a for loop?

**Comment by NingLin-P** [comment]
A `LruCache`'s capacity is limited, after it is full, every `insert` comes with a `remove`. With the approach mentioned above, we only need to clear invalid `delegate` when we know there has a large amount of invalid `delegate`, it should not be frequent and will be efficient, also prevent the `HashMap` grow unlimitedly.

**Comment by BusyJay** [comment]
The usage in TiKV usually maintains `LruCache`'s capacity the same as region count. A remove is an `O(1)` operation that only takes several nanoseconds. Removal occurs only when capacity is full and new delegate is inserted. However the time of looping over a HashMap is undetermined. If the count of hashmap exceeds 100000, the time probably can be tens or hundreds of millis.
