### ISSUE TITLE
engine_traits: merge Mutable trait with WriteBatch

### ISSUE THREAD

**Issue by brson** [tikv/tikv#9481]
This trait has drastically changed over time and now is just a bunch of WriteBatch-specific methods. Rename `SyncMutable` to `Mutable`.

cc https://github.com/tikv/tikv/issues/6402

**Comment by brson** [comment]
It also _might_ be worth keeping the Mutable trait, with just the mutation methods that SyncMutable has, if just for the aesthetic similarity between the two.

**Comment by saresend** [comment]
Would be interested to take a look if this is available!

**Comment by brson** [comment]
@saresend yes please. For now I'd suggest moving all the write-batch specific methods into WriteBatch while leaving the Mutable trait there, mirroring the SyncMutable trait.

I'm still unsure about what to do with the Mutable/SyncMutable traits.

**Comment by hi-rustin** [comment]
@saresend Are you still doing it? I'd like to get it done.

**Comment by brson** [comment]
Go for it @hi-rustin

**Comment by brson** [comment]
Thanks @hi-rustin!
