### ISSUE TITLE
Follower read statistics should also be considered in PD scheduling

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#9518]
## Feature Request

TiKV reports read statistics by region heartbeat, which is only reported by leader. After introducing replica reads, read statistics in replica can't be reported to PD in current mechanism, so workload can be imbalanced. We can decouple the statistics report from region heartbeat by using a separate message, so that every replica can report read flows in need. This can cause triple pressure on PD, we can filter some by using a water mark that only significant flows will be reported.

/cc @NingLin-P @nolouch

**Comment by nolouch** [comment]
Yes!! we need to consider the follower read. moreover, the tiflash may also need to do that(https://github.com/tikv/pd/issues/3261).

**Comment by nolouch** [comment]
closed by https://github.com/tikv/pd/pull/3681
