### ISSUE TITLE
BR will lead to the emergence of big regions with version v4.0.9

### ISSUE THREAD

**Issue by shuijing198799** [tikv/tikv#9520]
### What version of TiKV are you using?

TiKV
```
TiKV 
Release Version:   4.0.9
Edition:           Community
Git Commit Hash:   18dec72b12eafdc40a463eee8f6c32594ee4a9ff
Git Commit Branch: heads/refs/tags/v4.0.9
UTC Build Time:    2020-12-21 02:52:25
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec
Profile:           dist_release
```
BR
```
Release Version: v4.0.9
Git Commit Hash: 804aa908719748888010edaa944757b82f99f4df
Git Branch: heads/refs/tags/v4.0.9
Go Version: go1.13
UTC Build Time: 2020-12-19 04:53:25
Race Enabled: false
```
### Steps to reproduce

Prepare some data to the tidb cluster
use BR to backup
### What did you expect?
tikv region will keep in a stable status, and use limited memory
### What did happened?
region decrease dramatically and tikv OOM

When the backup started, the region dropped from 3K to close to 1K and the region became larger. Lead to tikv-2 OOM
tikv configuration 1c 3.75G mem 100G cloud-ssd
like shown in the next picture
![2021-01-18 20-32-22 的屏幕截图](https://user-images.githubusercontent.com/30903849/104916186-acaab080-59cc-11eb-9b12-7c446533e6ea.png)

**Comment by overvenus** [comment]
This is caused by missing region approximate size/keys after restoration, it is resolved by https://github.com/pingcap/br/pull/702 .

**Comment by shuijing198799** [comment]
with PR https://github.com/pingcap/br/pull/702 the region decrease is imporve and momory used like below
![image](https://user-images.githubusercontent.com/30903849/105335258-cd644780-5c12-11eb-8087-de85f962f69b.png)
