### ISSUE TITLE
Resolved TS is not updated with async commit transactions

### ISSUE THREAD

**Issue by sticnarf** [tikv/tikv#9523]
### What version of TiKV are you using?

Master (35c66d38ff8180f3652643e35575590d9ab57fc1)

### Steps to reproduce

Enable failpoints in TiDB (with unmerged https://github.com/pingcap/tidb/pull/22431):

```
github.com/pingcap/tidb/store/tikv/asyncCommitDoNothing=50%return
github.com/pingcap/tidb/store/tikv/runTTLManager=return
github.com/pingcap/tidb/store/tikv/shortPessimisticLockTTL=return
github.com/pingcap/tidb/store/tikv/twoPCShortLockTTL=return
```

Set the interval of updating PD physical TS to 2s.

Run tipocket/pbank with async commit and 1PC enabled:

```
./pbank -case=multi_bank -prepare-sql='set global tidb_enable_async_commit = 1;set global tidb_enable_1pc = 1;'
```

### What did you expect?

CDC works well.

### What did happened?

From the monitor, we see some TiKV failed to update the resolved TS, so CDC didn't work.

![image](https://user-images.githubusercontent.com/17217495/105005435-4d05e100-5a70-11eb-8199-ff910bbf87de.png)
![image](https://user-images.githubusercontent.com/17217495/105005468-5727df80-5a70-11eb-802a-81fa0e843cd9.png)

**Comment by sticnarf** [comment]
cc @MyonKeminta @youjiali1995

**Comment by sticnarf** [comment]
When doing an unprotected rollback and there is already a write record with the same commit TS, we don't write any write record:
https://github.com/tikv/tikv/blob/7b057aa9bdc0b1c18d4d8a90fd731f461105e62e/src/storage/mvcc/txn.rs#L35

And CDC now only untracks locks according to writes.

**Comment by youjiali1995** [comment]
Good catch! Can CDC untrack locks according to deleting locks too? I'm afraid the assumption that every lock deletion has a corresponding write can't hold. @overvenus

**Comment by sticnarf** [comment]
> Good catch! Can CDC untrack locks according to deleting locks too? I'm afraid the assumption that every lock deletion has a corresponding write can't hold. @overvenus

I tried but found it not so easy. The locks are managed by start_ts. However, when deleting a lock, we have no information about the deleted lock. So we cannot find the lock by start_ts and untrack it.

**Comment by MyonKeminta** [comment]
cc @5kbpers

**Comment by sticnarf** [comment]
I talked with @5kbpers and conclude there are two solutions.

1. As a simple fix for this issue, we can remove the optimization. Always write an overlapped rollback no matter if it is protected. Then, CDC can track such a rollback.

2. If we do not want such a constraint of transactions, we can add another data structure to the resolver to track locks by key. Then, we can let the resolver find the key first, then remove the start_ts from the heap. In this solution, we can track locks through lock cf applies.
