### ISSUE TITLE
TiKV reported memory is wrong

### ISSUE THREAD

**Issue by breeswish** [tikv/tikv#9532]
### What version of TiKV are you using?

v4.0.9

### What operating system and CPU are you using?

CentOS + tidb-operator.

### Steps to reproduce

Open TiDB Dashboard.

### What did you expect?

Memory usage should be <= 100%.

### What did happened?

We expect memory usage > 100%.

![image](https://user-images.githubusercontent.com/1916485/105173986-cd097500-5b5c-11eb-8dc9-edd70f912527.png)

### Cause

In this [PR](https://github.com/tikv/tikv/pull/7074), a container memory quota is returned in the memory info, instead of a system memory capacity.

**Comment by breeswish** [comment]
@zhongzc PTAL

**Comment by breeswish** [comment]
Additionally it might be better that we can display a container usage / capacity in this page. @crazycs520 What do you think

**Comment by zhongzc** [comment]
I will try to fix it. Just make memory usage cgroup-aware.

**Comment by breeswish** [comment]
@zhongzc I would recommend two steps:

Step1. Display host memory capacity as a hot fix. Only 1 LOC change.
Step2. Change TiDB, TiKV and TiFlash, to report cgroup-aware memory, CPU and disk. This might be a big project..

**Comment by zhongzc** [comment]
### Environment

- All conponents in one container
- Host memory capacity: 16G
- Container memory capacity: 8G


### Happened

```
mysql root@127.0.0.1:INFORMATION_SCHEMA> SELECT TYPE, INSTANCE, DEVICE_TYPE, DEVICE_NAME, JSON_OBJECTAGG(NAME, VALUE) AS JSON_VALUE FROM `CL
                                         USTER_LOAD` WHERE DEVICE_TYPE = 'memory' && DEVICE_NAME = "virtual" GROUP BY TYPE, INSTANCE, DEVICE
                                         _TYPE, DEVICE_NAME\G
***************************[ 1. row ]***************************
TYPE        | pd
INSTANCE    | 127.0.0.1:2379
DEVICE_TYPE | memory
DEVICE_NAME | virtual
JSON_VALUE  | {"free": "5920423936", "free-percent": "0.37", "total": "16178434048", "used": "10258010112", "used-percent": "0.63"}
***************************[ 2. row ]***************************
TYPE        | tiflash
INSTANCE    | 127.0.0.1:3930
DEVICE_TYPE | memory
DEVICE_NAME | virtual
JSON_VALUE  | {"free": "248238080", "free-percent": "0.02", "total": "16178434048", "used": "10290814976", "used-percent": "0.64"}
***************************[ 3. row ]***************************
TYPE        | tidb
INSTANCE    | 127.0.0.1:4000
DEVICE_TYPE | memory
DEVICE_NAME | virtual
JSON_VALUE  | {"free": "5920423936", "free-percent": "0.37", "total": "16178434048", "used": "10258010112", "used-percent": "0.63"}
***************************[ 4. row ]***************************
TYPE        | tikv
INSTANCE    | 127.0.0.1:20160
DEVICE_TYPE | memory
DEVICE_NAME | virtual
JSON_VALUE  | {"free": "247586816", "free-percent": "0.03", "total": "8589934592", "used": "9753706496", "used-percent": "1.14"}
```


### Summary

|         | Memory Free    | Memory Capacity | Memory Usage |
| ------- | -------------- | --------------- | ------------ |
| TiDB    | Host Available | Host            | Host         |
| TiKV    | Host Free      | Container       | Host         |
| TiFlash | Host Free      | Host            | Host         |
| PD      | Host Available | Host            | Host         |
