### ISSUE TITLE
TiKV cannot send KMS request

### ISSUE THREAD

**Issue by hunterlxt** [tikv/tikv#9541]
### What version of TiKV are you using?
master

### What operating system and CPU are you using?
ubuntu 20.04

### Steps to reproduce
1. set up kms server such as localstack (https://github.com/localstack/localstack.git)
2. create tikv config
```
[security.encryption.master-key]
type = "kms"
key-id = "8c929cbb-b3b6-432a-b091-67f742be0666"
endpoint = "http://localhost:4566"
region = "us-east-1"

[security.encryption]
data-encryption-method = "aes256-ctr"
data-key-rotation-period = "7d"
```
3. try to run pd-server and tikv-server
```
./bin/pd-server --name=pd --data-dir=pd --client-urls="http://127.0.0.1:2379" --peer-urls="http://127.0.0.1:2380" --initial-cluster="pd=http://127.0.0.1:2380" --log-file=pd.log
./bin/tikv-server --pd-endpoints="127.0.0.1:2379" --addr="172.16.111.10:20160" --data-dir=tikv --log-file=tikv.log --config="tikv.toml"
```
4. view the tikv.log and found kms request error due to timeout.

### What did you expect?
access kms service correctly.

use awslocal to test and found the service is enabled. And I created a real kms key to test, got same problem.

**Comment by hunterlxt** [comment]
@gregwebs I tested using a real KMS key, maybe something is wrong with my steps

**Comment by gregwebs** [comment]
> @gregwebs I tested using a real KMS key, maybe something is wrong with my steps

What does this mean? Was this test successful? Was it against AWS rather than localstack?

I have verified that master works against localstack as per the CONTRIBUTING instructions on both Mac and WSL Ubuntu Linux.

A timeout error means that the KMS endpoint is never reached. Can you add a log statement to log the url that is being used?

**Comment by hunterlxt** [comment]
> > @gregwebs I tested using a real KMS key, maybe something is wrong with my steps
> 
> What does this mean? Was this test successful? Was it against AWS rather than localstack?
> 
> I have verified that master works against localstack as per the CONTRIBUTING instructions on both Mac and WSL Ubuntu Linux.
> 
> A timeout error means that the KMS endpoint is never reached. Can you add a log statement to log the url that is being used?

I got the key-id from `https://aws.amazon.com/` and got same error from tikv.log.
I followed your instructions but failed.
curl operations:
```
sudo docker-compose up
localstack_main | 2021-01-26T05:27:20:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /", target header "", auth header "", data "b''"
```
```
curl http://localhost:4566
{"status": "running"}%
```

**Comment by gregwebs** [comment]
What is the exact error in the tikv.log? I have tested the KMS code based off of mater on Mac, Windows with WSL, and Linux (the latter both using Ubuntu) and I do not get a timeout error (testing both localstack and real AWS). Have you tested on a different machine?

This issue seems to imply that there is a regression on master from prior releases. Have you tested your setup with a prior release?

**Comment by hunterlxt** [comment]
I referenced https://docs.pingcap.com/tidb/dev/encryption-at-rest and https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md#testing-aws but i didn't set credentials in my environment. And tikv log didn't show the root cause.

**Comment by gregwebs** [comment]
Can you approve my PR that adds instructions for the credentials? https://github.com/tikv/tikv/pull/9599

If there are error messages we don't understand we should try to spend a little time improving the error messages. Error messages end up as the user interface for end users.

**Comment by hunterlxt** [comment]
> Can you approve my PR that adds instructions for the credentials? #9599
> 
> If there are error messages we don't understand we should try to spend a little time improving the error messages. Error messages end up as the user interface for end users.

Yeah, it just shows "kms request timeout" but no reason
