### ISSUE TITLE
When I compile the tikv master branch, the following error appears

### ISSUE THREAD

**Issue by newHE3DBer** [tikv/tikv#9557]
## Question
tikv master banch, cargo 1.49.0-nightly  ,rustup 1.23.1
When I compile the tikv master branch, the following error appears：
Caused by:
  the `registry.index` config value is no longer supported
  Use `[source]` replacement to alter the default index for crates.io.

**Comment by BusyJay** [comment]
This should be caused by your local outdated configuration. Please check the file ~/.cargo/config and https://doc.rust-lang.org/cargo/reference/source-replacement.html.

**Comment by newHE3DBer** [comment]
Can you tell me the version of rust and cargo when compiling tikv in master branch。

**Comment by newHE3DBer** [comment]
I configured the file ~/.cargo/config, and then this problem occurred. I suspect that the version of cargo is incompatible with the rust version

**Comment by BusyJay** [comment]
The version is written in rust-toolchain in the root of the TiKV source, and will be used by cargo automatically.
