### ISSUE TITLE
Bench and upgrade to zstd 1.4.8

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/tikv#9601]
## Development Task

Zstd introduce performance improvement since 1.4.7. We need to benchmark and upgrade to the latest version: https://github.com/facebook/zstd/releases We are currently on 1.4.4: https://github.com/tikv/rust-rocksdb/blob/master/librocksdb_sys/Cargo.toml#L15

**Comment by ZhenhanGong** [comment]
related PR: https://github.com/tikv/rust-rocksdb/pull/610

**Comment by yiwu-arbug** [comment]
done
