### ISSUE TITLE
Support the TTL for rawkv

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#9612]
## Development Task

Currently, TiKV doesn't support TTL feature, so some users who use rawkv directly need to implement the TTL logic on the applications side, like https://github.com/tikv/tikv/issues/3337. 

To make TiKV self productization, we're planning to support TTL for rawkv with demands:
- Every key can have different TTLs or non-TTL
- When a key-value exceeds the TTL, it doesn't mean the storage space is recycled, but TiKV promises that it can't be read from raw API.
- It provides linearizability within the clock gap among different TiKV nodes. Namely, once the key-value is invalid on the leader, it can't be read out from the followers or the new leader.
- TTL doesn't provide backward compatibility with origin rawkv.

## Design

Rocksdb provides TTL support natively, but it has some limitations so that we won't utilize it to support rawkv TTL.

The key point of the design to store TTL information somewhere so the key-value can be filtered on read or compaction. Like rocksdb, we decide to append the expiration time to the end of values.

With that, the write path changes are:
- user calls tikv-client's raw API with the TTL parameter
- TiKV calculated the expire timestamp by `current unix timestamp + TTL`(if is non-TTL kvs, the expire timestamp would be 0), and appends as 8 bytes to the value at `storage` level so that `raftstore` has no knowledge about TTL. 

Kvs invalidate on compactions:
- Add CompactionFilter to filter the kvs that `current unix timestamp > kv's expire timestamp`
- Some SSTs are not compacted for a long time. To make the storage space is recycled in time, add TTL related properties of SST and check them periodically to manual compact the invalided SSTs.

And last, strip the expiration timestamp on the read path.

### API changes
- [x] proto changes https://github.com/pingcap/kvproto/pull/712
- [x] Add TTL parameter for go-client
- [x] Add TTL parameter for java-client

### TiKV changes 
- [x] Add TTL compaction filter https://github.com/tikv/tikv/pull/9757
- [x] Add TTL properties collector https://github.com/tikv/tikv/pull/9756
- [x] Add TTL checker
- [x] Append expiration timestamp on write
- [x] Strip expiration timestamp on read https://github.com/tikv/tikv/pull/9758
- [x] Do compatibility check on start
- [x] Add metrics

**Comment by duduainankai** [comment]
I would like to help if you don't mind.

**Comment by Connor1996** [comment]
@duduainankai Sorry for not referring to the PRs. The implementation of TiKV is almost done. You can add support for the clients if you want.

**Comment by duduainankai** [comment]
@Connor1996 Sure. Any related issues exist?

**Comment by Connor1996** [comment]
No, that's all for it. For clients, just to add a TTL option for put API.

**Comment by duduainankai** [comment]
Got. But it seems the proto changes are still not merged.

**Comment by Connor1996** [comment]
It will be merged when the whole implementation is steady. Though you can send PR based on the draft now.
