### ISSUE TITLE
slack invitation link in README.md is expired

### ISSUE THREAD

**Issue by cfeitong** [tikv/tikv#9636]
Get this message when I am trying to click the slack link in README.md.
```
Invitation expired
It looks like you’re trying to accept an invitation, but the link was deactivated.

Contact the person who originally invited you about getting a new link or manually inviting you.
```
Is that link broken or it dones't work for me only?

**Comment by skyzh** [comment]
Maybe @WT-Liu could help?

**Comment by WT-Liu** [comment]
> Maybe @WT-Liu could help?

@cfeitong I have sent invitation through Gmail and will check after the holiday! Thanks!
