### ISSUE TITLE
pd connection is reconnecting every 10 minutes

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#9690]
## Bug Report

#7028 adds a new behavior that reconnecting PD leader every 10 minutes. The motivation is avoiding unavailability during pd member changes without restarting TiKV. However, the implementation reconnecting PD unconditionally, which can drop all pd region heartbeats every 10 minutes. If hibernate region is enabled, it can make scheduler ops from PD working very slowly.

PD doesn't need to be reconnected if memberships are the same.

Perhaps related to #9681.

**Comment by NingLin-P** [comment]
Instead of reconnecting every 10m, maybe it is better to attach the PD member list to `StoreHeartbeatResponse` when the list is changed so that TiKV can update its PD member list within about 10s (much shorter than 10m).

**Comment by BusyJay** [comment]
Coupling `StoreHeartbeatResponse` and PD client doesn't seem a good idea to me.

**Comment by xuhui-lu** [comment]
@BusyJay hey jay, is there anyone taking this issue already? Or is there anything I could help with? I am interested in this one, and glad to help if possible.

**Comment by BusyJay** [comment]
Thank you @xuhui-lu. I don't think anyone is working on this. If you have any questions, you can ask me in the issue or at our [slack](https://github.com/tikv/tikv#slack).

**Comment by BusyJay** [comment]
@xuhui-lu Hi, we are supposing to freeze code by this Friday for next major release, and I want to land the bugfix by then. So I sent a patch for this issue. Sorry for the duplicated work.

There are still some [issues](https://github.com/tikv/tikv/issues?q=is%3Aopen+is%3Aissue+label%3Astatus%2Fhelp-wanted) that are not urgent you can have a try.

**Comment by MimeLyc** [comment]
REFRESH
