### ISSUE TITLE
Async snapshot may take long time if replica read is used with hibernate region

### ISSUE THREAD

**Issue by cfzjywxk** [tikv/tikv#9713]
### What version of TiKV are you using?

v5.0-rc release

### What operating system and CPU are you using?

Using the i3.4xl on aws, a tikv-server on a single machine.

### Steps to reproduce

Simple read/write requests like:
- Read. Table range scan using prefix clustered index.
- Write. Simple update serveral keys per transaction.

Enable the hibernate region feature(which is default enabled on master or v5.0-rc).
Using the follower-read in the client for each session.

### What did you expect?
The latency and qps are expected.

### What did happened?
Sometimes latency are very high, especially for the async-snapshot duration, while other metrics look good, there are just a few regions and load is not high.
![image](https://user-images.githubusercontent.com/3692139/109128845-deacf080-778a-11eb-9058-8aa77ce1b983.png)

@BusyJay has helped to analyze this phenomenon.
I believe it’s related to follower read and hibernate regions. According to the logs, one of the timeout requests is trying to request a peer of region 3848 (you can find such logs by searching error-response and looking around the context). The peer happens to be leader just before the error log. And it’s the first time it becomes leader, so the timeout request has to be accepted when it’s still follower. So TiDB should be using follower/replica read. A replica can execute read when when it has applied to the index returned by leader. I notice that hibernate region is enabled in configuration file, which can prevent leader from broadcasting its commit logs, and possibly lead to this problem. There is only a few regions in the cluster, I suggest to disable hibernate regions instead. And TiDB may also need to investigate if it’s expected to send a follower read request to a TiKV instance. As far as I known, only tiflash should accept follower read and it will keep polling unfinished requests.

- Make these two features work well together.
- Record the wait duration applying to the expected index.

**Comment by BusyJay** [comment]
There should be three metrics can be collected:
- how many replica reads are served
- how many reads/proposals waiting in queue
- how long do reads/proposals waiting in queue after they are committed before they are applied, aka apply wait time of read requests

We need a release plan for generic replica read.

**Comment by cfzjywxk** [comment]
After disabling the hibernate region, the `async snapshot duration` could still be very high, leading to the high wait duration of coprocessor requests. 
After disabling the replica-read too, this phenomenon seems disppeared. It's still needed to trace the root cause and add related metrics, and as @BusyJay has said, we may need a release plan for generic replica read.

**Comment by cfzjywxk** [comment]
@coocood has taked a look at this, it's possible not related to the 1pc usage and related memory lock checks refactored for replica read in https://github.com/tikv/tikv/pull/8926. The user does use 1pc to commit the transactions.
