### ISSUE TITLE
Lease check should consider tick count

### ISSUE THREAD

**Issue by BusyJay** [tikv/tikv#9728]
## Bug Report

To guarantee lease correctness, follower should not start elections or accept vote request when with in lease. Inside raft, lease is counted by tick count, which is not accurate, the error range is within 1 tick. For example, if a tick interval is 2s, election timeout is 5 ticks, lease is also 2s * 5 = 10s. A follower is scheduled to tick at time 3:00, and leader's message arrives at 2:59, which reset its tick count to 0, so the follower may start election at 3:08. But leader expects its lease last till 2:59 + 10s = 3:09.

The correct check should ensure lease duration should not larger than election timeout - 1 tick. The default value follows the rule but we need a safe check when validating custom configuration.

**Comment by seiya-annie** [comment]
Probability appears when election timeout time == lease time

**Comment by TszKitLo40** [comment]
Can I try this issue?

**Comment by BusyJay** [comment]
Sure!

**Comment by TszKitLo40** [comment]
If I have any questions, can I ask help from you in slack? @BusyJay

**Comment by TszKitLo40** [comment]
I am doubt that why the follower may start election at 3:08? @BusyJay

**Comment by BusyJay** [comment]
> If I have any questions, can I request for help from you in slack? @BusyJay

Of course yes.

>  it is just 4 ticks since 3:00.

Because the follower is scheduled to tick at 3:00, so at 3:00, it will increase the tick from 0 to 1. Following ticks will be scheduled at 3:02, 3:04, 3:06, 3:08, and the tick will increase to 2, 3, 4, 5 respectively. It can start election or approve vote request at tick 5.
