### ISSUE TITLE
The propose time may be smaller than the real one

### ISSUE THREAD

**Issue by gengliqi** [tikv/tikv#9748]
### What version of TiKV are you using?
master

### What operating system and CPU are you using?
doesn't matter

### Steps to reproduce
doesn't matter

### What did you expect?
right propose time

### What did happened?
https://github.com/tikv/tikv/blob/311515d67331dee4bf1f34ebeb6200bd6061f711/components/raftstore/src/store/peer.rs#L104-L107
If the `idx` is got from `back.binary_search_by_key(&key, map)`, the `self.queue[idx]` is not the one we want.
The underlying data structure of `VecDeque` is a ring buffer. So if it's the back slice, the `idx` should add the length of front slice.
As an alternative, we can use the `VecDeque's binary_search_by_key` function though it's not stable yet.

Luckily, this bug can not lead to serious consequences because it may only return the smaller `propose time`.
As a result, it may cause a smaller `commit log duration` and `maybe_renew_leader_lease` will use this smaller one to update lease which doesn't break correctness.

**Comment by NingLin-P** [comment]
Thanks! @gengliqi , https://github.com/tikv/tikv/pull/9754 will fix it.
