### ISSUE TITLE
Check overflow in timestamp computation

### ISSUE THREAD

**Issue by youjiali1995** [tikv/tikv#9771]
## Development Task
[`TimesStamp`](https://github.com/tikv/tikv/blob/master/components/txn_types/src/timestamp.rs#L8) is an u64 integer. There are some places where TiKV increases or decreases it but TiKV doesn't check overflow. Overflow can result in an infinite loop. Even if it's not possible to happen in theory, it's better to check it.

**Comment by TszKitLo40** [comment]
Can I try this issue?

**Comment by youjiali1995** [comment]
Of course.

**Comment by TszKitLo40** [comment]
I can't find `TimesSamp` in the TiKV project. @youjiali1995 Can you please tell me where the position of it is?

**Comment by youjiali1995** [comment]
Sorry, I don't make it clear. There are some places an overflow can occur, for example. https://github.com/tikv/tikv/blob/144393ec515db2880b2566c33305638d43073bee/src/storage/txn/commands/mod.rs#L412

You should check all places and try your best to make code changes small and ergonomic. 😃 @TszKitLo40

**Comment by TszKitLo40** [comment]
> Sorry, I don't make it clear. There are some places an overflow can occur, for example.
> 
> https://github.com/tikv/tikv/blob/144393ec515db2880b2566c33305638d43073bee/src/storage/txn/commands/mod.rs#L412
> 
> You should check all places and try your best to make code changes small and ergonomic. 😃 @TszKitLo40

In this case, what should be `prev()` return? If it is 0, should it return 0? Otherwise it may return -1.

**Comment by youjiali1995** [comment]
You can use [`checked_add`](https://doc.rust-lang.org/std/primitive.u64.html#method.checked_add). When an overflow occurs, it returns `None`.

I can't make sure there is a unified way to handle all overflow cases. It may break the loop, return an error or sth else.

**Comment by TszKitLo40** [comment]
I have also considered using `checked_add`, but the function like `prev` will return `Timestamp` instead of `Option`. If `Option` is returned, it seems that all the place where `Timestamp` is used will have to be changed.

**Comment by youjiali1995** [comment]
> I have also considered using `checked_add`, but the function like `prev` will return `Timestamp` instead of `Option`. If `Option` is returned, it seems that all the place where `Timestamp` is used will have to be changed.

There aren't many places using `prev`/`next`/`incr`/`desc`, but the target is to try our best to make code changes small and ergonomic.

**Comment by TszKitLo40** [comment]
> > I have also considered using `checked_add`, but the function like `prev` will return `Timestamp` instead of `Option`. If `Option` is returned, it seems that all the place where `Timestamp` is used will have to be changed.
> 
> There aren't many places using `prev`/`next`/`incr`/`desc`, but the target is to try our best to make code changes small and ergonomic.

So do you think we should change `Timestamp` to `Option<Timestamp>`?
