### ISSUE TITLE
Raftstore GC snapshot calculates crc32 which is useless and causes unnecessary IO

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/tikv#9786]
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

\-

### Steps to reproduce

Not sure if there's any simple way to reproduce, but it may happen when there are too many stale generated snapshot files to ge GCed

### What did you expect?

The cluster runs normally and the stale generated snapshot files are deleted normally.

### What did happened?

The raftstore threads consumes too much IO, which makes the cluster's performance is bad and nearly unable to serve.

Here's a sample flame graph when the issue happens:
![image-2021-02-19-16-11-20-127](https://user-images.githubusercontent.com/9948422/110748190-55151c80-827a-11eb-85e4-71b7dadfedbe.png)

**Comment by hicqu** [comment]
Closed by https://github.com/tikv/tikv/pull/9669.
