### ISSUE TITLE
There is no limit to reconnect with PD

### ISSUE THREAD

**Issue by HunDunDM** [tikv/tikv#9799]
### What version of TiKV are you using?

```
Release Version:   5.0.0-rc.x
Edition:           Community
Git Commit Hash:   2d3c66cc44ea19a4e339ec44cf1fcd1477555b7d
Git Commit Branch: master
UTC Build Time:    2021-02-08 09:58:47
Rust Version:      rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb
Profile:           dist_release
```

### Steps to reproduce

* Large-scale cluster
* For some reasons, PD does not have a leader

### What did you expect?

* TiKV performs the backoff strategy normally and waits for PD to recover.

### What did happened?

* Each Region heartbeat triggers a reconnection with PD. A large number of regions triggers similar DDoS attacks on PD. PD cannot be recovered.
* `[INFO] [util.rs:396] ["connecting to PD endpoint"]` Thousands of times per second.

**Comment by coocood** [comment]
Does 4.0 has this issue?

**Comment by HunDunDM** [comment]
> Does 4.0 has this issue?

yes
