### ISSUE TITLE
coprocessor IN expr not handle max_u64 properly

### ISSUE THREAD

**Issue by guo-shaoge** [tikv/tikv#9821]
### What version of TiKV are you using?
    TiKV
    Release Version:   5.0.0-rc.x
    Edition:           Community
    Git Commit Hash:   eca434da4e71d540f7201203d10bf078d2ece853
    Git Commit Branch: master
    UTC Build Time:    2021-02-24 08:22:44
    Rust Version:      rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)
    Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
    Profile:           debug

### What operating system and CPU are you using?

    AMD Ryzen 5 PRO 4650U with Radeon Graphics

### Steps to reproduce

Copr bug, use following SQL can reproduce [TiDB issue](https://github.com/pingcap/tidb/issues/23198)

    use test;
    drop table if exists t;
    create table t (a int);
    insert into t values(-1);
    select * from t where a in(18446744073709551615, 1);

### What did you expect?
empty set
### What did happened?
    select a from t where a in(18446744073709551615, 1);
    +-----+
    | a   |
    |-----|
    | -1  |
    +-----+

**Comment by jebter** [comment]
This bug has not been fixed in 5.0
