### ISSUE TITLE
enlarge the upper limitation for space reserving

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#9831]
## Development Task

https://github.com/tikv/tikv/pull/9497 introduces a complex strategy for space reserving. The upper limitation is `20GB`, which is proved to be not enough exactly.

So we need to enlarge the upper limitation, seems `max(config.reserve-space, 0.05 * capacity)` is OK. It means for a 4T disk, 80GB will be reserved.

**Comment by BusyJay** [comment]
Why `20GB` is not enough while `80GB` will be enough?

**Comment by JaySon-Huang** [comment]
1. Why do we need to reserve such a large amount of space?
2. Can we limit the max space in a test environment?
