### ISSUE TITLE
Tikv node gets stuck

### ISSUE THREAD

**Issue by salarali** [tikv/tikv#9852]
## Bug Report

I have a tidb cluster. Periodically, one of the tikv nodes get stuck. I see these errors in the log. I have replaced tikv nodes, but the same error then appears in other nodes. I have to keep restarting the nodes once they get into this state.

```
tikv-server[31056]: [2021/03/19 06:58:28.267 +00:00] [INFO] [kv.rs:577] ["batch_raft RPC is called, new gRPC stream established"]
tikv-server[31056]: [2021/03/19 06:58:28.276 +00:00] [ERROR] [kv.rs:597] ["dispatch raft msg from gRPC to raftstore fail"] [err=RaftServer(Transport(Full))]
tikv-server[31056]: [2021/03/19 06:58:28.276 +00:00] [ERROR] [kv.rs:603] ["KvService::batch_raft send response fail"] [err=RemoteStopped]
```

### What version of TiKV are you using?
```
Release Version:   4.0.11
Edition:           Community
Git Commit Hash:   4ac5e7ea1839d63163e911e2e1164d663f49592b
Git Commit Branch: HEAD
UTC Build Time:    2021-02-26 07:42:27
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc mem-profiling portable protobuf-codec
Profile:           dist_release
```

### What operating system and CPU are you using?

Amazon Linux 2, c6g instances

### Steps to reproduce

None

**Comment by NingLin-P** [comment]
hi @salarali, what is the value of `raftstore.store-pool-size` config, and how many regions on a tikv node?

**Comment by salarali** [comment]
Around 16k regions per tikv node and `raftstore.store-pool-size` is set to 2.

I did find out that this issue was only happening on the arm graviton nodes on aws. Once I moved to intel nodes, this issue was not happening.

**Comment by NingLin-P** [comment]
This may cause by the `raftstore` run slowly and raft messages get pile up in the channel, could you also see the `Propose wait duration` panels in `TiKV details -> Raft propose`

**Comment by salarali** [comment]
I do see high times.
![image](https://user-images.githubusercontent.com/1452840/113372317-62cc3800-9336-11eb-9d2f-4588204ee043.png)


Another thing I see is iotop at 99%.

```
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
15045 be/4 root        0.00 B/s   19.62 K/s  0.00 % 99.99 % tikv-server --config=/etc/tikv/tikv.toml --addr=172.30.101.117:2016 --status-addr=172.30.101.117:2018 --pd=172.30.101.155:2379 [apply-0]
14891 be/4 root        0.00 B/s   19.62 K/s  0.00 % 99.99 % tikv-server --config=/etc/tikv/tikv.toml --addr=172.30.101.117:2016 --status-addr=172.30.101.117:2018 --pd=172.30.101.155:2379 [rocksdb:high0]
15041 be/4 root        0.00 B/s  439.56 K/s  0.00 % 99.99 % tikv-server --config=/etc/tikv/tikv.toml --addr=172.30.101.117:2016 --status-addr=172.30.101.117:2018 --pd=172.30.101.155:2379 [raftstore-10357]
```

**Comment by salarali** [comment]
This issue was "probably" caused by an IO regression in the aws linux 2 kernel. Amazon Linux 2.0.20210326.0 Update fixed the issue. Updating the kernel has fixed the issue was us.

Increasing the `vm.diry_ratio` did alleviate the issue for a while on the "bugged" kernel.
