### ISSUE TITLE
test_node_failed_merge_before_succeed_merge could fail

### ISSUE THREAD

**Issue by hicqu** [tikv/tikv#9853]
## Question

PTAL https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/45110/nodes/203/steps/694/log/?start=0.

**Comment by LykxSassinator** [comment]
This issue has become out-of-date. Given that no further feedback regarding this issue has been reported, it can be safely closed.
