### ISSUE TITLE
raftstore: leader may not send snapshot to the follower

### ISSUE THREAD

**Issue by NingLin-P** [tikv/tikv#9859]
### What version of TiKV are you using?

5.0-rc, master

The leader will be triggered to generates snapshot for a follower in two places: 

https://github.com/tikv/tikv/blob/f02f492614c10d1cdffce8e0214feef15ce521f0/components/raftstore/src/store/peer.rs#L1662-L1671

https://github.com/tikv/tikv/blob/f02f492614c10d1cdffce8e0214feef15ce521f0/components/raftstore/src/store/peer.rs#L1881-L1886

The first place will not enter if the region has a `Ready`,  and the latter one will also not enter if the `Ready` has not committed entries because it is inside `handle_raft_committed_entries` and:
https://github.com/tikv/tikv/blob/f02f492614c10d1cdffce8e0214feef15ce521f0/components/raftstore/src/store/peer.rs#L1729-L1731

**Comment by BusyJay** [comment]
Why 4.0.x is safe?

**Comment by gengliqi** [comment]
> Why 4.0.x is safe?

Because the function name of `handle_raft_committed_entries` in 4.0 is `handle_raft_ready_apply`, which is always called after getting ready.

**Comment by ilovesoup** [comment]
Does this affect learner?

**Comment by NingLin-P** [comment]
> Does this affect learner?

Yes, it will affect learner.
