### ISSUE TITLE
Store used size changes a lot after restarting

### ISSUE THREAD

**Issue by Connor1996** [tikv/tikv#9896]
### What version of TiKV are you using?

```
Release Version:   5.0.0-rc.x
Edition:           Community
Git Commit Hash:   34d72b137a3eeadbcb444613a32763e0cfa5c084
Git Commit Branch: heads/refs/tags/v5.0.0-nightly
UTC Build Time:    2021-03-17 03:10:24
Rust Version:      rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

### What operating system and CPU are you using?

Not related 

### Steps to reproduce

Run some workload and the used size will increase infinitely. And do a restart, the used size will be normal again.

### What did you expect?
the store used size is close to store size

### What did happened?
<img width="928" alt="截屏2021-03-25 下午7 55 10" src="https://user-images.githubusercontent.com/13497871/112469394-66931400-8da4-11eb-9c6f-3aa5b2fbda24.png">

From PD metrics, store used size changes a lot after restarting which is reported from TiKV side.
TiKV calculates store used size by adding snapshot total size and engine used size.

<img width="1231" alt="截屏2021-03-25 下午7 55 27" src="https://user-images.githubusercontent.com/13497871/112469553-94785880-8da4-11eb-8ba1-86ab49c58ea7.png">

![image](https://user-images.githubusercontent.com/13497871/112469753-cab5d800-8da4-11eb-990f-dd2d77231aa2.png)

From metrics, we can know that store size(engine used size) and disk space util doesn't changes a lot, **so it must be something wrong with snpashot total size.**

**Comment by Connor1996** [comment]
This is like https://github.com/tikv/tikv/issues/9429 but not same

**Comment by hicqu** [comment]
It's not easy to locate what's wrong for `SnapManager.snap_size`. I prefer to calculate the directory size in PD worker thread. @Connor1996 @BusyJay what do you say?

**Comment by Connor1996** [comment]
> It's not easy to locate what's wrong for `SnapManager.snap_size`. I prefer to calculate the directory size in PD worker thread. @Connor1996 @BusyJay what do you say?

I notice that `snap_size` is used in `get_snapshot_for_building` too

**Comment by hicqu** [comment]
Bench shows that iterating a directory with 100000 entries and fetching metadata for them all needs about **150ms**:
```
running 1 test
test bench_iter_dir ... bench: 158,881,406 ns/iter (+/- 25,386,574)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured; 0 filtered out; finished in 48.40s
```

The code is like
```rust
fn create_tmpfiles(dir_name: &str) {
    for i in 0..100000 {
        let file_name = format!("temp_{:06}", i);
        let path = Path::new(dir_name).join(file_name);
        println!("creating {:?}", path);
        OpenOptions::new()
            .create(true)
            .write(true)
            .open(&path)
            .unwrap();
    }
}

#[bench]
fn bench_iter_dir(bench: &mut Bencher) {
    bench.iter(|| {
        for entry in fs::read_dir("temp-dir").unwrap() {
            let x = entry.unwrap().metadata().unwrap();
            drop(x);
        }
    });
}
```

**Comment by BusyJay** [comment]
Have you confirmed `snap_size` is the root cause?

**Comment by hicqu** [comment]
Both @Connor1996 and me think so based on

* PD just shows `StoreState.used_size` in metrics, there should be nothing wrong.
* TiKV posts `get_total_snap_size() + engine.get_size()` to PD, and `engine.get_size()` is not wrong.

**Comment by BusyJay** [comment]
How about adding a log to verify it directly before thinking about fixes?
