### ISSUE TITLE
the rule for TiKV_GC_can_not_work alert should be enhanced to check with GC speed instead of GC task

### ISSUE THREAD

**Issue by seiya-annie** [tikv/tikv#9910]
## Bug Report

ctive Since	Value
alertname="TiKV_GC_can_not_work" env="ENV_LABELS_ENV" expr="sum(increase(tikv_gcworker_gc_tasks_vec{task="gc"}[1d])) < 1" level="emergency"	FIRING	2021-03-27 15:10:06.568417073 +0000 UTC

sometimes, the system maybe has not update or delete record, should not triggered this alert.

### What version of TiKV are you using?
v5.0.0

**Comment by sticnarf** [comment]
#10661 fixes similar false-positive problems.
