### ISSUE TITLE
Core client proposal

### ISSUE THREAD

**Issue by tisonkun** [tikv/tikv#9922]
## Background

So far, there are several client implementations of TiKV.

- https://github.com/tikv/client-c
- https://github.com/tikv/client-cpp
- https://github.com/tikv/client-go
- https://github.com/tikv/client-java
- https://github.com/tikv/client-py
- https://github.com/tikv/client-rust
- Java Client inside TiSpark https://github.com/pingcap/tispark/tree/master/tikv-client
- Go Client inside TiDB https://github.com/pingcap/tidb/tree/master/store/tikv

Many of them support  a subset of features and only Go Client inside TiDB implements all features required by TiDB.

Since TiKV client consists of complex logics especially transaction related code, implementing them from implementation to implementation is ridiculous for both development burden and repetitive bug shooting.

I propose to investigate other multilingual SDK implementation strategy and heal our current situation.

For example, we can learn from gRPC who at first maintains only [C++](https://github.com/grpc/grpc/) / [Go](https://github.com/grpc/grpc-go) / [Java](https://github.com/grpc/grpc-java) core(full-featured) implementation. Other implementations such as Python / C# / Kotlin / Node are all based on these core implementations. Also as the community grown, they can implement their native one like [Swift](https://github.com/grpc/grpc-swift), see also [the deprecation note](https://github.com/grpc/grpc-swift/blob/cgrpc/DEPRECATION.md).

## Stage

cc @c4pt0r @leiysky @andylokandy

**Comment by tisonkun** [comment]
@andylokandy you can attach the stage information here or just edit section section in the description. I'll take care of the design document side the next two weeks.

**Comment by andylokandy** [comment]
FYI, here is the discussion about Rust Client roadmap in 2021Q2Q3: https://github.com/tikv/client-rust/discussions/272

**Comment by tisonkun** [comment]
Closed as no more activities. We do have several clients for multiple languages, though.
