### ISSUE TITLE
Too many compaction pending bytes when truncating a huge table in TiDB

### ISSUE THREAD

**Issue by ekexium** [tikv/tikv#9936]
### What version of TiKV are you using?

5.0 nightly

### What operating system and CPU are you using?

Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz

### Steps to reproduce

Truncate a large table (about 2.3T) in TiDB. The store size reduced about 18T.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/31720476/113137522-3988aa80-9257-11eb-9093-50f8213ad564.png">

### What did you expect?

There shouldn't be many compaction pending bytes, according to @5kbpers 

### What did happened?

There are about 4.5T compaction pending bytes, which causes write stall.
<img width="921" alt="image" src="https://user-images.githubusercontent.com/31720476/113137706-78b6fb80-9257-11eb-8da7-cd97066c8889.png">

<img width="1884" alt="image" src="https://user-images.githubusercontent.com/31720476/113137651-62a93b00-9257-11eb-837e-6a22ae89c482.png">

**Comment by zhangjinpeng1987** [comment]
I guess that deleting a lot of sst files by DeleteFilesInRange may cause the LSM tree into a strange shape, and in the abnormal shape, the way of calculating pending compaction bytes may not work well.

**Comment by Connor1996** [comment]
Close by https://github.com/tikv/tikv/pull/10978

The PR avoids the write stall after table drop though compaction pending bytes still change dramatically(it's as expected and just a statistics)
