### ISSUE TITLE
document and recommend try TiKV with TiUP

### ISSUE THREAD

**Issue by tisonkun** [tikv/tikv#9937]
Update README to document and recommend try TiKV with TiUP, both start a release version or binary version built from source.

I'll try to take care of it this week.

**Comment by c4pt0r** [comment]
Using TiUP to deploy standalone TiKV cluster is easy. Here is an example:

1. Ensure ssh connectivity between tiup's machine and several target nodes
2.  topo.yaml:

global:
  user: "ubuntu"
  ssh_port: 22
  deploy_dir: "whatever"
  data_dir: "whatever"

pd_servers:
  - host: x.x.x.x
  - host: y.y.y.y
  - host: z.z.z.z

tikv_servers:
  - host: x.x.x.x
  - host: y.y.y.y
  - host: z.z.z.z

monitoring_servers:
  - host: a.a.a.a

grafana_servers:
  - host: b.b.b.b

alertmanager_servers:
  - host: c.c.c.c



3. $ tiup cluster deploy foobar v4.0.0 ./topo.yaml --user ubuntu -i ~/.ssh/id_rsa
4. $ tiup cluster start foobar
5. You're all set!

**Comment by tisonkun** [comment]
Thanks for your input @c4pt0r ! I think it can be a paragraph on setting up cluster deployment. However, for the beginner journey a local setup is more appreciated. It seems tiup itself doesn't support well yet and here is [the improvement ticket](https://github.com/pingcap/tiup/issues/1269).

I will create a pull request this week rephrase the "Try TiKV" paragraph and link it to your input above while putting your into doc folder. It is somewhat advanced topic, anyway.
