### ISSUE TITLE
Cherry-pick recent CDC changes to release-4.0 branch

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#9964]
## Development Task

Ensure all bugfix commits in the release-5.0 branch are cherry-picked to release-4.0 https://github.com/tikv/tikv/commits/release-5.0/components/cdc/src

**Comment by asddongmen** [comment]
I have checked the following commits (commits after Jan 22, 2021)：

1. 515df8d
2. 58c9c5e
3. eca434d
4. bbc6bff
5. ffd6812
6. cfd7840
7. df3b405

Among them, the 1、2、5、6、7 th commits have been confirmed by the authors that they do not need to be  Cherry-pick to the 4.0.0 branch.

The 2th commit's  author said whether this commit will be Cherry-pick to release 4.0.0 depends on whether it will affect subsequent fixes.

The 3th commit is not important ,  so there is no need to merge to version 4.0.0.

My conclusion is that there are no bug fixes that need to be Cherry-pick to release 4.0.0 after Jan 22, 2021.
