### ISSUE TITLE
CDC endpoint thread CPU usage 100% with insert 800ops

### ISSUE THREAD

**Issue by overvenus** [tikv/tikv#9981]
### What version of TiKV are you using?

tikv v4.0.6
ticdc v4.0.9

### Steps to reproduce

Creates a changefeed with old value, and executes 800ops insertion in upstream TiDB. 

### What did you expect?

CPU usage should be no more than 50%.

**Comment by seiya-annie** [comment]
/serverity/bug

**Comment by seiya-annie** [comment]
/severity/critical

**Comment by overvenus** [comment]
Reproduced with sysbench prepare

```
sysbench --db-driver=mysql --mysql-host=172.16.5.33 --mysql-port=47904 --mysql-user=root \
    --time=15000 --report-interval=10 --threads=64 \
    --mysql-db=test --tables=1 --table-size=6000000 oltp_write_only prepare
```

![image](https://user-images.githubusercontent.com/2150711/117748690-16ccb700-b243-11eb-9a5f-c0bd0bbbac99.png)
![image](https://user-images.githubusercontent.com/2150711/117748729-26e49680-b243-11eb-8e34-21c2513dba22.png)
![image](https://user-images.githubusercontent.com/2150711/117748753-306dfe80-b243-11eb-8330-da1fd01ba7a0.png)

Metric export and flame graph: https://gist.github.com/overvenus/d8b31c92bb7baaeb48d821d8e29326cf
