### ISSUE TITLE
Provided config-template.toml is not valid

### ISSUE THREAD

**Issue by Jibbow** [tikv/tikv#9990]
### What version of TiKV are you using?

latest `master` branch.

### What operating system and CPU are you using?

Linux, but shouldn't matter.

### Steps to reproduce

Take the provided `config-template.toml` for TiKV, strip leading `#` from all lines and use it for as a config for TiKV.

### What did you expect?
It should "just work" and be a valid config. In the ideal case, it would be identical to `TiKvConfig::default()`.

### What did happened?
Several things were wrong:

 1. after stripping away the leading `#`, the resulting toml was *not parsable*. This was mainly because *some* lines with comments used only a single `#` instead of two `##`. Only a minor issue, but still it's inconsistent.
 2. after fixing (1), the toml was parsable as a `TiKvConfig`, but it did not pass `validate()`.
 3. after fixing (2), the resuling config differed from `TiKvConfig::default()`. Maybe that's intended, but I found it rather unusual. Here is a diff (left: `config-template.toml`, right: `TiKvConfig::default()`): https://www.diffchecker.com/Et8GSSHO

If it's okay, I would create a PR with fixes for (1) and (2) and maybe (3) depending on the comments on this issue. I would also add a test to check these issues for the future.

**Comment by skyzh** [comment]
Basically the difference could be sorted into two categories: 'value tweaks' and 'default value for None'. For the former one, I think it's okay to modify the toml to match the default values in TiKV. For the latter one, we should change default value in `TiKVConfig` not to use `None` as default.

The only thing I'm unsure about is `allow_concurrent_memtable_write: true`, which is introduced by https://github.com/tikv/tikv/pull/2054/ 4 years ago. Should this be `true` or `false` for default value?

**Comment by skyzh** [comment]
https://docs.pingcap.com/tidb/stable/tikv-configuration-file#raftdb The official docs of TiKV didn't mention this config item `allow_concurrent_memtable_write`. I wonder if this item is stale

**Comment by MyonKeminta** [comment]
> https://docs.pingcap.com/tidb/stable/tikv-configuration-file#raftdb The official docs of TiKV didn't mention this config item `allow_concurrent_memtable_write`. I wonder if this item is stale.

It's a mistake introduced by https://github.com/tikv/tikv/pull/7460 which modified the default config without updating config-template.toml. And some of the configurations that are unusual to be changed are usually not documented.

**Comment by Jibbow** [comment]
Thanks for the comments @skyzh and @MyonKeminta! I opened a PR #10010 where we can further work on this issue :)
